JabRef/jabref

CHANGELOG, src/main/java/net/sf/jabref/imports/HTMLConverter.java, src/main/resources/help/About.html
Committer: Ruy Minoru Ito Takata <ruy.takata@gmail.com>
When using the "Cleanup entries" function, the special character Å should be converted to {{\AA}} to preserve the capital when generating the PDF.
=> Fix for bug #1253: Cleanup entries error 2

CHANGELOG, src/main/java/net/sf/jabref/imports/DOItoBibTeXFetcher.java, src/main/resources/help/About.html
Changes the CrossRef content negotiation method to yield more complete bibtex entries. This fixes an issue with DOI import from papers with many authors, which previously yielded truncated results.
=> Change DOI importer to use application/x-bibtex

CHANGELOG, src/main/java/net/sf/jabref/Globals.java, src/main/java/net/sf/jabref/imports/HTMLConverter.java
Tests with various accented characters were made. The result was: 
Ç ü é ã á ä à å ç ê ë è ï í ì î Ä Å É æ Æ ô ö ò û ù ÿ Ö Ü ó ú ñ Ñ Ã Á Â À Ð Ê Ë È Í Î Ï Ì Ó Ô Ò õ Õ Ú Û Ù ý Ý ø Ø ï
=> Fix for bug #919: Accents don't export to RTF

README.md, jabref-launch4j.xml
In order that the Launch4j build task works, some paths in the configuration file have to be changed.
=> Updated some paths in Launch4j configuration file

CHANGELOG, src/main/java/net/sf/jabref/BasePanel.java, src/main/java/net/sf/jabref/JabRefFrame.java, src/main/java/net/sf/jabref/JabRefPreferences.java
In addition, I would suggest to hide the toolbar by default.
=> Add entry under the 'View' menu to hide the toolbar

src/main/java/net/sf/jabref/AppearancePrefsTab.java, src/main/java/net/sf/jabref/JabRefPreferences.java, src/main/java/net/sf/jabref/gui/MainTable.java
Previously, the padding added to the row height for the main table was hardcoded.
The padding value can now be modified by the user through the preferences dialog.
The old hardcoded value is used as the default value for the new preference.
=> Added the option to change the table row height padding.

src/main/java/net/sf/jabref/JabRefPreferences.java, src/main/java/net/sf/jabref/SidePaneComponent.java, src/main/java/net/sf/jabref/SidePaneManager.java
Side pane panels now feature an up arrow button and a down arrow button immediately to the left of the close button. These buttons allow panes to be swapped with the pane above or below them, respectively.
Whenever the panes are reordered, the current position of each visible pane is recorded in the application preferences, so the user's custom ordering can be preserved when JabRef is next run.
=> Added the ability to reorder the panels in the side pane.

CHANGELOG, src/main/java/net/sf/jabref/BasePanel.java, src/main/java/net/sf/jabref/JabRefFrame.java, src/main/java/net/sf/jabref/export/FileActions.java, src/main/java/net/sf/jabref/export/SaveDatabaseAction.java
Adds a new menu option called "Save selected as plain BibTeX ...".
This option behaves the same way as the existing "Save selected as ..." option, except that the JabRef metadata and signature comment are not written to the resulting output file.
=> Add the option to save selected entries as plain BibTeX.

src/main/java/net/sf/jabref/JabRefFrame.java
The "Save selected as plain BibTeX..." menu option is now correctly enabled and disabled based on whether or not a database is currently open.
I haven't included a CHANGELOG entry, since this commit effectively just corrects a minor oversight on my behalf when adding this menu entry in [a previous pull request](https://github.com/JabRef/jabref/pull/48), but I'm happy to add one if deemed necessary.
=> Minor UI Fix: Add "Save selected as plain BibTeX..." to the list of open database-only actions.

src/main/java/net/sf/jabref/journals/JournalAbbreviations.java
Some journals put trailing space in the journal names when
exporting a bibtex citation. This causes the abbreviation
to fail. This should fix that.
=> Trim journal names before looking up the Abbreviation

CHANGELOG, src/main/java/net/sf/jabref/AdvancedTab.java, src/main/java/net/sf/jabref/JabRef.java
Now a proper error message is shown at start if the L&F is not available.
Moreover, only available L&Fs are listed in the preference window.
=> Fix for Bug #1278 Crash after changing LookAndFeel

src/main/java/net/sf/jabref/JabRefFrame.java
Moving the registration of Apple events ensures that double-clicking on a file to open it works even if JabRef is not yet running.
=> Fix double-click opening of files on Mac

CHANGELOG, build.gradle
This pull request updates all dependencies to their newest versions. 
The only dependency for which this is not possible is antlr3. Here the upgrade from 3.4 to 3.5.2 would introduce API-breaking changes.
=> Update dependencies if possible

src/main/java/net/sf/jabref/imports/INSPIREBibtexFilterReader.java
Due to a change in the html output of the INSPIRE search, JabRef was no more able to distinguish the interesting output from the rest of the page. It was due to a missing newline character.
=> fixed incompatibility with INSPIRE output page

src/main/resources/help/About.html
I replaced the information for the old SF bug tracker inside the GUI application.
Am I missing any locations? 
At the moment it is only replaced inside `About.html`.
=> Refer to new issue tracker

src/test/java/net/sf/jabref/logic/labelPattern/LabelPatternUtilTest.java
The package declaration in this class is syntactically wrong. For some reason, this does not bother gradle, which still runs the test (Eclipse, however, doesn't). This is kind of alarming, since this code should not compile.
=> Fix package declaration in LabelPatternUtilTest

src/main/java/net/sf/jabref/BibtexFields.java
The referenced XML file (`/resource/fields/fields.xml`) is not present and it is unclear how the functionality is used. Maybe some plugin needed it?
Therefore, I'm proposing to remove this functionality for now.
=> Removes functionality for additional fields via XML file

CHANGELOG, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditorTab.java
Restores the cursor resp. "caret" position when a field is store during editing.
This fixes [SF.net bug #1285](http://sourceforge.net/p/jabref/bugs/1285/).
To be done: 
- Backport to dev_2.11
- Ask for confirmation on SF.net and close the issue there.
=> Fix SF Bug #1285

src/main/java/net/sf/jabref/JabRefPreferences.java
As discussed in #164 the timestamp column shouldn't be displayed by default.
=> Timestamp is not displayed by defaut

CHANGELOG, src/main/java/net/sf/jabref/JabRefPreferences.java, src/main/java/net/sf/jabref/gui/EntryCustomizationDialog2.java, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java, src/main/java/net/sf/jabref/logic/bibtex/BibtexEntryWriter.java, src/main/java/net/sf/jabref/logic/bibtex/DuplicateCheck.java, src/main/java/net/sf/jabref/model/entry/BibLatexEntryTypes.java, src/main/java/net/sf/jabref/model/entry/BibtexEntry.java, src/main/java/net/sf/jabref/model/entry/BibtexEntryType.java, src/main/java/net/sf/jabref/model/entry/BibtexEntryTypes.java, src/main/java/net/sf/jabref/model/entry/CustomEntryType.java, src/main/java/net/sf/jabref/model/entry/UnknownEntryType.java, src/main/java/net/sf/jabref/sql/exporter/DBExporter.java, src/main/java/net/sf/jabref/wizard/text/gui/TextInputDialog.java
Intended to fix #122, this PR turned into a major API change. It replaces `String[]` in the return types of `BibtexEntryType` with `List<String>`. This allows to return immutable lists instead of mutable arrays and improves the stability of the program. Additionally, the rewrite allowed to replace a lot of duplicate object creation with instance variables.
With respect to #122, the immutability of the new lists removes the necessity to create defensive copies and therefore avoids a lot of cloning.
=> Increase saving speed

CHANGELOG, src/main/java/net/sf/jabref/gui/fieldeditors/FileListEditor.java, src/main/java/net/sf/jabref/logic/util/io/FileUtil.java, src/main/resources/l10n/JabRef_en.properties
In case the auto downloader saved a wrong file, the user might need to delete it #101.
=> Adds a delete local file action to FileListEditor menu

CHANGELOG, circle.yml, src/main/java/net/sf/jabref/JabRef.java, src/main/java/net/sf/jabref/gui/nativeext/WindowsExtensions.java, src/main/java/net/sf/jabref/logic/util/OS.java
This should fix the problem with Windows XP and Vista being unable to use the pin to taskbar feature.
However, I'm not certain if the feature works on Windows 7 and up.
My first tests on Windows 10 didn't allow me to pin JabRef.
We need to investigate this.
Likewise, we should also extract other OS-dependent logic from our code.
=> Extracted native Windows logic and fixed #194

src/main/java/net/sf/jabref/exporter/LatexFieldFormatter.java, src/test/java/net/sf/jabref/exporter/layout/LatexFieldFormatterTests.java
Another attempt to fix the line wrapping. As far as I can see, some of the current behavior is due to the formatting implemented in `LatexFieldFormatter`. This PR tries to rectify some of this behavior by explicitly excluding the "review" and "abstract" fields from line wrapping.
Related: #114 #186 #185
=> [WIP] Fix latex field formatter

CHANGELOG, src/main/java/net/sf/jabref/sql/exporter/DBExporter.java
=> Fixing bug 1282

src/main/java/net/sf/jabref/external/AutoSetExternalFileForEntries.java, src/main/java/net/sf/jabref/external/SynchronizeFileField.java, src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/ColorSetupPanel.java, src/main/java/net/sf/jabref/sql/DBConnectDialog.java, src/main/java/net/sf/jabref/util/ManageKeywordsAction.java, src/main/java/net/sf/jabref/util/MassSetFieldAction.java, src/main/java/net/sf/jabref/util/Util.java, src/main/java/net/sf/jabref/wizard/auximport/gui/FromAuxDialog.java
Another batch of replacing the deprecated DefaultFormBuilder with FormBuilder:
AutoSetExternalFileForEntries, BasePanel, ColorSetupPanel, DBConnectDialog, FromAuxDialog, ManageKeywordsAction, MassSetFieldAction, and SynchronizeFileField.
Clean up in Util.java.
=> Replaced DefaultFormBuilder with FormBuilder

CHANGELOG, src/main/java/net/sf/jabref/JabRefPreferences.java, src/main/java/net/sf/jabref/external/push/AbstractPushToApplication.java, src/main/java/net/sf/jabref/external/push/PushToApplication.java, src/main/java/net/sf/jabref/external/push/PushToApplicationAction.java, src/main/java/net/sf/jabref/external/push/PushToApplicationButton.java, src/main/java/net/sf/jabref/external/push/PushToApplications.java, src/main/java/net/sf/jabref/external/push/PushToEmacs.java, src/main/java/net/sf/jabref/external/push/PushToLatexEditor.java, src/main/java/net/sf/jabref/external/push/PushToLyx.java, src/main/java/net/sf/jabref/external/push/PushToTeXstudio.java, src/main/java/net/sf/jabref/external/push/PushToTexmaker.java, src/main/java/net/sf/jabref/external/push/PushToVim.java, src/main/java/net/sf/jabref/external/push/PushToWinEdt.java, src/main/java/net/sf/jabref/gui/JabRefFrame.java, src/main/java/net/sf/jabref/gui/preftabs/ExternalTab.java, src/main/java/net/sf/jabref/logic/util/OS.java, src/main/java/net/sf/jabref/openoffice/OpenOfficePanel.java
Here's my go at an AbstractPushToApplication class. So far I've implemented PushToTexmaker.java using the new class. See the last commit, the earlier commit is primarily refactoring all these files to external.push.
Comments so far? I thought it might be a better idea to get some input on the construction of the abstract class before I continue converting the rest.
The abstract class will work "out of the box" if there's just a single path to be set. In that case one will have to define the four methods in PushToTexmaker: name, icon, command line, and an init, primarily meant to get the preference key (maybe better to have a `getPreferenceKey()`? I was originally thinking that maybe more preference values could be read in here in case of a more complicated configuration dialogue.)
(I know …
=> [WIP] AbstractPushToApplication

CHANGELOG, src/main/java/net/sf/jabref/external/push/AbstractPushToApplication.java, src/main/java/net/sf/jabref/external/push/PushToApplication.java, src/main/java/net/sf/jabref/external/push/PushToApplicationAction.java, src/main/java/net/sf/jabref/external/push/PushToApplications.java, src/main/java/net/sf/jabref/external/push/PushToEmacs.java, src/main/java/net/sf/jabref/external/push/PushToLyx.java, src/main/java/net/sf/jabref/external/push/PushToVim.java, src/main/java/net/sf/jabref/gui/keyboard/KeyBinds.java, src/main/java/net/sf/jabref/openoffice/OpenOfficePanel.java
Currently, there is a key binding for "push to application" but there can be key bindings for each specific application, e.g., LyX, Vim, etc.
To simplify, there should only be a key binding for the currently selected application, hence, only the "push to application" key binding.
=> Simplify key bindings

src/main/java/net/sf/jabref/JabRefPreferences.java
The UTF-8 support of LaTeX, [biber](https://www.ctan.org/pkg/biber) and [LaTeX editors](http://tex.stackexchange.com/questions/339/latex-editors-ides) is really mature. To have interoperable `.bib` files, JabRef should set the default encoding (for new users) to `UTF-8`
=> Set default encoding to UTF-8

CHANGELOG, src/main/java/net/sf/jabref/gui/StringDialog.java
Removed the button, but kept the shortcut plus all the cleanups from the previous PR.
=> Save shortcut and cleanups in Stringdialog

src/main/java/net/sf/jabref/JabRefPreferences.java, src/main/java/net/sf/jabref/exporter/LatexFieldFormatter.java, src/main/java/net/sf/jabref/gui/ColorSetupPanel.java, src/main/java/net/sf/jabref/gui/MainTableFormat.java
This PR remove preferences that are no longer used in JabRef.
I checked the usage each public field of `JabRefPreferences` and, if there was no such usage, searched for String occurrences of the preference value in the complete project. If such usage was found, I replaced it with a usage of the respective field. Otherwise, I deleted the preference.
All in all, only a surprisingly small amount of preferences is not used.
=> Cleanup preferences

CHANGELOG, src/main/java/net/sf/jabref/gui/preftabs/AdvancedTab.java
I propose to update the list of supported lookAndFeels:
- The FQCN for the `jgoodies` LaFs were wrong
- the "`javax.swing.plaf.mac.MacLookAndFeel`" is not available on Windows and not chosable on Macs either (as the whole input field is hidden on a Mac (see https://github.com/JabRef/jabref/blob/1a0d23b64efa72f5184ad7f4100a428b7cc06040/src/main/java/net/sf/jabref/gui/preftabs/AdvancedTab.java#L123-L148)
- `com.sun.java.swing.plaf.motif.MotifLookAndFeel` looks like this:
=> Update supported lookAndFeels

src/main/resources/help/About.html, src/main/resources/help/da/About.html, src/main/resources/help/de/About.html, src/main/resources/help/fr/About.html, src/main/resources/help/in/About.html, src/main/resources/help/ja/About.html
Maintaining a list of active developers is tedious and not necessarily fair.
All authors are automatically included in the contributors list (if we regenerate it often enough).
I know this is not an easy decision especially for those that contributed more than others and or are/were project leads. Maybe we can add these people exclusively again (as maintainers or the like).
=> Only show automated list of contributors

DEVELOPERS, build.gradle, scripts/generate-developers.sh, src/main/resources/help/da/About.html, src/main/resources/help/de/About.html, src/main/resources/help/en/About.html, src/main/resources/help/fr/About.html, src/main/resources/help/in/About.html, src/main/resources/help/ja/About.html
As discussed in #244, especially at https://github.com/JabRef/jabref/pull/224#issuecomment-147650492, it would be good to show the currently active developers.
JabRef offers the team "developers", which are the currently developers of JabRef. There is also the organization, but these guys are more involved in the overall steering of JabRef and related projects (homepage, journal lists, ...) and not the concrete development and reviews of PRs in the JabRef code.
Similar to the AUTHORs list, I keep the alphabetical order. This is untypical, but more easy to create.
Side note: You have to have `GRADLE_OPTS` to be set to `-Dfile.encoding=UTF-8` on Windows to have the gradle build working correctly. See [README.md](https://github.com/JabRef/jabref/blob/master/README.md#building-jabref-from-sour …
=> Show developers

src/main/java/net/sf/jabref/gui/JabRefFrame.java, src/main/java/net/sf/jabref/importer/ImportCustomizationDialog.java
Found some dead code in JabRefFrame which has been used to generate subMenus for custom imports/exports. 
Would be glad if someone checks whether this is okay.
=> Remove unused menus for import/export

CHANGELOG, src/main/java/net/sf/jabref/JabRefPreferences.java, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java, src/main/java/net/sf/jabref/gui/preftabs/EntryEditorPrefsTab.java
Why?
- I do not see the point of hiding the BibTeX Code tab in the entry editor. Hence, I removed the option.
=> Removes option to hide the BibTeX Code tab in the entry editor.

src/main/java/net/sf/jabref/bibtex/BibtexEntryWriter.java, src/main/java/net/sf/jabref/bibtex/DuplicateCheck.java, src/main/java/net/sf/jabref/collab/EntryChange.java, src/main/java/net/sf/jabref/gui/IncrementalSearcher.java, src/main/java/net/sf/jabref/gui/ReplaceStringDialog.java, src/main/java/net/sf/jabref/gui/RightClickMenu.java, src/main/java/net/sf/jabref/gui/actions/CleanUpAction.java, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java, src/main/java/net/sf/jabref/gui/mergeentries/MergeEntries.java, src/main/java/net/sf/jabref/gui/mergeentries/MergeEntryDOIDialog.java, src/main/java/net/sf/jabref/gui/undo/UndoableFieldChange.java, src/main/java/net/sf/jabref/importer/EntryFromFileCreator.java, src/main/java/net/sf/jabref/importer/ImportFormatReader.java, src/main/java/net/sf/jabref/importer/fetcher/OAI2Fetcher.java, src/main/java/net/sf/jabref/importer/fileformat/EndnoteImporter.java, src/main/java/net/sf/jabref/logic/mods/MODSEntry.java, src/main/java/net/sf/jabref/logic/search/rules/ContainBasedSearchRule.java, src/main/java/net/sf/jabref/logic/search/rules/GrammarBasedSearchRule.java, src/main/java/net/sf/jabref/logic/search/rules/RegexBasedSearchRule.java, src/main/java/net/sf/jabref/logic/xmp/XMPSchemaBibtex.java, src/main/java/net/sf/jabref/logic/xmp/XMPUtil.java, src/main/java/net/sf/jabref/model/database/BibtexDatabase.java, src/main/java/net/sf/jabref/model/entry/BibtexEntry.java, src/main/java/net/sf/jabref/model/entry/EntryConverter.java, src/main/java/net/sf/jabref/openoffice/OOUtil.java, src/test/java/net/sf/jabref/bibtex/BibtexEntryWriterTest.java, src/test/java/net/sf/jabref/importer/fileformat/BibtexParserTest.java, src/test/java/net/sf/jabref/util/XMPSchemaBibtexTest.java, src/test/java/net/sf/jabref/util/XMPUtilTest.java
- Renames getAllFields() to getFieldNames() 
- add getFields() method
Often the workflow in our code is:
```java 
for(String name: entry.getFieldnames()) {
entry.getField(name);
// do something
}
```
We can directly use `entry.getFields()` for this now.
Are there any concurrency Problems behind the old rationale or was it just dumb?
=> Refactor BibTex model (a bit)

CHANGELOG, src/main/java/net/sf/jabref/JabRefPreferences.java, src/main/java/net/sf/jabref/gui/JabRefFrame.java, src/main/java/net/sf/jabref/gui/preftabs/AdvancedTab.java
Why?
- I think this is annoying as one would expect this to work. 
I can also live with the option that this is ALWAYS active, but giving the user the option to choose is not good in my opinion.
=> Removes option to disable renaming in FileChooser dialogs.

src/main/java/net/sf/jabref/bst/VM.java
After looking more into the Bibtex VM (as part of PR #298), I better understood the structure of VM.java. Hence, the main focus was to introduce logging for the warn function and it also lead to that other printouts were replaced with the logger.
=> Replaced System.*.println with LOGGER in VM.java

README.md, build.gradle, circle.yml
Why?
- coverity does static analysis of the source code and makes the found warnings available via reports. In addition to its own checks it also performs findbugs evaluations.
To fix still
=> Enable coverity

src/main/java/net/sf/jabref/gui/JabRefFrame.java
(In this case it was a new database, otherwise the full path is shown.)
=> Fix #328: Added more and better information with unsaved database

src/main/java/net/sf/jabref/bibtex/BibtexEntryWriter.java, src/main/java/net/sf/jabref/external/ExternalFilePanel.java, src/main/java/net/sf/jabref/external/push/PushToApplicationAction.java, src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/ImportInspectionDialog.java, src/main/java/net/sf/jabref/gui/UrlDragDrop.java, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditorTab.java, src/main/java/net/sf/jabref/gui/labelPattern/SearchFixDuplicateLabels.java, src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java, src/main/java/net/sf/jabref/importer/fileformat/FreeCiteImporter.java, src/main/java/net/sf/jabref/logic/labelPattern/LabelPatternUtil.java, src/main/java/net/sf/jabref/model/entry/BibtexEntry.java, src/main/java/net/sf/jabref/model/entry/CustomEntryType.java, src/test/java/net/sf/jabref/logic/labelPattern/LabelPatternUtilTest.java
Verify that special latex characters in author names are handled correctly in bibtex key generation (from [SF bug 1186](http://sourceforge.net/p/jabref/bugs/1186/)).
Small code cleanup (`makeLabel` now returns voids since it updates the entry instead of returning a updated one)
=> Add test for bibtex key generation and refactoring

CHANGELOG.md, src/main/java/net/sf/jabref/importer/ImportFormatReader.java, src/main/java/net/sf/jabref/importer/OpenDatabaseAction.java, src/test/java/net/sf/jabref/importer/OpenDatabaseActionTest.java, src/test/resources/net/sf/jabref/importer/wrong-header.bib
The encoding was not correctly inferred from the first/second line of the file, i.e. from
````
% Encoding: encoding
```
This bug is covered in the tests by changing the default encoding to something different from the encoding in the test files. Fixed this bug by completely rewriting `checkForEncoding`.
=> Fix bug: encoding was not read from comment

src/main/java/net/sf/jabref/importer/OpenDatabaseAction.java, src/test/java/net/sf/jabref/importer/OpenDatabaseActionTest.java
This PR attempts to fix #367
We have a bit of a problem. `UTF8` came from these lines
```  java
try (InputStreamReader reader = openFile(fileToOpen, suppliedEncoding, fallbackEncoding)) {
BibtexParser bp = new BibtexParser(reader);
ParserResult pr = bp.parse();
pr.setEncoding(reader.getEncoding());
```
It is set in [this method call](https://docs.oracle.com/javase/8/docs/api/java/io/InputStreamReader.html#getEncoding--). That's the Java API. The `InputStreamReader` says that the proper name of the encoding is `UTF8`. 
My solution is an ugly compatibility hack in which we just insert the `-` manually. Ugly, but works... What do you think?
=> Add compatibility check for UTF8

CHANGELOG.md, src/main/java/net/sf/jabref/gui/BibtexFields.java, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java, src/main/java/net/sf/jabref/model/entry/IEEETranEntryTypes.java, src/main/java/net/sf/jabref/util/Util.java
Added better support for the specific fields in IEEEtranBSTCTL. Especially, a new extra field "yesno" was introduced to simplify the setting of some of the fields.
=> Better support for IEEEtranBSTCTL entries

CHANGELOG.md, src/main/java/net/sf/jabref/gui/BibtexFields.java, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java
Added a button for the month field such that one can select a month and get the correct bibtex string for that month.
Ideally there should probably be localized month names in the list, but I didn't manage to find a way to do that which still keeps the entry model independent, avoids hard coding the month names again and make sure that syncLang can find the strings.
=> Added month selection to EntryEditor

build.gradle, buildres/JabRef.VisualElementsManifest.xml
Add a gray background in JabRef's start menu tile (for Windows 8.1 and 10) by implementing the [VisualElementsManifest](https://msdn.microsoft.com/en-us/library/windows/apps/dn393983.aspx).
Note: I couldn't test the install procedure since `gradlew releaseWindows` gives an error:
```
[ERROR] [org.gradle.BuildExceptionReporter] > A problem occurred starting process 'command 'launch4j''
```
=> Add purple background in Windows 8.1+ start menu

CHANGELOG.md, src/main/java/net/sf/jabref/JabRefPreferences.java
I think, the new default makes sense as JabRef sometimes opens twice which is a bit annoying for me.
Before resetting the preference every now and then, I had the remote server activated for a few months and it worked fine.
=> Change default preferences: Remote server is started

src/main/java/net/sf/jabref/exporter/ExportCustomizationDialog.java, src/main/java/net/sf/jabref/groups/structure/SearchGroup.java, src/main/java/net/sf/jabref/gui/FetcherPreviewDialog.java, src/main/java/net/sf/jabref/gui/ImportInspectionDialog.java, src/main/java/net/sf/jabref/gui/MainTable.java, src/main/java/net/sf/jabref/gui/search/SearchResultsDialog.java, src/main/java/net/sf/jabref/openoffice/CitationManager.java, src/main/java/net/sf/jabref/openoffice/StyleSelectDialog.java
I replaced the deprecated calls to the glazedlists-API with the current versions. The major difference is that the new ones are not thread-safe and as such in most placed I've used the suggested factory method to obtained a wrapped list/model.
This seems to work, but may require a bit more testing/thinking. Especially to figure out if the wrapping may not be needed in all places and if there actually should be wrapping where there currently isn't.
A better option would be to explicitly lock and unlock the tables, but that require much more work.
=> [WIP] Replaced deprecated Glazedlists-API with current

CHANGELOG.md, src/main/java/net/sf/jabref/JabRefPreferences.java, src/main/java/net/sf/jabref/logic/util/io/FileHistory.java, src/test/java/net/sf/jabref/logic/util/io/FileHistoryTest.java
Removed file history size as a preference variable, since it could not be set anyway and replaced it with a constant. See discussion in koppor/Jabref#43.
=> Removed file history size from preferences

src/main/java/net/sf/jabref/gui/DatabasePropertiesDialog.java, src/main/java/net/sf/jabref/gui/preftabs/GeneralTab.java
A similar bug as #420 happened when the encoding was changed in the database properties dialog. This is now fixed in this PR. 
Sorry for introducing these bugs in the first place.
=> Fix similar bug as #420 for the database properties dialog

src/main/java/net/sf/jabref/exporter/layout/format/CurrentDate.java, src/main/java/net/sf/jabref/importer/EntryFromPDFCreator.java
Default time stamps follows ISO-8601. Reason: https://xkcd.com/1179/
I am not aware of side effects at the CurrentDate formatter.
=> Default time stamps follows ISO-8601

CHANGELOG.md, src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/actions/CleanUpAction.java, src/main/java/net/sf/jabref/gui/actions/RenamePdfCleanup.java
The cleanup process sometimes wasn't successful and reported a `null` reference. The reason was that a registered file wasn't available. This is fixed in this PR.
Moreover, if an exception is thrown in actions then a more detailed error message is displayed including the stack trace.
=> Fix that the cleanup process aborts if linked file does not exists 

src/main/java/net/sf/jabref/bibtex/DuplicateCheck.java, src/test/java/net/sf/jabref/bibtex/DuplicateCheckTest.java
I changed the core function of the duplicate checker from correlation to approximate string matching. This enables the test to work (which earlier failed as `Bob` and `Joyce` was deemed as close enough to indicate a duplicate...). Probably some of the constants used for comparison needs to be tuned. Also, as the approximate string matching is based on edit distance (the number of edits required to turn one string into the other), it might be that one may operate the complete comparison on the full string rather than the word by word style as currently is used.
I think this is good to go (in the sense that it probably performs better than the previous), but please check it with a few different databases to make sure that the false positives or missing hits are to frequent.
=> Improved duplicate checker

src/main/java/net/sf/jabref/importer/fetcher/GoogleScholarFetcher.java
Fix so that the Google Scholar fetcher is working again after the new BibtexEntry class require nun-null values.
=> Fixed null issue in GoogleScholarFetcher

src/main/java/net/sf/jabref/groups/structure/KeywordGroup.java, src/main/java/net/sf/jabref/gui/actions/BiblatexCleanup.java, src/main/java/net/sf/jabref/gui/mergeentries/MergeEntries.java, src/main/java/net/sf/jabref/importer/fetcher/DiVAtoBibTeXFetcher.java, src/main/java/net/sf/jabref/importer/fetcher/GoogleScholarFetcher.java, src/main/java/net/sf/jabref/logic/cleanup/RemoveFieldCleanup.java
As entry.setField() does not accept a null argument anymore, the method entry.clearField() is used instead.
=> Fixed all fields set to null

src/main/java/net/sf/jabref/importer/fileformat/BibtexImporter.java, src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java, src/main/java/net/sf/jabref/model/database/BibDatabase.java, src/test/java/net/sf/jabref/importer/fileformat/BibtexParserTest.java
I added a few tests for the Bibtex parser. I appreciate your feedback about the following points.
For the record: While going through the code, I also changed the following things:
- Remove `BibtexParser.isRecognizedFormat` since the code has quite a few shortcomings (whitespace before @ or closing brackets on new lines were a problem) and the execution was quite slow for big files
- Fixed a bug where loading a file with corrupted bibtex entries showed an exception, cf. `parseIgnoresAndWarnsAboutCorruptedEntry()`
- Made `EntryType` an abstract class which implements the `Comparable` interface and overwrites `equals(Object other)`. Thus new expressions like `entry.getType() == BibtexEntryTypes.ARTICLE` return the expected result.
=> Add tests for the Bibtex parser

src/main/java/net/sf/jabref/JabRef.java, src/main/java/net/sf/jabref/bibtex/DuplicateCheck.java, src/main/java/net/sf/jabref/collab/ChangeScanner.java, src/main/java/net/sf/jabref/external/ExternalFileTypeEditor.java, src/main/java/net/sf/jabref/external/SynchronizeFileField.java, src/main/java/net/sf/jabref/gui/ImportInspectionDialog.java, src/main/java/net/sf/jabref/gui/preftabs/AppearancePrefsTab.java, src/main/java/net/sf/jabref/gui/preftabs/FontSelectorDialog.java, src/main/java/net/sf/jabref/gui/preftabs/NameFormatterTab.java, src/main/java/net/sf/jabref/gui/preftabs/TableColumnsTab.java, src/main/java/net/sf/jabref/gui/remote/JabRefMessageHandler.java, src/main/java/net/sf/jabref/importer/EntryFromExternalFileCreator.java, src/main/java/net/sf/jabref/importer/EntryFromFileCreator.java, src/main/java/net/sf/jabref/importer/EntryFromPDFCreator.java, src/main/java/net/sf/jabref/importer/HTMLConverter.java, src/main/java/net/sf/jabref/importer/fileformat/JSONEntryParser.java, src/main/java/net/sf/jabref/logic/labelPattern/LabelPatternUtil.java, src/main/java/net/sf/jabref/logic/util/strings/StringUtil.java, src/main/java/net/sf/jabref/model/entry/BibEntry.java, src/main/java/net/sf/jabref/util/Util.java
* Used `Optional` instead of `return null`. Sometimes it makes much sense, sometimes less.
* Replaced checking zero or non-zero `String` lengths with `.isEmpty()`
* Changed the default case in some switch-statements to avoid `return null` (as that case should never happen anyway)
* Avoided an exception from happening when importing items without author and generating a BibTexKey which is based on the author name.
=> More use of Optional and some other fixes

CHANGELOG.md, src/main/java/net/sf/jabref/importer/ImportFormatReader.java
The Problem is, that the stream can not be resetted without a BufferedInputStream. 
However this is necessary since we check if a import file is in the right format with
looking into the stream and searching for specific patterns.
Result of the above mentioned issue is that I always got an error message saying
"No entries found" when trying to import a file with a valid format and entries. 
This fixes the issue without changing any method interfaces.
=> Import Format Reader Fix

CHANGELOG.md, src/main/java/net/sf/jabref/JabRefPreferences.java, src/main/java/net/sf/jabref/bibtex/BibEntryWriter.java, src/main/java/net/sf/jabref/exporter/LatexFieldFormatter.java, src/main/java/net/sf/jabref/gui/preftabs/FileTab.java, src/test/java/net/sf/jabref/bibtex/BibEntryWriterTest.java
As decided in #116 all field saving options should be removed.
This PR purges the options from the GUI and cleans up related reader and formatter classes. This simplification greatly reduces the complexity of `BibEntryWriter`.
=> Remove field saving options

.gitignore, CHANGELOG.md, src/main/java/net/sf/jabref/importer/fetcher/IEEEXploreFetcher.java, src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java, src/main/java/net/sf/jabref/util/Util.java
Summary of changes
- moved away from the freesearchresult.jsp script for older browsers (notice on the IEEE suggests support for this will be dropped in Jan 2016), instead use the 'search' script and POST method
- results are returned in JSON format and the article numbers are obtained directly; HTML parsing has been removed
- the article numbers are used to construct a second query for the raw Bibtex records, which now captures all fields available from the IEEE
- the Bibtex entries are still passed to the existing cleanup() routine to improve the formatting consistency
- cleaned up unsued code as a result of the changes (removed HTML parsing code)
- added a method to Util for performing HTTP POST
=> IEEEXplore fetcher downloads the raw bibtex records from IEEEXplore

src/test/java/net/sf/jabref/importer/fileformat/BibtexImporterTest.java, src/test/resources/net/sf/jabref/importer/fileformat/BibtexImporter.examples.bib
Added tests for BibtexImporter, depends on PR #514 (missing Gradle test encoding, special char 'ß')
=> BibtexImporter test

CHANGELOG.md, src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java, src/test/java/net/sf/jabref/importer/fileformat/BibtexParserTest.java
Field values as `escaped \{ bracket` are now parsed properly by the BibtexParser. However, there is still a warning about non-matching brackets if the same string is entered directly in the review panel.
=> Fix SF bug 482 partly: escaped brackets are now properly parsed

CHANGELOG.md, src/main/java/net/sf/jabref/gui/EntryCustomizationDialog2.java
When customizing entry types, the visible panel wasn't directly updated on "Apply" or "OK". Now it is. (And a Coverity warning leading to the solution of this is removed.)
It is only the final changed line in `updateTables` that is the solution, the rest is just using nicer methods.
=> Changes in customized entry types are now directly reflected

src/main/java/net/sf/jabref/gui/BasePanel.java
I installed PMD https://github.com/pmd and cleaned up BasePanel based on the issues there. I didn't add `final` to all the cases where it could (partly out of boredom, partly that I wasn't sure if it was appreciated).
Some interesting things emerged though, such as unused GridBagLayouts. 
Positive is that all printStackTrace are removed.
The cases where if-statements are modified, it is basically have the "positive" (i.e. not using !) case first.
=> BasePanel cleanup

CHANGELOG.md, src/main/java/net/sf/jabref/JabRef.java, src/main/java/net/sf/jabref/gui/ParserResultWarningDialog.java
Now, all warnings when opening a file is shown in a scrollable text area instead of as plain warning text (with all the consequences, try opening a file with ~1000 items without keys...).
=> Used a scrollable text area for parser warnings

CHANGELOG.md, src/main/java/net/sf/jabref/JabRefPreferences.java, src/main/java/net/sf/jabref/openoffice/AutoDetectPaths.java, src/main/java/net/sf/jabref/openoffice/BstWrapper.java, src/main/java/net/sf/jabref/openoffice/CitationManager.java, src/main/java/net/sf/jabref/openoffice/ComparableMark.java, src/main/java/net/sf/jabref/openoffice/OOBibBase.java, src/main/java/net/sf/jabref/openoffice/OOBibStyle.java, src/main/java/net/sf/jabref/openoffice/OOUtil.java, src/main/java/net/sf/jabref/openoffice/OpenOfficePanel.java, src/main/java/net/sf/jabref/openoffice/StyleSelectDialog.java
Hopefully solved #593.
Try it out at http://builds.jabref.org/ooreferencelist/
(Also cleaned up the code a bit based on PMD. The actual fix is on lines 76-90 in OOUtil.java.)
=> Solved #593 and cleaned up the OO-code a bit

src/main/java/net/sf/jabref/openoffice/AutoDetectPaths.java, src/main/java/net/sf/jabref/openoffice/CitationManager.java, src/main/java/net/sf/jabref/openoffice/OOBibBase.java, src/main/java/net/sf/jabref/openoffice/OpenOfficePanel.java
Revert a minor error introduced in earlier fix.
Further cleanup, primarily getting rid of duplicated code and some Coverity warnings.
=> Fixes and cleanup for OpenOffice

src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/BibtexFields.java, src/main/java/net/sf/jabref/gui/CheckBoxMessage.java, src/main/java/net/sf/jabref/gui/ClipBoardManager.java, src/main/java/net/sf/jabref/gui/ColorSetupPanel.java, src/main/java/net/sf/jabref/gui/ContentSelectorDialog2.java, src/main/java/net/sf/jabref/gui/DatabasePropertiesDialog.java, src/main/java/net/sf/jabref/gui/DragDropPopupPane.java, src/main/java/net/sf/jabref/gui/DuplicateSearch.java, src/main/java/net/sf/jabref/gui/EntryMarker.java, src/main/java/net/sf/jabref/gui/EntryTypeList.java, src/main/java/net/sf/jabref/gui/FetcherPreviewDialog.java, src/main/java/net/sf/jabref/gui/FieldWeightDialog.java, src/main/java/net/sf/jabref/gui/FileHistoryMenu.java, src/main/java/net/sf/jabref/gui/IconTheme.java, src/main/java/net/sf/jabref/gui/RightClickMenu.java, src/main/java/net/sf/jabref/gui/SidePaneComponent.java, src/main/java/net/sf/jabref/gui/StringDialog.java, src/main/java/net/sf/jabref/gui/UrlDragDrop.java, src/main/java/net/sf/jabref/gui/VerticalLabelUI.java, src/main/java/net/sf/jabref/gui/WrapLayout.java, src/main/java/net/sf/jabref/gui/actions/CopyAction.java, src/main/java/net/sf/jabref/gui/actions/PasteAction.java, src/main/java/net/sf/jabref/wizard/text/gui/TextInputDialog.java
Sometimes comparing objects with `==` and `!=` is better than `equals`...
=> Reverted a fix that lead to new Coverity warnings and more PMD cleanups

CHANGELOG.md, src/main/java/net/sf/jabref/exporter/ExportFormat.java
This seems to fix #608. Darn autoclosing...
=> Fixed #608

CHANGELOG.md, src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/maintable/MainTable.java
Removed checks that prevented the table from being updated when switching between groups.
=> Fix for issue #417

src/test/java/net/sf/jabref/importer/fileformat/BibtexParserTest.java
I tried to replicate the problems of #650 but in the progress realized that the problem lied in the bib file provided there and not in the parser. 
So the added test is rather useless but I figured it does not hurt to have more tests :)
=> Add test for parsing accents

CHANGELOG.md, src/main/java/net/sf/jabref/importer/OpenDatabaseAction.java, src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java, src/test/java/net/sf/jabref/importer/OpenDatabaseActionTest.java, src/test/java/net/sf/jabref/importer/fileformat/BibtexParserTest.java, src/test/resources/net/sf/jabref/importer/encodingWithoutNewline.bib
As described in #669 and #621 the parser has some problems when an entry (or preamble) follows directly the file encoding header (on the same line), i.e. 
`% Encoding: myEncoding @article{...}`.
Actually, as the tests reveal it was not a problem with the actual parser but within the file opening logic. 
I don't view this PR as a complete fix for #669 and #621 since not just the parser but also the serialization should be improved.
Also fix a bug that prevented the import of BibTex entries having only a key as its content.
=> Make BibTex parser more robust against missing newlines

src/main/java/net/sf/jabref/gui/FileListTableModel.java, src/main/java/net/sf/jabref/importer/DatabaseFileLookup.java, src/main/java/net/sf/jabref/importer/UnlinkedFilesCrawler.java, src/main/java/net/sf/jabref/logic/util/io/FileUtil.java, src/main/java/net/sf/jabref/model/entry/FileField.java, src/test/java/net/sf/jabref/model/entry/FileFieldTest.java
Reenables functionality #410 
Important point:
- Removed one file.exists check in FileUtil.java expandPath
I think one check after replacing / and \ is enough, without checking the expanded path with directory in front.
- Cache is filled at initial creation for bibdatabase, therefore no checks against the whole database are done for each file entry
- Parse logic for file field should moved from the FileListTableModel to FileField.java.
We could still improve quite a lot here but maybe its GOOD ENOUGH :tm: for now.
=> Simplify matching complexity of unlinked file finder

CHANGELOG.md, src/main/java/net/sf/jabref/importer/fetcher/IEEEXploreFetcher.java
When importing entries from IEEEXplore, keywords are separated by ;. Now, they are separated with the keyword group separator.
=> Replaced ; with the used defined keyword separator

src/main/java/net/sf/jabref/JabRef.java, src/main/java/net/sf/jabref/JabRefPreferences.java, src/main/java/net/sf/jabref/gui/preftabs/NetworkTab.java, src/main/java/net/sf/jabref/logic/ProxyPreferences.java, src/main/java/net/sf/jabref/logic/ProxyRegisterer.java
Moves code from `JabRef` to own class and introduces new class encapsulating the proxy preferences.
=> Refactor proxy registration and preferences

CHANGELOG.md, src/main/java/net/sf/jabref/gui/mergeentries/MergeEntryDOIDialog.java
Earlier the field wasn't removed when "None" was selected in the Merge from DOI dialog.
=> Merge from DOI now honors removed fields

src/main/java/net/sf/jabref/model/entry/BibEntry.java, src/main/java/net/sf/jabref/openoffice/CitationManager.java, src/main/java/net/sf/jabref/openoffice/OOBibBase.java, src/main/java/net/sf/jabref/openoffice/OOBibStyle.java, src/main/java/net/sf/jabref/openoffice/OOPreFormatter.java, src/main/java/net/sf/jabref/openoffice/OOUtil.java, src/main/java/net/sf/jabref/openoffice/OpenOfficePanel.java, src/main/java/net/sf/jabref/openoffice/StyleSelectDialog.java, src/main/java/net/sf/jabref/specialfields/SpecialFieldValue.java, src/main/java/net/sf/jabref/sql/DBImportExportDialog.java
Fixed a number of warnings, primarily related to catching general Exceptions in OpenOffice connection. Not all are removed, but many are more fine tuned. Also, all(?) printStackTrace are removed from there.
It also tuned out that some methods didn't even throw exceptions (based on documentation) although there were catch blocks.
=> Sorting out exceptions in OpenOffice connection

src/main/java/net/sf/jabref/logic/labelPattern/LabelPatternUtil.java
Generating a new key would prepend the pattern which resulted for example in `[author]Weinstein` instead of the expected `Weinstein`. The reason for the bug was that the list returned by
`getLabelPattern().getValue(entryType)` contains as the first item the complete pattern.
This bug was introduced in https://github.com/oscargus/jabref/commit/81f2a687010c4da31f1808133ae03fb3ef8cd0b9.
=> Fix a small bug in citekey generator

src/main/java/net/sf/jabref/gui/RightClickMenu.java, src/main/java/net/sf/jabref/gui/maintable/MainTableSelectionListener.java
All code is now gone (and the Move to group menu item follows the same logic as the add to and remove from group).
=> Removed unused group submenu from RIghtClickMenu

CHANGELOG.md, src/main/java/net/sf/jabref/sql/exporter/DBExporter.java
Couldn't resolve the root cause, because of a mixup between Connection and Filehandling (disregards SoC)
=> NPE when exporting the database to an .sql file

src/main/java/net/sf/jabref/exporter/ExportFileFilter.java, src/main/java/net/sf/jabref/exporter/OpenOfficeDocumentCreator.java, src/main/java/net/sf/jabref/external/SynchronizeFileField.java, src/main/java/net/sf/jabref/gui/JabRefFrame.java, src/main/java/net/sf/jabref/importer/fetcher/ACMPortalFetcher.java, src/main/java/net/sf/jabref/importer/fetcher/ADSFetcher.java, src/main/java/net/sf/jabref/importer/fetcher/INSPIREFetcher.java, src/test/java/net/sf/jabref/FileBasedTestCase.java, src/test/java/net/sf/jabref/logic/xmp/XMPUtilTest.java
The most important consequences:
* The entry count when synchronizing file links is correct again (and the database is marked as modified).
* The correct (i.e. current) encoding is hard coded for ACM, ADS and Inspire fetchers.
=> Fixed some warnings

src/main/java/net/sf/jabref/exporter/ExportToClipboardAction.java, src/main/java/net/sf/jabref/external/TransferableFileLinkSelection.java, src/main/java/net/sf/jabref/groups/GroupSelector.java, src/main/java/net/sf/jabref/groups/GroupsTree.java, src/main/java/net/sf/jabref/groups/TransferableEntrySelection.java, src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/TransferableBibtexEntry.java, src/main/java/net/sf/jabref/gui/actions/CleanupAction.java, src/main/java/net/sf/jabref/gui/actions/ManageKeywordsAction.java, src/main/java/net/sf/jabref/gui/actions/MassSetFieldAction.java, src/main/java/net/sf/jabref/gui/maintable/MainTable.java, src/main/java/net/sf/jabref/gui/search/SearchResultsDialog.java, src/main/java/net/sf/jabref/openoffice/OOBibBase.java, src/main/java/net/sf/jabref/openoffice/OpenOfficePanel.java, src/main/java/net/sf/jabref/specialfields/SpecialFieldAction.java
=> [WIP] More List<BibEntry> instead of BibEntry[]

CHANGELOG.md, src/main/java/net/sf/jabref/sql/DBStrings.java, src/main/java/net/sf/jabref/sql/SQLUtil.java, src/main/java/net/sf/jabref/sql/exporter/MySQLExporter.java
Added ability to add server specific connection parameters
Using setCatalog instead of use database (recommended in mysql doc)
For #685
=> Fixes the export of more than one entry through the connection option

src/main/java/net/sf/jabref/importer/HTMLConverter.java, src/main/java/net/sf/jabref/logic/formatter/Formatter.java, src/main/java/net/sf/jabref/logic/formatter/IdentityFormatter.java, src/main/java/net/sf/jabref/logic/formatter/bibtexfields/MonthFormatter.java, src/main/java/net/sf/jabref/logic/formatter/bibtexfields/PageNumbersFormatter.java, src/main/java/net/sf/jabref/logic/formatter/bibtexfields/RemoveBracesFormatter.java, src/main/java/net/sf/jabref/logic/formatter/bibtexfields/SuperscriptFormatter.java, src/main/java/net/sf/jabref/logic/formatter/bibtexfields/TrimFormatter.java, src/main/java/net/sf/jabref/logic/formatter/bibtexfields/UnitFormatter.java, src/main/java/net/sf/jabref/logic/formatter/casechanger/CaseKeeper.java, src/main/java/net/sf/jabref/logic/formatter/minifier/AuthorsMinifier.java, src/test/java/net/sf/jabref/importer/HTMLConverterTest.java, src/test/java/net/sf/jabref/logic/formatter/FormatterTest.java, src/test/java/net/sf/jabref/logic/formatter/PageNumbersFormatterTest.java, src/test/java/net/sf/jabref/logic/formatter/SuperscriptFormatterTest.java, src/test/java/net/sf/jabref/logic/formatter/bibtexfields/RemoveBracesFormatterTest.java, src/test/java/net/sf/jabref/logic/formatter/bibtexfields/TrimFormatterTest.java, src/test/java/net/sf/jabref/logic/formatter/minifier/AuthorsMinifierTest.java
This PR adds the following formatters, which are suitable for the new save actions functionality #821:
- TrimFormatter: trims whitespace (as suggested in https://github.com/JabRef/jabref/pull/821#issuecomment-185801238)
- RemoveBracesFormatter: removes enclosing braces (i.e. "{{test}}" -> "test"). Partly implements [kooper #60](https://github.com/koppor/jabref/issues/60). This functionality was previously available under the option "Remove double braces around BibTeX fields when
loading" but was removed from the parser in c2928d2153301b3c5e90db468b53199bc8b1d521.
Also add some tests for all formatters.
=> Add a few cleanup formatters

CHANGELOG.md, src/main/java/net/sf/jabref/logic/cleanup/RenamePdfCleanup.java, src/test/java/net/sf/jabref/logic/cleanup/RenamePdfCleanupTest.java
=> Fix #466: Rename PDF cleanup now also changes case of file name

src/main/java/net/sf/jabref/gui/actions/CleanupAction.java
This addresses https://github.com/JabRef/jabref/pull/884#issuecomment-189891290.
Replaces `null` by the concrete database at `CleanWorker`.
No tests as #507 is not yet finished.
=> Pass database to doCleanup to enable resolving of crossref fields at renaming of files

CHANGELOG.md, src/main/java/net/sf/jabref/logic/util/strings/StringUtil.java, src/main/java/net/sf/jabref/openoffice/OOBibStyle.java, src/main/java/net/sf/jabref/openoffice/OOPreFormatter.java, src/main/java/net/sf/jabref/openoffice/OpenOfficePanel.java, src/test/java/net/sf/jabref/logic/util/strings/StringUtilTest.java
Fixed #856: Clicking on browse for manual OpenOffice does now work
Fixed #815: Curly braces in OO/LO citation no longer ignored
- Code cleanup: Replaced ActionListener with Lamdbas
One point for discussion: DefaultFormBuilder (jgoodies) is deprecated. Is there already a replacement for the creation? I found this thread:
http://stackoverflow.com/questions/33044573/jgoodies-what-is-the-nextline-equivalent-in-formbuilder
@oscargus  @koppor
=> Fixing OpenOffice Citation with curly braces and manual connection browsing

src/main/java/net/sf/jabref/logic/integrity/IntegrityCheck.java, src/main/java/net/sf/jabref/logic/util/io/FileUtil.java, src/test/java/net/sf/jabref/logic/integrity/IntegrityCheckTest.java
Suppose you have a linked file test.pdf in the same folder as the bib file. Then "Open linked file" finds the file. However the integrity check complained. This is fixed now.
Solution was to replace FileUtil.expandFilename(p.link, fileDirectory) with FileUtil.expandFilename(context.getMetaData(), p.link), which is a bit smarter.
=> Fix bug in "Find broken file links" integrity check: files relative to the bibfile are now found

CHANGELOG.md, src/main/java/net/sf/jabref/logic/layout/Layout.java, src/main/java/net/sf/jabref/logic/layout/LayoutEntry.java, src/test/java/net/sf/jabref/logic/layout/LayoutEntryTest.java, src/test/java/net/sf/jabref/logic/layout/format/HTMLCharsTest.java
=> Fixed #890

src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java, src/main/java/net/sf/jabref/logic/CustomEntryTypesManager.java, src/main/resources/l10n/JabRef_da.properties, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fa.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_in.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_nl.properties, src/main/resources/l10n/JabRef_no.properties, src/main/resources/l10n/JabRef_pt_BR.properties, src/main/resources/l10n/JabRef_ru.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_vi.properties, src/main/resources/l10n/JabRef_zh.properties, src/test/java/net/sf/jabref/importer/fileformat/BibtexParserTest.java
Fix unreported bug which prevented the parsing of custom entry types.
Also move the custom entry type parsing logic to the parser.
=> Fix bug in parsing custom entry types

src/main/java/net/sf/jabref/MetaData.java, src/main/java/net/sf/jabref/exporter/BibDatabaseWriter.java, src/main/java/net/sf/jabref/logic/config/SaveOrderConfig.java, src/main/java/net/sf/jabref/logic/formatter/casechanger/LowerCaseChanger.java, src/main/java/net/sf/jabref/logic/labelpattern/AbstractLabelPattern.java, src/test/java/net/sf/jabref/importer/fileformat/BibtexParserTest.java
This solves #707 and prepares the way to refactor the metadata class.
I added a few methods to the MetaData class to make testing more convenient. Many calls to getData() in fact can be replaced by these new methods. I think this is something for a new PR.
One question: to write the tests in a nice way I had to overwrite a few equals methods. In particular for the LowerCaseChanger. Should I also override equals for all other formatters?
=> Add tests for metadata parsing

CHANGELOG.md, src/main/java/net/sf/jabref/gui/PreviewPanel.java
Fixes #649.
Until now the toolbar within the Preview panel held the key bindings which weren't active when the toolbar wasn't created. Now the Preview panel itself carries the key bindings.
=> Key bindings are now working in preview panel

src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/actions/ChangeTypeAction.java, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java, src/main/java/net/sf/jabref/model/entry/BibEntry.java
Regression bug introduced by https://github.com/JabRef/jabref/commit/51685e85a39cb6dd998e6f4fb994ff2dd15b8fb8.
JabRef v3.2 is fine, so no changelog entry.
EntryEditor must keep a field for the currentlyDisplayed BibEntry type in order to update the editor correctly onChange to the entry type.
=> When changing the type of an entry, the editor does not update

CHANGELOG.md, src/main/java/net/sf/jabref/importer/fileformat/PdfContentImporter.java, src/main/java/net/sf/jabref/logic/util/DOI.java, src/test/java/net/sf/jabref/logic/util/DOITest.java
1. Fixed #410 Reason was an IllegalArgumentException thrown by DOI class when pasting the contents of the whole first PDF page to the constructor.
2. The DOI class can only handle real DOIs and does not extract Strings that might look like a DOI from the text, therefore the whole DOI scraper was removed in https://github.com/JabRef/jabref/commit/acdcd829c304e03b9bfd92d6eba383b5a1d52108
3. The whole PDFImporter class is screwed and a monkeypatch. It should be reimplemented from scratch.
=> "Find unlinked files" freezes when using for PDF

CHANGELOG.md, src/main/java/net/sf/jabref/gui/BasePanel.java
Fixes #936.
When an entry is cut/deleted the preview panel will be hidden due to the fact that no entry is selected anymore.
=> Preview panel is now updated when an entry is cut/deleted

src/main/java/net/sf/jabref/BibDatabaseContext.java, src/main/java/net/sf/jabref/MetaData.java, src/main/java/net/sf/jabref/exporter/BibDatabaseWriter.java, src/test/java/net/sf/jabref/MetaDataTest.java, src/test/java/net/sf/jabref/exporter/BibDatabaseWriterTest.java, src/test/java/net/sf/jabref/importer/fileformat/BibtexParserTest.java, src/test/resources/testbib/complex.bib
Changes:
- `@comment{groups...}` is now in the right position (based on alphabetical order of metadata keys)
- Empty content selectors are no longer written
Code changes:
-  Add tests for metadata serialization
- Move  the biggest part of metadataserialization to metadata class (probably not the final solution, just eased writing tests)
- Add a few methods which allow to change the metadata in a typed fashion
- Cleanup BibDataBasewriter tests
-
=> Add test to metadata serialization

src/main/java/net/sf/jabref/exporter/SaveAllAction.java, src/main/java/net/sf/jabref/gui/ImportInspectionDialog.java, src/main/java/net/sf/jabref/gui/JabRefFrame.java, src/main/java/net/sf/jabref/gui/SidePaneManager.java, src/main/java/net/sf/jabref/gui/actions/NewEntryAction.java, src/main/java/net/sf/jabref/gui/actions/NewSubDatabaseAction.java, src/main/java/net/sf/jabref/gui/actions/SortTabsAction.java, src/main/java/net/sf/jabref/gui/preftabs/EntryEditorPrefsTab.java, src/main/java/net/sf/jabref/importer/OpenDatabaseAction.java
Triggered by #931. 
- Makes tabbedPane in mainframe private
- Set tab tooltips in consistent way (for example they should now also show up after the tab list is sorted)
-
=> Make tabbedPane in mainframe private

CHANGELOG.md, src/main/java/net/sf/jabref/logic/search/SearchQueryHighlightObservable.java, src/main/java/net/sf/jabref/logic/search/rules/RegexBasedSearchRule.java, src/test/java/net/sf/jabref/logic/search/rules/ContainBasedSearchRuleTest.java
Attempts to fix the issue with whitespaces in #962.
Currently, all search queries are split on whitespaces and then matched separately on all fields.
This would change with this PR as Regex based search queries are only matched entirely on every field.
This PR must be assessed carefully to avoid unwanted effects.
=> Fixes #962 Do not split Regexes and only match on entire fields

src/main/java/net/sf/jabref/JabRefPreferences.java, src/main/java/net/sf/jabref/gui/desktop/JabRefDesktop.java, src/main/java/net/sf/jabref/gui/desktop/os/DefaultDesktop.java, src/main/java/net/sf/jabref/gui/desktop/os/Linux.java, src/main/java/net/sf/jabref/gui/desktop/os/NativeDesktop.java, src/main/java/net/sf/jabref/gui/desktop/os/OSX.java, src/main/java/net/sf/jabref/gui/desktop/os/Windows.java, src/main/java/net/sf/jabref/logic/util/OS.java
=> Extract native functions to OS package

src/main/java/net/sf/jabref/bibtex/BibtexSingleField.java, src/main/java/net/sf/jabref/bibtex/BibtexSingleFieldProperties.java, src/main/java/net/sf/jabref/gui/FieldWeightDialog.java, src/main/java/net/sf/jabref/gui/GUIGlobals.java, src/main/java/net/sf/jabref/gui/InternalBibtexFields.java, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditorTab.java, src/main/java/net/sf/jabref/gui/maintable/MainTable.java, src/main/java/net/sf/jabref/gui/preftabs/TableColumnsTab.java
Based on the initial ideas in #978 the class SingleBibtexField is extracted and two EnumSets are used for implementing the existing functionality.
=> Refactored Singlebibtexfield

src/test/java/net/sf/jabref/exporter/BibDatabaseWriterTest.java
Disabled the dubious test. 
(The roundtrip test doesn't pass on my computer although I can not tell any difference between the outputs... Let's see what happens here...)
=> Disabled NPE test

src/test/java/net/sf/jabref/cli/AuxCommandLineTest.java, src/test/java/net/sf/jabref/importer/OpenDatabaseActionTest.java, src/test/java/net/sf/jabref/logic/auxparser/AuxParserTest.java, src/test/java/net/sf/jabref/openoffice/OOBibStyleTest.java
After I relocated my workspace, I notice some problems with white spaces in file paths. The whitespaces got encoded as %20 and failed on Windows.
Problem was Url.toFile()
`Paths.get(url.toUri()).toFile()` is now the correct way to handle Files from URLs.
See  http://stackoverflow.com/questions/6164448/convert-url-to-normal-windows-filename-java
=> Fixed problem with whitespaces in file paths for tests

src/main/java/net/sf/jabref/JabRefPreferences.java, src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/GUIGlobals.java, src/main/java/net/sf/jabref/gui/PreambleEditor.java
Now the preamble editor opens with the same size and position as last time. (Plus that some unused preferences and GUIGlobals variables were removed.)
=> Used PositionWindow for PreambleEditor dialog size

src/main/java/net/sf/jabref/JabRef.java, src/main/java/net/sf/jabref/exporter/BibDatabaseWriter.java, src/main/java/net/sf/jabref/exporter/ExportFormat.java, src/main/java/net/sf/jabref/exporter/ExportFormats.java, src/main/java/net/sf/jabref/exporter/MSBibExportFormat.java, src/main/java/net/sf/jabref/exporter/ModsExportFormat.java, src/main/java/net/sf/jabref/exporter/MySQLExport.java, src/main/java/net/sf/jabref/exporter/OpenDocumentSpreadsheetCreator.java, src/main/java/net/sf/jabref/exporter/OpenOfficeDocumentCreator.java, src/main/java/net/sf/jabref/exporter/PostgreSQLExport.java, src/test/java/net/sf/jabref/exporter/BibDatabaseWriterTest.java, src/test/java/net/sf/jabref/exporter/ExportFormatTest.java
Really trivial and early test, but could maybe avoid bugs like #1001 to happen (and form a foundation to extend on).
=> Added initial tests for ExportFormat

CHANGELOG.md, src/integrationTest/java/net/sf/jabref/gui/GUITest.java, src/main/java/net/sf/jabref/gui/SaveOrderConfigDisplay.java, src/main/java/net/sf/jabref/gui/dbproperties/DatabasePropertiesDialog.java, src/main/java/net/sf/jabref/gui/dbproperties/FieldFormatterCleanupsPanel.java, src/main/java/net/sf/jabref/gui/dbproperties/SaveActionsListModel.java
Fixes  #957  and #958 
Fix height of the dialog and add spacing between OK/Cancel Button and  border
Changed JComboxBox to editable and removed the unnecessary textfields
Added JCombobox for selecting the fields to apply the selected formatter to
Changed position of Delete Button
Removed IndexOutOfBound Exception when no item is selected
Edit// I just see this PR is #999 ;)
=> DB properties layout and save order config changed

src/main/java/net/sf/jabref/MetaData.java, src/main/java/net/sf/jabref/collab/ChangeScanner.java, src/main/java/net/sf/jabref/collab/EntryChange.java, src/main/java/net/sf/jabref/exporter/IExportFormat.java, src/main/java/net/sf/jabref/exporter/MSBibExportFormat.java, src/main/java/net/sf/jabref/exporter/ModsExportFormat.java, src/main/java/net/sf/jabref/exporter/MySQLExport.java, src/main/java/net/sf/jabref/exporter/OOCalcDatabase.java, src/main/java/net/sf/jabref/exporter/OpenDocumentRepresentation.java, src/main/java/net/sf/jabref/exporter/PostgreSQLExport.java, src/main/java/net/sf/jabref/exporter/SaveDatabaseAction.java, src/main/java/net/sf/jabref/gui/FieldWeightDialog.java, src/main/java/net/sf/jabref/gui/GlazedEntrySorter.java, src/main/java/net/sf/jabref/gui/labelpattern/SearchFixDuplicateLabels.java, src/main/java/net/sf/jabref/importer/fetcher/GVKFetcher.java, src/main/java/net/sf/jabref/model/database/EntrySorter.java, src/test/java/net/sf/jabref/bst/TestVM.java
Actually found a bug in the ChangeScanner leading to NPEs while trying to remove a Codacy warning (not sure if that part succeeded though).
Got rid of unused imports (don't you have your editors configured to do that automatically :question: ).
Got rid of maybe the last unwanted println.
=> Coverity and Codacy cleanups

src/main/java/net/sf/jabref/bibtex/BibtexSingleFieldProperties.java, src/main/java/net/sf/jabref/gui/InternalBibtexFields.java, src/main/java/net/sf/jabref/gui/maintable/MainTableColumn.java, src/main/java/net/sf/jabref/logic/layout/format/FormatChars.java
The main table doesn't always look that nice with latex commands in it. This PR makes things much better.
Potential drawback is rendering time, but I am not sure how much of a problem it actually is.
=> Better main table rendering

src/main/java/net/sf/jabref/gui/help/AboutDialog.java, src/main/java/net/sf/jabref/model/entry/BibEntry.java, src/test/java/net/sf/jabref/model/database/BibDatabaseTest.java, src/test/java/net/sf/jabref/model/entry/BibtexEntryTests.java
Added more tests and fixed a few issues.
Fixed(?) a Coverity issue in AboutDialog.
=> Tests of BibEntry and BibDatabase

CHANGELOG.md, src/main/java/net/sf/jabref/gui/journals/ManageJournalsPanel.java, src/main/java/net/sf/jabref/logic/journals/AbbreviationParser.java, src/main/java/net/sf/jabref/logic/journals/JournalAbbreviationLoader.java, src/main/java/net/sf/jabref/openoffice/OOBibStyle.java, src/main/java/net/sf/jabref/openoffice/OpenOfficePanel.java, src/main/java/net/sf/jabref/openoffice/StyleSelectDialog.java, src/test/java/net/sf/jabref/exporter/ExportFormatTest.java, src/test/java/net/sf/jabref/external/RegExpFileSearchTests.java, src/test/java/net/sf/jabref/importer/DatabaseFileLookupTest.java, src/test/java/net/sf/jabref/importer/EntryFromFileCreatorManagerTest.java, src/test/java/net/sf/jabref/openoffice/OOBibStyleTest.java
Fixed some issues with the encoding for files and resources. Now the user defined journal abbreviation lists are always saved and loaded using the current default encoding from the preferences. Ideally, it should be possible to specify the encoding (or maybe not needed?). Similarly, OO style files are loaded with the default encoding.
=> Encoding fixes

src/main/java/net/sf/jabref/gui/BasePanel.java
Fixes NPE in Export to External DB
Add DB Type to Export Succesful message
Reformatting
#1055
No Changelog because I think it was new introduced by the redesign of the Entry sorting (passing null)
=> Fixes NPE in Export to External DB

src/main/java/net/sf/jabref/BibDatabaseContext.java, src/main/java/net/sf/jabref/MetaData.java, src/test/java/net/sf/jabref/exporter/BibDatabaseWriterTest.java, src/test/java/net/sf/jabref/importer/fileformat/BibtexParserTest.java, src/test/java/net/sf/jabref/logic/integrity/IntegrityCheckTest.java, src/test/resources/net/sf/jabref/cli/origin.bib, src/test/resources/net/sf/jabref/logic/auxparser/config.bib, src/test/resources/net/sf/jabref/logic/auxparser/origin.bib, src/test/resources/testbib/complex.bib, src/test/resources/testbib/save-actions.bib
This finally fixes #963. A quick fix has been introduced in 661eea007e555, but that does not cover the lower case writing of the type.
@Comment{jabref-meta: DATABASE_TYPE:BibTeX;}
finally gets
@Comment{jabref-meta: databaseType:bibtex;}
=> Write database type in lower case into the bib file

src/main/java/net/sf/jabref/exporter/SavePreferences.java, src/test/java/net/sf/jabref/exporter/BibDatabaseWriterTest.java
Fix sorting of entries on save (this shouldn't affect the sorting of export, so is unrelated to #1051). In the end it was just a wrong boolean in the preference.
=> Fix sorting of entries on save

CHANGELOG.md, src/main/java/net/sf/jabref/gui/JabRefFrame.java
Move the function `Set clear rename fields` to edit from search. Since it is definitely an edit function and has nothing to do with searches.
=> Move Set/clear/rename fields to edit

src/main/java/net/sf/jabref/importer/EntryFromFileCreatorManager.java, src/main/java/net/sf/jabref/importer/EntryFromPDFCreator.java, src/main/java/net/sf/jabref/model/database/BibDatabase.java
This can be significantly improved, but at least it won't freeze for now. Also, the output do make sense.
=> Fixed freezing when canceling Find unlinked files (for PDFs)

build.gradle, src/jmh/java/net/sf/jabref/benchmarks/Benchmarks.java, src/main/java/net/sf/jabref/BibDatabaseContext.java, src/main/java/net/sf/jabref/model/database/BibDatabase.java, src/main/java/net/sf/jabref/model/database/BibDatabaseModeDetection.java
This PR adds some basic benchmarks for parsing and writing a bib file. The results are as following for a database consisting of 1000 entries.
Benchmark                         Score     Error  Units
Benchmarks.parse                 49736.582 ± 788.879  ops/s
Benchmarks.write                0.706 ±   0.012  ops/s
Benchmarks.search                258.838 ±   5.604  ops/s
Benchmarks.inferBibDatabaseMode  1297.622 ±  22.910  ops/s
As one can see the parse operation is by many orders of magnitudes quicker then writing. I had a closer look at the write operation and it turned out that 66% of the time is spent in Database.getMode(). Some small changes improved the situation by a factor of 10
Benchmark                         Score      Error  Units
Benchmarks.parse                42031.971 ± …
=> Add benchmarks

src/main/resources/l10n/JabRef_de.properties
The only one I am not really sure about is the last one. It is from the integrity checker, if you have an "proceedings" entry with "pages" field instead of page-number
=> Add missing german Translation

src/jmh/java/net/sf/jabref/benchmarks/Benchmarks.java, src/main/java/net/sf/jabref/exporter/LatexFieldFormatter.java, src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java, src/main/java/net/sf/jabref/importer/fileformat/FieldContentParser.java, src/main/java/net/sf/jabref/logic/search/rules/ContainBasedSearchRule.java, src/main/java/net/sf/jabref/logic/util/strings/StringUtil.java, src/main/java/net/sf/jabref/model/entry/BibEntry.java
Motivated by the nice blog post from @mlep, I tried to further improve the performance.
Starting point
Benchmark                         Score      Error  Units
Benchmarks.parse                 30        ± 2.7  ops/s
Benchmarks.search                230.359 ±   27.399  ops/s
Benchmarks.write                 53.323 ±    5.528  ops/s
Now with this PR
Benchmark                         Score     Error  Units
Benchmarks.parse                 46.965 ±   0.608  ops/s
Benchmarks.search                304.795 ±   5.905  ops/s
Benchmarks.write                 85.171 ±   1.301  ops/s
For further improvements on should have a closer look at the formatter:
- RemoveLatexCommands for search (70% of time is spent there)
- FieldContentParser and LatexFieldFormatter for write (also >50%)
(also fixed a bug …
=> Some performance improvements

src/integrationTest/java/net/sf/jabref/gui/GUITest.java, src/main/java/net/sf/jabref/gui/labelpattern/LabelPatternPanel.java
@koppor It's just a simple if :smile:
=> Fix #1130 and re-enable GUI test

jabref.install4j
See #783 
All users needs admin privileges. Current user cannot install into Program file directory.
Installation directory will be set to `user.home` when installation only for current user is selected.
Please, check the installer on http://builds.jabref.org/install-privileges/ if its working correctly.
=> Installer allows to select installation for all users or current user

src/main/java/net/sf/jabref/external/RegExpFileSearch.java, src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/SidePaneManager.java, src/main/java/net/sf/jabref/logic/journals/JournalAbbreviationRepository.java, src/main/java/net/sf/jabref/logic/openoffice/OOBibStyle.java, src/main/java/net/sf/jabref/migrations/PreferencesMigrations.java, src/main/java/net/sf/jabref/model/EntryTypes.java
Based on a disussion in #1142, pointed out by @Siedlerchr , checking if a `Map` containts a key is better done using `Map.containsKey()` than checking if `Map.get()` returns null. (I have checked that null is not stored in the `Map` as well.)
=> Replaced Map.get()  with containsKey() where appropriate

CHANGELOG.md, src/main/java/net/sf/jabref/logic/formatter/bibtexfields/NormalizeNamesFormatter.java, src/main/java/net/sf/jabref/logic/util/strings/StringUtil.java, src/main/java/net/sf/jabref/model/entry/Author.java, src/main/java/net/sf/jabref/model/entry/AuthorListParser.java, src/test/java/net/sf/jabref/logic/formatter/bibtexfields/NormalizeNamesFormatterTest.java, src/test/java/net/sf/jabref/logic/util/strings/StringUtilTest.java, src/test/resources/net/sf/jabref/importer/fileformat/OvidImporterTestBib5.bib, src/test/resources/net/sf/jabref/importer/fileformat/OvidImporterTestBib6.bib, src/test/resources/net/sf/jabref/importer/fileformat/RisImporterTest6.bib
- Fixes #318 (and refs #950)
- Removes comma as delimiter of author names (in NormalizenamesFormatter).
The problem is that comma separated authors cannot be distingued from one author in BibTeX format.
For example `Name, della, first` could be three names separated by commas or if interpreted as valid BibTeX string it is one author with lastname=name, jrpart=della, firstname=first.
- Add colon as delimiter of author names (in AuthorListParser).
Thanks at all, but especially @oscargus, for creating many tests. Made implementing this PR way easier! 
--
=> Replace NormalizeNamesFormatter by AuthorList and so fix #318

src/main/java/net/sf/jabref/Globals.java, src/main/java/net/sf/jabref/gui/GUIGlobals.java, src/main/java/net/sf/jabref/logic/layout/LayoutEntry.java
Alternative to  #1114 to add backwards compatibility for FormatChars (and a few other renamed LayoutFormatters). The idea was to replace the reflection code by an (admittedly big) switch statement. In this way we gain some flexibility about the location and naming of LayoutFormatter classes.
By the way,  according to http://jabref.sourceforge.net/help/CustomExports.php all LayoutFormatters starting with "Author" are deprecated and are replaced by "Authors" since 2.7. Should we just delete them now?
=> Readd FormatChars support

CHANGELOG.md, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java, src/main/java/net/sf/jabref/gui/fieldeditors/FileListEditor.java
Fixes #672.
The FileList (within the EntryEditor) now automatically resizes its Columns dependent on the length of its content.
=> FileList field size now dependent on its content

localization.gradle
I always have to look up the Gradle task name to generate missing translation keys.
Therefore, I suggest to change to a more memorizable name.
=> More memorizable task names

src/main/java/net/sf/jabref/logic/fulltext/IEEE.java, src/main/java/net/sf/jabref/logic/journals/Abbreviation.java
While looking for the use of Guava I found these calls which can be replaced with standard java-classes.
Regarding the original quest:
* Most uses are for checking null or empty Strings or similarly return an empty String if the input String is null, it may not be worth importing the library just for these two and better to create these two trivial methods in StringUtil (and use them to a larger extent)
* There is also `CharMatcher.WHITESPACE` which may be slightly less trivial to replace
=> Replaced some Guava usage with standard java.*

src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/undo/UndoableInsertEntry.java, src/main/java/net/sf/jabref/gui/undo/UndoableRemoveEntry.java
When I fixed #936 some time ago (PR: #937) I made a tiny error.
The Issue was to hide the Preview Panel when deleting/cutting an entry, but it also hid it when aborting the Delete-Confirmation-Dialog.
I too refactored both actions a little to make it easier for future changes.
I also removed in `UndoableRemoveEntry` and `UndoableInsertEntry` the ID generation.
=> Preview panel is now updated when an entry is cut/deleted (again)

src/main/java/net/sf/jabref/importer/OpenDatabaseAction.java
When openning a file and special fields are used, users currently **always** get the message `INFO net.sf.jabref.importer.OpenDatabaseAction - Synchronized special fields based on keywords` displayed. This is confusing. See for example https://github.com/JabRef/jabref/issues/742#issuecomment-209811934.
Currently, JabRef uses `info` for errors and warnings, too:
The synchronized message is a debug message, which should not be shown in the general case.
To be consistent with the current logging approach, I changed the log level for a message from `info` to `debug`. This also reduces clutter in the log and on the console. 
The alternative is to rethink all log levels and the preferred default output.
=> Change output level from info to debug to remove clutter in the output

src/main/java/net/sf/jabref/logic/cleanup/CleanupWorker.java, src/test/java/net/sf/jabref/logic/cleanup/CleanupWorkerTest.java
As reported by @stefan-kolb, the field formatters run although they were disabled. This is fixed with this PR.
=> Fix that FieldFormatters run although they are disabled

CHANGELOG.md, src/main/java/net/sf/jabref/gui/BasePanel.java
When you click on an entry directly after startup the preview panel was not shown (of course this bug occurs only when it was activated in the preferences).
Now it does.
- start JabRef
- open a database with entries
- click on one of the entries (single click)
- now the preview Panel should appear (if its activated in the settings), but it doesn't
When you de- and activate the Preview Panel (Ctrl+f9) or open and close the entry editor it works again.
=> now the preview panel will be shown with a single click after startup

src/main/java/net/sf/jabref/gui/FindUnlinkedFilesDialog.java
May also avoid problems with whitespaces in Directories.
Remove unnecessary checks
Some Reformatting and organizing imports
Added Debug Logging for "ignored" Exception, better than ignoring it.
=> Use Path methods from nio in FindUnlinkeFiles

CHANGELOG.md, src/main/java/net/sf/jabref/logic/integrity/IntegrityCheck.java, src/main/java/net/sf/jabref/model/entry/BibEntry.java, src/main/resources/l10n/JabRef_da.properties, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fa.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_in.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_nl.properties, src/main/resources/l10n/JabRef_no.properties, src/main/resources/l10n/JabRef_pt_BR.properties, src/main/resources/l10n/JabRef_ru.properties, src/main/resources/l10n/JabRef_sv.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_vi.properties, src/main/resources/l10n/JabRef_zh.properties, src/test/java/net/sf/jabref/logic/integrity/IntegrityCheckTest.java
Will sometimes help for #1212 and #1188
=> Added integrity checker for odd number of #

src/main/java/net/sf/jabref/JabRefPreferences.java, src/main/java/net/sf/jabref/gui/preftabs/GeneralTab.java, src/main/resources/l10n/JabRef_da.properties, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fa.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_in.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_nl.properties, src/main/resources/l10n/JabRef_no.properties, src/main/resources/l10n/JabRef_pt_BR.properties, src/main/resources/l10n/JabRef_ru.properties, src/main/resources/l10n/JabRef_sv.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_vi.properties, src/main/resources/l10n/JabRef_zh.properties
Found some unused code when doing translations. This is a left over from when it was possible to edit in the table directly.
I've earlier seen some code which checks if a single cell is selected. That should also be safe to remove I assume (I was a bit confused why it was ever there, but now I think I know the reason...).
=> Removed leftovers from option to edit in table cells

CHANGELOG.md, src/main/java/net/sf/jabref/logic/integrity/IntegrityCheck.java, src/main/resources/l10n/JabRef_da.properties, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fa.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_in.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_nl.properties, src/main/resources/l10n/JabRef_no.properties, src/main/resources/l10n/JabRef_pt_BR.properties, src/main/resources/l10n/JabRef_ru.properties, src/main/resources/l10n/JabRef_sv.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_vi.properties, src/main/resources/l10n/JabRef_zh.properties, src/test/java/net/sf/jabref/logic/integrity/IntegrityCheckTest.java
=> Added integrity checker to detect HTML encoded characters in fields

CHANGELOG.md, src/main/java/net/sf/jabref/gui/entryeditor/FieldExtraComponents.java
I'm not quite sure if this fixes all issues. The real problem ist the update mechanism of the `StoreFieldAction` imho. Our GUI state is so inconsistent...
=> Fixes #1234 Trigger entry update explicitly

src/main/java/net/sf/jabref/gui/actions/CleanupAction.java, src/main/java/net/sf/jabref/gui/preftabs/ImportSettingsTab.java, src/main/java/net/sf/jabref/gui/preftabs/NameFormatterTab.java, src/main/java/net/sf/jabref/gui/preftabs/PreferencesDialog.java, src/main/java/net/sf/jabref/gui/preftabs/XmpPrefsTab.java
Previously, the cleanup used the preference state from the program start and not the most recent preferences. This is fixed with this PR.
=> Cleanup now uses active preferences

CHANGELOG.md, src/main/java/net/sf/jabref/logic/openoffice/OOBibStyle.java, src/test/java/net/sf/jabref/logic/openoffice/OOBibStyleTest.java, src/test/resources/net/sf/jabref/logic/openoffice/test.jstyle
This should fix #1245 so that it is possible to set empty strings is jstyle-files as `key=""`
=> Fixed #1245

src/main/java/net/sf/jabref/logic/cleanup/FieldFormatterCleanup.java, src/test/java/net/sf/jabref/logic/cleanup/CleanupWorkerTest.java
Tests when DOI in URL-field.
Fix so that the FieldChange new value is null instead of "" after removing field contents.
=> More tests for DOI cleanup and a small fix

CHANGELOG.md, src/main/java/net/sf/jabref/exporter/AutoSaveManager.java
Fixed #1270. The auto save file was actually not saved at the desired place and thus the temp files were left over.
=> Fix 1270: autosave is working again

src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/preftabs/PreviewPrefsTab.java, src/main/java/net/sf/jabref/importer/fileformat/BibTeXMLHandler.java, src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java, src/main/java/net/sf/jabref/importer/fileformat/MedlinePlainImporter.java, src/main/java/net/sf/jabref/importer/fileformat/RisImporter.java, src/main/java/net/sf/jabref/logic/labelpattern/LabelPatternUtil.java, src/main/java/net/sf/jabref/logic/mods/MODSEntry.java, src/main/java/net/sf/jabref/logic/msbib/MSBibEntry.java, src/main/java/net/sf/jabref/model/database/BibDatabase.java, src/main/java/net/sf/jabref/model/entry/BibEntry.java, src/main/java/net/sf/jabref/sql/importer/DatabaseImporter.java, src/test/java/net/sf/jabref/bibtex/BibtexEntryAssert.java, src/test/java/net/sf/jabref/exporter/FieldFormatterCleanupsTest.java, src/test/java/net/sf/jabref/external/RegExpFileSearchTests.java, src/test/java/net/sf/jabref/importer/fileformat/BibtexParserTest.java, src/test/java/net/sf/jabref/logic/autocompleter/BibtexKeyAutoCompleterTest.java, src/test/java/net/sf/jabref/logic/cleanup/CleanupWorkerTest.java, src/test/java/net/sf/jabref/model/entry/BibtexEntryTests.java, src/test/java/net/sf/jabref/model/entry/CanonicalBibEntryTest.java
As proposed in #625 a proper BibEntry.equals is provided in this PR and used for the tests. 
This as a few advantages:
- detect differences which are not visible in the canonical string representation (so far this hit empty fields and different line breaks)
- get more meaningful test-failure messages for lists (instead of "expected 2 got 3" the added entry is displayed)
- Assert.assertEquals just works and no custom written assertEquals method has to be used
I clicked around a bit, but couldn't find any unexpected side effects due to the overwritten equals method. 
If this PR is accepted, then I would inline the BibtexEntryAssert.assertEquals methods.
=> Replace BibtexEntryAssert by overwriting BibEntry.equals method

src/test/java/net/sf/jabref/bibtex/BibEntryAssert.java, src/test/java/net/sf/jabref/bibtex/BibtexEntryAssert.java, src/test/java/net/sf/jabref/importer/fetcher/GVKParserTest.java, src/test/java/net/sf/jabref/importer/fileformat/BibTeXMLImporterTestFiles.java, src/test/java/net/sf/jabref/importer/fileformat/BibTeXMLImporterTestTypes.java, src/test/java/net/sf/jabref/importer/fileformat/BiblioscapeImporterTestFiles.java, src/test/java/net/sf/jabref/importer/fileformat/BiblioscapeImporterTestTypes.java, src/test/java/net/sf/jabref/importer/fileformat/BibtexParserTest.java, src/test/java/net/sf/jabref/importer/fileformat/CopacImporterTestFiles.java, src/test/java/net/sf/jabref/importer/fileformat/InspecImportTest.java, src/test/java/net/sf/jabref/importer/fileformat/MedlinePlainImporterTest.java, src/test/java/net/sf/jabref/importer/fileformat/MsBibImporterTestfiles.java, src/test/java/net/sf/jabref/importer/fileformat/OvidImporterTest.java, src/test/java/net/sf/jabref/importer/fileformat/PdfContentImporterTestFiles.java, src/test/java/net/sf/jabref/importer/fileformat/RISImporterTestFiles.java, src/test/java/net/sf/jabref/importer/fileformat/RepecNepImporterTest.java, src/test/java/net/sf/jabref/importer/fileformat/SilverPlatterImporterTest.java, src/test/java/net/sf/jabref/logic/search/DatabaseSearcherTest.java, src/test/java/net/sf/jabref/logic/util/UpdateFieldTest.java, src/test/java/net/sf/jabref/logic/xmp/XMPUtilTest.java, src/test/java/net/sf/jabref/model/database/BibDatabaseTest.java, src/test/java/net/sf/jabref/sql/DatabaseImportExportTests.java
This is a follow up of  #1281 with removing obsolete BibtexEntry.assertEquals methods
=> Improve BibtexEntryAssert

src/integrationTest/java/net/sf/jabref/gui/GUITest.java
This PR adds the possibility to take srceenshots in GUI tests. The idea is that srceenshots for the website can easily be updated for a new version by just running the GUI tests.
The images are stored in `builds/srceenshots/`.
=> Take srceenshots in GUI tests

CHANGELOG.md, src/main/java/net/sf/jabref/model/entry/AuthorList.java, src/main/java/net/sf/jabref/model/entry/AuthorListParser.java, src/test/java/net/sf/jabref/model/entry/AuthorListTest.java
=> Fix #1271: Authors with compound first names are parsed properly

src/main/java/net/sf/jabref/model/entry/BibEntry.java
- <s>rename CiteKey to BibTeXKey to be consistent with wording of JabRef users</s>
- reorder methods in BibEntry to follow id, cite key, type, everything else
- add some JavaDoc
- remove obsolete setting of `changed=true`
=> Minor updates to BibEntry

src/main/java/net/sf/jabref/logic/formatter/bibtexfields/NormalizePagesFormatter.java, src/test/java/net/sf/jabref/logic/formatter/bibtexfields/NormalizePagesFormatterTest.java
Formatting the page range `R1--R50` resulted in `1--50`. Now nothing is changed.
Moreover, "43 -- 103" is now correctly converted to "43--103".
=> Normalize pages formatter does not remove letters in page numbers

src/main/java/net/sf/jabref/gui/mergeentries/MergeEntries.java, src/test/java/net/sf/jabref/gui/mergeentries/MergeEntriesTest.java
Changes are only highlighted. See the doi field in the following screenshot. Previously the change
was written as "MSP~~msp~~".
Also fixed some smaller bugs in the symmetric diff (like accidentantly removed whitespace).
=> Improve symmetric diff

.github/ISSUE_TEMPLATE.md
Hide the comment
`Hint: If you use a [development version](http://builds.jabref.org/master/), ensure that you use the latest one.`
for new issues. (i.e. it is still displayed in the edit dialog but not in the posted issue)
=> Hide helpful comments in issue reports

src/main/java/net/sf/jabref/gui/desktop/os/Windows.java
This should work with query strings like
`http://books.google.de/books?id=0yaM63MuqckC&lpg=PA153&ots=0H7EqpbM79&lr&hl=de&pg=PA153#v=onepage&q&f=false`
and normal URLs.
However, the question is:
Does this impact the opening of any other file path or anything? We need to be careful as this is a generic open method. Maybe that's also the problem because it needs to handle any kind of URI.
@Siedlerchr @tobiasdiez Please take a look.
=> Fix #1347 Open URLs does not work with query strings

CHANGELOG.md, src/main/java/net/sf/jabref/gui/worker/MarkEntriesAction.java, src/main/resources/l10n/JabRef_da.properties, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fa.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_in.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_nl.properties, src/main/resources/l10n/JabRef_no.properties, src/main/resources/l10n/JabRef_pt_BR.properties, src/main/resources/l10n/JabRef_ru.properties, src/main/resources/l10n/JabRef_sv.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_vi.properties, src/main/resources/l10n/JabRef_zh.properties
Added a textual description for the functionality "Mark Specific Color" since some Look and Feels (including the OSX one) do not consider the Background and Foreground color (at least for) JMenuItem
the current fix at least provides some kind of indicator of the level instead of a blank field as before
=> preliminary fix for #1340

CHANGELOG.md, src/integrationTest/java/net/sf/jabref/gui/UndoTest.java, src/main/java/net/sf/jabref/specialfields/SpecialFieldDatabaseChangeListener.java
Workaround for #796.
When an undo with multiple entries is undone, each entry is undone one at a time. The Problem herein lies, that when the first entry is undone, the insertion in the database triggers the creation and insertion of an NamedCompund into the UndoManager which kills the main Undo (the one with the multiple entries), which result in just one entry being undone.
With this Workaround each entry has its own NamedCompund which solves the Problem but the user has to call the UndoAction several times (Ctrl-Z for each entry).
=> [WIP] Fix for undoing deletion/cutting multiple entries

CHANGELOG.md, src/main/java/net/sf/jabref/gui/DuplicateResolverDialog.java, src/main/java/net/sf/jabref/gui/ImportInspectionDialog.java, src/test/java/net/sf/jabref/importer/fetcher/CrossRefTest.java
Fix for #1353
Fixed some missing unlocks
Some formatting
=> Update Preview Panel on Generate BibtexKey

src/main/java/net/sf/jabref/gui/SaveOrderConfigDisplay.java, src/main/java/net/sf/jabref/gui/dbproperties/DatabasePropertiesDialog.java, src/main/java/net/sf/jabref/logic/config/SaveOrderConfig.java
The logic is fucked but this should fix the issue.
Problem was that when sort in original order was selected, the corresponding variable newSortOrder would still read the disabled sort order inside the JDialog.
=> Fix sorting issue #1357

CHANGELOG.md, src/main/java/net/sf/jabref/gui/desktop/os/Windows.java
Runtime.exec with a String splits on white spaces...
=> Fix #1381 File links containing blanks are broken if non-default viewer is set

src/main/java/net/sf/jabref/gui/openoffice/StyleSelectDialog.java, src/main/java/net/sf/jabref/logic/openoffice/OOBibStyle.java, src/main/java/net/sf/jabref/logic/openoffice/StyleLoader.java, src/test/java/net/sf/jabref/logic/openoffice/StyleLoaderTest.java
Follow up from #1294 
NPE was raised in Comparator because name was initialized with null instead of Empty string
Only store preferences if style is valid
@oscargus  The fix has the side effect that a file where the name can not be parsed correctly is displayed as "Empty style". I attached the problematic style file which was provided in #1294 
However: Valid still returns true. 
As you have worked recently with the styles things, do you know what is required for a jstyle? @koppor  Maybe you know this?
Then we could improved the validity check 
[campus_format.english.txt](https://github.com/JabRef/jabref/files/247561/campus_format.english.txt)
=> Fix NPE on selecting invalid jstyle

src/main/java/net/sf/jabref/gui/PreviewPanel.java
This bug caused a "missing event subscriber" exception, when clicking on different bib entries in preview mode.
=> Fix small event bug in PreviewPanel.java

src/main/java/net/sf/jabref/exporter/ExportFormat.java, src/main/java/net/sf/jabref/exporter/ExportFormats.java, src/test/java/net/sf/jabref/exporter/HtmlExportFormatTest.java
Always write the footer, no matter if encoding is given or not.
=> Fix #1399 export to html: html code is not well-formed

CHANGELOG.md, src/main/java/net/sf/jabref/importer/fetcher/GVKParser.java, src/main/java/net/sf/jabref/importer/fileformat/MedlineHandler.java, src/main/java/net/sf/jabref/logic/util/strings/StringUtil.java, src/test/java/net/sf/jabref/logic/util/strings/StringUtilTest.java, src/test/java/net/sf/jabref/model/entry/AuthorTest.java
Reasoning:
- only used by a few importers and not consistently so
- better handled by cleanup actions / converter
- duplicates logic to parse list of author names (while the AuthorList.parse method is far superior)
- results in discussion about string joiner and builder in #547 :smile_cat:
=> Remove StringUtil.expandAuthorInitials

src/main/java/net/sf/jabref/gui/groups/GroupTreeNodeViewModel.java, src/main/java/net/sf/jabref/logic/groups/AbstractGroup.java, src/main/java/net/sf/jabref/logic/groups/ExplicitGroup.java, src/main/java/net/sf/jabref/model/entry/BibEntry.java, src/test/java/net/sf/jabref/logic/groups/AbstractGroupTest.java
Fix of #1334. Nice bonus: total number of entries is displayed after "All Entries" group.
=> Fix #1334: Display correct number of entries in static groups

CONTRIBUTING.md, build.gradle, localization.gradle
We can now
I started this attempt with:
- Include localization tasks and package into a group
=> Refactor Gradle script

CHANGELOG.md, src/main/java/net/sf/jabref/gui/fieldeditors/contextmenu/CaseChangeMenu.java, src/main/java/net/sf/jabref/gui/fieldeditors/contextmenu/ConversionMenu.java
=> Fix #1342: Show description of case converters as tooltip

src/main/java/net/sf/jabref/logic/util/strings/StringUtil.java, src/test/java/net/sf/jabref/importer/fileformat/MedlineImporterTest.java, src/test/java/net/sf/jabref/importer/fileformat/MedlineImporterTestFiles.java, src/test/resources/net/sf/jabref/importer/fileformat/MedlineImporterTestArticleID.bib, src/test/resources/net/sf/jabref/importer/fileformat/MedlineImporterTestArticleID.xml, src/test/resources/net/sf/jabref/importer/fileformat/MedlineImporterTestMalformedEntry.xml, src/test/resources/net/sf/jabref/importer/fileformat/MedlineImporterTestMinimalEntry.bib, src/test/resources/net/sf/jabref/importer/fileformat/MedlineImporterTestMinimalEntry.xml, src/test/resources/net/sf/jabref/importer/fileformat/MedlineImporterTestSingleEntry.bib, src/test/resources/net/sf/jabref/importer/fileformat/MedlineImporterTestSingleEntry.xml
New PR started because the old one was on a wrong branch.
MedlineImporTest + Testfile added
Couldn't cover two exceptions in importEntries.
=> [WIP] MedlineImporterTest

src/integrationTest/java/net/sf/jabref/gui/AbstractUITest.java, src/integrationTest/java/net/sf/jabref/gui/EntryTableTest.java, src/integrationTest/java/net/sf/jabref/gui/GUITest.java, src/integrationTest/java/net/sf/jabref/gui/UndoTest.java
I wrote a ui-test for the following use case:
I import a bib-file into a new database.
Then I double-click on the first entry in the database to open up the entry editor.
Then I click back into the table and start scrolling through the entries.
When I do that, the table should always keep the focus.
This test case tests the following pull-requests enhancement: #988
It also referes to the discussion about ui-testing: #507
=> Scrollingthroughentrylisttest

CHANGELOG.md, src/main/java/net/sf/jabref/event/EntryAddedEvent.java, src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/undo/UndoableRemoveEntry.java, src/main/java/net/sf/jabref/model/database/BibDatabase.java
When undoing an entry which was deleted/cut while a group was selected of which the entry wasn't a member of it was after the undo.
I fixed that.
- delete an entry
- select a group of which the entry wasn't a member of
- undo the deletion
- now the entry is a member of the group
=> Entries retain their groupmembership when undoing their cut/deletion

CHANGELOG.md, src/main/java/net/sf/jabref/gui/BasePanel.java
This fixes #1450 
After changing the preferences the mainTable is using a new `SplitPane` object to divide table and `EntryEditor` - in the course of creating the actual table existing entryEditors are closed which causes a saving of the current `EntryEditor` height in the prefs. As this is calculated based on the (already new) `SplitPane` a wrong value "1" is stored.
To prevent this the previous state of the divider for the SplitPane is restored based on the prefs before the mainTable is recreated.
=> Fix for #1450

src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/specialfields/Printed.java, src/main/java/net/sf/jabref/specialfields/Priority.java, src/main/java/net/sf/jabref/specialfields/Quality.java, src/main/java/net/sf/jabref/specialfields/Rank.java, src/main/java/net/sf/jabref/specialfields/ReadStatus.java, src/main/java/net/sf/jabref/specialfields/Relevance.java, src/main/java/net/sf/jabref/specialfields/SpecialField.java, src/main/java/net/sf/jabref/specialfields/SpecialFieldAction.java, src/main/java/net/sf/jabref/specialfields/SpecialFieldValue.java, src/main/resources/l10n/JabRef_da.properties, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fa.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_in.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_nl.properties, src/main/resources/l10n/JabRef_no.properties, src/main/resources/l10n/JabRef_pt_BR.properties, src/main/resources/l10n/JabRef_ru.properties, src/main/resources/l10n/JabRef_sv.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_vi.properties, src/main/resources/l10n/JabRef_zh.properties
The status messages for some specialfields have not been translated correctly (missing localization has not been detected automatically as a variable has been used.)
=> Add missing status translations for various specialfields

CHANGELOG.md, src/jmh/java/net/sf/jabref/benchmarks/Benchmarks.java, src/main/java/net/sf/jabref/logic/formatter/bibtexfields/HtmlToLatexFormatter.java, src/main/java/net/sf/jabref/logic/formatter/bibtexfields/UnicodeToLatexFormatter.java, src/main/java/net/sf/jabref/logic/util/strings/HTMLUnicodeConversionMaps.java, src/test/java/net/sf/jabref/logic/cleanup/CleanupWorkerTest.java, src/test/java/net/sf/jabref/logic/formatter/bibtexfields/HtmlToLatexFormatterTest.java, src/test/java/net/sf/jabref/logic/formatter/bibtexfields/UnicodeConverterTest.java
The HTML/Unicode <-> LaTeX conversion map source was based on regular expressions making it a jungle of backslashes. Now, replace is used instead of replaceAll so fewer backslashes and (theoretically) a bit faster.
I also added benchmarking for the following conversions:
* HTML to LaTeX (used at import, cleanup and save action)
* LaTeX to HTML (used for preview)
* LaTeX to Unicode (used for table rendering)
and I got a slight improvement, although I cannot really tell why the two latter are faster now as they are based on cleaned versions... One reason might be that the tests are based on LaTeX symbols with more backslashes in them for the old case...
Before:
Benchmarks.htmlToLatexConversion      5533.070 ▒   86.148  ops/s
Benchmarks.latexToHTMLConversion     141500.226 ▒ 8011.038  ops/s …
=> Improved conversion maps and conversion speed

CHANGELOG.md, src/main/java/net/sf/jabref/JabRefPreferences.java, src/main/java/net/sf/jabref/gui/labelpattern/LabelPatternPanel.java, src/main/java/net/sf/jabref/sql/importer/DbImportAction.java
- Use the default mode set inside the Preferences for each import from an external SQL database
- Add new method for getting the default DB mode from the preferences
- Use the preferences method where necessary
=> Fix #1476 NPE when importing from SQL DB because of missing DatabaseMode

src/main/java/net/sf/jabref/JabRefPreferences.java, src/main/java/net/sf/jabref/MetaData.java, src/main/java/net/sf/jabref/exporter/BibDatabaseWriter.java, src/main/java/net/sf/jabref/exporter/FieldFormatterCleanups.java, src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java, src/main/java/net/sf/jabref/logic/CustomEntryTypesManager.java, src/main/java/net/sf/jabref/logic/cleanup/CleanupPreset.java, src/main/java/net/sf/jabref/logic/config/SaveOrderConfig.java, src/main/java/net/sf/jabref/logic/groups/GroupTreeNode.java, src/main/java/net/sf/jabref/logic/groups/GroupsParser.java, src/main/java/net/sf/jabref/model/database/BibDatabaseMode.java, src/main/java/net/sf/jabref/model/entry/CustomEntryType.java, src/test/java/net/sf/jabref/MetaDataTest.java
According to the following conventions:
- All objects which can be read from a string have `public static Type parse(Stringy input)` method.
- All objects which can be written to a string have a `public Stringy getAsString()` method.
Should fix #888.
--
=> Refactor placement of parsing and writing logic

CHANGELOG.md, src/main/java/net/sf/jabref/gui/groups/GroupDialog.java, src/main/java/net/sf/jabref/logic/groups/ExplicitGroup.java, src/main/java/net/sf/jabref/util/Util.java
Reason for this bug: ExplicteGroup now derives from KeywordGroup and thus was sometimes displayed as a keyword group.
=> Fix #1434: Static groups are now longer displayed as dynamic ones

CHANGELOG.md, src/main/java/net/sf/jabref/gui/groups/GroupTreeNodeViewModel.java, src/main/java/net/sf/jabref/logic/groups/AbstractGroup.java, src/main/java/net/sf/jabref/logic/groups/GroupTreeNode.java, src/test/java/net/sf/jabref/logic/groups/AbstractGroupTest.java, src/test/java/net/sf/jabref/logic/groups/GroupTreeNodeTest.java
The issue was that, for the number of hits, JabRef only checked if the
group taken separately matched the entry. That is, it was completely
ignored that the group sits in a tree and might be set up to refine the
search of the parent. Taking the example given in #1482, 577 entries
satisfy the condition `articlé original` but only 38 are also matched by
`articlé`.
=> Fixes #1482: Correct number of matched entries is displayed for refining subgroups

CHANGELOG.md, config/checkstyle/checkstyle.xml, src/main/java/net/sf/jabref/JabRefMain.java, src/main/java/net/sf/jabref/gui/FXAlert.java, src/main/java/net/sf/jabref/gui/JabRefFrame.java, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java, src/main/java/net/sf/jabref/gui/help/AboutAction.java, src/main/java/net/sf/jabref/gui/help/AboutDialogView.java, src/main/java/net/sf/jabref/gui/help/AboutDialogViewModel.java, src/main/resources/l10n/JabRef_da.properties, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fa.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_in.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_nl.properties, src/main/resources/l10n/JabRef_no.properties, src/main/resources/l10n/JabRef_pt_BR.properties, src/main/resources/l10n/JabRef_ru.properties, src/main/resources/l10n/JabRef_sv.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_vi.properties, src/main/resources/l10n/JabRef_zh.properties
If the `MRNumber` field is present in the entry, then a new tab is added which shows the associated MathSciNet review. (Note that MathSciNet is probably _the_ reference for all mathematicians).
This PR is against the javafx branch since the javafx control WebView is used to show the webpage.
@JabRef/stupro also have a look at this PR, since you are the ones with JavaFX experience.
=> Add MathSciNet tab

src/main/java/net/sf/jabref/logic/l10n/Localization.java, src/main/java/net/sf/jabref/logic/l10n/LocalizationBundle.java
As discussed in https://github.com/JabRef/jabref/pull/968, JavaFX just calls "ResoucreBundle.getString" instead of using our methods in `Localization`. Thus entries like `Copy Version` are not found since they are stored as `Copy_Version`. This PR provides a wrapper which converts keys and translation properly.
=> Support language keys with spaces for JavaFX

eclipse.gradle
The eclipse import order settings don't cover javafx packages but the file checkstyle.xml does. Therefore using "organize import" in eclipse gave wrong import order warnings at travis CI.
=> Added import order for javafx packages to the eclipse settings

CHANGELOG.md, src/main/java/net/sf/jabref/importer/ImportFileFilter.java, src/test/java/net/sf/jabref/importer/ImportFileFilterTest.java
Fixes #1431. 
The open dialog of the `importer import into (new | current) database` now shows the filextensions behind the filetypename and filters the view based on it (if no extension is know it shows all files).
Right now almost no extensions are known, but this should change when #1487 is merged.
=> Import dialog shows file extensions and filters the view

src/main/java/net/sf/jabref/logic/util/Version.java, src/test/java/net/sf/jabref/logic/util/version/VersionTest.java
Just running the compiled version without using gradle resulted in a NumberFormatException since the version update was based on the wrong version string `${version}`. This is fixed with this PR (also in this case no update notification is shown).
=> Fix update notification for developer builds

CHANGELOG.md, src/main/java/net/sf/jabref/gui/labelpattern/ResolveDuplicateLabelDialog.java, src/main/java/net/sf/jabref/gui/labelpattern/SearchFixDuplicateLabels.java
Added an "Ignore" button to the duplicate key resolving dialog and changed the behavior of cancel and close key such that the complete key resolving process is cancelled.
Not sure how to refer to the discourse topic.
=> Minor improvement for duplicate key resolving dialog

CHANGELOG.md, src/main/resources/resource/layout/html.begin.layout
Added a content type tag (and fixed tag name, head instead of header) to fix #1484.
=> Added content-type heading for HTML export fixing #1484

src/main/java/net/sf/jabref/gui/entryeditor/FieldExtraComponents.java
Using the drop down resulted in strings like `##jan##`. Now, the correct `#jan#` is obtained.
=> Corrected month value when using drop-down in entry editor

CHANGELOG.md, src/main/java/net/sf/jabref/gui/EntryMarker.java
Marking of imported entries should work again (#1534). Not really sure why I introduced that bug. Looking back at the code https://github.com/JabRef/jabref/commit/8d9c806eb41b809822e3acadc9299315850bd10c it doesn't really make sense to do as I did...
=> Fixed #1534

src/main/java/net/sf/jabref/gui/groups/AddToGroupAction.java, src/main/java/net/sf/jabref/gui/groups/GroupDialog.java, src/main/java/net/sf/jabref/gui/groups/GroupsTree.java, src/main/java/net/sf/jabref/gui/groups/RemoveFromGroupAction.java, src/main/java/net/sf/jabref/gui/groups/WarnAssignmentSideEffects.java, src/main/java/net/sf/jabref/sql/importer/DbImportAction.java
Final methods moved from Util and the class finally removed. I'm sure the DbImportAction can be improved by using `Thread.start()`, but this seems like a generic problem for JabRef.
=> Moved final methods from Util

CHANGELOG.md, src/main/java/net/sf/jabref/logic/integrity/IntegrityCheck.java, src/test/java/net/sf/jabref/logic/integrity/IntegrityCheckTest.java
=> Fix 1530: Integrity checker should ignore unescaped hashes in url field

CHANGELOG.md, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java, src/main/java/net/sf/jabref/gui/entryeditor/FieldExtraComponents.java, src/main/java/net/sf/jabref/gui/maintable/MainTableSelectionListener.java, src/main/java/net/sf/jabref/model/database/BibDatabase.java, src/main/java/net/sf/jabref/model/entry/FieldProperties.java, src/main/java/net/sf/jabref/model/entry/InternalBibtexFields.java
Based on the idea in #1338 a button is added in the crossref entry editor field to select the parent entry in the main table. It is not exactly the same thing as suggested in #1338 though.
=> Added button to crossref entry editor field to select parent entry

CHANGELOG.md, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java
Fixed a bug where the field change compound was not ended, leading to that field changes could not be undone when "automatically update time stamp on edit" was enabled.
=> Fixed undo when update time stamp on edit is enabled

CHANGELOG.md, src/main/java/net/sf/jabref/gui/groups/AutoGroupDialog.java, src/main/java/net/sf/jabref/gui/groups/GroupDialog.java, src/main/java/net/sf/jabref/gui/groups/GroupSelector.java, src/main/java/net/sf/jabref/gui/groups/GroupTreeNodeViewModel.java, src/main/java/net/sf/jabref/gui/groups/UndoableAddOrRemoveGroup.java, src/main/java/net/sf/jabref/logic/groups/GroupTreeNode.java, src/main/java/net/sf/jabref/logic/groups/GroupsParser.java, src/main/java/net/sf/jabref/sql/importer/DatabaseImporter.java, src/test/java/net/sf/jabref/exporter/BibDatabaseWriterTest.java, src/test/java/net/sf/jabref/importer/ConvertLegacyExplicitGroupsTest.java, src/test/java/net/sf/jabref/logic/groups/GroupTreeNodeTest.java, src/test/java/net/sf/jabref/sql/DatabaseImportExportTests.java
Also moved the code responsible for carrying over previous assignments from the gui to logic; add tests for it.
=> Fix #1500: Renaming of explicit groups changes entries accordingly

jabref.install4j
Will delete the registry keys of JabRef on uninstall.
I'm not sure if we save anything that should permanently stay in the registry, custom entry types etc? Currently this reg key only hosts the Path word for me, which displays the installation location of JabRef.
=> Clean registry on uninstall

src/main/java/net/sf/jabref/gui/groups/GroupSelector.java, src/main/java/net/sf/jabref/logic/groups/KeywordGroup.java, src/main/java/net/sf/jabref/logic/util/strings/StringUtil.java, src/main/java/net/sf/jabref/model/entry/BibEntry.java, src/main/java/net/sf/jabref/model/entry/EntryUtil.java, src/test/java/net/sf/jabref/logic/groups/KeywordGroupTest.java
The BibEntry now stores a list of words which are contained in the field. in this way the KeywordGroup.isMatch method just has to compare two arrays instead of analyzing strings over and over again. For a big file (> 7000 entries, > 100 groups) the load time decreased by 1 sec from 4.8 seconds to 3.7. Half of the time needed for showing the groups tree is spent in calculating the number of hits. Moreover, subsequent rerendings of the groups tree (for example after changing an entry) are also quicker.
Note that the match algorithm changed slightly. For example, previously looking for `test` in `some$test` resulted in a match; this is no longer the case. However, normal word separators (like whitespace, comma and semicolon are recognized properly), i.e. searching for `test` in `some test` …
=> Performance improvements for groups

CHANGELOG.md, src/main/java/net/sf/jabref/Globals.java, src/main/java/net/sf/jabref/logic/formatter/bibtexfields/UnicodeToLatexFormatter.java, src/main/java/net/sf/jabref/logic/layout/format/LatexToUnicodeFormatter.java, src/main/java/net/sf/jabref/logic/util/strings/HTMLUnicodeConversionMaps.java, src/test/java/net/sf/jabref/logic/layout/format/LatexToUnicodeFormatterTest.java
I finally got around to understand the reasons for #1264 (and parts of #1464). It turned out that commands starting with c was handled in a special way and that `{\v{S}}` was for unknown reasons used as "line tabulation set".
As a result, not only does JabRef now render `\v{S}` and `\chi` correctly, it also renders combining accents, see screen shot.
=> Fixed #1264

src/jmh/java/net/sf/jabref/benchmarks/Benchmarks.java, src/main/java/net/sf/jabref/cli/ArgumentProcessor.java, src/main/java/net/sf/jabref/collab/ChangeScanner.java, src/main/java/net/sf/jabref/collab/FileUpdateMonitor.java, src/main/java/net/sf/jabref/exporter/AutoSaveManager.java, src/main/java/net/sf/jabref/exporter/BibDatabaseWriter.java, src/main/java/net/sf/jabref/exporter/BibtexDatabaseWriter.java, src/main/java/net/sf/jabref/exporter/ExportFormat.java, src/main/java/net/sf/jabref/exporter/FileSaveSession.java, src/main/java/net/sf/jabref/exporter/MSBibExportFormat.java, src/main/java/net/sf/jabref/exporter/ModsExportFormat.java, src/main/java/net/sf/jabref/exporter/SaveDatabaseAction.java, src/main/java/net/sf/jabref/exporter/SaveException.java, src/main/java/net/sf/jabref/exporter/SavePreferences.java, src/main/java/net/sf/jabref/exporter/SaveSession.java, src/main/java/net/sf/jabref/exporter/StringSaveSession.java, src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/importer/OpenDatabaseAction.java, src/main/java/net/sf/jabref/logic/util/io/FileBasedLock.java, src/main/java/net/sf/jabref/logic/util/strings/StringUtil.java, src/test/java/net/sf/jabref/exporter/BibtexDatabaseWriterTest.java, src/test/java/net/sf/jabref/exporter/MSBibExportFormatTestFiles.java, src/test/java/net/sf/jabref/exporter/MsBibExportFormatTest.java, src/test/resources/testbib/complex.bib
The main aim of this PR is to simplify the implementation of https://github.com/JabRef/jabref/pull/1451 (sql export) and other exporters.
- Abstract class BibDatabaseWriter, which controls the generic things of
writing a database (i.e. sorting entries, applying save actions, some
basic conversations, ...)
- Derived class BibtexDatabaseWriter, which only contains logic how to
actually write to in BibTeX format (should be simple to write similar
classes for other export formats like ris)
- Make SaveSession abstract and introduce two implementations which
write to a temporary file (FileSaveSession) or two a string/buffer
(StringSaveSession)
- Move code related to lock files to FileBasedLock
--
=> Refactor writing of bib files

CHANGELOG.md, src/main/java/net/sf/jabref/logic/integrity/ISBNChecker.java, src/main/java/net/sf/jabref/logic/integrity/IntegrityCheck.java, src/main/java/net/sf/jabref/logic/util/ISBN.java, src/test/java/net/sf/jabref/logic/integrity/IntegrityCheckTest.java
=> Added ISBN integrity checker

CHANGELOG.md, src/main/java/net/sf/jabref/gui/actions/IntegrityCheckAction.java
Added the possibility to dynamically filter out some classes of integrity check messages.
=> Added filter to not show selected integrity checks

CHANGELOG.md, src/main/java/net/sf/jabref/gui/FieldSetComponent.java
When using tab to navigate through the entry customization dialog, the lists now selects the first entry to give visual feedback when they are selected and to enable the up and down buttons functionality.
=> The customize entry dialogs field list gets the focus as soon as it is focused

src/main/java/net/sf/jabref/importer/CustomImporter.java, src/test/java/net/sf/jabref/importer/CustomImporterTest.java
Create a test for CustomImporter.java
=> Test CustomImporter

src/main/java/net/sf/jabref/external/WriteXMPAction.java, src/main/java/net/sf/jabref/external/WriteXMPEntryEditorAction.java, src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/FindUnlinkedFilesDialog.java, src/main/java/net/sf/jabref/gui/GUIGlobals.java, src/main/java/net/sf/jabref/gui/desktop/JabRefDesktop.java, src/main/java/net/sf/jabref/gui/maintable/MainTableFormat.java, src/main/java/net/sf/jabref/importer/OAI2Handler.java, src/main/java/net/sf/jabref/importer/fileformat/BiblioscapeImporter.java, src/main/java/net/sf/jabref/importer/fileformat/FreeCiteImporter.java, src/main/java/net/sf/jabref/logic/cleanup/CleanupWorker.java, src/main/java/net/sf/jabref/logic/exporter/OOCalcDatabase.java, src/main/java/net/sf/jabref/logic/exporter/OpenDocumentRepresentation.java, src/main/java/net/sf/jabref/logic/msbib/MSBibMapping.java, src/main/java/net/sf/jabref/logic/xmp/XMPUtil.java, src/main/java/net/sf/jabref/migrations/FileLinksUpgradeWarning.java, src/main/java/net/sf/jabref/model/entry/BibLatexEntryTypes.java, src/main/java/net/sf/jabref/model/entry/BibtexEntryTypes.java, src/main/java/net/sf/jabref/model/entry/EntryConverter.java, src/main/java/net/sf/jabref/model/entry/FieldName.java, src/main/java/net/sf/jabref/model/entry/InternalBibtexFields.java
I guess `"publishers"` in `XMPUtil` was a typo?
=> Added more fields and fixed some issues

CHANGELOG.md, src/main/java/net/sf/jabref/gui/cleanup/CleanupPresetPanel.java, src/main/java/net/sf/jabref/logic/cleanup/CleanupPreset.java, src/main/java/net/sf/jabref/logic/cleanup/CleanupWorker.java, src/main/java/net/sf/jabref/logic/cleanup/ISSNCleanup.java, src/main/java/net/sf/jabref/logic/integrity/ISSNChecker.java, src/main/java/net/sf/jabref/logic/util/ISBN.java, src/main/java/net/sf/jabref/logic/util/ISSN.java, src/main/java/net/sf/jabref/preferences/JabRefPreferences.java, src/main/resources/l10n/JabRef_da.properties, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fa.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_in.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_nl.properties, src/main/resources/l10n/JabRef_no.properties, src/main/resources/l10n/JabRef_pt_BR.properties, src/main/resources/l10n/JabRef_ru.properties, src/main/resources/l10n/JabRef_sv.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_vi.properties, src/main/resources/l10n/JabRef_zh.properties, src/test/java/net/sf/jabref/logic/cleanup/CleanupWorkerTest.java, src/test/java/net/sf/jabref/logic/cleanup/ISSNCleanupTest.java, src/test/java/net/sf/jabref/logic/util/ISBNTest.java, src/test/java/net/sf/jabref/logic/util/ISSNTest.java
Implemented cleanup that adds a missing dash in the ISSN field if it looks like an ISSN (checksum is not controlled, but eight digits, where the last may be an x).
=> Implemented #1345 - cleanup ISSN

src/main/java/net/sf/jabref/gui/openoffice/StyleSelectDialog.java, src/main/java/net/sf/jabref/gui/preftabs/PreviewPrefsTab.java, src/main/java/net/sf/jabref/logic/util/TestEntry.java
While working on #1602 I realized that the preview entries used deprecated fields, so I updated them and improved the casing a bit.
=> Updated preview entries

CHANGELOG.md, src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/ImportInspectionDialog.java, src/main/java/net/sf/jabref/gui/date/DatePickerButton.java, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java, src/main/java/net/sf/jabref/gui/entryeditor/FieldExtraComponents.java, src/main/java/net/sf/jabref/gui/plaintextimport/TextInputDialog.java, src/main/java/net/sf/jabref/gui/preftabs/GeneralTab.java, src/main/java/net/sf/jabref/importer/AppendDatabaseAction.java, src/main/java/net/sf/jabref/importer/EntryFromPDFCreator.java, src/main/java/net/sf/jabref/importer/ImportMenuItem.java, src/main/java/net/sf/jabref/importer/ZipFileChooser.java, src/main/java/net/sf/jabref/logic/layout/format/CurrentDate.java, src/main/java/net/sf/jabref/logic/net/Cookie.java, src/main/java/net/sf/jabref/logic/util/UpdateField.java, src/main/java/net/sf/jabref/logic/util/date/EasyDateFormat.java, src/main/java/net/sf/jabref/logic/util/date/TimeStamp.java, src/main/java/net/sf/jabref/model/entry/FieldProperties.java, src/main/java/net/sf/jabref/model/entry/InternalBibtexFields.java, src/main/java/net/sf/jabref/pdfimport/PdfImporter.java, src/test/java/net/sf/jabref/logic/net/CookieTest.java
Based on the discussion in another PR (primarily @Siedlerchr as I recall) the date selector now returns the date in ISO format when applicable. Basically, it returns in ISO format for all BibLatex fields related to dates, while e.g. timestamp is still based on the preferences (there is a property `FieldProperties.ISO_DATE` which can be set to enable ISO format).
I also replaced some of the SimpelDateFormat usage with the new thread safe API.
Question: should we still support a user defined date format?
=> Some enhancements and cleanups related to dates

medline.gradle
I defined the input/output dirs for xjc in the configuration phase. Now the Task will only executed if the input/output dir has changed which will speed up starting JabRef with Gradle a little.
~~- [ ] Change in CHANGELOG.md described~~
=> [WIP] Define xjc input/ouput dir (subsequent builds will be faster)

CHANGELOG.md, src/main/java/net/sf/jabref/gui/mergeentries/MergeEntries.java, src/main/java/net/sf/jabref/gui/util/component/DiffHighlightingTextPane.java, src/main/java/net/sf/jabref/logic/util/strings/DiffHighlighting.java
In earlier versions, the column headings were wrong when merging two entries from the database after information had been merged from DOI. This fixes that (removed `static` for the heading strings).
Also refactored the code a bit and extracted `DiffHighlightingTextPane` which may be useful elsewhere (such as in the external change viewer).
=> Fixed a minor issue and refactored MergeEntries

src/test/java/net/sf/jabref/logic/layout/LayoutTest.java, src/test/java/net/sf/jabref/logic/net/CookieTest.java, src/test/java/net/sf/jabref/logic/util/strings/StringUtilTest.java
A few more tests of Cookie, StringUtil.intValueOfWithNull, and reenabling some tests for Layout.
=> More tests

build.gradle, src/test/java/net/sf/jabref/importer/CustomImporterTest.java
Version 2.0.11 should have solved the issue making 2.0.10 unusable. As I did not face the problem, I have no idea if it actually is working though...
=> Updated Errorprone to 2.0.11

CHANGELOG.md, src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java, src/main/java/net/sf/jabref/model/entry/BibEntry.java, src/test/java/net/sf/jabref/importer/fileformat/BibtexParserTest.java, src/test/resources/testbib/bibWithUserCommentAndEntryChange.bib, src/test/resources/testbib/bibWithUserComments.bib
Implements #1632. User comments marked by `@Comment` are now kept in the bib file, regardless of whether they use brackets or not.
=> Keep @Comment text in a bib file

CHANGELOG.md, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java, src/main/java/net/sf/jabref/gui/journals/ManageJournalsPanel.java, src/main/java/net/sf/jabref/gui/maintable/SpecialMainTableColumns.java, src/main/java/net/sf/jabref/gui/plaintextimport/TextInputDialog.java, src/main/java/net/sf/jabref/importer/AppendDatabaseAction.java, src/main/java/net/sf/jabref/importer/CustomImporter.java, src/main/java/net/sf/jabref/logic/groups/AllEntriesGroup.java, src/main/java/net/sf/jabref/logic/groups/KeywordGroup.java, src/main/java/net/sf/jabref/logic/integrity/IntegrityCheck.java, src/main/java/net/sf/jabref/logic/mods/MODSEntry.java, src/main/java/net/sf/jabref/logic/xmp/XMPUtil.java, src/main/java/net/sf/jabref/model/entry/BibEntry.java, src/main/java/net/sf/jabref/model/entry/CanonicalBibtexEntry.java, src/main/java/net/sf/jabref/specialfields/SpecialField.java
Thanks to @Siedlerchr reminding me about the brilliance of Optional, I decided to try and convert some BibEntry.getField to BibEntry.getFieldOptional in a "proper" way. I managed in a few positions, but more importantly i reinstalled Find bugs as a consequence of this. 
I found a few quite bad bugs, such as NPEs when clicking "Browse" in the journal management dialog with an empty text field. Also, there where some other example of introducing requireNonNull without really checking that all existing calling functions did call without a null hard coded...
@Siedlerchr as I know that you are a big fan of Path, Find bugs complains that some method there is quite likely to return null (I think getPath()), so stacking a number of method calls is claimed to be risky.
Still a few to be fixed …
=> Replaced some getField and fixed some bugs

CHANGELOG.md, src/main/java/net/sf/jabref/importer/fetcher/GoogleScholarFetcher.java
Fixed #1639 as Google now moved the link generation to http://scholar.googleusercontent.com the full link is now provided.
=> Fixed #1639

CHANGELOG.md, src/main/java/net/sf/jabref/gui/JabRefFrame.java, src/main/java/net/sf/jabref/gui/openoffice/CreationException.java, src/main/java/net/sf/jabref/gui/openoffice/OOBibBase.java, src/main/java/net/sf/jabref/gui/openoffice/OpenOfficePanel.java, src/main/java/net/sf/jabref/logic/exporter/OpenDocumentSpreadsheetCreator.java, src/main/java/net/sf/jabref/logic/openoffice/OOUtil.java, src/main/resources/l10n/JabRef_da.properties, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fa.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_in.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_nl.properties, src/main/resources/l10n/JabRef_no.properties, src/main/resources/l10n/JabRef_pt_BR.properties, src/main/resources/l10n/JabRef_ru.properties, src/main/resources/l10n/JabRef_sv.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_vi.properties, src/main/resources/l10n/JabRef_zh.properties
Based on a forum discussion, http://discourse.jabref.org/t/export-a-bibtex-file-with-all-papers-cited-in-a-doc-via-ooplugin/87 . 40 minutes later.
=> Export OO/LO citations to new database

src/main/java/net/sf/jabref/gui/openoffice/OOBibBase.java, src/main/java/net/sf/jabref/importer/ImportFileFilter.java, src/main/java/net/sf/jabref/importer/fileformat/ImportFormat.java, src/main/java/net/sf/jabref/logic/groups/ExplicitGroup.java, src/main/java/net/sf/jabref/logic/groups/KeywordGroup.java, src/main/java/net/sf/jabref/logic/groups/SearchGroup.java, src/main/java/net/sf/jabref/logic/openoffice/CitationEntry.java, src/main/java/net/sf/jabref/logic/openoffice/OOBibStyle.java, src/main/java/net/sf/jabref/model/entry/CustomEntryType.java
I might regret this, but I tried to unify some of the equals considering the discussion in #1631. The style is not completely identical, but the ideas are there at least.
Looking at the `equals` in `ProxyPreferences` and `FieldChange` one can conclude that hopefully that code is automatically generated, although it might not be the best way to generate that code...
In some classes implementing `Formatter`, `equals` and `hashCode` are overridden by `defaultEquals` and `defaultHashCode` but in most not. Not really clear how this really should be.
=> Unified some equals

src/main/java/net/sf/jabref/gui/openoffice/OOBibBase.java, src/main/java/net/sf/jabref/gui/openoffice/OpenOfficePanel.java, src/main/java/net/sf/jabref/logic/openoffice/UndefinedBibtexEntry.java, src/main/resources/l10n/JabRef_da.properties, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fa.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_in.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_nl.properties, src/main/resources/l10n/JabRef_no.properties, src/main/resources/l10n/JabRef_pt_BR.properties, src/main/resources/l10n/JabRef_ru.properties, src/main/resources/l10n/JabRef_sv.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_vi.properties, src/main/resources/l10n/JabRef_zh.properties
By using a shorter text for the button introduced in #1630 , it is possible to make it more narrow. Now, "OpenOffice/LibreOffice" is limiting the width.
Some small refactorings.
=> Made possible to make the OO/LO panel a bit more narrow

src/main/java/net/sf/jabref/cli/ArgumentProcessor.java, src/main/java/net/sf/jabref/cli/JabRefCLI.java, src/main/java/net/sf/jabref/external/ExternalFileTypes.java, src/main/java/net/sf/jabref/gui/DuplicateSearch.java, src/main/java/net/sf/jabref/gui/groups/EntryTableTransferHandler.java, src/main/java/net/sf/jabref/importer/EntryFromPDFCreator.java, src/main/java/net/sf/jabref/importer/ParserResult.java, src/main/java/net/sf/jabref/pdfimport/PdfImporter.java, src/test/java/net/sf/jabref/cli/JabRefCLITest.java, src/test/java/net/sf/jabref/importer/fileformat/BibtexParserTest.java
=> Replaced some array return types

src/main/java/net/sf/jabref/external/RegExpFileSearch.java, src/main/java/net/sf/jabref/logic/exporter/OpenDocumentRepresentation.java, src/main/java/net/sf/jabref/logic/layout/LayoutEntry.java, src/main/java/net/sf/jabref/logic/openoffice/OOBibStyle.java, src/main/java/net/sf/jabref/logic/xmp/XMPSchemaBibtex.java, src/main/java/net/sf/jabref/model/database/BibDatabase.java, src/main/java/net/sf/jabref/model/entry/BibEntry.java
A bit weird that there are no explicit tests at all for `getResolvedField`...
=> Replaced output of getResolvedField to Optional<String>

src/jmh/java/net/sf/jabref/benchmarks/Benchmarks.java, src/main/java/net/sf/jabref/gui/help/HelpAction.java, src/main/java/net/sf/jabref/gui/openoffice/OOBibBase.java, src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java, src/main/java/net/sf/jabref/logic/groups/AllEntriesGroup.java, src/main/java/net/sf/jabref/model/database/EntrySorter.java, src/test/java/net/sf/jabref/importer/fileformat/PdfContentImporterTest.java, src/test/java/net/sf/jabref/importer/fileformat/PdfXmpImporterTest.java
=> Removed thrown Exception declarations

src/main/java/net/sf/jabref/collab/EntryChange.java, src/main/java/net/sf/jabref/collab/EntryDeleteChange.java, src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/ImportInspectionDialog.java, src/main/java/net/sf/jabref/gui/PreviewPanel.java, src/main/java/net/sf/jabref/gui/actions/IntegrityCheckAction.java, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditorTab.java, src/main/java/net/sf/jabref/gui/fieldeditors/FileListEditor.java, src/main/java/net/sf/jabref/gui/push/PushToApplicationAction.java, src/main/java/net/sf/jabref/logic/autocompleter/BibtexKeyAutoCompleter.java, src/main/java/net/sf/jabref/logic/integrity/IntegrityMessage.java, src/main/java/net/sf/jabref/logic/util/io/FileUtil.java, src/main/java/net/sf/jabref/model/FieldChange.java, src/main/java/net/sf/jabref/model/database/BibDatabase.java, src/main/java/net/sf/jabref/model/entry/BibEntry.java, src/main/java/net/sf/jabref/model/entry/CanonicalBibtexEntry.java, src/test/java/net/sf/jabref/importer/OpenDatabaseActionTest.java, src/test/java/net/sf/jabref/importer/fetcher/OAI2HandlerFetcherTest.java, src/test/java/net/sf/jabref/importer/fileformat/BibtexParserTest.java, src/test/java/net/sf/jabref/logic/bst/TestVM.java, src/test/java/net/sf/jabref/logic/xmp/XMPSchemaBibtexTest.java, src/test/java/net/sf/jabref/logic/xmp/XMPUtilTest.java, src/test/java/net/sf/jabref/model/database/BibDatabaseTest.java, src/test/java/net/sf/jabref/model/entry/BibEntryTests.java
There are some interesting consequences in the code. Or rather it is clear that in quite a few places the code breaks with a `null` cite key.
=> Introduced method getCiteKeyOptional and made getCiteKey deprecated

src/main/java/net/sf/jabref/logic/openoffice/OpenOfficePreferences.java, src/test/java/net/sf/jabref/logic/bibtex/EntryTypesTestBibLatex.java, src/test/java/net/sf/jabref/logic/bibtex/EntryTypesTestBibtex.java, src/test/java/net/sf/jabref/logic/bibtex/FieldContentParserTest.java, src/test/java/net/sf/jabref/logic/formatter/FormatterTest.java, src/test/java/net/sf/jabref/logic/formatter/bibtexfields/HtmlToLatexFormatterTest.java, src/test/java/net/sf/jabref/logic/formatter/bibtexfields/UnicodeConverterTest.java, src/test/java/net/sf/jabref/logic/groups/ExplicitGroupTest.java, src/test/java/net/sf/jabref/logic/groups/GroupTreeNodeTest.java, src/test/java/net/sf/jabref/logic/groups/KeywordGroupTest.java, src/test/java/net/sf/jabref/logic/groups/SearchGroupTest.java, src/test/java/net/sf/jabref/logic/journals/AbbreviationsTest.java, src/test/java/net/sf/jabref/logic/labelpattern/LabelPatternUtilTest.java, src/test/java/net/sf/jabref/logic/layout/LayoutTest.java, src/test/java/net/sf/jabref/logic/layout/format/FileLinkTest.java, src/test/java/net/sf/jabref/logic/net/URLDownloadTest.java, src/test/java/net/sf/jabref/logic/openoffice/OOBibStyleTest.java, src/test/java/net/sf/jabref/logic/openoffice/StyleLoaderTest.java, src/test/java/net/sf/jabref/logic/search/MatchesHighlighterTest.java, src/test/java/net/sf/jabref/logic/search/rules/ContainBasedSearchRuleTest.java, src/test/java/net/sf/jabref/logic/util/io/FileUtilTest.java, src/test/java/net/sf/jabref/logic/util/strings/StringUtilTest.java
As a consequence of the introduced preference classes, it is no longer as often required to set `Globals.prefs`.
=> Removed dependencies of Globals.prefs in some tests

src/main/java/net/sf/jabref/logic/layout/format/CompositeFormat.java, src/main/java/net/sf/jabref/model/DuplicateCheck.java, src/test/java/net/sf/jabref/logic/layout/format/CompositeFormatTest.java
=> Some minor code cleanups

CHANGELOG.md, src/main/java/net/sf/jabref/gui/groups/AutoGroupDialog.java
=> Group names can now be rendered using LaTeXs commands

src/main/java/net/sf/jabref/importer/ImportMenuItem.java, src/main/java/net/sf/jabref/importer/ParserResult.java, src/test/java/net/sf/jabref/logic/exporter/ExportFormatTest.java, src/test/java/net/sf/jabref/logic/exporter/HtmlExportFormatTest.java, src/test/java/net/sf/jabref/logic/exporter/MSBibExportFormatTestFiles.java, src/test/java/net/sf/jabref/logic/exporter/MsBibExportFormatTest.java
Fewer initialization of empty `MetaData` to simplify when moving to `model`.
=> Some cleanups to initialize empty MetaData at fewer positions

src/main/java/net/sf/jabref/gui/maintable/MainTable.java
FindBugs reported a potential NPE here, which never occurred since it would only happen if `model.getSearchState() == MainTableDataModel.DisplayOption.DISABLED`. As this is checked for in the first part of the if-clause, I removed the second check., so this shouldn't affect any perfomance since `matches` will only be triggered under the same conditions as before.
Nothing in CHANGELOG since the NPE couldn't actually happen.
=> Removed (false) NPE issue reported by FindBugs

src/main/java/net/sf/jabref/logic/cleanup/RenamePdfCleanup.java, src/main/java/net/sf/jabref/logic/formatter/casechanger/ProtectTermsFormatter.java, src/main/java/net/sf/jabref/logic/util/io/FileNameCleaner.java, src/main/java/net/sf/jabref/logic/util/io/FileUtil.java, src/test/java/net/sf/jabref/logic/cleanup/CleanupWorkerTest.java
Travis uses JDK 1.8.0_101, whereas CircleCI uses 1.8.0_40.
Current state: There are no protected terms loaded any more. I don't know, why.
=> [WIP] Get rid of NPE on Travis

eclipse.gradle
I changed the eclipse formatter to better display enums:
=> Update eclipse formatter for better enum formatting

CHANGELOG.md, src/main/java/net/sf/jabref/logic/integrity/IntegrityCheck.java, src/main/resources/l10n/JabRef_da.properties, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fa.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_in.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_nl.properties, src/main/resources/l10n/JabRef_no.properties, src/main/resources/l10n/JabRef_pt_BR.properties, src/main/resources/l10n/JabRef_ru.properties, src/main/resources/l10n/JabRef_sv.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_vi.properties, src/main/resources/l10n/JabRef_zh.properties, src/test/java/net/sf/jabref/logic/integrity/IntegrityCheckTest.java
To avoid problems using BibTeX and non-ASCII chars.
Quick tests show that it also marks `é` as an error. Does anyone know what chars BibTeX can really handle? Umlauts are a problem but `é`  should work?! So i cannot include all of the extended ascii table http://www.theasciicode.com.ar/extended-ascii-code/letter-e-acute-accent-e-acute-lowercase-ascii-code-130.html
=> Ascii integrity checker

CHANGELOG.md, src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java, src/main/java/net/sf/jabref/model/entry/BibEntry.java, src/test/java/net/sf/jabref/importer/fileformat/BibtexParserTest.java
Fixes #1716.
- ~~Screenshots added (for bigger UI changes)~~
- ~~Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)~~
As this is rather crucial it would be great if someone else checks what I have done ;-)
To explain: 
```
-                // get the text before the entry
-                String prolog = parsedSerialization.substring(0, parsedSerialization.lastIndexOf('@'));
``` 
... did not work properly if an `@` is used within an entry.
However, determining from the complete parsed serialization where the entry begins and what are comments before the entry is not so trivial. Thus, I added another attribute in the bibentry `commentsBeforeEntry` in which the serialized form of the comments stored in …
=> Fixes broken serialization of bibentries containing an @

CHANGELOG.md, src/main/java/net/sf/jabref/logic/autocompleter/AutoCompleterFactory.java, src/main/java/net/sf/jabref/model/database/BibDatabase.java, src/main/java/net/sf/jabref/model/database/KeyChangeListener.java, src/main/java/net/sf/jabref/model/entry/BibEntry.java, src/main/java/net/sf/jabref/model/entry/InternalBibtexFields.java, src/main/java/net/sf/jabref/model/event/FieldChangedEvent.java, src/test/java/net/sf/jabref/model/database/KeyChangeListenerTest.java
Another WIP just to show what is coming (as I may be unavailable for a week or so now).
Change listener that updates the crossref field when the key changes. In the longer run this will be extended to all field with keys, see #1637.
Will continue with tests and CHANGELOG entries eventually.
=> Added change listener for crossref field

CHANGELOG.md, src/main/java/net/sf/jabref/gui/ContentSelectorDialog2.java
Fixed an issue in Manage content selectors introduced in https://github.com/JabRef/jabref/commit/625d17d736805aa6a4f6d879b0f7e7bd4b9e7ae0 where the content selectors were only saved if they didn't exist before. Also improved some other things such as not having to select a field for it to show (issue on startup) and not showing database as changed if it is not.
=> Fixed some issues in Manage content selector dialog

CHANGELOG.md, src/main/java/net/sf/jabref/gui/importer/fetcher/ISBNtoBibTeXFetcher.java, src/main/java/net/sf/jabref/specialfields/SpecialFieldsUtils.java, src/test/java/net/sf/jabref/specialfields/SpecialFieldsUtilsTest.java
Fixed #1519 and an unrelated NPE due to bad documentation (it says that it can be null, but it couldn't and there is a use case where it now is null). Added tests for the fixed NPE.
=> Removed Seiten from pagetotal and fixed a totally unrelated NPE

src/main/java/net/sf/jabref/gui/BasePanel.java
Fixes #1726. Now it only says "Undo" or "Redo", although the (much) more detailed information can be obtained from the tooltip.
Nothing in CHANGELOG since this is an inter-version issue.
=> Changed possibly giant undo/redo texts in status field

CHANGELOG.md, src/main/java/net/sf/jabref/gui/maintable/MainTableColumn.java, src/test/java/net/sf/jabref/model/entry/AuthorListTest.java
Fixed #1499 and #1531. Better to format the author names before converting LaTeX to Unicode... Bah!
=> Fixed name column rendering #1499 and #1531

src/main/java/net/sf/jabref/gui/preftabs/GeneralTab.java
I know I have strange font settings, but I couldn't see some preferences on my portrait screen:
Hence, I changed the layout a bit to scale:
It is not perfect since all the stuff to the right keeps moving, even though all text is shown but still more practical than the current layout.
=> Better layout of general preferences tab

src/main/java/net/sf/jabref/logic/util/strings/HTMLUnicodeConversionMaps.java
Added a number of characters to the converters. Sorted a bit so that it is easier to find the gaps.
=> Added more characters to converters

CHANGELOG.md, src/main/java/net/sf/jabref/collab/ChangeDisplayDialog.java, src/main/java/net/sf/jabref/external/ExternalFileTypeEditor.java, src/main/java/net/sf/jabref/gui/FindUnlinkedFilesDialog.java, src/main/java/net/sf/jabref/gui/StringDialog.java, src/main/java/net/sf/jabref/gui/actions/IntegrityCheckAction.java, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditorTab.java, src/main/java/net/sf/jabref/gui/exporter/ExportCustomizationDialog.java, src/main/java/net/sf/jabref/gui/fieldeditors/FileListEditor.java, src/main/java/net/sf/jabref/gui/groups/GroupsTree.java, src/main/java/net/sf/jabref/gui/importer/ImportCustomizationDialog.java, src/main/java/net/sf/jabref/gui/importer/ImportInspectionDialog.java, src/main/java/net/sf/jabref/gui/importer/ZipFileChooser.java, src/main/java/net/sf/jabref/gui/journals/ManageJournalsPanel.java, src/main/java/net/sf/jabref/gui/keyboard/KeyBindingsDialog.java, src/main/java/net/sf/jabref/gui/openoffice/CitationManager.java, src/main/java/net/sf/jabref/gui/openoffice/StyleSelectDialog.java, src/main/java/net/sf/jabref/gui/preftabs/NameFormatterTab.java, src/main/java/net/sf/jabref/gui/preftabs/PreferencesFilterDialog.java, src/main/java/net/sf/jabref/gui/preftabs/TableColumnsTab.java, src/main/java/net/sf/jabref/gui/preftabs/XmpPrefsTab.java, src/main/java/net/sf/jabref/gui/protectedterms/ProtectedTermsDialog.java, src/main/java/net/sf/jabref/gui/search/SearchResultsDialog.java, src/main/java/net/sf/jabref/gui/util/GUIUtil.java
When increasing the menu font size on Windows (at least WIndows 10), the tables also scale but not the row width. This has been fixed in some dialogs earlier, but this is a general fix.
I have no idea how it works on OSX, but on Linux (my CentOS office machine) it seems like the table font is not the same as the menu font.
This is relevant for high resolution displays (although I cannot find the issue that discussed it...)
Before:
After:
=> Table row height adjusts on Windows as the font scales with the menu

CHANGELOG.md, src/main/java/net/sf/jabref/gui/SidePaneManager.java
Follow up of https://github.com/JabRef/jabref/pull/1525
The minimum quality is achieved: The new system is better then the old one.
Some issues remain, which i try to improve in this PR. Also thanks to @koppor for finding these and even providing a .gif.
Expectation: When I toggle something, the focus after toggling twice should be the same. This is not the case.
1. Click on first entry
2. Show web search (<kbd>alt</kbd>+<kbd>4</kbd>)
3. Click on first entry
4. Hide web search (<kbd>alt</kbd>+<kbd>4</kbd>)
5. Show web search (<kbd>alt</kbd>+<kbd>4</kbd>)
6. Hide web search (<kbd>alt</kbd>+<kbd>4</kbd>)
7. "New database" is focused instead of the first entry.
Sometimes, this happens after step 4, but not reproducable.
(updated)
The position in the entry table changes depended of the …
=> Improve focus of the maintable after a sidepane gets closed

src/main/java/net/sf/jabref/JabRefGUI.java, src/main/java/net/sf/jabref/gui/GUIGlobals.java
No point in having a static initializer when there is an init method that is called at startup or a single line just after the init method call.
=> Moved a few more initialization to GUIGlobals.init()

src/main/java/net/sf/jabref/logic/importer/fileformat/BibTeXMLImporter.java, xjc.gradle
Moved location of generated files from importer to logic.importer. Will merge when the tests pass.
=> Fixed BibTeXMLImporter

src/main/java/net/sf/jabref/shared/DBMSSynchronizer.java
Quickfix for the comments in https://github.com/JabRef/jabref/issues/1748:
> JabRef shows "Aktualisierung verweigert. Den Eintrag, den Sie zur Zeit bearbeiten, ist auf der geminsam genutzen Datenbank nicht mehr vorhanden." for each entry.
and
> After the import, all entries appear twice.
Bug occured due to change of a `BibEntry` before adding it into local database.
=> Quickfix for import into current [shared] database

src/main/java/net/sf/jabref/gui/importer/ImportFileFilter.java, src/main/java/net/sf/jabref/gui/importer/ImportFormats.java, src/main/java/net/sf/jabref/logic/util/FileExtensions.java
When importing a file (`Import into new | current Database`) and a file type was selected sometimes the directories weren't shown anymore (we experienced it under win10 and linux).
Furthermore BibTeXml can also be in .xml format.
=> Some OS didn't show directories when a file type was selected in the import dialog

src/main/java/net/sf/jabref/JabRefGUI.java, src/main/java/net/sf/jabref/JabRefMain.java, src/main/java/net/sf/jabref/external/DroppedFileHandler.java, src/main/java/net/sf/jabref/gui/JabRefFrame.java, src/main/java/net/sf/jabref/gui/actions/CleanupAction.java, src/main/java/net/sf/jabref/gui/cleanup/CleanupPresetPanel.java, src/main/java/net/sf/jabref/gui/help/NewVersionDialog.java, src/main/java/net/sf/jabref/gui/maintable/MainTableFormat.java, src/main/java/net/sf/jabref/gui/menus/RightClickMenu.java, src/main/java/net/sf/jabref/gui/preftabs/ImportSettingsTab.java, src/main/java/net/sf/jabref/gui/preftabs/TableColumnsTab.java, src/main/java/net/sf/jabref/logic/autocompleter/AutoCompletePreferences.java, src/main/java/net/sf/jabref/logic/remote/RemotePreferences.java, src/main/java/net/sf/jabref/logic/util/io/FileUtil.java, src/main/java/net/sf/jabref/pdfimport/ImportDialog.java, src/main/java/net/sf/jabref/pdfimport/PdfImporter.java, src/main/java/net/sf/jabref/preferences/JabRefPreferences.java, src/main/java/net/sf/jabref/preferences/LastFocusedTabPreferences.java, src/main/java/net/sf/jabref/preferences/VersionPreferences.java, src/main/java/net/sf/jabref/specialfields/SpecialFieldsUtils.java, src/test/java/net/sf/jabref/logic/cleanup/RenamePdfCleanupTest.java, src/test/java/net/sf/jabref/logic/util/io/FileUtilTest.java, src/test/java/net/sf/jabref/preferences/LastFocusedTabPreferencesTest.java
All preference constants should be in `JabRefPreferences`.
Relates to https://github.com/koppor/jabref/issues/158
Also, renamed some variables (not the actual preference strings).
=> Moved preference constants to JabRefPreferences and renamed

src/main/java/net/sf/jabref/gui/importer/fetcher/GoogleScholarFetcher.java
Fixes #1762 and #1694
Use `&oe=utf-8` to tell google to deliver content in UTF-8 - more over explicitly use UTF-8 in the JabRef code instead of beeing dependent on the prefs.
- ~~[ ] Change in CHANGELOG.md described~~ - has been introduced in dev version
=> Tell google explicitly to send UTF-8 and always use UTF-8

CHANGELOG.md, src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/JabRefFrame.java
The Preview panel height is not stored when changed (only when JabRef is closed)
- selecting an entry (thus opening the preview panel)
- changing the preview panel height
- closing the preview panel
- selecting an entry (thus opening the preview panel)
- the preview panel has the old height, not the new one we just changed
=> Preview panel height is now saved immediately

CHANGELOG.md, src/main/java/net/sf/jabref/gui/maintable/MainTableColumn.java
Earlier on a name formatter was used if any of the fields in a column contained person names, now it is determined by the used field. (Marginally related to #1795, or at least one step towards a solution, figuring out which field actually was used.)
Before:
After:
(As can be seen, the author/editor column is still rendered as it should.)
=> Improved main table rendering when using e.g. 'title/author'

CHANGELOG.md, src/main/java/net/sf/jabref/logic/integrity/IntegrityCheck.java, src/main/java/net/sf/jabref/model/entry/FieldProperties.java, src/main/java/net/sf/jabref/model/entry/InternalBibtexFields.java
Better to disable the check than remove the field from the entry. ;-)
Fixes #1804
=> Fixed #1804: URL field is not removed by integrity check

CHANGELOG.md, src/main/java/net/sf/jabref/gui/maintable/MainTableSelectionListener.java
Fixes #1760.
Preview is now updated correctly when selecting a single entry after selecting multiple entries.
=> Fix preview update when selecting single entry after selecting multiple entries

src/main/java/net/sf/jabref/MetaData.java, src/main/java/net/sf/jabref/gui/BibtexKeyPatternDialog.java, src/main/java/net/sf/jabref/gui/bibtexkeypattern/BibtexKeyPatternPanel.java, src/main/java/net/sf/jabref/logic/bibtexkeypattern/BibtexKeyPatternPreferences.java, src/main/java/net/sf/jabref/logic/bibtexkeypattern/BibtexKeyPatternUtil.java, src/main/java/net/sf/jabref/model/bibtexkeypattern/DatabaseBibtexKeyPattern.java, src/test/java/net/sf/jabref/logic/exporter/BibtexDatabaseWriterTest.java, src/test/java/net/sf/jabref/logic/importer/fileformat/BibtexParserTest.java
One further step towards a `Globals`-free `MetaData`.
=> Removed one Globals call from MetaData

CHANGELOG.md, src/main/java/net/sf/jabref/logic/bibtex/comparator/FieldComparator.java, src/test/java/net/sf/jabref/logic/bibtex/comparator/FieldComparatorTest.java
When sorting according to "month", "ascending"/"descending" are switched.
=> Fixes #1687 "month" field ascending/descending sorting swapped

src/main/java/net/sf/jabref/gui/BasePanel.java
Follow up to #1811.
I didn't consider that the splitpane is reinitialized each time the preferencesDialog is closed (then the listener would get lost and the divider position wouldn't get saved anymore).
This fixes that.
=> Preview panel height is not saved after the PreferencesDialog has closed

CHANGELOG.md, src/main/java/net/sf/jabref/logic/layout/format/Authors.java, src/test/java/net/sf/jabref/logic/layout/format/AuthorsTest.java
Earlier it was not allowed to set the etal-string in the Authors layout formatter to be empty. However, as clear from #1841 there is at least one use case for it and it is not obvious why it wasn't allowed earlier.
A side note: it is still not allowed to set Sep and LastSep empty. Maybe there are good reasons for that?
=> Allow setting the etal-string empty. Implements #1841

src/main/java/net/sf/jabref/gui/JabRefFrame.java, src/main/java/net/sf/jabref/gui/dbproperties/DatabasePropertiesDialog.java
Issue: https://github.com/JabRef/jabref/issues/1703.
> Database properties dialog:
Do not show "Save sort order" - database sorts arbitrarily :innocent:
Do not show "Database protection" - makes no sense in a shared database setting
Depends on: ~~https://github.com/JabRef/jabref/pull/1818~~ and https://github.com/JabRef/help.jabref.org/pull/57
=> Disable incompatible properties for shared database

CHANGELOG.md, src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/exporter/SaveDatabaseAction.java, src/main/java/net/sf/jabref/gui/maintable/MainTable.java
When you insert a duplicate in your database the editor has the wrong entry linked.
- select an entry
- copy and paste it (`ctrl+c` & `ctrl+v`; leave the old entry selected)
- now the entry editor is open, edit any value and you'll see that the lower duplicate has changed although the upper one is selected
=> When inserting a duplicate the right entry will be selected

CHANGELOG.md, src/main/java/net/sf/jabref/gui/PreviewPanel.java
Found when trying #1841 although non-related.
=> Fixed NPE when loading a style file that has no default style

CHANGELOG.md, src/main/java/net/sf/jabref/BibDatabaseContext.java, src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/JabRefFrame.java, src/main/java/net/sf/jabref/gui/StringDialog.java, src/main/java/net/sf/jabref/gui/exporter/AutoSaveManager.java, src/main/java/net/sf/jabref/gui/exporter/SaveAllAction.java, src/main/java/net/sf/jabref/gui/exporter/SaveDatabaseAction.java, src/main/java/net/sf/jabref/gui/importer/actions/OpenDatabaseAction.java, src/main/java/net/sf/jabref/gui/search/SearchBar.java, src/main/java/net/sf/jabref/logic/layout/LayoutEntry.java
Plus one (or two, I couldn't confirm the second but I think there will be an NPE if starting JabRef with an already existing file as an argument and an unsaved (untitled) database open) bug fixes.
This also includes #1782 as I messed up a bit...
=> Made BibDatabaseContext.getDatabaseFile() return Optional

src/jmh/java/net/sf/jabref/benchmarks/Benchmarks.java, src/main/java/net/sf/jabref/MetaData.java, src/main/java/net/sf/jabref/gui/actions/ManageKeywordsAction.java, src/main/java/net/sf/jabref/gui/groups/AutoGroupDialog.java, src/main/java/net/sf/jabref/gui/groups/GroupDialog.java, src/main/java/net/sf/jabref/gui/importer/actions/AppendDatabaseAction.java, src/main/java/net/sf/jabref/logic/groups/AbstractGroup.java, src/main/java/net/sf/jabref/logic/groups/ExplicitGroup.java, src/main/java/net/sf/jabref/logic/groups/GroupTreeNode.java, src/main/java/net/sf/jabref/logic/groups/GroupsParser.java, src/main/java/net/sf/jabref/logic/groups/KeywordGroup.java, src/main/java/net/sf/jabref/logic/importer/ImportFormatPreferences.java, src/main/java/net/sf/jabref/logic/importer/OpenDatabase.java, src/main/java/net/sf/jabref/logic/importer/fileformat/BibtexParser.java, src/main/java/net/sf/jabref/preferences/JabRefPreferences.java, src/main/java/net/sf/jabref/shared/DBMSSynchronizer.java, src/main/java/net/sf/jabref/specialfields/SpecialFieldDatabaseChangeListener.java, src/main/java/net/sf/jabref/specialfields/SpecialFieldsUtils.java, src/test/java/net/sf/jabref/gui/importer/actions/ConvertLegacyExplicitGroupsTest.java, src/test/java/net/sf/jabref/logic/exporter/BibtexDatabaseWriterTest.java, src/test/java/net/sf/jabref/logic/groups/ExplicitGroupTest.java, src/test/java/net/sf/jabref/logic/groups/GroupTreeNodeTest.java, src/test/java/net/sf/jabref/logic/groups/KeywordGroupTest.java, src/test/java/net/sf/jabref/logic/importer/ImportFormatReaderIntegrationTest.java, src/test/java/net/sf/jabref/logic/importer/ImportFormatReaderTestParameterless.java, src/test/java/net/sf/jabref/logic/importer/OpenDatabaseTest.java, src/test/java/net/sf/jabref/logic/importer/fileformat/BibtexParserTest.java, src/test/java/net/sf/jabref/logic/layout/LayoutEntryTest.java
Still a bit of logic dependencies left to be able to move to model.
All Globals dependencies in `logic`-test except one is now gone, so it is not possible to add an architecture test yet. It is only the Globals dependency of ExternalFileType that remains (good to be able to move external to logic and gui as well).
=> Removed last Globals dependency in MetaData

src/databaseTest/java/net/sf/jabref/shared/DBMSSynchronizerTest.java, src/databaseTest/java/net/sf/jabref/shared/SynchronizationTestSimulator.java, src/jmh/java/net/sf/jabref/benchmarks/Benchmarks.java, src/main/java/net/sf/jabref/BibDatabaseContext.java, src/main/java/net/sf/jabref/gui/shared/OpenSharedDatabaseDialog.java, src/main/java/net/sf/jabref/gui/shared/SharedDatabaseUIManager.java, src/main/java/net/sf/jabref/shared/DBMSProcessor.java, src/main/java/net/sf/jabref/shared/DBMSSynchronizer.java, src/test/java/net/sf/jabref/gui/importer/actions/ConvertLegacyExplicitGroupsTest.java, src/test/java/net/sf/jabref/logic/exporter/BibtexDatabaseWriterTest.java, src/test/java/net/sf/jabref/logic/groups/ExplicitGroupTest.java, src/test/java/net/sf/jabref/logic/groups/GroupTreeNodeTest.java, src/test/java/net/sf/jabref/logic/groups/KeywordGroupTest.java, src/test/java/net/sf/jabref/logic/importer/fileformat/BibtexParserTest.java, src/test/java/net/sf/jabref/logic/layout/LayoutEntryTest.java
And in parts of shared (to possibly allow easier refactoring to gui/logic later).
(Not sure if the database tests will actually pass, so better wait until everything is green..."
=> Removed some Globals in tests

src/main/java/net/sf/jabref/gui/BasePanel.java
Fixes #1881 . I missed an if-statement when inverting an if/else in #1830 
- ~~[ ] Change in CHANGELOG.md described~~ - introduced in development version only (fortunately)
=> Do not mark a new database as changed

CHANGELOG.md, src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java, src/main/java/net/sf/jabref/gui/maintable/MainTable.java
When traversing the entry table with Tab not only changed the selected row but the column did too.
When the most right column was selected and the user would press Tab one entry would be skipped,
Extracted some logic too.
=> [WIP] Fix entry table traversal with Tab

CHANGELOG.md, src/main/java/net/sf/jabref/logic/exporter/MSBibExportFormat.java, src/main/java/net/sf/jabref/logic/importer/fileformat/MsBibImporter.java, src/main/java/net/sf/jabref/logic/msbib/BibTeXConverter.java, src/main/java/net/sf/jabref/logic/msbib/MSBibDatabase.java, src/main/java/net/sf/jabref/logic/msbib/MSBibEntry.java, src/test/resources/net/sf/jabref/logic/exporter/MsBibExportFormatTest2.xml, src/test/resources/net/sf/jabref/logic/exporter/MsBibLocationTest.bib, src/test/resources/net/sf/jabref/logic/exporter/MsBibLocationTest.xml, src/test/resources/net/sf/jabref/logic/exporter/MsBibMultiAddressTest.bib, src/test/resources/net/sf/jabref/logic/exporter/MsBibMultiAddressTest.xml, src/test/resources/net/sf/jabref/logic/importer/fileformat/MsBibLocationTest.bib, src/test/resources/net/sf/jabref/logic/importer/fileformat/MsBibLocationTest.xml, src/test/resources/net/sf/jabref/logic/importer/fileformat/MsBibMultiLocationAddressTest.bib, src/test/resources/net/sf/jabref/logic/importer/fileformat/MsBibMultiLocationAddressTest.xml
Fix location field not exported correctly to office 2007 xml
=> Fix location field not exported correctly to office 2007 xml

CHANGELOG.md, src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/maintable/MainTable.java
I imroved the `findEntry`-method some more. Now it always finds the correct Entry (by searching it with the id and not with the canonical representation.
- have multiple duplicates in a database
- search them and open the results in the extra window
- select one of the duplicates in the extra window but the first
- in the main window always the first of the duplicates is selected
=> improve find entry

src/main/java/net/sf/jabref/gui/journals/ManageJournalAbbreviationsView.java, src/main/java/net/sf/jabref/gui/journals/ManageJournalAbbreviationsViewModel.java, src/main/java/net/sf/jabref/gui/keyboard/KeyBindingsDialogViewModel.java, src/main/java/net/sf/jabref/gui/util/ValueTableCellFactory.java, src/main/java/net/sf/jabref/gui/util/ViewModelTreeTableCellFactory.java
It is relatively cumbersome to create custom (tree) table cells in JavaFX. The aim of this PR is to introduce helper classes which provide a simpler way to customize tables.
@JabRef/stupro @JabRef/stupro-qa please also review this PR, thanks.
=> Introduce cell factory helper (JavaFX)

CHANGELOG.md, src/main/java/net/sf/jabref/gui/JabRefFrame.java
I am working on this issue https://github.com/JabRef/jabref/issues/463
I have disabled and greyed out all menu items and toolbar buttons that should not be active if no database is open. (take a look at screenshots)
=> Disable some actions while no database is open

CHANGELOG.md, src/main/java/net/sf/jabref/logic/msbib/MSBibConverter.java, src/main/java/net/sf/jabref/logic/msbib/MSBibEntry.java, src/main/java/net/sf/jabref/logic/msbib/MSBibMapping.java, src/test/resources/net/sf/jabref/logic/exporter/MsBibExportFormatTest2.xml, src/test/resources/net/sf/jabref/logic/exporter/MsBibExportFormatTest3.xml, src/test/resources/net/sf/jabref/logic/exporter/MsBibExportFormatTest6.xml, src/test/resources/net/sf/jabref/logic/exporter/MsBibKeyTest.bib, src/test/resources/net/sf/jabref/logic/exporter/MsBibKeyTest.xml
Add : Export key field (not to be confused with bibtexkey field), 
Add test for custom entry type and key field 
Refs #1851 
Documentation has to be updated.
=> Export number field as number if not patent or issue in office 07 xml

src/main/java/net/sf/jabref/gui/openoffice/OOBibBase.java, src/main/java/net/sf/jabref/gui/openoffice/OpenOfficePanel.java
Removed deprecated calls, renamed a few variables, and restructured the code a bit.
=> Some OO/LO cleanups

build.gradle
When I read it correct in the doc, this should help fixing the Unicode problems in #1178 
I tested locally and it seemed working for me. 
>It's a good practice to specify the charset when reading and writing the file, using the filteringCharset property. If not specified, the JVM default charset is used, which might not match with the actual charset of the files to filter, and might be different from one machine to another. 
https://docs.gradle.org/current/userguide/working_with_files.html#sec:filtering_files
=> Add filteringCharset = 'UTF-8' to gradle

CHANGELOG.md, src/main/java/net/sf/jabref/gui/externalfiles/DownloadExternalFile.java, src/main/java/net/sf/jabref/gui/preftabs/FileTab.java
Many users set file directories by copy pasting the path and not by opening the file chooser. This means invalid paths could be set in preferences -> File -> main file directory
See https://github.com/koppor/jabref/issues/109 for more information.
Now the preferences tab won't save an invalid path anymore and notifies the user about it.
Also there is now an error message when trying to download a file to a directory which does not exist or can not be written to.
=> Added error dialog when setting invalid main file directory

src/main/java/net/sf/jabref/gui/keyboard/KeyBinding.java
Recently the keybindings at the master branch have been changed with #1525 . This pr will change the keybindings in the javafx branch accordingly.
=> [WIP] Adjusted key bindings according to master branch

CHANGELOG.md, src/main/java/net/sf/jabref/gui/maintable/MainTableSelectionListener.java
@obraliar and I fixed a critical Bug in the shared Database (broken in v3.6):
- open 2 JabRef instances with shared database
- edit a field of an entry in the first instance and push the change (eg. selecting another field)
- select the same entry/field which was edited int the second instance
- pull changes in the second instance
- second JabRef loops indefinitely
=> Hotfix: Fix loop when pulling changes when current selected field has changed

src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/search/GlobalSearchBar.java
Fix for #1549
- Select a bibentry
- Edit a field
- save the change (eg. click outside the field)
- the searchbar would be focused
=> Fix when editing a bibEntry field the searchbar would be focused

CHANGELOG.md, src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/keyboard/KeyBinding.java, src/main/java/net/sf/jabref/gui/maintable/MainTable.java, src/main/java/net/sf/jabref/gui/search/SearchResultFrame.java, src/main/resources/l10n/JabRef_da.properties, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fa.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_in.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_nl.properties, src/main/resources/l10n/JabRef_no.properties, src/main/resources/l10n/JabRef_pt_BR.properties, src/main/resources/l10n/JabRef_ru.properties, src/main/resources/l10n/JabRef_sv.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_vi.properties, src/main/resources/l10n/JabRef_zh.properties
- <kbd>Pos1</kbd> / <kbd>HOME</kbd> now select the first/last entry in the main table and the search result frame.
- <kbd>UP</kbd> / <kbd>Down</kbd> / <kbd>Tab</kbd> / <kbd>shift+Tab</kbd> in the search result frame have now the same functionality as in the main  table.
=> Add key shortcuts to search result frame and main table

.mailmap, AUTHORS
.mailmap edited, AUTHORS generated by script.
=> Double authors removed

CHANGELOG.md, src/main/java/net/sf/jabref/logic/integrity/HTMLCharacterChecker.java, src/main/java/net/sf/jabref/model/entry/FieldName.java, src/test/java/net/sf/jabref/logic/integrity/IntegrityCheckTest.java
=> Fixes #1958: Verbatim URL field is no longer checked for HTML encoded chars

src/test/java/net/sf/jabref/logic/search/DatabaseSearcherTest.java
There was a failing test in #1976. This should fix it.
=> fix failing test from #1976

src/main/java/net/sf/jabref/gui/EntryTypeDialog.java
Fixing a problem when closing the EntryTypeDialog. The problem is that it is not checked if the fetcherWorker already started. So if we closed the Dialog with `ESC` or `X` a CancelException was thrown. To fix this we check the status of the SwingWorker when we try to close the window.
=> Fix Entrytypedialog

src/main/java/net/sf/jabref/logic/importer/IdBasedParserFetcher.java, src/main/java/net/sf/jabref/logic/importer/fetcher/DiVA.java, src/main/java/net/sf/jabref/logic/importer/fetcher/IsbnFetcher.java, src/main/java/net/sf/jabref/logic/util/ISBN.java, src/main/resources/l10n/JabRef_da.properties, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fa.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_in.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_nl.properties, src/main/resources/l10n/JabRef_no.properties, src/main/resources/l10n/JabRef_pt_BR.properties, src/main/resources/l10n/JabRef_ru.properties, src/main/resources/l10n/JabRef_sv.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_vi.properties, src/main/resources/l10n/JabRef_zh.properties, src/test/java/net/sf/jabref/logic/importer/fetcher/IsbnFetcherTest.java
Follow-up from #1929. Since the changes in this PR are completely parallel to #1929, I will merge it as soon as the build passes.
=> Introduce convienent interface for ID-based fetcher

CHANGELOG.md, src/main/java/net/sf/jabref/gui/help/HelpAction.java
If help lang not avaiable use English
Fix for #1937
=> Check avaiable help lanugages when opening specific help page

src/main/java/net/sf/jabref/gui/EntryTypeDialog.java
While fixing another bug (#1987) in the EntryTypeDialog I created a new one. To fix this bug I added the IdFetcher section to the BibLaTeX-mode, as it was intended. Before, it was only in the BibTeX mode. The problem was that the fetcherWorker was null in the BibLaTeX-mode, because `createIdFetcherPanel()` was only called in the `else` part. So the fetcherWorker was never initialized.
The ParameterizedDialogNewEntryTest works fine again.
Fixes #2001
=> Fix EntryTypeDialog using BibLaTeX-mode

CHANGELOG.md, src/main/antlr4/net/sf/jabref/search/Search.g4, src/main/java/net/sf/jabref/logic/search/SearchQuery.java, src/main/java/net/sf/jabref/logic/search/SearchQueryHighlightObservable.java, src/main/java/net/sf/jabref/logic/search/rules/describer/GrammarBasedSearchRuleDescriber.java, src/main/java/net/sf/jabref/model/search/rules/ContainBasedSearchRule.java, src/main/java/net/sf/jabref/model/search/rules/GrammarBasedSearchRule.java, src/test/java/net/sf/jabref/logic/search/SearchQueryHighlightObservableTest.java, src/test/java/net/sf/jabref/logic/search/SearchQueryTest.java
As observed by @oscargus in https://github.com/JabRef/jabref/pull/1876#issuecomment-247533268 certain mixed search queries does not work (for example, `fruity and keywords=apple`).
This PR fixes this issue.
Side-effect: simple queries as `fruity` are also recognized as "grammar based" (which is why I had to change a few tests). However, there should be no major performance decline since the query parsing is quite fast and for the actual search in the end the same code gets called.
=> Fix search mixed from contains and grammar

CHANGELOG.md, src/main/java/net/sf/jabref/logic/integrity/BibtexkeyChecker.java, src/main/java/net/sf/jabref/logic/integrity/IntegrityCheck.java, src/main/resources/l10n/JabRef_da.properties, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fa.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_in.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_nl.properties, src/main/resources/l10n/JabRef_no.properties, src/main/resources/l10n/JabRef_pt_BR.properties, src/main/resources/l10n/JabRef_ru.properties, src/main/resources/l10n/JabRef_sv.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_vi.properties, src/main/resources/l10n/JabRef_zh.properties, src/test/java/net/sf/jabref/logic/integrity/IntegrityCheckTest.java
Check for empty bibtexkey. #1779.
=> Implemented BibtexkeyChecker

src/main/java/net/sf/jabref/gui/maintable/MainTable.java
Hotfix `MainTable` using `Optional`.
Steps to reproduce the bug:
* Open two JabRef instances A and B
* Connect A and B to a shared database supporting LiveUpdate
* Create a new Entry in A
* Open the entry and change the value of a field like author
* Delete the new Entry from B and confirm the upcoming dialog in A
`MainTable` and `EntryMarker` contains a lot of ugly code which produces such errors and can be refactored. @bartsch-dev shows interest to do this probably in the next week. :+1:
=> [WIP] Hotfix for IndexOutOfBoundsException in MainTable

src/test/java/net/sf/jabref/model/groups/TreeNodeTest.java
Removes build warning
> Note: /home/travis/build/JabRef/jabref/src/test/java/net/sf/jabref/model/groups/TreeNodeTest.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
=> Remove unsafe operation from TreeNodeTest

src/main/java/net/sf/jabref/gui/search/GlobalSearchBar.java
This should fix following Exception which occurred since short.
```
12:51:21.727 [AWT-EventQueue-0] WARN  net.sf.jabref.model.search.rules.GrammarBasedSearchRule - Search query invalid
org.antlr.v4.runtime.misc.ParseCancellationException: line 1:0 no viable alternative at input '<EOF>'
at net.sf.jabref.model.search.rules.GrammarBasedSearchRule$ThrowingErrorListener.syntaxError(GrammarBasedSearchRule.java:50) ~[main/:?]
at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:65) ~[antlr4-runtime-4.5.3.jar:4.5.3]
at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:564) ~[antlr4-runtime-4.5.3.jar:4.5.3]
at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:308) ~[antlr4-runtime-4.5.3.jar:4.5.3]
at …
```
=> Fix search Syntax Error

scripts/syncLang.py
Fixes this Problem: https://github.com/JabRef/jabref/pull/2037#issuecomment-249146208
I forgot to mark some strings as Unicode strings (the standard python strings are ASCII) which causes some problems if the translation has non ASCII characters.
=> Localization script: replace ASCII with Unicode strings

src/jmh/java/net/sf/jabref/benchmarks/Benchmarks.java, src/main/java/net/sf/jabref/gui/search/GlobalSearchWorker.java, src/main/java/net/sf/jabref/gui/search/SearchWorker.java
With this the search should be much faster on platforms where multiple cores are available. (#1993)
=> Use parallel stream while searching

src/main/resources/l10n/JabRef_tr.properties
Translated the last 4 entries to Turkish
=> Updated jabref_tr.properties

CONTRIBUTING.md, localization.gradle, scripts/README.md, src/test/java/net/sf/jabref/logic/l10n/LocalizationConsistencyTest.java
fixes: #2029
Replaces hints to the old gradle localization task names with the new ones.
=> Fix localization task hints

CHANGELOG.md, src/main/java/net/sf/jabref/logic/integrity/IntegrityCheck.java, src/main/java/net/sf/jabref/logic/integrity/NoBibtexFieldChecker.java, src/main/resources/l10n/JabRef_da.properties, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fa.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_in.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_nl.properties, src/main/resources/l10n/JabRef_no.properties, src/main/resources/l10n/JabRef_pt_BR.properties, src/main/resources/l10n/JabRef_ru.properties, src/main/resources/l10n/JabRef_sv.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_vi.properties, src/main/resources/l10n/JabRef_zh.properties, src/test/java/net/sf/jabref/logic/integrity/IntegrityCheckTest.java
Background: Converting to Biblatex format changes journal to journaltitle. Because journaltitle is a Biblatex field only, Integrity check now reports a problem for a journaltitle field in a BibTeX mode database.
=> Implemented Integrity NoBibtexFieldChecker

CHANGELOG.md, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java
=> Undo #2002

src/main/java/net/sf/jabref/JabRefGUI.java, src/main/java/net/sf/jabref/JabRefMain.java
Follow up of #1704 to fix the key pattern part of #2021
Preference migrations are executed too late after other operations already worked on the prefs node --> execute them directly in the main class.
=> Fix execution of preference migrations

CHANGELOG.md, src/main/java/net/sf/jabref/gui/maintable/MainTable.java
Fixes: https://github.com/koppor/jabref/issues/160.
Tool tips in the main table now work as expected.
If the content of the cell is too big to be rendered in the cell itself it will be shown as a tool tip. What is more important, the original tool tip or the content?
=> Tooltips now working in the main table

CHANGELOG.md, src/main/java/net/sf/jabref/gui/maintable/MainTable.java
fixes: https://github.com/koppor/jabref/issues/31
Now the number in the `#`-column is always left aligned.
=> Fix number column alignment

.github/PULL_REQUEST_TEMPLATE.md, scripts/logger.py, scripts/syncLang.py, src/main/resources/l10n/Menu_vi.properties
I really don't like the missing type safety in python ...
Now the problematic translations get printed to the terminal correctly.
I simplified the output while running the update task; printing only the changes.
I also added a new checkbox to the PR-template to make it easier for new people.
=> Localization script: Simplify update output and fix printing of special characters

src/main/java/net/sf/jabref/gui/PreviewPanel.java
Fixed a NPE which rarely appears on Window, more often on linux (b/c of the `invokeLater` in line 299)
=> Fix NPE in the PreviewPanel

src/main/java/net/sf/jabref/gui/importer/fetcher/GoogleScholarFetcher.java, src/main/java/net/sf/jabref/logic/net/URLDownload.java
Google Scholar fetching was broken again (see #1886)
With this fix at least getting the first 10 search hits is possible again. 
Configuration is no longer possible in the current form and google generally limits the responses (per page) to 20 hits (however, even using this will cause a captcha challenge for JabRef).
As only 10 hits are allowed a rewrite to the new FetcherInfrastructure should now be possible (thus, omitting the 2-step approach).
=> Quick fix google scholar entry fetching

CHANGELOG.md, jabref.install4j, src/main/java/net/sf/jabref/model/entry/BibEntry.java, src/main/java/net/sf/jabref/model/search/rules/ContainBasedSearchRule.java, src/main/java/net/sf/jabref/model/search/rules/GrammarBasedSearchRule.java, src/main/java/net/sf/jabref/model/search/rules/RegexBasedSearchRule.java, src/main/java/net/sf/jabref/model/strings/LatexToUnicode.java
Based on the discussion in #1993 and the work of @bartsch-dev in #2091, this PR aims to improve the speed of search by storing LaTeX-free versions of field values in a cache. It aims at a balance between better performance and an acceptable memory footprint. Basically, all ideas from #1993 are implemented: a cached store of LaTeX-free fields which is computed on demand, String internalization, and regex performance improvements in `LatexToUnicode`.
Here are measurements with the new branch:
```
Benchmark                             Mode  Cnt         Score        Error  Unit
Benchmarks.latexToUnicodeConversion  thrpt   20    119823.078   2063.425  ops/s
Benchmarks.parallelSearch            thrpt   20       735.890    113.685  ops/s
Benchmarks.search                    thrpt   20 …
```
=> Store LaTeX-free fields in BibEntry

CHANGELOG.md, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java
Fixes #2109. Ctrl-s doesn't trigger parsing error message.
Problem: conflict of local shortcut (of the entry editor) with the global shortcut.
Solution: local shortcut removed. (The action assigned to local and global shortcut is essentially the same (save database))
=> Ctrl-s parsing error message

src/main/java/net/sf/jabref/logic/importer/fileformat/MedlineImporter.java, src/test/resources/net/sf/jabref/logic/importer/fileformat/MedlineImporterTestArticleNoISSN.bib, src/test/resources/net/sf/jabref/logic/importer/fileformat/MedlineImporterTestArticleNoISSN.xml
Fix for #2110
When issn was null, calling a method on it resulted in NPE.
=> Fix NPE in Medline fetcher on missing ISSN

CHANGELOG.md, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java, src/main/java/net/sf/jabref/gui/plaintextimport/TextInputDialog.java, src/main/resources/l10n/JabRef_da.properties, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fa.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_in.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_nl.properties, src/main/resources/l10n/JabRef_no.properties, src/main/resources/l10n/JabRef_pt_BR.properties, src/main/resources/l10n/JabRef_ru.properties, src/main/resources/l10n/JabRef_sv.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_vi.properties, src/main/resources/l10n/JabRef_zh.properties
This is a minor change to the source panel, which used to always display "BibTeX source" as title and a similar tooltip. Now, that is dependent on the mode of the database and reads "BibLaTeX source" in biblatex mode.
=> Change title/tooltip of source panel in biblatex mode

CHANGELOG.md, src/main/java/net/sf/jabref/gui/date/DatePickerButton.java
Fixes https://github.com/JabRef/jabref/issues/2092
Implemented behavior for the "none"-button of the data picker, which now clears the content of the date field.
=> Implement Datepicker "none"-button

src/main/java/net/sf/jabref/gui/search/SearchResultFrame.java, src/main/java/net/sf/jabref/logic/importer/fetcher/CrossRef.java, src/main/java/net/sf/jabref/logic/msbib/MSBibConverter.java, src/main/java/net/sf/jabref/model/search/rules/ContainBasedSearchRule.java, src/main/java/net/sf/jabref/model/search/rules/RegexBasedSearchRule.java
I removed some uses of the `UnicodeToLatexFormatter` and used the latexFreeField directly.
=> Remove some UnicodeToLatex uses

src/main/java/net/sf/jabref/gui/maintable/MainTableSelectionListener.java
Fixes: #2105.
1. have at least 2 entries
- open the entry editor and close it 
- the preview will be rendered correctly
- select the other entry 
- the preview will be rendered correctly
- select the first entry (the one you opened the editor with)
- the preview will not be updated
The problem is that the editor variable doesn't get cleared when the editor closes, thus the bottom component in the main table doesn't get updated if that entry is the last one which had the editor open.
=> Fix entry preview not updated properly

src/main/java/net/sf/jabref/gui/maintable/ListSynchronizer.java
- have at least 2 entries in a database
- edit the lower one so that it matches the first one in every detail (creating a duplicate)
- now the upper one will be internally replaced with the lower one (and will be lost visually), both entries in the table are now one and the same
This is again caused by the `BibEntry#equals` method which doesn't recognize duplicates, maybe we have to do something about that?
=> Fix main table bug when creating a duplicate

src/main/java/net/sf/jabref/gui/maintable/MainTableSelectionListener.java
Fixes https://github.com/JabRef/jabref/issues/2136
1. open any entry
- edit any field
- try switching to the next field with <kbd>TAB</kbd>
- focus is taken away from the next field
=> Fix switching edited textfield in the entry editor with TAB

src/main/java/net/sf/jabref/logic/util/Version.java
We want to get back control of the download site we offer. Thus, we created https://downloads.jabref.org (https://github.com/JabRef/downloads.jabref.org) with a redirection to fosshub.
Refs #1670
=> Change download URL to downloads.jabref.org

src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/search/SearchWorker.java
Fixes: https://github.com/koppor/jabref/issues/172.
**Edit:** Fixes #2142.
When the search is active and you edit an entry until the entry doesn't match the search an longer the first match would be selected.
Now, if you edit an entry the selected entry won't change.
=> Don't change the selected entry after search if you edit an entry

src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/PreviewPanel.java, src/main/java/net/sf/jabref/gui/autocompleter/AutoCompleteSupport.java, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java, src/main/java/net/sf/jabref/gui/search/GlobalSearchBar.java
At request of @koppor.
When hitting `ESC` in the main table and neither preview nor editor is open the search term will be cleared.
Since the action in the main table overshadows the actions in the preview-/editorpanel I have to call the `close()` method manually (same Keybinding).
=> Clear searchterm with ESC from main table if neither preview nor editor is open

CHANGELOG.md, src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/bibtexkeypattern/SearchFixDuplicateLabels.java, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java, src/main/java/net/sf/jabref/gui/openoffice/OpenOfficePanel.java, src/main/java/net/sf/jabref/gui/undo/UndoableKeyChange.java, src/main/java/net/sf/jabref/logic/bibtexkeypattern/BibtexKeyPatternUtil.java, src/main/java/net/sf/jabref/model/database/BibDatabase.java, src/main/java/net/sf/jabref/model/database/DuplicationChecker.java, src/test/java/net/sf/jabref/model/database/BibDatabaseTest.java, src/test/java/net/sf/jabref/model/database/DuplicationCheckerTest.java
Fixes https://github.com/JabRef/jabref/issues/2089.
The Duplication checker was faulty and didn't catch all the cite keys. There needed to be used a special method in the BasePanel which wasn't used at all.
I registered the DuplicationChecker with the Eventbus which now gets notified when an Entry changes, gets added, or removed.
This fixes the automatic Key generation which before had wrong information on what cite keys exist.
=> Fix DuplicationChecker and key generator

src/test/java/net/sf/jabref/logic/importer/fetcher/DoiResolutionTest.java
I implemented a missing test case `notReturnAnythingWhenMultipleLinksAreFound`, that has been ignored.
=> [WIP] Doi resolution ignore

CHANGELOG.md, src/main/java/net/sf/jabref/gui/menus/RightClickMenu.java
Fixes: https://github.com/koppor/jabref/issues/171.
Added shortcuts to the context menu (just displayed them, didn't create new ones) and refactored the context menu a little bit.
=> Add shortcuts to context menu

CHANGELOG.md, src/main/java/net/sf/jabref/gui/FileDialog.java
make all files selectable in filechooser
fixed #2021
=> Make all files selectable in file chooser dialogs

src/test/java/net/sf/jabref/logic/bibtex/BibEntryWriterTest.java, src/test/java/net/sf/jabref/logic/importer/fileformat/BibtexParserTest.java
Regarding: [#29] (https://github.com/koppor/jabref/issues/29) 
I've added a test case for reading and writing a file with other and unknwon type.
=> Add test case for other and unknown type

CHANGELOG.md, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java
Fixes #2177. NullPointerException caused by clearing bibtexkey field in entry editor.
=> Clear bibtexkey exception

src/main/java/net/sf/jabref/logic/autosaveandbackup/BackupManager.java, src/main/java/net/sf/jabref/logic/exporter/FileSaveSession.java, src/main/java/net/sf/jabref/logic/util/io/FileUtil.java, src/test/java/net/sf/jabref/logic/autosaveandbackup/BackupManagerTest.java, src/test/java/net/sf/jabref/logic/util/io/FileUtilTest.java
While updating `.gitignore` files to contain `.bib.swp`, I [saw that there is a WinEdt setting for `*.sav`](https://www.gitignore.io/api/latex). To avoid complaints by users, I think, we should also use `.sav` for the autosave extension.
I know, that this is the typical backup functionality. However, we use `.bak` during saving an thus, I opted for `.sav`.
WinEdt settings:
Source: http://tex.stackexchange.com/a/240965/9075
=> Replace ".bib.swp" by ".bib.sav" for autosave file

src/main/java/net/sf/jabref/model/entry/FieldName.java, src/main/java/net/sf/jabref/model/entry/InternalBibtexFields.java
I made a mistake (typos) in #2186. This PR corrects the typos (editoratype). Sorry for that.
=> Typos Field name constants

CHANGELOG.md, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java
Something went wrong with the old PR dealing with this issue. So here a new PR. Fixes an issue with closing the entry editor. (I've discarded some additional save action, because this might not be the desired behaviour.)
Here again the bug:
Fixed close action of entry editor not working after parsing (and invalid field) error corrected.
1. generate parsing error in source tab
2. Save database
3. error message > Edit
4. correct parsing error
5. Close entry editor (x) blocked
=> Fixed close entry editor block

src/main/java/net/sf/jabref/model/groups/KeywordGroup.java, src/test/java/net/sf/jabref/model/groups/ExplicitGroupTest.java, src/test/java/net/sf/jabref/model/groups/KeywordGroupTest.java
... seems to be as simple as that.
Change has been introduced as the delimitor is no longer saved as a String ", " but as a `Character` which chops away the space after the comma.
- ~~[ ] Change in CHANGELOG.md described~~ introduced in dev Builds
=> Fix for #2184: Add space after separator

src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/maintable/MainTableSelectionListener.java
Fixes: #2208
When you delete an entry the focus will no longer jump to the searchbar, instead it will select the next entry (also counts for pasting).
=> Prevent the search to get focus when deleting/pasting an entry

src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditorTab.java, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditorTabFocusListener.java
I refactored many comments (some of them even referred to variables which do not exist anymore).
I removed some unused Methods, replaced some code with already existing methods and refactored a switch-case.
=> Refactor EntryEditor & EntryEditorTab

src/main/java/net/sf/jabref/gui/errorconsole/ErrorConsoleController.java, src/main/java/net/sf/jabref/gui/errorconsole/ErrorConsoleView.java, src/main/java/net/sf/jabref/gui/errorconsole/ErrorConsoleViewModel.java, src/main/java/net/sf/jabref/gui/util/ViewModelListCellFactory.java
This should fix the wrong styling behaviour of the different log messages when scrolling. It seems like the styling error came because we never resetted the style classes of the cells when adding new ones.
I also created a generic ListFactory class (similar to #1917) so this issue won't occur in the future. Refs #2210
=> Fix strange styling behaviour of the error console

src/main/java/net/sf/jabref/logic/importer/fetcher/AstrophysicsDataSystem.java, src/test/java/net/sf/jabref/logic/importer/fetcher/AstrophysicsDataSystemTest.java
(see #2218)
Fetcher is now working again...
- ~~[ ] Change in CHANGELOG.md described~~ affected search based fetcher still unreleased
=> Fix for #2218: Reenable ADS fetcher

CHANGELOG.md, src/main/java/net/sf/jabref/logic/importer/fetcher/MedlineFetcher.java
Fix for #2228 
After November 9, 2016, NCBI HTTP servers will redirect or reject all HTTP requests.
=> Fix medline fetcher by using https

src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java, src/main/java/net/sf/jabref/gui/maintable/MainTableSelectionListener.java
Possibly fixes: #2220.
Mainly I removed `SwingUtilities.invokeLater(() ->`. I also added some lines to remove the event listener from the old entry editors.
=> Fix editor freeze

CHANGELOG.md, src/main/java/net/sf/jabref/logic/bibtex/comparator/FieldComparator.java, src/main/java/net/sf/jabref/model/entry/BibEntry.java, src/test/java/net/sf/jabref/model/entry/BibEntryTests.java
Fixes #2200 by using the latex free value of the field for sorting the main table.
However, just using `getLatexFreeField()` was not possible as the table is using `getFieldOrAlias`. Thus I introduced a new method `getFieldOrAliasLatexFree()` which is based on the previous implementation of `getFieldOrAlias()` using lambdas. This approach is used instead of formatting the `getFieldOrAlias()` result for performance reasons as the latex-free field values are cached in the `BibEntry`.
*Sidenote: If this approach is approved by you, the same should be applied to `BibDatabase.getResolvedFields()` which is used in `MainTableColumn.getColumnValue()` to show a latex-free version of the contents in the main table)*
- ~~[ ] Check documentation …
=> Fix maintable sorting

src/main/java/net/sf/jabref/model/entry/InternalBibtexFields.java
Add issn field to the drop-down text field, that adds a field formatter in cleanup entries. This should fix #2241.
=> Add issn field to drop-down

src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java
Issue #2233: In BibLaTeX the `date` field is recommended. For backward compatibility the BibTeX fields `month` and `year` are also accepted. I've added both fields to the deprecated fields tab, although the year field is present in the required fields tab too.
=> BibLaTeX mode: Add month and year field to deprecated tab

src/main/java/net/sf/jabref/model/search/rules/GrammarBasedSearchRule.java
"Fixes" a side aspects mentioned in #2249.
Currently a search will throw errors if one types "author=" as the search term is still incomplete - those exceptions should not be visible to the normal user.
=> Change log level to debug

CHANGELOG.md, src/main/java/net/sf/jabref/logic/importer/IdBasedParserFetcher.java, src/test/java/net/sf/jabref/logic/importer/fetcher/AstrophysicsDataSystemTest.java, src/test/java/net/sf/jabref/logic/importer/fetcher/IsbnFetcherTest.java
When fetching a valid ISBN from ebook.de, but the site has no data of the ISBN, the error message just showed "FileNotFoundException". This PR fixes that.
The issue itself is a kind of regression as it has been fixed for verison 3.3 - see #684.
=> When an ISBN is not available on ebook.de, the error message is more clear.

src/main/java/net/sf/jabref/gui/keyboard/KeyBinding.java
In the JavaFX branch, JabRef outputs
```
09:52:15.355 [AWT-EventQueue-0] WARN  net.sf.jabref.logic.l10n.Localization - Warning: could not get message translation for "Check integrity" for locale en
09:52:15.356 [AWT-EventQueue-0] WARN  net.sf.jabref.logic.l10n.Localization - Warning: no message translation for "Check integrity" for locale en
```
This is fixed with this PR.
When digging deeper, it seems also other calls to `Localization.lang` should be replaced by `Localization.menuTitle`.
For other cases, like "Copy_BibTeX_key_and_title" (or "Open Database"), some calls might get replaced. The RightClickMenu calls `lang` with that string, whereas JabReFrame calls `menuTitle`. I would opt for changing the call of RightClickMenu. Reason: When adding a new language, first the menu strings …
=> Fix translation warning

CHANGELOG.md
Keyboard key format unified according to following rules:
<kbd>Ctrl</kbd> + <kbd>Enter</kbd>
`<kbd>Ctrl</kbd> + <kbd>Enter</kbd>`
- `<kbd>` tag for each key
- First letter of key capitalized
- Combined keys separated by `+`
- Spaces before and after separator `+`
=> CHANGELOG.md keyboard key format unified

CHANGELOG.md, src/main/java/net/sf/jabref/logic/exporter/FileSaveSession.java
Fixes #2279.
JabRef does not directly writes to the bib-file upon save but creates a temporary file which is then copied over the original one. In this process the original file permissions get lost. Should be fixed with this PR (I have not tried it...).
I pushed the code to the branch https://github.com/JabRef/jabref/tree/filePermissions but for some reason the setup files do not show up on [builds.jabref.org](http://builds.jabref.org/)
=> Fix #2279: File permissions are kept upon save

CHANGELOG.md, src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/logic/exporter/FileSaveSession.java, src/main/java/net/sf/jabref/logic/util/io/FileUtil.java
Fix the error message reported in https://github.com/JabRef/jabref/issues/2285, which is due to trying to use posix on Windows.
Update: also fixes the issue reported at https://github.com/JabRef/jabref/issues/2285. The original exception from http://discourse.jabref.org/t/jabref-cannot-complete-save-of-database-error-in-log/294 resulted from a `Optional.get` on an empty optional. Please merge as separate commits.
=> Fix UnsupportedOperationException on Windows due to Posix usage

CHANGELOG.md, src/main/java/net/sf/jabref/shared/DBMSConnection.java
I got the error message "No suitable driver found for jdbc:pgsql://fizzy-cherry.db.elephantsql.com:5432/zdndklfq" when using the session restore of shared databases of JabRef. Google pointed me to http://stackoverflow.com/a/22384826/873282, which states that all drivers should be loaded before they are used.
This PR ensures that all available DBMS drivers are loaded before any connection attempt is made.
This does not fix #2294, which means that one has to enable autosave to be able to automatically reconnect.
=> Fix "No suitable driver found"

CHANGELOG.md, src/main/java/net/sf/jabref/gui/exporter/SaveDatabaseAction.java, src/main/java/net/sf/jabref/gui/shared/ConnectToSharedDatabaseDialog.java
A `NullPointerException` occurred when leaving the file path field empty and connecting to a shared database.
Exception:
```
[AWT-EventQueue-0] ERROR net.sf.jabref.gui.shared.ConnectToSharedDatabaseDialog - Error while saving the database
java.lang.NullPointerException: null
at java.util.prefs.AbstractPreferences.put(AbstractPreferences.java:241) ~[?:1.8.0_111]
at net.sf.jabref.preferences.JabRefPreferences.put(JabRefPreferences.java:922) ~[main/:?]
at net.sf.jabref.gui.exporter.SaveDatabaseAction.saveAs(SaveDatabaseAction.java:337) ~[main/:?]
...
```
=> Fix NullPointerException in ConnectToSharedDatabaseDialog

CHANGELOG.md, src/main/java/net/sf/jabref/logic/importer/util/MetaDataParser.java, src/main/java/net/sf/jabref/shared/DBMSSynchronizer.java
Issue: https://github.com/JabRef/jabref/issues/2219.
This issue is fixed by overloading and using the `parse(...)` method in `MetaDataParser`.
The reason was a reset of the local field `metaData` in `DBMSSynchronizer`. This caused other instances containing this field not to be up-to-date.
=> Fix local metadata synchronization (fixes: #2219)

src/main/java/net/sf/jabref/gui/groups/GroupDialog.java, src/main/java/net/sf/jabref/gui/maintable/MainTableColumn.java, src/main/java/net/sf/jabref/gui/specialfields/SpecialFieldValueViewModel.java, src/main/java/net/sf/jabref/logic/exporter/OpenDocumentRepresentation.java, src/main/java/net/sf/jabref/logic/layout/LayoutEntry.java, src/main/java/net/sf/jabref/logic/openoffice/OOBibStyle.java, src/main/java/net/sf/jabref/logic/util/io/RegExpFileSearch.java, src/main/java/net/sf/jabref/logic/xmp/XMPSchemaBibtex.java, src/main/java/net/sf/jabref/model/database/BibDatabase.java
The method getResolvedField was in BibDatabase and in BibEntry with identical same code. This PR removes the copy from BibDatabase.
=> Remove duplicate code getResolvedFieldOrAlias

src/main/java/net/sf/jabref/FallbackExceptionHandler.java, src/main/java/net/sf/jabref/JabRefExecutorService.java, src/main/java/net/sf/jabref/JabRefMain.java, src/main/java/net/sf/jabref/gui/util/FallbackExceptionHandler.java
Previously, uncaught exceptions were simply ignored by our logging framework. With these changes, they are properly logged in log4j.
One would actually want to show a nice error dialog to the user, but well, this is something for another time https://github.com/JabRef/jabref/issues/2288.
=> Add fallback exception handler

src/test/java/net/sf/jabref/logic/citationstyle/CitationStyleGeneratorTest.java
The discussion at https://github.com/michel-kraemer/citeproc-java/commit/729ca2c21c508654e51a713399c8becf2c0dff39 revealed that `\r` does not appear as line separator alone. Thus, our tests should be adapted accordingly.
Refs https://github.com/koppor/jabref/issues/174
=> Adapt CSL tests to CRLF and LF

src/main/java/net/sf/jabref/gui/actions/BaseAction.java, src/main/java/net/sf/jabref/gui/actions/CopyBibTeXKeyAndLinkAction.java, src/main/java/net/sf/jabref/gui/bibtexkeypattern/SearchFixDuplicateLabels.java, src/main/java/net/sf/jabref/gui/exporter/SaveDatabaseAction.java, src/main/java/net/sf/jabref/gui/externalfiles/FindFullTextAction.java, src/main/java/net/sf/jabref/gui/groups/GroupAddRemoveDialog.java, src/main/java/net/sf/jabref/gui/worker/AbstractWorker.java
Reviewing #2307 I noticed that `BaseAction` and `AbstractWorker` use `Throwable` in their method signature. I cannot find a reason for linking to the highest possible error type here. After all, this has nothing to do with JVM errors or the like. 
I moved the type one step down in the hierarchy to `Exception` which is still basic enough to cover every possible.
=> Replace usages of Throwable with Exception

CHANGELOG.md, src/main/java/net/sf/jabref/logic/util/Version.java, src/test/java/net/sf/jabref/logic/util/VersionTest.java
Fixes: https://github.com/JabRef/jabref/issues/2298
The version check now considers the dev tag.
=> Consider dev tag in version comparison

CHANGELOG.md, src/main/java/net/sf/jabref/logic/integrity/DOIValidityChecker.java, src/main/java/net/sf/jabref/logic/integrity/IntegrityCheck.java, src/main/java/net/sf/jabref/logic/util/DOI.java, src/main/resources/l10n/JabRef_da.properties, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fa.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_in.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_nl.properties, src/main/resources/l10n/JabRef_no.properties, src/main/resources/l10n/JabRef_pt_BR.properties, src/main/resources/l10n/JabRef_ru.properties, src/main/resources/l10n/JabRef_sv.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_vi.properties, src/main/resources/l10n/JabRef_zh.properties, src/test/java/net/sf/jabref/logic/integrity/IntegrityCheckTest.java
Refs #1445
Adds an integrity check to determine whether we can handle the content in the DOI field of a bib entry.
=> Add DOI integrity check

CHANGELOG.md
A user suggested to improve the v3.7 changelog at http://discourse.jabref.org/t/where-is-doi-to-bibtex-websearch-option-in-jabref-3-7/359/3?u=koppor
I did this here and also updated the help page at https://github.com/JabRef/help.jabref.org/pull/138.
=> Add longer explanation for ID-based entry generation.

CHANGELOG.md, src/main/java/net/sf/jabref/gui/preftabs/AppearancePrefsTab.java
Fixes the issue mentioned in http://discourse.jabref.org/t/cannot-start-jabref-3-7-3-6-on-ubuntu-16-04/361/4
=> Fix opening of preference dialog with Java 9

src/main/java/net/sf/jabref/gui/errorconsole/ErrorConsoleController.java, src/main/java/net/sf/jabref/gui/errorconsole/ErrorConsoleViewModel.java, src/main/resources/net/sf/jabref/gui/errorconsole/ErrorConsole.css, src/main/resources/net/sf/jabref/gui/errorconsole/ErrorConsole.fxml
The log messages in the list view of the error console can now be selected and copied. The error message will also automatically scroll to the newest log message. Refs #2210
=> Improvements to the JavaFX Error Console

build.gradle, external-libraries.txt
Changes made:
- Added a compile dependency on com.eclipsesource.j2v8 in build.gradle
We are using citeproc-java library in CitationStyleGenerator to generate previews, which itself is basically a wrapper around the javascript library citeproc-js. Switching to V8 engine dramatically improves the time taken to generate these previews. For example, on my laptop, generating preview used to take about 20s for the first preview, and 10s for each subsequent preview; using V8 reduces both by a factor of 10.
=> [WIP] Use v8 engine for CSL

build.gradle
The changelog of swingx is available there: https://java.net/jira/browse/SWINGX?selectedTab=com.atlassian.jira.jira-projects-plugin:changelog-panel
The only changelog entry with "memory leak" is https://java.net/jira/browse/SWINGX-299. I don't know, wether this is related.
I am aware of https://github.com/JabRef/jabref/issues/271. Thus, I manually tested which version to use and 1.6.4 seems to be the latest version usable.
We should check whether this helps solving #2247.
- [n/a] Change in CHANGELOG.md described
- [n/a] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
=> Update swingx from 1.6.1 to 1.6.4

src/main/java/net/sf/jabref/logic/importer/fetcher/MedlineFetcher.java, src/test/java/net/sf/jabref/logic/importer/fetcher/MedlineFetcherTest.java
Fix #2012 
Checks if the month field is present. In the case it's present, the month field is set to bibtex format using MonthUtil.
=> Fix Issue 2012: Use bibtexformat for month field in medlinefetcher

src/main/java/net/sf/jabref/gui/EntryCustomizationDialog.java, src/main/java/net/sf/jabref/gui/EntryTypeList.java, src/main/java/net/sf/jabref/gui/FieldSetComponent.java, src/main/java/net/sf/jabref/gui/preftabs/FontSelectorDialog.java
Hi guys,
Sorry in advance for the long text.
We are researchers in software engineering that currently work on user interface (UI) bad coding practices. We are studying UI listeners, in particular listeners that manage several widgets, like the following listener extracted from JabRef:
```
public void valueChanged(ListSelectionEvent evt) {
Object source = evt.getSource();
if (familyList.equals(source)) {
String family = familyList.getSelectedValue();
if (family != null) {
familyField.setText(family);
}
} else if (sizeList.equals(source)) {
String size = sizeList.getSelectedValue();
if (size != null) {
sizeField.setText(size);
}
} else if (styleList.equals(source)) {
String style = styleList.getSelectedValue();
if (style != null) {
styleField.setText(style);
}
}
updatePreview();
}
```
In …
=> Remove four Blob listeners

build.gradle, src/main/java/net/sf/jabref/gui/AbstractController.java, src/main/java/net/sf/jabref/gui/AbstractDialogView.java, src/main/java/net/sf/jabref/gui/errorconsole/ErrorConsoleController.java, src/main/java/net/sf/jabref/gui/help/AboutDialogController.java, src/main/java/net/sf/jabref/gui/keyboard/KeyBindingAction.java, src/main/java/net/sf/jabref/gui/keyboard/KeyBindingViewModel.java, src/main/java/net/sf/jabref/gui/keyboard/KeyBindingsDialogController.java, src/main/java/net/sf/jabref/gui/keyboard/KeyBindingsDialogView.java, src/main/java/net/sf/jabref/gui/keyboard/KeyBindingsDialogViewModel.java, src/main/java/net/sf/jabref/gui/util/RecursiveTreeItem.java, src/main/resources/net/sf/jabref/gui/keyboard/KeyBindingsDialog.fxml, src/test/java/net/sf/jabref/gui/keyboard/KeyBindingsDialogViewModelTest.java
Another step for #2290.
Only change in behavior is that all the categories are collapsed by default. The reason is that I have no idea how to cleanly implement "expanded by default". But in the end I actually think in this way the dialog is a bit more usuable as the user sees all the categories.
@koppor the localization tests fail, I think this issue resulted from the recent merge.
=> [FX] Review key bindings dialog

CHANGELOG.md, src/main/java/net/sf/jabref/logic/TypedBibEntry.java, src/main/java/net/sf/jabref/logic/cleanup/MoveFilesCleanup.java, src/main/java/net/sf/jabref/logic/cleanup/RelativePathsCleanup.java, src/main/java/net/sf/jabref/logic/cleanup/RenamePdfCleanup.java, src/main/java/net/sf/jabref/logic/importer/fetcher/ArXiv.java, src/main/java/net/sf/jabref/logic/integrity/IntegrityMessage.java, src/main/java/net/sf/jabref/logic/integrity/NoBibtexFieldChecker.java, src/main/java/net/sf/jabref/logic/msbib/BibTeXConverter.java, src/main/java/net/sf/jabref/model/entry/BibEntry.java, src/main/java/net/sf/jabref/model/entry/BibLatexEntryTypes.java, src/main/java/net/sf/jabref/model/entry/EntryConverter.java, src/test/java/net/sf/jabref/logic/cleanup/CleanupWorkerTest.java, src/test/java/net/sf/jabref/logic/importer/fetcher/ArXivTest.java, src/test/java/net/sf/jabref/logic/importer/fileformat/BibtexImporterTest.java, src/test/java/net/sf/jabref/logic/integrity/NoBibTexFieldCheckerTest.java, src/test/resources/net/sf/jabref/logic/exporter/MsBibExportFormatTest7.bib, src/test/resources/net/sf/jabref/logic/importer/fileformat/BibtexImporter.examples.bib, src/test/resources/net/sf/jabref/logic/importer/fileformat/MsBibImporterTest3.bib, src/test/resources/net/sf/jabref/logic/importer/fileformat/MsBibImporterTest4.bib, src/test/resources/net/sf/jabref/logic/importer/fileformat/MsBibImporterTest5.bib, src/test/resources/net/sf/jabref/logic/importer/fileformat/MsBibImporterTest6.bib, src/test/resources/net/sf/jabref/logic/importer/fileformat/MsBibImporterTest7.bib
I'd like to copy bibtex entries to biblatex databases and vice versa. When using required fields only, this works perfectly. When in biblatex mode, JabRef does not display the value of `journal` in the required fields, because JabRef demands the field `journaltitle`. This is not only confusing for me, but also for other users: #2209.
I know that a clean solution is #521. This, however, won't happen this year.
I also know that a bibtex-to-biblatex converter and biblatex-to-bibtex converter is another solution. This, however, forces users to run these when copying and pasting between databases. This could be solved by running these converters silently when copying and pasting. When JabRef is used in parallel to other software (such as Notepad++), this does not help. I cannot force everyone …
=> Be more friendly when using journal alias field

CHANGELOG.md, src/main/java/net/sf/jabref/gui/fieldeditors/FileListEditor.java
Bug fix for issue number 2391.
When clicking on "Get fulltext" from the editor view, the autoSetLinks function should be performed only to the entry being edited.
Before this pr, the autoSetLinks function uses the selected entries, which can causes problems in different cases (See issue number #2391 for details).
=> When clicking on "Get fulltext" in the editor view, link the files for the entry being edited instead of looking for the selected entries

CHANGELOG.md, src/main/java/net/sf/jabref/logic/importer/fileformat/BiblioscapeImporter.java, src/main/java/net/sf/jabref/logic/importer/fileformat/MedlinePlainImporter.java, src/main/java/net/sf/jabref/logic/importer/fileformat/RisImporter.java, src/main/java/net/sf/jabref/logic/importer/util/OAI2Handler.java, src/main/java/net/sf/jabref/logic/integrity/NoBibtexFieldChecker.java, src/main/java/net/sf/jabref/model/entry/BibtexEntryTypes.java, src/main/java/net/sf/jabref/model/entry/FieldName.java, src/main/java/net/sf/jabref/model/entry/InternalBibtexFields.java, src/main/java/net/sf/jabref/preferences/JabRefPreferences.java, src/test/java/net/sf/jabref/logic/integrity/IntegrityCheckTest.java, src/test/java/net/sf/jabref/logic/integrity/NoBibTexFieldCheckerTest.java
This fixes #2390. The last implementation used `EntryConverter.FIELD_ALIASES_LTX_TO_TEX`. This implementation is based on `BibtexEntryTypes` and `BiblatexEntryTypes`. 
`JabRefPreferences.CUSTOM_TAB_NAME_num_` should be used to really determine the fields to check. This, however, is really a **huge** architectural rework.
It has to be checked, in following (seldom) situation:
- Field X is defined in JabRef's BiblatexEntryTypes
- Field X is added by the user to a general tab
JabRef now complains that X is Biblatex only.
* ISBN and ISBN are now BibTeX fields, too.
- Reason: Even though, both are not listed in [WikiPedia](https://en.wikipedia.org/wiki/BibTeX) and the [lncs style](ftp://ftp.springer.de/pub/tex/latex/llncs/latex2e/splncs03.bst), I see them so hard tied to a book and article, …
=> [WIP] Introduce explicit list of ALL_BIBLATEX_ONLY_FIELDS

CHANGELOG.md, src/main/java/net/sf/jabref/model/groups/WordKeywordGroup.java, src/test/java/net/sf/jabref/model/entry/KeywordListTest.java, src/test/java/net/sf/jabref/model/groups/ExplicitGroupTest.java
=> Fix #2394 groups matching with brackets in name

CHANGELOG.md, src/main/java/net/sf/jabref/gui/fieldeditors/HtmlTransferable.java, src/main/java/net/sf/jabref/gui/worker/CitationStyleToClipboardWorker.java, src/test/java/net/sf/jabref/gui/fieldeditors/HtmlTransferableTest.java, src/test/java/net/sf/jabref/gui/worker/CitationStyleToClipboardWorkerTest.java
When copying citations to the clipboard using HTML (introduced by #2363), pasting into Nodepad++ leads to pure HTML be pasted. We had a short discussion during #2363 what would be more useful: HTML code or Text. I think, text is better.
When using "Copy as Text" offered by using the CSL library, following is the text reaching Nodepad++:
> 1.Garcia-Molina, H., Salem, K.: Sagas. In: Dayal, U. and Traiger, I.L. (eds.) SIGMOD’87: Proceedings of the Association for Computing Machinery Special Interest Group on Management of Data 1987 Annual Conference. pp. 249–259 ACM Press (1987).
When using the results of this PR and using Copy as HTML:
> 1. Garcia-Molina, H., Salem, K.: Sagas. In: Dayal, U. and Traiger, I.L. (eds.) SIGMOD’87: Proceedings of the Association for Computing Machinery Special …
=> Improve CSL copy

CHANGELOG.md, src/main/java/net/sf/jabref/logic/net/URLDownload.java, src/test/java/net/sf/jabref/logic/net/URLDownloadTest.java
I wanted to download ftp://ftp.informatik.uni-stuttgart.de/pub/library/ncstrl.ustuttgart_fi/INPROC-2016-15/INPROC-2016-15.pdf using the "Download from URL" button. However, this did not succeed as JabRef insisted on an HTTPURLConnection. 
- [n/a] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
=> Alllow FTP URLs for downloading

CHANGELOG.md, src/main/java/net/sf/jabref/gui/groups/GroupTreeNodeViewModel.java
Fix of #2319: Function "collapse subtree" is working again
- ~~[ ] Tests created for changes~~ UI only
=> Fix "collapse sub tree" functionality for groups tree

CHANGELOG.md, src/main/java/net/sf/jabref/logic/net/ProxyRegisterer.java
Another small fix... refs #2249 
Proxy settings are now also used for HTTPS connections
=> Use proxy configuration also for HTTPS connections - fixes #2249

src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/exporter/SaveAllAction.java, src/main/java/net/sf/jabref/gui/exporter/SaveDatabaseAction.java, src/main/java/net/sf/jabref/gui/worker/AbstractWorker.java, src/main/java/net/sf/jabref/gui/worker/Worker.java
This is a refactoring PR (yeah, I know we do not really want pure refactoring PRs for now), and it is open for discussion (I will not throw a tantrum if it does not get merged).
I ran into the `Worker` interface, which does really nothing but extend the `Runnable` interface. I fail to see the point in this additional level of indirection. The `Worker` interface is supposed to mark tasks that should not be executed on the EDT, but there is nothing in the interface to actually maintain that apart from a comment line. All code using the `Worker` depends on the object being a `Runnable`, the `Worker` aspect is basically ignored, as there is nothing to consider in the first place. 
Instead, there is class `AbstractWorker` which implements the `Worker` aka `Runnable` interface and actually does …
=> Remove the redundant worker interface

CHANGELOG.md, src/main/java/net/sf/jabref/logic/importer/fetcher/DoiFetcher.java, src/test/java/net/sf/jabref/logic/importer/fetcher/DoiFetcherTest.java, src/test/java/net/sf/jabref/logic/importer/fetcher/TitleFetcherTest.java
Counterproposal to https://github.com/JabRef/jabref/pull/2424 😈
=> Fix #2417: DOI no longer contains URL

CHANGELOG.md, src/main/java/net/sf/jabref/logic/importer/fetcher/ArXiv.java, src/test/java/net/sf/jabref/logic/importer/fetcher/ArXivTest.java
=> Fix #2427: Arxiv fetcher works with prefix

CHANGELOG.md, src/main/java/net/sf/jabref/logic/formatter/bibtexfields/NormalizePagesFormatter.java, src/test/java/net/sf/jabref/logic/formatter/bibtexfields/NormalizePagesFormatterTest.java
This fixes https://github.com/koppor/jabref/issues/212
I worked with the article https://doi.org/10.1145/1658373.1658375 which had pages formatted as `2:1--2:33`. Since I use the recommended BibTeX save actions, these pages got destroyed. This PR fixes that.
=> Add support for pages in the format 2:1-2:33

CHANGELOG.md, src/main/java/net/sf/jabref/logic/exporter/MetaDataSerializer.java, src/main/java/net/sf/jabref/logic/importer/util/MetaDataParser.java, src/test/java/net/sf/jabref/logic/exporter/BibtexDatabaseWriterTest.java
Fixes #2426 and is ready for review.
Attempts to fix  #2426.
Is not yet functional, since the issue goes somewhat deeper and affects LaTeX-encoding things in all MetaData, also groups. The problem is line 64 in MetaDataSerializer:
```
stringBuilder.append(StringUtil.quote(dataItem, MetaData.SEPARATOR_STRING, MetaData.ESCAPE_CHARACTER)).append(MetaData.SEPARATOR_STRING);
```
For every MetaData item, all special characters are quoted, including the quoting symbol (`\`). Thus, if there is a `\` in the MetaData, it is quoted during serialization, resulting in `\\`, which is read as such and requoted on the next serialization, resulting in `\\\\` and so on. 
Unfortunately, unquoting the text during parsing and quoting it again during writing does not help, since a single `\` will simply be …
=> Escaping of escape symbols in the MetaData

CHANGELOG.md, src/main/java/net/sf/jabref/gui/date/DatePickerButton.java
=> unregister DateChangeListener in manual update method

CHANGELOG.md, src/main/java/net/sf/jabref/gui/search/GlobalSearchBar.java
Implemented a feature request from the forum (http://discourse.jabref.org/t/ctrl-f-behaviour/408).
When pressing <kbd>Ctrl</kbd> + <kbd>F</kbd> and the searchbar is already focused the current query will be selected.
This is the same behavior as many other programs have.
=> ctrl+f selects current query while the searchbar is focusd

CHANGELOG.md, src/main/java/net/sf/jabref/gui/maintable/MainTableColumn.java, src/main/java/net/sf/jabref/gui/maintable/MainTableNameFormatter.java, src/test/java/net/sf/jabref/logic/layout/format/LatexToUnicodeFormatterTest.java
And although I said that I would not work on JabRef for the next two weeks, here is a PR. This stuff is addictive and I need help :-/
Fixes #2458. Author name formatting in the main table is handled different from the formatting of the remaining columns and we simply forgot to perform the unicode conversion also for the author column.
=> Fix conversion of tilde n

CHANGELOG.md, src/main/java/net/sf/jabref/model/strings/LatexToUnicode.java, src/test/java/net/sf/jabref/logic/layout/format/LatexToUnicodeFormatterTest.java
This is a follow up for fixing  #2458
The combinations `\'n` and `\\'{n}` are converted from LaTeX to different symbols in Unicode.
This was really hard to track down. It was not a problem in our conversion maps, but in `LatexToUnicode`. The ultimate reason is that this code is just an utter mess of hacks and I could only fix this by adding another ugly map on top of this heap.
We have already identified this class to cause performance issues and, as you can see here, it is very difficult to maintain. We should consider removing the functionality and rewriting it from scratch or (preferably) replace it with an external library. After all, converting a LaTeX string to Unicode seems sufficiently well-defined that there is some library for this out there.
=> Fix conversion of "'n" and "\'{n}" from LaTeX to Unicode

CHANGELOG.md, src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/gui/JabRefFrame.java, src/main/java/net/sf/jabref/gui/search/GlobalSearchBar.java
Fixes https://github.com/JabRef/jabref/issues/2468.
If one deleted the current query it was not saved (every basepanel can have it's own query).
The only neede change is the line in `GlobalSearchBar.java`.
=> Save deletion of current searchquery

src/main/java/net/sf/jabref/gui/groups/GroupAddRemoveDialog.java
Program hung if user clicked ExpandAll or CollapseAll dialog button when
assigning refs to groups. Also changed CollapseAll to show 1st-level
children of AllEntries node.
Any thoughts? Big fan of JabRef but new to open source, git, etc.  Let me know if anything else is required.
CC @chm052
=> Fixed bug when assigning refs to groups.

CHANGELOG.md, src/main/java/net/sf/jabref/gui/importer/fetcher/EntryFetchers.java, src/main/java/net/sf/jabref/logic/importer/fetcher/DoiFetcher.java, src/test/java/net/sf/jabref/gui/importer/fetcher/EntryFetchersTest.java
Implement https://github.com/JabRef/jabref/issues/2432.
Added the option to update bibliographic information from DOI to the sidebar of the entryeditor.
=> Add update from DOI to the entryeditor sidebar

CHANGELOG.md, src/main/java/net/sf/jabref/logic/auxparser/AuxParser.java
Fixes #2475
A very simple change. Our aux export had some problems when there were crossrefs to other entries. Such references could result in multiple additions of the referenced entry to the generated bib file. A simple check avoids this
=> Fix aux duplicates

CHANGELOG.md, src/main/java/net/sf/jabref/JabRefGUI.java, src/main/java/net/sf/jabref/cli/ArgumentProcessor.java, src/main/java/net/sf/jabref/gui/importer/actions/OpenDatabaseAction.java, src/main/java/net/sf/jabref/logic/importer/OpenDatabase.java, src/main/java/net/sf/jabref/logic/importer/ParserResult.java, src/main/java/net/sf/jabref/logic/importer/fileformat/BibTeXMLImporter.java, src/main/java/net/sf/jabref/logic/importer/fileformat/BibtexParser.java, src/main/java/net/sf/jabref/logic/importer/fileformat/MedlineImporter.java, src/main/java/net/sf/jabref/logic/importer/fileformat/ModsImporter.java, src/main/java/net/sf/jabref/logic/importer/fileformat/PdfContentImporter.java, src/main/java/net/sf/jabref/logic/importer/fileformat/PdfXmpImporter.java, src/main/java/net/sf/jabref/logic/importer/util/GroupsParser.java, src/test/java/net/sf/jabref/logic/bibtex/BibEntryAssert.java, src/test/java/net/sf/jabref/logic/importer/util/GroupsParserTest.java
Fixes https://github.com/JabRef/jabref/issues/2477 in the sense that a more detailed error message is displayed. 
The functional change is https://github.com/JabRef/jabref/pull/2488/files#diff-48e24aa13e9cd41a20bf4e79f4ad7d6bR129, while the rest is a bit of code cleanup (introduction of helper methods, removal of unused code, change public -> private if applicable).
=> Catch NumberFormatException if context can't be parsed in groups

circle.yml
I just stumbled over https://circleci.com/docs/test-metadata/#gradle-junit-results .
Not sure if we still use circle ci ?!
=> Save test reports as build artifacts on circle ci

CHANGELOG.md, src/main/java/net/sf/jabref/gui/keyboard/KeyBinding.java
Fixes #2251. This solution is the quick solution by changing the shortcut. The alternative is to change the ActionTable etcl.
- [no] Tests created for changes
- [n/a] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
=> Change key binding for cleanup from F8 to ALT+F8

CHANGELOG.md, src/main/java/net/sf/jabref/model/strings/HTMLUnicodeConversionMaps.java, src/main/java/net/sf/jabref/model/strings/LatexToUnicode.java, src/test/java/net/sf/jabref/logic/layout/format/LatexToUnicodeFormatterTest.java
Fixes #2500. This repairs the apostrophe handling in the LaTeX to unicode conversion broken by #2464 and maintains the special handling of apostrophes in conjunction with the character 'n' that #2464 intended to fix. 
It increases complexity and reduces performance in the unicode conversion a tiny bit (through the additional checks that are now in there). Ultimately, the goal should be to replace the conversion with an external library.
=> Fix apostrophe conversion

CHANGELOG.md, src/main/java/net/sf/jabref/logic/importer/fileformat/RisImporter.java, src/test/java/net/sf/jabref/logic/importer/fileformat/RISImporterTestFiles.java, src/test/resources/net/sf/jabref/logic/importer/fileformat/RisImporterTestScience.bib, src/test/resources/net/sf/jabref/logic/importer/fileformat/RisImporterTestScience.ris
Fix for #2506.
The problem was that the T2 field was used for the journal title, if it comes first. Now T2 is only used for the journal title, if the field JO does not appear. I've also added the file from science direct as test case.
=> Fix journal title in ris importer

src/main/java/net/sf/jabref/pdfimport/PdfImporter.java
Prevented deadlock for #2482 when importing PDF by removing UI update via multiple threads.  Likely to be similar resolution for #2489 but insufficient information on non AWT thread to identify where fix should be made.
=> fix for #2482 deadlock on PDF import

CHANGELOG.md, src/main/java/net/sf/jabref/logic/formatter/bibtexfields/LatexCleanupFormatter.java, src/test/java/net/sf/jabref/logic/formatter/bibtexfields/LatexCleanupFormatterTest.java
Extracted Regexe in Patterns
Fix for #2451
=> Fix repeated escaping of % sign

CHANGELOG.md, src/main/java/net/sf/jabref/logic/formatter/bibtexfields/LatexCleanupFormatter.java, src/test/java/net/sf/jabref/logic/formatter/bibtexfields/LatexCleanupFormatterTest.java
Fix previous stackoverflow errror with large input
Follow up from #2451
=> Fix % sign cleanup

src/main/java/net/sf/jabref/gui/FileDialog.java
Fixes the exception Folder parameter must be a valid folder
Internal fix, 4.0.0 only
When no working directory is set and last used path was an actual file, File Dialog could not be opened.
Fixes #2522
=> Fix error when path is no valid directory

src/main/java/net/sf/jabref/gui/externalfiles/FindFullTextAction.java, src/main/java/net/sf/jabref/gui/fieldeditors/FileListEditor.java
Major changes:
- Download from URL will now insert at __first__ position (formerly last)
- Get Fulltext from URL will now insert at __first__ position(formerly last)
- Add Button will now insert at __last__ position (formerly at selected row)
=> Rework File links logic

src/main/java/net/sf/jabref/logic/importer/fetcher/CrossRef.java
Resolves #2431
Changes:
- We will now check 5 results instead of just the first one for a matching title.
=> Check more results returned by CrossRef API for matching

CHANGELOG.md, src/main/java/net/sf/jabref/gui/maintable/MainTableColumn.java
Fixes #2534 which resulted in authors with multiple surnames having their names cut off.
=> Maintable authors

CONTRIBUTING.md
Just stubled over the gradle format task in the CONTRIBUTING for formatting the code. However, the plugin is discontinued and was removed in 5004f1e20d54f82606557470acc8203c81aeb30e.
Thus, I just deleted that sentence and as I was already around, I read the whole fixing minor issues in the text.
=> CONTRIBUTING: Code formatter is no longer

src/main/java/net/sf/jabref/logic/auxparser/AuxParser.java, src/main/java/net/sf/jabref/logic/auxparser/AuxParserResult.java, src/main/java/net/sf/jabref/model/database/BibDatabase.java, src/test/java/net/sf/jabref/model/database/BibDatabaseTest.java, src/test/resources/net/sf/jabref/logic/auxparser/config.bib
I'm making a method to properly copy entries from one database to another, including crossref entries and used strings. This is useful in generating a database from an aux file and for generating a database based on an OO/LO document. It could also be useful for generating a subdatabase from selected entries (or copying relevant strings when copying entries).
There are some problems though related to the preamble. In OO/LO the entries may come from several databases and there it is not obvious how to deal with the preamble. However, a possibly solvable problem is to detect which strings are used in the preamble.
In AuxParserTest @stefan-kolb have generated a test file with a string in the preamble. JabRef doesn't parse this in a way such that the string can be resolved automatically. …
=> [WIP] Proper copying of entries

CHANGELOG.md, build.gradle, external-libraries.txt, src/main/java/net/sf/jabref/gui/BasePanel.java, src/main/java/net/sf/jabref/logic/pdf/FileAnnotationCache.java
This is intended as a fix for #2546.
Note that the Guava Caches would allow for automated reloading of the entries, but this is not undertaken in this implementation. Instead everything should work as before with the LRUMap.
=> Replaced LRUMap with a Guava Cache

src/main/java/net/sf/jabref/gui/preftabs/ExportSettingsTab.java, src/main/java/net/sf/jabref/gui/preftabs/PreferencesDialog.java
I reordered the preferences tab as the current ordering made no sense to me.
We currently don't have a help on the preferences screen. So, it is not urgent to update the help pages. I found http://help.jabref.org/en/Autosave#activation, but the users will find the preference as I did not change the titles.
=> Reorder pferences tab to be more intuitive

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupSelector.java, src/main/java/org/jabref/preferences/JabRefPreferences.java
In the edit mode, you were able to select a few entries and assign them to a group with a single click.
As I think that drag&drop and the special "add to groups" dialog provide sufficient facilities to add entries to groups, I hereby propose to remove this "feature".  
Resolves https://github.com/JabRef/jabref/issues/1550.
=> Remove groups edit mode

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fetcher/ScienceDirect.java, src/test/java/org/jabref/logic/importer/fetcher/ScienceDirectTest.java
=> Add logic for new Sciencedirect pages

CHANGELOG.md, src/main/java/org/jabref/gui/FileDialog.java, src/main/java/org/jabref/gui/specialfields/SpecialFieldDatabaseChangeListener.java, src/main/java/org/jabref/gui/specialfields/SpecialFieldUpdateListener.java, src/main/java/org/jabref/logic/importer/OpenDatabase.java, src/main/java/org/jabref/logic/specialfields/SpecialFieldsUtils.java, src/test/java/org/jabref/logic/specialfields/SpecialFieldsUtilsTest.java
Fixes #2580 
Synch should now work appropriately.
Few questions here @koppor and all others:
Only the first one is synched with the special field. Was this always like this? Seems like a bug to me.
=> Keyword - Special field synchronization

src/test/java/org/jabref/logic/l10n/LocalizationConsistencyTest.java, src/test/java/org/jabref/logic/l10n/LocalizationParser.java, src/test/java/org/jabref/logic/l10n/LocalizationParserTest.java
=> Localization tests

CHANGELOG.md, src/main/java/org/jabref/pdfimport/PdfImporter.java
Fixes #2577 
Problem is not the filename 
Problem: You still get a warning that one file could not be imported, although it successfully worked.
I have unfortunately no idea if this code is at all correct, the DroppedFileHandler stuff looks suspicious to me, as it is normally used wit Drag and drop.
**Question**: Is there somewhere a method for linking pdfs?
=> Fix pdf file import when only one file selected and no entry created

CHANGELOG.md, src/main/java/org/jabref/logic/bibtex/LatexFieldFormatter.java, src/test/java/org/jabref/logic/bibtex/LatexFieldFormatterTests.java
This is my take at  #2561
So far, escaped braces were counted in when calculating brace balance in a field. This PR avoids counting them in. As a result, when somebody enters `{\}` into a field in the entry editor, a warning dialog appears. Previously, there was no dialog.
=> Improve braces checking

src/main/java/org/jabref/logic/bibtex/LatexFieldFormatter.java, src/test/java/org/jabref/logic/bibtex/LatexFieldFormatterTests.java
This is a followup to #2593 (still tackles the same issue, therefore no need for an additional changelog entry). It seems that we only had error tests in `LatexFieldFormatterTest` and since I added tests for an additional error condition, our tests did not notice that my changes broke the normal case. This PR fixes the error, simplifies the code a little further and adds tests for it.
=> Braces checking followup

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupNodeViewModel.java, src/main/java/org/jabref/gui/groups/GroupTree.css, src/main/java/org/jabref/gui/groups/GroupTree.fxml, src/main/java/org/jabref/gui/groups/GroupTreeController.java, src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java, src/main/java/org/jabref/gui/util/RecursiveTreeItem.java, src/test/java/org/jabref/gui/groups/GroupNodeViewModelTest.java, src/test/java/org/jabref/gui/util/RecursiveTreeItemTest.java, src/test/java/org/jabref/model/TreeNodeTest.java, src/test/java/org/jabref/model/TreeNodeTestData.java
Add textbox add the bottom of the groups panel which allows for filtering the groups by name. Implements #1904.
=> Implement #1904: filter groups

src/test/java/org/jabref/logic/bibtexkeypattern/BibtexKeyPatternUtilTest.java
I've changed a comment line in the test function veryShortTitle because it referenced the function veryShortTitle instead of shortTitle.
=> Fixed a small error in the code comments

CHANGELOG.md, src/main/java/org/jabref/logic/importer/util/GroupsParser.java, src/test/java/org/jabref/logic/importer/util/GroupsParserTest.java
Fixes the import of #2600 
The problem occurred when after the definition of a subgroup of level >0 a group definition with level 0 followed.
```
2 ExplicitGroup:15\;0\;;
0 ExplicitGroup:16\;0\;;
2 ExplicitGroup:17\;0\;;
```
~~- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org]~~(https://github.com/JabRef/help.jabref.org/issues)?)
=> Fix exception when parsing groups which contain a top level group

CHANGELOG.md, src/main/java/org/jabref/logic/bibtexkeypattern/BibtexKeyPatternUtil.java, src/test/java/org/jabref/logic/bibtexkeypattern/BibtexKeyPatternUtilTest.java, src/test/java/org/jabref/logic/bibtexkeypattern/MakeLabelWithDatabaseTest.java
Related to [#2604](https://github.com/JabRef/jabref/issues/2604) and [#2589](https://github.com/JabRef/jabref/issues/2589)
In the class BibtexKeyPatternUtil I've added cases for [title] and [camel] to try and make them conform to the [documentation](http://help.jabref.org/en/BibtexKeyPatterns).
@Siedlerchr was also working on this issue [here](https://github.com/JabRef/jabref/pull/2597). I found out that  
`CaseFormat.LOWER_CAMEL.to(CaseFormat.UPPER_CAMEL, entry.getField(FieldName.TITLE).orElse("").replaceAll("\\s+", ""));`
didn't work because to be able to transform the title into upper_camel this way the title has to be in  lower_camel case initially, which is often not the case.
I've added some test cases and changed a few others to conform to the documentation. 
I still need to take a …
=> Fix title-related key patterns in BibtexKeyPatternUtil

src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/entryeditor/EntryEditorTabRelatedArticles.java, src/test/java/org/jabref/logic/importer/fetcher/MrDLibFetcherTest.java
Fixes https://github.com/koppor/jabref/issues/231
Mr DLib did never load the recommendations, because of an NPE fix (#2567)
=> Fixes displaying of Mr DLib recommendations

CHANGELOG.md, src/main/java/org/jabref/gui/actions/CleanupAction.java, src/main/java/org/jabref/gui/cleanup/CleanupPresetPanel.java
=> Cleanup window has a scrollbar now.

src/main/java/org/jabref/logic/pdf/PdfAnnotationImporter.java
=> Fixed wrong logger import

src/main/java/org/jabref/collab/GroupChange.java, src/main/java/org/jabref/gui/IconTheme.java, src/main/java/org/jabref/gui/Main.css, src/main/java/org/jabref/gui/groups/GroupDialog.java, src/main/java/org/jabref/gui/groups/GroupNodeViewModel.java, src/main/java/org/jabref/gui/groups/GroupSelector.java, src/main/java/org/jabref/gui/groups/GroupTree.css, src/main/java/org/jabref/gui/groups/GroupTreeController.java, src/main/java/org/jabref/gui/util/ViewModelTreeTableCellFactory.java, src/main/java/org/jabref/logic/groups/DefaultGroupsFactory.java, src/main/java/org/jabref/logic/importer/util/GroupsParser.java, src/main/java/org/jabref/model/groups/AbstractGroup.java, src/main/resources/l10n/JabRef_da.properties, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fa.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_in.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_nl.properties, src/main/resources/l10n/JabRef_no.properties, src/main/resources/l10n/JabRef_pt_BR.properties, src/main/resources/l10n/JabRef_ru.properties, src/main/resources/l10n/JabRef_sv.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_vi.properties, src/main/resources/l10n/JabRef_zh.properties
The user can now specify an icon (and color) that is displayed next to the group's name. Moreover, a custom description text can be specified and will be shown on mouse-over.
Also the expanded status is now kept when switching between tabs.
Related issues:
- Color: http://discourse.jabref.org/t/assign-colors-to-groups/321
- Expansion status: https://github.com/JabRef/jabref/issues/1428
- Desrciption: https://sourceforge.net/p/jabref/feature-requests/489/ and https://sourceforge.net/p/jabref/feature-requests/818/
Things to note:
- Icon + color + description + expanded status are not yet written to the bib file (I will implement this in forthcoming PR)
- The UI in the groups dialog is pretty horrible. For the icon and the color it is just a text field, so in the current state the user has …
=> Add icon + color and description to groups

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/FileListEditor.java
=> F4 opens selected file in current JTable context

CHANGELOG.md, src/main/java/org/jabref/gui/FXDialogService.java, src/main/java/org/jabref/gui/FileDialog.java, src/main/java/org/jabref/gui/externalfiles/DownloadExternalFile.java, src/main/java/org/jabref/gui/externalfiles/FindFullTextAction.java, src/main/java/org/jabref/gui/filelist/FileListEntryEditor.java, src/main/java/org/jabref/gui/importer/ImportInspectionDialog.java, src/main/java/org/jabref/gui/util/DefaultTaskExecutor.java, src/main/java/org/jabref/gui/util/FileDialogConfiguration.java
Fix for #2572 
When running Get fulltext, the dialog is now a save dialog which enables to select a different folder or even a different filename. The initial filename which JabRef assigns is now also visible in the file dialog
~- [ ] Tests created for changes~
~- [X] Screenshots added (for bigger UI changes)
~- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org]~(https://github.com/JabRef/help.jabref.org/issues)?)
~- [ ] If you changed the localization: Did you run `gradle localizationUpdate`?~
=> Change dialog of download fulltext to save dialog

CHANGELOG.md, src/main/java/org/jabref/logic/exporter/FileSaveSession.java
Fix for #2635
Just tested in my Ubuntu VM. Works fine:
Permissions are now: 
`-rw-rw-r-- `
~- [ ] Tests created for changes~
~- [ ] Screenshots added (for bigger UI changes)~
~- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org]~(https://github.com/JabRef/help.jabref.org/issues)?)
~- [ ] If you changed the localization: Did you run `gradle localizationUpdate`?~
=> Set POSIX filepermissions to 644

src/main/java/org/jabref/JabRefGUI.java, src/main/java/org/jabref/gui/importer/actions/CheckForNewEntryTypesAction.java, src/main/java/org/jabref/gui/importer/actions/GUIPostOpenAction.java, src/main/java/org/jabref/gui/importer/actions/HandleDuplicateWarnings.java, src/main/java/org/jabref/gui/importer/actions/OpenDatabaseAction.java, src/main/java/org/jabref/logic/importer/OpenDatabase.java, src/main/java/org/jabref/logic/importer/util/ConvertLegacyExplicitGroups.java, src/main/java/org/jabref/logic/importer/util/PostOpenAction.java, src/main/java/org/jabref/migrations/FileLinksUpgradeWarning.java, src/test/java/org/jabref/logic/importer/util/ConvertLegacyExplicitGroupsTest.java
Previously, the conversion of the old groups format to the new one was performed after the database was completely loaded and displayed. Thus after every change during the conversion the groups panel and main table were redrawn, resulting in performance problems (in particular with larger db's). 
Now the conversion is done before the db is displayed (and thus nobody yet listens to the changes).
Fixes: http://discourse.jabref.org/t/v3-8-2-x64-windows-problem-saving-large-bib-libraries/456
=> Improve perfomance of opening a database that still used the old groups format

src/main/java/org/jabref/gui/errorconsole/ErrorConsoleViewModel.java, src/main/resources/l10n/JabRef_da.properties, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fa.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_in.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_nl.properties, src/main/resources/l10n/JabRef_no.properties, src/main/resources/l10n/JabRef_pt_BR.properties, src/main/resources/l10n/JabRef_ru.properties, src/main/resources/l10n/JabRef_sv.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_vi.properties, src/main/resources/l10n/JabRef_zh.properties
See #2573.
I also wanted to add the log details to the report without the necessity to paste them later on. Dunno why this was implemented this way initially (See https://github.com/JabRef/jabref/pull/1383). However, the explorer will cut off the arguments at some point so this did not work for me.
I  think it is not convenient if the user needs to add this info manually.
Maybe someone else has an idea how to change this.
I still think the current addition fixes #2573 for now.
=> Improve issue reporting a bit

CHANGELOG.md, src/main/java/org/jabref/gui/preftabs/PreferencesDialog.java
Fix for issue [#2559](https://github.com/JabRef/jabref/issues/2559).
Shows horizontal and vertical scroll bars when the content in the preference dialog gets too big.
=> Add scroll bars to preference dialog

build.gradle
The fetcher tests were not included in the calculation of code coverage. Hopefully, this is fixed with this PR.
=> Fix fetcher code coverage

CHANGELOG.md, src/main/java/org/jabref/logic/exporter/GroupSerializer.java, src/main/java/org/jabref/logic/importer/util/GroupsParser.java, src/main/java/org/jabref/logic/util/MetadataSerializationConfiguration.java, src/main/java/org/jabref/logic/util/strings/QuotedStringTokenizer.java, src/main/java/org/jabref/model/groups/AbstractGroup.java, src/main/java/org/jabref/model/groups/AutomaticKeywordGroup.java, src/main/java/org/jabref/model/groups/AutomaticPersonsGroup.java, src/main/java/org/jabref/model/groups/ExplicitGroup.java, src/test/java/org/jabref/logic/exporter/BibtexDatabaseWriterTest.java, src/test/java/org/jabref/logic/exporter/GroupSerializerTest.java, src/test/java/org/jabref/logic/importer/util/GroupsParserTest.java, src/test/resources/testbib/complex.bib
Serialize and parse:
- Icon (with customizable color) that is shown in the groups panel (implements a [feature request in the forum](http://discourse.jabref.org/t/assign-colors-to-groups/321)).
- Description text that is shown on mouse hover (implements old feature requests [489](https://sourceforge.net/p/jabref/feature-requests/489/) and [818](https://sourceforge.net/p/jabref/feature-requests/818/))
- "automatic groups" that automatically create subgroups based on a certain criteria (e.g. a subgroup for every author or keyword). Implements [91](https://sourceforge.net/p/jabref/feature-requests/91/), [398](https://sourceforge.net/p/jabref/feature-requests/398/) and [#1173](https://github.com/JabRef/jabref/issues/1173).
- Expansion status …
=> Finally write the new group properties to the bib file: icon with color, description, expanded status and automatic groups

CHANGELOG.md, src/main/java/org/jabref/gui/openoffice/OOBibBase.java, src/main/java/org/jabref/logic/openoffice/CitationEntry.java, src/main/java/org/jabref/logic/openoffice/OOPreFormatter.java, src/main/java/org/jabref/logic/openoffice/OOUtil.java
OpenOffice text formatting now handles nested tags properly [#2483](https://github.com/JabRef/jabref/issues/#2483)
Formerly it was a Set, so nested tags were not kept and consequently the first closing tag removes (both) opening tags.
```
Formerly: <i>some<i>test</i>text</i> ->[i], [i], []
Now: -> [i], [i,i], [i], []
```
=> OO formatting

src/test/java/org/jabref/logic/importer/fetcher/GoogleScholarTest.java, src/test/java/org/jabref/support/DevEnvironment.java
Google Scholar tests currently fail. This PR just follows the comment given within the test cases and disables the Google Scholar tests on **all** CI Servers.
We might revert this if we have time to fix Google Scholar.
Refs #2173
=> Disalbe Google Scholar tests on all CI environments

eclipse.gradle
`@FXML ` and other  annotations on fields will no stay in the same line 
e.g. `    @FXML private TreeTableView<GroupNodeViewModel> groupTree;`
instead of
```
@FXML
private TreeTableView<GroupNodeViewModel> groupTree;
```
For methods I decided to not change it, as it would affect annotations like
`@deprecated, @SuppressWarning`, too
Additionally I changed the cleanup to use organize imports
=> Changed codeformatting for better fxml annotation

src/main/java/org/jabref/JabRefException.java, src/main/java/org/jabref/gui/logging/GuiAppender.java, src/main/java/org/jabref/gui/util/DefaultTaskExecutor.java
Hopefully, fixes that the error console is not updated properly #2667 as well as that Swing errors lead to frezzing #2680. At least for me, it works now without problems. @stefan-kolb @lynyus can you please also check it.
For the error console, I took the suggestion https://github.com/JabRef/jabref/issues/2667#issuecomment-288742546 by @matthiasgeiger. The freezing after a Swing message occurred since 
̀`LOGGER.warn("No localized message exception message defined. Falling back to getMessage().");`
lead to recursive calls (actually, Log4j has some logic to prevent deadlocks but these don't take effect since the original message is thrown in the Swing thread, while the above "no localized messsage" is posted in the JavaFX thread.). I simply changed it to log level "debug", which effectively …
=> Fix #2680 and fix #2667: Swing errors are catched properly and without freezing

src/main/java/org/jabref/logic/importer/fileformat/BibtexParser.java, src/main/java/org/jabref/logic/integrity/BibtexKeyChecker.java, src/main/java/org/jabref/logic/integrity/IntegrityCheck.java, src/test/java/org/jabref/logic/importer/fileformat/BibtexParserTest.java
As we have an integrity check for this and BibTeX keys are no longer required for the groups.
Issue was raised in https://github.com/JabRef/jabref/issues/2599#issuecomment-290681963.
=> Parser no longer warns about empty BibTeX keys

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupNodeViewModel.java, src/main/java/org/jabref/gui/groups/GroupSelector.java, src/main/java/org/jabref/gui/groups/GroupTreeCellRenderer.java, src/main/java/org/jabref/gui/groups/GroupTreeController.java, src/main/java/org/jabref/gui/groups/GroupTreeNodeViewModel.java, src/main/java/org/jabref/gui/preftabs/GroupsPrefsTab.java, src/main/java/org/jabref/model/strings/StringUtil.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/main/resources/l10n/JabRef_da.properties, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fa.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_in.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_nl.properties, src/main/resources/l10n/JabRef_no.properties, src/main/resources/l10n/JabRef_pt_BR.properties, src/main/resources/l10n/JabRef_ru.properties, src/main/resources/l10n/JabRef_sv.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_vi.properties, src/main/resources/l10n/JabRef_zh.properties
Will merge immediately since they are only small changes...
=> Fix a few smaller group related things 

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/logic/importer/WebFetchers.java, src/main/java/org/jabref/logic/importer/fetcher/ArXiv.java, src/main/java/org/jabref/model/entry/identifier/ArXivIdentifier.java, src/test/java/org/jabref/logic/importer/WebFetchersTest.java, src/test/java/org/jabref/logic/importer/fetcher/ArXivTest.java
Find arXiv ids for multiple entries using Quality -> Lookup identifier -> ArXiv (similar to the same solution for DOI).
=> Add ArXiv identifier batch lookup

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupDialog.java, src/main/java/org/jabref/gui/groups/GroupNodeViewModel.java, src/main/java/org/jabref/logic/exporter/GroupSerializer.java, src/main/java/org/jabref/logic/importer/util/GroupsParser.java, src/main/java/org/jabref/logic/util/TreeCollector.java, src/main/java/org/jabref/model/ChainNode.java, src/main/java/org/jabref/model/database/BibDatabase.java, src/main/java/org/jabref/model/entry/Keyword.java, src/main/java/org/jabref/model/entry/KeywordList.java, src/main/java/org/jabref/model/groups/AutomaticGroup.java, src/main/java/org/jabref/model/groups/AutomaticKeywordGroup.java, src/main/java/org/jabref/model/groups/GroupTreeNode.java, src/main/java/org/jabref/model/util/TreeCollector.java, src/test/java/org/jabref/gui/groups/GroupNodeViewModelTest.java, src/test/java/org/jabref/logic/exporter/GroupSerializerTest.java, src/test/java/org/jabref/logic/importer/util/GroupsParserTest.java, src/test/java/org/jabref/model/entry/KeywordListTest.java, src/test/java/org/jabref/model/entry/KeywordTest.java, src/test/java/org/jabref/model/groups/AutomaticKeywordGroupTest.java
The automatic keywords group now supports hierarchical keywords. 
The changes mainly concentrate on the keywords class...so this may have some unwanted side effects in other parts (but I didn't noticed anything unusual in my tests).
Note: Bib files containing an automatic keyword from prior 4.0 tests can no longer be opened and the lines containing `AutomaticKeywordGroup` have to be deleted.
=> Fix #628: implement hierarchical keywords

CHANGELOG.md, src/main/java/org/jabref/logic/layout/format/LatexToUnicodeFormatter.java, src/main/java/org/jabref/model/strings/LatexToUnicodeAdapter.java, src/test/java/org/jabref/logic/layout/format/LatexToUnicodeFormatterTest.java
Fixes #2664
Single underscores that are not followed by `{` are not converted to unicode during the LaTeX to unicode conversion. This is not actually correct according to the rules of LaTeX, but seems to be an important exception required by our users.
This is achieved by the following:
1. Replace all single underscores with `JABREFUNDERSCORE`
2. Do the unicode conversion
3. Replace `JABREFUNDERSCORE` with an underscore
TODO: We should find a better magic word instead of `JABREFUNDERSCORE`, because every character will be processed by latex2unicode and that costs performance. However, it should still be long and unique enough so that we avoid accidental conversions. Suggestions anyone?
=> Avoid conversion of single underscores

src/main/java/org/jabref/logic/importer/util/MetaDataParser.java, src/main/java/org/jabref/model/metadata/MetaData.java, src/test/java/org/jabref/logic/exporter/BibtexDatabaseWriterTest.java, src/test/resources/testbib/complex.bib
Right now, files written with 4.0 cannot be opened in older versions. The new format of the groups leads to a NPE. 
As a way out, I changed the tag for the groups tree from `groupstree` to `group` (`groups` was already used by previous version way back). Thus older versions completely ignore the group tree and no longer try to parse it, so no NPE is thrown. On the downside, however, the groups tree is deleted upon save in the older version. Still a bit better than a crashing Jabref in my opinion.
=> Write groups under tag `group` instead of `groupstree` to enhance compatibility with previous versions

CHANGELOG.md, src/main/java/org/jabref/gui/maintable/MainTableColumn.java, src/main/java/org/jabref/model/entry/BibEntry.java
As suggested by @koppor in #2671, removes any unicode conversion for the key field, internally and in the main table.
=> Unicode conversion bibtexkey

src/main/java/org/jabref/gui/groups/GroupTreeController.java, src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java
Fixed that JabRef for Mac OS X was freezing / not responding when using the "add subgroup" or "edit group" feature. Also fixed some menu items which had the wrong functionality. Refs #2722
=> Fixed freeze on Mac OS X when creating/editing groups

src/main/java/org/jabref/gui/IconTheme.java, src/main/java/org/jabref/logic/groups/DefaultGroupsFactory.java
Remove the hidden reference of gui in logic.
=> Remove gui dependency in logic

.travis.yml
As many of @JabRef/developers are annoyed by randomly failing fetcher tests, here's an option to test them but ignore them for the overall build output.
Waiting for your comments if we should do it this way for now.
=> Allow failures for fetcher test

src/main/java/org/jabref/logic/bibtexkeypattern/BibtexKeyPatternUtil.java, src/test/java/org/jabref/logic/bibtexkeypattern/MakeLabelWithoutDatabaseTest.java
I would like to offer my fix for the issue  2701: JabRef would find too many files when they are search with the [year]_[auth].* pattern. The reason seems to be a 'null' database passed to the BibtexKeyPatternUtil.makeLabel(BibEntry, String, Character, BibDatabase) method, and a null pointer exception is triggered. As a result, the '[auth]' part of the pattern was erased and ignored. With the suggested fix, JabRef uses the '[auth]' part of the pattern and finds just the files with the matching author, as expected. A relevant unit test was added; no other tests were broken.
- [x ] Tests created for changes -- 1 unit test added;
- [x ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?) -- the issue #2701 …
=> Fix 2701 too may files found

src/main/java/org/jabref/model/strings/LatexToUnicodeAdapter.java, src/test/java/org/jabref/logic/layout/format/LatexToUnicodeFormatterTest.java
This is a follow up for https://github.com/JabRef/jabref/issues/2596 and https://github.com/JabRef/jabref/pull/2601. I'd like to test how I can reproduce the behavior of ordinals.
Can someone explain me, why I don't get Unicode as result here?
=> Add test for ordinals

src/main/java/org/jabref/gui/entryeditor/FileAnnotationTab.java
Still, the real reason is a missing file...
=> Fixes #2766 If file is not found annotations might be null

src/main/java/org/jabref/gui/SidePaneManager.java
Some older versions had different names for the side pane components and their preferred sizes are still associated with these old names. Thus opening a newer JabRef always logged some errors, which only can be resolved by resetting the preferences. 
This PR changes the log level from error to debug since I don't think that the size of a side pane is that essential.
=> Do not log an exception if side pane was not found

eclipse.gradle
This changes the default line length from 120 to the maximum 9999, so long lines are no longer wrapped when running the formatter
=> Set eclipse line wrapping to maximum

src/main/java/org/jabref/gui/importer/fetcher/IEEEXploreFetcher.java
See #2789.
> JabRef version 4.0.0-beta on Windows 10
>Steps to reproduce:
>Perform a web search using the "IEEEXplore" fetcher
>result is always "Invalid search term"
Please check if this works for you.
=> Fixes #2789 Add Referer to API call

src/main/java/org/jabref/gui/groups/GroupTree.fxml
should be a quick fix for #2803. I'm not sure if there are side-effects, so please have a quick look @tobiasdiez
=> Removed maximal width of the numberColumn in the groups view

config/checkstyle/checkstyle.xml
This readds the checkstyle "WhitespaceAround" rule. This rule is important to have the code consistently formatted. --> `if (thing) {` instead of `if(thing){`
I disabled the `RCULRY` brace rule, because @tobiasdiez had issues with it, because of following code:
```
// Create a trust manager that does not validate certificate chains
TrustManager[] trustAllCerts = {new X509TrustManager() {
@Override
public void checkClientTrusted(X509Certificate[] chain, String authType) {
}
...
}};
```
(https://github.com/JabRef/jabref/pull/2798/commits/21f69630a6b0432cd83073e48295cd39cb4059d0)
=> Readd WhitespaceAround rule

build.gradle
to avoid having duplicate libs in gradle and maven
Background story is: I have a big project which still uses maven and JabRef uses gradle. Previously libraries would be downloaded also if they already existed in a local repo. This avoids unnecessary space consumption. If no local libs are found, they are of course downloaded
=> Add Local Maven repo as first lookup resource

CHANGELOG.md, src/main/java/org/jabref/model/pdf/FileAnnotation.java, src/test/java/org/jabref/model/pdf/FileAnnotationTest.java
=> Relaxed the regex to also match negative timezone formats when parsing pdf annotation dates

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fetcher/AstrophysicsDataSystem.java
This moves the `adsurl` field to the `url` field. The current ADS fetcher removes the field `adsurl`. The `adsurl` field is the only url given by the ADS database to *all* entry in the database. I think it is better to keep the url information rather than deleting it. It is more profitable when considering the copy command 'Edit - Copy BibTex key and link.'
=> Adsurl to url

CHANGELOG.md, src/main/java/org/jabref/logic/msbib/MSBibEntry.java, src/main/java/org/jabref/model/entry/Date.java, src/test/java/org/jabref/model/entry/DateTest.java, src/test/resources/org/jabref/logic/exporter/MsBibExportFormatTest1.xml, src/test/resources/org/jabref/logic/exporter/MsBibExportFormatTestDateAcessed.bib, src/test/resources/org/jabref/logic/exporter/MsBibExportFormatTestDateAcessed.xml
Fix possible NPE in Date parsing
Fixes #2859 
=> Fix export and import of MS office day/year/month acessed fields

CHANGELOG.md, src/main/java/org/jabref/gui/groups/DroppingMouseLocation.java, src/main/java/org/jabref/gui/groups/GroupNodeViewModel.java, src/main/java/org/jabref/gui/groups/GroupTree.css, src/main/java/org/jabref/gui/groups/GroupTreeController.java, src/main/java/org/jabref/gui/util/RecursiveTreeItem.java, src/main/java/org/jabref/model/util/TreeCollector.java, src/test/java/org/jabref/gui/groups/GroupNodeViewModelTest.java, src/test/java/org/jabref/model/TreeNodeTest.java
With this PR it is now possible to resort groups using drag and drop.
When the user drags a group over the center of another one, then the target group is highlighted as follows
and the source group is added as a child. 
In contrast, when the user hovers over the bottom or top part of a group, then a line is added that indicates that the source group is added at this point (i.e. between Test 1 and Test 2 in this picture)
There are still some problems with the selection status after a drag and drop.
=> Implement #2785: resort groups using drag & drop

src/main/java/org/jabref/gui/entryeditor/EntryEditorTab.java
Internal thing, it could happen that when the fields array is empty the rows variable is zero which led to an Arithmetic Exception (divide by zero)
=> Fix Divide by zero exception if rows is zero in Entry Editor Tab

src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/entryeditor/EntryEditorTab.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.fxml, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java
Fixes #2843 and #2851.
This was a tricky bug: JavaFX creates empty dummy cells at the end of a list view. For some reason the list view for the linked files had an initial size of `1.7976931348623157E308` and, well, creating that many dummy cells takes a while (probably longer than the universe took to create humans) and eventually lead to a freeze of the JavaFX thread.
The fix was easy, just add `maxHeight="100"` and be happy (finally, after trying to debug the problem for ages).
=> Fix entry editor

build.gradle
Two months ago Codecov stopped working. I have identified the problem being the failing fetcher tests.
By removing these from the jacoco test suite, the reports are generated again solving the issue.
=> Fixes jacoco by excluding the fetcher tests from analysis

src/main/java/org/jabref/gui/DefaultInjector.java
The else part tried to instantiate the interface otherwise
Fix for #2881
=> Fix loading of preferencesService

src/test/java/org/jabref/logic/importer/fetcher/AstrophysicsDataSystemTest.java, src/test/java/org/jabref/logic/importer/fetcher/DBLPFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/MathSciNetTest.java
#2890
Internal change only, some adjusted tests
=> Adjust tests: Ads fetcher returns url, DBLP no longer works with negative operators

CHANGELOG.md, src/main/java/org/jabref/model/entry/identifier/DOI.java, src/test/java/org/jabref/logic/layout/format/DOICheckTest.java, src/test/java/org/jabref/model/entry/identifier/DOITest.java
I think this is an important issue with small code change.  @JabRef/developers  Should we do a fix for 3.8,2?
For 3.8.2 https://github.com/JabRef/jabref/blob/v3.8.2/src/main/java/net/sf/jabref/logic/util/DOI.java
~~- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org]~~(https://github.com/JabRef/help.jabref.org/issues)?)
=> Fix DOI resolving by using https

CHANGELOG.md, src/main/java/org/jabref/logic/pdf/FileAnnotationCache.java
=> Fix exception when no citekey is present

src/main/java/org/jabref/JabRefExecutorService.java, src/main/java/org/jabref/gui/journals/AbbreviateAction.java
Made changes in the AbbreviateAction class to abbreviate journal names in parallel by splitting up the work among threads.
=> Abbreviate journal names in parallel

src/main/java/org/jabref/gui/IconTheme.java, src/main/java/org/jabref/gui/groups/GroupDialog.java, src/main/java/org/jabref/gui/groups/GroupNodeViewModel.java, src/main/java/org/jabref/gui/groups/GroupTreeController.java, src/main/java/org/jabref/gui/util/ViewModelTreeTableCellFactory.java, src/main/java/org/jabref/logic/exporter/GroupSerializer.java, src/main/java/org/jabref/logic/groups/DefaultGroupsFactory.java, src/main/java/org/jabref/logic/importer/util/GroupsParser.java, src/main/java/org/jabref/model/groups/AbstractGroup.java, src/main/java/org/jabref/model/groups/ExplicitGroup.java, src/test/java/org/jabref/logic/exporter/GroupSerializerTest.java, src/test/java/org/jabref/logic/importer/util/GroupsParserTest.java
Parse enum icon value from icon field by name (and apply to uppercase)
Only minor caveat: When you edit a group, you see only a unicode-box and not the name)
No valid icon: (the illegal is just a simple string)
Valid icon name: `facebook`
Icon Enum based on Material Design Icons v1.7.22
=> Better icon support for groups

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/RelatedArticlesTab.java, src/main/java/org/jabref/gui/util/HyperLinkListener.java, src/main/java/org/jabref/gui/util/OpenHyperlinksInExternalBrowser.java
Added a generic HyperLinkListener which opens any hyperlink in a new browser window.
By defeault javafx opens all urls in the same webview window
Fix #2931 
=> Open Urls for recommneded Articles in the browser

src/main/java/org/jabref/gui/entryeditor/EntryEditor.java
Related to the new entry editor
We need to consume the key events on the jfx panel to stop propagation back to the Main Frame.
Fix for #2855 and the other lkeybindings (CTRL + C, CTR+X )
=> Fix propagation of key events back to the Jabref main frame

src/main/java/org/jabref/logic/bibtexkeypattern/BibtexKeyPatternUtil.java, src/test/java/org/jabref/logic/bibtexkeypattern/BibtexKeyPatternUtilTest.java
This PR adds a new special field marker for BibTeX key generator [pageprefix]. It returns the non-digit prefix of `pages` (like "L" of L7) or "" if no non-digit prefix is found in `pages`. Some journals use non-digit letters for their pages, e.g. http://iopscience.iop.org/journal/2041-8205. (I have run `gradlew check` and there was no problem.)
=> Page prefix

src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/keyboard/KeyBinding.java
This PR adds a shortcut key <kbd>Alt</kbd> + <kbd>F7</kbd>  to the function "Quality"-"Look up full text documents". I've found that a issue was already raised in #1323 after finishing the code revision (hence, I happened to use the modifier <kbd>Alt</kbd> rather than <kbd>Ctrl</kbd> :-) )
=> Add a shortcut to "Quality - Look up full text documents"

CHANGELOG.md, src/main/java/org/jabref/gui/actions/CopyBibTeXKeyAndLinkAction.java
This PR fixes the function "Edit - Copy BibTeX key and link"  to pass a hyperlink rather than an HTML statement. A copied hyperlink is more useful than an HTML statement in practice, like when writing emails. This is related with [#549](https://github.com/JabRef/jabref/issues/549).
=> Fix the function "Edit - Copy BibTeX key and link" 

src/test/java/org/jabref/gui/journals/ManageJournalAbbreviationsViewModelTest.java, src/test/java/org/jabref/logic/citationstyle/CitationStyleTest.java, src/test/java/org/jabref/logic/formatter/bibtexfields/NormalizeNamesFormatterTest.java, src/test/java/org/jabref/logic/importer/fileformat/BiblioscapeImporterTest.java, src/test/java/org/jabref/logic/importer/fileformat/IsiImporterTest.java, src/test/java/org/jabref/logic/importer/fileformat/RISImporterTest.java, src/test/java/org/jabref/logic/util/DevelopmentStageTest.java, src/test/java/org/jabref/model/database/BibDatabaseTest.java, src/test/java/org/jabref/model/database/DuplicationCheckerTest.java
This is only an internal change, no functionality was actually changed. I thought it would be good to open a PR anyways to raise awareness.
=> In JUnit tests, always state the expected value before the actual

src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/keyboard/KeyBinding.java, src/main/java/org/jabref/gui/keyboard/KeyBindingRepository.java, src/main/java/org/jabref/gui/keyboard/KeyBindingViewModel.java, src/test/java/org/jabref/gui/keyboard/KeyBindingsDialogViewModelTest.java
Rename Escape to ESC for javafx
Renamed Enum variables as key for the constant was amibiuous
First part of #2949 
Internal change only, from the new entry editor.
Edit// You may need to reset the keybinding for CLOSE_ENTRY_EDITOR in the Manage keybinding dialog, as the old stored value from the prefs no longer works for javafx.
=> Fix closing entry editor with ESC

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java
Fixes #2932
It seems that up to now all group related changes in the UI were not actually stored in the MetaData and lost on save. This PR resets the group-related information in the MetaData whenever something group-related changes.
Hopefully I found all positions where that may happen. If tested it manually, but someone else needs to do this, too!
It also seems that IntelliJ decided to remove trailing whitespaces in the Changelog when I added my entry...
=> Fix group storage

CHANGELOG.md, src/main/java/org/jabref/logic/l10n/Languages.java, src/test/java/org/jabref/logic/l10n/LanguagesTest.java
Fix regression bug #1182
Pass language and country as separate args for Locale constructor
=> Fix Brazilian Portugese language loading

src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java, src/main/java/org/jabref/model/entry/BibEntry.java, src/main/java/org/jabref/model/entry/CanonicalBibtexEntry.java, src/test/java/org/jabref/logic/importer/fileformat/BibtexParserTest.java, src/test/resources/org/jabref/logic/importer/fileformat/MedlinePlainImporterStringOutOfBounds.bib, src/test/resources/org/jabref/logic/importer/fileformat/RepecNepImporterTest2.bib, src/test/resources/org/jabref/logic/importer/fileformat/RepecNepImporterTest3.bib, src/test/resources/org/jabref/logic/importer/fileformat/RisImporterTestScopus.bib
The MathSciNet fetcher appended a "pre" html tag in front of the entry.
This is only a small change that I deem not to be important enough for a changelog entry.
Will merge as soon as tests pass.
=> Remove <pre> tag from entries fetched using MathSciNet

src/main/java/org/jabref/gui/FXDialogService.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditorViewModel.java
=> Add Remove link context menu entry in file editor

config/checkstyle/checkstyle.xml, src/main/java/org/jabref/Globals.java, src/main/java/org/jabref/gui/ClipBoardManager.java, src/main/java/org/jabref/gui/DefaultInjector.java, src/main/java/org/jabref/gui/EntryTypeDialog.java, src/main/java/org/jabref/gui/TransferableBibtexEntry.java, src/main/java/org/jabref/gui/entryeditor/FieldsEditorTab.java, src/main/java/org/jabref/gui/entryeditor/RelatedArticlesTab.java, src/main/java/org/jabref/gui/externalfiles/FindFullTextAction.java, src/main/java/org/jabref/gui/fieldeditors/contextmenu/ProtectedTermsMenu.java, src/main/java/org/jabref/gui/help/AboutDialogViewModel.java, src/main/java/org/jabref/gui/help/HelpAction.java, src/main/java/org/jabref/gui/preftabs/AppearancePrefsTab.java, src/main/java/org/jabref/gui/preftabs/FontSelectorDialog.java, src/main/java/org/jabref/logic/exporter/FileSaveSession.java, src/main/java/org/jabref/logic/importer/fetcher/DoiFetcher.java, src/main/java/org/jabref/logic/msbib/MSBibMapping.java, src/main/java/org/jabref/logic/protectedterms/ProtectedTermsLoader.java, src/main/java/org/jabref/logic/util/io/FileUtil.java, src/main/java/org/jabref/model/entry/AuthorList.java, src/main/java/org/jabref/model/entry/FieldName.java, src/main/java/org/jabref/model/entry/IdGenerator.java
To adhere the Java Code Conventions I have added another CheckStyle check to make sure that all `static final` variables are in CAPS. For some reason Checkstyle suggests to exclude the logger, which I am unsure if we really need it. Check the following regex for the exact specification:
```
"^log(ger)?|[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$"
```
I have already fixed the instances where this rule was violated.
=> Add CheckStyle Check for Constants (final static)

CHANGELOG.md, src/main/java/org/jabref/logic/bibtex/DuplicateCheck.java, src/test/java/org/jabref/logic/bibtex/DuplicateCheckTest.java
Fixes #2960 by checking for different editions before the actual duplicate check.
If both BibEntries have a Edition field that mismatches, it cannot be a duplicate.
=> Check for different editions in the duplicate check

src/main/java/org/jabref/logic/autosaveandbackup/BackupManager.java, src/main/java/org/jabref/model/entry/event/FieldChangedEvent.java
Addresses #2993
The frequent events are due to the bidirectional binding which transfers every change directly into the BibEntry. If we want fewer events, the only solution will probably be to break the binding, which would be very disappointing for the JavaFX implementation. In my point of view the problem is not on the side of event creation. After all, every change should trigger an event and JavaFX triggers many changes. Imho, this should be fixed in how we react to events.
I also noticed the exception, but do not get a dialog. This seems to happen because of the save operation invoked by the backup.
A solution might be to do less backups, by:
1. Doing backups only every X events and not for every event
2. Ignoring FieldChangeEvents in the Backup
3. Adding the size of the field change …
=> Less backups

src/main/java/org/jabref/gui/keyboard/KeyBindingRepository.java, src/test/java/org/jabref/gui/keyboard/KeyBindingsDialogViewModelTest.java
This should make the entry editor commands work again with Command+X /C etc
@chochreiner  Could you please test if that works now? Copy/Cut/Paste in the entry editor with Command key instead of control key.
Unfortunately I could not add a unit test, because the OS is a static class with final vars.
=> Fix mac keybinding by replacing ctrl it with meta key

src/main/java/org/jabref/logic/autosaveandbackup/BackupManager.java
This PR makes the BackupManager a little more intelligent. It fixes a bug that I've only noticed locally and discussed with @tobiasdiez in chat. There's no issue for it, but the fix comes directly here.
If you have save actions configured (say LatexToUnicode) and the backup triggers too early (say after 5 characters) then the BackupManager interrupts you if you add a longer command in the entry edior (say `\alpha`). With this PR, the BackupManager is no longer triggered every five characters, but only if there are changes of more than one character (a user pastes text into the entry editor) or if the user edits a different field than before. This seems way more reasonable to me and is as it has been before (only backups when a user changes the field, edits a group, etc.)
=> Only do a back up for bigger changes or if a different field is edited

build.gradle
Upon wish of @lenhard, nothing more to say here
=> Don't abort build when there are checkstyle violations

src/main/java/org/jabref/collab/FileUpdateMonitor.java, src/main/java/org/jabref/logic/journals/AbbreviationParser.java, src/main/java/org/jabref/logic/journals/JournalAbbreviationRepository.java, src/test/java/org/jabref/gui/journals/ManageJournalAbbreviationsViewModelTest.java, src/test/java/org/jabref/logic/journals/JournalAbbreviationRepositoryTest.java
This PR improves the performance of the journal abbreviation loader/repository/parser and thus is a partial fix for https://github.com/JabRef/jabref/issues/2966.
Previously, loading and parsing the journal repository files took nearly 10 seconds and now almost nothing:
Main boost came from using `equalsIgnoreCase` instead of using `equals(text.toLowerCase())` and changing `LinkedList` to `HashSet` as we don't care about the ordering.
I had to adopt two tests which relied on the sorting.
Moreover, only one copy of the list is now stored in memory opposed to the 1 + 4 maps previously (equates to 1/10 RAM consummation). In principle, this makes the journal auto completion slower but I couldn't notice any negative impact.
=> Improve performance of journal abbreviation loader

CHANGELOG.md, src/main/java/org/jabref/gui/BasePanel.java, src/main/java/org/jabref/gui/entryeditor/EntryEditor.java
This PR aims to solve a issue which was reported frequently (https://github.com/JabRef/jabref/issues/2675, https://github.com/JabRef/jabref/issues/2984, https://github.com/JabRef/jabref/issues/2896)
The solution I propose is to pass an argument with the name of the tab to be shown when instantiating a new EntryEditor.
=> When browsing through the MainTable remember which EntryEditor tab was open

build.gradle
This is an followup for https://github.com/JabRef/jabref/pull/3006.
I thought about it and maybe it's a good idea to run `checkstyle` after `test` and don't allow failures as suggested in #3006.
The alternative would be to show the checkstyle warnings, then execute the tests, and let the build fail afterwards. However, I couldn't find a nice way to achieve this.
What are your thoughts?
=> Run Checkstyle task after Test task

src/main/java/org/jabref/JabRefMain.java, src/main/java/org/jabref/migrations/PreferencesMigrations.java, src/main/java/org/jabref/preferences/JabRefPreferences.java
=> Add preference migration for keybdingings

build.gradle
This is to reduce the mass of transitive dependencies fetched by using corda.net. See https://github.com/JabRef/jabref/issues/3014.
=> Minimize depdencies fetched by using net.corda:jfx

build.gradle, external-libraries.txt, src/main/java/org/jabref/Globals.java, src/main/java/org/jabref/architecture/ApacheCommonsLang3Allowed.java, src/main/java/org/jabref/cli/ArgumentProcessor.java, src/main/java/org/jabref/gui/errorconsole/LogEventViewModel.java, src/main/java/org/jabref/gui/groups/GroupNodeViewModel.java, src/main/java/org/jabref/gui/preftabs/PreviewPrefsTab.java, src/main/java/org/jabref/logic/formatter/bibtexfields/HtmlToUnicodeFormatter.java, src/main/java/org/jabref/logic/integrity/IntegrityMessage.java, src/main/java/org/jabref/model/strings/StringUtil.java, src/main/resources/log4j2.xml, src/test/java/org/jabref/CodeStyleTests.java, src/test/java/org/jabref/architecture/MainArchitectureTests.java, src/test/java/org/jabref/architecture/MainArchitectureTestsWithArchUnit.java, src/test/java/org/jabref/architecture/TestArchitectureTests.java
We don't have an [Architectural Decision Record](https://adr.github.io/) why we included Apache Commons Lang. We introduced the dependency within https://github.com/JabRef/jabref/pull/1572.
I don't know, why Apache Commons Lang3 was chosen. The [current opinion](https://stackoverflow.com/a/4543114/873282) is that Guava is more modern and that new projects should use Google Guava instead of Apache Commons Lang3.
Should we replace Apache Commons Lang3 or should we just keep it, because it is not that huge and we have other class issues (see https://github.com/JabRef/jabref/issues/3014).
Refs https://github.com/JabRef/jabref/issues/2966#issuecomment-314369222
- I replaced most places where we use Apache Commons Lang3 and there is a Google Guava equivalent
- We have some places, where there …
=> Google Guava over Apache Commons Lang3

build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/java/org/jabref/gui/exporter/SaveDatabaseAction.java
Fixed the following issue: 
https://github.com/zacmks/jabref/issues/1
Also, update the maven repo, with secure http
=> Can't Save a Database to a new File

src/main/java/org/jabref/preferences/JabRefPreferences.java
Check below https://github.com/JabRef/jabref/pull/3008#issuecomment-315136683
> 
> Default Arial has only 3988 glyphs (cf. https://en.wikipedia.org/wiki/Unicode_font#List_of_Unicode_fonts), where italics don't seem to be supported.
> 
> To fix the issue at hand I would propose to change the font to GNU Unifont](https://en.wikipedia.org/wiki/GNU_Unifont) which supports 63,449 glyphs.
> 
> License-wise there shouldn't be any issues:
> 
> > The software on this site, unless otherwise noted, is released under the terms of the GNU General Public License (GNU GPL) version 2.0, or (at your option) a later version. The precompiled fonts are released under the terms of the GNU GPL version 2, or (at your option) a later version, with the exception that embedding the font in a document does not in …
=> Don't enforce default Windows font

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/entryeditor/SourceTab.java
Attempts to fix the remaining part of #2888. The source tab is now updated each time an entry is changed in the editor.
There no part of a BibEntry that represents the source tab per se to which we could bind. Therefore, this PR adds a listener to the source tab. It now listens to `EntryChangedEvents` and if the entry that it represents is changed, then it updates its content.
=> Update source tab when an entry is changed

build.gradle, external-libraries.txt, src/main/java/org/jabref/gui/util/BindingsHelper.java, src/main/java/org/jabref/gui/util/MappedList.java
Fixes https://github.com/JabRef/jabref/issues/3014.
I have mainly used this gist as an idea https://gist.github.com/TomasMikula/8883719, the alternative would have been https://gist.github.com/mikehearn/a2e4a048a996fd900656
=> Replace Reimplement MappedList.kt

src/main/java/org/jabref/gui/keyboard/KeyBindingRepository.java
Check keycode to avoid localization problems
Follow up from #2853
=> Fix keybinding in entry editor in localized installation

docs/adr/0000-use-architectural-decision-records.md, docs/adr/index.md, docs/adr/template.md
I'd like to improve the code documentation of JabRef to make is easier for newcomers to understand the code. One part of that is to document the ideas behind of some code. This PR adds an initial directory and template for that.
I tried to collect background information at http://adr.github.io/.
=> Initial idea for architectural decision records

src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/keyboard/KeyBinding.java
=> Fix navigation in entry editor increases modifies font size

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fetcher/AstrophysicsDataSystem.java
=> Fix ads fetcher

CHANGELOG.md, src/main/java/org/jabref/gui/BasePanel.java
This fixes #3036 
I debugged a bit and found that this was a threading problem. When assiging an entry to a group, the markBaseChanged was executed in the JavaFX Thread and not in the Swing thread.
=> Fix group freeze by running markBasechange in swing thread

src/main/java/org/jabref/Globals.java, src/main/java/org/jabref/gui/BasePanel.java, src/main/java/org/jabref/gui/importer/actions/OpenDatabaseAction.java, src/main/java/org/jabref/logic/citationstyle/CitationStyle.java, src/main/java/org/jabref/logic/importer/fetcher/MrDLibFetcher.java, src/main/java/org/jabref/model/groups/WordKeywordGroup.java
Some few issues, mostly some issues with equal:
https://spotbugs.github.io/
=> Fix some spotbugs issues

CHANGELOG.md, src/main/java/org/jabref/gui/util/FileDialogConfiguration.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/test/java/org/jabref/gui/util/FileDialogConfigurationTest.java
Set default Prefs to USER_HOME instead of working dir which could not have been intialized
Fix for #3064 
A rare case: When you did not restart JabRef after resetting the prefs, but directly imported them, the EXPORT_Path pref returned the key for WORKING_DIRECTORY - and in that case, the String "workingDirectory" which is a non existing directory and led to an NPE in File exists
=> Fix importing preferences after resetting without restarting

src/main/java/org/jabref/gui/util/MappedList.java
This is the followup for https://github.com/JabRef/jabref/pull/3032#discussion_r129271280.
This is different from https://github.com/JabRef/jabref/pull/3032, as now the mapping only happens on insert.
=> Reimplement MappedList using a backigList

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java
Swing GUI was called from FXApplication Thread which lead to a freeze.
Has to be called in Swing Thread. 
Fixes https://github.com/JabRef/jabref/issues/2930#issuecomment-311050976
=> Fix freezing when editing assigned file in General Tab

src/main/java/org/jabref/Globals.java, src/main/java/org/jabref/gui/JabRefDialog.java, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/logging/ApplicationInsightsAppender.java
Up to now, the telemetry service was always running (even if the reporting was turned of).
This initialization already requires a lot of time during startup, which is already rather long on MacOS
I hope I have caught all usages of the telemetry client to avoid nullpointer exceptions, but i would be great if @lynyus could have a look at it.
=> Only load the telementry service as a background task if used

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/entryeditor/SourceTab.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java, src/main/java/org/jabref/gui/groups/GroupTreeController.java, src/main/java/org/jabref/preferences/JabRefPreferences.java
This fix for #3034 is inspired and based on https://github.com/JabRef/jabref/pull/3042. Due to my limited git knowledge I was not able to directly hijack the other PR; sorry @lenhard.
=> Fix #3034: Make font size in entry editor and group panel customizable

CHANGELOG.md, src/main/java/org/jabref/gui/filelist/AttachFileAction.java, src/main/java/org/jabref/gui/filelist/FileListEntryEditor.java, src/main/java/org/jabref/model/entry/BibEntry.java, src/main/java/org/jabref/model/entry/FileFieldParser.java, src/test/java/org/jabref/model/entry/BibEntryTest.java
Return new ArrayList instead of unmodiefable emptyList()
Fixes #3080
=> Fix attach file action from contextmenu

src/main/java/org/jabref/logic/citationstyle/CitationStyleCache.java
This uses Guava's Cache instead of a HashMap for caching.
This enables us to limit the number of cached entries. The current number 1024 is chosen arbitrarily. Maybe, 100 could be enough.
=> Add Guava Cache to CitationStyleCache

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/entryeditor/SourceTab.java
Fixes #3103 by making sure that updates to the source tab are always performed on the FXApplication Thread.
=> Source tab doi

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupSidePane.java
Attempts to fix #1903
Makes the maintable update whenever grouping changes and not just when group selection changes.
=> Trigger group display update when grouping changes

CHANGELOG.md, src/main/java/org/jabref/gui/actions/IntegrityCheckAction.java, src/main/resources/l10n/JabRef_da.properties, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_el.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fa.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_in.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_nl.properties, src/main/resources/l10n/JabRef_no.properties, src/main/resources/l10n/JabRef_pt_BR.properties, src/main/resources/l10n/JabRef_ru.properties, src/main/resources/l10n/JabRef_sv.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_vi.properties, src/main/resources/l10n/JabRef_zh.properties
Fixes #2718 
I added new 'Filter All' and 'Filter None' buttons.  They can be clicked by the user to
check/uncheck all options in the filter menu.  When one of the buttons gets clicked the system will iterate through the existing menu components and toggle the checkmarks and info displayed.
I wasnt sure on the best placement of the buttons in the window so went with the simplest solution
Updated localization info with text for aforementioned buttons.
=> Additional filter functionality for Check Integrity popup

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/FileListEditorTransferHandler.java
This fixes https://github.com/koppor/jabref/issues/245. The issue was caused during a code cleanup at https://github.com/JabRef/jabref/pull/2723: https://github.com/JabRef/jabref/pull/2723/files#diff-093fbc56554f6c75313823ee81f28ec6L152
=> Files can be dropped to entry preview panel to attach a file again.

src/main/java/org/jabref/logic/util/strings/HTMLUnicodeConversionMaps.java
Having `\%` in some of the fields, it was displayed as `&percnt;` in the entry preview. For some reason the HTML display was not able to correctly handle this HTML code (probably because it uses [IE's rendering](https://stackoverflow.com/questions/7638338/percnt-not-recognized-by-ie/7638363#7638363)).
This issue was reported at https://github.com/JabRef/jabref/issues/3148#issuecomment-324294303.
=> Fix display of percentage symbol in entry preview

CHANGELOG.md, src/main/java/org/jabref/gui/BasePanel.java, src/main/java/org/jabref/gui/entryeditor/EntryEditor.java
Fixes the remaining part of #2946
When you externally delete an entry that is opened in the entry editor and accept the change in the dialog in JabRef, then the entry editor closes. That way, it prevents you from editing an entry that does no longer exist.
As a side note: The `BasePanel` is ripe for a refactoring. There are a good dozen classes that I could extract. In the light of only doing bug fixes before the 4.0 release, I'll avoid that now. But when we've released, this class gets it...
=> Close entry editor when the shown entry is removed externally

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/contextmenu/ProtectedTermsMenu.java, src/main/java/org/jabref/gui/protectedterms/NewProtectedTermsFileDialog.java
when adding from entrry editor
changed open file dialog to save file dialog
Fix #3157
=> Fix freezing on browse in protected terms dialog 

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/EditorValidator.java, src/main/java/org/jabref/gui/fieldeditors/FieldEditors.java, src/main/java/org/jabref/gui/fieldeditors/IdentifierEditor.java, src/main/java/org/jabref/gui/fieldeditors/JournalEditor.java, src/main/java/org/jabref/gui/fieldeditors/OwnerEditor.java, src/main/java/org/jabref/gui/fieldeditors/PersonsEditor.java, src/main/java/org/jabref/gui/fieldeditors/SimpleEditor.java, src/main/java/org/jabref/gui/fieldeditors/UrlEditor.java, src/main/java/org/jabref/preferences/JabRefPreferences.java
Adds a preference option for enabling/disabling validation in the entry editor: #3100 (but not the UI)
The reason is because the validation is simply broken at the moment #3145
The preference option is set to false by default and there is no UI to change it. So this turns off validation in the entry editor. We can add the UI to turn it on later, when the display bug in controlsfx has been fixed.
When this is merged, the related issues can be removed from the 4.0 milestone.
=> Add preference to disable validation in the entry editor by default

CHANGELOG.md, src/main/java/org/jabref/model/pdf/FileAnnotation.java, src/test/java/org/jabref/model/pdf/FileAnnotationTest.java
This should be the last aspect for being able to close #3130. @HViethen85 should consider using another PDF Annotation tool (; However, the fault is of course on our side since we didn't validate the date format before.
=> Fix unparseable FileAnnotation dates

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/contextmenu/ProtectedTermsMenu.java
Fixes  #3161
The result of the dialog needs to be evaluated *after* the dialog is actually finished and the update of the context menu needs to be called.
=> Update protected terms list in context menu when a new list is added.

src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/entryeditor/SourceTab.java
Fixes #3170 The problem here, as far as I understand, was that the undo didn't happen on the FXApplication thread.
On top of that, I found the the source tab isn't integrated in the undo framework at all, so I have added this as well. However, it doesn't work problem-free. It seems that the FX CodeArea consumes undo events as well. So when you hit undo in the sourcetab, the CodeArea does the undo and then the UndoManager tries to do it again and fails. It has no consequence, though, apart from an exception, the undo happens anyway.
Since this is an improvement (add undo to source tab again), I would like to merge this even if it's not perfect. I have zero time to dig deeper into these FX problems, and I assume that no one else will do it. So, we can just merge the current state.
=> Add undo functionality to the source tab

scripts/syncLang.py
To allow for a more direct edit of the localization files.
Please, triple check, I am in no way a python programmer.
=> syncLang.py: link in markdown output

CHANGELOG.md, src/main/java/org/jabref/gui/search/GlobalSearchBar.java
Fix #3081 
Arrow keys (left, right, up and down no work as expected and the up/down + Enter can be used to select an entry from the autocomplete menu)
=> Fix focus and keybinding in search

src/test/java/org/jabref/logic/importer/fetcher/DoiResolutionTest.java
DOI URL changed to https, was http.
Minor change
Updated URL 
- Goto https://www.doi.org/ 
- search for 10.1051/0004-6361/201527330
- be redirected to http**s**://www.aanda.org/articles/aa/abs/2016/01/aa27330-15/aa27330-15.html
=> update link from http to https

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditorViewModel.java
Implements https://github.com/koppor/jabref/issues/244
=> Add drag and drop support for files in General Tab

CHANGELOG.md, src/main/java/org/jabref/model/entry/AuthorListParser.java, src/test/java/org/jabref/model/entry/AuthorListTest.java
I missed JabRef so much, that I even dared to touch the name parsing algorithm.  
The only real changed consists in the few added lines https://github.com/JabRef/jabref/compare/fix3142?expand=1#diff-b8249d741d31352dd2bcafcab07d9457R147, the rest is only code formatting/renaming of variables. The added tests come from [biblatex](https://github.com/plk/biber/blob/f418da9b1975847461fad884fedf910aed73c13b/t/names.t).
=> Fix #2775: Hyphens in last names are properly parsed

src/main/java/org/jabref/FallbackExceptionHandler.java, src/main/java/org/jabref/gui/actions/NewEntryAction.java, src/main/java/org/jabref/gui/logging/ApplicationInsightsAppender.java
For some reason, some unhandled exceptions are report multiple (meaning in the thousands) times in the Azure telemetry. Thus we regularly hit the daily cap and I get an annoying email. I tried to investigate, but couldn't reproduce the behavior and thus I'm not sure that these changes actually fix the problem. The only difference between logging in the FallbackExceptionHandler to other loggings of errors was the direct usage of `log4j` instead of the usual `LogFactory` approach. Thus I changed it to the later and hope for the best.
While touching the telemetry, I also added logging of the creation of new entries and the created entry type. This information might serve as a guide for a forthcoming improvement of the "New entry..." dialog (with sensible defaults and/or completely different …
=> Improve telemetry

src/test/java/org/jabref/gui/importer/fetcher/OAI2HandlerFetcherTest.java
FieldName is "comment" not "comments".
Removing "s" fixes the assertion failure
- [] Manually tested changed features in running JabRef
=> [minor change] Fix assertion by removing typo

src/main/java/org/jabref/gui/entryeditor/EntryEditor.css
Right now the odd rows in the file list have a slightly darker background. This makes sens for bigger lists as the eye can follow the row more easily. However, it is just disturbing for our case of 2-3 files.
=> Don't highlight odd rows in file list editor

src/main/java/org/jabref/gui/externalfiles/AutoSetLinks.java, src/main/java/org/jabref/pdfimport/PdfImporter.java
The autolink feature added the file name also as a description to the newly added linked file. This resulted in a strange display of the linked file in the entry editor as the file name is shown twice (once as description and once as the name of the file).
=> Don't add file name as description

CHANGELOG.md, src/main/java/org/jabref/gui/autocompleter/PersonNameStringConverter.java, src/main/java/org/jabref/gui/search/GlobalSearchBar.java
Now only the last name of the author is added (and shown as a suggestion) to the search bar. Previously it was in the format "Last, F.". Thus authors specified as "Last, First" were not found correctly because of the "dot".
Fixes https://github.com/koppor/jabref/issues/253.
=> Use only last name for auto completion in search bar

CHANGELOG.md, src/main/java/org/jabref/logic/cleanup/RenamePdfCleanup.java
This patch fixes the issue described in #3230. The link to the renamed file is successfully updated now.
=> Update link to renamed file

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefFrame.java
see https://github.com/JabRef/jabref/issues/2955#issuecomment-334591123
To wait before showing the TrackingNotification, a new ScheduledExecutorService was created but never shutdown. Now the daemon Timer of the JabRefExecutorService is used.
=> Wait to ask to collect anonymous statistics in JabRefExecutorService to allow jvm to terminate

src/main/java/org/jabref/gui/JabRefFrame.java
The dialog to ask for collecting anonymous statistics needs to be created in
the Swing EDT. Do so using SwingUtilities.invokeLater().
This is a follow-up on 7ef2b3a and should finally fix #2955.
No addition to CHANGELOG.md as 7ef2b3a already included a corresponding entry.
=> Open statistics dialog from correct thread

CHANGELOG.md, src/main/java/org/jabref/JabRefMain.java
Fix for Issue #3247
When JabRef was run with the '-n' parameter, i.e. the "No GUI" option, like:
`java -jar JabRef.jar -n`
or any other reason for `ArgumentProcessor#shouldShutDown()` returning `true` took place, the application should shut down after performing custom export filters etc. However, `Platform.exit()` wasn't called, so the JavaFX thread kept running indefinitely. Simply added this call to resolve the problem.
=> Terminate JavaFX thread when running with "nogui" option

CHANGELOG.md, src/main/java/org/jabref/gui/GUIGlobals.java
WM_CLASS is used by certain Un*x window managers, such as GNOME, to map windows
to the corresponding application. Currently WM_CLASS is set to java-lang-Thread
which is very generic and not unique to JabRef. Instead, use reflection to set
it to org-jabref-JabRefMain which resembles the main class name.
The implementation in this PR is based on this blog post:
http://elliotth.blogspot.de/2007/02/fixing-wmclass-for-your-java.html
By now you find similar solutions in several Java applications. I'm not aware of a more convenient way to manually set WM_CLASS.
I tested the change on a Linux system running GNOME 3 and also on macOS to rule out any cross-platform issues. Also I chose the WM_CLASS name that matches the StartupWMClass in [buildres/snapcraft/jabref.desktop](../blob/master/buildres/sn …
=> Set WM_CLASS to org-jabref-JabRefMain

src/main/java/org/jabref/gui/entryeditor/fileannotationtab/FileAnnotationViewModel.java
Resolves #3280
@JabRef/developers Any votes against this? @lynyus
=> Empty String instead of N/A in file annotations

CHANGELOG.md, src/main/java/org/jabref/logic/openoffice/OpenOfficePreferences.java
=> Change OO paths to Libre Office in preferences

CHANGELOG.md, src/main/java/org/jabref/shared/DBMSProcessor.java
Fix for https://github.com/JabRef/jabref/issues/3235. Instead of completely deleting and refiling the metadata table, now an `update` is preformed. I've never touched the SQL code before and didn't tested it, so I appreciate feedback from someone with more experience on this part of the code.
=> Fix #3235: remote metadata is updated instead of delete + insert

src/main/java/org/jabref/gui/importer/ImportFileFilter.java, src/main/java/org/jabref/gui/importer/ImportFormats.java
=> File open dialog should have "supported formates" file type

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/EntryEditor.java
Fixes #3294  Digging down in the log file I found that the problem is that the sourceTab.update is not executed in the FXThread. This could also be
=> Fix exception/freezing on EntryChangedEvent in Entry Editor

CHANGELOG.md, src/main/java/org/jabref/logic/util/strings/HTMLUnicodeConversionMaps.java
Fixes #3307 by adding \textendash to the html conversion table
=> Add \textendash to the html conversion table

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/entryeditor/FieldsEditorTab.java, src/main/java/org/jabref/gui/fieldeditors/FieldEditors.java, src/main/java/org/jabref/gui/fieldeditors/MultilineEditor.java, src/main/java/org/jabref/model/entry/BibtexSingleField.java, src/main/java/org/jabref/model/entry/FieldProperty.java, src/main/java/org/jabref/model/entry/InternalBibtexFields.java
Someone had the abstract field in the "required" tab. Since all fields were treated the same way, the abstract field was as big as the other fields resulting in a inconvenient display. See http://discourse.jabref.org/t/entry-preview-in-version-4/827/7. With this PR the solution for the keywords field is adopted and the abstract gets a bigger weight.
~~Not yet ready for review, a bit of code cleanup is still coming.~~
=> Increase relative size of abstract field in editor

src/main/java/org/jabref/gui/maintable/MainTable.java
As observed by @stefan-kolb in https://github.com/JabRef/jabref/issues/3275#issuecomment-336180146 the NPE resulted from the strange `matches(null)` code. This is fixed now. Not sure if this actually fixes the problem of #3275.
=> Fix NPE in MainTable

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/FieldsEditorTab.java
This is a very small fix with big implications for performance and memory. The reasoning is simple: Currently, all editor tabs (extending from `FieldsEditorTab`) are initialized when a new entry is selected. So even if the user is only browsing through the entry table with the editor open, on each new BibEntry we create all the tabs for each entry from scratch. This can in the case of `FieldsEditorTab` simply prevented by moving this initialization to `initialize` which is called when the tab gets focus. This PR addresses this issue.
I want to give a detailed analysis because there is much more potential when we slightly rework how the `EntryEditor` and its tabs work. First of all, this is the memory increase when I scroll the 209 entry example `jabref-authors.bib` with the current master …
=> Initializing EntryEditor Tabs on focus

src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/entryeditor/EntryEditorTab.java, src/main/java/org/jabref/gui/entryeditor/FieldsEditorTab.java, src/main/java/org/jabref/gui/entryeditor/MathSciNetTab.java, src/main/java/org/jabref/gui/entryeditor/OptionalFields2Tab.java, src/main/java/org/jabref/gui/entryeditor/OptionalFieldsTab.java, src/main/java/org/jabref/gui/entryeditor/OtherFieldsTab.java, src/main/java/org/jabref/gui/entryeditor/RelatedArticlesTab.java, src/main/java/org/jabref/gui/entryeditor/RequiredFieldsTab.java, src/main/java/org/jabref/gui/entryeditor/SourceTab.java, src/main/java/org/jabref/gui/entryeditor/UserDefinedFieldsTab.java, src/main/java/org/jabref/gui/entryeditor/fileannotationtab/FileAnnotationTab.java
Not to let @halirutan and @lenhard have all the fun, I'll jump onto the "improve-the-entry-editor"-train. So this PR is a natural continuation of https://github.com/JabRef/jabref/pull/3331. 
Changes:
- The entry editor tabs are only initialized once and then later notified about getting the focus or the change of entry.
- The different tabs no longer rely on the JabRefFrame and BasePanel (finally!)
- I removed some commented-out code in the FieldsEditorTab, that was a relic of previous (incomplete) refactorings.
- Disable tab animation.
------
=> Refactoring: Lazy init of all editor tabs

CHANGELOG.md, src/main/java/org/jabref/cli/ArgumentProcessor.java, src/main/java/org/jabref/gui/EntryTypeDialog.java, src/main/java/org/jabref/gui/desktop/JabRefDesktop.java, src/main/java/org/jabref/gui/entryeditor/RelatedArticlesTab.java, src/main/java/org/jabref/gui/preftabs/EntryEditorPrefsTab.java, src/main/java/org/jabref/gui/shared/SharedDatabaseUIManager.java, src/main/java/org/jabref/logic/auxparser/AuxParserResult.java, src/main/java/org/jabref/logic/formatter/bibtexfields/RegexFormatter.java, src/main/java/org/jabref/logic/importer/fetcher/AbstractIsbnFetcher.java, src/main/java/org/jabref/logic/importer/fetcher/DoiFetcher.java, src/main/java/org/jabref/logic/importer/fetcher/MrDLibFetcher.java
I noticed warnings in running JabRef in debug mode regarding translations. Found some places where and underscore was used instead of space.
=> Remove underscore in Localized messages

src/main/java/org/jabref/gui/util/FileUpdateMonitor.java
Fixes #3342, follow up issue from #3325 
Use toAbsolutePath before calling of getParent
=> Fix NPE when calling with bib file as cmd argument

CHANGELOG.md, build.gradle, src/main/java/org/jabref/gui/fieldeditors/EditorTextArea.java, src/main/java/org/jabref/gui/fieldeditors/IdentifierEditor.java, src/main/java/org/jabref/gui/fieldeditors/contextmenu/EditorMenus.java
I believe I could bring down the performance impact of the context menus to a bare minimum. I reported this in https://github.com/JabRef/jabref/issues/3335 and @tobiasdiez provided me with the hint how this could work. Against his suggestion to not overshoot, I decided to prove my point that even those small context menus have a significant impact because things will sum up in the end and those menus are newly instantiated for every visible field in the editor.
The starting point was the current master-branch and profiling it by going through only 50 bib-entries. This means that the context menus are instantiated for the visible text fields. This has an impact on performance and memory and, unfortunately, it is not only a tiny fraction. 
Notable are the columns "Objects", which are all …
=> Used late initialization for context menus

build.gradle
Upgraded error-prone gradle plugin to version 0.0.13 (up from 0.0.11) #hacktoberfest
=> Upgrade error-prone

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/entryeditor/SourceTab.java
Adapts the source tab a little better to the new and no longer re-created entry editor. It is a fix for the problem described in this comment https://github.com/JabRef/jabref/issues/3352#issue-268580818 The remaining problems in the issue are not addressed here, so the issue should stay open when merging this and the update flow in the source tab should be reworked in further PRs.
=> Source tab entry duplication

CHANGELOG.md, src/main/java/org/jabref/gui/FindUnlinkedFilesDialog.java, src/main/java/org/jabref/gui/actions/AutoLinkFilesAction.java, src/main/java/org/jabref/gui/externalfiles/AutoSetLinks.java, src/main/java/org/jabref/gui/externalfiles/SynchronizeFileField.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditorViewModel.java, src/main/java/org/jabref/gui/groups/UndoableModifySubtree.java, src/main/java/org/jabref/gui/importer/ImportInspectionDialog.java, src/main/java/org/jabref/model/search/matchers/MatcherSet.java
=> Refactorings

src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/entryeditor/SourceTab.java, src/main/java/org/jabref/gui/util/BindingsHelper.java, src/main/java/org/jabref/model/entry/BibEntry.java, src/main/resources/l10n/JabRef_da.properties, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_el.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fa.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_in.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_nl.properties, src/main/resources/l10n/JabRef_no.properties, src/main/resources/l10n/JabRef_pt_BR.properties, src/main/resources/l10n/JabRef_ru.properties, src/main/resources/l10n/JabRef_sv.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_vi.properties, src/main/resources/l10n/JabRef_zh.properties
In https://github.com/JabRef/jabref/issues/3352#issuecomment-339910785, @lenhard suggested to update the entry as soon as the source code is changed (instead of only on focus lost). This is accomplished in this PR. 
Jörg mentioned that the most direct solution does not work since
> the store operation will move the cursor to the end of the source tab.
This problem is circumvented by implementing a proper bidirectional binding between the entry and the source code, which prevents update cycles.
Moreover, in case of a parse error, the message is no longer shown in a dialog but inline as a notification:
=> Update entry for every change in the source panel

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fetcher/CrossRef.java
=> Treat CrossRef titles as optional

build.gradle
@lenhard Can you please try if these updates fixes the `IndexOutOfBounds` exception. They fixed an issue that looks very similar https://github.com/FXMisc/RichTextFX/issues/579.
=> Update richtext and flowless

CHANGELOG.md, src/main/java/org/jabref/gui/actions/IntegrityCheckAction.java, src/main/resources/l10n/JabRef_da.properties, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_el.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fa.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_in.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_nl.properties, src/main/resources/l10n/JabRef_no.properties, src/main/resources/l10n/JabRef_pt_BR.properties, src/main/resources/l10n/JabRef_ru.properties, src/main/resources/l10n/JabRef_sv.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_vi.properties, src/main/resources/l10n/JabRef_zh.properties
This change is related to #3358. JabRef looked like it is hanging during long integrity checks. I added a dialog with a progress bar to show that it is working.
=> Added checking integrity dialog

config/IntelliJ Code Style.xml
Add IntelliJ code format rules according to the following checkstyle 
https://github.com/JabRef/jabref/blob/9aa4ac56deafb512860cdfc44cb9c990ce848dc8/config/checkstyle/checkstyle.xml#L32-L33
=> Config intellj code style to adhere to empty lines checkstyle rule

scripts/syncLang.py
=> Improve SyncLang.py

src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/entryeditor/SourceTab.java, src/main/java/org/jabref/gui/util/DefaultTaskExecutor.java
So here is now a real fix of these problems in the source editor (index out of bounds, paste, select all, update,...). The problem was that updates to the editor were not performed on the javafx thread although they were wraped in a `runInJavaFXThread` call. The reason was that this method would actually submit tasks to the executor, which would then start a new thread. So the fix only happens in `DefaultTaskExecutor`, the rest of the changes are minor cosmetic improvements to get rid of globals or base panels in the source tab.
=> Fix problems in source editor

src/main/java/org/jabref/gui/search/SearchDisplayMode.java, src/main/java/org/jabref/logic/l10n/Localization.java, src/main/java/org/jabref/logic/protectedterms/ProtectedTermsLoader.java
I had some problems with not initialized resource bundles (an issue on my side), which lead me to discover a few instances where localized text were accessed statically. Such text would never be translated correctly. Should be fixed with this PR. (I didn't add a changelog entry since it is a really minor fix.)
=> Fix static localized text

CHANGELOG.md, src/main/java/org/jabref/logic/citationstyle/CitationStyle.java
Fixes #3389 by skipping invalid parts of the prolog of citation styles.
=> Strip invalid prolog when loading CitationStyles

CHANGELOG.md, src/main/java/org/jabref/gui/customentrytypes/EntryCustomizationDialog.java, src/main/java/org/jabref/gui/customentrytypes/FieldSetComponent.java, src/main/java/org/jabref/gui/entryeditor/DeprecatedFieldsTab.java, src/main/java/org/jabref/gui/entryeditor/FieldsEditorTab.java, src/main/java/org/jabref/gui/entryeditor/OptionalFields2Tab.java, src/main/java/org/jabref/gui/entryeditor/OptionalFieldsTab.java, src/main/java/org/jabref/gui/entryeditor/OtherFieldsTab.java, src/main/java/org/jabref/gui/entryeditor/RequiredFieldsTab.java, src/main/java/org/jabref/gui/entryeditor/UserDefinedFieldsTab.java, src/main/java/org/jabref/logic/bibtex/BibEntryWriter.java, src/main/java/org/jabref/logic/bibtex/DuplicateCheck.java, src/main/java/org/jabref/model/entry/BibEntry.java, src/main/java/org/jabref/model/entry/BiblatexEntryType.java, src/main/java/org/jabref/model/entry/BiblatexEntryTypes.java, src/main/java/org/jabref/model/entry/BibtexEntryType.java, src/main/java/org/jabref/model/entry/CustomEntryType.java, src/main/java/org/jabref/model/entry/EntryType.java, src/test/java/org/jabref/logic/importer/fileformat/BibtexParserTest.java, src/test/java/org/jabref/model/entry/IEEETranEntryTypesTest.java
Fixes #3046 (problems in the entry editor caused by duplicate fields in customized entry types) by no longer allowing duplicate fields, i.e. moved from List to Set.
=> Fix #3046: No longer allow duplicate fields in customized entry types

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/OtherFieldsTab.java, src/main/java/org/jabref/model/entry/InternalBibtexFields.java
Seemed to be the consent in https://github.com/JabRef/jabref/issues/3213.
=> Move groups field from others to general

scripts/syncLang.py
fixes #3414,
makes https://github.com/JabRef/jabref/pull/3415 obsolete...
=> Backport of syncLang to python2

src/main/java/org/jabref/gui/customentrytypes/EntryCustomizationDialog.java, src/main/java/org/jabref/gui/customentrytypes/FieldSetComponent.java
merge if test passes since it is only a very minor code change.
=> Fix #3411: ordering of fields in customized entry types works again

src/main/java/org/jabref/gui/EntryTypeDialog.java, src/main/java/org/jabref/gui/preftabs/ImportSettingsTab.java, src/test/java/org/jabref/logic/l10n/LocalizationConsistencyTest.java
Fix for https://github.com/JabRef/jabref/issues/3397
(I made some newlines in the `findMissingLocalizationKeys` so that they can be better seen in the console)
=> Fix test for quoted lang messages

.github/ISSUE_TEMPLATE.md
I added a tasklist checkbox with the hint to verify the problem with the latest master
=> Add Hint for checking master version

AUTHORS, CHANGELOG.md, src/main/java/org/jabref/logic/specialfields/SpecialFieldsUtils.java, src/main/java/org/jabref/model/entry/BibEntry.java, src/test/java/org/jabref/logic/specialfields/SpecialFieldsUtilsTest.java, src/test/java/org/jabref/model/entry/BibEntryTests.java
Fixes a bug where JabRef special fields (such as 'printed', 'relevant', ...) were not cleared (e.g. removing the 'printed' flag) when using synchronization of special fields via the bibtex keywords field.
See #3432 for more details.
=> Fix removal of special fields when syncing them via keywords

src/test/java/org/jabref/logic/importer/fileformat/FreeCiteImporterTest.java
FreeCite seems to be down atm. While the issues looks to be temporary (http://freecite.library.brown.edu/) is also down, I have declared the test as a fetcher test.
=> Declare FreeCiteImportestTest as Fetcher Test

jabref.install4j
Should fix #3434 
add  max version to 1.8
I tested this under Windows 10 with jdk9 and jdk9 installed and it now works correclty
@halirutan  @tobiasdiez  could you please test, if this works for you, too?
=> Improve searching for JRE in install4j and set max version

build.gradle, external-libraries.txt, src/main/java/org/jabref/gui/EntryTypeDialog.java, src/main/java/org/jabref/gui/SidePaneComponent.java, src/main/java/org/jabref/gui/groups/GroupSidePane.java
In order to be able to properly move to Java 9 (see #2594), we need to get rid of all accesses of internal APIs. Unfortunately, we also use libraries that make such internal accesses and we need to find a solution for that.
One of these libraries is swingx. Originally by Sun, it is no longer maintained since quite a while we could not even upgrade to the newest version, because of bugs in the library. It is time to get rid of this dependency. This PR replaces the usage of swingx with regular Swing components. Only the new entries dialog and the side pane are affected. For the new entries dialog, the change is trivial (just using a regular layout manager). For the side pane, a few changes are needed, but I can make it roughly resemble the old layout. 
There's one bigger change, though, …
=> Replace swingx with standard swing

CHANGELOG.md, src/main/java/org/jabref/gui/preftabs/AppearancePrefsTab.java
In regard to the java9 switch I played around with some styles and noticed, that the [Nimbus Lool and Feel](https://docs.oracle.com/javase/tutorial/uiswing/lookandfeel/nimbus.html) is not avaiable 
----
=> list all avaiable styles

.travis.yml, build.gradle
With the switch to JUnit 5, the upload of test coverage data to codecov stopped working. Hopefully, this is working again with this PR. The added code essentially comes from https://github.com/junit-team/junit5/issues/1024.
I also included the fetcher tests in the calculation of the code coverage. Was there a reason to exclude them?
----
=> Fix code coverage report

CHANGELOG.md, src/main/java/org/jabref/gui/BasePanel.java, src/main/java/org/jabref/gui/entryeditor/EntryEditor.java
=> Fix threading issues 

CHANGELOG.md, src/main/java/org/jabref/logic/util/strings/HTMLUnicodeConversionMaps.java
`LaTex` use various escape strings to denote certain symbols. Here I add {\textquotesingle} to the html conversion table, which represents apostrophe (').
----
=> Add \textquotesingle to the html conversion table

CHANGELOG.md, src/main/java/org/jabref/gui/externalfiles/DroppedFileHandler.java
Fixes  #3490.
There's a checkstyle problem at the moment, but is present on master. It's a false positive and we have to see how to get around that.
----
=> Link PDF on JavaFX thread

src/main/java/org/jabref/logic/util/strings/HTMLUnicodeConversionMaps.java, src/test/java/org/jabref/logic/layout/format/HTMLCharsTest.java
Follow-up to #3487 Actually, the mapping in that PR has not been correct syntactically.
----
=> Fix mapping of textquotesingle

build.gradle
This enables working junit5 with eclipse Oxygen 
https://marketplace.eclipse.org/content/junit-5-support-oxygen
----
=> Add required lib for junit5 in eclipse

.travis.yml
Our current workflow is to create a branch on the main JabRef fork and then open a PR for it. This, however, leads to two travis builds: one for the new push to JabRef and one for the PR.
There seems to be no elegant way to force travis to
- always build PRs
- but don't build PRs from main branches twice
See https://github.com/travis-ci/travis-ci/issues/6612. I followed [the suggested solution on stackoverflow](https://stackoverflow.com/a/31882307/873661) and only white-listed the master branch.
Thus pushes to master still trigger a build, as well as all PRs. However, pushes to other branches on main does not result in build. Thus only one build is executed if you open a PR from a main branch. Disadvantage: you have to open a PR to get a build from a different branch. I don't think this …
=> Only build master branch on push

src/main/java/org/jabref/gui/search/GlobalSearchBar.java
In #3471 a NPE was mentioned. I'm not sure which object was null (it should not be the scene, since this is just set and the css file should also be always found). Moreover, I could not reproduce the exception, so this fix is a shot in the blue.
----
=> Fix NPE in search bar

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java
Resolves #3491. A click on the PDF icon on a linked file in the entry editor opens the file. This is consistent with the behavior in the main table and thus I didn't added a new button and / or changed the double-click behavior as it was suggested in the issue.
----
=> Implement #3491: Clicking the PDF icon in the linked files editor opens the file

build.gradle, circle.yml
As VersionEye is no longer working, I searched for an alternative and found this nice plugin:
https://github.com/ben-manes/gradle-versions-plugin
Run `gradlew dependencyUpdates` to show the dependencies and avaiable updates.
Supports different output formats to log stuff.
Example:
```
The following dependencies have later milestone versions:
- com.microsoft.azure:applicationinsights-core [1.0.9 -> 1.0.10]
- com.microsoft.azure:applicationinsights-logging-log4j2 [1.0.9 -> 1.0.10]
- com.tngtech.archunit:archunit-junit [0.4.0 -> 0.5.0]
- com.gradle:build-scan-plugin [1.9 -> 1.10.3]
- org.controlsfx:controlsfx [8.40.14 -> 9.0.0]
- de.jensd:fontawesomefx-materialdesignfont [1.7.22-4 -> 2.0.26-9.1.2]
- org.apache.pdfbox:fontbox [1.8.13 -> 2.0.8]
- gradle.plugin.install4j.install4j:gradle_plugin …
```
=> Add dependency checker plugin

src/main/java/org/jabref/gui/search/GlobalSearchBar.java
Fiexes #3505
I think, I managed to locate the problem of the NPE and the missing search bar. Apparently, in some conditions the syntax `../` to access the parent in a path does not work for resources. Thus the css file is not found, resulting in a NPE.
----
=> Fixes #3505: Another try to fix the NPE in the search bar

src/main/java/org/jabref/gui/collab/GroupChangeViewModel.java
This avoids the NPEs in #3526. However, I can't get the groups side pane to repaint and depict the modified groups tree. I've tried different ways via calling the `GroupsSidePane` or setting selected groups in the `StateManager`, but no success.
@tobiasdiez How do I force the `GroupSidePane` to display a changed group tree?
----
=> Add null checks in GroupChangeViewModel

.travis.yml
Per default, travis pulls the last 50 commits.
This sets the depth to one, which is all we need. It's a small optimization.
=> Set git clone depth to 1 in Travis

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/MapBasedEditorViewModel.java
Fixes #3538 
I dunno if this is the best idea, but it works...
----
=> Fix options databinding by adding elements if they are not in the initial map

.travis.yml, build.gradle, xjc.gradle
I have created a new build job on Travis, that automatically checks if there are zero out-of date dependencies.
Features:
As soon as anybody sees that a dependency is out-of-date, on travis, we can update it automatically.
Furthermore, I regrouped the gradle tasks that belong together.
=> Automate Gradle dependency Update checks

CONTRIBUTING.md, src/test/java/org/jabref/logic/l10n/LocalizationConsistencyTest.java
[Crowdin](http://translate.jabref.org/) automatically adds missing translations to the other languages.
With our `localizationUpdate` task, we also do that. This leads to conflicts at the Crowdin synchronizations.
This PR proposes to 
1. update the description of how to add new strings
2. update the tests to enable the translations being a subset of the existing translations.
After each sync, the translation will reappear. So we have a short time window where the translations are missing and that translators using GitHub do not see these new translations. I would accept that.
News: We have 17 new Indonesian translations, because a guy just translated some strings there at Crowdin. 🎉
=> Describe new workflow with Crowdin

CHANGELOG.md, src/main/java/org/jabref/gui/externalfiles/AutoSetFileLinksUtil.java, src/test/java/org/jabref/gui/externalfiles/AutoSetFileLinksUtilTest.java
=> Make path relative when adding automatically found file

src/test/java/org/jabref/gui/keyboard/KeyBindingsDialogViewModelTest.java, src/test/java/org/jabref/logic/remote/RemoteTest.java
=> Fix JUnit tests on MacOS

src/main/java/org/jabref/gui/exporter/ExportAction.java, src/main/java/org/jabref/gui/exporter/ExportFileFilter.java, src/main/java/org/jabref/logic/exporter/BibTeXMLExportFormat.java, src/main/java/org/jabref/logic/exporter/ExportFormat.java, src/main/java/org/jabref/logic/exporter/ExportFormats.java, src/main/java/org/jabref/logic/exporter/IExportFormat.java, src/main/java/org/jabref/logic/exporter/MSBibExportFormat.java, src/main/java/org/jabref/logic/exporter/ModsExportFormat.java, src/main/java/org/jabref/logic/exporter/OpenDocumentSpreadsheetCreator.java, src/main/java/org/jabref/logic/exporter/OpenOfficeDocumentCreator.java, src/main/java/org/jabref/logic/util/FileExtensions.java, src/main/java/org/jabref/preferences/CustomExportList.java
=> ExportFormats: Use FileExtension enum

.mailmap, AUTHORS
These are the new authors of Jabref. :tada: 
I have contacted @MBunel  and @weidafan, whether they can provide us their full names, so let's wait until the release before we merge this.
=> Add new authors to mailMap

build.gradle
The JUnit4 tests are handled by the `junit-vintage-engine`, so we don't need the old dependency anymore. 🎉
=> Remove Dependency for JUnit4

src/main/java/org/jabref/gui/dbproperties/DatabasePropertiesDialog.java
When user wanted to lead default Library properties, after clicking OK button even though there was no modification in Library property the bibTeX tab marked as modified. I fixed this bug so no need to  worry about this anymore.  
Fixes #3562 
----
=> Library properties: no change but.. (issue #3562)

CHANGELOG.md, src/main/java/org/jabref/gui/search/GlobalSearchBar.java
Fixes #3598 by covering the autocompletion in the search bar with the same preference option as in the entry editor. 
----
=> Make it possible to disable autocompletion in the search bar

README.md
[CodeTriage](https://www.codetriage.com/) is an app I have maintained
for the past 4-5 years with the goal of getting people involved in
Open Source projects like this one. The app sends subscribers a random
open issue for them to help "triage". For some languages you can also
suggested areas to add documentation.
The initial approach was inspired by seeing the work of the small
core team spending countless hours asking "what version was
this in" and "can you give us an example app". The idea is to
outsource these small interactions to a huge team of volunteers
and let the core team focus on their work.
I want to add a badge to the README of this project. The idea is to
provide an easy link for people to get started contributing to this
project. A badge indicates the number of people …
=> Get more Open Source Helpers

CHANGELOG.md, src/main/java/org/jabref/gui/cleanup/CleanupPresetPanel.java, src/main/java/org/jabref/preferences/JabRefPreferences.java
This fixes https://github.com/JabRef/jabref/issues/3619 with a (IMHO) less confusing default:
----
- <s>[ ] If you changed the localization: Did you run `gradle localizationUpdate`?</s>
=> CleanupStep.MOVE_PDF is not a CleanupPreset anymore

CONTRIBUTING.md, README.md
This addresses https://github.com/JabRef/jabref/issues/3586
In the DevCall, we decided, that we will try to use Gitter and see how it goes.
The main arguments were:
- easy to join for new users
- offer help for new developers since the burden of initial JabRef development is high for newcomers - even if we have https://github.com/JabRef/jabref/wiki/High-Level-Documentation and https://github.com/JabRef/jabref/wiki/Code-Howtos
- Nearly none of the developers uses Slack
- does not clutter the Skype chat of the developers
- developers can use [pinned tabs](https://support.mozilla.org/en-US/kb/pinned-tabs-keep-favorite-websites-open) to keep gitter always opened
We will shutdown gitter in case there won't be much support from @JabRef/developers there (because lack of time). Nevertheless, we …
=> Add gitter badge

CHANGELOG.md, src/main/java/org/jabref/gui/importer/ImportFormats.java, src/main/java/org/jabref/gui/util/FileFilterConverter.java, src/main/java/org/jabref/logic/msbib/BibTeXConverter.java, src/main/java/org/jabref/logic/msbib/MSBibConverter.java, src/main/resources/l10n/JabRef_fr.properties, src/test/java/org/jabref/logic/importer/fileformat/MsBibImporterTestFiles.java, src/test/resources/org/jabref/logic/importer/fileformat/MsBibImporterTestTranslator.bib, src/test/resources/org/jabref/logic/importer/fileformat/MsBibImporterTestTranslator.xml
Upcoming issue from #1750
While testing this I noticed that the import was broken (due to the recent export filetype/extension changes), fixed that, too.
Directly use Bookauthors and Translator for import from xml
Add test 
----
=>  Export translator field to msoffice 2007 xml

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, scripts/syncLang.py, src/test/java/org/jabref/logic/l10n/LocalizationConsistencyTest.java
Thanks to Crowdin, the workflow to add new keys is simpler.
This addresses https://github.com/JabRef/jabref/issues/3573, but not completely fixes it. More work is required at `syncLang.py`. That script, however, is not absolutely required any more. Crowdin de facto replaced it.
----
=> Update documentation to new workflow using Crowdin

CHANGELOG.md, src/main/java/org/jabref/gui/IconTheme.java, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_in.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_sv.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_zh.properties
Before:
After:
- Also add entry "Twitter" to "JabRef resources"
- Put "Opens JabRef's X page" together in JabRef_*.properties
Does not connect to Twitter directly, thus no spying by Twitter, Facebook, ... Refs https://www.heise.de/newsticker/meldung/Datenschutz-und-Social-Media-Der-c-t-Shariff-ist-im-Einsatz-2470103.html
----
=> Add Facebook and Twitter icons to the toolbar

src/main/java/org/jabref/gui/util/IconValidationDecorator.java
The current version does not compile on my computer locally. This PR fixes it. It was already discussed with @halirutan on gitter.
```
/Users/dietzl/git/jabref/src/main/java/org/jabref/gui/util/IconValidationDecorator.java:42: error: createDecorationNode(ValidationMessage) in IconValidationDecorator cannot override createDecorationNode(ValidationMessage) in GraphicValidationDecoration
private Node createDecorationNode(ValidationMessage message) {
^
attempting to assign weaker access privileges; was protected
```
=> Quickfix to get build running on all platforms

CHANGELOG.md, src/main/java/org/jabref/logic/exporter/ExporterFactory.java, src/main/java/org/jabref/logic/exporter/TemplateExporter.java, src/main/java/org/jabref/logic/layout/Layout.java
This fixes the remaining part of #3634
I had a closer look at the export / layout logic and wow, this is arcane! The code is more than 12 years old and almost as bad as the bibtex parser used to be.
This PR is based on two decisions:
- I do not want to change the old layouting code. If I do, I am almost guaranteed to break it in many ways.
- I do not know if the removal of empty lines in exported text is really desirable in all cases. Maybe users wrote their custom formatters to explicitly include empty lines? I cannot tell.
We now have one case (RIS export) where empty lines are not desired. So, I implemented a solution that only changes the behavior of the RIS export, but leaves all others untouched. Nonetheless, it is very easy (single constructor parameter) to let other formats use …
=> Export no empty lines in RIS format

src/test/java/org/jabref/logic/importer/FulltextFetchersTest.java, src/test/java/org/jabref/logic/importer/WebFetchersTest.java, src/test/java/org/jabref/logic/importer/fetcher/AbstractIsbnFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/ArXivTest.java, src/test/java/org/jabref/logic/importer/fetcher/AstrophysicsDataSystemTest.java, src/test/java/org/jabref/logic/importer/fetcher/CrossRefTest.java, src/test/java/org/jabref/logic/importer/fetcher/DBLPFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/DiVATest.java, src/test/java/org/jabref/logic/importer/fetcher/DoiFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/GvkFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/IacrEprintFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/IsbnFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/IsbnViaEbookDeFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/LibraryOfCongressTest.java, src/test/java/org/jabref/logic/importer/fetcher/MedlineFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/MrDLibFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/SpringerLinkTest.java, src/test/java/org/jabref/logic/importer/fetcher/TitleFetcherTest.java
I converted only some, because others rely on Mockito and there is not yet an offical Mockito-Extension for junit5
See https://github.com/mockito/mockito/issues/445 and https://github.com/mockito/mockito/pull/1221 for details.  Then we can consider the others.
----
=> Fix medline and convert some fetchers to junit5 where possible

CHANGELOG.md, src/main/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGenerator.java, src/main/java/org/jabref/logic/bibtexkeypattern/BracketedPattern.java, src/main/java/org/jabref/logic/util/io/FileUtil.java, src/main/java/org/jabref/logic/util/io/RegExpBasedFileFinder.java, src/test/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGeneratorTest.java, src/test/java/org/jabref/logic/util/BracketedPatternTest.java
Fixes #3648. 
The problem was that `resultingLabel = formatter.get().format(label);` always used the original input and not the result of the previous modifier.
----
=> Fixes #3648: Chained modifiers work again

src/main/java/org/jabref/gui/BasePanel.java
While investigating #3673  I noticed a thread error when changing the entry otherwise. 
I think this could also solve some other issues here 
----
=> Fix some FX  Thread issue

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java, src/test/java/org/jabref/gui/fieldeditors/LinkedFileViewModelTest.java
This pull request fixes the following issues:
* When a file link in a bibliography entry is deleted by the user, a dialog is displayed. Previously, the default (first) dialog option deleted the linked file from disk. The default behaviour has been changed to just removing the file link from the entry.
This is a fix to issue #3679 
Fixes #3679 
* When clicking the "Cancel" button in the file link deletion dialog, the file  was being deleted from the list. This behaviour has been fixed by changing the return value of the `delete()` method when the "Cancel" button is chosen.
---
I am unsure whether the remaining checklist items are applicable to this pull request.
I would be willing to provide tests for the `delete()` method; however, the `DialogService` member cannot be stubbed-in/mocked as …
=> [WIP] File link deletion dialog improvements

src/main/java/org/jabref/model/search/matchers/AndMatcher.java, src/main/java/org/jabref/model/search/matchers/OrMatcher.java
Just a small change in the groups matcher code to use streams instead of old-style for-loops.
----
=> Use streams in group matcher

src/main/java/org/jabref/gui/Main.css
A few visual improvements for the new maintable.
As it should be for a "visual PR", I only had to touch the stylesheet - I love JavaFX ;-).
- Use the same color for the focus of text-input as for the other controls (e.g. tabs, selected row)
- Remove space between tab header and content (previously, there was a small gray gap below the header)
- Replace JavaFX scrollbar by "flat version" and display scrollbars only if control has focus
----
=> Visually improve display of maintable

src/main/java/org/jabref/gui/maintable/MainTable.java, src/main/java/org/jabref/gui/util/ViewModelTableRowFactory.java
With this PR the new maintable support again the following gesture to select entries: click on one row and hold mouse button, then move over other rows to also select them.
The view does not scroll when you move the curser to the border and thus currently it is only possible to select rows in the current view using the method described above. To enable scrolling needs further research on my part and thus is something for a new PR.
----
=> Fix select entries my holding mouse

config/IntelliJ Code Style.xml
Code examples are better than words. So, let them speak. Instead of the current
````java
super.getFoo()
.foo()
.getBar()
.bar();
````
we now get the nicely aligned
````java
super.getFoo()
.foo()
.getBar()
.bar();
````
----
=> [WIP] Django style unchained.

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/SourceTab.java, src/main/java/org/jabref/gui/util/DefaultTaskExecutor.java
=> Fix space leads to jump in entry editor

src/main/java/org/jabref/model/entry/identifier/DOI.java, src/test/java/org/jabref/model/entry/identifier/DOITest.java
Fix koppor issues https://github.com/koppor/jabref/issues/3 "DOI: encoded URLs should be supported". New divider within the DOI % is supported.
----
=> DOI encoded with % supported

src/main/java/org/jabref/logic/exporter/GroupSerializer.java, src/test/java/org/jabref/logic/importer/util/GroupsParserTest.java
=> Group separator escaping

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupDialog.java, src/main/java/org/jabref/gui/groups/GroupTreeController.java, src/main/resources/l10n/JabRef_en.properties
Fixes [koppor#277](https://github.com/koppor/jabref/issues/277)
This fixes the name of the group editing window to "Add group" instead of "Edit Group" when adding a new group.
The group editing window can now also be called by double-clicking the group to be edited.
----
----
_Credit (for an exercise):
Rico Haas
David Zeck_
=> Group interface: Usability tweaks

src/main/java/org/jabref/gui/journals/AbbreviateAction.java
Removed redundant code in line 60 and 61 (callable was executed twice without using the return value of the first execution).
Also removed the ArrayList which was used to count the number of abbreviations made. Instead the number will be incremented within the for-loop now.
Removed the null check of the _entries_ variable, because JavaDoc comment of _panel.getSelectedEntries()_ clearly says it never returns _null_.
----
=> Code cleanup AbbreviateAction.java

src/main/java/org/jabref/gui/IconTheme.java, src/main/java/org/jabref/gui/search/GlobalSearchBar.java, src/main/java/org/jabref/gui/search/SearchTextField.java
I am trying to change the color of the magnifier icon as requested here: #3535
However, the icon refuses a color change. It even opts out of the color scheme of JabRef, since it is black instead of purple (despite the fact that the icon is configured as purple in the code).
@tobiasdiez How can I change the color of this icon? Any change will do, really. For reasons unknown to me the icon straight-out refuses the change. 
----
=> Try to change color of magnifier icon

src/main/java/org/jabref/gui/PreviewPanel.java, src/main/java/org/jabref/gui/fieldeditors/EditorTextArea.java, src/main/java/org/jabref/gui/fieldeditors/FieldEditors.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java, src/main/java/org/jabref/gui/fieldeditors/OptionEditor.java, src/main/java/org/jabref/gui/fieldeditors/TextArea.java, src/main/java/org/jabref/gui/groups/GroupTreeNodeViewModel.java, src/main/java/org/jabref/gui/search/SearchResultFrame.java, src/main/java/org/jabref/logic/exporter/GroupSerializer.java, src/test/java/org/jabref/logic/bibtex/FieldContentParserTest.java
I thought it might be good to reduce the number of Codacy issues, so I started hunting them.
To keep these changes reviewable, I will open a new PR for the next batch.
Also I plan to adapt the codacy configuration to reduce false positives.
=> Fix Some Codacy Issues

CHANGELOG.md, scripts/bib-file-generator.py, src/main/java/org/jabref/JabRefExecutorService.java, src/main/java/org/jabref/gui/journals/AbbreviateAction.java
Fixes #2831 
Added new method _executeAndReturn_ to the JabRefExecutorService that allows to run callables that return a value when the computation is completed. Using this method the abbreviations in _AbbreviateAction.java_ should run parallel now.
----
=> [WIP] Fix for issue 2831

CHANGELOG.md, src/main/java/org/jabref/gui/PreviewPanel.java
fixed issue 298
----
Credit (for an exercise):
Florian Grotepaß
=> fixed issue 298

CHANGELOG.md, src/main/java/org/jabref/gui/journals/ManageJournalAbbreviationsViewModel.java, src/main/java/org/jabref/logic/journals/JournalAbbreviationRepository.java
Fixes #3323
I was actually surprised to find that no one attacked the issue so far. These were really just a few minor changes. Ultimately, the `Abbreviation` class is still flawed, because it violates the equals contract and we use it in a `Set`. That's why the code might look strange. Nevertheless, it is the fix suggested in the issue. 
----
=> Improve performance for managing journal abbreviations

src/main/resources/xjc/mods/mods-3-7.xsd, src/main/resources/xjc/mods/mods-binding.xjb, xjc.gradle
Since the MODS Schema is backwards-compatible to 3.6 http://www.loc.gov/standards/mods/mods-schemas.html we can update it without any issues.
This fixes https://github.com/koppor/jabref/issues/307, but not https://github.com/JabRef/jabref/issues/3737
=> Update MODS from 3.6 -> 3.7

README.md
I am not sure about a good way to link http://contribute.jabref.org. WDYT?
=> Add link to contribute.jabref.org

src/main/java/org/jabref/JabRefGUI.java, src/main/java/org/jabref/gui/JabRefFrame.java
=> Add the Menubar to the Titlebar in MacOS

.github/PULL_REQUEST_TEMPLATE.md
I found https://github.com/joelparkerhenderson/git_commit_message in the net and I really like it. Maybe, we should promote that here, too? WDYT?
I also reordered the checklist at the PR template to go from UI to technical issues. Although the documentation is still the last bullet point.
=> Reorder checklist in PR template and add "good commit message"

src/main/java/org/jabref/logic/bibtex/FieldContentParser.java, src/main/java/org/jabref/logic/migrations/MergeReviewIntoCommentMigration.java, src/test/java/org/jabref/logic/importer/migrations/MergeReviewIntoCommentActionMigrationTest.java, src/test/java/org/jabref/testutils/TestUtils.java
fixes https://github.com/koppor/jabref/issues/311
=> Don't trim when migrating review field

src/test/java/org/jabref/architecture/MainArchitectureTests.java
Fixes a part of #2617
Updates the architecture tests to JUnit5 and also catches violations in static imports now. I tested this by adding a static import and checking that the build breaks. It does, but of course I had to remove the cause again.
----
=> Update Architecture Tests to catch static imports

src/main/java/org/jabref/gui/importer/actions/MergeReviewIntoCommentAction.java, src/main/java/org/jabref/gui/importer/actions/MergeReviewIntoCommentConfirmationDialog.java, src/main/resources/l10n/JabRef_en.properties
Fixes https://github.com/koppor/jabref/issues/312.
Sorry, the PR quality of https://github.com/JabRef/jabref/pull/3658 was really not so good.
=> Meaningful button review field migration

CHANGELOG.md, src/main/java/org/jabref/gui/importer/ImportFormats.java
Added *.* (any file) to the File Filter Dialog. Now you can choose any file to import to try to import to your library. Fixes #3757.
----
=> Added <any file type> to the Import File Filter Dialog.

src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java
Fixes an issue where the group tree of the last database is still shown even after the database was closed.
Reported in https://github.com/JabRef/jabref/pull/3621#issuecomment-368821666
----
=> Show empty group pane if no database is open

src/main/java/org/jabref/gui/JabRefFrame.java
Fixes points 3. and 4. of https://github.com/JabRef/jabref/pull/3621#issuecomment-368821666
> Another issue is that the search-bar is connected to the splitter between main-table and the left side bar. When I resize the main-table, it is possible to move the search-bar over the toolbar icons:
> When closing the sidebar, the main-table is not maximized anymore. As can be seen in the image above, we end up with a gray area where the side-bar was.
----
=> Allow side pane to be completely hidden

src/main/java/org/jabref/gui/FXDialogService.java, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/actions/JabRefAction.java
Sets the correct parent for the file dialogs so that these are now modal. 
----
=> Set main stage for file dialogs

src/main/java/org/jabref/gui/BasePanel.java, src/main/java/org/jabref/gui/DialogService.java, src/main/java/org/jabref/gui/FXDialog.java, src/main/java/org/jabref/gui/FXDialogService.java, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/resources/l10n/JabRef_en.properties
Fixes the delete action in the maintable branch and the "do you really want to delete the entry"-dialog is converted to JavaFX. Moreover, a few lines of JavaFX-Swing-interaction code in `FXDialog` are deleted since it is no longer needed.
----
=> Fix delete action and convert confirmation dialog to JavaFX

src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/actions/ActionFactory.java
I know this is a controversial topic in the maintable-beta right now, but to get the discussion going a little more and taking inspiration from #3678, I took the liberty to extend the toolbar with more buttons here.
This is really not meant as a final say, it just moves the code in place for some buttons that seem of some value for me. They can be removed again, resorted, and the layout is probably also not perfect.
Here's a screenshot:
----
=> Extend toolbar with more icons and add tool tips

src/main/java/org/jabref/JabRefGUI.java, src/main/java/org/jabref/gui/FXDialogService.java, src/main/java/org/jabref/gui/dialogs/BackupUIManager.java, src/main/java/org/jabref/gui/importer/actions/OpenDatabaseAction.java, src/main/resources/l10n/JabRef_en.properties
Fixes #3799 @halirutan  Have a look if this works for you
----
=> Change open last edited dialgo to javafx

.travis.yml
I think it would be nice to have travis build for maintable-beta. 
That would show us some potential errornous tests or
Edit// Maybe first it is useful to update the localization files to be consistent 
----
=> Enable travis build for maintable-beta

build.gradle, src/main/java/org/jabref/logic/xmp/DublinCoreExtractor.java
@tobiasdiez this is another round of trying to update the applicationinsights.
refs https://github.com/JabRef/jabref/pull/3559, https://github.com/JabRef/jabref/pull/3317, https://github.com/JabRef/jabref/issues/3561, and https://github.com/JabRef/jabref/issues/3313
=> Update applicationinsights from 1.0.9 -> 2.0.1

.travis.yml
Checkstyle will fail at first, so I think it makes sense to let it execute/start at first
----
=> Update test order -> Execute checkstyle first

CHANGELOG.md, src/main/java/org/jabref/gui/copyfiles/CopyFilesAction.java, src/main/java/org/jabref/gui/copyfiles/CopyFilesTask.java
Fixes #3818 
(ignore the branch name, I  thought it was a different error)
The part in the CopyTask should also be copied to the maintable beta branch. The rest is already there.
----
=> Fix Copy linked files dialog showing NPE when no linked files

scripts/syncLang.py
Fixes #3573 
As already mentioned in my comment here: https://github.com/JabRef/jabref/issues/3573#issuecomment-366490651
there was a logical issue hidden within the merging process when synchronizing the files. I fixed this issue and added/changed a couple of other things.
----
=> [WIP] Fix syncLangPy script 

src/main/java/org/jabref/logic/l10n/Localization.java
=> Fixes #3796: Pretend that we have every translation for every key

src/main/java/org/jabref/gui/copyfiles/CopyFilesAction.java, src/main/resources/l10n/JabRef_en.properties
Follow up from #3818 
Fixes #3818 
----
=> Show dialog when copy files did not found file

src/main/resources/l10n/JabRef_en.properties
This seems to be an escape character that slipped into the localized text. Presumably a copy-and-paste error?
=> Remove erroneous escape character

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupTreeController.java
This PR reverts the part of #3715, which introduced that a double click on a group opens the edit window. However, the default behavior is that double click expands or collapse the subtree and users probably profit from the default behavior more than from the easier way to edit a group.
Fixes (or better closes) https://github.com/koppor/jabref/issues/277.
----
=> Partial revert of #3715 since double click on group should expand/collapse it

CHANGELOG.md, src/main/java/org/jabref/gui/externalfiles/FileDownloadTask.java, src/main/java/org/jabref/gui/fieldeditors/FieldEditors.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditorViewModel.java, src/main/java/org/jabref/gui/util/BackgroundTask.java, src/main/java/org/jabref/logic/importer/fetcher/ArXiv.java, src/main/java/org/jabref/logic/util/io/FileUtil.java, src/main/java/org/jabref/model/entry/LinkedFile.java, src/test/java/org/jabref/architecture/TestArchitectureTests.java, src/test/java/org/jabref/gui/fieldeditors/LinkedFileViewModelTest.java
Inspired by the discussion in #3818, I added a "Download file" option in the context menu of a linked file (if it is an online link). Moreover, the bug #3614 is fixed.
This PR was brought to you with the support of coffee from the JabRef cup!
----
=> Provides download option in context menu and fixes #3614

src/main/java/org/jabref/Globals.java, src/main/java/org/jabref/JabRefGUI.java, src/main/java/org/jabref/gui/AbstractView.java, src/main/java/org/jabref/gui/customjfx/CustomJFXPanel.java, src/main/java/org/jabref/gui/util/ControlHelper.java, src/main/java/org/jabref/gui/util/ThemeLoader.java
With this PR, working on styling and css files should be easier. Css files are now watched for changes and automatically reloaded. Thus JabRef does not have to be restarted in order to apply a new design. In IntellJ you can now start debugging, edit the css and apply the changes by `Build > Build project` or `Run > Reload Changed Classes`. 
The idea of the `ThemeLoader` class is to support external css files (next to the jar file) in the future so that users could change the theme on their own.
I'll add a short note documenting this feature to the wiki after this PR gets merged.
----
=> Watch main css file for change and reapply automatically

src/main/java/org/jabref/gui/fieldeditors/FieldEditors.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditorViewModel.java, src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java, src/test/java/org/jabref/gui/fieldeditors/LinkedFileViewModelTest.java
Cleanup PR for my changes I had to make during merge
----
=> Get rid of journal abbrev loader in linkedFiles

CHANGELOG.md, src/main/java/org/jabref/logic/autosaveandbackup/BackupManager.java, src/main/java/org/jabref/logic/bibtex/BibEntryWriter.java
Fixes  #3811
InvalidFieldValueExceptions are no longer printed into the log when they occur during autosave. Fields in the entry editor still have the warning sign next to them.
The normal save operation (CTRL+S) still triggers a warning dialog, saying that the file could not be saved.
----
=> Do no longer log InvalidFieldValueExceptions during autosave

src/main/java/org/jabref/gui/BasePanel.java, src/main/java/org/jabref/gui/entryeditor/EntryEditor.css, src/main/java/org/jabref/gui/entryeditor/SourceTab.java
I looked a bit more at the freezing problem and could nail it down to the CodeArea.
I replaced the CodeArea with a simple TextArea and now I don't get any freezes anylonger 
We don't use any extensive features of the TextArea, except for some styling.
We should adapt this for the 4.2 release as a workaround. As we don't have those freezes in the maintable-beta, I am in strong favor of using this.
I did some heavy clicking and scrolling and did not receive any freezes.
----
=> Fix freezing by replacing codeArea with TextArea

src/test/java/org/jabref/gui/importer/fetcher/OAI2HandlerFetcherTest.java
This enables on OAI2HandlerFetcherTest
=> Exchange Ignore by Disabled

external-libraries.txt
This fixes [#3897](https://github.com/JabRef/jabref/issues/3897).
So I went through the BSD ones and ensure their license info is correct now. Two points worth mentioning:
- jgoodies form 1.9.0 is no longer downloadable. Most recent available version is 1.8.0, so I checked its license and assume it did not change.
- antlr v3 has an alternative website now, so I changed its URL too.
Also fixed the ID "Apache 2.0" to "Apache-2.0". Didn't really look into each project with non-BSD license though.
----
=> Fix SPDX license ID for external libraries

src/main/java/org/jabref/logic/formatter/Formatters.java, src/main/java/org/jabref/logic/formatter/bibtexfields/RegexFormatter.java, src/test/java/org/jabref/logic/formatter/FormatterTest.java, src/test/java/org/jabref/logic/formatter/bibtexfields/RegexFormatterTest.java
Refactor the regular expression-based formatter. Previously, the regex was sent through a static `setRegex` method, now it gets passed as a normal constructor argument.
----
=> Formatter refactoring

src/main/java/org/jabref/cli/ArgumentProcessor.java, src/main/java/org/jabref/logic/exporter/ExporterFactory.java, src/main/java/org/jabref/logic/exporter/XmpExporter.java, src/main/java/org/jabref/logic/util/FileType.java, src/main/java/org/jabref/logic/xmp/XmpUtilWriter.java, src/test/java/org/jabref/logic/exporter/CsvExportFormatTest.java, src/test/java/org/jabref/logic/exporter/ExporterTest.java, src/test/java/org/jabref/logic/exporter/HtmlExportFormatTest.java, src/test/java/org/jabref/logic/exporter/XmpExporterTest.java
Refs [koppor#319](https://github.com/koppor/jabref/issues/319).
Adds the first functionality to export the bib entries in a single .xmp file. 
@koppor For a first review: Please check the output format of the new .xmp file.
There is also a <?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?> tag included. Should I remove this tag?
The cli support is planned for the next days :)
----
=> Add XMP Exporter

CHANGELOG.md, src/main/java/org/jabref/gui/search/GlobalSearchBar.java
Before executing the search there is now a short delay.
I tested this with the Huge file bib and the performance is way better.
Still the entry editor has a high load, but that's out of scope.
Thx to @halirutan  who pointed me to the code in  #3553
----
=> Improve search performance

CHANGELOG.md, src/main/java/org/jabref/gui/preftabs/PreviewPrefsTab.java
Fixed saving entry preview preferences.
Stored preview citation styles were loaded in a wrapping Optional before.
Fixes #3845 
----
=> Fixed saving of entry preview preferences

src/main/java/org/jabref/logic/importer/IdBasedParserFetcher.java, src/test/java/org/jabref/logic/importer/fetcher/IsbnFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/IsbnViaEbookDeFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/MedlineFetcherTest.java
Refs #3854
Unfortunately not a very clean fix, but it is fine again.
Using the normal InputStream does not return anything. Probably as it is detected as automated crawler?
The interface with InputStream is just not really fitting here.
=> Fix ebook.de

src/main/java/org/jabref/logic/importer/fetcher/IEEE.java
Fixes #3966 
Apparently when in VPN network of University IEEE fulltext fetcher needs cookie support enabled
----
=> Fix IEEE Fetcher by enabling cookie support

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/EntryEditor.fxml, src/main/java/org/jabref/gui/entryeditor/EntryEditor.java
When re-designing the Entry Editor, the Generate BibTeX Button moved to the left on the Required Fields tab. Now I'm re-adding it to the toolbar on the left, because I think it should be accessible from all tabs. See screenshot
=> Add GenerateKey Button to Entry Editor Toolbar

.travis.yml, build.gradle
With these changes, the `checkstyle` task is no longer invoked as part of the `build` or `check` task. The `checkstyleMain` task and its variations are kept. 
Reason: The build fails as soon as the checkstyle task fails, possibly hiding more important build or test failures (recent [example](https://travis-ci.org/JabRef/jabref/builds/371621951?utm_source=github_status&utm_medium=notification)). Moreover, the checkstyle task is invoked as a separate build command on travis anyway. 
----
=> Do not run checkstyle as part of the gradle check task

src/main/java/org/jabref/gui/exporter/ExportToClipboardAction.java
Fix #3994 
```
runCommand error: null
java.lang.UnsupportedOperationException
at java.util.Collections$UnmodifiableList.sort(Unknown Source)
at org.jabref.gui.exporter.ExportToClipboardAction.run(ExportToClipboardAction.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at spin.Invocation.evaluate(Invocation.java:175)
at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108)
at java.lang.Thread.run(Unknown Source)
```
=> Fix #3994 Duplicate unmodifiable list for sorting

src/main/java/org/jabref/gui/util/ViewModelTableRowFactory.java
As wished in the [forum](http://discourse.jabref.org/t/how-to-enable-keyboard-context-key-windows), pressing the "context menu" button on the keyboard should show the context menu.
----
=> Activate context menu on key press

src/main/java/org/jabref/logic/bibtex/LatexFieldFormatter.java, src/main/java/org/jabref/logic/citationstyle/CSLAdapter.java
Fix issue [#3239](https://github.com/JabRef/jabref/issues/3239) on [maintable-beta](https://github.com/JabRef/jabref/tree/maintable-beta) branch
On month change from comboBox on OptionalFieldsTab, Month was not appear on IEEE style.
The issue get fixed.
----
=> Fix IEEE preview does not display month 

src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java, src/main/java/org/jabref/gui/util/ValueTableCellFactory.java
This fixes #3973.
Reimplements tooltips for file-, URL-/DOI- and Eprint-column in the maintable-beta.
----
=> Reimplement tooltips for file and identifier columns

CHANGELOG.md, src/main/java/org/jabref/gui/importer/fetcher/ACMPortalFetcher.java
Fixes #4018 
Removed `&` sign from ID pattern
Tested with a couple of searches, works fine
----
=> Fix ACM fetcher import of entries

CHANGELOG.md, src/main/java/org/jabref/logic/bibtexkeypattern/BracketedPattern.java, src/test/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGeneratorTest.java, src/test/java/org/jabref/logic/bibtexkeypattern/MakeLabelWithDatabaseTest.java
Feature Request in the forum:
http://discourse.jabref.org/t/jabref-differences-in-shorttitle-between-versions-3-8-1-and-4-not-discounting-the-a-an-of-in-titles/1147
----
=> Shortittle bibtexkeypattern now also discards small words

build.gradle, src/main/java/org/jabref/gui/help/AboutDialog.css, src/main/java/org/jabref/gui/help/AboutDialog.fxml, src/main/java/org/jabref/gui/help/AboutDialogView.java, src/main/java/org/jabref/logic/util/io/FileUtil.java
Instead of requiring an additional library for rendering one SVG image, the JavaFX-native [SVGPath](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/shape/SVGPath.html) should be used.
Removing the dependency `de.codecentric.centerdevice:javafxsvg:1.3.0` also removed the transitive dependency on Apache Commons IO, so its usages had to be removed.
This is part of #3421 
----
=>  Use JavaFX-native SVGPath for logo in About dialog

CHANGELOG.md, src/main/java/org/jabref/logic/cleanup/Cleanups.java
The cleaup presets in bibtex were not equal to the ones at biblatex. I fixed that:
Before in bibtex:
After in bibtex:
=> Use all-text-fields magic also in BibTeX cleanup.

src/main/java/org/jabref/logic/formatter/bibtexfields/HtmlToUnicodeFormatter.java, src/main/resources/l10n/JabRef_en.properties
All formatters return a localized `getName`. The only exception is the `HtmlToUnicodeFormatter`. This PR fixes this.
=> Add missing translation for "HTML to Unicode"

src/main/java/org/jabref/JabRefMain.java, src/main/java/org/jabref/cli/JabRefCLI.java
ExportFactory is not initialized at this execution point...
The printUsage method is used twice. The JabRefCLI prints the usage, if an error occurs during argument parsing and the ArgumentProcessor prints the usage, when --help option is chosen. 
I made two solutions for this problem:
- Commit 1: Some sort of a hack to only get the names of the exporters without altering the processing in the main method. 
- Commit 2: Changed the order of execution in the main method. The argument processor needs the export factory. I don't know, if the processing of the preferences will influence the cli functionality?
Fixes #4038
=> A first solution for the cli problem #4038

src/main/java/org/jabref/JabRefMain.java, src/main/java/org/jabref/migrations/PreferencesMigrations.java
Considered as necessary when reviewing #4047
=> Restructure startup

src/main/java/org/jabref/gui/push/AbstractPushToApplication.java
For unknown reasons, it seems no longer possible to give the command
as one single string. I created a test class and not even simple commands
can be executed. I'm not sure when this changed but giving the command
as a list of arguments works as expected.
----
=> Fix #4041 to make Push to Application work again on OSX.

src/main/java/org/jabref/gui/menus/FileHistoryMenu.java, src/main/java/org/jabref/logic/formatter/Formatters.java
So small that I merge directly...
----
=> Small fixes

crowdin.yml
Our JavaFX port does not need separate files anymore.
Refs #3873 #3877
=> Remove menu* from crowdin.yml

CHANGELOG.md, build.gradle
Fixes #4093. Since Java does not automatically update to 171, users have to manually install the 172 update. This is very convenient. 
I actually propose to cherry-pick this PR to 4.x and immediately release 4.3.1.
----
=> Set minimum java to 171

build.gradle, circle.yml
I discovered a gradle task fetching all dependencies without building. I added that and adapted the CircleCI script accordingly.
I also made some cleanups, which should ease the migration from CircleCI 1.0 to CircleCi 2.0.
=> Add gradle task downloadDependencies and use it at CircleCI

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/FieldsEditorTab.java, src/main/java/org/jabref/gui/fieldeditors/PersonsEditor.java
The first field of the FieldsEditorTab.java is selected on creating for focus, and the textarea inside the PersonsEditor is focused when the field is focused.
fixes [#4024](https://github.com/JabRef/jabref/issues/4024)
----
=> The textarea in the PersonsEditor is focused when the field is focused

CHANGELOG.md, gradle/wrapper/gradle-wrapper.properties, src/main/java/org/jabref/gui/importer/actions/OpenDatabaseAction.java
Opens the directory of the currently edited file when opening a new file
Fixes #4097
----
=> Opens the directory of the currently edited file when opening a new file

CHANGELOG.md, src/main/java/org/jabref/JabRefGUI.java, src/main/java/org/jabref/preferences/JabRefPreferences.java
Saves and reloads window state on close and on open.
Opens by default maximized.
Fixes #3859
----
=> Saves and reloads window state on close and on open

src/main/java/org/jabref/Globals.java, src/main/java/org/jabref/JabRefMain.java
@tobiasdiez  As this is just contains the relevant fix and works for me, I would be in favor for using this PR. You could still have your PR as refactoring PR then
----
=> Fix open thread prevents shutdown

src/main/java/org/jabref/gui/groups/GroupTreeView.java
(Partly) fixes https://github.com/JabRef/jabref/issues/4025. Right-click on a group no longer focuses that group. It's not perfect since there is no longer feedback on which group the user clicked and the context menu belongs to.  
Clicking the disclosure node (the small arrow) still leads to an immediate selection of the group. The selection happens before any events are triggered on the row and thus I'm not able to intercept the selection.
----
=> Groups right click

CHANGELOG.md, src/main/java/org/jabref/logic/journals/JournalAbbreviationRepository.java, src/test/java/org/jabref/logic/integrity/AbbreviationCheckerTest.java
=> Don't report journal name as abbreviated when full name = abbreviated name

build.gradle
There currently seems to be a problem in the version check plugin.
All issues resolved.
As long as junit-pioneer has no release version, we need so set level to integration. Disadvantage: This reports all snapshot versions from all other libs, too,
See https://github.com/ben-manes/gradle-versions-plugin/issues/239
----
=> Update dependency checker version and update deps

build.gradle
- Fixes that all the SNAPSHOT releases are shown in the dependencyUpdates check https://github.com/JabRef/jabref/pull/4131
- Updates two dependencies
=> Fix SNAPSHOT releases marked as outdated

docs/adr/0003-use-gradle-as-build-tool.md, docs/adr/index.md
This is part of a research by @snisnisniksonah, where we research on generalized architectural decision records (see <https://github.com/adr/gadr-java>) and concrete architectural decision records (see [MADR](https://adr.github.io/madr/)).
We aim for having two ADRs for build tools. One for Maven (see [ADR-0023](https://github.com/eclipse/winery/blob/master/docs/adr/0023-use-maven-as-build-tool.md) at Eclipse Winery) and one for Gradle. The one for gradle is contained in this PR.
=> Add ADR on using Gradle

src/main/java/org/jabref/gui/importer/fetcher/EntryFetchers.java, src/main/java/org/jabref/gui/importer/fetcher/SpringerFetcher.java, src/main/java/org/jabref/logic/importer/WebFetchers.java, src/main/java/org/jabref/logic/importer/fetcher/SpringerFetcher.java, src/main/java/org/jabref/logic/importer/util/JSONEntryParser.java, src/test/java/org/jabref/gui/importer/fetcher/SpringerFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/SpringerFetcherTest.java
The Springer fetcher is now implemented according to the new fetcher infrastructure. Instead of pagination support, the fetcher now only returns the first 20 items matched by the search query. 
I used the opportunity and fixed a few small things: url to pdf is now added as online file link (instead of in the url field) and the ending page is correctly parsed.
----
=> Convert Springer fetcher to new interface

build.gradle
I now added an exception for junit-pioneer  version checker. All other snapshots are rejected.
----
=> add exception for junit-pioneer in version rejection of snapshots

build.gradle, external-libraries.txt
There have been licensing issues at java-diff-utils. I resolved them (see https://github.com/java-diff-utils/java-diff-utils#license). This PR updates the dependency to the library version with a clean license.
=> Update java-diff-utils from 2.1.1 to 2.2.0

src/main/java/org/jabref/gui/BasePanel.java, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/actions/Actions.java, src/main/java/org/jabref/gui/search/GlobalSearchBar.java
Shortcut was simply not registered. Also remove a bit of legacy code which is no longer needed.
----
=> Fix #3062: Ctrl + F selects search field again

src/main/java/org/jabref/gui/EntryTypeDialog.java, src/main/java/org/jabref/gui/actions/NewEntryAction.java
As usual with these kind of freezes, it was again a problem with the interaction of Swing and JavaFX... it still has the problem that the dialog sometimes opens in the background (I've no idea how to fix it except converting the dialog to JavaFX).
----
=> Fix #4177: New entry dialog freezes no longer

src/main/java/org/jabref/gui/actions/NewSubLibraryAction.java
Yet another interaction between Swing and JavaFX threads...
----
=> Fix #4134: no longer freeze when clicking browse in aux import dialog

src/main/java/org/jabref/gui/mergeentries/MergeEntries.java
And another threading issue fixed...
----
=> Fix not on javafx thread exception in "generate data from doi"

src/main/java/org/jabref/JabRefGUI.java, src/main/java/org/jabref/logic/util/io/FileBasedLock.java, src/main/java/org/jabref/migrations/PreferencesMigrations.java, src/main/java/org/jabref/preferences/JabRefPreferences.java
Since we no longer allow for a customizable look & feel, the migration can also be removed.
----
=> Remove unnecessary look and feel migration

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_zh.properties
----
Fixed: [#4166](https://github.com/JabRef/jabref/issues/4166)
=> Fixed: #4166 add move & rename file

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java, src/main/java/org/jabref/logic/util/io/FileBasedLock.java, src/main/resources/l10n/JabRef_en.properties
Removes confirmation dialogs when renaming or moving files. It is hard to accidentally invoke this action (you have to right click on the file > move/rename) and it is not irreversible. Thus, in my opinion, no confirmation dialog is needed.
----
=> Make it easier to rename and move files

CHANGELOG.md, src/main/java/org/jabref/model/entry/AuthorListParser.java, src/test/java/org/jabref/model/entry/AuthorListParameterTest.java
We have fixed an issue where author list parser can't generate bibtexkey for <B>Chinese author.</B> [#4169](https://github.com/JabRef/jabref/issues/4169)
<h2>Before fix: </h2>
The default bibtexkey is [author][year], actually it only shows [year]. Obviously the [author] can't be generated normally. <br/>
<h2>After fix: </h2>
Now it can generate bibtexkey for <B>Chinese author.</B><br/>
We have used correct logic so that if author's name is not Chinese name, it won't do anything.
=> Fix author list parser (#4169)

CHANGELOG.md, src/main/java/org/jabref/gui/filelist/LinkedFilesEditDialogViewModel.java
Fixes #4241 
Attached files were only made relative before if you hit the browse button
----
=> Fix attach file does not relativize file path

src/main/java/org/jabref/JabRefGUI.java, src/main/java/org/jabref/gui/Base.css, src/main/java/org/jabref/gui/GUIGlobals.java, src/main/java/org/jabref/gui/actions/ActionFactory.java, src/main/java/org/jabref/gui/customjfx/CustomJFXPanel.java, src/main/java/org/jabref/gui/documentviewer/DocumentViewer.fxml, src/main/java/org/jabref/gui/entryeditor/EntryEditor.css, src/main/java/org/jabref/gui/entryeditor/EntryEditor.fxml, src/main/java/org/jabref/gui/entryeditor/fileannotationtab/FileAnnotationTab.fxml, src/main/java/org/jabref/gui/fieldeditors/BibtexKeyEditor.fxml, src/main/java/org/jabref/gui/fieldeditors/IdentifierEditor.fxml, src/main/java/org/jabref/gui/fieldeditors/JournalEditor.fxml, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.fxml, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java, src/main/java/org/jabref/gui/fieldeditors/OwnerEditor.fxml, src/main/java/org/jabref/gui/fieldeditors/UrlEditor.fxml, src/main/java/org/jabref/gui/groups/GroupTree.fxml, src/main/java/org/jabref/gui/help/AboutDialog.css, src/main/java/org/jabref/gui/help/AboutDialog.fxml, src/main/java/org/jabref/gui/help/AboutDialogView.java, src/main/java/org/jabref/gui/icon/IconTheme.java, src/main/java/org/jabref/gui/util/BaseDialog.java, src/main/java/org/jabref/gui/util/DefaultFileUpdateMonitor.java, src/main/java/org/jabref/gui/util/ThemeLoader.java, src/main/java/org/jabref/gui/util/component/Tag.fxml, src/main/java/org/jabref/styletester/StyleTester.fxml, src/main/java/org/jabref/styletester/StyleTesterMain.java, src/main/java/org/jabref/styletester/StyleTesterView.java
Fixes #4202 and a few other small style related issues. I also created a little new app that make it simple to test the display of JavaFX controls. As of now, I only added a lot of buttons in different styles and states:
Please merge instead of squashing the commits.
----
=> Fix style issues in about dialog

external-libraries.txt, src/main/java/org/jabref/gui/exporter/SaveDatabaseAction.java, src/main/java/org/jabref/gui/importer/actions/GUIPostOpenAction.java
Fixes #4192 
Comments mentioning Spin were removed or replaced with a mention that BackgroundTask is now used.
----
=> Remove Spin comments

src/main/java/org/jabref/gui/Base.css, src/main/java/org/jabref/styletester/StyleTester.fxml, src/main/java/org/jabref/styletester/StyleTesterMain.java
Fixes part of https://github.com/JabRef/jabref/issues/4190: checkboxes are now shown properly.
----
=> Fix display of checkboxes

src/main/java/org/jabref/gui/journals/ManageJournalAbbreviations.css, src/main/java/org/jabref/gui/journals/ManageJournalAbbreviations.fxml, src/main/java/org/jabref/gui/journals/ManageJournalAbbreviationsView.java, src/main/java/org/jabref/gui/journals/ManageJournalAbbreviationsViewModel.java
Make it possible to close the "Manage journal abbreviations" dialog using the x-button. Fixes part of https://github.com/JabRef/jabref/issues/4190.
=> Fix "Manage journal abbreviations" dialog

build.gradle
I pinned an errorprone dependency to version 2.3.1, which is the latest version as of August 17, 2018.  As it stands in the master branch, the plugin net.ltgt.errorprone creates a configuration of errorprone that automatically updates to the latest version, which is meant to be overridden.  I overrode that configuration by explicitly creating it in build.grade, and then I added the dependency to the configuration necessary to pin the version.  build.gradle executes the plugins first, but then overrides the configuration afterward.  The issue is [#4176](https://github.com/JabRef/jabref/issues/4176).
=> Pin errorprone dependency to specific version
