build.gradle, src/main/java/org/jabref/model/database/shared/DBMSType.java
Suports all newer mysql versions
https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-versions.html
----
=> Update mysql driver to 8.0.12

src/main/java/org/jabref/gui/BasePanel.java, src/main/java/org/jabref/gui/PreviewPanel.java, src/main/java/org/jabref/gui/openoffice/StyleSelectDialog.java, src/main/java/org/jabref/gui/preftabs/PreviewPrefsTab.java
Followup from #3765. I discovered an NPE with the bibdatabasecontext in the NewDroppedFileHandler.
The reason is that the move files cleanup operation requires a non null bibdatabasecontext and when calling the preview panel from the preferences, no context was there.
----
=> Fix NPE with bibdatabasecontext in preview style dialog

src/main/java/org/jabref/gui/actions/BibtexKeyPatternAction.java, src/main/java/org/jabref/gui/bibtexkeypattern/BibtexKeyPatternDialog.java, src/main/java/org/jabref/gui/copyfiles/CopyFilesDialogView.java, src/main/java/org/jabref/gui/documentviewer/DocumentViewerView.java, src/main/java/org/jabref/gui/errorconsole/ErrorConsoleView.java, src/main/java/org/jabref/gui/externalfiletype/ExternalFileTypeEditor.java, src/main/java/org/jabref/gui/help/AboutDialogView.java, src/main/java/org/jabref/gui/journals/ManageJournalAbbreviationsView.java, src/main/java/org/jabref/gui/keyboard/KeyBindingsDialogView.java, src/main/java/org/jabref/gui/util/BaseDialog.java
Followup from #4253  in the Bibtex key pattern panel there was an exception thrown if you had defined custom entry types or used biblatex mode.
@Super-Tang In your PR you used a fixed size for the number of labels and buttons. However, as it is possible in JabRef to customize the entry types, e.g. add new ones, the size is no longer fixed. Therefore if the number of entry types was > 19 the array threw an exception.
I now used the size of the entry type list to setup the array size and wrapped it in a Scroll Pane
Edit// I set colspan to remaining, so it uses all space
----
=> convert bibtexkeypatterndlg to javafx as well

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/EntryEditor.fxml
=> Add minimal height for entry editor

src/main/java/org/jabref/gui/BasePanel.java, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/exporter/ExportToClipboardAction.java, src/main/java/org/jabref/gui/maintable/RightClickMenu.java, src/main/resources/l10n/JabRef_en.properties
Fixes #4286  
The content is correctly put, but I can't paste it in Notepad++ or wherever 
----
=> Fix Export to clipbaord action

src/main/java/org/jabref/gui/importer/ImportAction.java
Execute import inspetion dialog in swing thread
Fixes #4296
----
=> Fix freeze on import into current library

CHANGELOG.md, src/main/java/org/jabref/gui/preferences/XmpPrefsTab.java, src/main/java/org/jabref/gui/util/ValueTableCellFactory.java, src/main/resources/l10n/JabRef_en.properties, src/test/java/org/jabref/logic/exporter/XmpExporterTest.java
Fixes #4072 
@koppor  I am not that into the XMP stuff, are those "fields" I can add there bibtexfields which I can exclude from the export? 
Then it would make sense to have a combobox analogous to the Cleanup panel with all fields
Edit// Decided to add the combobox with all fields
----
=> fix loading and storing of XMP Field Exclusions

build.gradle, src/main/java/org/jabref/gui/Base.css, src/main/java/org/jabref/gui/BasePanel.java, src/main/java/org/jabref/gui/DialogService.java, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/worker/VersionWorker.java
Bring back the status line in the following form:
Fixes https://github.com/JabRef/jabref/issues/4223.
Since these notifications have a rather great visual weight, we may revisit some of the existing notifications that are trivial/not useful and remove them. 
As I've learned these things are called snack bars and the notifications toasts. In this sense: 🍻 
----
=> Readd status line in form of a snack bar

build.gradle
add rejection rule for jfoenix 9.x (requires java 9)
merge if green
----
=> update junit to release

src/main/java/org/jabref/gui/preferences/GeneralTab.java, src/main/java/org/jabref/gui/preferences/PreferencesDialog.java
don't override pref size
Quick fix. We definitively need to redesign/rearrange some prefs
Fixes #4322
----
=> Wrap preferences in scrollPane as well

src/main/java/org/jabref/gui/importer/fetcher/WebSearchPane.java
Fixes https://github.com/JabRef/jabref/issues/4330 by making the search button in the web search pane not the default button.
=> Fix that web search pane steals input

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/keyboard/KeyBinding.java, src/main/resources/l10n/JabRef_en.properties
Enhancement presented here [
Fixes #4222 
I have added a new keyboard shortcut for closing the entry editor by using "Ctrl+E".
----
=> Added new keyboard shortcut "ctrl+E" for closing the entry editor. (#4222)

src/main/java/org/jabref/logic/msbib/MSBibConverter.java, src/test/java/org/jabref/logic/exporter/MSBibExportFormatTestFiles.java, src/test/resources/org/jabref/logic/exporter/MsBibExportFormatTest2.xml, src/test/resources/org/jabref/logic/exporter/MsBibExportFormatTest3.xml, src/test/resources/org/jabref/logic/exporter/MsBibExportFormatTest4.xml, src/test/resources/org/jabref/logic/exporter/MsBibExportFormatTest5.xml, src/test/resources/org/jabref/logic/exporter/MsBibExportFormatTest6.xml, src/test/resources/org/jabref/logic/exporter/MsBibLCID.xml, src/test/resources/org/jabref/logic/exporter/MsBibLocationTest.xml
Fix tests
Fix  #4329  
The underlying problem is the same as in #4152 
However, I came up with a workaround for MSOffice. 
1. Getting the original field
2. Check for corporate author (braces start and end)
3. get latex free value
4. Readd braces for corporate 
5. Parse author
The only edgecase which can occur if the entry starts with an author in latex braces and ends with an author in latex braces. That one will probably be interpreted as corporate.
----
=> Fix export of corporate author to MSOffice

src/main/java/org/jabref/JabRefGUI.java, src/main/java/org/jabref/gui/fieldeditors/PersonsEditor.java
Fixes https://github.com/JabRef/jabref/issues/4323 and probably fixes https://github.com/JabRef/jabref/issues/4294 as well.
The reason for the freezes were the pull-request https://bitbucket.org/controlsfx/controlsfx/pull-requests/710. These changes mess up the layout for some reason. The fix is to inject a DecorationPane ourselves directly from the beginning. Although this fix started as a workaround for this bug in controlsfx, I think, we should keep it permanently for performance reasons.
=> Fix freezes in entry editor

src/main/java/org/jabref/gui/SaveOrderConfigDisplay.java, src/main/java/org/jabref/gui/preferences/ExportSortingPrefsTab.java
e83680f18d815ebebc779d239a6eacd8930150fe changed the way the SaveOrderConfig works. These changes caused SaveOrderConfigDisplay to throw IndexOutOfBoundsExceptions when saving the settings. This pull request fixes that issue.
Additionally the RadioButtons allowed the user to select none or multiple order types. This pull request adds them to a ToggleGroup, which prevents these multiselections.
----
This issue was introduced in this release. Should I still add a changlog entry?
=> Fix problems with sort order of exports

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fetcher/ArXiv.java, src/test/java/org/jabref/logic/importer/fetcher/ArXivTest.java
In this PR I wanted to fix the issue from [koppor#328](https://github.com/koppor/jabref/issues/328). 
I simply used existing code in the same file which just takes the identifier at the end of the URL and perform a search.
For example: _https://arxiv.org/abs/1802.01168_ to _1802.01168_
The error dialog does not appear anymore and a new entry is made.
----
=> ArXiv fetcher support http url

src/test/java/org/jabref/logic/exporter/ModsExportFormatTestFiles.java
[#4272](https://github.com/JabRef/jabref/issues/4272)
----
=> Fixed testExportAsModsAndThenImportAsMods

src/main/java/org/jabref/gui/maintable/MainTable.css
Should make it easier to distinguish these icons from the ones that represent values that are already set.
=> Color special column icons in lighter gray on mouse hover

CHANGELOG.md, src/main/java/org/jabref/Globals.java, src/main/java/org/jabref/gui/preferences/AppearancePrefsTab.java, src/main/java/org/jabref/gui/util/ThemeLoader.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/main/java/org/jabref/styletester/StyleTesterMain.java
Add ability to change theme via settings
=> 4130 provide dark theme

.travis.yml
Since checkstyle is already run as part of a separate test suite, there is no need to invoke it in the main test suite.
=> Do not execute checkstyle tasks in main test suite on travis

CHANGELOG.md, src/main/java/org/jabref/gui/icon/InternalMaterialDesignIcon.java
It currently only applies to the Rank menu; the sub-entries were only showing the first star instead of 5 stars
Since `SpecialFieldMenuAction` has been removed and in `RightClickMenu` the following has been removed, the icons are not set correctly anymore.
```
public static void populateSpecialFieldMenu(JMenu menu, SpecialField field, JabRefFrame frame) {
SpecialFieldViewModel viewModel = new SpecialFieldViewModel(field);
menu.setText(viewModel.getLocalization());
menu.setIcon(viewModel.getRepresentingIcon());
for (SpecialFieldValue val : field.getValues()) {
menu.add(new SpecialFieldMenuAction(new SpecialFieldValueViewModel(val), frame));
}
}
```
The new way of working is through `ActionFactory` which uses `setGraphic()` instead:
```
private static void setGraphic(MenuItem node, Action …
```
=> Fix showing multiple icons for one menu entry - fixes #4384

src/main/java/org/jabref/gui/EntryTypeView.java, src/main/java/org/jabref/gui/EntryTypeViewModel.java
When generating an entry from an DOI or similar, the entry was inserted, but the dialog not closed.
Followup from the conversion to javafx
----
=> Fix EntryType dialog not closed after generate button

src/main/java/org/jabref/gui/JabRefFrame.java
#4360 
Now When you click new entry in a right toolbar, it open an extra dialog where user can select a entry type
=> show dialog before creating entry

src/main/java/org/jabref/gui/util/ThemeLoader.java, src/main/java/org/jabref/preferences/JabRefPreferences.java
I notice there is a dark theme in recent commit. So I tried it, and find out an issue that you can not save preference. "Save" button have no response. The issue starts from _Provide access to dark theme in preferences_ (https://github.com/JabRef/jabref/pull/4372). 
The reason is that default value for key "fxTheme" is not set, thus cause a null exception when access this option. Solution is simple, just to set default value "Base.css" for key "fxTheme" in preference.
Finally, I have to say dark theme is a great job. thanks
=> fix "save" button in preference dialog not response

CHANGELOG.md, src/main/java/org/jabref/gui/util/BindingsHelper.java
Fixes [#3312](https://github.com/JabRef/jabref/issues/3112)
The cause of this bug is that the local variable "pseudoClassState" is garbaged by java gc. There is no reference to this variable except an weak one from "bind" function.
Note: groups that autonatically created won't highlight at all, for example the _tag_ group in above gif.  I think this shall be another issue.
=> fixed an issue where corresponding groups are sometimes not highlighted when clicking on entries

src/main/java/org/jabref/gui/util/ThemeLoader.java
If you run the [jar file](https://builds.jabref.org/master/ ) ouside IDE, then an error will be reprted:
> [JavaFX Application Thread] ERROR org.jabref.JabRefMain - Unexpected exception
java.nio.file.FileSystemNotFoundException: null
at com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:171) ~[zipfs.jar:1.8.0_172]
at com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:157) ~[zipfs.jar:1.8.0_172]
at java.nio.file.Paths.get(Paths.java:143) ~[?:1.8.0_172]
at org.jabref.gui.util.ThemeLoader.<init>(ThemeLoader.java:52) ~[JabRef--master--latest.jar:?]
at org.jabref.Globals.startBackgroundTasks(Globals.java:82) ~[JabRef--master--latest.jar:?]
at org.jabref.JabRefMain.start(JabRefMain.java:63) ~[JabRef--master--latest.jar:?]
at …
=> fix java.nio.file.FileSystemNotFoundException and reorganize code

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupNodeViewModel.java
Fixes #3537 by replacing the EventBus subscription by a JavaFX listener.
=> Fix group hit counter when adding entries

src/main/java/org/jabref/gui/actions/GenerateBibtexKeyAction.java
Fixes #4417
The problem was that the GenerateBibtexKeyAction is executed using a TaskExecutor and therefore not run on the FX Thread. Unfortunately the exception was swallowed and not reported.
----
=> Fix generate bibtex key overwrite warning dialog

src/main/java/org/jabref/gui/edit/ReplaceStringViewModel.java, src/main/java/org/jabref/gui/preferences/AppearancePrefsTab.java, src/main/java/org/jabref/logic/integrity/IntegrityMessage.java, src/main/java/org/jabref/model/entry/BibtexString.java, src/main/java/org/jabref/model/entry/identifier/MathSciNetId.java, src/main/java/org/jabref/model/groups/AutomaticKeywordGroup.java, src/main/java/org/jabref/model/groups/AutomaticPersonsGroup.java, src/main/java/org/jabref/model/groups/TexGroup.java, src/main/java/org/jabref/model/metadata/ContentSelectors.java, src/test/java/org/jabref/gui/search/TextFlowEqualityHelper.java
Since @tobiasdiez already proposed the Always Use Braces rule in https://github.com/JabRef/jabref/pull/4387, I just went ahead and fixed the violations in the code.
=> Fix Violations of Always Use Braces

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fileformat/PdfContentImporter.java, src/test/java/org/jabref/logic/importer/fileformat/PdfContentImporterTest.java
Fixes #4422 
The variable formally known as i is a global variable which had -1 after the first run and therefore threw an exception
----
=> Fix ArrayIndexOutOfBoundsException on second pdf import

src/main/java/org/jabref/gui/preferences/EntryEditorPrefsTab.java, src/main/java/org/jabref/gui/preferences/ExternalTab.java, src/main/java/org/jabref/gui/preferences/FileTab.java, src/main/java/org/jabref/gui/preferences/GroupsPrefsTab.java, src/main/java/org/jabref/gui/preferences/ImportSettingsTab.java, src/main/java/org/jabref/gui/preferences/TableColumnsTab.java, src/main/java/org/jabref/gui/preferences/TablePrefsTab.java
Previously multiple radiobuttons in preference menu belonging to the same group were selectable simultaneously. This issue is now fixed on multiple occasions, allowing only one option per group to be selected at the same time. Issue: [#4409](https://github.com/JabRef/jabref/issues/4409)
=> Fixed radiobuttons in preference menu (#4409)

src/main/java/org/jabref/gui/groups/GroupTreeView.java
Fix a bug with drag and drop groups.
Steps to reproduce:
1) select more than groups
2) Move it to another group via drag and drop
Groups not moved into another group if you use drag and drop
=> fix groups drag and drop

.circleci/config.yml, src/main/java/org/jabref/gui/util/ThemeLoader.java
=> Add submodule pull to circle ci and fix theme loading css

CHANGELOG.md, src/main/java/org/jabref/gui/preferences/GeneralTab.java
This patch addresses issue [#4427](https://github.com/JabRef/jabref/issues/4427). Added a call to the existing event handler (which enables/disables the checkbox in response to user clicks) when we set the checkbox value from the preferences.
----
=> Set auto-update checkbox enable/disable when reading preferences

AUTHORS, CHANGELOG.md, src/main/java/org/jabref/gui/shared/SharedDatabaseLoginDialog.fxml, src/main/java/org/jabref/gui/shared/SharedDatabaseLoginDialogView.java, src/main/java/org/jabref/gui/shared/SharedDatabaseLoginDialogViewModel.java, src/main/java/org/jabref/logic/shared/DBMSConnectionProperties.java, src/main/java/org/jabref/logic/shared/prefs/SharedDatabasePreferences.java, src/main/java/org/jabref/model/database/shared/DatabaseConnectionProperties.java, src/main/resources/l10n/JabRef_en.properties, src/test/java/org/jabref/logic/shared/DBMSConnectionTest.java, src/test/java/org/jabref/logic/shared/TestConnector.java
This PR add feature requested in #4464 
----
=> Added feature to add server timezone when connecting to shared database

src/main/java/org/jabref/gui/exporter/SaveDatabaseAction.java
fix issue: #4467 
When you click `save` and there is no database selected. That will act as `save as`.
=> 4467 - fix save button

CHANGELOG.md, src/main/java/org/jabref/logic/integrity/PagesChecker.java, src/test/java/org/jabref/logic/integrity/PagesCheckerBibLatexTest.java
Superseeds the PR #4188 and fixes #4113. Now page ranges like `R2-R5` are considered to be correct.
=> Improve page checker

src/main/java/org/jabref/gui/preferences/TableColumnsTab.java
----
- [ X ] Change in CHANGELOG.md described
- [ X ] Tests created for changes
- [ X ] Manually tested changed features in running JabRef
- [ X ] Screenshots added in PR description (for bigger UI changes)
- [ X ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ X ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
=> Fix button sizes in issue #4437

src/main/java/org/jabref/gui/PreviewPanel.java
Fix #4365 .
I get all tag value and put it in a string.
=> fixed 4365 put html in clipboard

CHANGELOG.md, src/main/java/org/jabref/gui/exporter/ExportCommand.java, src/main/java/org/jabref/gui/exporter/ExportToClipboardAction.java, src/main/java/org/jabref/preferences/JabRefPreferences.java
Add feature to store last selected export file type, and preselect that type the next time the dialog to export to clipboard is fired.
=> Add preselect last used export format in export to clipboard dialog

CHANGELOG.md, src/main/java/org/jabref/gui/BasePanel.java, src/main/java/org/jabref/gui/externalfiles/FindFullTextAction.java, src/main/resources/l10n/JabRef_en.properties
Fix fulltext document linking from Quality menu
=> fix-for-issue-4489

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupNodeViewModel.java, src/main/java/org/jabref/gui/groups/GroupTreeView.java, src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java, src/main/java/org/jabref/gui/util/ViewModelTreeTableCellFactory.java, src/main/java/org/jabref/model/groups/GroupTreeNode.java
=> Fixes that renaming a group did not change the group name in the interface

src/main/java/org/jabref/gui/autocompleter/AutoCompletionStrategy.java, src/main/java/org/jabref/preferences/PreferencesService.java
Some interfaces were with the access modifier public these were removed since they are redundant
=> Cleanup interfaces

src/main/java/org/jabref/gui/preferences/PreferencesDialog.css, src/main/java/org/jabref/gui/preferences/PreferencesDialog.java
:christmas_tree: As promised: A small christmas PR improving the styling of the new Java FX preferences dialog.  :christmas_tree:
Before:
After:
----
=> improve styling of preferences side menu

src/main/java/org/jabref/model/entry/BibEntry.java
This is the followup for https://github.com/JabRef/jabref/pull/4554, which removed the usage of this constructor. This PR also deleted this code.
=> Delete the Deprecated BibEntry Constructor

src/main/java/org/jabref/gui/maintable/MainTable.java
fix performance issues
I had to remove the code which sets sorting at startup of the columns, that kills the performance.
Mabye it helps to store it directly in the column objects
Will investigate this further.
----
=> Don't set column sort type at startup

src/main/java/org/jabref/gui/EntryType.fxml
replace border pane with vbox
Fixes #4593
----
=> Fix overlapping font in adding new ID entry type dialog

src/main/java/org/jabref/gui/PreviewPanel.java
Proposed solution for #4580:
I have added a previewStyle variable to check when the preview style changes.
From my observation, the layout is updated every time tabs are switched or preview styles are cycled through. With the addition of a variable, these 2 situations can be differentiated to print out the notification more appropriately.
----
=> Add a variable to track the change in preview style

src/main/java/org/jabref/gui/EntryTypeView.java
Fixes #4600.
Sets text field on focus at the end of initialization by running the javafx thread.
----
=> Enable default cursor for new entry

src/main/java/org/jabref/gui/actions/NewSubLibraryAction.java, src/main/java/org/jabref/gui/actions/StandardActions.java, src/main/java/org/jabref/gui/auximport/AuxParserResultViewModel.java, src/main/java/org/jabref/gui/auximport/FromAuxDialog.fxml, src/main/java/org/jabref/gui/auximport/FromAuxDialog.java, src/main/resources/l10n/JabRef_en.properties
=> Convert "From Aux file" dialog to JavaFX

src/main/java/org/jabref/gui/DuplicateResolverDialog.java, src/main/java/org/jabref/gui/DuplicateSearch.java, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/bibtexkeypattern/ResolveDuplicateLabelDialog.java, src/main/java/org/jabref/gui/importer/ImportInspectionDialog.java
=> Convert DuplicateResolverDialog to javafx

src/main/java/org/jabref/gui/BasePanel.java
Add the following autosave actions to your database:
```
@Comment{jabref-meta: databaseType:biblatex;}
@Comment{jabref-meta: saveActions:enabled;
date[normalize_date]
pages[normalize_page_numbers]
all-text-fields[latex_to_unicode]
title[html_to_unicode]
;}
```
search for something and press <kbd>ctrl+space</kbd> to open autocomplete popup. Enter sth like \emph{dictionary} in the title field and press save.
No errros.
Noted this in #4616 
----
=> Try to fix not on FX thread for search and autocomplete

.gitignore, snap/snapcraft.yaml
This picks up from the previous snap (#4615),
it adds the explicit build architectures, the removable-media plug (not autoconnected) and disables tests on gradlwe build
=> snap: disable tests build, add removable media and specify architectures

src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/PreviewPanel.java, src/main/java/org/jabref/gui/actions/ShowPreferencesAction.java, src/main/java/org/jabref/gui/preferences/PreferencesDialog.java, src/main/java/org/jabref/gui/preferences/PreviewPrefsTab.java, src/main/java/org/jabref/preferences/PreviewPreferences.java, src/main/resources/l10n/JabRef_en.properties
Remove obsolete swing stuff
Create proper javafx binding
Fixes #4621
Fixes #4622 
Fixes #4570
I fixed and tuned the copypreview stuff.
Copy Preview copies the HTML formatted stuff for usage in email:
Purified text for non html:
```
Incollection (Akerkar:)
Akerkar, R.
Processing Big Data for Emergency Management 
Smart Technologies for Emergency Response and Disaster Management, 
IGI Global, 
, 144-166 
```
When all styles get removed from the right side, the default "Preview" style is added back again to prevent divide by zero exception
Fix another issue where the Preview style is not set correctly
----
=> Fix NPE and not on FX Thread in PreviewPrefs Tabs

build.gradle, src/test/java/org/jabref/gui/externalfiles/AutoSetFileLinksUtilTest.java, src/test/java/org/jabref/gui/fieldeditors/LinkedFileViewModelTest.java, src/test/java/org/jabref/gui/journals/ManageJournalAbbreviationsViewModelTest.java, src/test/java/org/jabref/gui/util/FileDialogConfigurationTest.java, src/test/java/org/jabref/logic/cleanup/CleanupWorkerTest.java, src/test/java/org/jabref/logic/cleanup/MoveFilesCleanupTest.java, src/test/java/org/jabref/logic/cleanup/RenamePdfCleanupTest.java, src/test/java/org/jabref/logic/exporter/BibTeXMLExporterTestFiles.java, src/test/java/org/jabref/logic/exporter/CsvExportFormatTest.java, src/test/java/org/jabref/logic/exporter/DocBook5ExporterTest.java, src/test/java/org/jabref/logic/exporter/ExporterTest.java, src/test/java/org/jabref/logic/exporter/HtmlExportFormatTest.java, src/test/java/org/jabref/logic/exporter/MSBibExportFormatTestFiles.java, src/test/java/org/jabref/logic/exporter/ModsExportFormatTest.java, src/test/java/org/jabref/logic/exporter/ModsExportFormatTestFiles.java, src/test/java/org/jabref/logic/exporter/MsBibExportFormatTest.java, src/test/java/org/jabref/logic/exporter/XmpExporterTest.java, src/test/java/org/jabref/logic/integrity/IntegrityCheckTest.java, src/test/java/org/jabref/logic/protectedterms/ProtectedTermsListTest.java, src/test/java/org/jabref/logic/protectedterms/ProtectedTermsLoaderTest.java, src/test/java/org/jabref/logic/util/io/CiteKeyBasedFileFinderTest.java, src/test/java/org/jabref/logic/util/io/FileUtilTest.java, src/test/java/org/jabref/logic/xmp/XmpUtilWriterTest.java
Fixes: #4641 
Removed the TempDirectory extension from junit-pioneer with the built-in extension of junit 5.4
----
=> Fix for issue 4641: Remove usage of TempDirectory extension from junit-pioneer

src/main/java/org/jabref/logic/integrity/EditionChecker.java, src/main/resources/l10n/JabRef_en.properties, src/test/java/org/jabref/logic/integrity/IntegrityCheckTest.java
=> [#4591] Add Integrity check for books with edition reported as 1

src/main/java/org/jabref/gui/groups/GroupDescriptions.java, src/main/java/org/jabref/gui/groups/GroupDialog.java, src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_en.properties
fixes [#4610](https://github.com/JabRef/jabref/issues/4610)
- Changed GroupDialog description Node to TextFlow
- GroupDialog is no longer resizable
- Changed the layout of the GroupDialog window to be more horizontal
- OK Button is only enabled after some input
----
=> fixes #4610. Changed the way the GroupDialog description is displayed. 

src/main/java/org/jabref/logic/exporter/BibTeXMLExporter.java
This exception showed-up quite often in the Azure Analytics. 
----
=> Catch NumberFormatException in BibTeXML exporter

src/main/java/org/jabref/logic/importer/fileformat/BibtexParser.java, src/main/resources/l10n/JabRef_en.properties
Based on http://discourse.jabref.org/t/warnings-by-jabref-start/1532, in which a user (rightfully) complained that the error message is not very helpful.
----
=> Improve parser warnings

src/main/java/org/jabref/logic/bibtex/LatexFieldFormatter.java
Quick fix to help locating Errors like the one reported in the forum:
http://discourse.jabref.org/t/problems-getting-started/1537/13?u=siedlerchr
----
=> Improve error mesage on save, add current field content

src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/customentrytypes/CustomizeEntryAction.java, src/main/java/org/jabref/gui/customentrytypes/EntryTypeCustomizationDialog.java
As discussed in the devcall, we might temporarily remove (or disable) some of the old Swing dialog instead of converting them directly to JavaFX. The "Customize entry types" dialog is one of these dialogs, because it is not yet clear how entries should be displayed in the entry editor (especially how to group fields) and these decisions directly translate to changes to the customization dialog.
After merging, an issue for the re-implementation should be opened.
----
=> Temporarily remove "Customize entry types"

CHANGELOG.md, src/main/java/org/jabref/logic/formatter/Formatters.java, src/test/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGeneratorTest.java
As I currently wanted to have a possibility to have "Capitalized Shorttitles" in my bibtex keys I reused the already existing `CapitalizeFormatter`, `TitleCaseFormatter` and `SentenceCaseFormatter` as "modifiers" to be used also for the BibtexKeyGenerator.
This implements #1506 and is more flexible as the solution developed by @oscargus at the time in  #1894 as it can be applied to all other fields and not only to titles. 
----
=> Adding additional modifiers to be used in bibtex key generator

src/main/java/org/jabref/gui/preferences/ImportSettingsTab.java, src/main/java/org/jabref/migrations/PreferencesMigrations.java, src/test/java/org/jabref/migrations/PreferencesMigrationsTest.java
Remove Display Array
Add migration
Fixes #4724
----
=> Fix default import format pattern

src/main/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGenerator.java, src/main/java/org/jabref/logic/bibtexkeypattern/BracketedPattern.java, src/test/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGeneratorTest.java, src/test/java/org/jabref/logic/bibtexkeypattern/MakeLabelWithDatabaseTest.java
Fixes #4709.
Clean up the author value in `BracketedPattern` after it is retrieved from the `BibEntry`.
----
=> Fix: bibkey generated does not handle diacritics

src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/bibtexkeypattern/BibtexKeyPatternDialog.java
Follow-up of #4666 and #4707: Menu entry "BibTeX Key patterns" is calling a library specific dialog to set key patterns. The global key patterns are managed using "Options" -> "Preferences".
Thus: Moving it to "library" menu:
(Another minor addition: setting title of dialog which was empty before)
----
- ~~Change in CHANGELOG.md described~~
- ~~Tests created for changes~~
- ~~Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)~~
=> Move library specific key pattern dialog call to library menu

src/main/java/org/jabref/logic/shared/DBMSProcessor.java, src/main/java/org/jabref/logic/shared/DBMSSynchronizer.java, src/test/java/org/jabref/logic/shared/DBMSProcessorTest.java
Optimize fetching data from database
=> Optimize data fetching

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupDialog.java
Changes the title of Group Dialog to "Add subgroup" from "Edit group" when we select Add subgroup option.
----
=> Changes the title of Group Dialog to Add subgroup when adding a new subgroup

CHANGELOG.md, src/main/java/org/jabref/gui/Base.css, src/main/java/org/jabref/gui/groups/GroupTree.css
Fixes [#4583](https://github.com/JabRef/jabref/issues/4583)
----
=> Modifications to improve contrast of UI elements

src/main/java/org/jabref/JabRefMain.java, src/main/java/org/jabref/gui/remote/JabRefMessageHandler.java, src/main/java/org/jabref/logic/remote/client/RemoteClient.java, src/main/java/org/jabref/logic/remote/server/RemoteListenerServer.java
Fixes #4023 (multiple instances possible) and should fix #4481 by reducing the timeout (thus JabRef does no longer waits seconds if a proxy prevents us from connecting to localhast). Surpasses #4460.
----
=> Improve Remote messaging

src/main/java/org/jabref/gui/preferences/PreferencesFilterDialog.fxml, src/main/java/org/jabref/gui/preferences/PreferencesFilterDialog.java
Add a search box in show preferences window to allow users to filter
preference options.
Resolves #1019
----
=> Feature: implement search filter in show preferences

src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java, src/main/java/org/jabref/model/util/OptionalUtil.java
=> [#4306] Disable renaming

src/main/java/org/jabref/gui/BasePanel.java
Fixes #4762. The problem was that the NotificationPane was hiding the entry editor/preview.
----
=> Fix opening of entry editor

src/main/java/org/jabref/gui/DuplicateResolverDialog.java, src/main/java/org/jabref/gui/PreviewPanel.java, src/main/java/org/jabref/gui/collab/EntryAddChangeViewModel.java, src/main/java/org/jabref/gui/search/SearchResultFrame.java
Fixes #4785
init method was accessing the database field before it was initialized.
Fixes #4786
Pass a new BibDatabsecontext()
----
=> Fix NPE in Duplicate Resolver Dialog

src/main/java/org/jabref/gui/BasePanel.java, src/main/java/org/jabref/gui/exporter/SaveDatabaseAction.java
Fixes the remaining problems mentioned in https://github.com/JabRef/jabref/pull/4784#pullrequestreview-216419250:
- table is now working again in case a new file is opened (also fixes https://github.com/JabRef/jabref/issues/4793)
- in case preferences are saved entry editor is working properly again
- external changes are now also detected in case file name has changed due to "Save As"
-- 
- ~~Change in CHANGELOG.md described~~
- ~~Tests created for changes~~
- ~~Screenshots added in PR description (for bigger UI changes)~~
- ~~Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)~~
=> Followup of #4784 - fixes remaining issues of #4762

CHANGELOG.md, src/main/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGenerator.java, src/test/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGeneratorTest.java
Moved cleanKey to the field case, so it not clears the wanted special characters. Fix for [#4767](https://github.com/JabRef/jabref/issues/4767).
So now [author]-[year] or [author]:[year] are resolving the keys Kilian-2019 or Kilian:2019.
----
=> Fix do not clear wanted special characters

src/main/java/org/jabref/gui/JabRefFrame.java
Fixes #4789
The issue was when the tab is closed by clicking 'x' it did not call
the method `closeTab()` which handles the closing of backup and
autosave manager.
----
=> Fix closing of library not handling backup and autosave manager shutdown

src/main/java/org/jabref/gui/groups/GroupNodeViewModel.java
Fixes issue [#4679](https://github.com/JabRef/jabref/issues/4679)
This PR fixes the first issue. I could not reproduce the second issue. The item count should now be updated correctly.
The problem was because of the Listener not getting notified when changes were being made. This was due to the weak listener which was attached to ObservableList returned by `databaseContext.getDatabase().getEntries()`.
https://stackoverflow.com/questions/44341400/whats-the-purpose-of-fxcollections-unmodifiableobservablelist
The only case where this PR might not work is when we are dealing with a library in which there are no groups other than the All Entries [#4441](https://github.com/JabRef/jabref/issues/4441). That is because the group being utilized in the line …
=> Item Count in a group updated correctly

src/main/java/org/jabref/gui/entryeditor/SourceTab.java
Fixes #4764
The issue was, `storeSource()` method is called when entry is out of focus, however, if another entry is selected then `currentEntry` is updated to that and `storeSource()` is called with the previous `codeArea` but updating it in the second entry, thus causing a duplication.
Fix was to pass the entry as another argument to `storeSource()`. 
----
=> Fix removing entries when source-code-field is out of focus

src/main/java/org/jabref/logic/cleanup/RenamePdfCleanup.java
closes #4817 
Because field changes must be done in the JavaFX thread, i put the field change in a callable to be executed by the JavaFX thread.
This issue might arise for other cleanup tasks as well.
----
=> Put renaming of file entries in JavaFX thread for cleanup

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fileformat/RisImporter.java, src/test/resources/org/jabref/logic/importer/fileformat/RisImporterTest3.bib, src/test/resources/org/jabref/logic/importer/fileformat/RisImporterTest6.bib, src/test/resources/org/jabref/logic/importer/fileformat/RisImporterTest8_date.bib, src/test/resources/org/jabref/logic/importer/fileformat/RisImporterTest8_date.ris
Now the first valid year is taken into account. Previously the year was overwritten when another field containing year was found.
Adjusted the tests to reflect the new behavior. This required adjusting the month field in the test files
Fixes #4816
----
=> Fix overwriting of date in RIS import

src/main/java/org/jabref/gui/preferences/PreferencesDialog.java
After every search clear the selection of tabs and select the first
tab in the tabsList.
Fixes #4824
----
=> Select the first tab which matches the search query in preferences window

src/main/java/org/jabref/gui/util/BaseDialog.java
All buttons in custom dialogs react now also on <kbd>enter</kbd>. (The default behavior <kbd>space</kbd> in JavaFX is not affected by this change.)
Fixes #4820 
----
=> All buttons in custom dialogs react on enter

src/main/java/org/jabref/gui/groups/GroupTreeView.java
Adds a delay to the group expansion action. The delay is currently 1 second and only expands the group.
Is there also a need to collapse the item, if an user drags over it after a specific period?
Closes #4674 
----
=> Adds a delay to the group expansion

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupDialog.java, src/main/java/org/jabref/logic/auxparser/DefaultAuxParser.java, src/main/java/org/jabref/logic/importer/util/GroupsParser.java, src/main/java/org/jabref/model/groups/TexGroup.java, src/test/java/org/jabref/logic/exporter/GroupSerializerTest.java, src/test/java/org/jabref/logic/importer/util/GroupsParserTest.java
Fixes #4735. 
Catch file not found exception and handle non existing aux files gracefully.
----
=> Fix parser exception when loading tex-groups with non-existing file

CHANGELOG.md, src/main/java/org/jabref/logic/layout/LayoutEntry.java, src/main/java/org/jabref/logic/layout/format/NameFormatter.java, src/main/java/org/jabref/logic/layout/format/NotFoundFormatter.java, src/test/java/org/jabref/logic/layout/LayoutTest.java
=> Fix custom name formatters

src/main/java/org/jabref/gui/BasePanel.java, src/main/java/org/jabref/gui/FXDialogService.java, src/main/java/org/jabref/gui/JabRefDialogService.java, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/actions/CopyBibTeXKeyAndLinkAction.java, src/main/java/org/jabref/gui/worker/CitationStyleToClipboardWorker.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/main/resources/l10n/JabRef_en.properties
=> Improve Snackbar Dialogs for Copy to Clipboard Menu

src/main/java/org/jabref/gui/preferences/ExternalTab.java, src/main/java/org/jabref/gui/push/PushToApplication.java, src/main/java/org/jabref/gui/push/PushToApplicationAction.java, src/main/java/org/jabref/gui/push/PushToApplicationSettings.java, src/main/java/org/jabref/gui/push/PushToApplicationSettingsDialog.java, src/main/java/org/jabref/gui/push/PushToEmacsSettings.java, src/main/java/org/jabref/gui/push/PushToLyx.java, src/main/java/org/jabref/gui/push/PushToLyxSettings.java, src/main/java/org/jabref/gui/push/PushToVimSettings.java, src/main/resources/l10n/JabRef_en.properties
Replace Runnable with BackgroundThread in Push
If I'm not mistaken this was the last swing dialog! 🙌 
----
=> Convert PushToApp Settings to javafx

src/main/java/org/jabref/gui/externalfiles/FindFullTextAction.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java
Solution proposal for #4854 
In `FindFullTextAction`, `Task` is now used instead of `BackgroundTask` to be able to show a progress dialog which shows the progress for searching files online.
Furthermore, the functionality for downloading a file in `LinkedFileViewModel` is split into `download` and `prepareDownloadTask` to be able to define a custom onSucess-action for the background task. This is used in `FindFullTextAction` to add the downloaded file to the entry instead of the URL.
The functionality provided by `LinkedFileViewModel.dowload` remains as it is, so it does not affect the download of a single file via the EntryEditor.
----
=> Improve full text search for several files

src/main/java/org/jabref/gui/maintable/PersistenceVisualStateTable.java, src/main/java/org/jabref/gui/preferences/TableColumnsTab.java
Fixes #4579
Store column widths as integer 
----
=> Store column widths as integer

src/main/java/org/jabref/gui/libraryproperties/LibraryPropertiesDialogView.java, src/main/java/org/jabref/gui/libraryproperties/LibraryPropertiesDialogViewModel.java, src/main/java/org/jabref/logic/auxparser/DefaultAuxParser.java
=> Fix Some Codacy Code Convention Issues

src/main/java/org/jabref/gui/groups/GroupDialog.java
Fixes #2419
Allow resizing of the Edit/Add Group dialog:
----
=> Make Group dialog resizable

src/main/java/org/jabref/gui/preferences/TableColumnsTab.java
Fixes #4911 
This is just a hotfix to make the preferences dialog working again.
I will create another PR for converting the TableColunns preferences tab to proper MVVM structure with fxml and a new improved layout.
----
=> Quick fix for error when opening preferences

src/main/java/org/jabref/model/entry/BibEntry.java, src/test/java/org/jabref/model/entry/BibEntryTest.java
=> Fixes throwing an exception when 'id' field is present in bib file

src/main/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGenerator.java, src/test/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGeneratorTest.java
Apostrophe character removed from KEY_ILLEGAL_CHARACTERS in BibtexKeyGenerator
----
=> Fix for the issue #4912

src/main/java/org/jabref/gui/preferences/AdvancedTab.java, src/main/java/org/jabref/gui/preferences/PreferencesDialog.css, src/main/java/org/jabref/gui/preferences/PreferencesDialog.fxml, src/main/resources/l10n/JabRef_da.properties, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_el.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_in.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_no.properties, src/main/resources/l10n/JabRef_pt_BR.properties, src/main/resources/l10n/JabRef_ru.properties, src/main/resources/l10n/JabRef_tl.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_vi.properties, src/main/resources/l10n/JabRef_zh.properties
Minors improvements in Preferences->advancedTab UI :
I deleted some useless rows, used a wrap text for the text (it was 3 labels), and changed the separators location a bit.
-----
BEFORE :
-----
AFTER :
----
=> UI Preferences->advanced tab optimization : separators and text modification

CHANGELOG.md, src/main/java/org/jabref/model/entry/Author.java, src/main/java/org/jabref/model/entry/AuthorListParser.java, src/test/java/org/jabref/model/entry/AuthorListParameterTest.java, src/test/java/org/jabref/model/entry/AuthorTest.java
Fixes #4864. The author class added an additional space when converting "A O" to the dotted version "A. O.".
----
=> Improve author parsing

CHANGELOG.md, src/main/java/org/jabref/gui/openoffice/OOBibBase.java, src/main/java/org/jabref/logic/openoffice/OOBibStyle.java
Fixes #4932 
When an entry got removed a NPE complaining about an empty database was thrown because of some weird UnkownBibTexEntry thing.
Now the correct BibEntryNotFound  Exception is thrown showing the problematic reference mark
----
=> Throw BibEntryNotFound exception in case entry is no longer present 

src/main/java/org/jabref/gui/importer/actions/OpenDatabaseAction.java, src/main/java/org/jabref/gui/menus/FileHistoryMenu.java
Fixes #4940
On Windows 10 I could not reproduce the original exception, but I'm very convinced that I found the threading culprit
----
=> Fix threading issue with opening from recent libraries

src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java, src/main/java/org/jabref/logic/externalfiles/LinkedFileHandler.java
Fixes #4844 
As usual the situation was not as easy as it seemed to be in #4887. I reused now the existing renaming logic for "renaming to suggested filename" which performs some more checks like not to overwrite existing files and also takes the "file directory" settings into account.
Thus, this should fix the remaining problem mentioned in #4844.
----
=> fixes remaining issues in #4844

src/main/java/org/jabref/gui/shared/SharedDatabaseLoginDialog.fxml
Fixed the tab order used in the database login dialog to make it natural.
Fixes [#4954](https://github.com/JabRef/jabref/issues/4954).
=> Fixed the tab order in the database login dialog

CONTRIBUTING.md
Added a link to the current open issues with tags 'good first issue' to the beginning of CONTRIBUTING.md to help new contributors find a way to get started.
----
=> Add link to good first issues in CONTRIBUTING.md

src/main/java/org/jabref/gui/externalfiles/FindFullTextAction.java
Fixes #4490 Prevent KeyCollion with empty urls
=> fix-for-issue-4490: Download fulltext for multiple entries

src/main/java/org/jabref/gui/maintable/MainTable.java, src/main/java/org/jabref/gui/maintable/MainTableDataModel.java
Fixes #4886
Renenables sorting.
Tried a bit around and could not find any side issue so far.
----
=> Remove UI ThreadList for maintable as it prevents sorting in maintable

build.gradle, src/main/java/org/jabref/logic/importer/IdBasedParserFetcher.java, src/main/java/org/jabref/logic/importer/SearchBasedParserFetcher.java, src/main/java/org/jabref/logic/importer/fetcher/AstrophysicsDataSystem.java, src/main/java/org/jabref/logic/importer/fetcher/IsbnFetcher.java, src/main/java/org/jabref/logic/importer/fetcher/IsbnViaChimboriFetcher.java
Here is a correction for #4968: it bumps Jsoup from 1.11.3 to 1.12.1 and, also, it switchs Jsoup's StringUtil for JabRef's StringUtil in all files that used it.
----
=> Bump Jsoup to 1.12.1 and switch Jsoup's StringUtil for JabRef's StringUtil

CONTRIBUTING.md
Moved basic steps of the workflow into a numbered listed to clearly express the process, and moved helpful links into specific steps to better associate links with the workflow.
----
=> Reformat Understanding the basics section of CONTRIBUTING.md

src/main/java/org/jabref/gui/externalfiles/FindFullTextAction.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditorViewModel.java, src/main/java/org/jabref/gui/filelist/AttachFileAction.java, src/main/java/org/jabref/gui/filelist/LinkedFilesEditDialogViewModel.java, src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java, src/main/java/org/jabref/logic/externalfiles/LinkedFileHandler.java, src/test/java/org/jabref/gui/fieldeditors/LinkedFileViewModelTest.java
If we already have a filetype we use that instead of relying on the autodetection
Fixes #4913
----
=> Fix downloading pdf produces html as extension

CHANGELOG.md, src/main/java/org/jabref/cli/JabRefCLI.java, src/main/resources/l10n/JabRef_en.properties
Now in the CLI help text, arguments and descriptions have been rewritten for fixing, simplifying, and detailing them better.
It fixes issue #2016.
----
=> Fix command line help text

CHANGELOG.md, src/main/java/org/jabref/gui/preferences/AdvancedTab.java, src/main/java/org/jabref/gui/preferences/GeneralTab.java, src/main/java/org/jabref/gui/preferences/PreferencesDialog.java, src/main/java/org/jabref/gui/search/GlobalSearchBar.java, src/main/java/org/jabref/gui/search/rules/describer/ContainsAndRegexBasedSearchRuleDescriber.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/main/resources/l10n/JabRef_en.properties
fixes #3599 - conflicts with #4971 
I realized, talking about changes without presenting a possible solution is just lame.
What do you think?
Sorry about these ugly commit-msgs. I promise improvement.
----
=> Extended Hints - Alternative to #4971

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/EntryEditor.css
Now JabRef uses the same typography for the two menus to change entry type (and for the tooltip).
It fixes #4977.
----
=> Resize different fonts changing entry type

src/main/java/org/jabref/gui/actions/ActionFactory.java, src/main/java/org/jabref/gui/entryeditor/EntryEditor.fxml, src/main/java/org/jabref/gui/entryeditor/EntryEditor.java
The entry-editor showed a slightly smaller icon for the GenerateBibtexKey-Button, this bug also had an effect on the display of icon size in #4991
The GenerateBibtexKey-Button is now a Button like every other Button in FXML, the ActionObject was put into a standard-FXML-method. Everything works, including Undo and asking before overwriting.
----
=> Fix icon size - the second

CHANGELOG.md, src/main/java/org/jabref/gui/filelist/AttachFileAction.java
Now the "Attach file" dialog, in the right-click menu for an entry, starts on the working directory instead of the user's main directory. It is the same behavior as when adding a file from the entry editor.
It solves [#4995](https://github.com/JabRef/jabref/issues/4995)
----
=> Fix the 'Attach file' dialog for starting on the user's main directory

src/main/java/org/jabref/logic/util/TestEntry.java
One liner to have also a DOI available in the entry to test the preview function.
@noMicrosoftBuhtz any more suggestions what should be added?
----
=> Adding DOI to test entry - fixes #5013

build.gradle, src/main/java/org/jabref/JabRefLauncher.java, src/main/java/org/jabref/gui/util/ThemeLoader.java
See https://github.com/beryx/badass-jlink-plugin/issues/61
=> fix jlink task

src/main/java/org/jabref/gui/errorconsole/ErrorConsoleViewModel.java
Right now users often forget to change the title to something reasonable.
----
=> Remove "automatic bug report" title

CHANGELOG.md, src/main/java/org/jabref/gui/customizefields/CustomizeGeneralFieldsDialogViewModel.java, src/main/java/org/jabref/gui/entryeditor/EntryEditorTabList.java, src/main/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGenerator.java
As asked, the character '-' was included on the error message, also we included other characters that were not being mentioned on the message. We tried to remove the character '-' from KEY_ILLEGAL_CHARACTERS and KEY_UNWANTED_CHARACTERS on BibtexKeyGenerator.java, but we did not know if it would be a good idea because it violates some tests.
About the order of the tabs, we removed the alphabetical ordering so now it is following the order defined when the tabs are created on the "Set up general fields" option.
This PR fixes #5019.
----
=> "Set up general fields" character check not correct & alphabetical ordering

src/main/java/org/jabref/gui/importer/ImportEntriesDialog.java, src/main/java/org/jabref/gui/importer/ImportEntriesViewModel.java
created background task for the work done in org/jabref/gui/importer/ImportEntriesViewModel.java:68
=> Duplicate check on import should be run in background Task #4963

src/main/java/org/jabref/Globals.java
Just realized that our shutdown problems might also be caused by the Unirest library:
> Exiting an application
Unirest starts a background event loop and your Java application won't be able to exit until you manually shutdown all the threads by invoking:
Unirest.shutdown();
Maybe worth a try?
=> Shutdown Unirest workers

src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/externalfiles/AutoLinkFilesAction.java
Executing the created task would have been helpful... 🤦‍♂ 
Fixes #5023
----
=> Fix automaticalls set file links task not runinng

src/main/resources/l10n/JabRef_ru.properties
Should fix this bug when select Russian translation
```
java.lang.IllegalStateException: It is not allowed that the toReplace string: '<tt>author=smith and title=electrical</tt>' does not exist in the original string
at org.jabref.gui.util.TooltipTextUtil.splitReplace(TooltipTextUtil.java:92)
at org.jabref.gui.util.TooltipTextUtil.formatToTexts(TooltipTextUtil.java:62)
at org.jabref.gui.search.GlobalSearchBar.setHintTooltip(GlobalSearchBar.java:291)
...
```
----
=> Fix Russian translation

src/main/java/org/jabref/gui/groups/GroupTreeView.java, src/main/java/org/jabref/logic/util/Version.java
Noticed this when doing analysis
Close version socket
----
=> Refactor for loop to stream in groupTree

src/main/java/org/jabref/gui/ClipBoardManager.java, src/main/java/org/jabref/gui/maintable/MainTable.java
Fixes #5043.
Encodes and decodes data with UTF-8.
=> Preserve encoding while copy and pasting in maintable

src/main/java/org/jabref/gui/copyfiles/CopyFilesAction.java, src/main/java/org/jabref/gui/copyfiles/CopyFilesDialogView.java, src/main/java/org/jabref/gui/copyfiles/CopySingleFileAction.java, src/main/java/org/jabref/gui/externalfiles/FindFullTextAction.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditorViewModel.java, src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/main/java/org/jabref/preferences/PreferencesService.java, src/main/resources/l10n/JabRef_en.properties, src/test/java/org/jabref/gui/fieldeditors/LinkedFileViewModelTest.java
=> Add copy linked files action to contextmneu in general tab

src/main/java/org/jabref/logic/importer/fileformat/RisImporter.java, src/test/resources/org/jabref/logic/importer/fileformat/RisImporterTest3.bib, src/test/resources/org/jabref/logic/importer/fileformat/RisImporterTestDate1.1.bib, src/test/resources/org/jabref/logic/importer/fileformat/RisImporterTestDate1.1.ris, src/test/resources/org/jabref/logic/importer/fileformat/RisImporterTestDate1.2.bib, src/test/resources/org/jabref/logic/importer/fileformat/RisImporterTestDate1.2.ris
This pull resquest fixes issue [#4816](https://github.com/JabRef/jabref/issues/4816).
When importing RIS files Jabref checks for date fields (Y1,PY,DA and Y2) and uses the first one it finds. The problem is that Y2 refers to access date, DA in most cases is a generic date, and PY is the publication year(reliable field)*. 
https://github.com/JabRef/jabref/blob/40600b35420e688ee5d5758224717b484ad34f84/src/main/java/org/jabref/logic/importer/fileformat/RisImporter.java#L196-L203
We couldn't find references to Y1('primary date'?). However, as already cited in [#4816](https://github.com/JabRef/jabref/issues/4816), and by doing some exports we found Y1 to be  PY's synonym, furthermore, when PY received a higher priority than Y1, some tests cases didn't pass as there were a missing month field …
=> Fixes RIS' data field

src/main/java/org/jabref/logic/l10n/Language.java, src/main/java/org/jabref/logic/l10n/Localization.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/test/java/org/jabref/logic/l10n/LanguageTest.java, src/test/java/org/jabref/logic/l10n/LocalizationTest.java
=> add Polish language

src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/entryeditor/LatexCitationsTab.java, src/main/java/org/jabref/gui/entryeditor/LatexCitationsTabViewModel.java, src/main/java/org/jabref/gui/texparser/ParseTexDialogViewModel.java, src/main/java/org/jabref/logic/texparser/DefaultTexParser.java, src/main/resources/l10n/JabRef_en.properties
Patch for solving some issues commented in: https://github.com/JabRef/jabref/pull/5155#issuecomment-517240431
=> LaTeX integration latest changes

src/main/java/org/jabref/logic/exporter/TemplateExporter.java, src/test/java/org/jabref/logic/exporter/DocBook5ExporterTest.java, src/test/resources/org/jabref/logic/exporter/Docbook5ExportFormat.xml
Fix a bug that appeared on `DocBook5ExporterTest` (`testPerformExportForSingleEntry`) since the last commit in the master branch (https://github.com/JabRef/jabref/commit/4b39b78e4afcd6c36b385f5c46f1d9a4eac2e29b).
The point is that the `<biblioset>` node is not contained in the export file. Also, I have used `normalizeWhitespace()` and `ignoreComments()` methods.
I have added the [WIP] mark because I still want to check if there is any trouble with the exporter. Any help about this?
=> Fix fail on testPerformExportForSingleEntry from DocBook5ExporterTest

src/main/java/org/jabref/gui/collab/EntryChangeViewModel.java, src/main/java/org/jabref/gui/mergeentries/FetchAndMergeEntry.java, src/main/java/org/jabref/gui/mergeentries/MergeEntries.java, src/main/java/org/jabref/model/database/BibDatabase.java
because natural order will require same types of the enum
Followup from  #5148
----
=> Fix enum class cast error in TreeSet by specifying an explicit comparator

src/main/java/org/jabref/gui/cleanup/FieldFormatterCleanupsPanel.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java, src/main/java/org/jabref/gui/texparser/CitationsDisplay.java, src/main/java/org/jabref/gui/util/ViewModelListCellFactory.java, src/main/java/org/jabref/model/texparser/Citation.java
This patch solves the issue detected by @calixtus in https://github.com/JabRef/jabref/issues/5002#issuecomment-519985132
Moreover:
----
Before:
After:
----
=> Fix tooltips in CitationsDisplay

src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java, src/main/resources/l10n/JabRef_en.properties
Fiyes #5152 
Fix issue with a missing tooltip and icon in the color group column. I used DEFAULT_GROUP_ICON from JabRefICons to supplement the missing icon.
=> Fix issue 5152, tooltip and icon added to group cell

src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java
Refs #5152 
One of my groupcolors is white, which made it hard to see in the jabref window.
I added a thin grey border, so one can see even white groups on white background.
Also I made the area, the user can put his mousepointer in to show the tooltip, a little wider (3 pixels were to small)
left before, right after
ready to review
----
=> Border for group color indicator and some space for tooltip

src/main/java/org/jabref/gui/texparser/ParseTexDialogViewModel.java, src/main/resources/l10n/JabRef_en.properties
This fixes one problem of JabRef trying to parse a directory, which it has no permission for.
Instead a generic exception dialog with a StackTrace, a more useful error message is displayed to the users.
=> Fix Permissions of LaTeXintegration

src/main/java/org/jabref/logic/texparser/DefaultTexParser.java, src/test/java/org/jabref/logic/texparser/DefaultTexParserTest.java
We added a few more citation commands: `autocite`, `Autocite`, `blockcquote`, and `textcquote`.
This PR fixes #5194.
----
=> Add citation commands to TexParser

src/main/java/org/jabref/logic/importer/fetcher/IsbnFetcher.java, src/main/java/org/jabref/logic/importer/fetcher/IsbnViaOttoBibFetcher.java, src/main/java/org/jabref/logic/net/URLDownload.java, src/test/java/org/jabref/logic/importer/WebFetchersTest.java, src/test/java/org/jabref/logic/importer/fetcher/IsbnViaChimboriFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/IsbnViaEbookDeFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/IsbnViaOttoBibFetcherTest.java
Fetcher does not return bibtex data in plain text, instead it's part of an html text area
Fix ISBN tests
Update user agent
Follow up from #5125
----
=> Implement ottobib fetcher

build.gradle, src/main/java/org/jabref/logic/texparser/DefaultTexParser.java, src/test/java/org/jabref/logic/texparser/DefaultTexParserTest.java, src/test/resources/org/jabref/logic/texparser/iso-8859-1.tex, src/test/resources/org/jabref/logic/texparser/iso-8859-15.tex, src/test/resources/org/jabref/logic/texparser/utf-8.tex
We added a file encoding checker for parsing LaTeX files.
This PR adds `tika.parsers` (from `org.apache.tika`) dependency.
----
=> Add encoding checker for parsing LaTeX files

src/main/java/org/jabref/gui/EntryTypeView.java
=> Fix exception when adding new entry

docs/adr/0000-use-markdown-architectural-decision-records.md, docs/adr/0004-use-mariadb-connector.md, docs/adr/index.md, docs/adr/template.md, external-libraries.txt
Follow up to https://github.com/JabRef/jabref/pull/4746#issuecomment-471418686.
Small updates:
- Update MADR to 2.1.2
- Fix `external-libraries.txt`
=> Add ADR-0004

CHANGELOG.md, src/main/java/org/jabref/logic/layout/LayoutEntry.java, src/test/java/org/jabref/logic/layout/LayoutTest.java
Export filter layout `\begin{...}` had [support for AND/OR operators](http://help.jabref.org/en/CustomExports#conditional-output), this PR adds per-field negation via `!`, see unit tests for example usage.
----
=> Allow negation (`!`, NOT operator) in \\begin{...} conditionals

src/main/java/org/jabref/gui/mergeentries/DiffHighlighting.java, src/main/java/org/jabref/logic/journals/AbbreviationParser.java, src/main/java/org/jabref/logic/journals/JournalAbbreviationLoader.java
If we create journal abbrev files via the JabRef, they are saved in UTF-8.
So it makes sense to use this as default encoding. Also see https://github.com/JabRef/jabref/issues/5133.
=> Use UTF-8 as default encoding for files

src/main/java/org/jabref/gui/preferences/FileTabViewModel.java, src/main/java/org/jabref/preferences/JabRefPreferences.java
Use getName when storing the file directory key
----
=> fix bug where main file directory is not set correctly

src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/actions/ActionFactory.java, src/main/java/org/jabref/gui/actions/Actions.java, src/main/java/org/jabref/gui/actions/JabRefAction.java, src/main/java/org/jabref/gui/actions/OldCommandWrapper.java, src/main/java/org/jabref/gui/actions/OldDatabaseCommandWrapper.java, src/main/java/org/jabref/gui/actions/Sources.java
Fix #4629
----
-  distinguish the user action between menu and button
-  reuse the Acitons class to add enum to the description of user action
=> Fix for issue 4629

build.gradle, docs/adr/0005-fully-support-utf8-only-for-latex-files.md, docs/adr/index.md, src/main/java/org/jabref/logic/texparser/DefaultTexParser.java, src/test/java/org/jabref/logic/texparser/DefaultTexParserTest.java
This fixes https://github.com/JabRef/jabref/pull/3421#issuecomment-524532832
=> Switch from tika-parsers to tika-core

src/main/java/org/jabref/model/bibtexkeypattern/AbstractBibtexKeyPattern.java
Fixes 
```
src\main\java\org\jabref\model\bibtexkeypattern\AbstractBibtexKeyPattern.java:60: error: [CollectionIncompatibleType] Argument 'type' should not be passed to this method; its type String is not compatible with its collection's type argument EntryType
data.remove(type);
^
(see https://errorprone.info/bugpattern/CollectionIncompatibleType)
```
=> Removed unused method

src/main/java/org/jabref/gui/BasePanel.java, src/main/java/org/jabref/gui/BasePanelMode.java, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/actions/Actions.java, src/main/java/org/jabref/gui/actions/StandardActions.java, src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/entryeditor/FieldsEditorTab.java, src/main/java/org/jabref/gui/keyboard/KeyBinding.java, src/main/java/org/jabref/gui/preview/PreviewPanel.java, src/main/resources/l10n/JabRef_en.properties, src/test/resources/testbib/complex.bib
Supersedes https://github.com/JabRef/jabref/pull/4976
=> Preview in Entryeditor

src/main/java/org/jabref/gui/cleanup/FieldFormatterCleanupsPanel.java
=> Fix exception when adding field formatter in 'Cleanup entries' dialog

.travis.yml
When getting JabRef close to a release, waiting 30 minutes, until all TravisCI tests pass is not amusing. OpenJDK is open source, OracleJDK is some closed source distribution. I would vote for testing JabRef with OpenJDK only. In case OracleJDK makes something worse, user will complain then. I think, however, it is very unlikely, that OracleJDK will fail when OpenJDK will not.
=> Remove testing on OracleJDK - we stick to OpenJDK only

.gitignore, .idea/runConfigurations/JabRef_Main.xml, build.gradle
1. Add the following compiler arguments for the `JabRef.main` module:
```
--patch-module test=fastparse_2.12-1.0.0.jar --patch-module test2=fastparse-utils_2.12-1.0.0.jar --patch-module test3=sourcecode_2.12-0.1.4.jar --add-exports javafx.controls/com.sun.javafx.scene.control=org.jabref --add-exports org.controlsfx.controls/impl.org.controlsfx.skin=org.jabref --add-exports javafx.graphics/com.sun.javafx.scene=org.controlsfx.controls --add-exports javafx.graphics/com.sun.javafx.scene.traversal=org.controlsfx.controls --add-exports javafx.graphics/com.sun.javafx.css=org.controlsfx.controls --add-exports javafx.controls/com.sun.javafx.scene.control.behavior=org.controlsfx.controls --add-exports javafx.controls/com.sun.javafx.scene.control=org.controlsfx.controls --add-exports …
```
=> Make it easier to compile with intellj

build.gradle
Fixes #5278 
There were a few more not allowed access from within the `com.jfoenix` dependency. But adding the lines with further jvm options from this pull request to the `build.gradle` in the `run` task prevents the Exceptions.
Is this the proper way to adress this or is there a better way to fix such issues?
----
=> added add-opens options

eclipse.gradle
This is the only change (plus the manual configuration)
----
=> Make JabRef work in eclipse

src/test/resources/org/jabref/logic/importer/fileformat/RisImporterTest3.bib, src/test/resources/org/jabref/logic/importer/fileformat/RisImporterTestDate1.1.bib, src/test/resources/org/jabref/logic/importer/fileformat/RisImporterTestDate1.2.bib
This change fixes issue [#5116 ](https://github.com/JabRef/jabref/issues/5116), where we have some bib files in which the month is written as {#jul#} rather than jul. This commit fixes this issue.
----
- [ V ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
=> unifying month format across all bib files

build.gradle
Reverts https://github.com/JabRef/jabref/commit/ba60cbe18640611e7d7f0986314c82049668c5f6. According to https://github.com/java9-modularity/gradle-modules-plugin#using-the-application-plugin this is the correct way to specify the main class name.
@davidemdot what was the reason for your change?
----
=> Fix main class name

config/checkstyle/checkstyle.xml, src/main/java/org/jabref/gui/util/RecursiveTreeItem.java, src/main/java/org/jabref/logic/bst/BibtexCaseChanger.java, src/main/java/org/jabref/logic/bst/BibtexWidth.java, src/main/java/org/jabref/logic/bst/VM.java, src/main/java/org/jabref/logic/importer/fetcher/MrDLibFetcher.java, src/main/java/org/jabref/logic/importer/fileformat/BibtexParser.java, src/main/java/org/jabref/logic/importer/fileformat/IsiImporter.java, src/main/java/org/jabref/logic/layout/StringInt.java, src/main/java/org/jabref/logic/layout/format/AuthorLastFirstAbbreviator.java, src/main/java/org/jabref/logic/shared/event/UpdateRefusedEvent.java, src/main/java/org/jabref/logic/xmp/XmpUtilShared.java, src/main/java/org/jabref/model/database/BibDatabaseContext.java, src/main/java/org/jabref/model/entry/Month.java, src/main/java/org/jabref/model/entry/event/FieldChangedEvent.java, src/main/java/org/jabref/model/entry/identifier/DOI.java, src/main/java/org/jabref/model/entry/identifier/Eprint.java
=> Add checkstyle for JavaDoc and fix related issues

CHANGELOG.md, src/main/java/org/jabref/model/entry/types/BiblatexEntryTypeDefinitions.java, src/main/java/org/jabref/model/entry/types/BibtexEntryTypeDefinitions.java, src/main/java/org/jabref/model/entry/types/StandardEntryType.java
issue #5223 
Add @Software and  @Dataset entrytype as an option in the Biblatex and Bibtex. Add fields eventitle, eventdate and venue to @unpublished entry type. I used the MISC set of fields to supplement Software and DataSet, couldn't find documentation about specific fields that should be included in @Software and @DataSet entry type. 
----
=> Issue #5223

snap/snapcraft.yaml
will require bionic now as base
@LyzardKing  It would be cool if you could help testing it
----
=> Update snapcraft to java 11

snap/snapcraft.yaml
This is a WIP to solve #5298 
----
=> Add gtk3 support

.gitignore, snap/plugins/x_gradle.py, snap/snapcraft.yaml
added a custom gradle plugin with the new build/run commands
added the gnome platform to use gtk3
added __pycache__ to .gitignore to avoid committing python cache to git repo
Built locally jabref installs and runs (with limited testing...)
I imported my local library, and opened pdfs for now..
Do not merge yet since I need to still test adding the themes (I get some errors in the terminal, but it should be an easy fix)
----
=> snap: Add custom gradle plugin

src/main/java/module-info.java
As we are not providing a JabRef library, we don't need to export anything. This should also resolve all these warnings shown in the IDE.
@calixtus This one is for you ;-).
----
=> Remove module exports for JabRef

CHANGELOG.md, build.gradle, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/groups/GroupTreeView.java, src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java
Use JavaFX binding instead of a listener to update the global state manager. That seems to work more reliable and fixes a bunch of issues. In particular, fixes #3142  and fixes #4441.
Moreover, I fixed an error that was thrown when interacting with the toolbar (missing open statement but we were using reflection...).
----
=> Use binding to update global state manager

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupNodeViewModel.java, src/main/java/org/jabref/gui/groups/GroupTreeView.java, src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java, src/main/java/org/jabref/gui/keyboard/KeyBindingsDialogView.java, src/main/java/org/jabref/gui/util/ViewModelTreeTableCellFactory.java
Fixes #5327. The problem was that `getTreeTableRow.getItem()` in `ViewModelTreeTableCellFactory` still returned the old item (and not the new one passed as method argument to `updateItem`).
Since I was already looking at the code, this PR also fixes #3112 that improves the coloring after an entry was added to the group. Also fixes #2857 (at least I couldn't replicate it anymore).
----
=> Improve group coloring and item count

build.gradle, src/main/java/org/jabref/gui/groups/GroupDialog.java
Fix another of these nice module export errors (this time when opening the groups dialog). Moreover, fixed that the dialog was empty when editing an automatic group.
----
=> Fix group edit dialog

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/menus/FileHistoryMenu.java
Fixes #5334 
dialogService object was null, because the FileHistoryMenu class is initialized before the ctor of JabRef frame creates the dialog service object
----
=> Fix NPE when opening a non existing file from the recent files menu

buildSrc/src/main/groovy/org/jabref/build/xjc/XjcTask.groovy
As mentioned in gitter chat there were currently some encoding issues with the XJC generation of java files based on XSDs.
I've added the encoding parameter to our XJC gradle task with default value of UTF8.
----
- ~~[ ] Change in CHANGELOG.md described~~
- ~~[ ] Screenshots added in PR description (for bigger UI changes)~~
=> fix encoding issues in xjc code generation

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefFrame.java
Fixes #5348 by using JavaFX windows instead of awt windows.
----
=> Fix exception when closing JabRef

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/EditorTextArea.java, src/main/java/org/jabref/gui/fieldeditors/EditorTextField.java, src/main/java/org/jabref/gui/fieldeditors/TextInputControlBehavior.java, src/main/java/org/jabref/gui/fieldeditors/UrlEditor.java
As explained in https://github.com/JabRef/jabref/issues/5254#issuecomment-526588221 it is no longer possible to customize the context menu items, because the classes related to the text field behavior are not accessible. Thus, instead I simply copied the relevant code from openjdk. Pretty ugly workaround... Fixes #5254 and refs https://github.com/javafxports/openjdk-jfx/issues/583.
Moreover, I removed the custom tab handling because it is now working as expected (i.e. #2902 is fixed in Java 9+).
----
=> Bring back the context menu

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupDialog.java, src/main/java/org/jabref/gui/groups/GroupNodeViewModel.java, src/main/java/org/jabref/gui/icon/IconTheme.java, src/main/java/org/jabref/preferences/JabRefPreferences.java
Now groups have a dark gray instead of white as their default color. Fixes #4868.
----
=> Fix default group color

CHANGELOG.md, src/main/java/org/jabref/gui/util/BindingsHelper.java
Fixes #5022. Problem was that the pseudo-class was not initialized correctly but was only triggered upon changes.
----
=> Fix group color when scrolling

eclipse.gradle
Improve eclipse module path loading
----
=> [WIP] Improve Eclipse config

CHANGELOG.md, src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java, src/test/java/org/jabref/logic/openoffice/OOBibStyleTest.java, src/test/resources/testbib/complex.bib
Shows multiple colored bars if the entry belongs to more than one group (with color). Implements #4574.
----
=> Show more than one group color bar

src/main/java/org/jabref/JabRefGUI.java
We now show the window first, and then load the last edited files. This does not really lead to an improvement of performance, but the user gets a quicker visual feedback.
----
=> Show window before loading files

src/main/java/org/jabref/preferences/JabRefPreferences.java, src/main/java/org/jabref/preferences/PreviewPreferences.java
Fix for #5369
problem should in theory not happen as always a correct size should be stored - however, if for example CSL styles are not loaded properly the mentioned exception in #5369 might occur.
To prevent this upon creating the preview prefs now the stored cycle position is now compared to the actual list of previews before being set. 
----
- ~~[ ] Screenshots added in PR description (for bigger UI changes)~~
=> Fix for #5369 - fallback to 0 in case stored preview cycle pos does no longer exist

build.gradle
In my understanding generating two installers with different versions and same --win-upgrade-uuid should uninstall another version during installation, i.e. this is needed to have a proper upgrade instead of a parallel installation of two JabRef versions.
----
=> Add UUID for upgrading

eclipse.gradle
I may need to add some tweaks as well
----
=> Fix eclipse javafx module access 

.github/workflows/deployment.yml, build.gradle
Actually the CSL styles are not properly loaded into the build artifacts due to missing usage of submodules.
I needed to revert 3fbe0a2b57340f03d7d1271eeeb30a061d724134 with fetch limiting as this is breaking the submodule  usage (see https://github.com/JabRef/jabref/commit/baa47ff95f13764f6ecb9f9ab38762f56752c342/checks?check_suite_id=252636752) - however, as far as I understood this limitation is nonetheless not necessary as the problem referred to by @Siedlerchr in #5364 was only the temporary problem in the java setup action.
New build is now containing the files again (and is 14MB bigger ;-))
----
=> Checkout submodule

CHANGELOG.md, src/main/java/org/jabref/gui/BasePanel.java, src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/entryeditor/EntryEditorTab.java, src/main/java/org/jabref/gui/entryeditor/FieldsEditorTab.java, src/main/java/org/jabref/gui/preview/PreviewPanel.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/main/java/org/jabref/preferences/PreviewPreferences.java
Okay... this should be working again now. However, without the CSL styles working (see #5246) it's a bit hard to check. ;-) 
Fixes https://github.com/JabRef/jabref/issues/5221
----
- ~~[ ] Screenshots added in PR description (for bigger UI changes)~~
=> Reenable prevcycle

CHANGELOG.md, src/main/java/org/jabref/logic/bibtex/BibEntryWriter.java, src/test/java/org/jabref/logic/bibtex/BibEntryWriterTest.java
Fixes #5359 
Serialization of `OrFields` was not implemented properly as the currently written field was not stored correctly.
----
- ~~ Screenshots added in PR description (for bigger UI changes) ~~
- ~~Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)~~
=> Fix 5359: Writing of Editor field is duplicated

CHANGELOG.md, src/main/java/org/jabref/gui/util/UiThreadList.java
The problem was that `sourceChanged` was invoked asynchronous and thus the information in the change event could be obsolete if another thread changed the underlying list in the meantime. Solution: run `sourceChanged` on the JavaFX thread but synchronously.
Fixes #5169.
----
=> Fix exception when merging entries

scripts/syncLang.py
Fixes https://github.com/JabRef/jabref/issues/3573.
=> Sync lang fix

build.gradle, src/main/java/module-info.java, src/test/java/module-info.test, src/test/java/org/jabref/logic/importer/WebFetchersTest.java
Replace outdated reflection library with [classgraph](https://github.com/classgraph/classgraph) library
Fixes part of #5226 
----
=> Renenable WebFetchers test

build.gradle, src/main/java/org/jabref/gui/logging/ApplicationInsightsAppender.java, src/main/java/org/jabref/gui/logging/GuiAppender.java
Logging still does not work and there are a few error messages when starting JabRef. Reported these at https://issues.apache.org/jira/browse/LOG4J2-2690?focusedCommentId=16949986&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16949986.
Will merge nonetheless to have at least a working build again.
----
=> Upgrade to latest log4j snapshot

build.gradle
Should fix the problem mentioned in https://github.com/JabRef/jabref/pull/5406#issuecomment-541297450
----
=> Remove mods folder in application image

src/main/java/org/jabref/gui/util/ThemeLoader.java
Fixes the error message
> ERROR ThemeLoader Could not watch css file for changes jrt:/org.jabref/org/jabref/gui/Base.css
when starting JabRef.
----
=> Fix error message related to themeloader

.github/workflows/deployment.yml
We (I) forgot that snapcraft needs to run from the docker image..
The same applies to the push command.
The settings can be applies outside, but the push command should be run in docker.
Should it be just one `docker run` with both the build and push commands?
It shouldn't make much difference...
----
=> Run snapcraft push from docker image

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/FieldsEditorTab.java
Fixes #5084. The entry editor was very aggressive and stole the focus from the search bar or from the main table. This lead to problems like #5084 where users overwrite the contents of the entry while doing a search. Moreover, it made it impossible to navigate between entries using the arrow keys in the main table. Both of these issues are fixed now.
----
=> Fix cursor jump

build.gradle
[ #5428](https://github.com/JabRef/jabref/issues/5428) - Issue this PR solves
Gradle was warning about deprecated feature usage. Logs show jacoco append to be the feature that is deprecated.From my understandind the propery is currently ignored.
Removed the Jacoco append property from build.gradle and builds don't throw any deprecation warnings anymore.
The append property in Jacoco is meant to write to the same coverage file. But as mentioned in this [issue](https://github.com/gradle/gradle/issues/5269) setting it to true broke the build caching capability. So starting Gradle 5.0 a breaking change was introduced where they did away with the append property. The default behavior was set to behave as if append is initially false to enable build caching and then append is set to true before …
=> Remove jacoco append property

src/main/java/org/jabref/JabRefGUI.java, src/main/java/org/jabref/gui/BasePanel.java, src/main/java/org/jabref/gui/JabRefFrame.java
----
(Partially) fixes issue https://github.com/JabRef/jabref/issues/5362
As requested by @tobiasdiez in the issue, I delegated the initialization of the auto completer to a background thread, to improve performance during start up.
I also moved the parsing process of the bib files into separate background tasks, which should speed up the start up of the GUI significantly (especially for a large amount of bib files to load).
=> Performance improvements for GUI start up

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/importer/ImportCommand.java
Fixes #5447
----
--> not testable with unit tests
--> not needed
=> Fix nullpointer on import

build.gradle
This reverts a change introduced by a bot without even mentioning it in the commit message. https://github.com/JabRef/jabref/commit/4add3167c918dc2b6c33f55a5a8aff70cb5f2bed#diff-c197962302397baf3a4cc36463dce5eaR39
I'd argue that quite often we don't want to see the full stack trace of Gradle. The motivating example for this was checking the outdated dependencies. We do have a error message for this, `There are outdated dependencies in build.gradle!\n Run ./gradlew dependencyUpdates to see which`, but the stacktrace still appeared and distracted from the normal error message.
=> Disable stacktrace on error

build.gradle, buildres/linux/copyright, buildres/linux/desktop.properties, buildres/linux/jabref-JabRef.desktop, buildres/linux/postrm
An error in the postrm file could prevent reinstalls
Remove the associations file and set in .desktop
(Avoid having another extra file for a single line declaration)
Manually set license/copyright for deb (rpm in gradle):
(The parsing of the license.md file is not working consistently)
----
=> Fix postrm in deb

CHANGELOG.md, src/main/java/org/jabref/gui/importer/ImportEntriesDialog.java, src/main/java/org/jabref/gui/importer/fetcher/WebSearchPaneViewModel.java, src/main/java/org/jabref/gui/util/BindingsHelper.java, src/main/java/org/jabref/gui/util/ViewModelListCellFactory.java
Fixes #5277 and fixes #5035. The problem was in both cases that the list view reuses nodes when scrolling (instead of creating new ones).
----
=> Fix highlight issues for lists

README.md
Grammar fixes
- your and own creates tautology
- preposition was missing in thousands scientist
----
=> (Grammar Fixes) Update README.md

CHANGELOG.md, src/main/java/org/jabref/gui/openoffice/StyleSelectDialogView.java, src/main/java/org/jabref/logic/openoffice/OOBibStyle.java
In addtion, dsplay correct layout for article and book
Fixes  #5452 
TODO: Add documentation issue
----
=> Mark OOSTyle as invalid if no defaultStyle

CONTRIBUTING.md
Fixes the issues found by [markdown-lint](https://github.com/DavidAnson/markdownlint).
=> lint CONTRIBUTING.md

src/main/java/org/jabref/gui/importer/fetcher/WebSearchPaneViewModel.java, src/main/java/org/jabref/logic/importer/WebFetchers.java
----
The list gets sorted in WebFetchers.getSearchBasedFetchers before 
Therefore its not necessary to sort it again.
=> Remove unnecessary sort

src/main/java/org/jabref/cli/ArgumentProcessor.java, src/main/java/org/jabref/gui/importer/fetcher/WebSearchPaneViewModel.java, src/main/java/org/jabref/logic/importer/FulltextFetchers.java, src/main/java/org/jabref/logic/importer/WebFetchers.java, src/test/java/org/jabref/logic/importer/FulltextFetchersTest.java, src/test/java/org/jabref/logic/importer/WebFetchersTest.java, src/test/java/org/jabref/logic/importer/fetcher/FulltextFetcherTest.java
**Follow Up PR for #5470** 
Refactored SortedList to SortedList
=> Refactor to sorted set

src/main/java/org/jabref/Globals.java
The former filename does not exist, the updated file being referred does contain the initialization of JabRefPreferences.
If the previous name is kept, new contributors could potentially be confused when looking for the file.
I do not think this change qualifies as *notable*, therefore I did not include it in the CHANGELOG.md, it is just a correction to a comment. No tests were created either.
----
=> Amend the reference to JabRefReferences initialization

CHANGELOG.md, src/main/java/org/jabref/gui/BasePanel.java, src/main/java/org/jabref/gui/maintable/MainTable.java
Fixes #5460
Select the first entry in the main table, and opens entry editor
for the same. This action is performed on the application thread.
----
=> Open entry editor by default on start-up

src/main/java/org/jabref/logic/importer/fetcher/CrossRef.java
Fixes #5485 
Changed the query parameter `query.title` (which is deprecated) to
`query.bibliographic`.
----
=> Fix deprecated CrossRef Rest API Parameter

snap/snapcraft.yaml
Update the snap to keep the confinement enabled
when using the jabfox extension.
=> snap: Add browser proxy for confined browser integration

CHANGELOG.md, src/main/java/org/jabref/model/cleanup/FieldFormatterCleanups.java, src/main/java/org/jabref/model/entry/BibEntryTypesManager.java, src/test/java/org/jabref/logic/exporter/BibtexDatabaseWriterTest.java
The save actions and/or customized entry types were not serialized alphabetically. This lead to constant changes when used with version control systems.
----
=> Fix metadata serialization order

CHANGELOG.md, src/main/java/org/jabref/gui/Base.css, src/main/java/org/jabref/gui/BasePanel.java, src/main/java/org/jabref/gui/maintable/MainTable.java, src/main/java/org/jabref/gui/maintable/SmartConstrainedResizePolicy.java
Looks now as follows:
Fixes https://github.com/JabRef/jabref/issues/5374.
----
=> Bring back the scrollbars

CHANGELOG.md, src/main/java/org/jabref/gui/Dark.css, src/main/java/org/jabref/gui/mergeentries/MergeEntries.css
fixes: #5516
The colour of the textfields in the Merge dialogue was set to black, I set that to `-fx-light-text-color` (#9aa3af) in MergeEntries.css
No need for documentation update.
Tested manually on local environment.
Open to suggestion for test cases. 😄 
PS: Forgive me if I missed something, this is my first PR to a relatively large project ✨ 
----
Changes:
=> Fix text colour in Merge dialogue

CHANGELOG.md, src/main/java/org/jabref/logic/xmp/DublinCoreExtractor.java, src/main/java/org/jabref/logic/xmp/XmpPreferences.java, src/main/java/org/jabref/logic/xmp/XmpUtilWriter.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/test/java/org/jabref/logic/exporter/XmpExporterTest.java
Fixes #5449. Was caused by wrapping a set of fields in a treeset without specifying the comparator.
----
=> Fix XMP null error

CHANGELOG.md, src/main/java/org/jabref/JabRefMain.java, src/main/java/org/jabref/cli/ArgumentProcessor.java, src/main/java/org/jabref/gui/importer/ImportCustomEntryTypesDialog.fxml, src/main/java/org/jabref/gui/importer/ImportCustomEntryTypesDialog.java, src/main/java/org/jabref/gui/importer/ImportCustomEntryTypesDialogViewModel.java, src/main/java/org/jabref/gui/importer/actions/CheckForNewEntryTypesAction.java, src/main/java/org/jabref/migrations/CustomEntryTypePreferenceMigration.java, src/main/java/org/jabref/model/entry/BibEntryTypesManager.java, src/test/java/org/jabref/logic/exporter/BibtexDatabaseWriterTest.java, src/test/java/org/jabref/model/entry/BibEntryTypesManagerTest.java
Fixes #5332. Problem was that the dialog was shown whenever the library contained customized entry types, even if the customizations were equal to the customization stored in the global preferences. A bit of refactoring/renaming along the way.
----
=> Remove empty customization warning

buildres/linux/postinst, buildres/linux/postrm
Fixes #5502 
I'd keep the branch open, to enable test  builds of deb/rpm packages while we fix the last jpackage options.
=> Fix destination for jabref mozilla json

src/main/java/org/jabref/gui/ClipBoardManager.java
=> Fix a bug that threw a NPE when using middle mouse click on Windows

docs/adr/0007-human-readable-changelog.md, docs/adr/README.md
I read the CHANGELOG and wondered, why we did not always prefix each line with `We`. I found https://github.com/JabRef/jabref/issues/2277 - and thought, I should write it down.
I am not fully satisfied; however: better than nothing.
=> Add ADR-007: Provide a human-readable changelog

src/main/java/org/jabref/gui/importer/ImportEntriesDialog.java
Fixes #5508 
I added a condition to see if only one entry is being imported.
If the condition adheres -> mark the entry as selected.
----
=> Making importing a single file easier (Issue #5508)

src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/entryeditor/FileDragDropPreferenceType.java
Fixes #5546 
The setting only applies to the entry editor. The maintainable is still differentiating between the DND Modifiers as implemented in the linked PR
@koppor  
Refs #3765
----
=> Make entry editor DND behave as specified in settings

src/main/java/org/jabref/gui/openoffice/StyleSelectDialogViewModel.java
=> Select newly added jstyle in table to prevent exception

CHANGELOG.md, src/main/java/org/jabref/gui/BasePanel.java, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/auximport/FromAuxDialog.java, src/main/java/org/jabref/gui/dialogs/AutosaveUIManager.java, src/main/java/org/jabref/gui/exporter/SaveDatabaseAction.java, src/main/java/org/jabref/gui/importer/NewDatabaseAction.java, src/main/java/org/jabref/gui/importer/actions/OpenDatabaseAction.java, src/main/java/org/jabref/gui/maintable/MainTable.java, src/main/java/org/jabref/gui/shared/SharedDatabaseUIManager.java, src/main/java/org/jabref/logic/shared/DBMSSynchronizer.java, src/main/resources/l10n/JabRef_en.properties
As discussed in #5555 this PR removes some obsolete notifications and additionally removes notifications during autosave.
I have also removed the strings from the language file, however, I was not sure if this was correct?
----
=> Fix 5555 status popups

src/main/java/org/jabref/logic/importer/PagedSearchBasedFetcher.java, src/main/java/org/jabref/logic/importer/PagedSearchBasedParserFetcher.java, src/main/java/org/jabref/logic/importer/SearchBasedFetcher.java, src/main/java/org/jabref/logic/importer/fetcher/AstrophysicsDataSystem.java, src/main/java/org/jabref/model/paging/Page.java, src/test/java/org/jabref/logic/importer/WebFetchersTest.java, src/test/java/org/jabref/logic/importer/fetcher/AstrophysicsDataSystemTest.java
Before i implement this, i want to discuss the interfaces i created. 
#5507
=> add paging support

build.gradle, src/main/java/module-info.java
This pull request updates citeproc-java to version 2.0.0. The new version uses GraalVM JavaScript on Java 11 and higher, so it should be significantly faster than the older one. Also, the internal citeproc-js process has been updated to the latest version.
I needed to add a `--add-exports` argument to make the module `com.oracle.truffle.regex` export the package `com.oracle.truffle.regex` to `org.graalvm.truffle`. Otherwise, the polyglot engine was not able to find the `regex` language. This might be a bug in GraalVM (i.e. a missing `exports` statement in the `org.graalvm.truffle` module). I opened an issue for that (https://github.com/oracle/graal/issues/1822).
I wasn't sure if I should amend the CHANGELOG or not. I can do this if you like me to.
All unit tests run successfully after …
=> Update citeproc-java to version 2.0.0

buildres/linux/jabrefHost.py
This updates the python script to keep the double quotes
(or to not fail at least) if passed on the cli by the extension.
if i call `jabref --importBibtex """some citation "with quotes" """`
the triple quotes should resolve it properly.
----
=> Escape quotes in import command

buildres/linux/jabrefHost.py
in the host file logger is not set
so we need to use logging instead.
I didn't set it properly so there's an error with a log command...
This PR fixes the typo
----
=> Fix typo logger to logging in python host script

src/main/java/org/jabref/gui/fieldeditors/UrlEditor.java, src/main/java/org/jabref/gui/fieldeditors/contextmenu/EditorMenus.java, src/main/java/org/jabref/logic/formatter/Formatters.java, src/main/java/org/jabref/logic/formatter/bibtexfields/CleanupUrlFormatter.java, src/main/java/org/jabref/logic/formatter/bibtexfields/LatexCleanupFormatter.java, src/main/java/org/jabref/logic/formatter/bibtexfields/ShortenDOIFormatter.java, src/main/java/org/jabref/logic/importer/fetcher/DBLPFetcher.java, src/main/java/org/jabref/logic/layout/Layout.java, src/main/java/org/jabref/logic/layout/LayoutFormatter.java, src/main/java/org/jabref/logic/layout/LayoutFormatterBasedFormatter.java, src/main/java/org/jabref/logic/layout/LayoutHelper.java, src/main/java/org/jabref/logic/layout/format/RemoveLatexCommandsFormatter.java, src/main/java/org/jabref/model/cleanup/FieldFormatterCleanups.java, src/main/java/org/jabref/model/cleanup/Formatter.java, src/test/java/org/jabref/logic/formatter/bibtexfields/CleanupUrlFormatterTest.java, src/test/java/org/jabref/logic/formatter/bibtexfields/ShortenDOIFormatterTest.java, src/test/java/org/jabref/logic/layout/format/RemoveBracketsTest.java, src/test/java/org/jabref/logic/layout/format/RemoveLatexCommandsFormatterTest.java
dblp changed the format of URLs - `_` is now escaped.
Clean URLs in DBLPFetcher.
Additionally:
- Style RemoveLatexCommandsFormatter
- Add tests for RemoveLatexCommandsFormatter
- Add support for removing single and multiple whitespaces after a command
- Split tests in RemoveBracketsTest
- Fix casing in CleanupUrlFormatter (to match style and current name of test class CleanUpFormatterTest)
- Fix casing in some ...Url.. method names
- Format CleanupUrlFormatter
=> Fix DBLPFetcherTest -- dblp changed the format

buildres/linux/jabrefHost.py
in bibtex json when importing from web extension.
This is a more complete fix that should support all escape characters.
The parsing works for `\` based characters, (tab, newline, ..)
and quotes.
It's been manually tested on the snap.
----
=> Use python raw string to preserve all special characters

buildres/linux/org.jabref.jabref.json, buildres/windows/jabref.json
This adds the id for the stable version of jabref to the Firefox extension.
As discussed in the JabRef issues..
Solves https://github.com/JabRef/JabRef-Browser-Extension/issues/89 https://github.com/JabRef/JabRef-Browser-Extension/issues/88
----
=> Add stable extension id to json

buildres/linux/jabref.spec
This PR simply adds the RPM spec file to add/remove the json files needed
by the browser extension (like the deb postinst/postrm scripts)
I just edited the jpackage template with the additions.
It's not tested yet so I can use the build repo to generate the rpm and test it from there.
----
=> [blocked by #5571 - can be merged afterwards] Add rpm spec file to add/remove json extension files

eclipse.gradle
Refs #5585 / https://github.com/oracle/graal/issues/1822
----
=> Add graalvm export also in eclipse gradle

build.gradle
Add in build.gradle the correct path to the json files needed
for the native-messaging-host functionality.
Fixes #5626 
----
=> Add the correct path to the native messaging json files

.travis.yml
CoveCov test are allowed to fail (see gradle build file) but the build should fail if there is a problem with the code cov update.
=> Let codecov fail during a test

src/main/java/org/jabref/logic/importer/fetcher/AstrophysicsDataSystem.java, src/test/java/org/jabref/logic/importer/fetcher/AstrophysicsDataSystemTest.java
`Not Available <P />` should not be put anymore.
=> Remove output of wrong abstract

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefFrame.java
Hi,
I found a bug where JavaFx was doing some recalculations during the initial layouting. 
Setting `setResizableWithParent` before initial layouting was finished resulted in JavaFx assuming a wrong fixed width.
I changed that by adding the code to a run later block.
It works good for me on Mac. Are there any concerns with that?
Best regards
Kai
=> Fix #5615 side pane not remembering position

build.gradle, src/main/java/org/jabref/JabRefLauncher.java, src/main/java/org/jabref/JabRefMain.java
Refs https://github.com/JabRef/jabref/issues/5602
- hamcrest wasn't visible --> add it to the test dependencies
- refine comments on JabRefLauncher and JabRefMain
I could not fix following issue when executing the test in IntelliJ
```text
ARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.bytebuddy.description.annotation.AnnotationDescription$ForLoadedAnnotation (file:/C:/Users/olive/.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy/1.9.10/211a2b4d3df1eeef2a6cacf78d74a1f725e7a840/byte-buddy-1.9.10.jar) to method com.sun.javafx.beans.IDProperty.value()
WARNING: Please consider reporting this to the maintainers of net.bytebuddy.description.annotation.AnnotationDescription$ForLoadedAnnotation
WARNING: Use --illegal-access=warn to …
```
=> Fix library access error at BasePanelTest

buildres/linux/jabrefHost.py
Retain compatibility with distros with python3 version < 3.5
This fixes https://github.com/JabRef/JabRef-Browser-Extension/issues/99
Tested on my end, still waiting for confirmation on the issue being solved.
----
=> Retain compatibility with python3.5 and earlier

CHANGELOG.md, src/main/java/org/jabref/gui/externalfiles/ExternalFilesEntryLinker.java
=> Fix copy drag and drop action

CHANGELOG.md, src/main/java/org/jabref/gui/Base.css, src/main/java/org/jabref/gui/Dark.css, src/main/java/org/jabref/gui/groups/GroupTree.css, src/main/java/org/jabref/gui/openoffice/StyleSelectDialogView.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/main/java/org/jabref/preferences/PreferencesService.java
There had been some visibility issues with the interface when in dark theme.
- Changed the color of the vertical scroll bar in dark mode to allow it to be more visible against the other colors.
- Changed the color of the accent behind the number selected which appears in the group tree when an item in a group is selected to allow for the number inside to be more readable.
fixes [#5522](https://github.com/JabRef/jabref/issues/5522)
Then:
Now:
----
- [x ] Change in CHANGELOG.md described
=> Dark Theme Visibility Fixes

src/main/java/org/jabref/gui/BasePanel.java, src/main/java/org/jabref/gui/externalfiles/DownloadFullTextAction.java, src/main/java/org/jabref/gui/keyboard/KeyBinding.java, src/main/resources/l10n/JabRef_en.properties
Closes #3874 and surpasses #5216.
Does not addresses the follow-up issues mentioned in https://github.com/JabRef/jabref/pull/5216#issuecomment-557589116
=> Rename "lookup fulltext" to "download fulltext"

CHANGELOG.md, src/main/java/org/jabref/logic/exporter/BibDatabaseWriter.java, src/test/java/org/jabref/logic/exporter/BibtexDatabaseWriterTest.java
=> Write customized types in alphabetical order

src/main/java/org/jabref/gui/maintable/MainTableColumnModel.java, src/main/java/org/jabref/migrations/PreferencesMigrations.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/test/java/org/jabref/migrations/PreferencesMigrationsTest.java
=> Improve column preference migration

CHANGELOG.md, src/main/java/org/jabref/logic/util/io/CiteKeyBasedFileFinder.java, src/main/java/org/jabref/logic/util/io/RegExpBasedFileFinder.java
Fixes #5664. I didn't tried it, but it should work...
=> Auto file finder follows symbolic links

.gitattributes, src/main/java/org/jabref/gui/dialogs/AutosaveUIManager.java, src/main/java/org/jabref/gui/exporter/SaveDatabaseAction.java, src/main/java/org/jabref/gui/util/DefaultFileUpdateMonitor.java, src/main/java/org/jabref/logic/exporter/BibDatabaseWriter.java, src/main/java/org/jabref/model/database/BibDatabaseContext.java, src/main/java/org/jabref/model/entry/BibEntry.java, src/test/java/org/jabref/gui/exporter/SaveDatabaseActionTest.java, src/test/java/org/jabref/logic/exporter/BibtexDatabaseWriterTest.java, src/test/java/org/jabref/model/entry/BibEntryTest.java
**Update** Do not change any functionality, but add tests.
Add tests for changed
- Add tests
- Guard AtomicFileWriter with a try-with-resources during save
- use Objects.requireNonNull in DefaultFileUpdateMontitor
- add comment
- some auto-formattings
- Fix typo in comment
(Follow-up to #5635)
----
=> Add tests for "changed" flag

src/main/java/org/jabref/gui/collab/ChangeScanner.java, src/main/java/org/jabref/gui/collab/DatabaseChangeMonitor.java, src/main/java/org/jabref/gui/collab/EntryChangeViewModel.java, src/main/java/org/jabref/gui/collab/EntryDeleteChangeViewModel.java, src/main/java/org/jabref/gui/collab/StringChangeViewModel.java, src/main/java/org/jabref/gui/collab/StringNameChangeViewModel.java, src/main/java/org/jabref/gui/collab/StringRemoveChangeViewModel.java, src/main/java/org/jabref/gui/importer/actions/AppendDatabaseAction.java, src/main/java/org/jabref/logic/importer/OpenDatabase.java, src/main/java/org/jabref/model/database/BibDatabase.java, src/main/resources/l10n/JabRef_en.properties, src/test/java/org/jabref/logic/bibtex/comparator/BibDatabaseDiffTest.java, src/test/java/org/jabref/model/database/BibDatabaseTest.java
If a file is changed externally, JabRef is doing a 3-way merge between the last saved value vs current value in JabRef vs new value in file.
The way this is done is by first comparing the last saved file with the current (changed) file, and then trying to find additional/other changes in the currently open database. This is really complex and I believe there is some subtle bug in the logic leading to #5257.
With this PR, the change scanner is changed to a to simple 2-way merge between the current value in JabRef vs new value in file. This is way simpler and I hope this PR fixes #5257.
In a few edge cases, the 2-way merge has a small disadvantage. For example, consider the following steps:
- User A opens file
- User A changes field `Author` to `User A` and adds field `Title` with value …
=> Improve change scanner

.github/workflows/deployment.yml, GitVersion.yml, build.gradle
Fixes https://github.com/JabRef/jabref/issues/5399 and fixes https://github.com/JabRef/jabref/issues/5657.
The following version information is automatically determined by GitVersion based on the current tags.
|  Context      | Build version |  Build information |
|---------------|---------------|--------------------|
| PR            | 5.0.X         | 5.0-branch.Y       |
| Master        | 5.0.X         |  5.0               |
| After tag 5.1 | 5.1.X         |  5.1               |
Here, `X` is the number of commits since the last tag; and `Y is the number of commits on this branch; and `branch` is the branch name. Build version is the version used in gradle, i.e. the one used to generate the installer. Build information is what is displayed in the about dialog.
(Not sure if it really works …
=> Use GitVersion to increment build numbers

eclipse.gradle
Add missing --add opens for controlsfx in eclipse classpath
=> Fix eclipse classpath build file

src/main/java/org/jabref/logic/importer/fetcher/SpringerFetcher.java, src/test/java/org/jabref/logic/importer/fetcher/SpringerFetcherTest.java
=> fix springer fetcher tests

CHANGELOG.md, src/main/java/org/jabref/logic/autosaveandbackup/AutosaveManager.java
As discussed in #5679 there are a lot of save actions performed when autosave is turned on. This PR adds a timer which limits the save actions to one in 200ms which is especially handy when automated tasks like find and replace are performed.
=> Add throttle to AutosaveUIManager

CHANGELOG.md, src/main/java/org/jabref/JabRefGUI.java, src/main/java/org/jabref/gui/JabRefFrame.java
Remove unnecessary parallel execution of `addTab`, which fixes #5537.
=> Fix import into currently open library

.github/failure-csl-update, .github/workflows/refresh-csl-subtrees.yml
The update currently fails. https://github.com/JabRef/jabref/commit/e251de5c50bf19afcd7fa761eb9d900eabc98a8e/checks?check_suite_id=336132856
This PR tries to fix that.
=> Try to fix csl update

.github/workflows/deployment.yml
According to https://help.github.com/en/actions/automating-your-workflow-with-github-actions/persisting-workflow-data-using-artifacts#uploading-build-and-test-artifacts one can store artifacts also on GitHub workflows. This PR tries that. If it succeeds, I can shut down builds.jabref.org.
We already have that in - but IMHO at the wrong place.
Download with 10 MB/s. All resulting files zipped.
<s>Background: Since our switch to github actions (https://github.com/JabRef/jabref/pull/5312), our upload to builds.jabref.org does not work reliably any more.</s>
=> Fix upload to GitHub artifacts

CHANGELOG.md, src/main/java/org/jabref/logic/util/io/FileUtil.java, src/test/java/org/jabref/logic/util/io/FileUtilTest.java
In #5603 the issue for not being able to rename files was because the file extension is part of the file name and therefore accounts to the maximum file length.
=> Fix #5603 - account for file extension in file name length

src/main/java/org/jabref/gui/bibtexkeypattern/BibtexKeyPatternTable.fxml, src/main/java/org/jabref/gui/groups/GroupTree.fxml, src/main/java/org/jabref/gui/preferences/BibtexKeyPatternTab.fxml, src/main/java/org/jabref/gui/preferences/TableColumnsTab.fxml, src/main/resources/l10n/JabRef_en.properties
I fixed the problem with the untranslated Strings that the Issue #5701 presented, since I talk Spanish, I implemented the changes for that language.
- [x ] Manually tested changed features in running JabRef (always required)
=> Fix for untranslated Strings

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupTreeView.java
This PR fixes a bug where the selection of the source groups was lost after drag and drop (#2868). I noticed a bug in the mapping from `GroupNodeViewModel` to the corresponding `TreeItem`.
The bug might also have caused other selection related bugs.
=> Fix #2868 - keep source groups selected after drag and drop

CHANGELOG.md, src/main/java/org/jabref/gui/importer/ImportCustomEntryTypesDialog.fxml, src/main/java/org/jabref/gui/importer/ImportCustomEntryTypesDialog.java
fixes issue #5651
Adds new CellFactory that changes the way the BibEntryTypes are displayed on the table without changing the `toString()` method on BibEntryType.
It also removes unnecessary label.
Here is a screenshot on how the window looks now.
=> Changes string representation when detecting custom entry types.

CHANGELOG.md, build.gradle
Fixes #5645 
The solution was to add a missing "uses" to the build.gradle file.
=> Fix medline fetcher/importer when using installer

.github/workflows/deployment.yml
Has been integrated now in jdk14
=> Update jpackage to build 27

CHANGELOG.md, src/main/java/org/jabref/gui/Base.css, src/main/java/org/jabref/gui/Dark.css, src/main/java/org/jabref/gui/FXDialog.java, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/entryeditor/EntryEditor.css, src/main/java/org/jabref/gui/entryeditor/LatexCitationsTab.java, src/main/java/org/jabref/gui/entryeditor/RelatedArticlesTab.java, src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java, src/main/java/org/jabref/gui/preferences/PreferencesDialog.css, src/main/java/org/jabref/gui/preferences/PreferencesDialog.fxml, src/main/java/org/jabref/gui/preferences/PreferencesDialogView.java, src/main/java/org/jabref/gui/texparser/CitationsDisplay.java, src/main/java/org/jabref/gui/texparser/ParseTexResult.css, src/main/java/org/jabref/gui/texparser/ParseTexResult.fxml, src/main/resources/l10n/JabRef_en.properties
Some visual bugs were still in the dark theme present. This is a quick fix:
+ Many icons where dark black. They use the standard text color now.
+ Wrong highlight color of the mark symbol in menus is now highlight text color.
+ The thin white line between the menubar and the toolbar is gone. ( fixes #5753 )
+ The background on starting up JabRef was white until a library was loaded.
+ The unselected checkbox border was black, only while the unselected radio-buttons were grey. Now they are all grey in various shades. (less then 50)
+ The group color indicator was unreadable, as the grey border was too ... grey. It's more lightweight now.
+ The CodeArea in the in the entry source editor and in the preview preferences had the wrong background color, caret color, selection background color, …
=> Various fixes to the dark theme

src/main/java/org/jabref/gui/BasePanel.java, src/main/java/org/jabref/gui/collab/ChangeDisplayDialog.java, src/main/java/org/jabref/gui/collab/ChangeScanner.java, src/main/java/org/jabref/gui/collab/DatabaseChangeMonitor.java, src/main/java/org/jabref/gui/collab/DatabaseChangePane.java, src/main/java/org/jabref/gui/collab/EntryAddChangeViewModel.java, src/main/java/org/jabref/gui/collab/EntryChangeViewModel.java, src/main/java/org/jabref/gui/exporter/SaveDatabaseAction.java, src/main/java/org/jabref/gui/importer/actions/AppendDatabaseAction.java, src/main/java/org/jabref/gui/preview/PreviewViewer.java, src/main/java/org/jabref/logic/importer/ImportFormatReader.java, src/main/java/org/jabref/logic/importer/OpenDatabase.java, src/main/resources/l10n/JabRef_en.properties, src/test/java/org/jabref/logic/importer/OpenDatabaseTest.java
Another shot at fixing https://github.com/JabRef/jabref/issues/4877. The changes in this PR might be already sufficient, let's see...
No time for extended PR description, see commit messages for changes. Last commit contains the actual "fix", the other ones are cosmetic changes.
=> Improve things arround change detection

src/main/java/org/jabref/JabRefGUI.java
Code follow-up to https://github.com/JabRef/jabref/pull/5738/. Just small changes. I hope, there won't be other improvements necessary.
=> Fix code style

src/main/java/org/jabref/logic/importer/IdBasedParserFetcher.java, src/test/java/org/jabref/logic/importer/fetcher/MedlineFetcherTest.java
- wait between calls to avoid 403
- remove assertion of entry not returned anymore
Follow up to https://github.com/JabRef/jabref/pull/5773, where the Springer tests are fixed. Here, the Medline tests are fixed.
=> Fix Medline tests

.github/workflows/deployment.yml
Extract "best of" of https://github.com/JabRef/jabref/pull/5748 to get things moving.
If this goes through, this is ready-for-review. Has some urgency as scp mostly does not work (because of our large file sizes). I am working at https://github.com/JabRef/jabref/pull/5748 to reduce the file sizes.
I kept `pigz --rsyncable` since a) I want to optimize transfer b) pgiz is better than gzip (see https://superuser.com/a/1050148/138868).
More background on rsyncable: https://beeznest.wordpress.com/2005/02/03/rsyncable-gzip/. Especially the link to the PhD thesis (I think by @tridge): https://www.samba.org//~tridge/phd_thesis.pdf
=> Switch to rsync

.github/workflows/cleanup_pr.yml
Follow-up to https://github.com/JabRef/jabref/pull/5365.
We need to clean up the builds directly after the merge, because we run out of disk space. This is now enabled, because we switched from scp to rsync (refs https://github.com/JabRef/jabref/pull/5778)
We already reviewed this script. I just opened a PR to check whether the "revert" worked and commits are "OK". Will merge as soon as I feel comfortable. 😇
=> Reenable cleanup

CHANGELOG.md, src/main/java/org/jabref/logic/citationstyle/CSLAdapter.java, src/test/java/org/jabref/logic/citationstyle/CitationStyleGeneratorTest.java
Bibtex entries with characters with diacritics {"a} were not rendering properly when showing non-default previews (eg: IEEE).
I added a call to the LatexToUnicodeAdapter on the "pipeline" when translating the data from the BibEntry to the HTML format to be displayed by the preview pane. With this change every preview style should always handle special diacritics. check issue #5779 for more details.
Here is a screenshot of the IEEE preview of the following entry
```
@book{Wickman2009non,
author={Wickman, Per-Olof and Persson, Hans},
title={Naturvetenskap och naturorienterande {\"a}mnen i grundskolan: En {\"a}mnesdidaktisk v{\"a}gledning},
publisher={Liber},
address={Stockholm},
year={2009},
ISBN={978-91-47-05333-9},
}
```
I also added a test to verify this functionality in the future, but …
=> Add latex2unicode formatter for displaying previews

.github/workflows/refresh-csl-subtrees.yml
Fixes https://github.com/JabRef/jabref/issues/5802
After the merge, I will allow the master branch being updated by the action (see https://github.com/JabRef/jabref/settings/branch_protection_rules/831054).
=> Fix csl update

src/main/java/org/jabref/gui/collab/ChangeDisplayDialog.java, src/main/java/org/jabref/gui/collab/DatabaseChangeViewModel.java, src/main/java/org/jabref/gui/collab/EntryChangeViewModel.java, src/main/java/org/jabref/gui/mergeentries/MergeEntries.java, src/main/resources/l10n/JabRef_en.properties
when merging entries
Fixes https://github.com/koppor/jabref/issues/385
=> Add select all buttons to change dialog

.github/workflows/tests-fetchers.yml, .github/workflows/tests.yml
Sometimes, our fetchers break (see e.g. https://github.com/JabRef/jabref/issues/5804) or an endpoint being down (e.g., ottobib this night).
```
Test searchForIsbnAvailableAtOttoBibButNonOnEbookDe() FAILED (31.4s)
org.jabref.logic.importer.FetcherException: A network error occurred
at org.jabref.logic.importer.fetcher.IsbnFetcherTest.searchForIsbnAvailableAtOttoBibButNonOnEbookDe(IsbnFetcherTest.java:104)
Caused by: java.net.ConnectException: Connection timed out
at org.jabref.logic.importer.fetcher.IsbnFetcherTest.searchForIsbnAvailableAtOttoBibButNonOnEbookDe(IsbnFetcherTest.java:104)
```
This proposal triggers fetcher tests a) only of fetchers code changes and b) once a week (to check for general issues such as changed endpoints at the provider's side)
It is accepted that refactorings …
=> Run fetcher tests on a weekly basis

.github/workflows/deployment.yml, snap/snapcraft.yaml
This PR uses a github action to build the snap.
The parts(build and push) need to be split, because there cannot be a uses and a run command on the same step.
It seems to work, since it uploads the snap on the pr.
I set the upload to the store to only run if building from master
But the .snap file is uploaded to builds.jabref.org on the PR as well, like the other builds
It might need checking still
=> Snap GitHub actions

src/main/java/module-info.java, src/main/java/org/jabref/gui/Dark.css, src/main/java/org/jabref/gui/entryeditor/SourceTab.java, src/main/java/org/jabref/gui/preferences/AdvancedTabViewModel.java, src/main/java/org/jabref/gui/preferences/AppearanceTabViewModel.java, src/main/java/org/jabref/gui/preferences/FileTabViewModel.java, src/main/java/org/jabref/gui/preferences/GeneralTabViewModel.java, src/main/java/org/jabref/gui/preferences/PreviewTabViewModel.java, src/main/java/org/jabref/gui/preferences/TableColumnsTabViewModel.java, src/main/java/org/jabref/gui/preferences/XmpPrivacyTabViewModel.java, src/main/java/org/jabref/gui/texparser/ParseTexDialogViewModel.java, src/test/java/org/jabref/gui/entryeditor/SourceTabTest.java
Fixes #5820
JabRef created a new instance of CodeArea everytime an entry was selected and bound multiple listeners to the CodeArea and to the ValidationStatus in bindToEntry. Refactored it a little bit, so the CodeArea stays persistent and the error messages are only displayed once.
Did some minor refactorings to the other Validators and to modules.info too, to avoid warning messages from the IDE, and fixed a minor mistake from a previous PR in dark.css. 
No screenshot, as there is no visual change.
=> Fix for multiple error messages in messed up source editor

src/main/java/module-info.java, src/main/java/org/jabref/gui/collab/ChangeScanner.java, src/main/java/org/jabref/gui/collab/EntryChangeViewModel.java, src/main/java/org/jabref/gui/collab/MetaDataChangeViewModel.java, src/main/java/org/jabref/gui/importer/actions/OpenDatabaseAction.java, src/main/java/org/jabref/logic/bibtex/comparator/MetaDataDiff.java, src/main/java/org/jabref/logic/importer/util/MetaDataParser.java, src/main/java/org/jabref/model/metadata/MetaData.java, src/main/resources/l10n/JabRef_en.properties
Another shot at fixing a part of #4877.
This time:
- Display changes in metadata in detail (aim: determine which change resulted in https://github.com/JabRef/jabref/issues/4877#issuecomment-568204571)
- Fix KeyCollisionException reported in https://github.com/JabRef/jabref/issues/4877#issuecomment-572943636
And a bit of code improvements along the way.
=> Improve change detection

.github/workflows/deployment.yml
IMHO we need new binaries on builds.jabref.org only if src/main/** changes. Not if we work on tests.
=> Build binaries only when src/main changes

.gitignore, external-libraries.txt, src/main/antlr3/org/jabref/bst/Bst.g, src/main/java/org/jabref/logic/bst/VM.java, src/main/resources/bst/IEEEtran.bst, src/test/java/org/jabref/logic/bst/TestVM.java, src/test/java/org/jabref/logic/formatter/bibtexfields/ClearFormatterTest.java
Taking the "best of" https://github.com/JabRef/jabref/pull/5702. Will merge after successful tests as I need it for input to students.
=> Fix BibTeX VM for IEEE (and some micro other fixes)

src/test/java/org/jabref/logic/importer/fetcher/GoogleScholarTest.java
The PDF has a title - try another publication without an available PDF
When fetching the old title, a PDF returned now. This PR fixes it.
=> Fix one Google Scholar test

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java
Fixes #5816 by falling back to PDF as default file type.
=> Fix missing file extension for downloaded files. 

CHANGELOG.md, src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java, src/main/java/org/jabref/gui/maintable/MainTableColumnModel.java, src/main/java/org/jabref/gui/preferences/TableColumnsTabViewModel.java, src/main/resources/l10n/JabRef_en.properties
=> Reintroducing master table index column

src/main/java/org/jabref/logic/importer/fetcher/SpringerFetcher.java
Calling the Springer web search always throws an exception:
```
java.lang.NullPointerException
at org.jabref.merged.module/kong.unirest.json.JSONObject.<init>(Unknown Source)
at org.jabref.merged.module/kong.unirest.json.JSONObject.<init>(Unknown Source)
at org.jabref/org.jabref.logic.importer.fetcher.SpringerFetcher.lambda$getParser$2(Unknown Source)
at org.jabref/org.jabref.logic.importer.SearchBasedParserFetcher.performSearch(Unknown Source)
at org.jabref/org.jabref.gui.importer.fetcher.WebSearchPaneViewModel.lambda$search$1(Unknown Source)
at org.jabref/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
at org.jabref/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
at org.jabref.merged.module/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
at …
```
=> duplicate query parameter removed

src/main/java/org/jabref/gui/groups/GroupNodeViewModel.java, src/main/java/org/jabref/gui/util/CurrentThreadTaskExecutor.java, src/main/java/org/jabref/gui/util/DefaultTaskExecutor.java, src/main/java/org/jabref/gui/util/TaskExecutor.java
It was indeed the throttler (at least it is working now for me)
=> Fix #5862.

CHANGELOG.md, src/main/java/org/jabref/logic/bibtex/FieldContentFormatter.java, src/main/java/org/jabref/logic/bibtex/FieldContentFormatterPreferences.java, src/main/java/org/jabref/logic/bibtex/FieldWriter.java, src/main/java/org/jabref/logic/bibtex/FieldWriterPreferences.java, src/main/java/org/jabref/logic/formatter/Formatters.java, src/main/java/org/jabref/logic/formatter/bibtexfields/EscapeAmpersandsFormatter.java, src/main/java/org/jabref/logic/importer/ImportFormatPreferences.java, src/main/java/org/jabref/logic/importer/fileformat/BibtexParser.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/main/resources/l10n/JabRef_en.properties, src/test/java/org/jabref/gui/entryeditor/SourceTabTest.java, src/test/java/org/jabref/gui/exporter/SaveDatabaseActionTest.java, src/test/java/org/jabref/logic/bibtex/FieldContentFormatterTest.java, src/test/java/org/jabref/logic/bibtex/FieldWriterTests.java, src/test/java/org/jabref/logic/formatter/bibtexfields/EscapeAmpersandsFormatterTest.java, src/test/java/org/jabref/logic/formatter/bibtexfields/EscapeUnderscoresFormatterTest.java, src/test/java/org/jabref/logic/importer/fetcher/ACMPortalFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/AstrophysicsDataSystemTest.java, src/test/java/org/jabref/logic/importer/fetcher/DBLPFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/GoogleScholarTest.java, src/test/java/org/jabref/logic/importer/fetcher/INSPIREFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/MathSciNetTest.java, src/test/java/org/jabref/logic/importer/fetcher/ZbMATHTest.java, src/test/java/org/jabref/logic/importer/fileformat/BibtexParserTest.java
Instead use save action to handle this case. Hopefully fixes the last remaining issue in #4877.
Includes also a bit of refactoring (mostly renames).
=> Remove ampersand escape when writing to bib file

CHANGELOG.md, src/main/java/org/jabref/gui/desktop/os/Linux.java
=> Fix opening pdf with okular in linux (#5253)

docs/guidelines-for-setting-up-a-local-workspace.md
While checking our IDE setup on ChromeOS, I saw that we stick to checkstyle and are not using our IntelliJ config. Is this intended? I suppose not, so I changed it back.
=> Switch to our IntelliJ config

CHANGELOG.md, src/main/java/org/jabref/logic/cleanup/RelativePathsCleanup.java, src/main/java/org/jabref/model/entry/LinkedFile.java
Fixes #5861
Description:
- Cleaning up entries with "Make paths of linked files relative (if possible)" broke web URLs and resulted in various other issues subsequently. This PR fixes this issue.
It has been tested for local files and web urls.
=> Fixes making paths of linked files relative (web urls will not be touched anymore)

README.md
As the current link just pointed to a page with another link, I'd propose to directly put that second link.
=> Replaced link to Workspace set-up with new one

AUTHORS, CHANGELOG.md, src/main/java/org/jabref/gui/externalfiletype/CustomizeExternalFileTypesDialog.java, src/main/java/org/jabref/gui/externalfiletype/CustomizeExternalFileTypesViewModel.java, src/main/java/org/jabref/gui/externalfiletype/EditExternalFileTypeEntryDialog.java, src/main/java/org/jabref/gui/externalfiletype/EditExternalFileTypeViewModel.java
Fixes #5846
**Changed:**
- edit/customize external file types: radio button for "default program"/"custom program" fixed: They now get updated and set properly (binding added and setting values).
- "Edit file type" dialog: correct value gets loaded now for the input field "Name"
- when updating an external file type entry: no differentiation will be made anymore whether the program runs on Windows or somewhere else
- Everything concerning the type `CustomExternalFileType` is now working properly as well.
- Settings will also be saved to JabRef's `config.xml` file.
- Editing an entry with type `ExternalFileType` works now as well. (changes are not lost anymore)
- Settings will also be saved to JabRef's `config.xml` file.
**Remarks:**
- Table in "Manage external file types" dialog is …
=> Fixes problems with managing external file types (issue 5846)

docs/guidelines-for-setting-up-a-local-workspace.md
=> IDE setup updated and extended

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/RequiredFieldsTab.java
Addresses: #5859 and partially #5853
This fix adds all entries of OrFields of the required fields of EntryTypeDefinitions to the list of required fields for the tab "Required fields" of the entry editor.
=> Fix properly resolves OrFields of required fields

.github/workflows/deployment.yml
We rely on JDK14 to build the binary distribution of JabRef. It is not released yet. The final release candidate will be available on 2020-02-20: https://openjdk.java.net/projects/jdk/14/. Meanwhile, we have to stick to the early access builds.
This PR updates to Build 34 (2020/1/29)
See https://jdk.java.net/14/ for more details.
Refs https://github.com/JabRef/jabref/issues/5591, https://github.com/JabRef/jabref/issues/5474, https://github.com/JabRef/jabref/issues/5079
=> Update JDK14 from EA 30 to EA 34

.github/workflows/check-outdated-dependencies.yml, .github/workflows/deployment.yml, .github/workflows/tests-fetchers.yml, .github/workflows/tests-oracle.yml, .github/workflows/tests.yml, gradle/wrapper/gradle-wrapper.properties
=> Update to jdk 13.0.2

CHANGELOG.md, src/main/java/org/jabref/model/entry/BibEntry.java, src/main/java/org/jabref/model/entry/field/InternalField.java
=> Fix maintable not updated when changing entry type

src/main/java/org/jabref/gui/StateManager.java, src/main/java/org/jabref/gui/search/GlobalSearchBar.java
and Fix exception when getSearchResultSize returned null
I found this wile trying to reproduce 
Hopefully Fixes #5897
and fixes #5821
=> Disable search when no library is opened

CHANGELOG.md, src/main/java/org/jabref/gui/importer/actions/OpenDatabaseAction.java
This PR fixes the problem when opening a library from the recent libraries menu. fixes #5939
=> Fix #5939 by creating a mutable list in OpenDatabaseAction

src/main/java/org/jabref/gui/preview/PreviewViewer.java, src/main/java/org/jabref/logic/search/SearchQuery.java, src/test/java/org/jabref/logic/search/SearchQueryTest.java
fixes #5892
The error when searching for "DOI 10.1210/endrev/bnz006" (or any phrases containing special javascript regular expression characters) is caused by not escaping special characters before passing search  pattern to javascript script used for highlighting words in preview view.
=> Fix not escaping special characters in search pattern

docs/guidelines-for-setting-up-a-local-workspace.md
=> Restructure and improve docs for setting up IntelliJ

src/main/java/org/jabref/gui/shared/SharedDatabaseLoginDialogViewModel.java
Follow up to https://github.com/JabRef/jabref/pull/5676
I could not connect to my MySQL instance without having `.setAllowPublicKeyRetrieval` set to true.
I am aware that this could lead to some security issues. For production use, the users nevertheless should use SSL and a local keystore.
Dialog values allowing me to connect to MySQL 8.0.19.
=> MySQL: Allow public key retrieval

src/main/java/org/jabref/logic/importer/fetcher/DoiResolution.java, src/test/java/org/jabref/logic/importer/FulltextFetchersTest.java, src/test/java/org/jabref/logic/importer/fetcher/DBLPFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/GoogleScholarTest.java
Added another possible option for checking fulltexts
=> Fixfetcher

CHANGELOG.md, build.gradle
Fixes #5474. Apparently, the upstream bug in the jdk concerning cmd line arguments was fixed in the meantime, which makes the `win-console` toggle obsolete.
Only problem I've encountered so far is that no logger output is written to the console. Combined with the Log4j issues we have at the moment, this means that for users it's not possible to report detailed stack traces etc. Workaround: use `.\runtime\bin\JabRef` to start JabRef instead of `JabRef.exe` (I would add this to the release notes under "known issues").
=> Remove background command line window

buildres/windows/JabRefHost.ps1
For some reason, removing `win-console` is still not compatible with JabFox (there are no errors, it simply does nothing). Changing the path to the "real" executable and removing new lines does work.
=> Fix communication with JabFox

src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/actions/StandardActions.java, src/main/java/org/jabref/gui/exporter/WriteXMPAction.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java, src/main/java/org/jabref/gui/preferences/XmpPrivacyTabView.java, src/main/java/org/jabref/gui/preferences/XmpPrivacyTabViewModel.java, src/main/java/org/jabref/gui/texparser/ParseTexDialogView.java, src/main/java/org/jabref/logic/xmp/XmpUtilShared.java, src/main/resources/l10n/JabRef_da.properties, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_el.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fa.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_in.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_nl.properties, src/main/resources/l10n/JabRef_no.properties, src/main/resources/l10n/JabRef_pt.properties, src/main/resources/l10n/JabRef_pt_BR.properties, src/main/resources/l10n/JabRef_ru.properties, src/main/resources/l10n/JabRef_sv.properties, src/main/resources/l10n/JabRef_tl.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_vi.properties, src/main/resources/l10n/JabRef_zh.properties
Formerly:
- 1st entry: alles klein + ... ("Search for citations in LaTeX files..."). ... because it opens a dialog
- XMP metadata (spelling)
- Move "Find and replace" to "Edit" (consistency to other tools)
- Add divider
Closes https://github.com/koppor/jabref/issues/399
=> Rework tools menu

CHANGELOG.md, src/main/java/org/jabref/model/entry/BibEntry.java
fixes  #5905
The issue happens because changed property in BibEntry is set after updating entry type, so property listeners get entry object with new entry type but changed value set to false. Because of that wrong bibtex code is generated by:
`entry.typeProperty().addListener(listener -> updateCodeArea());` (SourceTab.java).
=> Set BibEntry to "changed" state before setting a new entry type

docs/guidelines-for-setting-up-a-local-workspace.md
Does someone know how to correctly center the video-image with GitBook?
The earlier approach didn't work.
=> Add new IntelliJ video tutorial to docs.

docs/code-quality.md
This adds a section on our used code quality tools. Makes it explicit which tools are in place.
(Yes, I asked @cqse to check the job of Teamscale's JabRef analysis)
=> Add initial section on code quality

CHANGELOG.md, src/main/java/org/jabref/gui/maintable/BibEntryTableViewModel.java
fixes #5561 
The group and the linkedIdentifier column were not dynamically bound to the entry data.
=> Fixed display of groups and links column in MainTable

src/main/java/org/jabref/gui/JabRefFrame.java
Previously:
Now:
Assumption: Generate BibTeX keys is a replace action or at least closely related.
Closes https://github.com/koppor/jabref/issues/403
=> Move generate BibTeX keys to Edit menu

src/main/java/org/jabref/logic/importer/fetcher/OpenAccessDoi.java, src/test/java/org/jabref/logic/importer/fetcher/OpenAccessDoiTest.java
I had an NPE while checking the fetcher. This code fixes it.
It's an addition of a `null` check. I wanted to use Java streaming capabilities here 😇
=> Fix NPE in OpenAccessDoi

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupTreeView.java
fixes #5510 
Credit goes all to @mgroth0, who had Problems with git uploading this fix. Played around a little bit, I don't see any new issue arise from this fix.
=> Fixed group drag-n-drop not working after inserting an article into a group

src/main/java/org/jabref/gui/JabRefFrame.java, src/main/resources/l10n/JabRef_en.properties
"Lookup" is a core feature of JabRef and should be made more prominent.
"Tools" is away from library/bibtex context --> external, integration, ...
Content:
Search identifiers online
Search fulltext
unlinked lokal files
Automatically set file links
Previously:
Now:
Closes https://github.com/koppor/jabref/issues/404
=> New menu "Lookup"

src/main/java/org/jabref/gui/JabRefFrame.java
Previously:
Now:
Closes https://github.com/koppor/jabref/issues/398
=> Move journal abbreviations to library

build.gradle
As discussed in the devcall, the automatic checker for outdated dependencies needs to be maintained as well.
Now the workflow runs through, but of course, if it fails again, we need to look at it again.
=> Fix dependency updates workflow

codecov.yml
Often PRs are red because of minimal threshold changes below 1 percent
=> Raise codecov threshold

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefFrame.java
Followup to https://github.com/JabRef/jabref/pull/5988/ based on the discussion in the devcall.
Idea: Users should simply use the right click menu
=> Remove "Merge Entries" from Quality Menu

src/test/java/org/jabref/logic/importer/fetcher/AstrophysicsDataSystemTest.java
Locally all works (could not test zbMath)
=> Fix fetcher tests using correct month

.github/workflows/deployment.yml
and GitVresion from 5.1.2 to 5.1.3 (https://github.com/GitTools/GitVersion/releases/tag/5.1.3)
=> Try to update GitVersion action from v0.3 to v0.9

.github/workflows/deployment.yml
Use github actions to publish,
to try and reduce the upload time
=> Use github action to publish snap

.github/workflows/tests.yml, gradle/wrapper/gradle-wrapper.properties
* New patch level of gradle: https://docs.gradle.org/6.2.2/release-notes.html
* We do not use git submodules any more - we moved to [git subtree](https://www.atlassian.com/git/tutorials/git-subtree) at https://github.com/JabRef/jabref/pull/5647 - Thus, we can use the latest checkout source action (https://github.com/actions/checkout#whats-new)
In GitVersion we nevertheless fetch the whole history, so it does not harm to go for the latest version of checkout.
=> Update gradle and git checkout

src/main/java/org/jabref/gui/JabRefFrame.java
=> Really create new lookup menu

src/main/java/org/jabref/gui/groups/GroupTree.css, src/main/java/org/jabref/gui/groups/GroupTree.fxml, src/main/java/org/jabref/gui/groups/GroupTreeView.java
Rationale:
- larger search box as more text might be entered
- action buttons should be right we guess (yes it might look like a search button now but also before. we need another place/solution for the new group button then)
**Overall, we think the changes improve the visibility and usability.**
Old:
New:
=> ux: move group filter bar to top

CHANGELOG.md, src/main/java/org/jabref/gui/importer/actions/OpenDatabaseAction.java
This (really) fixes https://github.com/JabRef/jabref/issues/5939
Refs https://github.com/JabRef/jabref/pull/5940
=> fix: exception when opening already opened files

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fetcher/ArXiv.java, src/main/java/org/jabref/model/entry/identifier/ArXivIdentifier.java, src/test/java/org/jabref/logic/importer/fetcher/ArXivTest.java, src/test/java/org/jabref/model/entry/identifier/ArXivIdentifierTest.java
No longer include the version string in the `eprint` field, as wished in https://discourse.jabref.org/t/remove-version-in-arxiv-import/1941. Also improved the arXiv identifier parser a bit.
=> Improve arXiv fetcher

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java
=> Lowercase file extension

src/main/java/org/jabref/gui/groups/GroupNodeViewModel.java
Fixes #6078
Related #5245
@JabRef/developers  2b760cddf53cceae54fd149774226461f5290daa caused this issue.
https://github.com/JabRef/jabref/issues/5245
Obviously only icons contained inside JabRefIcons are available now.
The question is - do we really want this feature? Not sure if changing the line back to 
```
return Enums.getIfPresent(MaterialDesignIcon.class, iconCode.toUpperCase(Locale.ENGLISH))
.toJavaUtil()
.map(icon -> new InternalMaterialDesignIcon(getColor(), icon));
```
will reintroduce the referenced issue (https://github.com/JabRef/jabref/issues/5245).
This feature also only makes sense, if we have a dropdown with all available icons inside the new/edit group dialog IMHO.
=> Icons from Material design icons not recognized

src/main/java/org/jabref/logic/importer/fetcher/ACS.java, src/main/java/org/jabref/logic/importer/fetcher/ArXiv.java, src/main/java/org/jabref/logic/importer/fetcher/GoogleScholar.java, src/test/java/org/jabref/logic/importer/fetcher/ACSTest.java, src/test/java/org/jabref/logic/importer/fetcher/ArXivTest.java
Detect Google captcha div.
Follow up PRs might show or give more info to the user.
=> Minor fetcher improvements

src/main/java/org/jabref/cli/ArgumentProcessor.java, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/dialogs/AutosaveUIManager.java, src/main/java/org/jabref/gui/dialogs/AutosaveUiManager.java, src/main/java/org/jabref/gui/exporter/SaveAction.java, src/main/java/org/jabref/gui/exporter/SaveAllAction.java, src/main/java/org/jabref/gui/exporter/SaveDatabaseAction.java, src/main/java/org/jabref/gui/shared/SharedDatabaseUIManager.java, src/main/java/org/jabref/model/database/BibDatabaseContext.java, src/test/java/org/jabref/gui/exporter/SaveDatabaseActionTest.java, src/test/java/org/jabref/logic/cleanup/CleanupWorkerTest.java, src/test/java/org/jabref/logic/cleanup/MoveFilesCleanupTest.java, src/test/java/org/jabref/logic/cleanup/RenamePdfCleanupTest.java, src/test/java/org/jabref/logic/integrity/IntegrityCheckTest.java, src/test/java/org/jabref/model/database/BibDatabaseContextTest.java
While working on https://github.com/JabRef/jabref/issues/6109, we found, we need to refactor the `save` things to understand what's going on. ^^
- Get rid of "doSave()"
- Add notification for non-successful save in case of "SaveAll"
- Remove deprecated "setDatabaseFile" (as we are Java8 with Path)
=> Refactor SaveAction

CHANGELOG.md, src/main/java/org/jabref/gui/desktop/os/DefaultDesktop.java, src/main/java/org/jabref/gui/desktop/os/Linux.java, src/main/java/org/jabref/gui/desktop/os/NativeDesktop.java, src/main/java/org/jabref/gui/desktop/os/OSX.java, src/main/java/org/jabref/gui/desktop/os/Windows.java, src/main/java/org/jabref/gui/exporter/SaveAction.java, src/main/java/org/jabref/gui/icon/IconTheme.java, src/main/java/org/jabref/gui/preferences/AppearanceTab.fxml, src/main/java/org/jabref/gui/preferences/AppearanceTabView.java, src/main/java/org/jabref/gui/preferences/AppearanceTabViewModel.java, src/main/java/org/jabref/gui/preferences/ExternalTab.fxml, src/main/java/org/jabref/gui/preferences/ExternalTabView.java, src/main/java/org/jabref/gui/preferences/ExternalTabViewModel.java, src/main/java/org/jabref/gui/preferences/FileTabView.java, src/main/java/org/jabref/gui/preferences/GeneralTab.fxml, src/main/java/org/jabref/gui/preferences/GeneralTabView.java, src/main/java/org/jabref/gui/preferences/NameFormatterTab.fxml, src/main/java/org/jabref/gui/preferences/NameFormatterTabView.java, src/main/java/org/jabref/gui/preferences/NameFormatterTabViewModel.java, src/main/java/org/jabref/gui/preferences/PreferencesDialog.fxml, src/main/java/org/jabref/gui/preferences/TableColumnsTabView.java, src/main/java/org/jabref/gui/preferences/XmpPrivacyTabView.java, src/main/java/org/jabref/model/database/BibDatabaseMode.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/main/java/org/jabref/preferences/NewLineSeparator.java, src/main/resources/l10n/JabRef_en.properties
Changes:
- Reduces the size of the rarely used import/export/show/reset-preferences buttons to icon buttons to free space to display all of the tabs in the list ( fixes #6038 )
- The font size is now controlled by a Spinner (a text field with arrows on the right side)
- The ComboBoxes now have ValueFactories to properly display the real name of the languages, the charsets and the BibDatabaseMode which incorrectly displayed `biblatex` instead of `BibLaTeX`.
- Some keyboard events are added to the add-TextFields in NameFormatterTab etc. to make usage more intuitive.
- Removed obsolete and non functional `Open PDF` settings  ( closes #5529 )
=> Small improvements in preferences dialog

src/test/java/org/jabref/logic/importer/fetcher/CiteSeerTest.java
Fixes:
We searched for "JabRef". The returned paper does not contain anything about JabRef. I would not rely on changing search results. Therefore, I searched for the  DOI of the returned paper.
=> Fix fetcher test: CiteSeerTest

src/main/java/org/jabref/gui/BasePanel.java, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/logic/layout/LayoutEntry.java, src/main/java/org/jabref/model/database/BibDatabaseContext.java, src/main/java/org/jabref/preferences/LastFocusedTabPreferences.java, src/test/java/org/jabref/preferences/LastFocusedTabPreferencesTest.java
Folllow-up to #6117 
Get rid of `File` in `BibDatabaseContext`.
Also removed obsolete comments.
=> Remove obsolete usage of File in DatabaseContext

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefFrame.java
Background: <blockquote class="twitter-tweet"><p lang="en" dir="ltr">Oh bummer, did the new Jabref remove the &quot;Clear field&quot; feature?</p>&mdash; LianTze Lim (@liantze) <a href="https://twitter.com/liantze/status/1239401355573202944?ref_src=twsrc%5Etfw">March 16, 2020</a></blockquote>
Refs https://github.com/koppor/jabref/issues/410
=> Move "Manage field names & content" to "Edit"

.github/workflows/deployment.yml, .github/workflows/tests-fetchers.yml, .github/workflows/tests-oracle.yml, .github/workflows/tests.yml, build.gradle, src/main/java/org/jabref/Globals.java, src/main/java/org/jabref/JabRefGUI.java, src/main/java/org/jabref/JabRefMain.java, src/main/java/org/jabref/cli/JabRefCLI.java, src/main/java/org/jabref/gui/entryeditor/RelatedArticlesTab.java, src/main/java/org/jabref/gui/errorconsole/ErrorConsoleViewModel.java, src/main/java/org/jabref/gui/help/AboutDialogViewModel.java, src/main/java/org/jabref/gui/help/SearchForUpdateAction.java, src/main/java/org/jabref/logic/importer/fetcher/SpringerFetcher.java, src/main/java/org/jabref/logic/util/BuildInfo.java, src/main/resources/build.properties, src/test/java/org/jabref/logic/importer/fetcher/SpringerFetcherTest.java, src/test/java/org/jabref/logic/util/BuildInfoTest.java
Based on the discussion of today's devcall.
Won't work with self-compiled JabRef.
=> Move Springer key to environment

.github/workflows/check-outdated-dependencies.yml, .github/workflows/deployment.yml, .github/workflows/tests-fetchers.yml, .github/workflows/tests-oracle.yml, .github/workflows/tests.yml, README.md, build.gradle, docs/guidelines-for-setting-up-a-local-workspace.md, gradle/wrapper/gradle-wrapper.properties
Have to wait until Gradle 6.3 is released (which should be next week) due to https://github.com/gradle/gradle/issues/10248.
Apart from this issue, this PR is now ready for review.
=> [WIP] Update to JDK 14

codecov.yml
`project` should be a child of `status`, this might be why `comment` isn't being properly handled.
This should help with disabling Codecov comments (https://twitter.com/JabRef_org/status/1241737914205290502)
=> Update Codecov yaml with proper indentation

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java, src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java, src/test/java/org/jabref/logic/util/io/FileNameUniquenessTest.java
Added auto-numbering for downloaded file names, which conflict with file names in the current directory. #6068
=> Fix overwritting downloaded files with same name

docs/teaching.md
PR fixes several typos and grammar mistakes in teaching.md.
=> Fix typos and grammar mistakes in teaching.md

.github/workflows/refresh-journal-lists.yml
Use selective list combine script for dot-abbrevations and create extra file for dotless abbreviations
Uses the new scripts from https://github.com/JabRef/abbrv.jabref.org/pull/54/ modified in https://github.com/JabRef/abbrv.jabref.org/pull/57/
=> combine_journal_lists_dots

CHANGELOG.md, src/main/java/org/jabref/gui/BasePanel.java, src/main/java/org/jabref/gui/preferences/FileTab.fxml, src/main/java/org/jabref/gui/preferences/FileTabView.java, src/main/java/org/jabref/gui/preferences/FileTabViewModel.java, src/main/java/org/jabref/logic/exporter/SavePreferences.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/main/resources/l10n/JabRef_en.properties
Fixes https://github.com/JabRef/jabref/issues/6092
Additionally:
- remove obsolete method getEncodingOrDefault
- simplify code for adding a "*" for a modified library
=> Remove the option to configure to create .bib.bak

CHANGELOG.md, src/main/java/org/jabref/gui/openoffice/StyleSelectDialogViewModel.java, src/main/java/org/jabref/gui/openoffice/StyleSelectItemViewModel.java, src/main/java/org/jabref/logic/citationstyle/CitationStyleGenerator.java, src/main/java/org/jabref/logic/openoffice/OOBibStyle.java, src/main/java/org/jabref/logic/openoffice/StyleLoader.java, src/test/java/org/jabref/logic/openoffice/OOBibStyleTest.java, src/test/java/org/jabref/logic/openoffice/StyleLoaderTest.java
Fixes #6170
Rename method for internalStyle
=> Fix storing of custom jstyles

build.gradle, external-libraries.txt, src/main/java/org/jabref/logic/layout/format/MarkdownFormatter.java
Fixes https://github.com/JabRef/jabref/issues/6246
The flexmark dependencies were broken: https://github.com/vsch/flexmark-java/issues/385
Solution:
1. Update to latest version (released 3 days ago)
2. Narrow-down the included dependencies to the really used markdown extensions
After a successful build, I will merge.
=> Reduce the number depencencies introduced by markdown renderer

config/checkstyle/checkstyle.xml, src/main/java/org/jabref/logic/layout/format/AuthorAndsReplacer.java, src/main/java/org/jabref/logic/layout/format/Ordinal.java
Follow up on https://github.com/JabRef/jabref/pull/6202. Had to do it, because @Siedlerchr recommended to use JDK14 switch expressions at https://github.com/JabRef/jabref/pull/6203#discussion_r399826927 - and the PR of the contributor breaks the checkstyle task.
Could not reopen #6202, thus a new PR.
<s>The changes were approved by @tobiasdiez, so I will merge if the building succeeds. This will enable https://github.com/JabRef/jabref/pull/6203 to move forward.</s>
Does not work as expected. Created a StackOverflow question: https://stackoverflow.com/q/61050165/873282
I think, the first step could be to patch checkstyle's Java grammar: <https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java.g>
=> JDK14 switch - and checkstyle skipping

.github/workflows/stale.yml
Uses the [stale action](https://github.com/marketplace/actions/close-stale-issues) to automatically close stale issues. 
With this action, the workflow is as follows:
- Developer marks issue with "s: waiting-for-customer-feedback"
- After 30 days without reaction, the bot marks the issue with "s: stale" and comments on the issue.
- After further 7 days without reaction, the issue is closed.
This only applies to issues with "waiting-for-customer-feedback".
=> Create action to automatically close stale issues

src/main/java/org/jabref/logic/exporter/XmpExporter.java, src/test/java/org/jabref/logic/exporter/XmpExporterTest.java
Hotfix for XmpExporterTest not working.
As soon as PR goes through, I will merge.
Follow up on code-quality will be done at #6237.
The issue was introduced during removing of `@deprected` method in #6283.
=> Fix XmpExporterTest

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fileformat/RisImporter.java, src/test/java/org/jabref/logic/importer/fileformat/RISImporterTest.java, src/test/resources/org/jabref/logic/importer/fileformat/RisImporterTest9.bib, src/test/resources/org/jabref/logic/importer/fileformat/RisImporterTest9.ris
Fixes #6065 
1. Fixed an issue with "duplicate values in 'Abstract field';
2. Checked code and couldn't reproduce second error: "publication date is taken from the Y2 field, not from the correct Y1"
See lines 207-220 of `RisImporter.java`. It works fine and importing publication date as expected. Tested on file from @crystalfp (see file, attached to issue).
Kind regards,
Gennadiy
=> RIS import takes the wrong date and duplicates abstract

.github/workflows/deployment.yml
Recently our build script fails and often the reason is a problem with the cache. https://github.com/JabRef/jabref/runs/597567964 Let's see if it works without caching.
=> Remove caching in deployment scripts

CHANGELOG.md, build.gradle
That's also one thing that bothered me
=> Add JabRef to startmenu on windows

src/main/java/org/jabref/gui/maintable/BibEntryTableViewModel.java, src/main/java/org/jabref/gui/maintable/FieldColumn.java, src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java, src/main/java/org/jabref/gui/maintable/MainTableDataModel.java
There was a really stupid mistake in the way the main table was set up: the bindings for converting the raw field value to the proper displayed representation were created in the setCellValueFactory. 
https://github.com/JabRef/jabref/blob/5ed32e1c21337e216f773129f22946f61c49fd8a/src/main/java/org/jabref/gui/maintable/FieldColumn.java#L33
https://github.com/JabRef/jabref/blob/5ed32e1c21337e216f773129f22946f61c49fd8a/src/main/java/org/jabref/gui/maintable/FieldColumn.java#L50
This has the consequence that whenever the table view asked for the current value a new binding was created and the value was re-calculated over and over again. For example, if there were to the entry list then the table view asks all entries if their values changes. Usually only a couple of entries are changed, so …
=> Improve performance massively by fixing a stupid binding mistake

docs/adr/0009-use-plain-junit5-for-testing.md, src/test/java/org/jabref/architecture/MainArchitectureTestsWithArchUnit.java
When doing #latemob with external contributors, I often get asked, why we don't use [AssertJ](https://joel-costigliola.github.io/assertj/) @AlexanderGirgis @skufer322. This was a result of internal developer discussions, mostly in 2018 and before.
Thus, I thought, it is a good time to add an [ADR](https://adr.github.io/madr/).
Refs https://github.com/JabRef/jabref/pull/6232/commits/b13832575ebfd45df3b5381f5e6e424113bf5714
=> Add ADR von JUnit vs. AssertJ

CHANGELOG.md, src/main/java/org/jabref/gui/mergeentries/MergeEntries.css
This PR is related to #6334 (blue text color in the Merge entries dialog in dark theme).
After modifications, the dialog looks like this
I have also tried to replace the red color upon @koppor 's comment (located in the aforementioned issue)
=> Change blue and red colors in Merge entries dialog in Dark theme

CHANGELOG.md, src/main/java/org/jabref/gui/protectedterms/ManageProtectedTermsDialog.fxml, src/main/java/org/jabref/gui/protectedterms/ManageProtectedTermsDialog.java
Hi, I noticed that 'manage protected terms files' dialog button order was wrong - 'Apply' was on right side.
=> Fix wrong button order (Apply and Cancel) in ManageProtectedTermsDialog.

src/main/java/org/jabref/gui/Dark.css, src/main/java/org/jabref/gui/JabRefDialogService.java, src/main/java/org/jabref/gui/JabRefFrame.java
Related issues: #5522 , #5699 
The issue is that I don't find the dialogs graphics (e.g. the confirmation image) adequate, so maybe create custom ones for the dark theme (or remove them)?
The scroll pane is quite visible (at least on my side) so I don't know if that issue has been considered as resolved or not?
=> Fix various Dark theme issues

CHANGELOG.md, src/main/java/org/jabref/gui/menus/FileHistoryMenu.java
=> Fix underscore character being omitted from file name in Recent Libraries list

docs/README.md
Following message at https://discourse.jabref.org/t/github-documentation-uml-diagram-link-broken/2048 , fixing the file name.
Note: several links are in the form https://github.com/JabRef/jabref/tree/ec47f2138b0550a4622872d455902443cd56d9cc/docs/Groups.uml
Why not something like  https://github.com/JabRef/jabref/blob/master/docs/Groups.uml ?
=> Correcting file name for groups.uml

CHANGELOG.md, eclipse.gradle, src/main/java/org/jabref/gui/openoffice/StyleSelectDialogViewModel.java, src/main/java/org/jabref/logic/openoffice/OOBibStyle.java, src/main/resources/l10n/JabRef_en.properties, src/test/java/org/jabref/logic/openoffice/OOBibStyleTest.java, src/test/resources/org/jabref/logic/openoffice/testWithDefaultAtFirstLIne.jstyle
Fixes #6303
Adapted the error message to give a hint what is probably missing.
I also noticed a problem in eclipse when executing the L10n test. It was missing an add-opens
=> Fix jstyle was invalid with default section at the start

docs/README.md
Adding a recent architectural decision added to their list. 
Maybe there is an easy way to have this list being maintained automatically? 
Otherwise, I am afraid the list may be incomplete most of the time (the numbering is designed to go up to 9999 :wink: )
and some typo.
=> Docs: For developers: New architectural decision added to list

src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java
This fixes an issue introduced in #6381 that resulted in two identical fulltext-file entries when downloading a fulltext file via the context menu of an online link.
Now both the online link and the fulltext file are present in their BibEntry after the download.
=> Fixed entry duplication on file download

src/main/java/org/jabref/gui/JabRefFrame.java
Cleaned some LOCs left from JabRef 3.x (found during #6381)
=> Cleanup dead code

CHANGELOG.md, src/main/java/org/jabref/gui/edit/EditAction.java
In the text field, an edit action DELETE_ENTRY should do forward delete rather than do anything to the entry.
Fixes #6421
=> Fix the bug #6421

src/main/java/org/jabref/gui/exporter/SaveDatabaseAction.java
add concise message when SaveException happen. To fix https://github.com/JabRef/jabref/issues/6127
When SaveException happen (e.g. braces not match in any field) when saving, no consise message about what's wrong, I added the consise message of the SaveException to the popup window. 
Screenshots:
Before:
After:
=> add concise message when SaveException happen

snap/local/JabRef-launcher, snap/snapcraft.yaml
Fixes #5537 and https://github.com/JabRef/JabRef-Browser-Extension/issues/165
Add a separate launcher to avoid launching another instance of jabref, removing the list of errors that come from parsing the cli options (as viewed on gitter in https://paste.ubuntu.com/p/YXkqWVr9mz/)
=> Add launcher to fix extension import in snap

src/main/java/org/jabref/model/metadata/SaveOrderConfig.java
This PR fixes #6091
Co-authored-by: Heriniaina Randrianasolo <hjsrandrianasolo@gmail.com>
Co-authored-by: Omar Tachour <omar.tchr@hotmail.com>
Co-authored-by: Sadji Micipsa <micipsasadji@gmail.com>
This error is due to the absence of an object equality test for the saveInSpecifiedOrder attribute. 
So we have  handled this error by correcting the equals function in the SaveOrderConfig class.
=> Fix library sort order get lost

CHANGELOG.md, build.gradle, src/main/java/org/jabref/gui/autocompleter/AutoCompletionTextInputBinding.java, src/main/java/org/jabref/gui/fieldeditors/SimpleEditor.java
Fixes #6453
The autcomplete binding was triggered when a cleanup called setBibEntry from a background thread.
=> Fix autocomplete thread

CHANGELOG.md, src/main/java/org/jabref/logic/bibtexkeypattern/BracketedPattern.java, src/test/java/org/jabref/logic/util/BracketedPatternTest.java
Brackets in regular expressions were interpreted as brackets for fields. This change allows users to define regular expressions that contain brackets. This led to an exception before.
=> Fix bracket collisions

CHANGELOG.md, src/main/java/org/jabref/logic/texparser/DefaultLatexParser.java
Adds support for biblatex-mla style by slightly changing regex. Should fix #6476 .
=> Fix #6476 missing citation for biblatex-mla 

CHANGELOG.md, src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java
Addresses: #6499
Followup of #6178 
Truncates DOIs and URLs in the column "Linked identifiers" in main table, if too long.
=> Truncates DOIs and URLs in the column "Linked identifiers" in main table, if too long

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefFrame.java
Fixes #6487
Did as @Siedlerchr mentioned, I have added the drag and drop listeners to jabref's frame.
However, I could not reproduce the first part of the issue (double-clicking on the bib file), it works on my side, that is why I have opened a draft PR.
=> Fix Drag and Drop on empty database

.github/workflows/deployment.yml
We are apparently again blocked by maven
=> Reenable caching of gradle

src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/preferences/PreviewTabViewModel.java, src/main/java/org/jabref/gui/preview/PreviewPanel.java
Fixes #6447 
I have taken a long time considering how to update the preview when preference change. After I found that the PreviewPanel will be bind to entry in FieldsEditorTab.java, then we can just update the layout in PreviewPanel.java#setEntry()
Some ideas:
Can we using observer pattern to refactor the code: JabRefPreferences as Observable object and component need preferences can register as Observer. If the preferences were changed, we can notify the affected component to do an update?
=> Add some javadoc and fix the preview update issue

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefFrame.java
fixes issue #6485 to implement context menu on library tabs
with the "Library properties" menu item.
=> Fixes missing library properties context menu on library tab

CHANGELOG.md, src/main/java/org/jabref/gui/libraryproperties/LibraryPropertiesDialogViewModel.java
Fixes https://discourse.jabref.org/t/export-sort-by-entry-type/2122/1
Entrytype was missing in sort criterion.
I did not add it to the common fields, because the common fields are also used for the customize entrytype
=> Allow entrytype as sorting criterion

.github/workflows/tests.yml, .markdownlint.yml, CHANGELOG.md, docs/README.md, docs/adr/0004-use-mariadb-connector.md, docs/adr/0006-only-translated-strings-in-language-file.md, docs/adr/template.md, docs/code-howtos.md, docs/code-quality.md, docs/guidelines-for-setting-up-a-local-workspace.md, docs/javafx.md, docs/jpackage.md, docs/teaching.md, mlc_config.json
We have Markdown files, where [linting issues](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md) and wrong links could be contained. This PR adds a check for it. And also fixes issues of it.
=> Add markdown checks (and fix some markdown issues)

.github/workflows/tests.yml
I created a fork of markdown-lint. The upstream author quickly merged my changes back. Trying whether everything works fine. If yes, I'll merge.
No need to review.
=> Switch to upstream version of markdow-lint

src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/menus/FileHistoryMenu.java
Fixes #6529 
After fix the issue: (I typed 1, then 2, then 2)
It can open a database relative to typed key. And I also checked that when typing a letter not a num(eg, 'a'), there will be nothing to happen. And if type a num larger than the max index of history record, nothing will happen as well.
The main idea to solve this issue is to add key event listener in `JabRefFrame.java` and design relative handle function `openFileByKey()`.
=> Use letters to acess recent libraries in menu

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/PreviewTab.java
Fixes #6591
I didn't add "Preview" to `JabRef_en.properties` because already exists.
=> Fixed an issue where entry preview tab has no name in drop down list.

.github/workflows/deployment.yml, .github/workflows/tests-fetchers.yml, .github/workflows/tests.yml, build.gradle, src/main/java/org/jabref/logic/importer/fetcher/AstrophysicsDataSystem.java, src/main/java/org/jabref/logic/importer/fetcher/IEEE.java, src/main/java/org/jabref/logic/importer/util/GrobidService.java, src/main/java/org/jabref/logic/util/BuildInfo.java, src/main/resources/build.properties, src/test/java/org/jabref/logic/importer/fetcher/AbstractIsbnFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/AstrophysicsDataSystemTest.java, src/test/java/org/jabref/logic/importer/fetcher/DiVATest.java, src/test/java/org/jabref/logic/importer/fetcher/DoiFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/GrobidCitationFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/GvkFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/INSPIREFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/IsbnFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/IsbnViaEbookDeFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/IsbnViaOttoBibFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/MedlineFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/RfcFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/TitleFetcherTest.java, src/test/java/org/jabref/logic/importer/util/GrobidServiceTest.java
=> Fix some fetcher tests

src/main/java/org/jabref/gui/preferences/PreviewTabView.java
Related to #5522
Fixed an issue where entry preview in preferences has white theme.
=> Fixed an issue where entry preview in preferences has white theme.

CHANGELOG.md, src/main/java/org/jabref/logic/util/io/FileUtil.java, src/test/java/org/jabref/logic/cleanup/MoveFilesCleanupTest.java, src/test/java/org/jabref/logic/util/io/FileUtilTest.java
=> Fix downloaded files moved to citation key dir

src/main/java/org/jabref/gui/actions/ActionFactory.java
Catch InaccessibleObjectException otherwise JabRef becomes unusable in some occasions.
The problem is hard to reproduce, but happens quite frequently. It seems to be caused in the combination of searching the main table with the search bar and then clicking on a defined group in the side panel, where apparently some tooltip wants to get displayed during this processes (which I think is not vital in this case).
With this fix, I don't observe any malfunction and JabRef keeps usable. Since quite a lot other exceptions are already caught there, I think adding this one as well could be feasible.
<details><summary>Stack trace</summary>
22:51:38.624 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main] …
=> Catch InaccessibleObjectException

CHANGELOG.md, src/main/java/org/jabref/JabRefGUI.java, src/main/java/org/jabref/gui/util/DefaultFileUpdateMonitor.java, src/main/java/org/jabref/model/util/DummyFileUpdateMonitor.java, src/main/java/org/jabref/model/util/FileUpdateMonitor.java, src/main/java/org/jabref/model/util/WatchServiceUnavailableException.java, src/main/resources/l10n/JabRef_en.properties
Previously, the program was crashing for Unix users when inotify had reached its max file limit. Since the only way to fix this seems to be to close applications or to edit privileged system files, the proposed solution is to notify the user of the issue and give them the option of continuing usage of the application. Fixes #6073
=> Fixes issue where Unix crashes when inotify is full

CHANGELOG.md, src/main/java/org/jabref/gui/EntryTypeView.java, src/main/java/org/jabref/gui/EntryTypeViewModel.java, src/main/java/org/jabref/gui/StateManager.java, src/main/java/org/jabref/gui/duplicationFinder/DuplicateResolverDialog.java, src/main/java/org/jabref/gui/duplicationFinder/DuplicateSearch.java, src/main/java/org/jabref/gui/importer/ImportEntriesViewModel.java, src/main/java/org/jabref/gui/util/DialogWindowState.java
The "Possible duplicate entries" window now remembers its size and position throughout a session ([#6582](https://github.com/JabRef/jabref/issues/6582)). This was done by adding a DialogWindowState class to the gui utils. This class stores the size and position of the dialog window. The StateManager class was modified to store this object. It is retrieved whenever a new DuplicateResolverDialog object is created to get the previous size and position and is updated whenever the user proceeds through the dialog options. The DialogWindowState class can be re-used if this feature is needed for other dialog windows.
This is my first ever pull request so please let me know what you think or whether I need to re-tool my approach to be more in line with the structure of the rest of the code! I did …
=> Change "duplicates" window to recall size/position

src/main/java/org/jabref/gui/actions/ActionFactory.java
The last update to controlsfx seems to have introduced the requirement of unconfiguring buttons first before reconfiguring them.
In consequence, the user could not save any preferences anymore. This should fix it.
Please test it. I did, but i'm a bit cautious about unforseen consequences.
=> Unconfigure buttons first before reconficuring them

docs/teaching.md
Removed a link leading to nothing, a comma and replaced "wirking" through "working".
=> Typos in teaching.md

docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace.md
Fixes https://github.com/JabRef/jabref/issues/6678.
Up to now, we claimed that JavaFX magically works. One developer now showed up and said that plain OpenJDK does not work. On my machine, I always had to use LibericaJDK.
This PR makes that explicit.
Note that this change is only needed if developers use IntelliJ's internal build system. When executing JabRef using gradle, the binaries from maven central are used.
Let my quote https://openjfx.io/openjfx-docs/:
> ![image](https://user-images.githubusercontent.com/1366654/86996257-784b7180-c1ab-11ea-9005-5a58d447c769.png)
Since we claim that using the internal build system, we should also make the usage of it smooth.
> ![image](https://user-images.githubusercontent.com/1366654/86997514-8fd82980-c1ae-11ea-9ee4-6546f2279e6b.png) …
=> Add JavaFX installation notes

docs/teaching.md
Footnote doesn't work in Gitbook, so I at least set the reference of the research as a superscript. 
Here the link to the docs where it is for convenience:
https://devdocs.jabref.org/teaching
=> Update teaching.md : Reference as superscript

src/main/java/org/jabref/logic/importer/fetcher/DoiFetcher.java, src/main/java/org/jabref/model/entry/identifier/DOI.java
The method `getAgency` has been moved from `DOI` back to `DoiFetcher`.
=> getAgency moved from DOI to DoiFetcher

.github/workflows/check-links.yaml, .github/workflows/tests.yml, docs/adr/0011-test-external-links-in-documentation.md
The JabRef repository contains Markdown (`.md`) files documenting the JabRef code.
The documentation contains links to external resources.
For high-quality documentation, external links should be working.
Currently we check at each PR (option 2 below), but that is annoying. See https://github.com/JabRef/jabref/issues/6677.
* Checking external links should not cause issues in the normal workflow
* Check external links once a month
* Check external links in the "checkstyle" task
* Do not check external links
Chosen option: "\[option 1\]", because \[justification. e.g., only option, which meets k.o. criterion decision driver \| which resolves force force \| … \| comes out best \(see below\)\].
* Automatic notification of broken external links
* Some external sites need to [be …
=> Check external links once a month

.github/workflows/check-links.yaml, .github/workflows/deployment.yml
Applying the most recent documentation from: https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
=> Simplify deployment.yml

.github/workflows/tests.yml
Just before a release, I have to check the names of the contributors to be able to add them to `AUHTORS`. This is a good habit, where I received positive feedback for. We outline that in our contribution guide at https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md#author-credits, but it seems no one reads that far.
The issue is that 80% of the names are wrong. Be it casing errors, misspellings, multiple email adresses with slightly dfferent name, or no name at all.
To redeuce the load on my side, I created a check which comments on the PR if some new names will be added.
Example:
The check renders as follows if no new AUTHOR was found:
=> Add validation of "AUTHORS" file

src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java
=> Delete link after download

docs/advanced-reading/fetchers.md, src/main/java/org/jabref/logic/util/BuildInfo.java
This PR tries to summarize of how to work with fetchers locally.
I also added a fallback to environemnt variables in `BuildInfo.java` as I could not get it running locally.
My change in BuildInfo.java makes the handling more newcomer-friendly.
I am also opne to revert that change and to really desribe the IDE setup in the case of IntelliJ (and Eclipse) to enfore the reading of the "correct" `build.properties` even when running from the IDE (and not from gradle)
=> Add instructions how to work with fetchers 

src/main/java/org/jabref/gui/edit/EditAction.java, src/main/java/org/jabref/gui/maintable/MainTable.java
Add hack for OSX.
Caveat: Prevents pasting using Cmd+V on an empty library. Menu pasting however works.
Fixes #6739 
Fixes #6738 
Fixes #6293 
Would be nice if someone could test this for windows/linux as well
=> Fix copy pasting and delete via menu or key

CHANGELOG.md, src/main/java/org/jabref/logic/layout/format/HTMLChars.java, src/test/java/org/jabref/logic/layout/format/HTMLCharsTest.java
=> Fix HTML chars formatter for percent sign

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/auximport/FromAuxDialog.java, src/main/java/org/jabref/logic/auxparser/DefaultAuxParser.java, src/main/java/org/jabref/model/entry/BibEntry.java, src/test/java/org/jabref/logic/auxparser/AuxParserTest.java, src/test/java/org/jabref/logic/auxparser/DefaultAuxParserTest.java, src/test/java/org/jabref/logic/cleanup/BibtexBiblatexRoundtripTest.java, src/test/java/org/jabref/model/entry/BibEntryTest.java
Set changed flag on clone also for Misc entry type, because otherwise it equals the default entry type and no change is triggered which results in the entry not beeing written to the database on save
Fixes  #6405
Simplify gui code
=> Fix entry gets deleted after aux import

src/main/java/org/jabref/gui/importer/ImportEntriesDialog.java, src/main/java/org/jabref/gui/importer/ImportEntriesViewModel.java, src/main/java/org/jabref/gui/preferences/ImportTab.fxml, src/main/java/org/jabref/gui/preferences/ImportTabView.java, src/main/java/org/jabref/gui/preferences/ImportTabViewModel.java, src/main/java/org/jabref/model/metadata/FilePreferences.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/main/java/org/jabref/preferences/PreferencesService.java
The choice to download linked files in the import dialog is now remembered, and automatically restored. So if you downloaded the files the last time, the option is selected on the next import. This made the corresponding option in the preference dialog obsolete.
Rest is a bit of code cleanup.
=> Remember last choice of download files in import dialog

src/main/java/org/jabref/logic/bibtex/BibEntryWriter.java, src/test/java/org/jabref/logic/bibtex/BibEntryWriterTest.java, src/test/java/org/jabref/logic/exporter/BibtexDatabaseWriterTest.java, src/test/resources/testbib/bibWithUserCommentAndEntryChange.bib
The fields are no longer serialized in alphabetic order. This was introduced in https://github.com/JabRef/jabref/pull/6152.
=> Fix order of fields in bib file

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fetcher/AstrophysicsDataSystem.java, src/main/java/org/jabref/logic/importer/fetcher/ScienceDirect.java, src/test/java/org/jabref/logic/importer/fetcher/GrobidCitationFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/ScienceDirectTest.java
This PR fixes two fetchers (refs https://github.com/JabRef/jabref/issues/6369):
- APS fetcher: `\textbackslash` is added server side --> removed at cleanup-phase
- ScienceDirect: location of PDF link changed --> rewrote code to extract the PDF url - fixes https://github.com/JabRef/jabref/issues/5860
=> Fix APS and ScienceDirect fetcher

src/main/java/org/jabref/gui/cleanup/CleanupPresetPanel.java, src/main/java/org/jabref/gui/commonfxcontrols/FieldFormatterCleanupsPanel.java
Fixes #6787
The problem orginally comes from here:
https://github.com/JabRef/jabref/blob/4e220f618a755cb7dc18882653ea46e3ed049c9e/src/main/java/org/jabref/gui/commonfxcontrols/FieldFormatterCleanupsPanel.java#L109
Unfortuantely it's not possible to add a not() there directly
The method bindBidirectional(Property<Boolean>) in the type BooleanProperty is not applicable for the arguments (BooleanBinding)
=> Fix cleanup Field formatters not working when enabled

CHANGELOG.md, docs/adr/0014-separate-URL-creation-to-enable-proper-logging.md, src/main/java/org/jabref/logic/importer/SearchBasedParserFetcher.java, src/main/java/org/jabref/logic/importer/fetcher/CollectionOfComputerScienceBibliographiesFetcher.java, src/main/java/org/jabref/logic/importer/fetcher/GoogleScholar.java, src/main/java/org/jabref/logic/importer/fetcher/SpringerFetcher.java, src/main/java/org/jabref/logic/importer/fetcher/SpringerLink.java, src/main/java/org/jabref/logic/importer/fileformat/ModsImporter.java, src/main/java/org/jabref/logic/net/URLDownload.java, src/test/java/org/jabref/logic/importer/fetcher/CiteSeerTest.java, src/test/java/org/jabref/logic/importer/fetcher/CollectionOfComputerScienceBibliographiesFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/LibraryOfCongressTest.java, src/test/java/org/jabref/logic/importer/fetcher/SearchBasedFetcherCapabilityTest.java, src/test/java/org/jabref/logic/importer/fetcher/SpringerFetcherTest.java
This PR fixes fetchers (refs #6369):
- Add cleanup for Library of Congress
- SpringerLink now uses the SpringerNature API key (same key can be used) - refs #6729
- Add URL logger for IEEE (and other fetchers)
---
=> Fix more fetchers

.github/workflows/deployment.yml
This should fix the problem with the missing third version specifier. https://github.com/GitTools/GitVersion/issues/1994 is fixed in 5.3.3
=> Upgrade gittools

.github/workflows/refresh-csl-subtrees.yml
I've just noticed that the Update CSL workflow is invoked on every push, see e.g. https://github.com/JabRef/jabref/actions?query=workflow%3A%22Refresh+Citation+Style+Language+Files%22. This is fixed.
=> Disable CSL refresh on push

build.gradle
Triggered by https://github.com/JabRef/jabref/pull/6794#discussion_r478232430. All generated files are now placed in src/main/generated which is automatically indexed by Intellj. This removes a few configuration steps that are otherwise needed (see #6794). After running `compileJava` once, the intellj-based compilation and run is sufficient. 
For 2020.1 it was working, but it stopped now that I upgraded to 2020.2. It seems the generated sources are no longer included in the intellj-based build. As @koppor experience the same issues, I guess this is a bug in Intellj.
=> Rename /gen to /generate

config/checkstyle/checkstyle.xml, docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace.md, src/main/java/org/jabref/gui/EntryTypeView.java
Checkstyle 8.36 was released - including Java14 support: https://checkstyle.org/releasenotes.html. Thus, no hack necessary any more.
=> Remove checkstyle hack. 8.36 got released

src/main/java/org/jabref/gui/edit/EditAction.java
Fixes #6293
Also enable paste menu/action for empty libraries with no entries yet
=> Follow up fix for copy paste

.github/workflows/deployment.yml, .github/workflows/snap.yml, .github/workflows/tests.yml
We need to cancel previous running workflows in case a new one starts. This is not suppored by GitHub (https://github.community/t/github-actions-cancel-redundant-builds-not-solved/16025?u=koppor), but there is an action implementing it: https://github.com/marketplace/actions/cancel-workflow-action
This PR adds that action.
=> Cancel Previous Workflow Runs

src/main/java/org/jabref/gui/externalfiles/FindUnlinkedFilesDialog.java
The window "Find unlinked files" should be named "Search for unlinked local files" now (v. 5.2) to be consistent with the menu Lookup.
=> "Find unlinked files": rename window

src/main/java/org/jabref/gui/keyboard/KeyBinding.java
Following PR #6849, redefine the keyboard shortcut from "Find unlinked files" to "Search for unlinked local files".
=> "Find unlinked files": redefine keyboard shortcut

CHANGELOG.md, src/main/java/org/jabref/gui/BasePanel.java
=> Don't show entry editor on startup

CHANGELOG.md, src/main/java/org/jabref/gui/icon/IconTheme.java
Fixes #6834
Changed the link used when we have only one entry to a single chain.
=> Fix icon issue

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fetcher/AstrophysicsDataSystem.java, src/test/java/org/jabref/logic/importer/fetcher/AstrophysicsDataSystemTest.java
In drop-down menu for fetching by ID of the window "Select entry type", "SAO/NASA Astrophysics Data System" is quite long.
Replacement by SAO/NASA ADS (people knowing it will recognized it).
None of these items...:
=> Fetch by ID: SAO/NASA Astrophysics Data System -> SAO/NASA ADS

docs/adr.md
gitbook was not collaborative...
=> Dev Doc: Moving around ADR (end?)

CHANGELOG.md, src/main/java/org/jabref/gui/maintable/MainTable.java, src/main/java/org/jabref/gui/maintable/MainTableColumnModel.java
Compare propertys correctly with equals
=> Fix sort order in main table not stored

CHANGELOG.md, src/main/java/org/jabref/logic/openoffice/OOUtil.java
Discovered that bug while reproducing #6903
=> Catch correct exception in LO inserter

src/main/java/org/jabref/logic/formatter/bibtexfields/RegexFormatter.java, src/test/java/org/jabref/logic/formatter/bibtexfields/RegexFormatterTest.java
There are some bugs in the `regex` modifier. The following change-list is preliminary,
=> Fixes bugs in the `regex` cite key pattern modifier

docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace.md
Workaround for build errors: missing openjfx libraries
=> Update DevDocs: workaround for issues with local openjfx maven libraries

.github/workflows/deployment.yml
Try to build JabRef with JDK15 (which was released 6 days ago - https://openjdk.java.net/projects/jdk/15/
=> Always use Java 15

CHANGELOG.md, src/main/java/org/jabref/gui/customentrytypes/CustomEntryTypeDialogViewModel.java, src/main/java/org/jabref/gui/customentrytypes/CustomEntryTypeViewModel.java, src/main/java/org/jabref/gui/customentrytypes/CustomizeEntryTypeDialogView.java, src/main/java/org/jabref/gui/customentrytypes/EntryTypeViewModel.java, src/main/java/org/jabref/gui/customentrytypes/StandardEntryTypeViewModel.java
fixes #6906
* Created separate view models for standard and custom entry types, adding remove icon only for the custom ones
* Updated CHANGELOG.md
It's working solution, but please take a look whether the implementation is good. I will modify the user doc if it's accepted.
=> Fix remove actions for entry types in the editor

CHANGELOG.md, src/main/java/org/jabref/gui/customentrytypes/CustomizeEntryTypeDialogView.java
fixes #6934
The issue is happening because cells with delete icon are set editable (because the whole table is set editable).
https://github.com/JabRef/jabref/blob/129c36e24bbd3332832728124ebf27d2462a0300/src/main/java/org/jabref/gui/customentrytypes/CustomizeEntryTypeDialogView.java#L111-L112
=> Fix: in entry types editor selected field is not removed after first click 

.github/workflows/tests.yml
The current checker for AUTHORS does not work when a non-JabRef-developer creates a PR. This PR removes the commenting functionality and adds a normal failure.
Reason: consistent to other checkers (e.g., checkstyle)
I'll just go ahead, since I take care about the AUTHORS file. Just want to have the update better referenceable.
Follow up to #6722
=> Replace comment by just a failure

src/main/java/org/jabref/model/strings/StringUtil.java, src/test/java/org/jabref/logic/citationkeypattern/CitationKeyGeneratorTest.java, src/test/java/org/jabref/model/strings/StringUtilTest.java
Fixes #6583 . Some unicode characters can be encoded in multiple ways, and the mapping that `StringUtil#replaceSpecialCharacters` relies on does not contain all cases. The proposed solution uses [NFC](https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/text/Normalizer.Form.html#NFC) to re-encode the characters so that these characters can be found.
There exists more information on [Unicode normalization in the Java API](https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/text/Normalizer.Form.html#NFC).
My subjective opinion is that most people expect Unicode to work similar to NFC, i.e., if characters looks the same, it is likely that they are equivalent. Hence, if someone debugs issues in the `UNICODE_CHAR_MAP`, they will expect NFC.
A more holistic approach …
=> Fix for some Unicode characters in citation keys

src/main/java/org/jabref/gui/preferences/AppearanceTab.fxml, src/main/java/org/jabref/gui/preferences/CitationKeyPatternTab.fxml, src/main/java/org/jabref/gui/preferences/ExternalTab.fxml, src/main/java/org/jabref/gui/preferences/FileTab.fxml, src/main/java/org/jabref/gui/preferences/GeneralTab.fxml, src/main/java/org/jabref/gui/preferences/GroupsTab.fxml, src/main/java/org/jabref/gui/preferences/LinkedFilesTab.fxml, src/main/java/org/jabref/gui/preferences/PreferencesSearchHandler.java
Updated fxml files from the preferences package to appear in preference search.
The preferences search was unable to find some visual components because they are not a direct child from one of the preferences tab. 
So, the method getPrefsTabLabelMap in PreferencesSearchHandler cannot find them. I moved some components that were inside  <HBox> tags to let them "visible" to their parents in the mentioned method. It does not change the UI. Most of the components could be moved. Some could not because they have many parents until the tab and it could impact the UI. 
Fixes #6866
=> Fix Preferences Search

src/test/java/org/jabref/logic/importer/fetcher/MedraTest.java
I noticed that the unit tests were failing and that Medra was not categorized as Fetcher
Fix wrong entry
=> Mark medra test as fetcher test

.github/dependabot.yml, build.gradle
Fixes #6964 
Refs: https://github.com/FXMisc/RichTextFX/issues/967
TODO: Investigate/report bug
=> downgrade richtextfx to fix entering of curly braces in mac in code area

CHANGELOG.md, buildres/linux/jabrefHost.py
`shutil.which()` returns an `str` and not a `pathlib.Path`. Therefore, we need to check if `which()` actually returns something and if so, we should convert it to a `pathlib.Path` such that `JABREF_PATH` is always of the same type.
I stumbled across this while fixing https://github.com/JabRef/JabRef-Browser-Extension/issues/158 for the unofficial Arch Linux JabRef package in the Arch User Repository (AUR): https://github.com/michaellass/AUR/issues/17
=> Fix locating jabref in jabrefHost.py

snap/hooks/connect-plug-etc-chromium-native-messaging-jabref, snap/hooks/connect-plug-etc-opt-chrome-native-messaging-jabref
This PR changes reverts the paths in the snap hooks to the correct one for chrome/chromium.
They were set to look at the mozilla dir for chrome as well, but it's not correct
=> Fix the paths in chrome snap hooks

src/main/java/org/jabref/model/entry/identifier/DOI.java, src/test/java/org/jabref/model/entry/identifier/DOITest.java
It now accepts DOIs with only three characters. This fixes an error in the ShortenDOIFormatterTest as run by the CI (see #6369), for example [here](https://github.com/JabRef/jabref/runs/1185667289?check_suite_focus=true#step:6:426).
=> Adapt the short DOI regex 

.github/dependabot.yml
There is too much noise with non-working dependencies (see https://github.com/JabRef/jabref/pull/6952). I would like to pin the version. We can update the dependency as soon as issue https://github.com/microsoft/ApplicationInsights-Java/issues/1155 is closed.
=> Pin application insights

src/main/java/org/jabref/logic/importer/fetcher/INSPIREFetcher.java, src/main/java/org/jabref/model/entry/identifier/DOI.java
Arxiv Test is failing with the search phrase, because both queries return the same result.
@DominikVoigt  In ArxivTest supportsPhraseSearch(), both queries return the same result.  Maybe you can take a look at that
```
List<BibEntry> resultWithPhraseSearch = fetcher.performSearch("au:\"Tobias Diez\"");
List<BibEntry> resultWithOutPhraseSearch = fetcher.performSearch("au:Tobias Diez");
```
=> Fix INSPIRE fetcher and short doi fetcher tests

AUTHORS, src/main/java/org/jabref/gui/entryeditor/SourceTab.java
Issue #6936 is about the source tab (BibTeX source) losing the ability to be editable (https://github.com/JabRef/jabref/issues/6936#issuecomment-703110024). This happens because `codeArea` can be disabled, but there is no code path that re-enables it.
This patch re-enables `codeArea` as editable if the BibTeX entry's source code is correct. Although the source tab cannot be used by the user to fix any syntax error in BibTeX fields (source tab will be disabled if there are syntactic errors introduced by editing the fields in the other tabs), such error can be fixed by editing the field, which will trigger `SourceTab`'s listener and call the `updateCodeArea()` method, which will enable codeArea if the source of the BibTeX entry is syntactically correct.
=> Fix "irregularly losing ability to edit data in biblatex source tab"

AUTHORS, CHANGELOG.md, src/main/java/org/jabref/gui/externalfiles/FindUnlinkedFilesDialog.java
Fixes #6848 
When clicking Collapse All button in the Search for Unlinked Local Files, it expands the directory structure erroneously.
- Please don't remove any items, just leave them unchecked if they are not applicable.
=> 6848 fixed the issue of clicking collapse all expanding tree

src/main/java/org/jabref/logic/citationkeypattern/BracketedPattern.java, src/main/java/org/jabref/logic/citationkeypattern/CitationKeyGenerator.java, src/test/java/org/jabref/logic/citationkeypattern/BracketedPatternTest.java, src/test/java/org/jabref/logic/citationkeypattern/CitationKeyGeneratorTest.java
Fixes #6892.
Character classes (regex expressions in brackets, e.g., `[a-zA-Z]`) should be usable with the regex modifier, but it currently isn't for citation keys.
Bracketed patterns are parsed using several different methods in `CitationKeyGenerator.java`, `BracketedPattern.java` and `AbstractCitationKeyPattern`. This PR aims to merge all parsing code into `BracketedPattern.java` to make it easier to modify bracketed patterns without breaking the citation key generator.
Currently BracketedPattern's parser can parse expressions containing the regex modifier using character classes.
**Todo**
**Checklist**
=> Merge parsing of bracketed patterns

.github/workflows/deployment.yml
=> try to fix DEP issue with official jdk

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/actions/StandardActions.java
Fixes #6991 
Removed the menu entry to only have one way to access 'Manage external file types' in the Preferences Dialog
=> Removed menu entry for 'Manage external file types'

.github/workflows/snap.yml, build.gradle, snap/snapcraft.yaml
Fix #7022 
A change in jpackage has moved the version to an xml file.
We can parse that to read the version and set it in the snap package
=> Snapcraft: set version from new xml file

CHANGELOG.md, src/main/java/org/jabref/gui/EntryTypeViewModel.java, src/main/java/org/jabref/logic/importer/fetcher/IsbnFetcher.java, src/main/java/org/jabref/logic/importer/fetcher/IsbnViaOttoBibFetcher.java
Fixes #7000 
Added an error message that gets shown when the entered ISBN leads to no results on ebook.de and ottobib.
Screenshot of change:
=> Added error msg when isbn entry was not found

src/main/java/org/jabref/logic/importer/util/FileFieldParser.java, src/main/java/org/jabref/model/entry/LinkedFile.java, src/test/java/org/jabref/logic/bibtex/FileFieldWriterTest.java
Fixes #7032. The FileFieldParser did not detect an URL and created a LinkedFile object with the URL as a local file path, which caused an error when running "Check integrity".
I'm not sure if the unit test is in the right class.
If this change requires a changelog entry, I'm happy to add one.
=> Add online-link detection to FileFieldParser

CHANGELOG.md, snap/snapcraft.yaml, src/main/java/org/jabref/gui/desktop/os/Linux.java
Fixes https://github.com/flathub/org.jabref.jabref/issues/3
As discussed in gitter the confined releases do not play nicely with xdg-open.
The flatpak fails directly, and the snap asks for confirmation every time.
If we introduce awt.open it works as intended with native commands/windows.
It works in confined and unconfined releases.
At the moment this is a draft pending further tests
=> Add awt native open commands

CHANGELOG.md, src/main/java/org/jabref/logic/layout/LayoutEntry.java, src/main/java/org/jabref/logic/layout/format/ShortMonthFormatter.java, src/test/java/org/jabref/logic/layout/format/ShortMonthFormatterTest.java
Add formatter that can format the month field to use the shorthand abbreviation .
fixes #6579
=> add short date formatter

CHANGELOG.md, src/main/java/org/jabref/gui/preview/PreviewViewer.java
Make comment more precise
Fixes #7068
=> Fix custom theme styles not applied to the entry preview

CHANGELOG.md, src/main/java/org/jabref/gui/preferences/PreviewTabView.java, src/main/java/org/jabref/gui/preferences/PreviewTabViewModel.java, src/main/java/org/jabref/gui/preview/PreviewPanel.java, src/main/java/org/jabref/gui/preview/PreviewViewer.java, src/main/java/org/jabref/logic/bst/BstPreviewLayout.java, src/main/java/org/jabref/logic/citationstyle/CitationStylePreviewLayout.java, src/main/java/org/jabref/logic/layout/TextBasedPreviewLayout.java, src/main/java/org/jabref/logic/preview/PreviewLayout.java, src/main/java/org/jabref/preferences/JabRefPreferences.java
Introduce internal name for finding layout
Fixes #6447
The problem was that the getName method returned a l10n name for Custom Preview layout.....
=> Fix preview settings not saved due to l10n

src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/maintable/CellFactory.java, src/main/java/org/jabref/gui/maintable/MainTable.java, src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java, src/main/java/org/jabref/gui/maintable/RightClickMenu.java, src/main/java/org/jabref/gui/maintable/columns/SpecialFieldColumn.java, src/main/java/org/jabref/gui/specialfields/SpecialFieldAction.java, src/main/java/org/jabref/gui/specialfields/SpecialFieldMenuItemFactory.java, src/main/java/org/jabref/gui/specialfields/SpecialFieldViewModel.java, src/main/java/org/jabref/gui/util/FieldsUtil.java, src/main/java/org/jabref/model/entry/field/SpecialFieldValue.java
Just some refactoring in preparation for the Basel Java SE-class
=> Special field code maintenance

CHANGELOG.md, src/main/java/org/jabref/gui/DefaultInjector.java, src/main/java/org/jabref/gui/importer/ImportAction.java, src/main/java/org/jabref/gui/importer/ImportEntriesDialog.java, src/main/java/org/jabref/gui/importer/ImportEntriesViewModel.java, src/main/java/org/jabref/logic/importer/fileformat/EndnoteXmlImporter.java, src/main/resources/l10n/JabRef_en.properties, src/test/resources/org/jabref/logic/importer/fileformat/EndnoteXmlImporterTest_EmptyKeywordStyle.bib, src/test/resources/org/jabref/logic/importer/fileformat/EndnoteXmlImporterTest_EmptyKeywordStyle.xml
Display error messages/notifications for exceptions
I used the endnote xml the user provided via mail.
I will add tests later.
=> Fix endnote importer when keyword style is null

.github/workflows/deployment.yml, build.gradle
=> Try to fix linux build

CHANGELOG.md, src/main/java/org/jabref/preferences/JabRefPreferences.java
This applies the quick fix proposed at https://github.com/JabRef/jabref/issues/7083. To implement the full functionality a longer thought on previews is requried.
I think, the first proposal is a good step towards a better preview: Show the full names of authors and editors, to list the editor only if no author is present, have the year ealier. 
I disliked the default preview style, but could not make any (good) proposal. We need to keep the custom preview, because humanities have special requirements not met by CSL (especially displaying the comments field, ...)
=> Refine default preview

src/main/java/org/jabref/gui/preview/PreviewViewer.java, src/main/java/org/jabref/logic/search/SearchQuery.java, src/main/java/org/jabref/model/search/rules/GrammarBasedSearchRule.java, src/main/java/org/jabref/model/search/rules/SearchRules.java, src/test/java/org/jabref/model/search/rules/ContainBasedSearchRuleTest.java, src/test/java/org/jabref/model/search/rules/GrammarBasedSearchRuleTest.java
Fixes #6777 . The issue originates in how the JavaScript regexp is created in `PreviewViewer#highlightSearchPattern`.
1. Fixes the use of regexp while searching for one term (e.g., `Liu.*`)
2. Fixes exception in the preview when forward slash is used in the regexp
=> Fixes exception in preview using regexp search and regexp search without specified field

src/main/java/org/jabref/gui/search/GlobalSearchBar.java
This PR fixes the issue related to the regex and case sensitive search buttons disappearing if the search bar is not empty. This addresses the issue raised by @k3KAW8Pnf7mkmdSMPHz27 in https://github.com/JabRef/jabref/issues/7123.
Here how it currently looks if something else (WebSearchBar) is focused and the bar is nonempty:
In case of an empty search bar:
=> Fix binding issue for the regex and case sensitive search buttons

src/main/java/org/jabref/gui/StartLiteratureReviewAction.java, src/main/java/org/jabref/logic/crawler/Crawler.java, src/test/java/org/jabref/logic/crawler/CrawlerTest.java
This PR fixes the issue with the githandler NPE for the CrawlerTest.java on the CI server that does not have any git credentials configured
Signed-off-by: Dominik Voigt <dominik.ingo.voigt@gmail.com>
=> Add githandler mock to crawler test to fix NPE

CHANGELOG.md, src/main/java/org/jabref/gui/documentviewer/DocumentViewerViewModel.java, src/main/java/org/jabref/gui/documentviewer/PdfDocumentPageViewModel.java, src/main/java/org/jabref/gui/documentviewer/PdfDocumentViewModel.java
Turned out it was an off by one error.
Fixes #7108
=> Fix document viewer not showing first page

CHANGELOG.md, src/main/java/org/jabref/gui/shared/SharedDatabaseLoginDialogView.java
Fixes #6869
A binding was missing 🤦
=> Fix remembering password for sql db

CHANGELOG.md, src/main/java/org/jabref/gui/actions/ActionHelper.java, src/main/java/org/jabref/gui/shared/PullChangesFromSharedAction.java
Fixes #6959 implementing the method `needsSharedDatabase` in the `ActionHelper` and then binding it in the class `PullChangesFromSharedDatabase`. This solution prevents the user from clicking "Pull changes from database" if a shared database is not present.
When the DatabaseLocation is **local**:
When the DatabaseLocation is **shared**:
When there is **no library open**:
=> Fix for issue 6959

src/main/java/org/jabref/preferences/JabRefPreferences.java, src/main/resources/resource/layout/din1505/din1505winword.article.layout
=> Fixed issue in PreviewView for number textfield

build.gradle
Refs https://github.com/java9-modularity/gradle-modules-plugin/issues/170
This only fixes the plugin. Not the errors in the javadoc
For fixing the javadoc https://github.com/koppor/jabref/issues/475
=> Fix javadoc plugin complaining about missing exports

src/main/java/org/jabref/gui/externalfiles/DownloadFullTextAction.java, src/main/resources/l10n/JabRef_en.properties
Remove redundant code
While debugging for #7152  I found that the file is downloaded, but not linked to the library afterwards. 
Fortunately I could just replace it with the specific download method already defined.
=> Fix file not linked after DL from fulltext fetcher

src/main/java/org/jabref/gui/LibraryTab.java
not on fx thread with shared database
=> Fixed setting of tab title in wrong thread

src/main/java/org/jabref/gui/JabRefFrame.java
This PR addresses the issue of integrating the SLR feature in the planned release version without #7126 by disabling it.
Refs #7168
=> Disable SLR in UI until #7126 is merged

.idea/runConfigurations/JabRef_Main.xml
In `processResoures`, we only copy author information and keys into the build:
https://github.com/JabRef/jabref/blob/86e2c82cbe0eb8ca18f1b80f7b85b375cc316ad7/build.gradle#L263
It taskes a very long time for compilation. With removing that, we should be able to speed-up compilation
Regarding following, I did not do anyithing in the UI:
```xml
<option name="REDIRECT_INPUT" value="true" />
```
=> Remove processResources to speedup build

CHANGELOG.md, src/main/java/org/jabref/logic/shared/DBMSProcessor.java, src/test/java/org/jabref/logic/shared/DBMSProcessorTest.java, src/test/java/org/jabref/logic/shared/DBMSSynchronizerTest.java
Fixes #7176 
Should also fix #6944 
Newly added entries have empty fields; don't update the field table to prevent SQL Exception
Fix shared entry not found by id
use left outer join for this
=> Fix newly added entry not synced to db

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fileformat/PdfContentImporter.java, src/test/java/org/jabref/logic/importer/fileformat/PdfContentImporterTest.java
=> Fix pdf content importer exception if DOI is empty

CHANGELOG.md, src/main/java/org/jabref/logic/integrity/FieldCheckers.java
=> Remove field check for journal abbrev in entry editor

src/main/java/org/jabref/gui/DefaultInjector.java, src/main/java/org/jabref/gui/Globals.java, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/desktop/JabRefDesktop.java, src/main/java/org/jabref/gui/edit/CopyDoiUrlAction.java, src/main/java/org/jabref/gui/entryeditor/fileannotationtab/FileAnnotationTabViewModel.java, src/main/java/org/jabref/gui/maintable/MainTable.java, src/main/java/org/jabref/gui/preview/PreviewViewer.java
=> Fix ClipboardManager <-> Prefs ordering

build.gradle, gradle.properties
`processResources` task was very slow:
```terminal
$ gradlew processResources
> Configure project :
Project : => 'org.jabref' Java module
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
BUILD SUCCESSFUL in 49s
1 actionable task: 1 executed
```
Speed up by:
1. Pointing to the files to be modified directly
2. Add [gradle file system watcher](https://blog.gradle.org/introducing-file-system-watching)
```terminal
@ C:\git-repositories\jabref\jabref
$ gradlew --watch-fs -Dorg.gradle.vfs.verbose=true processResources
Watching the file system is an incubating feature.
Received 7 file system …
```
=> Speedup processResources

build.gradle, src/main/java/org/jabref/gui/JabRefMain.java, src/main/java/org/jabref/logic/l10n/Localization.java, src/main/resources/build.properties, src/main/resources/l10n/JabRef_en.properties
Before:
```
Skipped patching sourcecode_2.12-0.1.4.jar into test3
19:45:34.512 [JavaFX Application Thread] ERROR org.jabref.logic.l10n.Localization - Messages are not initialized before accessing key: Your current Java version (%0) is not supported. Please install version %1 or higher.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
BUILD SUCCESSFUL in 1m 38s
```
After:
Output on console reporting Java version errors.
```
20:11:40.714 [JavaFX Application Thread] ERROR org.jabref.logic.l10n.Localization - Messages are not initialized before accessing key: Your current Java version …
```
=> Output java error on console, too

src/main/java/org/jabref/logic/importer/fetcher/ComplexSearchQuery.java, src/test/java/org/jabref/logic/importer/fetcher/CompositeSearchBasedFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/JstorFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/TitleFetcherTest.java
This PR fixes some of the failing fetcher tests specified in #6369.
Namely:
=> Fix some fetcher test

docs/readings-on-coding/javafx.md
Fixes a broken external link
From https://fxdocs.github.io/docs/index.html to https://fxdocs.github.io/docs/html5/index.html
=> fxdocs changed their URL

CHANGELOG.md, src/main/java/org/jabref/logic/importer/WebFetchers.java
We cannot get the ACM fetcher working (#5804) nor the Google Scholar (#7075). JSTOR has a traffic limit. Thus, we disabled them.
=> Disable ACM, Google Scholar, JSTOR

CHANGELOG.md, buildres/linux/jabrefHost.py
This PR adds the flatpak support in the native messaging script used by the web extension.
It has been tested locally and will need a change in the flatpak to auto-install the json file with the correct path (like the other packages do).
I'll update the changelog and the documentation.
=> Added a check to integrate with the flatpak package

CHANGELOG.md, src/main/java/org/jabref/gui/Base.css
What:
- Fix style of checkboxes while searching in preferences
Why:
- The "unchecked" behaviour, while distinct from the "checked", is confusing since it still has a checkmark in it. This is a visual bug, the behaviour is still correct.
Fixes #7226
=> Fix style of highlighted checkboxes while searching in preferences

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java, src/test/java/org/jabref/gui/fieldeditors/LinkedFileViewModelTest.java
Fix equals in path method
Fixes #7194
The dialog is now only disable when the file is already in the file directory
=> Only disable  move to file dir when path equals

src/main/java/org/jabref/logic/util/strings/HTMLUnicodeConversionMaps.java
Fixes #7291. There is a typo in the unicode <-> latex <-> HTML conversion.
=> Fix typo in conversion for small pi

docs/adr/0018-implement-special-fields-as-seperate-fields.md
As input for https://github.com/JabRef/jabref/issues/6840
This writes down the ADR for special fields discussed at #JabCon.
Result: We have special fields as "normal" BibTeX key/value fields. We do not have synchronization of keywords any more.
Documentation: This will obsolete the last paragraph at https://docs.jabref.org/finding-sorting-and-cleaning-entries/specialfields#configuration-of-the-storage-mode-in-the-library.
For the brave: The ADR can be edited using the UI available at https://github.com/koppor/adr-manager/.
=> Add special fields ADR

CONTRIBUTING.md, docs/contributing.md
We have https://devdocs.jabref.org as central hub for developer's documentation. Why not also the one to contribute code? Thus, I moved the contents of `CONTRIBUTING.md` to `docs/contributing.md`.
After merging, it will nicely render at https://devdocs.jabref.org/contributing.
After merging, the link at https://docs.jabref.org/faqcontributing needs to be updated to https://devdocs.jabref.org/contributing (to avoid users navigating to `CONTRIBUTING.md` and then to the long text).
=> Make CONTRIBUTING.md much shorter. Move long text to docs/contributing.md

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
Add links to the discourse forum. When you are attempting to open an issue to JabRef,
---
---
**this is what is shown right now**,
---
---
and with the current version of GitHub, **this is what I want to change it to**,
---
---
Clicking the links will open https://discourse.jabref.org/c/help/ or https://discourse.jabref.org/c/features/ .
This relates to a recent issue since neither I nor the creator of the issue ticket appear to have noticed/known that it should have been in the discourse and not it in issue tracker (sorry :flushed:)
=> Update the templates for opening a new issue

CHANGELOG.md, src/main/java/org/jabref/gui/preferences/AppearanceTabViewModel.java, src/main/java/org/jabref/gui/preview/PreviewViewer.java, src/main/java/org/jabref/gui/util/DefaultFileUpdateMonitor.java, src/main/java/org/jabref/gui/util/Theme.java, src/main/java/org/jabref/model/strings/StringUtil.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/test/java/org/jabref/gui/util/ThemeTest.java, src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Fixes #7177 "Java Exception when trying to open the preferences with missing custom theme"
After some testing I found that there two main paths that could result in the same failure: the CSS file being missing before application start, and changing the name of the CSS file while the application is running. To resolve the latter, I think the best approach is to check the custom CSS file exists.
This is already done for the Theme as used for most of the application, however the Preview Viewer has it's own CSS URL logic.
Rather than add file checking logic to the Preview Viewer, I have refactored and moved the theme logic of Preview Viewer into Theme, so that all CSS URL logic is encapsulated in that class. I have also put the logic that checks that the URL is valid and filters it to an …
=> Fixed exception about missing custom css file

.github/workflows/snap.yml
This PR tries to fix upload to snapcraft.
Before this PR:
```
Run snapcore/action-publish@v1
with:
store_login: ***
snap: jabref_5.2.376_amd64.snap
release: edge
Publishing snap "jabref_5.2.376_amd64.snap"...
/snap/bin/snapcraft login --with /tmp/login-data-37F4mR/login.txt
Unexpected error when obtaining your account information.
Login failed.
Error: The process '/snap/bin/snapcraft' failed with exit code 1
```
See https://github.com/JabRef/jabref/runs/1605853743
=> Fix snapcraft upload

src/main/java/org/jabref/preferences/JabRefPreferences.java
So that users find these features more easily.
=> Add some special fields as default columns

src/test/java/org/jabref/logic/importer/fetcher/GoogleScholarTest.java, src/test/java/org/jabref/logic/importer/fetcher/JstorFetcherTest.java
Disable GoogleScholar and JSTOR. (Refs #7229)
Other fetchers will be fixed later.
=> Disable certain fetcher tests on CI

src/main/java/org/jabref/gui/preview/PreviewViewer.java
Fixes #7344.
Apparently I did not pay enough attention while copy-pasting in Intellij, or checking the method again afterward. See https://github.com/JabRef/jabref/pull/7073#pullrequestreview-526937823 for the original regex. Note that to reproduce it in the current JabRef you need to have the preview pane open while searching.
Sorry about this one.
=> Fixes regex (again) in PreviewViewer

CHANGELOG.md, src/main/java/org/jabref/logic/msbib/MSBibConverter.java, src/test/resources/org/jabref/logic/exporter/MsBibUrlDate.bib, src/test/resources/org/jabref/logic/exporter/MsBibUrlDate.xml
=> Export urldate to MSOffice

CHANGELOG.md, src/main/java/org/jabref/logic/exporter/ExporterFactory.java, src/main/resources/resource/layout/harvard/harvard.article.layout, src/main/resources/resource/layout/harvard/harvard.book.layout, src/main/resources/resource/layout/harvard/harvard.inbook.layout, src/main/resources/resource/layout/harvard/harvard.incollection.layout, src/main/resources/resource/layout/harvard/harvard.inproceedings.layout, src/main/resources/resource/layout/harvard/harvard.layout, src/main/resources/resource/layout/harvard/harvard.mastersthesis.layout, src/main/resources/resource/layout/harvard/harvard.phdthesis.layout, src/main/resources/resource/layout/harvard/harvard.proceedings.layout, src/test/java/org/jabref/logic/layout/format/RTFCharsTest.java
The layout files were still using the old formatter chaining for authors and therefore were responsible for removing braces 
Also fix extension.
Fixes #4508
=> Fix harvard exporter by changing AuthorsFormatter

CHANGELOG.md, src/main/java/org/jabref/gui/shared/SharedDatabaseLoginDialogViewModel.java
=> Fix an issue where the password for a shared SQL database was only remembered if it was the same as the username

src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/gui/citationkeypattern/GenerateCitationKeyAction.java, src/main/java/org/jabref/gui/cleanup/CleanupAction.java, src/main/java/org/jabref/gui/importer/ImportEntriesViewModel.java, src/main/resources/l10n/JabRef_en.properties
This pull request is to fix issue #6334 /  Finding duplicates
The previous message at duplicates found dialog was not so descriptive as it is marked at the issue #6334 
Modify ImportEntriesViewModel to show a more explicit message when a duplicate is found.
=> Modify message at the duplicates found dialog

src/main/java/org/jabref/gui/Globals.java
Follow-up to #6990, where the empty string is set at `build.properties` if no data is availble. Especially:
```properties
azureInstrumentationKey=
```
This leads to `throw new IllegalArgumentException("key");` at `com.microsoft.applicationinsights.TelemetryConfiguration#setInstrumentationKey`. This PR fixes that.
=> Fix Exception if no AzureInstrumentationKey is available

src/main/java/org/jabref/gui/importer/fetcher/WebSearchPane.java
Improves the UX of the web search by triggering it if the enter key is pressed while the search field is focused.
Refs a [user issue](https://discourse.jabref.org/t/web-search-doesnt-start-with-pressing-enter-key/2513/2).
=> Trigger websearch using enter

src/main/java/org/jabref/gui/Base.css, src/main/java/org/jabref/gui/externalfiles/FileExtensionViewModel.java, src/main/java/org/jabref/gui/externalfiles/UnlinkedFilesCrawler.java, src/main/java/org/jabref/gui/externalfiles/UnlinkedFilesDialog.fxml, src/main/java/org/jabref/gui/externalfiles/UnlinkedPDFFileFilter.java, src/main/java/org/jabref/logic/util/FileType.java, src/main/java/org/jabref/logic/util/StandardFileType.java, src/main/java/org/jabref/logic/util/UnknownFileType.java, src/main/java/org/jabref/logic/util/io/DatabaseFileLookup.java, src/main/resources/l10n/JabRef_en.properties
Fixes part of #7383
- File Filter now works with directories
- Better File type description
=> Fix File Filter and some layout issues

CHANGELOG.md, src/main/java/org/jabref/gui/Base.css, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java
In the original version, the file path is not visually good due to its font color. After a hard debuging process, I find that we don't bind the property of text with "css" and then the text color is black by default. Such that, I bind them and change the color the text and it looks wonderful now. Fixes #7382 
**Light Theme**
**Dark Theme**
=> Fixed invisible file path in the dark theme

CHANGELOG.md, src/main/java/org/jabref/gui/Base.css, src/main/java/org/jabref/gui/preferences/AppearanceTab.fxml
As the preferred width for the fontsize spinner under prefrences/appearence was set to a fixed pixel size, I changed it to use the `em` measure instead. A style class called `fontsizeSpinner` was added to `Base.css` with this change. 
Fixes #7085.
=> Fixes issue of Changing font size makes font size field too small

src/main/java/org/jabref/gui/importer/fetcher/WebSearchPane.java, src/main/java/org/jabref/gui/importer/fetcher/WebSearchPaneViewModel.java, src/main/resources/l10n/JabRef_en.properties
This PR removes unuseful feedback from the web search text field, as it is not necessary and provides no advantage.
With the introduction of transformers in #7350, the syntax feedback will be adapted  and provide adequate and useful feedback.
Fixes #7349, addresses #7277.
=> Remove unuseful search syntax feedback

CHANGELOG.md, src/main/java/org/jabref/gui/preview/PreviewPanel.java, src/main/java/org/jabref/gui/preview/PreviewViewer.java, src/main/resources/l10n/JabRef_en.properties
Fixes #6962 
Added a feature that allows users to copy highlighted text in the preview window
Screenshot:
=> add selection copy to preview window

CHANGELOG.md, src/main/java/org/jabref/gui/util/DefaultFileUpdateMonitor.java, src/main/java/org/jabref/logic/importer/util/GroupsParser.java, src/main/java/org/jabref/model/groups/TexGroup.java
Fixes https://github.com/JabRef/jabref/pull/7173#issuecomment-768998167 in #7173.
On Ubuntu Linux the auto-update functionality does not work with `TexGroup`s, when the associated `.aux` file gets updated externally.
<strike>This is a quick fix for this issue, which may still be improved. Only one of both files needs to be changed in order to fix it.</strike>
=> Fixes the auto-update problem with TexGroups on Ubuntu Linux and makes the detection of file modifications more reliable

CHANGELOG.md, src/main/java/org/jabref/gui/preferences/appearance/AppearanceTab.java
=> Fixes the issue "Non valid number as font size results in an uncaught exception."

CHANGELOG.md, src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogViewModel.java, src/test/java/org/jabref/gui/autocompleter/ContentSelectorSuggestionProviderTest.java, src/test/java/org/jabref/gui/contentselector/ContentSelectorDialogViewModelTest.java, src/test/java/org/jabref/gui/contentselector/ContentSelectorViewModelTest.java
List of keywords added in "Manage content selectors" is now always displayed in alphabetic order. Also added tests for ContentSelectorSuggestionProvider and ContentSelectorDialogViewModel classes which include asserting alphabetical order in suggestions affected by content selectors as well.
Fixes #3791.
=> Sorted list of content selectors

CHANGELOG.md, buildres/linux/jabrefHost.py, buildres/mac/jabrefHost.py
In general, it is recommended to use `#!/usr/bin/env python3` as the shebang instead of the hardcoded `!#/usr/bin/python3`.
See <https://stackoverflow.com/a/5709632> for more information.
Related to [JabRef-Browser-Extension #177](https://github.com/JabRef/JabRef-Browser-Extension/issues/177), especially [this comment](https://github.com/JabRef/JabRef-Browser-Extension/issues/177#issuecomment-640054939).
=> Use env to determine python3 location

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/LibraryTab.java
Fixes #7464
When loading/opening a bib file a new "normal" Tab is inserted to indicate loading. That is later removed again and it's not an instanceof our LibraryTab
=> Fix drag and drop of bib files 

CHANGELOG.md, src/main/java/org/jabref/gui/openoffice/OOBibBase.java, src/main/java/org/jabref/gui/openoffice/OpenOfficePanel.java, src/main/resources/l10n/JabRef_en.properties
Implemented "Unmerge citations" in the Openoffice/Libreoffice
integration panel. 
Fixes #7454(https://github.com/JabRef/jabref/issues/7454)
No, tests were not created.  Do you have GUI tests?
There is a known problem: "Merge citations" does not save the information needed
to find the optional extra info (like page reference) stored in document properties.
When reestablishing the individual references in unCombineCiteMarkers,
getUniqueReferenceMarkName() may or may not return the original name.
When it does not, the extra info may be lost, or even taken from another entry.
A solution could be to encode the number making the originals unique
in the merged name: in stead of  "JR_cite_1_XX2000a,YY2010" it would be e.g.
"JR_cite_1_XX2000a,1_YY2010". Apart from construction and parsing, …
=> Unmerge LO citations

CHANGELOG.md, src/main/java/org/jabref/preferences/JabRefPreferences.java
#7441 Add user name caching, because on mac `InetAddress.getLocalHost().getHostName()` operation is slow. Problem described [here](https://stackoverflow.com/questions/33289695/inetaddress-getlocalhost-slow-to-run-30-seconds)
=> Fixed freeze for few seconds on DNS timeout in MacOS

CHANGELOG.md, src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/gui/autocompleter/SuggestionProviders.java, src/test/java/org/jabref/gui/autocompleter/FieldValueSuggestionProviderTest.java
This fixes issue described in #7320. Even though user could choose fields on which autocomplete should not work it had no actual effect.
=> Fixed switching off autocomplete on specific fields

CHANGELOG.md, src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogView.java, src/main/java/org/jabref/model/entry/field/UnknownField.java
We Fix the issue that Content selector does not seem to work for custom fields. This issue actually do not affect the correctness of running and just show a ugly output in the frontend. So I simply change the 'toString()' method in UnkownField class. This method do not make any effect to other functions but the user interface shown in the issue.
fixes #6819
=> fix: fix content selector for custom fields

build.gradle, src/main/java/org/jabref/logic/citationstyle/CSLAdapter.java
The `SNAPSHOT` version of citeproc-java changed the constructor. Thus, JabRef did not compile when fetching the latest SNAPSHOT from maven central.
This PR fixes the constructor.
It also changed build.gradle to trigger a refetch of all dependencies in our CI.
=> Hotfix: Fix compilation error

build.gradle
https://github.com/openjdk/jfx/blob/master/doc-files/release-notes-16.md
=> Update to javafx 16

snap/snapcraft.yaml
Fixes #7515 
The snap cannot correctly unpack the env declaration, since python is not contained in the snap but is in a base snap (core18)
This fix reverts only the version in the snap, so the other builds still work with the env variables.
The flatpak needs checking.
=> Revert env path in snap python

CHANGELOG.md, src/main/java/org/jabref/gui/Dark.css
fixes  #7481
Color fix
Dark.css update to extend to the custom color picker
Custom-color-picker background was white instead of dark
Custom-color-picker background is now dark and matches dark theme
=> Extends dark theme to group custom-color-picker

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java
Fixes #7465
Now double click onto the file just open the file and edit prompt can be accessed through a new right-click > Edit option.
=> Fix double-click onto file in file list to just open the file

CHANGELOG.md, build.gradle, src/main/java/org/jabref/gui/externalfiletype/ExternalFileTypes.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java, src/main/resources/l10n/JabRef_en.properties, src/test/java/org/jabref/gui/fieldeditors/LinkedFileViewModelTest.java
Adds ignore parameter to `mimeType` and notify the user if the downloaded file is of HTML type, fixes #7452.
In the method `ExternalFileTypes::getExternalFileTypeByMimeType`, we added a feature to remove the parameters part
of the `mimeType`, this is allowed in mimeType-specification [link](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types). The previous code didn't consider the parameter part of the mimeType, thus not conforming to the correct enum type in `StandardExternalFileType.java`.
We also added a feature to notify the user if the downloaded link is a HTML file, via the "status bar", because the user might think they have downloaded a PDF while this isn't the case.
=> PDF Downloader downloads HTML source code instead if no access 

CHANGELOG.md, src/main/java/org/jabref/gui/externalfiletype/ExternalFileTypes.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java, src/main/resources/l10n/JabRef_en.properties, src/test/java/org/jabref/gui/fieldeditors/LinkedFileViewModelTest.java
=> Dd2480 2021 group 22 fix for issue 7452

src/main/java/org/jabref/gui/Dark.css
Fixes #5522 
1. Adding patterns to the entries background in dark theme.
2. Visibility issue with the group item number coloration when an item is assigned to a new group as mentioned in https://github.com/JabRef/jabref/issues/5522#issuecomment-643632385
=> Fix for issue 5522 and some UI changes.

src/main/java/org/jabref/gui/icon/IconTheme.java, src/main/java/org/jabref/gui/icon/InternalMaterialDesignIcon.java
Fixes #4129
Replaced the default group play icon by small circle.
I think this also fixes #7550.
=> UI: Fix for group icon

CHANGELOG.md, src/main/java/org/jabref/gui/maintable/MainTable.java
fixes #6851
Drag & Drop into empty library
Fixes issue preventing files from being "dragged & dropped" into an
empty library
Added a drag/drop handlers on the table-view to allow for files
to be drag & drop into an empty library
=> Fix drag and drop into empty library

CHANGELOG.md, build.gradle
I had to add 'org.mariadb.jdbc.authentication.AuthenticationPlugin' in build.gradle (in mergedModule) for the shared database feature to work properly.
I have a MariaDB database with the [pam_user_map](https://mariadb.com/kb/en/user-and-group-mapping-with-pam/) plugin activated. Login with an existing user in the database works well with the current code base but using a mapped user led to the error message below. This PR fixes this error.
```
java.util.ServiceConfigurationError: org.mariadb.jdbc.authentication.AuthenticationPlugin: module org.jabref.merged.module does not declare `uses`
at java.base/java.util.ServiceLoader.fail(Unknown Source)
at java.base/java.util.ServiceLoader.checkCaller(Unknown Source)
at java.base/java.util.ServiceLoader.<init>(Unknown Source)
at …
```
=> Fix AuthentificationPlugin not declared in mergedModule

.github/workflows/deployment.yml
As @tobiasdiez developer account is no longer valid, I disable the notarization until we have our e.V. account,  so that other dev builds are still uploaded.
=> Dsiable notarisation for mac until we hae an account for JabRef e.V.

docs/getting-into-the-code/code-howtos.md
This was long in my email inbox. Since there is some testing activity, I thought it is a good thing to work on now.
=> Add some hints on test tooling

.github/workflows/deployment.yml
PRs of users cannot build Mac OS. See https://github.com/JabRef/jabref/pull/7577 for example. With this PR this should be skipped.
=> Skip Mac OS build if secret not present

CHANGELOG.md, src/main/java/org/jabref/model/entry/Date.java
#7265 Changed to simpleDateFormatter it doesn't throw a lot of exception
=> Optimize saving

src/test/java/org/jabref/gui/autocompleter/AppendPersonNamesStrategyTest.java, src/test/java/org/jabref/gui/autocompleter/PersonNameStringConverterTest.java, src/test/java/org/jabref/gui/edit/ReplaceStringViewModelTest.java
Test coverage for org.jabref.gui package is rather low (8%). This pull request adds unit tests to 3 classes under the gui package, increasing their respective line coverage from 0% to 100%. They contribute to issue #6207.
Tests added:
1. AppendPersonNamesStrategyTest
2. PersonNameStringConverterTest
3. ReplaceStringViewModelTest
=> Add unit tests for org.jabref.gui classes

src/main/java/org/jabref/gui/commonfxcontrols/SaveOrderConfigPanel.fxml, src/main/java/org/jabref/gui/commonfxcontrols/SaveOrderConfigPanel.java, src/main/java/org/jabref/gui/libraryproperties/LibraryPropertiesDialog.fxml, src/main/java/org/jabref/gui/libraryproperties/LibraryPropertiesDialogView.java, src/main/resources/l10n/JabRef_en.properties
fix for 7517, change Export to Save
Fixes #7517
=> Change export to save

CHANGELOG.md, src/main/java/org/jabref/gui/desktop/JabRefDesktop.java, src/main/java/org/jabref/gui/fieldeditors/IdentifierEditorViewModel.java, src/main/java/org/jabref/gui/maintable/MainTable.java, src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java, src/main/java/org/jabref/gui/maintable/OpenUrlAction.java, src/main/java/org/jabref/gui/maintable/RightClickMenu.java, src/main/java/org/jabref/gui/maintable/columns/LinkedIdentifierColumn.java
As mentioned in 
Fixes #7337 the option to choose custom DOI base address did not propagate to `LibraryTab` and this PR aims to solve exactly that. In the process I refactored `LinkedIdentifierColumn` so that it uses `OpenUrlAction` as well.
=> Custom DOI base address fix

CHANGELOG.md, src/main/java/org/jabref/gui/duplicationFinder/DuplicateSearch.java
resolves #7366
When processing duplicate entries,
Possible Duplicates dialog gave no indication as to progress.
To address this lack of feedback,
a progress counter was added to the title bar.
The title property now contains two updatable properties:
1) A total count of all duplicates
2) a count of how many duplicates have already been addressed
They are updated with listeners and bindings to
provide real time feedback.
--- 
Note: because of the use of different threads, the total-count could not be directly bound so an extra variable and listener are required. Also line 88 was removed and `duplicateCount.getAndIncrement()` was changed from `getAndIncrement()` to `incrementAndGet()` so returned value could be used.
---
=> Adds progress count to Possible Duplicates dialog

.github/workflows/deployment.yml
=> update to JabRef e.V. apple certs

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fetcher/ArXiv.java, src/main/java/org/jabref/model/strings/StringUtil.java, src/test/java/org/jabref/logic/importer/fetcher/ArXivTest.java
Fix [#7633](https://github.com/JabRef/jabref/issues/7633)
1 Open library, select the .bib file as below
```
@Article{zhang_machine_2021v2,
author  = {Zhang, Ruohan and Guo, Sihang and Liu, Bo and Zhu, Yifeng and Hayhoe, Mary and Ballard, Dana and Stone, Peter},
journal = {arXiv:2010.15942v2 [cs]},
title   = {Machine versus {Human} {Attention} in {Deep} {Reinforcement} {Learning} {Tasks}},
year    = {2021},
month   = feb,
url     = {http://arxiv.org/abs/2010.15942v2},
}
```
2 Double click the entry and then click the **Get fulltext** on the right of **general | file **, it will give a message of "No full text document found"
3 And if we erase the curly brackets in the title, with other keep the same, it will download the pdf file successfully , the new title is given below
```
Machine …
```
=> Fix for issue 7633: Unable to download arXiv pdfs if Title contains curly brackets

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java, src/main/java/org/jabref/logic/net/URLDownload.java, src/main/resources/l10n/JabRef_en.properties
Fixes #7616 
File download path: https://www.serbski-institut.de/os/dnlarchiv/Kleine_Reihe_27_web.2217.pdf
<br>
A valid authentication path cannot be found from the site where the downloaded file is located, prompting the user with the option of whether to continue the download.
<br>
The user chooses to cancel the download.
<br>
The user chooses to download anyway.
=> Fix SSLHandshake Exception by using bypass

CHANGELOG.md, src/main/java/org/jabref/gui/Base.css
Fixes #7195 
Opacity of disabled icon-buttons
Add the disabled icon style in `Base.css`
- No tabs opened:
- Open a tab and do not select any entry:
- Select an entry in the opened tab:
=> Fix#7195 partly Opacity of disabled icon-buttons

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fetcher/ArXiv.java, src/test/java/org/jabref/logic/importer/fetcher/ArXivTest.java
Fixes #7660
1. Run EprintCleanup on a copy of the entry the ArXiv fetcher is fetching before getting arXiv id from the eprint field;
2. Add two test method. One finds full text with title containing colon and journal, while another finds full text with title containing colon and url.
When finding full text, this BibTeX reference works:
```
@Article{booth_bayes-trex_2020,
author        = {Serena Booth and Yilun Zhou and Ankit Shah and Julie Shah},
journal       = {arXiv:2002.10248v4 [cs]},
title         = {Bayes-TrEx: a Bayesian Sampling Approach to Model Transparency by Example},
year          = {2020},
month         = dec,
archiveprefix = {arXiv},
eprint        = {2002.10248},
url           = {http://arxiv.org/abs/2002.10248v4},
}
```
But when `eprint` field is missing, no full text will …
=> Fixes Jabref#7660 Unable to download some arXiv links if the "eprint" field is missing

CHANGELOG.md, src/main/java/org/jabref/logic/importer/ImportCleanup.java, src/main/java/org/jabref/model/entry/BibEntry.java
We fix the issue that uncaught exception when searching in dark mode. In fact, we found that this issue is not a dark mode issue and this is a threading issue. So we use Platform.runLater() to ensure that there will be no conflicts when adding key-value pairs to the map.
fixes [#7343](https://github.com/JabRef/jabref/issues/7343)
=> Fix exception when searching

src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/exporter/ExportToClipboardAction.java, src/main/java/org/jabref/gui/maintable/RightClickMenu.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/main/java/org/jabref/preferences/PreferencesService.java, src/test/java/org/jabref/gui/edit/CopyMoreActionTest.java, src/test/java/org/jabref/gui/exporter/ExportToClipboardActionTest.java, src/test/java/org/jabref/gui/importer/NewEntryActionTest.java
This pull request replaces #7635 (closed/not merged), and it contributes to issue #6207, which is to add more unit tests to the project,  in this case specifically in the gui package using test doubles.
Tests added:
NewEntryActionTest
CopyMoreActionTest
ExportToClipboardActionTest
In order to add the ExportToClipboardActionTest and to migrate to using PreferencesService, code refactoring has been done as suggested by @Siedlerchr. The purpose of the refactoring is to add PreferencesService as a parameter in the constructors of ExportToClipboardAction to replace the Globals variable. Refactored classes are as follows:
ExportToClipboardAction.java 
JabRefFrame.java 
RightClickMenu.java 
JabRefPreferences.java 
PreferencesService.java
=> Add more unit tests to three gui classes 

src/main/java/org/jabref/gui/maintable/MainTable.java
=> delete bug fix

CHANGELOG.md, src/main/java/org/jabref/gui/importer/ImportEntriesViewModel.java, src/main/java/org/jabref/logic/importer/fetcher/CompositeSearchBasedFetcher.java
=> Fix threading cleanup in performSearch

CHANGELOG.md, src/main/java/org/jabref/gui/mergeentries/FetchAndMergeEntry.java
Fixes #6267
Cleanup did use the wrong entry
=> Fix cleanup run on wrong entry when fetching from DOI

CHANGELOG.md, src/main/java/org/jabref/logic/msbib/MSBibConverter.java, src/test/resources/org/jabref/logic/exporter/MsBibExportFormatTestDay.xml, src/test/resources/org/jabref/logic/exporter/MsBibExportFormatTestDayBiblatex.bib, src/test/resources/org/jabref/logic/exporter/MsBibExportFormatTestDayBiblatex.xml
Fixes https://discourse.jabref.org/t/export-month-as-text-not-number/2685
The month field is also the full name in the example listed here https://docs.microsoft.com/de-de/dotnet/api/documentformat.openxml.bibliography.month?view=openxml-2.8.1
=> MS Office XML: Export month name

build.gradle, docs/advanced-reading/fetchers.md, src/main/java/org/jabref/logic/importer/fetcher/ScienceDirect.java, src/main/java/org/jabref/logic/util/BuildInfo.java
This PR aligns the key handling code of ScienceDirect to the one of other fetchers.
=> Make key for ScienceDirect configurable

src/main/java/org/jabref/logic/importer/fetcher/ArXiv.java, src/main/java/org/jabref/model/strings/StringUtil.java, src/test/java/org/jabref/logic/importer/fetcher/ArXivTest.java
arXiv does not use `https`, but `http`. Fixed in the test.
I also added some code comments to the fetcher
=> Fix arXiv fetcher tests

src/test/java/org/jabref/logic/integrity/NoBibTexFieldCheckerTest.java
This pull request contributes to issue #6207, which is to add more unit tests or improve existing ones. I used Pitest to compute the mutation coverage and found that some conditions were not covered in the unit test and some conditions tested were redundant because they would not be reached.  Following are the changes:
1. Switched to using parametrized test
2. Covers missing conditions: StandardField.DOI, StandardField.URL
3. Redundant conditions (still remains in source code and tests): StandardField.ABSTRACT, StandardField.COMMENT (they are not included in the fields of neither BibtexEntryTypeDefinitions.ALL nor BiblatexEntryTypeDefinitions.ALL)
Before:
After:
=> Refactor NoBibTexFieldCheckerTest to increase mutation coverage

src/main/java/org/jabref/logic/importer/fetcher/ScienceDirect.java, src/test/java/org/jabref/logic/importer/fetcher/ScienceDirectTest.java
For the test PDF, the json structure does not contain the full text any more. One has to use other meta data. This PR does that
Excerpt of new meta data:
```json
"pdfDownload": {
"linkType": "DOWNLOAD",
"isPdfFullText": false,
"urlMetadata": {
"queryParams": {
"md5": "2b19b19a387cffbae237ca6a987279df",
"pid": "1-s2.0-S1674775515001079-main.pdf"
},
"pii": "S1674775515001079",
"pdfExtension": "/pdfft",
"path": "science/article/pii"
}
},
```
=> Fix ScienceDirect fetcher

src/test/java/org/jabref/logic/integrity/DoiDuplicationCheckerTest.java
This pull request contributes to issue #6207, which is to add more unit tests or improve existing ones. I used Pitest to compute the line and mutation coverage. Since DoiDuplicationChecker did not have its unit test (its method was being tested in other test classes), I added the test to increase both coverages. 
Before:                                                                            
After:
=> Added DoiDuplicationCheckerTest to increase coverage

CHANGELOG.md, src/main/java/org/jabref/gui/preferences/preview/PreviewTabViewModel.java, src/main/resources/l10n/JabRef_en.properties
Refs #5464 
1. Options -> Preference -> Entry Preview
2. Change the setting of `Show preview as a tab in the entry editor.`
3. Save
Then we can find that the preview still exists in Entry Editors:
When detects the change of preview settings, throw a warning:
In code, I detect the change and add the warning. 
```
if (showAsExtraTab.getValue() != initialPreviewPreferences.showPreviewAsExtraTab()) {
restartWarning.add(Localization.lang("Preview settings changed."));
}
```
=> Refs for issue 5464: Entry preview as tab: Full change only takes effect after restart of program

gradle/wrapper/gradle-wrapper.properties
Update Gradle Wrapper from 7.0 to 7.0.2.
Read the release notes: https://docs.gradle.org/7.0.2/release-notes.html
---
- Gradle release: `7.0.2`
- Distribution (-bin) zip checksum: `0e46229820205440b48a5501122002842b82886e76af35f0f3a069243dca4b3c`
- Wrapper JAR Checksum: `e996d452d2645e70c01c11143ca2d3742734a28da2bf61f25c82bdc288c9e637`
---
<details>
<br /> …
=> Update Gradle Wrapper from 7.0 to 7.0.2

src/test/java/org/jabref/logic/bibtex/BibEntryWriterTest.java
Add unit test to BibEntryWriterTest.java in order to cover previously uncovered method serializeAll().
=> Add unit test for serializeAll() to BibEntryWriterTest.java

CHANGELOG.md, src/main/java/org/jabref/gui/importer/ImportEntriesDialog.fxml, src/main/java/org/jabref/gui/importer/ImportEntriesDialog.java, src/main/resources/l10n/JabRef_en.properties
Fixes #7768
We implemented a select all button for the library import function that fixes issue #7786. 
Added a new function selectAllEntires() to ImportEntriesDialog and a button to ImportEntriesDialog.fxml.
New localization String "Select all entries" also added to JabRef_en.properties.
=> Implemented a select all button for the library import function (issue #7786)

src/test/java/org/jabref/logic/importer/fileformat/ACMPortalParserTest.java
`ACMPortalParserTest` was in the wrong package. Test connects to an external service, therefore annotated with FetcherTest
=> Fix annotation + package of ACMPortalParserTest

src/main/java/org/jabref/logic/journals/JournalAbbreviationLoader.java, src/main/java/org/jabref/logic/net/URLDownload.java
Problem
- The two changed locations create temporary files, but do not arrange to clean them up.
- The tests create sevaral copies of journalList.mv, tends to fill up /tmp 
Now:
- these files and directoriees are removed on normal exit
- they are prefixed with "jabref-" to
-  (1) let the user know who to complain
and which program should not run while removing 
- (2) make it easier to remove them after abnormal exit
NA
NA
- [X ] Manually tested changed features in running JabRef (always required)
-  also with gradlew test
NA
NA
=> cleanup temporary files, use prefix "jabref-"

build.gradle
Use the latest release (to enable stable builds) of citeproc-java.
See https://github.com/michel-kraemer/citeproc-java/issues/92#issuecomment-798419164 for details.
=> Pin version of citeproc-java

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/JournalEditorViewModel.java
We changed the abbreviation toggle (shown in the entry editor for the journal field) in JournalEditorViewModel to ignore curly braces when matching. 
The field text is stripped of any left or right curly braces before it is passed to isKnownName() and getNextAbbreviation().
Fixes  #7773.
=> Abbreviation toggle within the JournalEditorViewModel now ignores curly braces (issue #7773)

CHANGELOG.md, src/main/java/org/jabref/logic/msbib/MSBibConverter.java, src/main/java/org/jabref/model/openoffice/uno/UnoCrossRef.java, src/test/resources/org/jabref/logic/exporter/MsBibPatent.xml
=> Ms Office Export patent author as inventor

src/main/java/org/jabref/logic/importer/fetcher/TitleFetcher.java, src/test/java/org/jabref/logic/importer/fetcher/INSPIREFetcherTest.java
Fixed fetcher tests:
1. Inspire (Seems to return UTF-8 now: `Fréchet` instead of `Fr\\'echet`)
2. Title (Strange: crossref seems to return a list of some random bibentries when called with an empty search string)
=> Fix fetchers Title and Inspire

CHANGELOG.md, src/main/java/org/jabref/logic/layout/LayoutHelper.java, src/test/java/org/jabref/logic/layout/LayoutHelperTest.java
This fixes #7526 (besides https://github.com/JabRef/jabref/issues/7526#issuecomment-818895244). When entering a backslash, JabRef does not throw an exception any more.
I thought long about using Optionals for a good code quality (see https://github.com/JabRef/jabref/pull/7539/files#r611956179). After discussing with @calixtus, I think, this is still an exertional case and should be treated as such. I changed the implementation to return the declared exception only and added tests.
The exception is already properly handled in at `org.jabref.logic.layout.TextBasedPreviewLayout#setText`, thus I did not need to touch that code.
=> Fix for entering a backslash in the custom entry preview dialog

src/main/java/org/jabref/logic/importer/FulltextFetchers.java, src/test/java/org/jabref/logic/importer/FulltextFetchersTest.java
=> Fix test "higherTrustLevelWins()"

CHANGELOG.md, docs/advanced-reading/fetchers.md, src/main/java/org/jabref/logic/importer/fetcher/AstrophysicsDataSystem.java, src/test/java/org/jabref/logic/importer/fetcher/AstrophysicsDataSystemTest.java
=> Fix AstroPhysicsFetcher

.github/workflows/check-outdated-dependencies.yml, .github/workflows/tests-fetchers.yml, build.gradle, docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace.md
=> Update to Java 16 in build.gradle

CHANGELOG.md, src/main/java/org/jabref/logic/util/Version.java, src/test/java/org/jabref/logic/util/VersionTest.java
Fixes https://github.com/JabRef/jabref/issues/7884 by adding a workaround.
Added test won't work on the CI, because of GitHub's rate limit.
```
java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/JabRef/JabRef/releases
at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1932)
at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528)
at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
at org.jabref.logic.util.Version.getAllAvailableVersions(Version.java:99)
at org.jabref.logic.util.VersionTest.getAllAvailableVersionsReturnsSomething(VersionTest.java:303)
```
- [] Change in `CHANGELOG.md` described in …
=> Add corporate proxy workaround for Version.getAllAvailableVersions()

build.gradle, docs/getting-into-the-code/code-howtos.md, src/main/java/org/jabref/logic/formatter/bibtexfields/CleanupUrlFormatter.java
code-howtos and build.gradle still referenced apache commons, but slf4j
should be used instead.
CleanupUrlFormatter was the only class still using it, but never
actually used the logger, so it was removed.
=> Removed references to apache commons logging

build.gradle, external-libraries.md, src/main/java/org/jabref/logic/citationstyle/CSLAdapter.java
Upgrade citeproc-java from 3.0.0-alpha.1 to 3.0.0-alpha.2.
This fixes #7637 and provides further improvements.
=> Update citeproc-java to 3.0.0-alpha.2

CHANGELOG.md, buildres/windows/JabRefHost.ps1
This resolves an issue where the encoding somehow got lost when using
the Jabref Browser extension. It will now write a temporary file
with UTF-8 encoding rather than passing the bibtex on the commandline.
See https://github.com/JabRef/JabRef-Browser-Extension/issues/274
- [] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the …
=> Write temporary file on bib import in jabrefhost.ps1

src/main/java/org/jabref/model/database/BibDatabaseContext.java, src/test/java/org/jabref/model/database/BibDatabaseContextTest.java
Fixes #7933 
Hello folks! I discovered this project yesterday and I downloaded the repo and started to play around with UI when I found this unexpected behavior when trying to create a new library. After checking the stack trace, I found a log statement that tries to get a value from an `Optional` before checking if it is present. So, I change the position of the statement. Additionally, I refactored the path attribute, unwrapping it from the `Optional`. Ideally, the `Optional` should only be used as return type of methods, as advocated by [Brain Goetz](https://stackoverflow.com/questions/26327957/should-java-8-getters-return-optional-type/26328555#26328555) (Java Language Architect at Oracle).
=> Log message after checking if the optional contains a value

CHANGELOG.md, src/main/java/org/jabref/logic/importer/util/FileFieldParser.java, src/test/java/org/jabref/logic/importer/util/FileFieldParserTest.java
=> Fix file field parser not recognizing online urls

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java, src/test/java/org/jabref/gui/groups/GroupDialogViewModelTest.java
Follow-up PR from #7728  Closes #7728
Fixes  #7719
I just added a test
=> Follow up the "Aux file" on "Edit group" doesn't support relative sub-directories path

CHANGELOG.md, src/main/java/org/jabref/logic/formatter/Formatters.java, src/test/java/org/jabref/logic/citationkeypattern/BracketedPatternTest.java
The bracketed patterns for renaming files don't translate fields to Unicode, so if there are protected terms (`{In} {CDMA}`) the brackets will be translated to underscore, (`_In_ _CDMA_`) which cannot be removed by the regex modifier (which respects protected terms).
This PR adds the already existing `UnprotectTermsFormatter` to the list of available modifiers, which can be used through the key `unprotect_terms`.
The motivation for adding it is https://discourse.jabref.org/t/filename-format-pattern-novice-user/2872 .
=> Add `unprotect_terms` to the list of modifiers for bracketed patterns

src/main/java/org/jabref/logic/pdf/search/indexing/PdfIndexer.java, src/test/java/org/jabref/logic/pdf/search/indexing/PdfIndexerTest.java
Filter for locally-stored PDF files when adding to the fulltext search index.
First attempt at fixing #7942.
=> Fulltext Index: Only index local pdf files

src/main/java/org/jabref/logic/exporter/TemplateExporter.java, src/test/java/org/jabref/logic/exporter/YamlExporterTest.java
And fix issue where calling with Encoding would have no effect if the database was not UTF-8.
I stumbled upon while checking the [forum post](https://discourse.jabref.org/t/utf-8-encoding-in-rdf-file/2892/)
=> Fix possible NPE in exporter with empty charset

src/main/java/org/jabref/logic/importer/fileformat/PdfMergeMetadataImporter.java, src/test/java/org/jabref/logic/importer/fileformat/PdfMergeMetadataImporterTest.java
Changed the list, that implies priority, of PdfImporters in the PdfMergeMetadataImporter.
Fixes https://github.com/koppor/jabref/issues/169
=> Reordered Pdf-Importer priorities

src/main/java/org/jabref/gui/push/PushToEmacs.java, src/main/java/org/jabref/gui/push/PushToLyx.java, src/main/java/org/jabref/gui/push/PushToTeXstudio.java, src/main/java/org/jabref/gui/push/PushToVim.java, src/main/java/org/jabref/gui/push/PushToWinEdt.java, src/main/java/org/jabref/model/JabRefStringConstants.java, src/main/java/org/jabref/model/push/PushToApplicationConstants.java, src/main/java/org/jabref/preferences/JabRefPreferences.java
This PR serves as a step to remove the dependence of the preferences on gui components.
In this PR some string constants are extracted from the gui component to inverse the depencendence.
=> Extract PushTo names into model

CHANGELOG.md, src/main/java/org/jabref/gui/Base.css
Fixed search bar icons after change to ikonli were **in Linux** only drawn in one color, unselected as well as selected.
Fixes #8014
Before:
After:
=> Fix search bar icons in linux

src/test/java/org/jabref/logic/importer/fetcher/ACMPortalFetcherTest.java, src/test/java/org/jabref/logic/importer/fileformat/ACMPortalParserTest.java
It's only important that the first one is the one we want.
=> ACM-Fetchers: Allow the search to return multiple entries.

src/main/java/org/jabref/gui/Dark.css, src/main/java/org/jabref/gui/search/GlobalSearchBar.java
Fixes #8026 
Normal mode:
case-sensitive:
=> Fix Search dark mode theme

src/main/java/org/jabref/logic/pdf/search/indexing/IndexingTaskManager.java
When the user closes JabRef while indexing, a Dialog is shown asking whether to cancel the indexing. If the cancel is approved by the user, the indexing continued anyways. This is fixed with this PR.
Fixes koppor/jabref#516
=> Stop fulltext-indexing on cancel

src/main/java/org/jabref/gui/externalfiles/ImportHandler.java, src/main/java/org/jabref/logic/externalfiles/ExternalFilesContentImporter.java, src/main/resources/l10n/JabRef_en.properties
Since XMP is imported by the MergeMetadataImporter anyways, there is no need to do it explicitly. This also respects the same prioritization that is used when importing PDFs.
=> Remove explicit XMP import for PDFs

src/main/java/org/jabref/model/entry/LinkedFile.java, src/test/java/org/jabref/logic/importer/fileformat/PdfMergeMetadataImporterTest.java
On Windows, the filename was not correctly written in the expected case. I fixed it by using the "standard" procedure to get file links
Now, it works "on my machine".
The CI (on another branch at https://github.com/JabRef/jabref/runs/3513022608?check_suite_focus=true) output following. Here, the `month` field was not included. Could not reproduce. Here for historical reasons (maybe I need to reference it)
```
org.jabref.logic.importer.fileformat.PdfMergeMetadataImporterTest
Test importWorksAsExpected() FAILED (17.9s)
org.opentest4j.AssertionFailedError: expected: <[
```
```bibtex
@book{9780134685991,
author = {Bloch, Joshua},
comment = {From embedded bib},
date = {2018-01-01},
doi = {10.1002/9781118257517},
ean = {9780134685991},
file = …
```
=> Fix PdfMergeMetaImporterTest on Windows

src/test/java/org/jabref/logic/importer/fetcher/IsbnViaOttoBibFetcherTest.java
The ISBN fetcher has a test for ISBN returning **no** data. However, there came back results since two years. Now, there is no result any more.
I updated the test:
- Change name and JavaDoc to really indicate we do not want any results
- Changed the ISBN number to an artificially one to ensure no results are returned.
---
=> Fixes the ISBN test

.github/workflows/check-outdated-dependencies.yml, .github/workflows/deployment.yml, .github/workflows/refresh-journal-lists.yml, .github/workflows/tests-fetchers.yml, .github/workflows/tests.yml
Since 5 days, `setup-java` supports caching by itself. See https://github.blog/changelog/2021-08-30-github-actions-setup-java-now-supports-dependency-caching/ for details.
I think, GitHub knows better than us how to correctly cache. Thus, I removed custom calls to the cache action and used the new cache property.
=> Use new "cache" property of setup-java

src/main/java/org/jabref/logic/importer/util/GrobidService.java, src/test/java/org/jabref/logic/importer/util/GrobidServiceTest.java
There was a `true`/`false` mixup at the `ImporterPreferences`. This PR fixes it.
It also fixes some typos.
I know that we discussed the usage of [EnumSet](https://docs.oracle.com/javase/7/docs/api/java/util/EnumSet.html)s to avoid Booleans. Too much effort for me to implement it here 😇
=> Fix grobid test

src/main/java/org/jabref/gui/StateManager.java, src/main/java/org/jabref/gui/maintable/BibEntryTableViewModel.java, src/main/java/org/jabref/gui/maintable/MainTableFieldValueFormatter.java, src/main/java/org/jabref/gui/search/GlobalSearchBar.java, src/main/java/org/jabref/gui/search/GlobalSearchResultDialog.java, src/main/java/org/jabref/gui/search/GlobalSearchResultDialogViewModel.java, src/main/java/org/jabref/gui/search/SearchResultsTable.java, src/main/java/org/jabref/gui/search/SearchResultsTableDataModel.java
Fixes parts of #8054 
Rely on Observable Magic and collect entries for each db context
=> Simplify global search and library name

snap/snapcraft.yaml
This adds a layer exposing the amd gpu libs to the snap (needed for the opengl plug)
This should fix #7969
=> snap amd fix

src/main/java/org/jabref/cli/JabRefCLI.java, src/main/java/org/jabref/logic/exporter/EmbeddedBibFilePdfExporter.java, src/main/resources/l10n/JabRef_en.properties, src/test/java/org/jabref/gui/fieldeditors/LinkedFileViewModelTest.java
Spotted by @hakova  on Crowdin
=> Fix l10n and fix some missing type args

CHANGELOG.md, snap/snapcraft.yaml
LZO compression speeds up cold starts tremendously while
increasing the download size a moderate amount.
Also switch to core20 and its more recent gnome extension.
=> snap: Use lzo compression & switch to core20 base

CHANGELOG.md, src/main/java/org/jabref/gui/preferences/linkedfiles/LinkedFilesTabViewModel.java
Fixes #8107
While usually I don't advocate silently catching exceptions, in this case I think it's the right thing to do as we just want a true / false value as to whether the path is valid or not. If we catch an `InvalidPathException` then we *always* know that the path is invalid - so this fixes the attached issue with UNC paths, as well as any other theoretical invalid path that might throw this exception.
=> Don't throw exception when validating invalid paths

CHANGELOG.md, src/main/java/org/jabref/gui/Base.css, src/main/java/org/jabref/gui/customentrytypes/CustomizeEntryTypeDialogView.java
=> Improve Drag and Drop in Custom Entry types dialog

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/LatexCitationsTabViewModel.java, src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java, src/main/java/org/jabref/gui/slr/ExistingStudySearchAction.java, src/main/java/org/jabref/gui/texparser/ParseLatexDialogViewModel.java, src/main/java/org/jabref/logic/importer/util/GroupsParser.java, src/main/java/org/jabref/logic/util/io/FileUtil.java, src/main/java/org/jabref/preferences/PreferencesService.java
Fixes https://github.com/koppor/jabref/issues/538
The directory of the currently opened database is now used as default directory for the LaTeX Ciations Tab
---
I did not dare to touch the logic of saving the "LatexFileDirectories". IMHO, they should be relative to the `.bib` file. This will be a longer discussion for a follow-up PR.
=> Fix default directory of the "LaTeX Citations" tab

CHANGELOG.md, build.gradle
Fixes #7860
Updating richtextfx 
Refs https://github.com/FXMisc/RichTextFX/issues/1021
=> Fix Exception on citation style selection

CHANGELOG.md, src/main/java/org/jabref/gui/EntryTypeViewModel.java, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/gui/importer/GenerateEntryFromIdAction.java, src/main/java/org/jabref/gui/importer/GenerateEntryFromIdDialog.java, src/main/resources/l10n/JabRef_en.properties
Fixes stuck-in-library issue when the fetcher DOI failed to find an entry for an ID [#7870](https://github.com/JabRef/jabref/issues/7870). User can now choose to add entry manually instead of returning to the new entry dialog box
=> Present options to create an article for manual entry or return to the new entry dialog box when failed to find DOI ID ... #7870

.github/ISSUE_TEMPLATE/bug_report.yml, buildres/mac/README.md, config/README.md, docs/advanced-reading/jpackage.md, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/main/resources/resource/layout/endnote/Readme.txt
The name of this operating system is `macOS` since 2016, so I though it would be a good idea to name it consistently.
=> Rename occurrences of OS X to macOS

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fetcher/DoiFetcher.java, src/main/java/org/jabref/model/entry/identifier/DOI.java, src/main/resources/l10n/JabRef_en.properties, src/test/java/org/jabref/model/entry/identifier/DOITest.java
Use single regexp to remove white-space and non-ASCII characters in DOI to fixes #8127. Further inform the user that "No DOI data exists" if DOI is valid and unable to find the article. Works for cases where DOI.findInText does not #8227. For example, the DOI "https : / / doi.org / 10 / gf4gqc" with the quote removed will result in an error not capture by Jabref itself. The reason is that the pattern used by DOI.findInText to extract DOI is not comprehensive. DOI.findInText is only tested in DOITest but not used elsewhere in the source code. However, DOI.parse is used in both DoiFetcher and CompositeIdFetcher, so it is probably better to improve DOI.parse.   
With DOI.findInText:
With this PR:
With this PR, user is informed that no data exists if the DOI is valid but no data is found …
=> Use regexp to remove non-ASCII characters from DOI and inform user when data for valid DOI does not exist #8127

src/main/java/org/jabref/gui/entryeditor/FieldsEditorTab.java, src/main/java/org/jabref/gui/entryeditor/OptionalFields2Tab.java, src/main/java/org/jabref/gui/entryeditor/OptionalFieldsTab.java, src/main/java/org/jabref/gui/entryeditor/OptionalFieldsTabBase.java
Fixes #7986 
Description:
This PR is to fix the entry editor -> Optional Fields tab first column fields invisibility issue when the width is too small. 
Solution:
As "Optional Fields tab" is a compressed double columns layout, I'd like to make two columns grow/shrink equally. As such, the first column won't be invisible anymore while the second column is shown.
=> Fix entry editor column visibility

src/test/java/org/jabref/model/entry/AuthorTest.java
This adds more unit tests to the AuthorTest.java file in by applying knowledge acquired through the Software Testing discipline of the University of Brasília
- [x ] Tests created for changes (if applicable)
- [x ] Manually tested changed features in running JabRef (always required)
=> Added more unit tests in AuthorTest

src/main/java/org/jabref/gui/libraryproperties/LibraryPropertiesDialogViewModel.java, src/main/java/org/jabref/model/metadata/SaveOrderConfig.java, src/main/java/org/jabref/preferences/JabRefPreferences.java
I saw the [frombooleans](https://github.com/JabRef/jabref/blob/3a44c6957f6c66427645c7891dee6be92067cdb9/src/main/java/org/jabref/model/metadata/SaveOrderConfig.java) method.
'frombooleans' method has 2 parameters.
First parameter needs to be given 'boolean SpecifiedOrder'.
Second parameter needs to be given 'boolean TableOrder'.
Second parameter of previous code was given 'boolean OrigianlOrder'.
So I changed that part.
Fixes [#8198](https://github.com/JabRef/jabref/issues/8198#issue-1038849241)
About "JabRefPreferences.java", there is no variable about 'TABLE OrderType'.
So I make it.
Update SaveOrderConfig.java to fix #8133
=> Fix for issue 8198, 8133

CHANGELOG.md, src/main/java/org/jabref/logic/bibtex/comparator/EntryComparator.java, src/main/java/org/jabref/logic/database/DuplicateCheck.java, src/main/java/org/jabref/logic/importer/Importer.java, src/main/java/org/jabref/model/entry/BibEntry.java, src/main/java/org/jabref/model/strings/StringUtil.java, src/test/java/org/jabref/logic/bibtex/comparator/BibDatabaseDiffTest.java, src/test/java/org/jabref/logic/bibtex/comparator/EntryComparatorTest.java, src/test/java/org/jabref/logic/database/DuplicateCheckTest.java
Fixes https://github.com/JabRef/jabref/issues/4877
When a user had `CRLF` configured as line ending and stored a multiline field (such as comment), JabRef always complained with "the library has been modified externally". See https://github.com/JabRef/jabref/issues/4877#issuecomment-967715080 for an MWE.
This PR fixes it and also refines the duplicate checker itself.
=> Fix "Library has changed externally" with CRLF markers

src/main/antlr4/org/jabref/search/Search.g4, src/test/java/org/jabref/model/groups/SearchGroupTest.java
I had issues with a search like `NOT(groups=alpha) AND NOT(groups=beta)`. It did not work, in case `beta` was the hit group. Therefore, I created https://github.com/JabRef/jabref/pull/8206.
After thinking more, the solution was that the search grammar was wrong: NOT was too low in the ordering (hint via https://stackoverflow.com/a/30987142/873282).
This PR fixes NOT and AND to be defined as in Boolean algebra. Before, NOT bound wrong and AND and OR were treated equally.
=> Fix search: NOT binds more than AND

.github/workflows/check-links.yaml, .github/workflows/deployment.yml, .github/workflows/gource.yml, .github/workflows/snap.yml, .github/workflows/tests-fetchers.yml, .github/workflows/tests.yml
Switch from <https://github.com/styfle/cancel-workflow-action> to GitHub's internal concurrency feature.
See https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/
=> Switch to GitHub's concurrency feature

docs/adr.md
ADRs 22 and 23 where not in the list. Adding them.
=> Add of ADRs 22 and 23

CHANGELOG.md, src/main/java/org/jabref/gui/preview/PreviewViewer.java
Fixes #7706 
DOI links in the preview pane no longer open in the WebView and no longer cause uncaught exceptions as a consequence. Unfortunately wasn't able to find a clean solution to opening a browser window on all OS's without using java.awt
=> Clicking a DOI link in the preview pane no longer crashes

build.gradle, gradle/wrapper/gradle-wrapper.properties, gradlew
Update Gradle Wrapper from 7.2 to 7.3.
Read the release notes: https://docs.gradle.org/7.3/release-notes.html
---
- Gradle release: `7.3`
- Distribution (-bin) zip checksum: `de8f52ad49bdc759164f72439a3bf56ddb1589c4cde802d3cec7d6ad0e0ee410`
- Wrapper JAR Checksum: `33ad4583fd7ee156f533778736fa1b4940bd83b433934d1cc4e9f608e99a6a89`
---
<details>
<br /> …
=> Update Gradle Wrapper from 7.2 to 7.3

src/test/java/org/jabref/logic/importer/fetcher/RfcFetcherTest.java
Fixes https://github.com/JabRef/jabref/issues/8263
The underlying discussion is whether the Java-programmer facing interface should be strict or relaxed.
@calixtus and me currently think that the newline character has to be provided.
=> Fixes RFC fetcher test case

src/main/java/org/jabref/gui/groups/GroupDialogView.java
Fixes #8094
Bug in controlsfx somehow https://github.com/controlsfx/controlsfx/issues/1400
=> Fix icon picker excpetion in groups dialog

src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/search/GlobalSearchResultDialog.java, src/main/resources/l10n/JabRef_en.properties
Add title to window
Fixes part of #8054
=> Apply search string on opening library when keep search string is selected

gradle/wrapper/gradle-wrapper.properties, gradlew
Update Gradle Wrapper from 7.3 to 7.3.1.
Read the release notes: https://docs.gradle.org/7.3.1/release-notes.html
---
- Gradle release: `7.3.1`
- Distribution (-bin) zip checksum: `9afb3ca688fc12c761a0e9e4321e4d24e977a4a8916c8a768b1fe05ddb4d6b66`
- Wrapper JAR Checksum: `33ad4583fd7ee156f533778736fa1b4940bd83b433934d1cc4e9f608e99a6a89`
---
<details>
<br /> …
=> Update Gradle Wrapper from 7.3 to 7.3.1

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fileformat/PdfEmbeddedBibFileImporter.java, src/main/java/org/jabref/logic/xmp/XmpUtilReader.java
=> Fix xmp import

src/main/java/org/jabref/gui/collab/StringRemoveChangeViewModel.java
=> Fixed exception handling

src/main/java/org/jabref/logic/net/URLDownload.java, src/test/java/org/jabref/logic/importer/fetcher/CompositeIdFetcherTest.java
Bypass SSL Verification in URLDownload
It was only set when JabRef was started normally
Fixes #8305
=> Fix IEEE test

snap/snapcraft.yaml
The cleanup part will remove any files that have been
included in the snap during build that also exist in the
content snap.
This reduces the size from 230 MB to 178 MB (~23%),
which improves startup & download speed.
=> snap: Remove superfluous files post build

src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java, src/test/java/org/jabref/logic/importer/fetcher/ACMPortalFetcherTest.java
=> Fix ACM fetcher

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/DeprecatedFieldsTab.java, src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/entryeditor/FieldsEditorTab.java, src/main/java/org/jabref/gui/entryeditor/OptionalFields2Tab.java, src/main/java/org/jabref/gui/entryeditor/OptionalFieldsTab.java, src/main/java/org/jabref/gui/entryeditor/OptionalFieldsTabBase.java, src/main/java/org/jabref/gui/entryeditor/OtherFieldsTab.java, src/main/java/org/jabref/gui/entryeditor/PreviewTab.java, src/main/java/org/jabref/gui/entryeditor/RequiredFieldsTab.java, src/main/java/org/jabref/gui/entryeditor/UserDefinedFieldsTab.java, src/main/java/org/jabref/gui/externalfiles/ExternalFilesEntryLinker.java, src/main/java/org/jabref/gui/maintable/MainTable.java, src/main/java/org/jabref/gui/preview/PreviewPanel.java, src/main/java/org/jabref/logic/pdf/search/indexing/IndexingTaskManager.java
There was a problem that involved the Indexer and Drag&Drop operations while having auto-file-move/rename enabled.
When dropping a File onto an entry, JabRef links that file to the entry and moves and renames the files according to the set preferences. It was possible for this to happen while the PDFIndexer was running. This could lead to:
- The pdf indexer not finding the file because it was invoked before the path changed
- The move/rename operation to fail because the indexer blocked the PDF
This was solved by not allowing for any files to be added to the indexer during drag&drop operations.
Fixes #8182.
=> Don't register any database changes to the indexer while dropping a file

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/exporter/ExportCommand.java, src/main/java/org/jabref/gui/exporter/ExportToClipboardAction.java, src/main/java/org/jabref/gui/maintable/RightClickMenu.java, src/test/java/org/jabref/gui/exporter/ExportToClipboardActionTest.java
=> Added missing executable bindings to various commands

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/OpenConsoleAction.java, src/main/java/org/jabref/gui/libraryproperties/LibraryPropertiesAction.java, src/main/java/org/jabref/gui/libraryproperties/LibraryPropertiesView.java, src/main/java/org/jabref/gui/libraryproperties/general/GeneralPropertiesViewModel.java
=> Fixes empty metadata in library properties called from right click menu

CHANGELOG.md, src/main/java/org/jabref/gui/integrity/IntegrityCheckAction.java, src/main/java/org/jabref/logic/integrity/IntegrityCheck.java, src/main/java/org/jabref/logic/integrity/UTF8Checker.java, src/test/java/org/jabref/logic/integrity/IntegrityCheckTest.java, src/test/java/org/jabref/logic/integrity/UTF8CheckerTest.java
Fixes #8022.
Previous method used `System.getProperty("file.encoding")` to get the current character encoding).
Changed to use,
1. `bibDatabaseContext.getMetaData().getEncoding()`
2. `preferencesService.getGeneralPreferences().getDefaultEncoding()`
**Todo**:
1. ~I don't think it can distinguish GBK from UTF-8~
Refs issue https://github.com/JabRef/jabref/issues/5850 and PR https://github.com/JabRef/jabref/pull/7639
=> Changed encoding used by IntegrityCheck

CHANGELOG.md, src/main/java/org/jabref/logic/pdf/search/indexing/PdfIndexer.java, src/main/java/org/jabref/logic/pdf/search/retrieval/PdfSearcher.java
fix some potential resource leaks
Fixes https://github.com/koppor/jabref/issues/522
I also tested the jpackage binaries
=> Fix lucence segment error by checking for existing index

CHANGELOG.md, src/main/java/org/jabref/gui/libraryproperties/constants/ConstantsPropertiesView.java, src/main/resources/l10n/JabRef_en.properties
=> Fix plural s in library properties tab

CHANGELOG.md, src/main/java/org/jabref/logic/exporter/BibDatabaseWriter.java, src/test/java/org/jabref/logic/exporter/BibtexDatabaseWriterTest.java, src/test/java/org/jabref/logic/importer/fileformat/BibtexImporterTest.java, src/test/resources/org/jabref/logic/importer/fileformat/encoding-windows-1252-with-header.bib
=> "% Encoding" is written again in the case of non-UTF-8

CHANGELOG.md, src/main/java/org/jabref/model/database/BibDatabaseContext.java, src/main/java/org/jabref/preferences/FilePreferences.java, src/main/java/org/jabref/preferences/JabRefPreferences.java
=> Fix file directory preferences not respected

src/main/java/org/jabref/gui/actions/StandardActions.java, src/main/resources/l10n/JabRef_en.properties
=> Rename Groups interface into Groups

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefFrame.java
Fixes #7614
Could not test it but I think the underlying issue is the same as described  in #7470
>When loading/opening a bib file a new "normal" Tab is inserted to indicate loading. That is later removed again and it's not an instanceof our LibraryTab
=> Fix library tab exception when saving prefs

buildres/linux/jabrefHost.py, buildres/mac/jabrefHost.py, buildres/windows/JabRefHost.bat, buildres/windows/JabRefHost.ps1
Still needs similar changes for the other problems and then some changes to the browser extension to actually show the error.
=> Improve error handling for browser extension

CHANGELOG.md, src/main/java/org/jabref/gui/importer/fetcher/WebSearchPaneView.java, src/main/java/org/jabref/gui/sidepane/SidePaneComponent.java
Made search button in Web search wider. Also skewed side panel titles to the left
Before:
After:
Fixes #8397
=> Made search button in Web search wider. Also skewed side panel titles to the left

src/main/java/org/jabref/gui/EntryTypeViewModel.java, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/JabRefGUI.java, src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/gui/exporter/SaveDatabaseAction.java, src/main/java/org/jabref/gui/importer/ImportEntriesViewModel.java, src/main/java/org/jabref/gui/menus/FileHistoryMenu.java, src/main/java/org/jabref/gui/mergeentries/DiffHighlightingEllipsingTextFlow.java, src/main/java/org/jabref/gui/mergeentries/DiffMode.java, src/main/java/org/jabref/gui/mergeentries/MergeEntries.java, src/main/java/org/jabref/gui/mergeentries/MultiMergeEntriesView.java, src/main/java/org/jabref/gui/preferences/file/FileTab.fxml, src/main/java/org/jabref/gui/preferences/file/FileTab.java, src/main/java/org/jabref/gui/preferences/file/FileTabViewModel.java, src/main/java/org/jabref/logic/util/io/FileHistory.java, src/main/java/org/jabref/preferences/GuiPreferences.java, src/main/java/org/jabref/preferences/ImportExportPreferences.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/main/java/org/jabref/preferences/PreferencesService.java, src/main/resources/l10n/JabRef_en.properties
Follow up to #8370 
- Integrated some loose preferences:
- openLastEdited
- autoSave
- FileHistory ~(still a bug)~
- mergeDiffMode
- lastSelectedIdBasedFetcher
- warnAboutDuplicatesForImport
- Extracted DiffMode to a separate class
.
=> Observable Preferences K (Integration of wild preferences)

src/main/java/org/jabref/gui/Globals.java
Quick fix fixes #8525 
Tobi will hate me, but we really need to either get rid of it completely or move to version 3.x which comes as an agent.
2.6.x is not working with jpms.
I had to disable it due to  #8525  which fails due to Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
=> Disable telemetry client due to incompatibilites with jakarta

docs/SUMMARY.md, docs/advanced-reading/telemetry.md
We have discussions on telemetry these days. I would like to collect the thoughts and result of discussions.
This PR adds the hint of https://github.com/JabRef/jabref/pull/5150#discussion_r307860859.
Initial telemetry PR was https://github.com/JabRef/jabref/pull/2283
=> Add initial telemetry development documentation

CHANGELOG.md, src/main/java/org/jabref/logic/formatter/bibtexfields/CleanupUrlFormatter.java, src/test/java/org/jabref/logic/formatter/bibtexfields/CleanupUrlFormatterTest.java
Fixes  #8448 
* What: Allow the URL fields to accept URL containing + sign.
* Why: Some URLs are changed by JabRef when copy/paste from a navigation bar, making a bib pointing to an false URL.
* How: this is done by replacing all the + sign UTF-8 code by it's escape sequence code %2b. The code is placed in the `CleanupUrlFormatter` in the `org.jabref.logic.formatter.bibtexfields` package. A test with the given case is provided also.
**Note**: please let me know in the PR comments what type of comment you want in `CHANGELOG.md` and if you need a screenshot.
=> issue(8448): allow URL with + sign in entry tabs

CHANGELOG.md, src/main/java/org/jabref/logic/auxparser/DefaultAuxParser.java, src/test/java/org/jabref/logic/auxparser/AuxParserTest.java, src/test/resources/org/jabref/logic/auxparser/papertwoargmacro.aux
Fixes #8513. I changed the regex as outlined in my [comment](https://github.com/JabRef/jabref/issues/8513#issuecomment-1060743243) on the issue, with the exception that I decided to go with a named group for the citation key rather than just incrementing the index.
I also added a test case for the `DefaultAuxParser` that ought to behave the exact same way that the normal case should, despite encountering the two argument variant of the cite macro.
=> Support two argument form of \abx@aux@cite macro in DefaultAuxParser

src/main/java/org/jabref/logic/importer/fileformat/BibtexImporter.java
Fixes #8555 temporarily. Further investigation is needed
It inlines https://github.com/JabRef/jabref/blob/75df9a3e3dacde8c986a44777a75596c0f9e84da/src/main/java/org/jabref/logic/importer/Importer.java#L103-L108 which were used previously.
=> Fix missing metadata in BibDatabaseContext

src/main/java/org/jabref/logic/importer/SearchBasedParserFetcher.java
Some more documentation refinements.
Follow-up to https://github.com/JabRef/jabref/commit/3c247ff55708970d857dda8ac5e0472265466435
=> Refine documentation

src/main/java/org/jabref/logic/importer/SearchBasedParserFetcher.java
=> Revert "Refine documentation"

docs/getting-into-the-code/code-howtos.md, src/main/java/org/jabref/model/entry/BibEntry.java, src/test/resources/tinylog-test.properties
We switched to tinylog. This PR fixes the documentation.
=> Refine documentation on logging

src/test/java/org/jabref/logic/remote/RemoteSetupTest.java
=> Update RemoteSetupTest.java, adding eq() function from mockito

CHANGELOG.md, src/main/java/org/jabref/logic/crawler/StudyRepository.java, src/test/java/org/jabref/logic/crawler/CrawlerTest.java, src/test/java/org/jabref/logic/crawler/StudyDatabaseToFetcherConverterTest.java, src/test/java/org/jabref/logic/crawler/StudyYamlParserTest.java, src/test/resources/org/jabref/logic/crawler/study.yml
Issue : Due to the Fetcher Name being "Medline/PubMed", File creation fails as Medline is treated as a Directory and since It isn't created, the issue is observable.
Fixes #8455
=> Resolve File Creation Issue With Medline/PubMed

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefMain.java
=> Fix missing search index dir

CHANGELOG.md, src/main/java/org/jabref/gui/externalfiles/ImportHandler.java
Fixes #8444 
Not all unlinked local files that are found in a directory were imported correctly due to some race condition. 
The import takes place in a UI background thread and the passed closure referenced a list of entries to add. This list was an instance field of another class and not final. In some cases this list was changed/reassigned before the UI thread ran the closure and accessed the list. Therefor some entries were missing after the import.
Manually tested with 256 files.
=> Fix for unlinked file importer that did not import all importable files (#8444)

src/test/java/org/jabref/model/strings/StringUtilTest.java
Add new test for method get part in StringUtil class. 
The test was planned using multiple conditions method and all the cases were successfull.
=> StringUtilTest new test for method GetPart

src/test/java/org/jabref/gui/util/comparator/NumericFieldComparatorTest.java
Just inserted two more test cases for NumericFieldComparatorTest file.
=> Creating more unit tests for NumericFieldComparatorTest

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/logic/util/Version.java, src/test/java/org/jabref/logic/util/VersionTest.java
=> Fix changelog and version parsing

CHANGELOG.md, src/main/java/org/jabref/logic/protectedterms/ProtectedTermsPreferences.java
Fixes #8608
See: https://stackoverflow.com/a/44343014
=> Fix protectedTerms not stored due to weaklistener

src/test/java/org/jabref/gui/util/ControlHelperTest.java
Adding units test to truncateString method
=> Creating units tests for ControlHelper truncateString

src/test/java/org/jabref/model/strings/StringUtilTest.java
To maintain the standard of the project, the test sentences have been translated
=> Update teste getPart

src/main/java/org/jabref/model/entry/field/StandardField.java, src/test/java/org/jabref/logic/importer/fetcher/ResearchGateTest.java, src/test/java/org/jabref/logic/importer/fetcher/ZbMATHTest.java
=> Fix zbMath fetcher

CHANGELOG.md, src/main/java/org/jabref/logic/citationkeypattern/BracketedPattern.java, src/test/java/org/jabref/logic/citationkeypattern/CitationKeyGeneratorTest.java
=> Citation keygen: Return vonPart if lastName is empty

src/main/java/org/jabref/gui/search/rules/describer/SearchDescribers.java, src/main/java/org/jabref/logic/search/SearchQuery.java, src/main/java/org/jabref/model/search/rules/ContainBasedSearchRule.java, src/main/java/org/jabref/model/search/rules/ContainsBasedSearchRule.java, src/main/java/org/jabref/model/search/rules/FullTextSearchRule.java, src/main/java/org/jabref/model/search/rules/RegexBasedSearchRule.java, src/main/java/org/jabref/model/search/rules/SearchRules.java, src/test/java/org/jabref/model/search/rules/ContainBasedSearchRuleTest.java, src/test/java/org/jabref/model/search/rules/ContainsBasedSearchRuleTest.java
This PR ports refactoring commits of https://github.com/JabRef/jabref/pull/8206 to here. These are the commits before I began to add support for Lucene.
=> Refine search code

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefDialogService.java, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/StateManager.java, src/main/java/org/jabref/gui/util/BackgroundTask.java, src/main/java/org/jabref/gui/util/DefaultTaskExecutor.java, src/main/java/org/jabref/logic/pdf/search/indexing/IndexingTaskManager.java
BackgroundTasks have a new flag that indicates whether JabRef will automatically resume/recover this task when relaunched. Such tasks should not interrupt a user shut-down.
I.e. indexing tasks, that will be continued when launching JabRef again.
Fixes #8468
=> Only show exit warning if running tasks will not be recovered

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java, src/main/resources/l10n/JabRef_en.properties
Adding notifications when writing metadata to pdfs
Fixes #8276
Simple notifications added when clicking in this button specifically, as mentioned in issue #8276
Screenshot with success:
Screenshot when writting in a deleted file:
Screenshot when writting in a corrupted file:
Error log when writting in a corrupted file:
=> Adding notifications when writing metadata to pdfs

src/main/java/org/jabref/logic/exporter/EmbeddedBibFilePdfExporter.java, src/main/java/org/jabref/logic/xmp/XmpUtilReader.java, src/main/java/org/jabref/logic/xmp/XmpUtilWriter.java
Fixes #8655
No changelog necessary as this was most likely introduced in https://github.com/JabRef/jabref/commit/d98a603d47835b6564f03fa550d5a84d7c2c6f3e
=> Save xmp data to new file and then copy it back

build.gradle, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/exporter/WriteMetadataToPdfAction.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java, src/main/java/org/jabref/gui/util/DefaultFileUpdateMonitor.java, src/main/java/org/jabref/logic/exporter/EmbeddedBibFilePdfExporter.java, src/main/java/org/jabref/logic/xmp/DublinCoreExtractor.java, src/main/java/org/jabref/logic/xmp/XmpUtilWriter.java, src/main/java/org/jabref/model/util/FileUpdateMonitor.java
Follow-up to https://github.com/JabRef/jabref/pull/8656 after feedback.
=> Fix XMP write

build.gradle, src/main/java/module-info.java
Somehow I got this error today that I am maybe missing some codecs
>java.lang.IllegalArgumentException: Could not load codec 'Lucene87'. Did you forget to add lucene-backward-codecs.jar?
=> Add lucence backwards codec

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/maintable/RightClickMenu.java, src/main/java/org/jabref/gui/menus/ChangeEntryTypeMenu.java
Fixes #8654
This allows for the right click option "Change entry type" to change the entry types of multiple entries at once.
Trying to change the entry type by first double clicking on the entry still behaves normally.
=> Allowing changing entry types of multiple entries

.editorconfig, .gitattributes
With IntelliJ 2022, I have issues with CRLF (IntelliJ) and LF (git config) line endings. With this PR, I kind of follow the recommendation from https://stackoverflow.com/a/42135910/873282 to have all source code files having the same line endings.
=> Fight EOL issues by pinning LF for *.java, *.fxml, and *.properties

build.gradle, src/main/java/module-info.java
Needed to add two require statements to our `module-info.java` to get JabRef compiling again.
<s>Quick fix, thus, I merge instantly. </s>
=> Add required modules to module-info.java

CHANGELOG.md, src/main/java/org/jabref/gui/maintable/MainTable.java
This fix always deselects the current entry when "New Article" is pressed, allowing for the correct entry to be selected, even if it is hidden by search filters.
Fixes #8674.
Note: This changes the method ```clearAndSelect()``` in MainTable to always deselect even when the entry isn't found. This method is used elsewhere, but I haven't seen any side effects from making this change (e.g. pressing the up arrow key doesn't make the selected entry go out of bounds).
=> Select correct entry in search using "New Article"

README.md
The link to the maintainer's page was not up-to-date and led to nowhere.
=> Fix link to maintainers

.github/workflows/refresh-csl-subtrees.yml, .github/workflows/refresh-journal-lists.yml, .github/workflows/tests-fetchers.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/DeprecatedFieldsTab.java
>  Only show deprecated fields tab if they contain values
Fixes #8396 by filtering out the empty deprecated fields.
The issue was caused because it always returns a valid deprecated field set but didn't check whether is empty or not.
5.4 (latest release)
Mac OS
Monterey 12.2.1
Before
After
=> Fix for issue 8396: filter out the empty field

CHANGELOG.md, src/main/java/org/jabref/gui/exporter/WriteMetadataToPdfAction.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java, src/main/java/org/jabref/logic/bibtex/comparator/EntryComparator.java, src/main/java/org/jabref/logic/exporter/XmpExporter.java, src/main/java/org/jabref/logic/exporter/XmpPdfExporter.java, src/main/java/org/jabref/logic/importer/fileformat/PdfContentImporter.java, src/main/java/org/jabref/logic/importer/fileformat/PdfEmbeddedBibFileImporter.java, src/main/java/org/jabref/logic/importer/fileformat/PdfVerbatimBibTextImporter.java, src/main/java/org/jabref/logic/importer/fileformat/PdfXmpImporter.java, src/main/java/org/jabref/logic/xmp/DublinCoreExtractor.java, src/main/java/org/jabref/logic/xmp/XmpUtilReader.java, src/main/java/org/jabref/logic/xmp/XmpUtilShared.java, src/main/java/org/jabref/logic/xmp/XmpUtilWriter.java, src/main/java/org/jabref/model/entry/BibEntry.java, src/test/java/org/jabref/logic/bibtex/comparator/EntryComparatorTest.java, src/test/java/org/jabref/logic/exporter/XmpExporterTest.java, src/test/java/org/jabref/logic/xmp/XmpUtilReaderTest.java, src/test/java/org/jabref/logic/xmp/XmpUtilWriterTest.java
Triggered by https://twitter.com/DrHagva/status/1524096667670171650, I went into the XMP code and tried to understand it. Thereby, I refactored the code to be more modern.
- I also made the XMP test to check for **content** instead of just the amount of entries.
- Removed two obsolete methods (filenames as string instead of Path)
This also fixes https://github.com/JabRef/jabref/issues/8452.
Note that I used the `UnprotectTermsFormatter` instead of `getLatexFreeField`, because with the latter, I get `Ungültiges Byte 3 von 3-Byte-UTF-8-Sequenz.`
The test case is org.jabref.logic.xmp.XmpUtilWriterTest#doubleDashAtPageNumberIsKept.
<details>
WARN: Problem parsing XMP schema. Continuing with other schemas.: java.io.IOException: org.apache.xmpbox.xml.XmpParsingException: Failed to parse
at …
=> Improve XMP handling - latex free field, remove file field

buildSrc/build.gradle, docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace.md
At https://github.com/gradle/gradle/issues/17236#issuecomment-923074298 I finally found a workaround for followwing gradle issue:
```
Execution failed for task ':buildSrc:jar'.
> Entry org/jabref/build/JournalAbbreviationConverter$_convert_closure1$_closure2.class is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.4.2/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```
=> Workaround for buildSrc:jar issue

src/main/java/org/jabref/preferences/JabRefPreferences.java
While discussing https://github.com/JabRef/jabref/pull/8791, it was sawn, that there is a two-level nesting of application data:
Selected examples:
Full path
C:\Users\koppor\AppData\Local\Mozilla\Firefox
For JabRef, it currently looks as follows:
Interpretation: The ssl trust store is stored one level too high. This PR fixes i. This PR is a follow-up to #8583.
Result:
---
=> Default path for ssl key store is nested inside "JabRef" directory

src/main/java/org/jabref/gui/JabRefDialogService.java, src/main/resources/l10n/JabRef_en.properties
> The new notification system works fine, but I am having the issue that the notifications overlap the task bar on Windows.
Fixes: #8769 
```
.owner(JabRefGUI.getMainFrame().getScene().getWindow())
```
=> Fix notifications that overlap task bar

CHANGELOG.md, src/main/java/org/jabref/gui/maintable/columns/LinkedIdentifierColumn.java
fixes #8758
fixes #8802 
ref #8813
=> Fixes for issues #8758 #8802

src/main/java/org/jabref/architecture/AllowedToUseStandardStreams.java, src/main/java/org/jabref/gui/desktop/os/Linux.java, src/main/java/org/jabref/logic/util/io/XMLUtil.java, src/test/java/org/jabref/architecture/MainArchitectureTests.java, src/test/java/org/jabref/logic/exporter/ModsExportFormatFilesTest.java, src/test/java/org/jabref/logic/git/SlrGitHandlerTest.java, src/test/java/org/jabref/logic/net/URLDownloadTest.java, src/test/java/org/jabref/logic/util/io/FileUtilTest.java
Since sometimes PRs just ignore the existing logging framework I propose an automated test for the use of `System.out.*`. Can be overridden by annotating a class with `@AllowedToUseStandardStreams`.
=> Restrict use of standard streams

src/test/java/org/jabref/logic/util/io/FileUtilTest.java
After running the coverage test, I find two methods are not tested.
So I added two test cases for this feature and they all passed.
=> add: add test cases for FileUtil

CHANGELOG.md, src/main/java/org/jabref/gui/keyboard/TextInputKeyBindings.java
Fixes https://github.com/koppor/jabref/issues/562
=> Fix missing clear action on pressing esc within the "Filter groups" field

eclipse.gradle
Suddenly these ones seem to be necessary again in eclipse
=> Fix eclipse config

src/main/java/org/jabref/gui/entryeditor/fileannotationtab/FileAnnotationViewModel.java, src/test/java/org/jabref/gui/entryeditor/fileannotationtab/FileAnnotationViewModelTest.java
The code for removing newlines & hyphens before linebreaks is inconsistent and lacks test cases for the part of when annotation doesn't have LinkedFileAnnotation.
=> adjust and add testcases for FileAnnotationViewModel

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fetcher/MedlineFetcher.java, src/main/java/org/jabref/logic/importer/fetcher/transformers/MedlineQueryTransformer.java, src/test/java/org/jabref/logic/importer/fetcher/MedlineFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/transformers/IEEEQueryTransformerTest.java, src/test/java/org/jabref/logic/importer/fetcher/transformers/SuffixTransformerTest.java
Supports the default search fields and boolean operators
The MedlineQueryTransformer is a SuffixTransformer; therefore, I added a new test class. However, I then noticed that the default test cases only over quoted strings whereas Medline uses unquoted strings, so I did not add a test case.
Test class is still useful for future suffix transformers
Fixes https://discourse.jabref.org/t/native-pubmed-search/3354
=> Add Pubmed/Medline Query Transformer

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/SourceTab.java
Big thank you to @ThiloteE and @Siedlerchr for all the provided information in #8012 that help me to find the root of this issue.
1. We have a entry with only `author` and `groups` as fields.
2. When we right click on group `111` and click on "Remove selected entries from this group", this entry will be deleted and still stay in `previousEntry` and `outOfFocusBound` variables.
3. However, `previousEntry` or `outOfFocusBound` only have `author` as field after "Remove selected entries from this group".
4. In the image below, we are iterating through all fields in `newEntry` which has keys `author` and `groups`.
6. Since `outOfFocusBound` does not have `groups` field, assigning value to a null result in error.
Fixes #8012
Add a validation before setting value to a field.
```
if …
```
=> Fix right clicking a group and choosing "remove selected entries from this group" leads to error when Bibtex source tab is selected

src/main/java/org/jabref/gui/JabRefDialogService.java
In https://github.com/JabRef/jabref/pull/8775#discussion_r870153000, I suggested a change for collapsed notifications to improve their UX. Since this has not been implemented there, I went ahead with my own approach.
The collapsed notifications contain a hint to the event log. However, for users, it is likely tiresome to find the menu entry and open the event log from there. Thus, when clicking the collapsed notification, the event log opens now.
Not sure, whether the way I did it is clean, so open for feedback.
An additional thing I noticed is that the event log is empty for me (not the case on the stable build). Probably not related, possibly, an issue should be created for it.
=> Open event log when clicking on collapsed notification

src/test/java/org/jabref/logic/citationstyle/CitationStyleGeneratorTest.java, src/test/java/org/jabref/logic/citationstyle/CitationStyleTest.java
Adding test cases to help improve testing for the citation styles.
Added two test cases to check citation styles non-default (IEEE) styles as the other styles were not being tested. Added testACMCitation and testAPACitation to cover the corresponding citation styles, which are imported from (build/resources/main/csl-styles/acm-siggraph.csl) and (build/resources/main/csl-styles/apa-6th-edition.csl). Also, added a test case for discoverCitationStyles to improve code coverage for the CitationStyle class.
=> Add: Add test cases for non-default styles in CitationStyleTest

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupTreeView.java
> When I want to assign an entry to a subgroup, I have to first expand the parent group and then drag-and-drop my entry in the appropriate subgroup. The problem is that when I expand the group, by clicking on the arrow on the right, the group gets activated (the entry table only shows the group entries) and, therefore, I have to go back to "All entries" and locate my entry again. The parent group gets activated when collapsing it as well.
Fixes: #7982 
Fixes #3176 
```
if (event.getButton() == MouseButton.SECONDARY || event.getTarget() instanceof StackPane) {
// Prevent right-click to select group
event.consume();
}
```
https://user-images.githubusercontent.com/49628911/167790196-3190698a-dafb-4752-9807-6b790f0f9277.mp4
It might not be a good idea to only check eventTarget that returns …
=> Prevent group expansion arrow from activating group when expanding or collapsing

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefFrame.java
I delete the DOI element directly. That way, it works well on a small screen.
link #8774 
- [x ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.
=> fixed for Don't show social links in menu bar #8774

src/main/java/org/jabref/logic/exporter/AtomicFileOutputStream.java, src/main/java/org/jabref/logic/util/io/FileUtil.java
Fixes spelling of compliant in FileUtil.
=> Fixes spelling of compliant

README.md
In the past we had some PRs which were not mergable for fundamental design changes we could not accept. This change to the readme tries to prevent contributors to waste time and work.
=> Update Readme.md for early contributor guidance

src/main/java/org/jabref/gui/JabRefMain.java
Noticed that while debugging another issue
=> Lucene dir checkers should only delete lucene dirs

CHANGELOG.md, src/main/java/org/jabref/gui/preferences/PreferencesDialogViewModel.java, src/main/java/org/jabref/gui/preferences/network/NetworkTabViewModel.java, src/main/java/org/jabref/logic/net/ProxyRegisterer.java, src/main/resources/l10n/JabRef_en.properties, src/test/java/org/jabref/logic/importer/fetcher/DoiFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/DoiResolutionTest.java
Follow up to https://github.com/JabRef/jabref/pull/8583
I did following:
1. fetch DOI
2. see SSL error
3. add custom SSL certificate
4. fetch DOI
5. see SSL error
6. restart JabRef
7. fetch DOI
8. see DOI
To prevent WTFs at users, I added a restart warning:
I digged in the code for URLDownload, but could not find the place for ssl certficate handling. I would assume, Java does some caching...
=> Add restart warning on SSL configuration change

.github/workflows/tests.yml, docs/adr/0025-reviewdog-reviews.md
There are more and more pull requests coming in JabRef. A significant number of them does not follow our guidelines to setup a workspace.
The contributors do not check our failing tests and they should get instant feedback.
I checked [comment-failure-action](https://github.com/quipper/comment-failure-action).
It will produce lots of similar comments at each run (https://github.com/quipper/comment-failure-action/issues/224).
Therefore, I did not use it.
The solution is to let reviewdog create a review.
=> Reviewdoc: Comment on PRs

CHANGELOG.md, src/main/java/org/jabref/logic/remote/client/RemoteClient.java, src/main/java/org/jabref/logic/remote/server/RemoteListenerServerLifecycle.java
In some instances, connecting to an existing JabRef instance may take longer
than the original 200ms timeout. Here we increase that timeout to a full
second. If it takes longer than that to connect to an existing instance,
chances are something else bad is going on.
Additionally, in a case where we attempt a ping but it fails for some reason,
but we're also unable to bind the port to listen ourselves, we give the
user a more informative error message about the potential cause of that
problem, and offer two possible solutions: figure out what other process
is already binding the port, or file a bug if that process happens to be
JabRef (since that would indicate that a 1s timeout isn't sufficient).
Fixes #8653.
=> Increase the network connection timeout and improve error message

src/main/java/org/jabref/gui/help/AboutDialogViewModel.java, src/main/java/org/jabref/logic/util/BuildInfo.java
It seems that the property is null when javafx is not yet loaded; therefore, we check that in the about dialog as well
=> Fix javafx version not displayed in About Dialog

buildres/linux/jabrefHost.py
closes https://github.com/JabRef/jabref/issues/8922
=> Pass the data as a string for the browser extension

CHANGELOG.md, src/main/java/org/jabref/gui/maintable/columns/FileColumn.java
Fixes #8930
Example icon for mime type application/excel
=> Show pdf icon for mime type in maintable

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefDialogService.java, src/main/java/org/jabref/gui/theme/ThemeManager.java, src/main/java/org/jabref/gui/util/BaseDialog.java
Remove `installCss(dialogScene)` from dialogs because JavaFX already handle that
- If we update dialog stylesheet ourselves then we're breaking the binding made by JavaFX and thus unexpected behaviors may/will happen
```
java.lang.IndexOutOfBoundsException: toIndex = 3
at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:507)
at java.base/java.util.AbstractList.subList(AbstractList.java:497)
at javafx.base@18/javafx.collections.ModifiableObservableListBase.subList(ModifiableObservableListBase.java:196)
at javafx.base@18/com.sun.javafx.binding.ContentBinding$ListContentBinding.onChanged(ContentBinding.java:114)
at javafx.base@18/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
at …
```
=> Fix theme switching exception

src/test/java/org/jabref/logic/importer/fetcher/ResearchGateTest.java
"Fixes"
```
ResearchGateTest > performSearchWithBibEntry() FAILED
org.jabref.logic.importer.FetcherException: ResearchGate server unavailable
```
=> Disable ResearchGateTest on CI

src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/maintable/MainTable.java, src/main/java/org/jabref/gui/maintable/RightClickMenu.java, src/main/java/org/jabref/gui/menus/ChangeEntryTypeAction.java, src/main/java/org/jabref/gui/menus/ChangeEntryTypeMenu.java
=> Refactor context menu entry types changing

CHANGELOG.md, src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/gui/search/RebuildFulltextSearchIndexAction.java, src/main/java/org/jabref/logic/pdf/search/indexing/IndexingTaskManager.java, src/main/java/org/jabref/logic/pdf/search/indexing/PdfIndexer.java
A user might have deleted a link to a fulltext-file in the source tex
file and we need to reflect that change in the index as well.
=> Cleanup index when opening a library

CHANGELOG.md, src/main/java/org/jabref/logic/exporter/BibtexDatabaseWriter.java, src/main/java/org/jabref/logic/importer/fileformat/BibtexImporter.java, src/main/java/org/jabref/model/metadata/MetaData.java, src/test/java/org/jabref/logic/exporter/BibtexDatabaseWriterTest.java, src/test/java/org/jabref/logic/importer/fileformat/BibtexImporterTest.java, src/test/resources/org/jabref/logic/importer/fileformat/encoding-utf-8-with-header-with-databasetypecomment.bib, src/test/resources/org/jabref/logic/importer/fileformat/encoding-utf-8-without-header-with-databasetypecomment.bib
Based on the forum post https://discourse.jabref.org/t/encoding-utf-8-not-in-bib-file/3438?u=koppor.
We should keep the header if it is in the file, because
> I’ll need this first line of “% Encoding: UTF-8” when using my bib file in other programs 
The deletion "feature" was introduced at https://github.com/JabRef/jabref/pull/8506.
=> Keep UTF-8 encoding header if present

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/gui/maintable/MainTable.java
Fixed [https://github.com/koppor/jabref/issues/521](https://github.com/koppor/jabref/issues/521)
by adding a new feature that allows to drag selected entries, and drop them to other opened inactive bib library tabs.
Now when dragging selected entries in main table, JabRef allows user to drop it on another opened library tab, and this item will be copied and added to the dropped library accordingly. Drop to current active tab is disallowed. If there're potential duplicated entries, JabRef will ask user to confirm and choose copy behavior (similar to ctrl-c/v copy and paste).
[![screenshot.gif](https://s8.gifyu.com/images/screenshot.gif)](https://gifyu.com/image/SKPDF)
=> Fixes koppor/jabref#521 - Allow to drag&drop selected bib entries to other library tabs

CHANGELOG.md, src/main/java/org/jabref/gui/shared/SharedDatabaseLoginDialogViewModel.java, src/main/java/org/jabref/logic/shared/prefs/SharedDatabasePreferences.java
With this changes, the autosave folder and tick in the shared database opening dialog is remembered for the next time. I introduced these two things as new attributes of `SharedDatabasePreferences`.
Fixes  #7516.
Please check if this changes are as intended. I have seen that there are preference attributes for all other elements of the shared database opening dialog, but not for these two. Maybe there is a reason for that. But I think the new changes more convenient when you frequently open the shared database and want to synchronize the same BIB file everytime.
=> Autosave folder and checkbox is remembered

src/main/java/org/jabref/gui/edit/automaticfiededitor/AutomaticFieldEditorDialog.fxml, src/main/java/org/jabref/gui/edit/automaticfiededitor/copyormovecontent/CopyOrMoveFieldContentTab.fxml, src/main/resources/l10n/JabRef_en.properties
=> Add missing translations for AutomaticFieldEditor

CHANGELOG.md, src/main/java/org/jabref/model/database/BibDatabase.java
Revert BibDatabase to previous state
Fixes #9041
=> Fix performance regresssion

src/main/java/org/jabref/gui/exporter/SaveDatabaseAction.java, src/main/java/org/jabref/logic/autosaveandbackup/BackupManager.java, src/main/java/org/jabref/logic/util/io/FileUtil.java
The BackupManager did not honor the EOL setting of the library. It could be that users hit strange messages when starting JabRef. This PR fixes that.
=> Keep EOL setting at backups

CHANGELOG.md
=> Add the three-way merge changes to CHANGELOG.md

src/main/java/org/jabref/logic/autosaveandbackup/AutosaveManager.java
No need for "synchronized" at autosave, because there is a throttler
=> Small improvement for AutoSaveManager

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefMain.java, src/main/java/org/jabref/gui/openoffice/OOBibBaseConnect.java
Fixes #9075 
Closes the OO-Bridge when JabRef exits. If none is open, nothing happens. Otherwise the bridge is closed, JabRef exits but the LO document stays open
=> Close OO connection on JabRef exit

src/main/java/org/jabref/logic/autosaveandbackup/BackupManager.java, src/test/java/org/jabref/logic/autosaveandbackup/BackupManagerTest.java
In case a `.bak` is older than a `.bib` - and it differs, a dialog is shown. This is not OK in a scenario, where git tooling, cloud synchronization or manual editing of the file was done. Thus, this PR adds checks for timestamps.
- Follow-up to https://github.com/JabRef/jabref/pull/9054.
- Fixes https://github.com/koppor/jabref/issues/597
---
=> Backupmanager: Include check for TimeStamp at .bak files

CHANGELOG.md, src/main/java/org/jabref/logic/formatter/casechanger/Word.java, src/test/java/org/jabref/logic/formatter/casechanger/TitleCaseFormatterTest.java, src/test/java/org/jabref/logic/importer/fileformat/IsiImporterTest.java
Fixes #9068 
Closes #9101 
Closes #9100 
Closes #9099
What: I implemented a change to the Word.java file so that it can capitalize any part of a title that follows one of the characters from the en-dash list, like "-", "~" or "〰" on the Title Case method. For example, the title "test-driven software" becomes "Test-Driven Software" instead of the previous result "Test-driven Software".
Why: Following the issue #9068  discussion, there was a need to solve such a problem.
Context:  This change was incentivized by the University that I'm a part of at the moment. On its course, I ended up studying Test-Driven Development (TDD), where this project (JabRef) was one of the options to work on using the TDD method. Therefore, i chose this issue to work on.
=> Fix title case capitalization after en-dash characters

src/main/java/org/jabref/gui/mergeentries/newmergedialog/FieldRowView.java
context: Show Diff: Split View: I would think again of the colors: red means removal in my experience - can another color be used? -- I would see both first two columns as input for the Merged Entry. Thus, I am a bit confused by using red as color at the "Original Entry"
*Originally posted by @koppor*
=> Hide diffs when one of the field values is blank a.k.a no conflict

CHANGELOG.md, src/main/java/org/jabref/logic/crawler/StudyRepository.java, src/main/java/org/jabref/model/study/Study.java, src/test/java/org/jabref/logic/crawler/StudyRepositoryTest.java, src/test/java/org/jabref/logic/crawler/StudyYamlParserTest.java, src/test/resources/org/jabref/logic/crawler/study.yml
We removed "last-search-date" from the SLR feature, because the last-search-date can be detucted from the git logs.
Ports one change of https://github.com/koppor/jabref/pull/559 to here.
=> SLR Remove "last-search-date"

CHANGELOG.md, src/main/java/org/jabref/logic/layout/format/NameFormatterPreferences.java
=> Fix exception that occurs when saving name formatters
