CHANGELOG
src/main/java/net/sf/jabref/AppearancePrefsTab.java
src/main/java/net/sf/jabref/BasePanel.java
src/main/java/net/sf/jabref/EntryEditorTab.java
src/main/java/net/sf/jabref/FieldNameLabel.java
src/main/java/net/sf/jabref/GUIGlobals.java
src/main/java/net/sf/jabref/JabRefFrame.java
src/main/java/net/sf/jabref/JabRefPreferences.java
src/main/java/net/sf/jabref/SidePaneComponent.java
src/main/java/net/sf/jabref/gui/MainTable.java

Cleaned-up version of older pull request https://github.com/JabRef/jabref/pull/43

Add option to hide/show gridlines in the main table

---

CHANGELOG
src/main/java/net/sf/jabref/AdvancedTab.java

Added some predefined look and feels in preference window (some of them are documented [here]( https://sourceforge.net/p/jabref/mailman/message/32703401/), but are not working by default on windows).

Added some predefined look and feels in preference window 

---

CHANGELOG
build.gradle
src/main/java/net/sf/jabref/Globals.java
src/main/java/net/sf/jabref/imports/TextAnalyzer.java

I think it should be fine to enable flexible updates for new patch versions of pdfbox.

Bump pdfbox dependency versions

---

src/main/java/net/sf/jabref/BasePanel.java
src/main/java/net/sf/jabref/FieldContentSelector.java
src/main/java/net/sf/jabref/JabRefFrame.java
src/main/java/net/sf/jabref/JabRefPreferences.java
src/main/java/net/sf/jabref/UrlDragDrop.java
src/main/java/net/sf/jabref/external/ExternalFilePanel.java
src/main/java/net/sf/jabref/external/FileLinksUpgradeWarning.java
src/main/java/net/sf/jabref/external/MoveFileAction.java
src/main/java/net/sf/jabref/external/WriteXMPEntryEditorAction.java
src/main/java/net/sf/jabref/gui/GenFieldsCustomizer.java
src/main/java/net/sf/jabref/gui/MainTableSelectionListener.java
src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java
src/main/java/net/sf/jabref/gui/entryeditor/EntryEditorTab.java
src/main/java/net/sf/jabref/gui/entryeditor/EntryEditorTabFocusListener.java
src/main/java/net/sf/jabref/gui/entryeditor/EntryEditorTabList.java
src/main/java/net/sf/jabref/gui/entryeditor/SimpleUrlDragDrop.java
src/main/java/net/sf/jabref/gui/fieldeditors/FileListEditor.java
src/main/java/net/sf/jabref/gui/journals/JournalAbbreviationsUtil.java
src/main/java/spl/PdfImporter.java
src/test/java/net/sf/jabref/logic/autocompleter/AutoCompleterTest.java

Moves the classes related to the EntryEditor into a separate GUI package and performs a few refactorings and quality improvements on the way.

Move and refactor EntryEditor

---

src/main/java/net/sf/jabref/logic/util/io/URLUtil.java
src/test/java/net/sf/jabref/logic/util/io/URLUtilTest.java

Fixes detection of domains such as google.co.uk / co.jp / etc. and moves test class to test folder.

Minor improvement in GoogleUrlCleaner #126

---

src/main/java/net/sf/jabref/JabRefPreferences.java
src/main/java/net/sf/jabref/gui/GUIGlobals.java

- Fields in table are not colored (required/optional)
- Owner column is not shown
- Slightly increasing row padding in table

Small changes to default preferences

---

CHANGELOG
src/main/java/net/sf/jabref/JabRef.java
src/main/java/net/sf/jabref/JabRefPreferences.java
src/main/java/net/sf/jabref/importer/ImportFormatReader.java
src/main/java/net/sf/jabref/logic/l10n/Encodings.java
src/main/java/net/sf/jabref/migrations/PreferencesMigrations.java

Fix encoding strings

---

CHANGELOG
src/main/java/net/sf/jabref/Globals.java
src/main/java/net/sf/jabref/JabRef.java
src/main/java/net/sf/jabref/exporter/layout/format/JournalAbbreviator.java
src/main/java/net/sf/jabref/gui/journals/AbbreviateAction.java
src/main/java/net/sf/jabref/gui/journals/JournalAbbreviationsUtil.java
src/main/java/net/sf/jabref/gui/journals/ManageJournalsPanel.java
src/main/java/net/sf/jabref/gui/journals/UnabbreviateAction.java
src/main/java/net/sf/jabref/gui/preftabs/AdvancedTab.java
src/main/java/net/sf/jabref/importer/fetcher/IEEEXploreFetcher.java
src/main/java/net/sf/jabref/logic/autocompleter/ContentAutoCompleters.java
src/main/java/net/sf/jabref/logic/journals/Abbreviations.java
src/main/java/net/sf/jabref/logic/journals/JournalAbbreviationRepository.java
src/test/java/net/sf/jabref/logic/journals/AbbreviationParserTest.java
src/test/java/net/sf/jabref/logic/journals/JournalAbbreviationRepositoryTest.java

- Fixes GH Bug #173: Personal journal abbreviation list is not loaded twice
- Bugfix: Preview of external journal abbreviation list now displays the correct list

Journal Abbreviation Improvements

---

CHANGELOG
src/main/java/net/sf/jabref/importer/HTMLConverter.java

More characters and combining accents from various sources
Used proper logging instead of print out
Log a warning for non-converted Unicode characters

Added more characters to HTML converter and better logging

---

CHANGELOG
src/main/java/net/sf/jabref/importer/fetcher/IEEEXploreFetcher.java

Fixed a bug which sometimes stalled the search, leaving some entries not parsed.
Changed the earlier print out logging/debugging to use the logging system.
Code clean up.

Fixed bug in IEEEXploreFetcher

---

CHANGELOG
src/main/java/net/sf/jabref/logic/util/strings/CaseChangers.java
src/test/java/net/sf/jabref/logic/util/CaseChangersTest.java

New attempt with the same code and same limitations, but using branches. So hopefully possible to merge. I also used the JabRef formatter and clean up. Hopefully, I got it correct.

Improved CaseChangers

---

CHANGELOG
src/main/java/net/sf/jabref/gui/fieldeditors/contextmenu/ConversionMenu.java
src/main/java/net/sf/jabref/gui/fieldeditors/contextmenu/FieldTextMenu.java
src/main/java/net/sf/jabref/importer/fetcher/DOItoBibTeXFetcher.java
src/main/java/net/sf/jabref/logic/util/strings/Converters.java
src/test/java/net/sf/jabref/logic/util/ConvertersTest.java

Accessing these conversions without going through clean up can be quite useful.

Added conversion menu on right click in text field (#191)

---

CHANGELOG
src/main/java/net/sf/jabref/JabRefPreferences.java
src/main/java/net/sf/jabref/external/DroppedFileHandler.java
src/main/java/net/sf/jabref/external/ExternalFileTypeEditor.java
src/main/java/net/sf/jabref/external/ExternalFileTypeEntryEditor.java
src/main/java/net/sf/jabref/external/PushToEmacs.java
src/main/java/net/sf/jabref/external/PushToLatexEditor.java
src/main/java/net/sf/jabref/external/PushToLyx.java
src/main/java/net/sf/jabref/external/PushToTeXstudio.java
src/main/java/net/sf/jabref/external/PushToTexmaker.java
src/main/java/net/sf/jabref/external/PushToVim.java
src/main/java/net/sf/jabref/external/PushToWinEdt.java
src/main/java/net/sf/jabref/groups/AutoGroupDialog.java
src/main/java/net/sf/jabref/groups/EntryTableTransferHandler.java
src/main/java/net/sf/jabref/gui/FileListEntryEditor.java
src/main/java/net/sf/jabref/gui/actions/CleanUpAction.java
src/main/java/net/sf/jabref/gui/fieldeditors/FileListEditor.java
src/main/java/net/sf/jabref/gui/journals/ManageJournalsPanel.java
src/main/java/net/sf/jabref/gui/labelPattern/ResolveDuplicateLabelDialog.java
src/main/java/net/sf/jabref/gui/preftabs/NetworkTab.java
src/main/java/net/sf/jabref/migrations/FileLinksUpgradeWarning.java
src/main/java/net/sf/jabref/util/Util.java

Replaced the deprecated DefaultFormBuilder with FormBuilder in about ten instances.
As I was working with the external programs code, the strings there were unified to ease the translation work a bit.

Replaced DefaultFormBuilder with FormBuilder

---

src/main/antlr3/net/sf/jabref/bst/Bst.g
src/main/java/net/sf/jabref/bst/VM.java
src/main/java/net/sf/jabref/exporter/layout/format/RTFChars.java
src/main/java/net/sf/jabref/logic/search/describer/ContainsAndRegexBasedSearchRuleDescriber.java
src/test/java/net/sf/jabref/bst/TestVM.java

Reduces console output during tests dramatically. This reduces the console output in travis, helping to find the cause for a failing test faster with less scrolling.

Less console output in tests

---

src/main/java/net/sf/jabref/JabRefPreferences.java
src/main/java/net/sf/jabref/gui/ColorSetupPanel.java
src/main/java/net/sf/jabref/gui/DatabasePropertiesDialog.java
src/main/java/net/sf/jabref/gui/preftabs/FontSelectorDialog.java
src/main/java/net/sf/jabref/wizard/text/gui/TextInputDialog.java

Fixed a bug in color preferences recently introduced.
Replaced the deprecated DefaultFormBuilder by FormBuilder in DatabasePropertiesDialog.
Removed some casts which weren't required.

Bug fix in color preferences, replaced DefaultFormBuilder and clean ups

---

CHANGELOG
src/main/java/net/sf/jabref/model/database/BibtexDatabase.java
src/main/java/net/sf/jabref/util/MassSetFieldAction.java

Added a JComboCox for "field" in MassSetFieldDialog (Set/clear/rename field in right-click menu).
Seemed to be quite convenient compared to typing the field name.

Added JComboBox in MassSetFieldDialog

---

src/main/java/net/sf/jabref/exporter/ExportFormats.java
src/main/java/net/sf/jabref/exporter/layout/LayoutEntry.java
src/main/java/net/sf/jabref/groups/EntryTableTransferHandler.java
src/main/java/net/sf/jabref/gui/ColorSetupPanel.java
src/main/java/net/sf/jabref/gui/EntryMarker.java
src/main/java/net/sf/jabref/gui/ImportInspectionDialog.java
src/main/java/net/sf/jabref/gui/MainTable.java
src/main/java/net/sf/jabref/gui/MainTableFormat.java
src/main/java/net/sf/jabref/gui/actions/CleanUpAction.java
src/main/java/net/sf/jabref/gui/help/HelpAction.java
src/main/java/net/sf/jabref/gui/help/HelpDialog.java
src/main/java/net/sf/jabref/gui/preftabs/EntryEditorPrefsTab.java
src/main/java/net/sf/jabref/gui/preftabs/ExternalTab.java
src/main/java/net/sf/jabref/gui/preftabs/LabelPatternPrefTab.java
src/main/java/net/sf/jabref/importer/fetcher/DBLPHelper.java
src/main/java/net/sf/jabref/importer/fetcher/GeneralFetcher.java
src/main/java/net/sf/jabref/importer/fetcher/INSPIREFetcher.java
src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java
src/main/java/net/sf/jabref/importer/fileformat/MedlineHandler.java
src/main/java/net/sf/jabref/logic/formatter/casechanger/Title.java
src/main/java/net/sf/jabref/logic/labelPattern/LabelPatternUtil.java
src/main/java/net/sf/jabref/logic/logging/Cache.java
src/main/java/net/sf/jabref/logic/search/describer/ContainsAndRegexBasedSearchRuleDescriber.java
src/main/java/net/sf/jabref/openoffice/OOBibBase.java
src/main/java/net/sf/jabref/openoffice/OpenOfficePanel.java
src/main/java/net/sf/jabref/wizard/text/gui/TextInputDialog.java
src/test/java/net/sf/jabref/TestIconsProperties.java

Warning removal

---

src/main/java/net/sf/jabref/JabRefPreferences.java
src/main/java/net/sf/jabref/external/push/AbstractPushToApplication.java
src/main/java/net/sf/jabref/external/push/PushToApplicationButton.java
src/main/java/net/sf/jabref/external/push/PushToApplications.java

- Fixed so that the storing and restoring of last used application to push to does not rely on possible translation.
- Ordered applications alphabetically
- Set TeXstudio as default application
(I ran format source on PushToApplicationButton so it looks more modified than it actually is.)

Improved the push to application storing and restoring 

---

src/main/java/net/sf/jabref/gui/SidePaneComponent.java
src/main/java/net/sf/jabref/gui/SidePaneManager.java

Java 8 conversion and removal of unused methods in SidePaneManager and SidePaneComponent.

Java8 + SidePane

---

src/main/java/net/sf/jabref/gui/ReplaceStringDialog.java
src/main/java/net/sf/jabref/importer/OpenDatabaseAction.java
src/main/java/net/sf/jabref/logic/util/strings/StringUtil.java
src/test/java/net/sf/jabref/logic/util/strings/StringUtilTest.java
src/test/java/net/sf/jabref/util/UtilTest.java

Replaced/removed/unified some methods in StringUtil and added some tests in StringUtilTest.

Clean-up of StringUtil and some added tests

---

CHANGELOG.md
src/main/java/net/sf/jabref/logic/formatter/bibtexfields/PageNumbersFormatter.java
src/main/java/net/sf/jabref/logic/integrity/IntegrityCheck.java
src/test/java/net/sf/jabref/logic/formatter/PageNumbersFormatterTest.java
src/test/java/net/sf/jabref/logic/integrity/IntegrityCheckTest.java

Pages checker

---

src/main/java/net/sf/jabref/logic/formatter/minifier/AuthorsMinifier.java
src/test/java/net/sf/jabref/logic/formatter/minifier/AuthorsMinifierTest.java

We wanted to have some minimizer formatters for a functionality to auto-minify bibtex files for conference papers.
This PR adds a first minimizer, the author minimizer from Simon's textools project.

Initial author minimizer impl

---

src/test/java/net/sf/jabref/logic/util/io/UtilFindFileTest.java
src/test/java/net/sf/jabref/testutils/AssertUtil.java

Found a file which better resides in testutils.

Moved AssertUtil to tests

---

src/main/java/net/sf/jabref/JabRefPreferences.java
src/main/java/net/sf/jabref/gui/FileHistoryMenu.java
src/main/java/net/sf/jabref/gui/JabRefFrame.java
src/main/java/net/sf/jabref/logic/util/io/FileHistory.java
src/test/java/net/sf/jabref/logic/util/io/FileHistoryTest.java

Separated FileHistory into FileHistoryMenu which contains the menu functions and FileHistory which contains the logic for the file history.

Extracted logic out of FileHistory

---

src/test/java/net/sf/jabref/exporter/layout/LatexFieldFormatterTests.java

Inspired by the old (and fixed) bug [SF #1191](http://sourceforge.net/p/jabref/bugs/1191/).

Add a few tests to the field formatter checking multiline normalization

---

src/main/java/net/sf/jabref/JabRef.java
src/main/java/net/sf/jabref/JabRefException.java
src/main/java/net/sf/jabref/JabRefPreferences.java
src/main/java/net/sf/jabref/gui/preftabs/PreferencesDialog.java
src/test/java/net/sf/jabref/JabRefPreferencesTest.java

(Inspired by #301) 
Ultimate Goal: Improving the exception handling by...
- replacing generic Exceptions by custom exceptions
- support localization already on exception level
... in the complete project.
Current status: 
- showing concept using newly introduced `JabRefException` for the preferences import

Concept: Improve exception handling

---

CHANGELOG.md
src/main/java/net/sf/jabref/openoffice/AutoDetectPaths.java
src/main/java/net/sf/jabref/openoffice/OpenOfficePanel.java

Changed default file names suitable for OO.o 4 and LO 5 and added support for having both OpenOffice.org and LibreOffice installed (sort of)

[WIP] OpenOffice.org/LibreOffice improvements

---

src/main/java/net/sf/jabref/gui/FileListEntry.java
src/main/java/net/sf/jabref/gui/FileListTableModel.java
src/main/java/net/sf/jabref/logic/util/strings/StringUtil.java
src/test/java/net/sf/jabref/logic/util/strings/StringUtilTest.java

The ones that remain are:
Related change in this PR:
* Change in FileListTableModel, which basically reimplemented StringUtil.encodeStringArray

Added tests for most methods in StringUtils 

---

src/main/java/net/sf/jabref/MetaData.java
src/main/java/net/sf/jabref/bibtex/BibtexEntryWriter.java
src/main/java/net/sf/jabref/exporter/AutoSaveManager.java
src/main/java/net/sf/jabref/exporter/FileActions.java
src/main/java/net/sf/jabref/gui/ImportInspectionDialog.java
src/main/java/net/sf/jabref/gui/search/SearchResultsDialog.java
src/main/java/net/sf/jabref/importer/fetcher/ACMPortalFetcher.java
src/main/java/net/sf/jabref/importer/fetcher/GoogleScholarFetcher.java
src/main/java/net/sf/jabref/logic/msbib/MSBibEntry.java
src/test/java/net/sf/jabref/logic/remote/RemoteTest.java

and cleaned up some disabled code in ImportInspectionDialog.

Fixed some issues reported by Coverity

---

src/main/java/net/sf/jabref/exporter/CustomExportDialog.java
src/main/java/net/sf/jabref/gui/BibtexFields.java
src/main/java/net/sf/jabref/gui/DatabasePropertiesDialog.java
src/main/java/net/sf/jabref/gui/EntryCustomizationDialog2.java
src/main/java/net/sf/jabref/gui/preftabs/FileSortTab.java
src/main/java/net/sf/jabref/gui/preftabs/TablePrefsTab.java
src/main/java/net/sf/jabref/sql/SQLUtil.java
src/main/java/net/sf/jabref/wizard/text/gui/TextInputDialog.java

Some more changes to get rid of Coverity warnings.

More fixes of Coverity issues

---

src/main/resources/l10n/Menu_fr.properties

French localization: translation of empty strings

French localization: translation of empty strings

---

src/main/java/net/sf/jabref/gui/actions/CleanUpAction.java
src/main/java/net/sf/jabref/logic/cleanup/FieldFormatterCleanup.java
src/main/java/net/sf/jabref/logic/formatter/bibtexfields/LatexFormatter.java
src/test/java/net/sf/jabref/logic/formatter/bibtexfields/LatexFormatterTest.java
src/test/java/net/sf/jabref/logic/formatter/bibtexfields/PageNumbersFormatterTest.java
src/test/java/net/sf/jabref/logic/formatter/bibtexfields/UnitFormatterTest.java
src/test/java/net/sf/jabref/logic/formatter/casechanger/CaseKeeperTest.java

Instead of #427 (easier to start all over as some files were already moved).

Cleanup tests and LatexFormatter

---

src/main/java/net/sf/jabref/bst/BibtexWidth.java
src/main/java/net/sf/jabref/exporter/MySQLExport.java
src/main/java/net/sf/jabref/exporter/PostgreSQLExport.java
src/main/java/net/sf/jabref/gui/DatabasePropertiesDialog.java
src/main/java/net/sf/jabref/gui/preftabs/GeneralTab.java
src/main/java/net/sf/jabref/importer/fileformat/BibTeXMLHandler.java
src/main/java/net/sf/jabref/logic/formatter/bibtexfields/UnitFormatter.java
src/main/java/net/sf/jabref/logic/formatter/casechanger/CaseKeeper.java
src/main/java/net/sf/jabref/logic/util/strings/StringLengthComparator.java
src/main/java/net/sf/jabref/sql/exporter/DBExporter.java
src/main/java/net/sf/jabref/util/ManageKeywordsAction.java
src/test/java/net/sf/jabref/importer/DatabaseFileLookupTest.java
src/test/java/net/sf/jabref/logic/util/strings/StringLengthComparatorTest.java

Some cleanups and warning removals. Should get rid of six high impact Coverity issues (I hope).

Cleanups, warning removals, move and test.

---

src/main/java/net/sf/jabref/JabRefPreferences.java
src/main/java/net/sf/jabref/bst/TextPrefixFunction.java
src/main/java/net/sf/jabref/collab/StringChange.java
src/main/java/net/sf/jabref/external/ExternalFileTypeEntryEditor.java
src/main/java/net/sf/jabref/importer/fetcher/INSPIREBibtexFilterReader.java
src/main/java/net/sf/jabref/model/entry/BibtexString.java
src/main/java/net/sf/jabref/openoffice/OpenOfficePanel.java
src/test/java/net/sf/jabref/bibtex/comparator/BibtexStringComparatorTest.java
src/test/java/net/sf/jabref/model/entry/BibtexStringTest.java

was the original idea, but after Simon informed me about findbugs, a number of issues were sorted out. Still a few more tests are added.

Tests for comparators

---

src/main/java/net/sf/jabref/external/WriteXMPEntryEditorAction.java
src/main/java/net/sf/jabref/groups/GroupTreeNode.java
src/main/java/net/sf/jabref/gui/preftabs/FontSelectorDialog.java
src/main/java/net/sf/jabref/gui/search/SearchResultsDialog.java
src/main/java/net/sf/jabref/importer/fileformat/FreeCiteImporter.java
src/main/java/net/sf/jabref/logic/util/io/FileHistory.java
src/main/java/net/sf/jabref/sql/DBConnectDialog.java

Fixed a number of issues indicated by Coverity.

More small fixes

---

src/main/java/net/sf/jabref/external/DownloadExternalFile.java
src/main/java/net/sf/jabref/logic/labelPattern/LabelPatternUtil.java
src/test/java/net/sf/jabref/logic/remote/RemoteTest.java

Got rid of some more Coverity issues.

Some clean ups/issue fixes

---

src/main/java/net/sf/jabref/importer/fetcher/GoogleScholarFetcher.java
src/main/java/net/sf/jabref/importer/fileformat/MedlinePlainImporter.java
src/main/java/net/sf/jabref/importer/fileformat/RisImporter.java
src/main/java/net/sf/jabref/logic/labelPattern/LabelPatternUtil.java
src/main/java/net/sf/jabref/model/entry/CanonicalBibtexEntry.java
src/main/java/net/sf/jabref/model/entry/CustomEntryType.java
src/main/java/net/sf/jabref/model/entry/UnknownEntryType.java
src/main/java/net/sf/jabref/openoffice/AutoDetectPaths.java
src/main/java/net/sf/jabref/openoffice/StyleSelectDialog.java
src/main/java/net/sf/jabref/sql/DBImporterExporter.java
src/main/java/net/sf/jabref/util/Util.java

Some more fixes based on Coverity and findbugs.

Even more cleanups

---

src/main/java/net/sf/jabref/gui/actions/BiblatexCleanup.java
src/main/java/net/sf/jabref/gui/actions/CleanUpAction.java
src/main/java/net/sf/jabref/gui/actions/FileEntryCleaner.java
src/main/java/net/sf/jabref/gui/actions/RelativePathsCleanup.java
src/main/java/net/sf/jabref/gui/actions/RenamePdfCleanup.java
src/main/java/net/sf/jabref/gui/actions/UnicodeCleanup.java
src/main/java/net/sf/jabref/gui/undo/UndoableFieldChange.java
src/main/java/net/sf/jabref/importer/HTMLConverter.java
src/main/java/net/sf/jabref/logic/FieldChange.java
src/main/java/net/sf/jabref/logic/cleanup/Cleaner.java
src/main/java/net/sf/jabref/logic/cleanup/DoiCleanup.java
src/main/java/net/sf/jabref/logic/cleanup/FieldFormatterCleanup.java
src/main/java/net/sf/jabref/logic/cleanup/FormatterCleanup.java
src/main/java/net/sf/jabref/logic/cleanup/RemoveFieldCleanup.java
src/main/java/net/sf/jabref/logic/formatter/bibtexfields/MonthFormatter.java
src/main/java/net/sf/jabref/util/Util.java

I removed all the functionality from `CleanupAction` to separate classes. The next step would be to add tests....next PR :)

Refactor code from cleanup action to separate classes

---

CHANGELOG.md
src/main/java/net/sf/jabref/JabRefPreferences.java

Show author/editor and journal/publisher in the main table by default

---

src/main/java/net/sf/jabref/JabRefPreferences.java
src/main/java/net/sf/jabref/gui/BasePanel.java
src/main/java/net/sf/jabref/gui/preftabs/EntryEditorPrefsTab.java
src/main/java/net/sf/jabref/logic/autocompleter/AbstractAutoCompleter.java
src/main/java/net/sf/jabref/logic/autocompleter/AutoCompleteFirstNameMode.java
src/main/java/net/sf/jabref/logic/autocompleter/AutoCompletePreferences.java
src/main/java/net/sf/jabref/logic/autocompleter/AutoCompleter.java
src/main/java/net/sf/jabref/logic/autocompleter/AutoCompleterFactory.java
src/main/java/net/sf/jabref/logic/autocompleter/BibtexKeyAutoCompleter.java
src/main/java/net/sf/jabref/logic/autocompleter/ContentAutoCompleters.java
src/main/java/net/sf/jabref/logic/autocompleter/DefaultAutoCompleter.java
src/main/java/net/sf/jabref/logic/autocompleter/EntireFieldAutoCompleter.java
src/main/java/net/sf/jabref/logic/autocompleter/NameFieldAutoCompleter.java
src/test/java/net/sf/jabref/gui/autocompleter/AutoCompleterTest.java
src/test/java/net/sf/jabref/logic/autocompleter/AutoCompleterTest.java

Main change is that the preferences are moved to a separate class `AutoCompletePreferences`. I also added or reworked some comments.
The tests for AutoCompleter should be reworked. Next PR...

Refactor AutoCompleter code

---

src/main/java/net/sf/jabref/external/FindFullText.java
src/main/java/net/sf/jabref/gui/JabRefFrame.java
src/main/java/net/sf/jabref/gui/PreambleEditor.java
src/main/java/net/sf/jabref/gui/StringDialog.java
src/main/java/net/sf/jabref/gui/WrapLayout.java
src/main/java/net/sf/jabref/gui/preftabs/PreviewPrefsTab.java
src/main/java/net/sf/jabref/logic/util/OS.java
src/main/java/net/sf/jabref/model/entry/BibtexEntryTypes.java

Removes unused code.
Rationales are given for each removal in commit message.

Unused code

---

CHANGELOG.md
src/main/java/net/sf/jabref/sql/DbConnectAction.java
src/main/java/net/sf/jabref/sql/SQLUtil.java
src/main/java/net/sf/jabref/sql/exporter/DBExporter.java
src/main/java/net/sf/jabref/sql/exporter/PostgreSQLExporter.java
src/main/java/net/sf/jabref/sql/importer/DbImportAction.java
src/main/java/net/sf/jabref/sql/importer/PostgreSQLImporter.java

This may solve the problem in #473 
I was apparently a bit to enthusiastic in introducing try-with resources...

Fixed(?) PostgreSQL problems

---

CHANGELOG.md
src/main/java/net/sf/jabref/openoffice/OOBibBase.java
src/main/java/net/sf/jabref/openoffice/OpenOfficePanel.java

Now the OpenOffice/LibreOffice should work again on Linux (and on OSX).

Fixed #526

---

src/main/java/net/sf/jabref/JabRef.java
src/main/java/net/sf/jabref/gui/ParserResultWarningDialog.java
src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java
src/main/java/net/sf/jabref/importer/AutosaveStartupPrompter.java
src/main/java/net/sf/jabref/importer/ImportMenuItem.java
src/main/java/net/sf/jabref/importer/OpenDatabaseAction.java
src/main/java/net/sf/jabref/importer/ParserResult.java
src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java

Some restructuring of the ParserResult warnings code. Introduced a new class that is used in a number of other classes to do the same thing.

Changes to ParserResult warnings

---

src/main/java/net/sf/jabref/gui/BibtexFields.java
src/main/java/net/sf/jabref/gui/maintable/MainTableColumn.java

I think, we don't need alternative display names. This will surely confuse users.

Remove alternative display name since it is never set

---

src/main/java/net/sf/jabref/groups/EntryTableTransferHandler.java
src/main/java/net/sf/jabref/gui/BasePanel.java
src/main/java/net/sf/jabref/gui/FileListTableModel.java
src/main/java/net/sf/jabref/gui/fieldeditors/FileListEditorTransferHandler.java
src/main/java/net/sf/jabref/logic/util/io/FileFinder.java
src/main/java/net/sf/jabref/logic/util/io/FileUtil.java
src/main/java/net/sf/jabref/util/Util.java
src/test/java/net/sf/jabref/logic/util/io/FileUtilTest.java

* Found code that extracts the extension from a file or a file name and used the already existing method for that
* Added tests for that method

Made better use of getFileExtension and added tests

---

src/main/java/net/sf/jabref/gui/maintable/MainTable.java
src/main/java/net/sf/jabref/gui/maintable/MainTableNameFormatter.java
src/main/java/net/sf/jabref/gui/maintable/MainTableSelectionListener.java
src/main/java/net/sf/jabref/gui/maintable/PersistenceTableColumnListener.java
src/main/java/net/sf/jabref/gui/maintable/PreventDraggingJTableHeader.java
src/main/java/net/sf/jabref/gui/maintable/SpecialMainTableColumns.java

Some cleanups in MainTable and related files

---

src/main/java/net/sf/jabref/external/DroppedFileHandler.java
src/main/java/net/sf/jabref/external/ExternalFileType.java
src/main/java/net/sf/jabref/external/MoveFileAction.java
src/main/java/net/sf/jabref/external/SynchronizeFileField.java
src/main/java/net/sf/jabref/gui/EntryMarker.java
src/main/java/net/sf/jabref/logic/labelPattern/LabelPatternUtil.java
src/main/java/net/sf/jabref/logic/msbib/MSBibDatabase.java
src/main/java/net/sf/jabref/model/entry/BibEntry.java

Some more random fixes

---

CHANGELOG.md
src/main/java/net/sf/jabref/importer/fetcher/ACMPortalFetcher.java

Fixed #545 and some PMD cleanup.

Fixed #545 - ACM fetcher works again

---

src/main/java/net/sf/jabref/sql/importer/DBImporter.java

Avoid ConcurrentModificationException when reading column names

---

src/main/java/net/sf/jabref/sql/importer/DBImporter.java
src/main/java/net/sf/jabref/sql/importer/DBImporterResult.java
src/main/java/net/sf/jabref/sql/importer/DbImportAction.java

@koppor something like this?  (Also a StringBuffer instead of String-concatenation.)

Extracted the object array to its own class

---

src/main/java/net/sf/jabref/JabRefPreferences.java
src/main/java/net/sf/jabref/MetaData.java
src/main/java/net/sf/jabref/bibtex/BibEntryWriter.java
src/main/java/net/sf/jabref/logic/formatter/bibtexfields/UnitFormatter.java
src/main/java/net/sf/jabref/logic/formatter/casechanger/CaseKeeper.java
src/main/java/net/sf/jabref/logic/groups/GroupsUtil.java
src/main/java/net/sf/jabref/logic/journals/Abbreviation.java
src/main/java/net/sf/jabref/logic/journals/AbbreviationParser.java
src/main/java/net/sf/jabref/logic/journals/JournalAbbreviationRepository.java
src/main/java/net/sf/jabref/logic/labelPattern/AbstractLabelPattern.java
src/main/java/net/sf/jabref/logic/labelPattern/DatabaseLabelPattern.java
src/main/java/net/sf/jabref/logic/labelPattern/GlobalLabelPattern.java
src/main/java/net/sf/jabref/logic/labelPattern/LabelPatternUtil.java
src/main/java/net/sf/jabref/logic/net/Cookie.java
src/main/java/net/sf/jabref/logic/net/CookieHandlerImpl.java
src/main/java/net/sf/jabref/logic/util/DOI.java
src/main/java/net/sf/jabref/logic/util/OS.java
src/main/java/net/sf/jabref/logic/util/io/FileFinder.java
src/main/java/net/sf/jabref/logic/util/io/FileUtil.java
src/main/java/net/sf/jabref/logic/util/io/URLUtil.java
src/main/java/net/sf/jabref/logic/util/strings/Converters.java
src/main/java/net/sf/jabref/logic/util/strings/StringUtil.java
src/main/java/net/sf/jabref/util/Util.java
src/test/java/net/sf/jabref/logic/groups/GroupsUtilTest.java
src/test/java/net/sf/jabref/logic/util/strings/StringUtilTest.java
src/test/java/net/sf/jabref/model/entry/AuthorListTest.java

Logic cleanup

---

src/main/java/net/sf/jabref/bst/BibtexCaseChanger.java
src/main/java/net/sf/jabref/bst/BibtexNameFormatter.java
src/main/java/net/sf/jabref/bst/ChangeCaseFunction.java
src/main/java/net/sf/jabref/bst/FormatNameFunction.java
src/main/java/net/sf/jabref/bst/TextPrefixFunction.java
src/main/java/net/sf/jabref/bst/VM.java
src/test/java/net/sf/jabref/bst/TestVM.java

Fixed all but one of the possible* Coverity warnings for the bst package.
Also a PMD cleanup of all those files. Please see Github-comments in VM.java and see if you agree with me (the checks pass).
* The warnings for the automatically generated files seems more challenging.

Removed Coverity warning in bst and cleaned up all files there

---

src/main/java/net/sf/jabref/importer/fileformat/FieldContentParser.java
src/test/java/net/sf/jabref/importer/DatabaseFileLookupTest.java
src/test/java/net/sf/jabref/importer/fetcher/GVKParserTest.java
src/test/java/net/sf/jabref/util/XMPSchemaBibtexTest.java

These tests were failing locally for me (but apparently not on the CI server).

Fix failure of some tests due to non initialized preferences

---

src/main/java/net/sf/jabref/JabRef.java
src/main/java/net/sf/jabref/JabRefPreferences.java
src/main/java/net/sf/jabref/exporter/CustomExportList.java
src/main/java/net/sf/jabref/exporter/LatexFieldFormatter.java
src/main/java/net/sf/jabref/gui/BibtexFields.java
src/main/java/net/sf/jabref/gui/JabRefFrame.java
src/main/java/net/sf/jabref/gui/SidePaneManager.java
src/main/java/net/sf/jabref/gui/journals/ManageJournalsPanel.java
src/main/java/net/sf/jabref/gui/keyboard/KeyBindingPreferences.java
src/main/java/net/sf/jabref/gui/maintable/MainTable.java
src/main/java/net/sf/jabref/gui/maintable/MainTableFormat.java
src/main/java/net/sf/jabref/gui/maintable/PersistenceTableColumnListener.java
src/main/java/net/sf/jabref/gui/preftabs/NameFormatterTab.java
src/main/java/net/sf/jabref/gui/preftabs/TableColumnsTab.java
src/main/java/net/sf/jabref/gui/preftabs/XmpPrefsTab.java
src/main/java/net/sf/jabref/importer/CustomImportList.java
src/main/java/net/sf/jabref/importer/CustomImporter.java
src/main/java/net/sf/jabref/importer/fileformat/FieldContentParser.java
src/main/java/net/sf/jabref/logic/autocompleter/AutoCompletePreferences.java
src/main/java/net/sf/jabref/logic/autocompleter/ContentAutoCompleters.java
src/main/java/net/sf/jabref/logic/journals/Abbreviations.java
src/main/java/net/sf/jabref/logic/util/io/FileHistory.java
src/main/java/net/sf/jabref/logic/xmp/XMPSchemaBibtex.java
src/main/java/net/sf/jabref/logic/xmp/XMPUtil.java
src/test/java/net/sf/jabref/logic/util/io/FileHistoryTest.java
src/test/java/net/sf/jabref/util/UtilTest.java
src/test/java/net/sf/jabref/util/XMPUtilTest.java

Also fixed an NPE in the XMP metadata preference tab.

Replaced getStringArray and putStringArray with getStringList and putStringList in preferences

---

build.gradle

Updated versions for pdfbox, fontbox, and jempbox

---

src/main/java/net/sf/jabref/wizard/auximport/AuxCommandLine.java
src/main/java/net/sf/jabref/wizard/auximport/AuxSubGenerator.java
src/main/java/net/sf/jabref/wizard/auximport/gui/FromAuxDialog.java

Cleanup in aux import

---

src/main/java/net/sf/jabref/bibtex/comparator/CrossRefEntryComparator.java
src/main/java/net/sf/jabref/external/AttachFileAction.java
src/main/java/net/sf/jabref/external/DroppedFileHandler.java
src/main/java/net/sf/jabref/gui/BasePanel.java
src/main/java/net/sf/jabref/gui/EntryMarker.java
src/main/java/net/sf/jabref/gui/ImportInspectionDialog.java
src/main/java/net/sf/jabref/gui/ReplaceStringDialog.java
src/main/java/net/sf/jabref/gui/RightClickMenu.java
src/main/java/net/sf/jabref/gui/search/SearchResultsDialog.java
src/main/java/net/sf/jabref/logic/groups/GroupsUtil.java

Intermediate result as I'm changing computer...

More use of getFieldOptional

---

CHANGELOG.md
src/main/java/net/sf/jabref/JabRef.java
src/main/java/net/sf/jabref/JabRefCLI.java
src/main/java/net/sf/jabref/gui/actions/ErrorConsoleAction.java

Changed the order of the error console tabs.
Add CLI switch `--debug` which enables logging of debug messages (shown as `FINE`).

[WIP] Error console and debugging

---

CHANGELOG.md
src/main/java/net/sf/jabref/gui/JabRefFrame.java
src/main/java/net/sf/jabref/gui/OSXCompatibleToolbar.java
src/main/java/net/sf/jabref/gui/PreviewPanel.java
src/main/java/net/sf/jabref/gui/SidePaneComponent.java
src/main/java/net/sf/jabref/gui/StringDialog.java
src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java
src/main/java/net/sf/jabref/gui/help/HelpDialog.java
src/main/java/net/sf/jabref/gui/preftabs/NameFormatterTab.java
src/main/java/net/sf/jabref/gui/preftabs/TableColumnsTab.java
src/main/java/net/sf/jabref/gui/preftabs/XmpPrefsTab.java
src/main/java/net/sf/jabref/gui/search/SearchBar.java
src/main/java/net/sf/jabref/importer/fetcher/GeneralFetcher.java
src/main/java/net/sf/jabref/wizard/text/gui/TextInputDialog.java

integrated OSX compatible toolbar

Osx improvements

---

src/main/java/net/sf/jabref/gui/MergeDialog.java
src/main/java/net/sf/jabref/gui/PreviewPanel.java
src/main/java/net/sf/jabref/gui/maintable/MainTableSelectionListener.java
src/main/java/net/sf/jabref/gui/util/PositionWindow.java
src/main/java/net/sf/jabref/importer/ImportFormatReader.java
src/main/java/net/sf/jabref/importer/fetcher/OAI2Fetcher.java
src/main/java/net/sf/jabref/logic/l10n/EncodingControl.java
src/main/java/net/sf/jabref/logic/util/io/FileUtil.java
src/main/java/net/sf/jabref/model/database/BibDatabase.java
src/main/java/net/sf/jabref/openoffice/OOBibBase.java
src/test/java/net/sf/jabref/logic/l10n/LocalizationEntry.java
src/test/java/net/sf/jabref/logic/labelPattern/LabelPatternUtilTest.java

By accident some automatic reformatting of the code...

Get rid of some warnings (and therefore possible issues)

---

src/main/java/net/sf/jabref/exporter/ExportToClipboardAction.java
src/main/java/net/sf/jabref/exporter/SaveSession.java
src/main/java/net/sf/jabref/external/DownloadExternalFile.java
src/main/java/net/sf/jabref/external/DroppedFileHandler.java
src/main/java/net/sf/jabref/external/ExternalFilePanel.java
src/main/java/net/sf/jabref/external/MoveFileAction.java
src/main/java/net/sf/jabref/gui/GroupAddRemoveDialog.java
src/main/java/net/sf/jabref/gui/RightClickMenu.java
src/main/java/net/sf/jabref/gui/WrapLayout.java
src/main/java/net/sf/jabref/sql/exporter/DBExporter.java
src/main/java/net/sf/jabref/sql/exporter/PostgreSQLExporter.java
src/main/java/net/sf/jabref/sql/importer/DBImporter.java
src/main/java/net/sf/jabref/sql/importer/DbImportAction.java
src/main/java/net/sf/jabref/sql/importer/MySQLImporter.java
src/main/java/net/sf/jabref/sql/importer/PostgreSQLImporter.java

Not really required to have the ResultSet in the try-with, but to get rid of Eclipse warnings...

More cleanup and warning removals

---

src/main/java/net/sf/jabref/exporter/layout/format/Authors.java
src/test/java/net/sf/jabref/exporter/layout/format/AuthorsTest.java
src/test/java/net/sf/jabref/exporter/layout/format/FileLinkTest.java

Two more tests (took a while to understand Authors, so incomplete but at least something...).
I will merge as soon that I see the coverage and it is not to bad.

Tests of two layout formatters

---

src/main/java/net/sf/jabref/gui/JabRefFrame.java
src/main/resources/l10n/Menu_da.properties
src/main/resources/l10n/Menu_de.properties
src/main/resources/l10n/Menu_en.properties
src/main/resources/l10n/Menu_es.properties
src/main/resources/l10n/Menu_fa.properties
src/main/resources/l10n/Menu_fr.properties
src/main/resources/l10n/Menu_in.properties
src/main/resources/l10n/Menu_it.properties
src/main/resources/l10n/Menu_ja.properties
src/main/resources/l10n/Menu_nl.properties
src/main/resources/l10n/Menu_no.properties
src/main/resources/l10n/Menu_pt_BR.properties
src/main/resources/l10n/Menu_ru.properties
src/main/resources/l10n/Menu_tr.properties
src/main/resources/l10n/Menu_vi.properties
src/main/resources/l10n/Menu_zh.properties

Improved menu structure

---

src/main/java/net/sf/jabref/exporter/AutoSaveManager.java
src/main/java/net/sf/jabref/gui/EntryCustomizationDialog.java
src/main/java/net/sf/jabref/gui/JabRefFrame.java
src/main/java/net/sf/jabref/gui/WaitForSaveOperation.java
src/main/java/net/sf/jabref/gui/journals/ManageJournalsPanel.java
src/main/java/net/sf/jabref/openoffice/OpenOfficePanel.java

Seemed like a convenient method considering how often it was used.

Added method getBasePanelList() and used it

---

src/main/java/net/sf/jabref/specialfields/SpecialFieldValue.java

This should fix #751. Should be merged in without waiting for confirmation.

Fixed #751

---

src/main/java/net/sf/jabref/gui/JabRefFrame.java

Move edit custom entry types to bibtex menu as it is directly bibtex-related

---

src/main/java/net/sf/jabref/bst/VM.java
src/main/java/net/sf/jabref/exporter/layout/format/HTMLParagraphs.java
src/main/java/net/sf/jabref/external/RegExpFileSearch.java
src/main/java/net/sf/jabref/gui/FileListEntryEditor.java
src/main/java/net/sf/jabref/gui/desktop/JabRefDesktop.java
src/main/java/net/sf/jabref/gui/fieldeditors/JTextAreaWithHighlighting.java
src/main/java/net/sf/jabref/importer/HTMLConverter.java
src/main/java/net/sf/jabref/importer/fetcher/IEEEXploreFetcher.java
src/main/java/net/sf/jabref/importer/fetcher/MedlineFetcher.java
src/main/java/net/sf/jabref/importer/fetcher/ScienceDirectFetcher.java
src/main/java/net/sf/jabref/importer/fileformat/BibteXMLImporter.java
src/main/java/net/sf/jabref/importer/fileformat/EndnoteImporter.java
src/main/java/net/sf/jabref/importer/fileformat/InspecImporter.java
src/main/java/net/sf/jabref/importer/fileformat/MedlinePlainImporter.java
src/main/java/net/sf/jabref/importer/fileformat/PdfContentImporter.java
src/main/java/net/sf/jabref/importer/fileformat/RisImporter.java
src/main/java/net/sf/jabref/importer/fileformat/SilverPlatterImporter.java
src/main/java/net/sf/jabref/logic/formatter/bibtexfields/PageNumbersFormatter.java
src/main/java/net/sf/jabref/logic/formatter/bibtexfields/SuperscriptFormatter.java
src/main/java/net/sf/jabref/logic/labelPattern/LabelPatternUtil.java
src/main/java/net/sf/jabref/logic/mods/PageNumbers.java
src/main/java/net/sf/jabref/logic/msbib/MSBibEntry.java
src/main/java/net/sf/jabref/logic/util/io/FileFinder.java
src/main/java/net/sf/jabref/logic/util/strings/StringUtil.java
src/main/java/net/sf/jabref/openoffice/OOBibBase.java
src/main/java/net/sf/jabref/openoffice/OOBibStyle.java
src/main/java/net/sf/jabref/util/Util.java

Should not be worse than the previous solution...

Made all static regex patterns private static final fields

---

src/main/java/net/sf/jabref/bibtex/BibEntryWriter.java
src/main/java/net/sf/jabref/bibtex/EntryTypes.java
src/main/java/net/sf/jabref/exporter/FileActions.java
src/main/java/net/sf/jabref/gui/EntryCustomizationDialog.java
src/main/java/net/sf/jabref/gui/EntryTypeList.java
src/main/java/net/sf/jabref/gui/actions/NewEntryAction.java
src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java
src/main/java/net/sf/jabref/gui/maintable/MainTable.java
src/main/java/net/sf/jabref/gui/menus/ChangeEntryTypeMenu.java
src/main/java/net/sf/jabref/importer/CheckForNewEntryTypesAction.java
src/main/java/net/sf/jabref/logic/CustomEntryTypesManager.java
src/main/java/net/sf/jabref/logic/xmp/XMPSchemaBibtex.java
src/main/java/net/sf/jabref/model/DuplicateCheck.java
src/main/java/net/sf/jabref/model/entry/BibEntry.java
src/main/java/net/sf/jabref/model/entry/TypedBibEntry.java
src/main/java/net/sf/jabref/sql/importer/DBImporter.java
src/main/java/net/sf/jabref/wizard/text/gui/TextInputDialog.java
src/test/java/net/sf/jabref/bibtex/EntryTypesTestBibLatex.java
src/test/java/net/sf/jabref/bibtex/EntryTypesTestBibtex.java
src/test/java/net/sf/jabref/importer/fileformat/MedlinePlainImporterTest.java
src/test/java/net/sf/jabref/model/entry/TypedBibEntryTest.java

Fix #741 (and a lot of other null pointer exceptions). getType and getStandardType now return an optional instead of possible null values.

Fix NPE at saving does not reset save flag #741

---

CHANGELOG.md
src/main/java/net/sf/jabref/importer/fetcher/ISBNtoBibTeXFetcher.java
src/main/resources/l10n/JabRef_da.properties
src/main/resources/l10n/JabRef_de.properties
src/main/resources/l10n/JabRef_en.properties
src/main/resources/l10n/JabRef_es.properties
src/main/resources/l10n/JabRef_fa.properties
src/main/resources/l10n/JabRef_fr.properties
src/main/resources/l10n/JabRef_in.properties
src/main/resources/l10n/JabRef_it.properties
src/main/resources/l10n/JabRef_ja.properties
src/main/resources/l10n/JabRef_nl.properties
src/main/resources/l10n/JabRef_no.properties
src/main/resources/l10n/JabRef_pt_BR.properties
src/main/resources/l10n/JabRef_ru.properties
src/main/resources/l10n/JabRef_tr.properties
src/main/resources/l10n/JabRef_vi.properties
src/main/resources/l10n/JabRef_zh.properties

Finished the full Request, hope now all is correct.   #684

ISBN2Bibtex warning is now more clear when no entry is found 

---

src/main/java/net/sf/jabref/openoffice/CitationManager.java
src/main/java/net/sf/jabref/openoffice/NoDocumentException.java
src/main/java/net/sf/jabref/openoffice/OOBibBase.java
src/main/java/net/sf/jabref/openoffice/OOBibStyle.java
src/main/java/net/sf/jabref/openoffice/OOUtil.java
src/main/java/net/sf/jabref/openoffice/OpenOfficePanel.java
src/main/java/net/sf/jabref/openoffice/StyleSelectDialog.java

* Extracted strings
* More detailed exception handling
* Simplified/improved code
Note that there's a new file and one removed, but here it looks like it is edited and renamed...

More OpenOffice fixes

---

src/test/java/net/sf/jabref/logic/remote/RemoteTest.java
src/test/java/net/sf/jabref/logic/xmp/XMPSchemaBibtexTest.java
src/test/java/net/sf/jabref/logic/xmp/XMPUtilTest.java

Hopefully this gets rid of some Coverity warnings...

Warning removal in tests

---

src/main/java/net/sf/jabref/gui/BasePanel.java

Some fixes to (almost) enable delete and cut.

More List<BibEntry> instead of BibEntry[]

---

src/test/java/net/sf/jabref/exporter/BibDatabaseWriterTest.java

No high impact Coverity warnings...

Got rid of resource leak

---

src/main/java/net/sf/jabref/groups/structure/KeywordGroup.java
src/main/java/net/sf/jabref/groups/structure/SearchGroup.java
src/main/java/net/sf/jabref/logic/mods/MODSEntry.java
src/main/java/net/sf/jabref/logic/msbib/MSBibEntry.java
src/main/java/net/sf/jabref/logic/util/strings/StringUtil.java

Some minor duplicate removal

---

.gitignore
CHANGELOG.md
build.gradle
jabref.install4j

please check, whether the changes to install4j breaks anything for the windows build

fixed OSX install process

---

CHANGELOG.md
src/main/java/net/sf/jabref/exporter/layout/format/Ordinal.java
src/test/java/net/sf/jabref/exporter/layout/format/OrdinalTest.java

Motivated by http://tex.stackexchange.com/questions/292491/numerals-to-ordinals-in-jabref-jstyle-layout-file

Added Ordinal formatter

---

src/main/java/net/sf/jabref/wizard/auximport/AuxCommandLine.java
src/main/java/net/sf/jabref/wizard/auximport/AuxSubGenerator.java
src/main/java/net/sf/jabref/wizard/auximport/gui/FromAuxDialog.java
src/test/java/net/sf/jabref/wizard/auximport/AuxCommandLineTest.java
src/test/java/net/sf/jabref/wizard/auximport/AuxSubGeneratorTest.java
src/test/resources/net/sf/jabref/wizard/auximport/badpaper.aux
src/test/resources/net/sf/jabref/wizard/auximport/origin.bib
src/test/resources/net/sf/jabref/wizard/auximport/paper.aux
src/test/resources/net/sf/jabref/wizard/auximport/result.bib

Added a basic test for the AuxSubGenerator.

Added test for AuxSubGenerator

---

src/main/java/net/sf/jabref/JabRef.java
src/main/java/net/sf/jabref/bibtex/comparator/EntryComparator.java
src/main/java/net/sf/jabref/external/DownloadExternalFile.java
src/main/java/net/sf/jabref/gui/ContentSelectorDialog2.java
src/main/java/net/sf/jabref/gui/DatabasePropertiesDialog.java
src/main/java/net/sf/jabref/gui/GenFieldsCustomizer.java
src/main/java/net/sf/jabref/gui/JabRefFrame.java
src/main/java/net/sf/jabref/gui/MergeDialog.java
src/main/java/net/sf/jabref/gui/PreambleEditor.java
src/main/java/net/sf/jabref/gui/StringDialog.java
src/main/java/net/sf/jabref/gui/autocompleter/AutoCompleteSupport.java
src/main/java/net/sf/jabref/gui/autocompleter/ListAutoCompleteRenderer.java
src/main/java/net/sf/jabref/gui/preftabs/TableColumnsTab.java
src/main/java/net/sf/jabref/importer/ImportCustomizationDialog.java
src/main/java/net/sf/jabref/importer/ImportFormatReader.java
src/main/java/net/sf/jabref/importer/OpenDatabaseAction.java
src/main/java/net/sf/jabref/importer/ZipFileChooser.java
src/main/java/net/sf/jabref/importer/fileformat/BiblioscapeImporter.java
src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java
src/main/java/net/sf/jabref/importer/fileformat/RepecNepImporter.java
src/main/java/net/sf/jabref/logic/autocompleter/AbstractAutoCompleter.java
src/main/java/net/sf/jabref/logic/autocompleter/AutoCompleters.java
src/main/java/net/sf/jabref/logic/cleanup/DoiCleanup.java
src/main/java/net/sf/jabref/logic/cleanup/FieldFormatterCleanup.java
src/main/java/net/sf/jabref/logic/cleanup/RenamePdfCleanup.java
src/test/java/net/sf/jabref/importer/fileformat/OAI2ImportTest.java
src/test/java/net/sf/jabref/logic/xmp/XMPSchemaBibtexTest.java

Yet another bunch of code cleanups. Some logging, some use of high level methods, some refined exception catching.

Code cleanups

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

[GitHub has a new feature "Issue and Pull Request templates](https://github.com/blog/2111-issue-and-pull-request-templates) and we directly wanted to make use of it. Here is the first shot.

Initial github issue and PR templates

---

src/main/java/net/sf/jabref/gui/DuplicateSearch.java
src/main/java/net/sf/jabref/gui/SidePaneManager.java
src/test/java/net/sf/jabref/logic/fetcher/ACSTest.java
src/test/java/net/sf/jabref/logic/fetcher/ArXivTest.java
src/test/java/net/sf/jabref/logic/fetcher/DoiResolutionTest.java
src/test/java/net/sf/jabref/logic/fetcher/FindFullTextTest.java
src/test/java/net/sf/jabref/logic/fetcher/GoogleScholarTest.java
src/test/java/net/sf/jabref/logic/fetcher/ScienceDirectTest.java
src/test/java/net/sf/jabref/logic/fetcher/SpringerLinkTest.java
src/test/java/net/sf/jabref/logic/formatter/PageNumbersFormatterTest.java
src/test/java/net/sf/jabref/wizard/auximport/AuxCommandLineTest.java

Removed some more warnings

---

src/main/java/net/sf/jabref/exporter/ExportFileFilter.java
src/main/java/net/sf/jabref/exporter/SaveActions.java
src/main/java/net/sf/jabref/external/ExternalFileType.java
src/main/java/net/sf/jabref/importer/CustomImporter.java
src/main/java/net/sf/jabref/importer/ImportFileFilter.java
src/main/java/net/sf/jabref/importer/fileformat/ImportFormat.java
src/main/java/net/sf/jabref/logic/FieldChange.java
src/main/java/net/sf/jabref/logic/cleanup/FieldFormatterCleanup.java
src/main/java/net/sf/jabref/logic/config/SaveOrderConfig.java
src/main/java/net/sf/jabref/logic/journals/Abbreviation.java
src/main/java/net/sf/jabref/logic/net/ProxyPreferences.java
src/main/java/net/sf/jabref/model/entry/AuthorList.java
src/main/java/net/sf/jabref/model/entry/FileField.java
src/main/java/net/sf/jabref/openoffice/CitationManager.java
src/main/java/net/sf/jabref/openoffice/OOBibStyle.java
src/main/java/net/sf/jabref/wizard/text/gui/TextInputDialog.java
src/test/java/net/sf/jabref/logic/l10n/LocalizationEntry.java

Changed hashCode (and equals) to be more consistent and per recommendations.

More systematic hashCode and equals

---

src/main/java/net/sf/jabref/importer/fetcher/ACMPortalFetcher.java
src/main/java/net/sf/jabref/importer/fetcher/ADSFetcher.java
src/main/java/net/sf/jabref/importer/fetcher/BibsonomyScraper.java
src/main/java/net/sf/jabref/importer/fetcher/CiteSeerXFetcher.java
src/main/java/net/sf/jabref/importer/fetcher/CrossRef.java
src/main/java/net/sf/jabref/importer/fetcher/DBLPFetcher.java
src/main/java/net/sf/jabref/importer/fetcher/DBLPHelper.java
src/main/java/net/sf/jabref/importer/fetcher/DOItoBibTeXFetcher.java
src/main/java/net/sf/jabref/importer/fetcher/IEEEXploreFetcher.java
src/main/java/net/sf/jabref/importer/fetcher/INSPIREFetcher.java
src/main/java/net/sf/jabref/importer/fetcher/ISBNtoBibTeXFetcher.java
src/main/java/net/sf/jabref/importer/fetcher/MedlineFetcher.java
src/main/java/net/sf/jabref/importer/fetcher/SpringerFetcher.java
src/main/java/net/sf/jabref/importer/fileformat/BibTeXMLHandler.java
src/main/java/net/sf/jabref/importer/fileformat/BiblioscapeImporter.java
src/main/java/net/sf/jabref/importer/fileformat/BibteXMLImporter.java
src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java
src/main/java/net/sf/jabref/importer/fileformat/FreeCiteImporter.java
src/main/java/net/sf/jabref/importer/fileformat/JSONEntryParser.java
src/main/java/net/sf/jabref/importer/fileformat/OvidImporter.java
src/main/java/net/sf/jabref/wizard/text/gui/TextInputDialog.java

Cleanups in fetchers

---

src/main/java/net/sf/jabref/gui/FindUnlinkedFilesDialog.java
src/main/java/net/sf/jabref/gui/GenFieldsCustomizer.java
src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java
src/main/java/net/sf/jabref/gui/entryeditor/EntryEditorTab.java
src/main/java/net/sf/jabref/gui/fieldeditors/FileListEditor.java
src/main/java/net/sf/jabref/gui/journals/ManageJournalsPanel.java
src/main/java/net/sf/jabref/gui/preftabs/TableColumnsTab.java
src/main/java/net/sf/jabref/importer/EntryFromFileCreator.java
src/main/java/net/sf/jabref/importer/ImportCustomizationDialog.java
src/test/java/net/sf/jabref/gui/entryeditor/EntryEditorTest.java
src/test/java/net/sf/jabref/logic/util/io/FileHistoryTest.java

Added explicit scoping for some methods and fields

---

src/main/java/net/sf/jabref/collab/MetaDataChange.java
src/main/java/net/sf/jabref/gui/BasePanel.java
src/main/java/net/sf/jabref/gui/DuplicateResolverDialog.java
src/main/java/net/sf/jabref/gui/UrlDragDrop.java
src/main/java/net/sf/jabref/gui/keyboard/KeyBindingTable.java
src/main/java/net/sf/jabref/gui/preftabs/EntryEditorPrefsTab.java
src/main/java/net/sf/jabref/gui/preftabs/FileTab.java
src/main/java/net/sf/jabref/gui/preftabs/FontSelectorDialog.java
src/main/java/net/sf/jabref/gui/preftabs/NetworkTab.java
src/main/java/net/sf/jabref/gui/util/component/VerticalLabelUI.java
src/main/java/net/sf/jabref/importer/fetcher/DOAJFetcher.java
src/main/java/net/sf/jabref/importer/fileformat/BibTeXMLHandler.java
src/main/java/net/sf/jabref/importer/fileformat/MedlineHandler.java
src/main/java/net/sf/jabref/logic/autocompleter/NameFieldAutoCompleter.java
src/main/java/net/sf/jabref/logic/cleanup/DoiCleanup.java
src/main/java/net/sf/jabref/logic/fetcher/DoiResolution.java
src/main/java/net/sf/jabref/logic/formatter/casechanger/CaseKeeper.java
src/main/java/net/sf/jabref/logic/formatter/casechanger/CaseKeeperList.java
src/main/java/net/sf/jabref/logic/labelpattern/AbstractLabelPattern.java
src/main/java/net/sf/jabref/logic/layout/format/WrapFileLinks.java
src/main/java/net/sf/jabref/sql/DBConnectDialog.java
src/main/java/net/sf/jabref/sql/DBExporterAndImporterFactory.java
src/test/java/net/sf/jabref/logic/formatter/SuperscriptFormatterTest.java
src/test/java/net/sf/jabref/logic/formatter/bibtexfields/AuthorsFormatterTest.java
src/test/java/net/sf/jabref/logic/formatter/minifier/AuthorsMinifierTest.java
src/test/java/net/sf/jabref/logic/util/strings/StringUtilTest.java
src/test/java/net/sf/jabref/model/DuplicateCheckTest.java
src/test/java/net/sf/jabref/model/entry/BibtexEntryTests.java

Less Codacy issues

---

src/main/java/net/sf/jabref/JabRefPreferencesFilter.java
src/main/java/net/sf/jabref/collab/ChangeDisplayDialog.java
src/main/java/net/sf/jabref/gui/BasePanel.java
src/main/java/net/sf/jabref/gui/BibtexKeyPatternDialog.java
src/main/java/net/sf/jabref/gui/EntryMarker.java
src/main/java/net/sf/jabref/gui/ImportInspectionDialog.java
src/main/java/net/sf/jabref/gui/JabRefFrame.java
src/main/java/net/sf/jabref/gui/PreviewPanel.java
src/main/java/net/sf/jabref/gui/dbproperties/SaveActionsPanel.java
src/main/java/net/sf/jabref/gui/labelpattern/LabelPatternPanel.java
src/main/java/net/sf/jabref/gui/maintable/MainTable.java
src/main/java/net/sf/jabref/gui/menus/RightClickMenu.java
src/main/java/net/sf/jabref/gui/preftabs/NetworkTab.java
src/main/java/net/sf/jabref/gui/preftabs/TableColumnsTab.java
src/main/java/net/sf/jabref/gui/search/SearchBar.java
src/main/java/net/sf/jabref/importer/fetcher/ScienceDirectFetcher.java
src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java
src/main/java/net/sf/jabref/logic/labelpattern/GlobalLabelPattern.java
src/main/java/net/sf/jabref/logic/labelpattern/LabelPatternUtil.java
src/main/java/net/sf/jabref/logic/layout/format/RemoveLatexCommands.java
src/main/java/net/sf/jabref/logic/mods/MODSEntry.java
src/main/java/net/sf/jabref/model/entry/FileField.java
src/main/java/net/sf/jabref/openoffice/OOBibBase.java
src/main/java/net/sf/jabref/util/Util.java
src/main/java/net/sf/jabref/wizard/text/gui/TextInputDialog.java
src/test/java/net/sf/jabref/logic/labelpattern/LabelPatternUtilTest.java

Cleanup in LabelPatternUtil and quite a bit more

---

CHANGELOG.md
src/main/java/net/sf/jabref/gui/actions/CleanupAction.java

Fixed #883

---

src/main/java/net/sf/jabref/exporter/ExportToClipboardAction.java
src/main/java/net/sf/jabref/gui/MergeDialog.java
src/main/java/net/sf/jabref/gui/OpenFileFilter.java
src/main/java/net/sf/jabref/gui/autocompleter/AutoCompleteSupport.java
src/main/java/net/sf/jabref/gui/autocompleter/ListAutoCompleteRenderer.java
src/main/java/net/sf/jabref/gui/fieldeditors/contextmenu/FieldTextMenu.java
src/main/java/net/sf/jabref/importer/fetcher/SpringerFetcher.java
src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java
src/main/java/net/sf/jabref/importer/fileformat/FieldContentParser.java
src/main/java/net/sf/jabref/logic/autocompleter/AutoCompleters.java
src/main/java/net/sf/jabref/logic/autocompleter/ContentAutoCompleters.java
src/main/java/net/sf/jabref/logic/autocompleter/NameFieldAutoCompleter.java
src/main/java/net/sf/jabref/logic/layout/LayoutHelper.java
src/main/java/net/sf/jabref/logic/net/ProxyAuthenticator.java
src/main/java/net/sf/jabref/logic/util/io/FileUtil.java
src/main/java/net/sf/jabref/specialfields/SpecialField.java
src/main/java/net/sf/jabref/specialfields/SpecialFieldAction.java
src/main/java/net/sf/jabref/specialfields/SpecialFieldsUtils.java
src/test/java/net/sf/jabref/bibtex/comparator/BibtexStringComparatorTest.java
src/test/java/net/sf/jabref/importer/GeneralFetcherTest.java
src/test/java/net/sf/jabref/importer/fileformat/FieldContentParserTest.java
src/test/java/net/sf/jabref/logic/net/URLUtilTest.java
src/test/java/net/sf/jabref/logic/util/io/FileHistoryTest.java
src/test/java/net/sf/jabref/logic/util/strings/StringUtilTest.java

Some cleanups

---

src/main/java/net/sf/jabref/gui/ImportInspectionDialog.java
src/main/java/net/sf/jabref/gui/maintable/MainTableNameFormatter.java
src/main/java/net/sf/jabref/importer/fileformat/EndnoteImporter.java
src/main/java/net/sf/jabref/importer/fileformat/InspecImporter.java
src/main/java/net/sf/jabref/importer/fileformat/MedlinePlainImporter.java
src/main/java/net/sf/jabref/importer/fileformat/OvidImporter.java
src/main/java/net/sf/jabref/importer/fileformat/RisImporter.java
src/main/java/net/sf/jabref/importer/fileformat/SilverPlatterImporter.java
src/main/java/net/sf/jabref/logic/labelpattern/LabelPatternUtil.java
src/main/java/net/sf/jabref/logic/layout/format/AuthorFirstAbbrLastCommas.java
src/main/java/net/sf/jabref/logic/layout/format/AuthorFirstAbbrLastOxfordCommas.java
src/main/java/net/sf/jabref/logic/layout/format/AuthorFirstFirst.java
src/main/java/net/sf/jabref/logic/layout/format/AuthorFirstFirstCommas.java
src/main/java/net/sf/jabref/logic/layout/format/AuthorFirstLastCommas.java
src/main/java/net/sf/jabref/logic/layout/format/AuthorFirstLastOxfordCommas.java
src/main/java/net/sf/jabref/logic/layout/format/AuthorLastFirst.java
src/main/java/net/sf/jabref/logic/layout/format/AuthorLastFirstAbbrCommas.java
src/main/java/net/sf/jabref/logic/layout/format/AuthorLastFirstAbbrOxfordCommas.java
src/main/java/net/sf/jabref/logic/layout/format/AuthorLastFirstCommas.java
src/main/java/net/sf/jabref/logic/layout/format/AuthorLastFirstOxfordCommas.java
src/main/java/net/sf/jabref/logic/layout/format/AuthorNatBib.java
src/main/java/net/sf/jabref/logic/layout/format/CreateDocBookAuthors.java
src/main/java/net/sf/jabref/logic/layout/format/RisAuthors.java
src/main/java/net/sf/jabref/logic/mods/PersonName.java
src/main/java/net/sf/jabref/logic/util/strings/StringUtil.java
src/main/java/net/sf/jabref/model/DuplicateCheck.java
src/main/java/net/sf/jabref/model/entry/AuthorList.java
src/test/java/net/sf/jabref/model/entry/AuthorListTest.java

Cleanups of StringUtil and AuthorList

---

src/main/java/net/sf/jabref/importer/fetcher/DOAJFetcher.java
src/main/java/net/sf/jabref/importer/fetcher/SpringerFetcher.java
src/main/java/net/sf/jabref/importer/fileformat/JSONEntryParser.java
src/main/java/net/sf/jabref/model/DuplicateCheck.java
src/main/java/net/sf/jabref/openoffice/AdvancedCiteDialog.java
src/main/java/net/sf/jabref/openoffice/AutoDetectPaths.java
src/main/java/net/sf/jabref/openoffice/OOBibBase.java
src/main/java/net/sf/jabref/openoffice/OOBibStyle.java
src/main/java/net/sf/jabref/openoffice/OOPreFormatter.java
src/main/java/net/sf/jabref/openoffice/OpenOfficePanel.java
src/main/resources/resource/openoffice/default_authoryear.jstyle
src/main/resources/resource/openoffice/default_numerical.jstyle
src/test/java/net/sf/jabref/importer/fetcher/GVKParserTest.java
src/test/java/net/sf/jabref/importer/fileformat/JSONEntryParserTest.java
src/test/java/net/sf/jabref/logic/labelpattern/LabelPatternUtilTest.java
src/test/java/net/sf/jabref/logic/search/DatabaseSearcherTest.java
src/test/java/net/sf/jabref/model/entry/AuthorListTest.java
src/test/java/net/sf/jabref/model/entry/BibtexEntryTests.java
src/test/java/net/sf/jabref/openoffice/OOBibStyleTest.java

Removed Codacy warnings.
Added test for OOBibStyle.getNumCitationMarker

Fixed some issues and added some tests

---

src/main/java/net/sf/jabref/gui/search/SearchResultsDialog.java
src/main/java/net/sf/jabref/gui/search/SearchWorker.java
src/main/java/net/sf/jabref/logic/layout/Layout.java
src/main/java/net/sf/jabref/migrations/VersionHandling.java
src/main/java/net/sf/jabref/pdfimport/PdfImporter.java

Extracted methods from large switch, rewrote as switch and added default labels to switch.

Removed some switch warnings and restructured code

---

src/test/java/net/sf/jabref/openoffice/OOBibStyleTest.java

Testing of a few more methods in OOBibStyle.

More tests for OOBibStyle

---

src/main/java/net/sf/jabref/gui/autocompleter/AutoCompleteSupport.java
src/main/java/net/sf/jabref/gui/desktop/JabRefDesktop.java
src/main/java/net/sf/jabref/importer/fetcher/OAI2Fetcher.java
src/main/java/net/sf/jabref/logic/util/DOI.java
src/test/java/net/sf/jabref/importer/fileformat/EndnoteImporterTest.java
src/test/java/net/sf/jabref/importer/fileformat/RepecNepImporterTest.java

Removed some error level issues

---

CHANGELOG.md
src/main/java/net/sf/jabref/JabRefPreferences.java
src/main/java/net/sf/jabref/gui/preftabs/PreferencesDialog.java
src/main/resources/l10n/JabRef_da.properties
src/main/resources/l10n/JabRef_de.properties
src/main/resources/l10n/JabRef_en.properties
src/main/resources/l10n/JabRef_es.properties
src/main/resources/l10n/JabRef_fa.properties
src/main/resources/l10n/JabRef_fr.properties
src/main/resources/l10n/JabRef_in.properties
src/main/resources/l10n/JabRef_it.properties
src/main/resources/l10n/JabRef_ja.properties
src/main/resources/l10n/JabRef_nl.properties
src/main/resources/l10n/JabRef_no.properties
src/main/resources/l10n/JabRef_pt_BR.properties
src/main/resources/l10n/JabRef_ru.properties
src/main/resources/l10n/JabRef_tr.properties
src/main/resources/l10n/JabRef_vi.properties
src/main/resources/l10n/JabRef_zh.properties

Implements #455 and/or https://github.com/koppor/jabref/issues/47.

Add button in preference dialog to reset preferences

---

src/main/java/net/sf/jabref/importer/fileformat/PdfContentImporter.java
src/main/java/net/sf/jabref/pdfimport/PdfImporter.java
src/test/java/net/sf/jabref/importer/fileformat/PdfContentImporterTest.java
src/test/resources/net/sf/jabref/importer/fileformat/encrypted.pdf

I don't know if this sufficies the requirements, but for me it does not throw the strange exception.

Test for encrypted PDF does not throw an Exception

---

src/main/java/net/sf/jabref/importer/fetcher/INSPIREFetcher.java
src/main/java/net/sf/jabref/importer/fetcher/ISBNtoBibTeXFetcher.java
src/main/java/net/sf/jabref/importer/fetcher/OAI2Fetcher.java

Removed Translation of Fetcher names, because that are proper nouns.
#941

Removed "Fetch" in title from Database Fetchers 

---

.gitattributes

Will currently not work on GitHub, but will at least avoid manual conflict resolving when sorting out the GitHub conflict.
(Opened a PR in case someone has any objections...)

Added union merge for translation files.

---

src/main/java/net/sf/jabref/external/ExternalFileType.java
src/main/java/net/sf/jabref/external/MoveFileAction.java
src/main/java/net/sf/jabref/external/SynchronizeFileField.java
src/main/java/net/sf/jabref/groups/EntryTableTransferHandler.java
src/main/java/net/sf/jabref/gui/preftabs/TablePrefsTab.java
src/main/java/net/sf/jabref/importer/EntryFromPDFCreator.java
src/main/java/net/sf/jabref/importer/fetcher/OAI2Fetcher.java
src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java
src/main/java/net/sf/jabref/logic/cleanup/CleanupPreset.java
src/main/java/net/sf/jabref/logic/labelpattern/LabelPatternUtil.java
src/main/java/net/sf/jabref/logic/msbib/MSBibEntry.java
src/main/java/net/sf/jabref/pdfimport/PdfImporter.java
src/test/java/net/sf/jabref/logic/labelpattern/LabelPatternUtilTest.java

Small change of behaviour in LabelPatternUtil.
However, I think that the previous code didn't even work... How can e.g.`"univ".equalsIgnoreCase(k.substring(0, 5))` ever evaluate to true? The substring is five characters, right? This is something for static code checkers to find...

Some more fixes

---

src/main/java/net/sf/jabref/JabRef.java
src/main/java/net/sf/jabref/JabRefCLI.java
src/main/java/net/sf/jabref/JabRefExecutorService.java
src/main/java/net/sf/jabref/gui/undo/UndoableInsertEntry.java
src/main/java/net/sf/jabref/gui/undo/UndoableInsertString.java
src/main/java/net/sf/jabref/gui/undo/UndoableRemoveEntry.java
src/main/java/net/sf/jabref/gui/undo/UndoableRemoveString.java
src/main/java/net/sf/jabref/gui/worker/MarkEntriesAction.java
src/main/java/net/sf/jabref/importer/fetcher/JSTORFetcher2.java

The last printStackTrace() are replaced with loggers. (Except one in a test.)

No more printStackTrace()

---

src/main/java/net/sf/jabref/openoffice/OOBibBase.java
src/main/java/net/sf/jabref/openoffice/OOUtil.java

Replaced Bitset with EnumSet in OOUtil

---

src/main/java/net/sf/jabref/BibDatabaseContext.java
src/main/java/net/sf/jabref/JabRef.java
src/main/java/net/sf/jabref/MetaData.java
src/main/java/net/sf/jabref/bibtex/comparator/EntryComparator.java
src/main/java/net/sf/jabref/exporter/BibDatabaseWriter.java
src/main/java/net/sf/jabref/exporter/SaveDatabaseAction.java
src/main/java/net/sf/jabref/external/push/PushToApplications.java
src/main/java/net/sf/jabref/gui/BasePanel.java
src/main/java/net/sf/jabref/gui/CleanupPresetPanel.java
src/main/java/net/sf/jabref/gui/ImportInspectionDialog.java
src/main/java/net/sf/jabref/gui/JabRefFrame.java
src/main/java/net/sf/jabref/gui/actions/SortTabsAction.java
src/main/java/net/sf/jabref/gui/entryeditor/SimpleUrlDragDrop.java
src/main/java/net/sf/jabref/gui/maintable/MainTableSelectionListener.java
src/main/java/net/sf/jabref/gui/mergeentries/MergeEntries.java
src/main/java/net/sf/jabref/gui/preftabs/EntryEditorPrefsTab.java
src/main/java/net/sf/jabref/gui/preftabs/ExternalTab.java
src/main/java/net/sf/jabref/gui/preftabs/PreferencesDialog.java
src/main/java/net/sf/jabref/gui/search/SearchResultsDialog.java
src/main/java/net/sf/jabref/importer/EntryFromPDFCreator.java
src/main/java/net/sf/jabref/importer/fetcher/OAI2Fetcher.java
src/main/java/net/sf/jabref/logic/search/SearchQuery.java
src/test/java/net/sf/jabref/logic/fetcher/DoiResolutionTest.java

* Removed unused imports
* Some code style fixes
* Most likely fixed a potential NPE in SaveDataBaseAction (chosenFile will never be null here, but f might be and is later dereferenced)

Some random cleanups (and probably a bug-fix)

---

src/main/java/net/sf/jabref/JabRef.java
src/main/java/net/sf/jabref/bibtex/comparator/FieldComparator.java
src/main/java/net/sf/jabref/external/RegExpFileSearch.java
src/main/java/net/sf/jabref/groups/EntryTableTransferHandler.java
src/main/java/net/sf/jabref/gui/desktop/os/Windows.java
src/main/java/net/sf/jabref/gui/worker/MarkEntriesAction.java
src/main/java/net/sf/jabref/importer/fetcher/ACMPortalFetcher.java
src/main/java/net/sf/jabref/importer/fetcher/GoogleScholarFetcher.java
src/main/java/net/sf/jabref/importer/fetcher/IEEEXploreFetcher.java
src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java
src/main/java/net/sf/jabref/logic/formatter/casechanger/Word.java
src/main/java/net/sf/jabref/logic/layout/format/XMLChars.java
src/test/java/net/sf/jabref/importer/fileformat/FieldContentParserTest.java
src/test/java/net/sf/jabref/logic/layout/LayoutEntryTest.java
src/test/java/net/sf/jabref/logic/layout/LayoutTest.java

replace is faster, so if no regular expression is needed it is better to use that.
There are a few more places where it can be replaced, but I got confused when it came to escaping...

Replaced replaceAll with replace

---

src/main/java/net/sf/jabref/JabRef.java
src/main/java/net/sf/jabref/exporter/SaveSession.java
src/main/java/net/sf/jabref/gui/BasePanel.java
src/main/java/net/sf/jabref/gui/GUIGlobals.java
src/main/java/net/sf/jabref/gui/JabRefFrame.java
src/main/java/net/sf/jabref/gui/PreambleEditor.java
src/main/java/net/sf/jabref/gui/StringDialog.java
src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java
src/main/java/net/sf/jabref/gui/fieldeditors/FieldNameLabel.java
src/main/java/net/sf/jabref/gui/fieldeditors/TextArea.java
src/main/java/net/sf/jabref/gui/fieldeditors/TextField.java
src/main/java/net/sf/jabref/gui/maintable/MainTable.java
src/main/java/net/sf/jabref/gui/preftabs/AppearancePrefsTab.java

There were a few unused constants in GUIGlobals and a few which shouldn't be there.

Reworked and checked the constants in GUIGlobals

---

src/main/java/net/sf/jabref/gui/BasePanel.java
src/main/java/net/sf/jabref/gui/BasePanelMode.java
src/main/java/net/sf/jabref/gui/DuplicateResolverDialog.java
src/main/java/net/sf/jabref/gui/DuplicateSearch.java
src/main/java/net/sf/jabref/gui/ImportInspectionDialog.java
src/main/java/net/sf/jabref/gui/maintable/MainTable.java
src/main/java/net/sf/jabref/gui/maintable/MainTableSelectionListener.java
src/main/java/net/sf/jabref/pdfimport/PdfImporter.java

Used enums instead of explicit ints for the mode of BasePanel, how to render cells in MainTable, and mode and result for DuplicateResolverDialog.

Added enums

---

src/main/java/net/sf/jabref/gui/JabRefFrame.java
src/main/resources/l10n/JabRef_da.properties
src/main/resources/l10n/JabRef_de.properties
src/main/resources/l10n/JabRef_en.properties
src/main/resources/l10n/JabRef_es.properties
src/main/resources/l10n/JabRef_fa.properties
src/main/resources/l10n/JabRef_fr.properties
src/main/resources/l10n/JabRef_in.properties
src/main/resources/l10n/JabRef_it.properties
src/main/resources/l10n/JabRef_ja.properties
src/main/resources/l10n/JabRef_nl.properties
src/main/resources/l10n/JabRef_no.properties
src/main/resources/l10n/JabRef_pt_BR.properties
src/main/resources/l10n/JabRef_ru.properties
src/main/resources/l10n/JabRef_tr.properties
src/main/resources/l10n/JabRef_vi.properties
src/main/resources/l10n/JabRef_zh.properties

Shows the new font size in the status bar after changing it with increase/decrease table font size.

Added info about current font size when changing it using key bindings

---

src/main/java/net/sf/jabref/external/RegExpFileSearch.java
src/main/java/net/sf/jabref/groups/EntryTableTransferHandler.java
src/main/java/net/sf/jabref/gui/OpenFileFilter.java
src/main/java/net/sf/jabref/importer/EntryFromFileCreator.java
src/main/java/net/sf/jabref/importer/EntryFromFileCreatorManager.java
src/main/java/net/sf/jabref/importer/EntryFromPDFCreator.java
src/main/java/net/sf/jabref/importer/ImportFormatReader.java
src/main/java/net/sf/jabref/openoffice/CitationManager.java
src/main/java/net/sf/jabref/openoffice/OOBibBase.java
src/main/java/net/sf/jabref/pdfimport/PdfImporter.java
src/test/java/net/sf/jabref/importer/EntryFromPDFCreatorTest.java
src/test/java/net/sf/jabref/openoffice/CitationManagerTest.java

* Replaced null return values with Optional (and emptyList())
* Added test for openoffice.CitationManager.CitEntry
* Removed unused method

Got rid of some null return values and added a small test

---

src/main/java/net/sf/jabref/openoffice/OOBibStyle.java

Replaced integers with enum

---

src/main/java/net/sf/jabref/openoffice/OOBibStyle.java
src/main/resources/resource/openoffice/default_authoryear.jstyle
src/main/resources/resource/openoffice/default_numerical.jstyle
src/test/java/net/sf/jabref/openoffice/OOBibStyleTest.java

More testing leading to more understanding and a few fixes. (And, no, the tests are maybe not the most elegant, but it was more a matter of figuring out how the code behaves in certain situations and try to trigger as many situations as possible...).

Added more testing to OOBibStyle and fixed a few issues

---

src/main/java/net/sf/jabref/importer/OpenDatabaseAction.java

Will merge this in as soon as the build passes.

Fix NPE on database load in SpecialFieldSync

---

src/main/java/net/sf/jabref/specialfields/SpecialFieldUpdateListener.java

Will merge this in as soon as the build passes.

Fixed another NPE due to missing named compound for sync special fields

---

CHANGELOG.md
src/main/java/net/sf/jabref/gui/mergeentries/MergeEntryDOIDialog.java
src/main/java/net/sf/jabref/gui/undo/UndoableChangeType.java

Fix #1062 Merge entry with DOI information now also applies changes to entry type

---

src/main/java/net/sf/jabref/sql/exporter/DBExporter.java

Followup from #1056. I noticed that all entries where inserted multiple times in the entry table.
Moved processQuery out of the loops.
From what I remember 3.2 Export was working correct.

Fix wrong SQL db-export (same entry multiple times)

---

src/main/java/net/sf/jabref/Globals.java
src/main/java/net/sf/jabref/JabRef.java
src/main/java/net/sf/jabref/JabRefCLI.java
src/main/java/net/sf/jabref/exporter/BibDatabaseWriter.java
src/main/java/net/sf/jabref/gui/PreviewPanel.java
src/main/java/net/sf/jabref/gui/preftabs/AdvancedTab.java
src/main/java/net/sf/jabref/importer/DatabaseFileLookup.java
src/main/java/net/sf/jabref/importer/ImportCustomizationDialog.java
src/main/java/net/sf/jabref/importer/ImportFormats.java
src/main/java/net/sf/jabref/importer/ImportMenuItem.java
src/main/java/net/sf/jabref/importer/OpenDatabaseAction.java
src/main/java/net/sf/jabref/importer/fileformat/FreeCiteImporter.java
src/main/java/net/sf/jabref/model/entry/CustomEntryType.java
src/test/java/net/sf/jabref/bibtex/EntryTypesTestBibLatex.java
src/test/java/net/sf/jabref/bibtex/EntryTypesTestBibtex.java
src/test/java/net/sf/jabref/model/entry/AuthorListParameterTest.java

Bugfix in FreeCiteImporter, some naming cleanups, primarily in Globals, and some unused imports.

Minor cleanups and a bug fix

---

src/main/java/net/sf/jabref/JabRefPreferences.java

Changed preview font from Arial to Sans-Serif family

---

CHANGELOG.md
src/main/java/net/sf/jabref/logic/fetcher/FindFullText.java
src/main/java/net/sf/jabref/logic/fetcher/IEEE.java
src/test/java/net/sf/jabref/logic/fetcher/IEEETest.java

PDFs can now be automatically downloaded from IEEE Xplore, given that you have IP-based access (if not, nothing should happen).

Added IEEE PDF fetcher

---

src/main/java/net/sf/jabref/bibtex/BibEntryWriter.java

With the recent changes in the writter the `hasWritten` field is no longer required.

Remove hasWritten field in BibEntryWriter

---

src/test/java/net/sf/jabref/exporter/BibDatabaseWriterTest.java
src/test/java/net/sf/jabref/importer/fileformat/BibtexImporterTest.java
src/test/java/net/sf/jabref/importer/fileformat/BibtexParserTest.java

Fixed encoding problem in Test when running gradle check
Follow up from #1014 
@tobiasdiez

Improded readability of some BibTex Test Strings

---

src/main/java/net/sf/jabref/gui/PreambleEditor.java
src/main/java/net/sf/jabref/gui/StringDialog.java
src/main/java/net/sf/jabref/gui/keyboard/KeyBindingPreferences.java
src/main/java/net/sf/jabref/importer/fetcher/CiteSeerXFetcher.java
src/main/java/net/sf/jabref/importer/fetcher/GoogleScholarFetcher.java
src/main/java/net/sf/jabref/importer/fetcher/JSTORFetcher.java
src/main/java/net/sf/jabref/importer/fetcher/JSTORFetcher2.java
src/main/java/net/sf/jabref/importer/fetcher/ScienceDirectFetcher.java

Fewer thrown RunTimeExceptions and fewer caught Throwables.

Sorted out some exceptions

---

src/main/resources/l10n/JabRef_fr.properties

French localization: translation of an empty string

---

src/main/java/net/sf/jabref/JabRef.java
src/main/java/net/sf/jabref/gui/GUIGlobals.java
src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java

Removed the unused zoomLevel and moved typeNameFont.

Removed some variables from GUIGlobals

---

CHANGELOG.md
src/main/java/net/sf/jabref/gui/preftabs/ExternalTab.java
src/main/java/net/sf/jabref/gui/preftabs/FileTab.java

Move PDF file directory configuration from external tab to file tab in preferences

---

CHANGELOG.md
src/main/java/net/sf/jabref/gui/preftabs/AdvancedTab.java
src/main/java/net/sf/jabref/gui/preftabs/AppearancePrefsTab.java
src/main/java/net/sf/jabref/gui/preftabs/PrefsTab.java

Move L&F configuration from advanced to appearance tab in preferences

---

src/main/java/net/sf/jabref/gui/autocompleter/AutoCompleteListener.java

Fix #644 Only suggest auto completion at the end of a word

---

src/main/java/net/sf/jabref/importer/ImportFormatReader.java
src/main/java/net/sf/jabref/importer/fetcher/GVKParser.java
src/main/java/net/sf/jabref/importer/fileformat/MedlineHandler.java
src/main/java/net/sf/jabref/logic/util/strings/StringUtil.java
src/test/java/net/sf/jabref/importer/ImportFormatReaderTest.java
src/test/java/net/sf/jabref/importer/ImportFormatReaderTestParameterless.java

Added initial tests for ImportFormatReader. Now, seven different formats are imported without specifying the format and the number of imported entries is checked. Should avoid bugs like #1134.
I also removed unused methods and moved a totally unrelated method to a better home.

ImportFormatReader test

---

src/main/java/net/sf/jabref/logic/util/strings/StringUtil.java
src/test/java/net/sf/jabref/logic/util/strings/StringUtilTest.java

Added support for names with - and A.A.
(Could be parameterized but then a new file is required etc... and didn't have time for that right now...)

Added test for StringUtil.expandAuthorInitials 

---

src/main/resources/l10n/Menu_tr.properties

Translated the single most recent entry to Turkish

Updated Menu_tr.properties

---

src/main/resources/l10n/JabRef_tr.properties

Translated the last single entry to Turkish.

Updated jabref_tr.properties

---

src/main/resources/l10n/Menu_fa.properties

Farsi localization: translation of empty strings by Behrouz javanmardi

---

src/main/java/net/sf/jabref/gui/DuplicateResolverDialog.java
src/main/java/net/sf/jabref/gui/JabRefFrame.java
src/main/java/net/sf/jabref/gui/PreambleEditor.java
src/main/java/net/sf/jabref/gui/StringDialog.java
src/main/java/net/sf/jabref/gui/mergeentries/MergeEntriesDialog.java
src/main/java/net/sf/jabref/gui/mergeentries/MergeEntryDOIDialog.java
src/main/java/net/sf/jabref/gui/openoffice/StyleSelectDialog.java
src/main/java/net/sf/jabref/gui/util/PositionWindow.java

Instead of always having to copy and paste the same code, the ComponentAdapter is now automatically installed.

PositionWindow automatically installs resize event listener

---

.travis.yml
README.md
build.gradle
circle.yml
scripts/prepare-install4j.sh

- Implements #1164 
- Removes coverity (which is no longer being used) in favor of codacy
- Coveralls is removed in favor of codecov due to quicker check

Testing is done at travis-ci, packaging on circleci

---

src/test/java/net/sf/jabref/importer/ImportDataTest.java
src/test/java/net/sf/jabref/importer/ImportFormatReaderTest.java

Fixes problem with failing tests due to whitespaces

Use Paths.get() instead of Url.getfile() - Fix failing tests

---

src/main/resources/l10n/Menu_in.properties

Menu: Update of Indonesian localization (by Josua R. Enslin)

---

src/main/resources/l10n/JabRef_in.properties

Messages: Update of Indonesian localization (by Josua R. Enslin)

---

src/main/resources/l10n/Menu_in.properties

Menu: (another) update of Indonesian localization (by Josua R. Enslin)

---

src/main/resources/l10n/Menu_ru.properties

With this PR, Menus are fully translated into Russian

Menu: Update of Russian localization (by Victor)

---

src/main/resources/l10n/Menu_da.properties

All items are now translated in the menus

Menu: Update of Danish localization (by Rohde Fischer)

---

src/main/java/net/sf/jabref/bibtex/BibEntryWriter.java
src/main/java/net/sf/jabref/exporter/BibDatabaseWriter.java
src/main/java/net/sf/jabref/importer/ImportFormatReader.java
src/main/java/net/sf/jabref/logic/util/strings/StringUtil.java
src/test/java/net/sf/jabref/logic/util/strings/StringUtilTest.java

Used in a number of places so makes sense to have a method.

Added method to generate string with n spaces or n characters

---

CHANGELOG.md
src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java
src/main/java/net/sf/jabref/gui/entryeditor/FieldExtraComponents.java
src/main/java/net/sf/jabref/importer/fetcher/CrossRef.java
src/main/resources/l10n/JabRef_da.properties
src/main/resources/l10n/JabRef_de.properties
src/main/resources/l10n/JabRef_en.properties
src/main/resources/l10n/JabRef_es.properties
src/main/resources/l10n/JabRef_fa.properties
src/main/resources/l10n/JabRef_fr.properties
src/main/resources/l10n/JabRef_in.properties
src/main/resources/l10n/JabRef_it.properties
src/main/resources/l10n/JabRef_ja.properties
src/main/resources/l10n/JabRef_nl.properties
src/main/resources/l10n/JabRef_no.properties
src/main/resources/l10n/JabRef_pt_BR.properties
src/main/resources/l10n/JabRef_ru.properties
src/main/resources/l10n/JabRef_sv.properties
src/main/resources/l10n/JabRef_tr.properties
src/main/resources/l10n/JabRef_vi.properties
src/main/resources/l10n/JabRef_zh.properties

 Add possibility to lookup DOI from BibTeX entry content

---

src/main/resources/l10n/Menu_nl.properties

Menu: Update of Dutch localization (by Pascaline (LearningTrain))

---

src/main/java/net/sf/jabref/JabRef.java
src/main/java/net/sf/jabref/JabRefPreferences.java
src/main/java/net/sf/jabref/exporter/ExportFormats.java
src/main/java/net/sf/jabref/exporter/ExportToClipboardAction.java
src/main/java/net/sf/jabref/external/AttachFileAction.java
src/main/java/net/sf/jabref/external/ConfirmCloseFileListEntryEditor.java
src/main/java/net/sf/jabref/external/DownloadExternalFile.java
src/main/java/net/sf/jabref/external/push/AbstractPushToApplication.java
src/main/java/net/sf/jabref/external/push/PushToApplicationAction.java
src/main/java/net/sf/jabref/external/push/PushToApplicationButton.java
src/main/java/net/sf/jabref/external/push/PushToEmacs.java
src/main/java/net/sf/jabref/external/push/PushToLyx.java
src/main/java/net/sf/jabref/external/push/PushToVim.java
src/main/java/net/sf/jabref/gui/BasePanel.java
src/main/java/net/sf/jabref/gui/openoffice/AutoDetectPaths.java
src/main/java/net/sf/jabref/gui/preftabs/AdvancedTab.java
src/main/java/net/sf/jabref/logic/cleanup/CleanupJob.java
src/main/java/net/sf/jabref/logic/layout/format/FileLink.java
src/main/java/net/sf/jabref/logic/layout/format/WrapFileLinks.java
src/main/java/net/sf/jabref/logic/openoffice/OpenOfficeFileSearch.java
src/main/java/net/sf/jabref/model/entry/Author.java

A little bit of everything... Maybe one should wait until after 3.3 is released before merging this?

Some minor cleanups

---

src/main/java/net/sf/jabref/gui/ContentSelectorDialog2.java
src/main/java/net/sf/jabref/gui/ImportInspectionDialog.java
src/main/java/net/sf/jabref/gui/actions/ManageKeywordsAction.java

Extracted some code to methods.

Refactored some dialogs

---

src/main/java/net/sf/jabref/gui/groups/AutoGroupDialog.java
src/main/java/net/sf/jabref/gui/groups/GroupAddRemoveDialog.java
src/main/java/net/sf/jabref/gui/groups/GroupSelector.java
src/main/java/net/sf/jabref/gui/groups/GroupTreeNodeViewModel.java
src/main/java/net/sf/jabref/gui/groups/UndoableAddOrRemoveGroup.java
src/main/java/net/sf/jabref/gui/groups/UndoableMoveGroup.java
src/test/java/net/sf/jabref/logic/groups/GroupsUtilTest.java

Removed some unused fields and parameters

---

src/main/java/net/sf/jabref/BibDatabaseContext.java
src/main/java/net/sf/jabref/Globals.java
src/main/java/net/sf/jabref/JabRefPreferences.java
src/main/java/net/sf/jabref/MetaData.java
src/main/java/net/sf/jabref/exporter/BibDatabaseWriter.java
src/main/java/net/sf/jabref/exporter/SaveDatabaseAction.java
src/main/java/net/sf/jabref/gui/ContentSelectorDialog2.java
src/main/java/net/sf/jabref/gui/FieldContentSelector.java
src/main/java/net/sf/jabref/gui/cleanup/FieldFormatterCleanupsPanel.java
src/main/java/net/sf/jabref/gui/dbproperties/DatabasePropertiesDialog.java
src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java
src/main/java/net/sf/jabref/gui/entryeditor/FieldExtraComponents.java
src/main/java/net/sf/jabref/importer/AppendDatabaseAction.java
src/main/java/net/sf/jabref/logic/autocompleter/ContentAutoCompleters.java
src/test/java/net/sf/jabref/importer/fileformat/BibtexParserTest.java
src/test/java/net/sf/jabref/logic/integrity/IntegrityCheckTest.java

Also removed support of legacy user-specific file paths (serialized with a @ symbol). JabRef stopped writing this format over 3 years ago (according to https://sourceforge.net/p/jabref/bugs/1153/).

Replace general get/put/remove metadata calls with typed versions

---

src/main/java/net/sf/jabref/gui/ImportInspectionDialog.java
src/main/java/net/sf/jabref/importer/ImportInspectionCommandLine.java
src/main/java/net/sf/jabref/importer/ImportInspector.java
src/main/java/net/sf/jabref/importer/fileformat/PdfContentImporter.java

Remove some unused code in ImportInspector

---

src/main/java/net/sf/jabref/model/entry/BibEntry.java

- remove obsolete settings of "changed" variable
- remove empty line
- use formatting rules for additional brackets in conditions

Minor BibEntry tweaks

---

src/main/java/net/sf/jabref/gui/JabRefFrame.java
src/main/java/net/sf/jabref/gui/actions/SortTabsAction.java

- Selected tab might be null when sorting tabs
- The logic is really strange in general, so this fixes the problem but we need to rework the actions enabling in general imho.

Fix #1295 NPE when sorting tabs

---

CHANGELOG.md
src/main/java/net/sf/jabref/Globals.java
src/main/java/net/sf/jabref/external/ExternalFileTypeEntryEditor.java
src/main/java/net/sf/jabref/gui/FileDialogs.java
src/main/java/net/sf/jabref/gui/FileListEntryEditor.java
src/main/java/net/sf/jabref/gui/actions/BrowseAction.java
src/main/java/net/sf/jabref/gui/journals/ManageJournalsPanel.java
src/main/java/net/sf/jabref/gui/openoffice/StyleSelectDialog.java
src/main/java/net/sf/jabref/logic/openoffice/StyleLoader.java

Filter filter for jstyle files #1294 
Extended BrowseAction to display file filter
Fixed NPE when selecting invalid jstyle (prevented style dialog from opening)
- [X ] Change in CHANGELOG.md described

Implemented Jstyle file filter and opening in last dir

---

CHANGELOG.md
src/main/java/net/sf/jabref/logic/integrity/ISSNChecker.java
src/main/java/net/sf/jabref/logic/integrity/IntegrityCheck.java
src/main/resources/l10n/JabRef_da.properties
src/main/resources/l10n/JabRef_de.properties
src/main/resources/l10n/JabRef_en.properties
src/main/resources/l10n/JabRef_es.properties
src/main/resources/l10n/JabRef_fa.properties
src/main/resources/l10n/JabRef_fr.properties
src/main/resources/l10n/JabRef_in.properties
src/main/resources/l10n/JabRef_it.properties
src/main/resources/l10n/JabRef_ja.properties
src/main/resources/l10n/JabRef_nl.properties
src/main/resources/l10n/JabRef_no.properties
src/main/resources/l10n/JabRef_pt_BR.properties
src/main/resources/l10n/JabRef_ru.properties
src/main/resources/l10n/JabRef_sv.properties
src/main/resources/l10n/JabRef_tr.properties
src/main/resources/l10n/JabRef_vi.properties
src/main/resources/l10n/JabRef_zh.properties
src/test/java/net/sf/jabref/logic/integrity/IntegrityCheckTest.java

Detects both that the content looks like an ISSN number and that the ISSN number is valid based on the control digit.

Added ISSN integrity checker

---

CONTRIBUTING.md
src/test/java/net/sf/jabref/logic/l10n/LocalizationConsistencyTest.java

Corrected gradlew task name
#1312 
@koppor  @stefan-kolb

Update Localization instructions

---

src/main/java/net/sf/jabref/external/push/PushToLyx.java
src/main/java/net/sf/jabref/gui/DragDropPane.java
src/main/java/net/sf/jabref/gui/groups/GroupAddRemoveDialog.java
src/main/java/net/sf/jabref/model/database/EntrySorter.java
src/main/java/net/sf/jabref/model/entry/BibEntry.java
src/main/java/net/sf/jabref/model/entry/BibtexString.java
src/main/java/net/sf/jabref/sql/DatabaseUtil.java
src/main/java/net/sf/jabref/sql/exporter/DatabaseExporter.java
src/test/java/net/sf/jabref/logic/groups/TreeNodeTest.java

- [X ] Changes in pull request outlined? (What, why, ...)
Used Lambdas for ActionListener
Fixed resource Leak in DB Exporter Methods

Fixes coverity issues, suppress Serialization issues

---

src/main/java/net/sf/jabref/logic/formatter/bibtexfields/NormalizePagesFormatter.java
src/test/java/net/sf/jabref/logic/formatter/bibtexfields/NormalizePagesFormatterTest.java

Normalize page cleanup also replaces em dash

---

CHANGELOG.md
jabref.install4j

Use LOCALADDATA (users/name/appdata/local/) as default installation directory instead of user home dir.

Win install

---

CHANGELOG.md
src/main/java/net/sf/jabref/gui/JabRefFrame.java
src/main/java/net/sf/jabref/gui/actions/Actions.java
src/main/java/net/sf/jabref/gui/actions/IntegrityCheckAction.java
src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java
src/main/resources/l10n/JabRef_da.properties
src/main/resources/l10n/JabRef_de.properties
src/main/resources/l10n/JabRef_en.properties
src/main/resources/l10n/JabRef_es.properties
src/main/resources/l10n/JabRef_fa.properties
src/main/resources/l10n/JabRef_fr.properties
src/main/resources/l10n/JabRef_in.properties
src/main/resources/l10n/JabRef_it.properties
src/main/resources/l10n/JabRef_ja.properties
src/main/resources/l10n/JabRef_nl.properties
src/main/resources/l10n/JabRef_no.properties
src/main/resources/l10n/JabRef_pt_BR.properties
src/main/resources/l10n/JabRef_ru.properties
src/main/resources/l10n/JabRef_sv.properties
src/main/resources/l10n/JabRef_tr.properties
src/main/resources/l10n/JabRef_vi.properties
src/main/resources/l10n/JabRef_zh.properties

* Table can be sorted
* Editing disabled
* Resize properly if a different menu font size is used
* Extracted to its own class
Also made writing of "BibTeX key" consistent.

Improved integrity check dialog

---

CHANGELOG.md
jabref.install4j

Add registry entries for installation path

---

src/main/java/net/sf/jabref/gui/PreviewPanel.java

Register listener for correct entry

---

codecov.yml

This should disable the PR comments of codecov...

Update codecov.yml to disable PR comments

---

src/integrationTest/java/net/sf/jabref/gui/UndoTest.java

related: #947 
After noticing that the integration test sometimes cannot find the entryTable ~~I open a new empty database to load the table beforehand. Now when loading the real database the entryTable is much faster.~~
Now I just wait for a second to give JabRef time to open the table. Maybe somebody else comes up with a better idea. (```robot().waitForIdle();```) right before the table search won't work)
I also replaced the backlashes with normal slashes (```\ -> /```)in the database path b/c assertJ can't type them on windows.

[WIP] Fix for undoing deletion/cutting multiple entries (again)

---

src/main/java/net/sf/jabref/logic/formatter/bibtexfields/NormalizePagesFormatter.java
src/test/java/net/sf/jabref/logic/formatter/bibtexfields/NormalizePagesFormatterTest.java

Small improvements for page normalizer

---

src/main/java/net/sf/jabref/importer/fetcher/ACMPortalFetcher.java
src/main/java/net/sf/jabref/importer/fetcher/CiteSeerXFetcher.java
src/main/java/net/sf/jabref/importer/fetcher/DBLPFetcher.java
src/main/java/net/sf/jabref/importer/fetcher/GoogleScholarFetcher.java
src/main/java/net/sf/jabref/importer/fetcher/IEEEXploreFetcher.java
src/main/java/net/sf/jabref/importer/fetcher/ScienceDirectFetcher.java
src/main/java/net/sf/jabref/logic/fulltext/IEEE.java
src/main/java/net/sf/jabref/logic/net/URLDownload.java

Add overload for stringy urls in URLDownload

---

CHANGELOG.md
src/main/java/net/sf/jabref/gui/journals/ManageJournalsPanel.java

Fix for #1394 (reproduced in 3.3)
File was not created before writing to it.
Use nio methods
UI redesign in #1396

Fix personal journal list saving

---

src/main/java/net/sf/jabref/gui/fieldeditors/FileListEditor.java
src/main/resources/l10n/JabRef_da.properties
src/main/resources/l10n/JabRef_de.properties
src/main/resources/l10n/JabRef_en.properties
src/main/resources/l10n/JabRef_es.properties
src/main/resources/l10n/JabRef_fa.properties
src/main/resources/l10n/JabRef_fr.properties
src/main/resources/l10n/JabRef_in.properties
src/main/resources/l10n/JabRef_it.properties
src/main/resources/l10n/JabRef_ja.properties
src/main/resources/l10n/JabRef_nl.properties
src/main/resources/l10n/JabRef_no.properties
src/main/resources/l10n/JabRef_pt_BR.properties
src/main/resources/l10n/JabRef_ru.properties
src/main/resources/l10n/JabRef_sv.properties
src/main/resources/l10n/JabRef_tr.properties
src/main/resources/l10n/JabRef_vi.properties
src/main/resources/l10n/JabRef_zh.properties

from auto->get fulltext, download->download from URL

Resolve #1417 Rename buttons in file list editor

---

src/main/resources/l10n/JabRef_ja.properties
src/main/resources/l10n/Menu_ja.properties

Updating JabRef_ja.properties and Menu_ja.properties.

Updating Japanese localization

---

CHANGELOG.md
src/main/java/net/sf/jabref/external/DownloadExternalFile.java
src/main/java/net/sf/jabref/external/DroppedFileHandler.java
src/main/java/net/sf/jabref/external/MoveFileAction.java
src/main/java/net/sf/jabref/logic/cleanup/RenamePdfCleanup.java
src/main/java/net/sf/jabref/logic/util/io/FileUtil.java
src/test/java/net/sf/jabref/logic/util/io/FileUtilTest.java

Fix #1420 Auto downloader should respect file pattern and propose correct filename

---

src/main/java/net/sf/jabref/importer/fileformat/MedlineHandler.java
src/main/java/net/sf/jabref/logic/util/strings/StringUtil.java

Was reintroduced in https://github.com/JabRef/jabref/pull/547/files#diff-53cc8c02d3134eab17c46d69012faee5R630. Will merge directly after tests pass.

Remove expandAuthorInitials again

---

CHANGELOG.md
src/main/java/net/sf/jabref/model/entry/AuthorListParser.java
src/test/java/net/sf/jabref/model/entry/AuthorListTest.java

Fix #651: Improve parsing of author names containing braces

---

src/main/java/net/sf/jabref/MetaData.java
src/main/java/net/sf/jabref/cli/ArgumentProcessor.java
src/main/java/net/sf/jabref/collab/ChangeScanner.java
src/main/java/net/sf/jabref/exporter/AutoSaveManager.java
src/main/java/net/sf/jabref/exporter/ExportFormats.java
src/main/java/net/sf/jabref/exporter/ExportToClipboardAction.java
src/main/java/net/sf/jabref/exporter/SaveDatabaseAction.java
src/main/java/net/sf/jabref/gui/BasePanel.java
src/main/java/net/sf/jabref/gui/ImportInspectionDialog.java
src/main/java/net/sf/jabref/gui/JabRefFrame.java
src/main/java/net/sf/jabref/gui/actions/NewDatabaseAction.java
src/main/java/net/sf/jabref/gui/actions/NewSubDatabaseAction.java
src/main/java/net/sf/jabref/gui/dbproperties/DatabasePropertiesDialog.java
src/main/java/net/sf/jabref/importer/AutosaveStartupPrompter.java
src/main/java/net/sf/jabref/importer/ImportMenuItem.java
src/main/java/net/sf/jabref/importer/OpenDatabaseAction.java
src/main/java/net/sf/jabref/importer/ParserResult.java
src/main/java/net/sf/jabref/importer/fileformat/ImportFormat.java
src/main/java/net/sf/jabref/logic/search/DatabaseSearcher.java
src/main/java/net/sf/jabref/sql/importer/DbImportAction.java
src/test/java/net/sf/jabref/BibDatabaseContextTest.java
src/test/java/net/sf/jabref/MetaDataTest.java
src/test/java/net/sf/jabref/importer/OpenDatabaseActionTest.java
src/test/java/net/sf/jabref/importer/fileformat/BibtexParserTest.java
src/test/java/net/sf/jabref/logic/search/DatabaseSearcherTest.java

Move Encoding from BasePanel to MetaData

---

CHANGELOG.md
src/main/java/net/sf/jabref/logic/layout/format/RTFChars.java
src/main/java/net/sf/jabref/logic/util/strings/RtfCharMap.java
src/test/java/net/sf/jabref/logic/layout/format/RTFCharsTest.java

Fix #1457 Whole formatter needs a refactoring...

Fix RTF formatter bug

---

src/main/java/net/sf/jabref/gui/ClipBoardManager.java
src/main/java/net/sf/jabref/gui/desktop/JabRefDesktop.java
src/main/java/net/sf/jabref/gui/mergeentries/MergeEntryDOIDialog.java
src/main/java/net/sf/jabref/importer/fetcher/DOItoBibTeXFetcher.java
src/main/java/net/sf/jabref/importer/fileformat/PdfContentImporter.java
src/main/java/net/sf/jabref/logic/fulltext/DoiResolution.java
src/main/java/net/sf/jabref/logic/layout/format/DOICheck.java
src/main/java/net/sf/jabref/logic/util/DOI.java
src/test/java/net/sf/jabref/logic/util/DOITest.java

Fix #1455 NPE when retrieving BibteX data from DOI

---

src/main/java/net/sf/jabref/gui/help/HelpFiles.java

Correct link to label patterns help

---

README.md

Remove codacy as its just meaningless right now

---

CHANGELOG.md
src/main/java/net/sf/jabref/model/database/BibDatabase.java
src/main/java/net/sf/jabref/model/database/EntrySorter.java
src/test/java/net/sf/jabref/model/database/EntrySorterTest.java

Try to fix 1430, worked locally

---

src/test/java/net/sf/jabref/importer/ImportFileFilterTest.java

Just a quick fix for #1517; improving the `ImportFileFilterTest` with Mockito.

test ImportFileFilter with Mockito (continue #1517)

---

src/main/resources/l10n/JabRef_fr.properties

French localization: translation of empty strings; correction of a few glitches

French localization: translation of empty strings; correction of a few glitches

---

CHANGELOG.md
src/main/resources/l10n/JabRef_de.properties

Updated German translation

---

src/main/java/net/sf/jabref/gui/ContentSelectorDialog2.java
src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java
src/main/java/net/sf/jabref/gui/groups/GroupSelector.java
src/main/java/net/sf/jabref/importer/fileformat/MedlinePlainImporter.java
src/main/java/net/sf/jabref/importer/fileformat/PdfContentImporter.java
src/main/java/net/sf/jabref/logic/cleanup/FieldFormatterCleanup.java
src/main/java/net/sf/jabref/logic/groups/KeywordGroup.java
src/main/java/net/sf/jabref/logic/util/BuildInfo.java
src/main/java/net/sf/jabref/logic/util/Version.java
src/main/java/net/sf/jabref/model/database/EntrySorter.java

While I was at it: some code cleanups...
* entrySet instead of keySet
* correct order of static and final
* used equalsIgnoreCase instead of equals() and toLowerCase()
* added default switch case
* "correct" form of lambda (not sure what it is called)
* isEmpty() instead of size() > 0
* removed unused private variable

Some code cleanups

---

CHANGELOG.md
src/main/java/net/sf/jabref/importer/fetcher/SpringerFetcher.java
src/main/java/net/sf/jabref/importer/fileformat/JSONEntryParser.java

Earlier one less entry than requested was fetched when searching Springer. Added ChangeLog entry in case someone else detects this...

Fixed number of entries fetched from Springer

---

src/main/java/net/sf/jabref/gui/maintable/MainTable.java
src/main/java/net/sf/jabref/gui/menus/RightClickMenu.java
src/main/java/net/sf/jabref/gui/mergeentries/MergeEntries.java
src/main/java/net/sf/jabref/logic/bibtex/BibEntryWriter.java
src/main/java/net/sf/jabref/logic/openoffice/OOUtil.java

Some Codacy issues removed and some more use of getFieldOptional

---

src/main/java/net/sf/jabref/Globals.java
src/main/java/net/sf/jabref/collab/ChangeScanner.java
src/main/java/net/sf/jabref/exporter/SaveDatabaseAction.java
src/main/java/net/sf/jabref/gui/BasePanel.java
src/main/java/net/sf/jabref/gui/JabRefFrame.java
src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java
src/main/java/net/sf/jabref/gui/fieldeditors/TextArea.java
src/main/java/net/sf/jabref/gui/fieldeditors/TextField.java
src/main/java/net/sf/jabref/gui/maintable/MainTable.java
src/main/java/net/sf/jabref/gui/search/SearchBar.java

Encapsulated some fields in Globals

---

src/main/java/net/sf/jabref/external/AutoSetLinks.java
src/main/java/net/sf/jabref/external/SynchronizeFileField.java
src/main/java/net/sf/jabref/logic/fulltext/ACS.java
src/main/java/net/sf/jabref/logic/fulltext/ArXiv.java
src/main/java/net/sf/jabref/logic/fulltext/DoiResolution.java
src/main/java/net/sf/jabref/logic/fulltext/FindFullText.java
src/main/java/net/sf/jabref/logic/fulltext/GoogleScholar.java
src/main/java/net/sf/jabref/logic/fulltext/IEEE.java
src/main/java/net/sf/jabref/logic/fulltext/ScienceDirect.java
src/main/java/net/sf/jabref/logic/fulltext/SpringerLink.java
src/main/java/net/sf/jabref/logic/util/DOI.java
src/main/java/net/sf/jabref/model/DuplicateCheck.java
src/main/java/net/sf/jabref/model/database/BibDatabase.java
src/main/java/net/sf/jabref/model/entry/BibEntry.java
src/main/java/net/sf/jabref/model/entry/EntryUtil.java
src/main/java/net/sf/jabref/specialfields/SpecialFieldsUtils.java
src/test/java/net/sf/jabref/model/entry/EntryUtilTest.java

Only a few, but always something...

A few conversions of getField to getFieldOptional

---

src/main/java/net/sf/jabref/gui/BasePanel.java
src/main/java/net/sf/jabref/model/database/BibDatabase.java

Initialized to true and set to true...

Removed support for optinally following crossrefs since it wasn't used

---

src/main/java/net/sf/jabref/JabRefPreferences.java
src/main/java/net/sf/jabref/MetaData.java
src/main/java/net/sf/jabref/bst/BibtexCaseChanger.java
src/main/java/net/sf/jabref/gui/maintable/MainTableSelectionListener.java
src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java
src/main/java/net/sf/jabref/logic/CustomEntryTypesManager.java
src/main/java/net/sf/jabref/logic/fulltext/MimeTypeDetector.java
src/main/java/net/sf/jabref/logic/xmp/XMPUtil.java
src/main/java/net/sf/jabref/model/entry/AuthorListParser.java
src/main/java/net/sf/jabref/model/entry/BibEntry.java
src/main/java/net/sf/jabref/model/entry/CustomEntryType.java
src/main/java/net/sf/jabref/specialfields/SpecialFieldsUtils.java
src/test/java/net/sf/jabref/model/entry/BibEntryTests.java

A few less `return null`. Also removed the unused method `purgeCustomEntryTypes()` from `JabRefPreferences`.

Introduced Optional return values

---

CHANGELOG.md
src/main/java/net/sf/jabref/gui/mergeentries/MergeEntries.java
src/main/java/net/sf/jabref/gui/mergeentries/MergeEntryDOIDialog.java
src/main/java/net/sf/jabref/logic/util/strings/DiffHighlighting.java
src/main/java/net/sf/jabref/model/database/BibDatabase.java
src/main/java/net/sf/jabref/model/entry/InternalBibtexFields.java
src/main/resources/l10n/JabRef_da.properties
src/main/resources/l10n/JabRef_de.properties
src/main/resources/l10n/JabRef_en.properties
src/main/resources/l10n/JabRef_es.properties
src/main/resources/l10n/JabRef_fa.properties
src/main/resources/l10n/JabRef_fr.properties
src/main/resources/l10n/JabRef_in.properties
src/main/resources/l10n/JabRef_it.properties
src/main/resources/l10n/JabRef_ja.properties
src/main/resources/l10n/JabRef_nl.properties
src/main/resources/l10n/JabRef_no.properties
src/main/resources/l10n/JabRef_pt_BR.properties
src/main/resources/l10n/JabRef_ru.properties
src/main/resources/l10n/JabRef_sv.properties
src/main/resources/l10n/JabRef_tr.properties
src/main/resources/l10n/JabRef_vi.properties
src/main/resources/l10n/JabRef_zh.properties
src/test/java/net/sf/jabref/logic/util/strings/DiffHighlightingTest.java

Fixed #1527 and did some refactoring and cleanups.

Fixed #1527 and some refactoring/cleanups

---

build.gradle

Updated wiremock and assert-swing-junit. Creating PR to see that the tests still pass on the servers.

Updated versions of test dependencies

---

CHANGELOG.md
src/main/java/net/sf/jabref/logic/layout/format/DateFormatter.java
src/test/java/net/sf/jabref/logic/layout/format/DateFormatterTest.java

Added a configurable layout formatter for dates. Fixes #1249.

Added layout DateFormatter, see #1249

---

CHANGELOG.md
src/main/java/net/sf/jabref/gui/openoffice/OOBibBase.java

Fixed #1592

---

src/main/java/net/sf/jabref/gui/BasePanel.java
src/main/java/net/sf/jabref/gui/PreviewPanel.java
src/main/java/net/sf/jabref/gui/openoffice/OpenOfficePanel.java
src/main/java/net/sf/jabref/logic/exporter/ExportFormat.java
src/main/java/net/sf/jabref/logic/layout/Layout.java
src/main/java/net/sf/jabref/logic/layout/LayoutEntry.java
src/main/java/net/sf/jabref/logic/layout/LayoutFormatterPreferences.java
src/main/java/net/sf/jabref/logic/layout/LayoutHelper.java
src/main/java/net/sf/jabref/logic/layout/format/FileLink.java
src/main/java/net/sf/jabref/logic/layout/format/FileLinkPreferences.java
src/main/java/net/sf/jabref/logic/layout/format/NameFormatter.java
src/main/java/net/sf/jabref/logic/layout/format/NameFormatterPreferences.java
src/main/java/net/sf/jabref/logic/layout/format/WrapFileLinks.java
src/main/java/net/sf/jabref/logic/openoffice/OOBibStyle.java
src/main/java/net/sf/jabref/logic/openoffice/StyleLoader.java
src/main/java/net/sf/jabref/logic/util/io/FileUtil.java
src/test/java/net/sf/jabref/logic/layout/LayoutEntryTest.java
src/test/java/net/sf/jabref/logic/layout/LayoutTest.java
src/test/java/net/sf/jabref/logic/layout/format/FileLinkTest.java
src/test/java/net/sf/jabref/logic/openoffice/OOBibStyleTest.java
src/test/java/net/sf/jabref/logic/openoffice/StyleLoaderTest.java

Added LayoutFormatterPreferences (and related files)

---

src/main/java/net/sf/jabref/gui/actions/MassSetFieldAction.java
src/main/java/net/sf/jabref/gui/maintable/MainTableSelectionListener.java
src/main/java/net/sf/jabref/gui/search/SearchResultsDialog.java
src/main/java/net/sf/jabref/gui/util/comparator/IconComparator.java
src/main/java/net/sf/jabref/gui/util/comparator/RankingFieldComparator.java
src/main/java/net/sf/jabref/importer/fetcher/CrossRef.java
src/main/java/net/sf/jabref/logic/cleanup/DoiCleanup.java
src/main/java/net/sf/jabref/logic/cleanup/FieldFormatterCleanup.java
src/main/java/net/sf/jabref/logic/cleanup/UpgradePdfPsToFileCleanup.java

Converted a few getField to getFieldOptional

---

CHANGELOG.md
src/main/resources/resource/layout/bibordf.article.layout
src/main/resources/resource/layout/bibordf.layout
src/main/resources/resource/layout/bibtexml.layout
src/main/resources/resource/layout/html.inbook.layout
src/main/resources/resource/layout/html.inproceedings.layout
src/main/resources/resource/layout/html.layout
src/main/resources/resource/layout/ris/ris.article.layout
src/main/resources/resource/layout/ris/ris.book.layout
src/main/resources/resource/layout/ris/ris.conference.layout
src/main/resources/resource/layout/ris/ris.incollection.layout
src/main/resources/resource/layout/ris/ris.inproceedings.layout
src/main/resources/resource/layout/ris/ris.layout
src/main/resources/resource/layout/ris/ris.mastersthesis.layout
src/main/resources/resource/layout/ris/ris.patent.layout
src/main/resources/resource/layout/ris/ris.phdthesis.layout
src/main/resources/resource/layout/ris/ris.techreport.layout
src/main/resources/resource/layout/ris/ris.unpublished.layout
src/main/resources/resource/layout/ris/ris.www.layout

Used the built in formatters for DOIs to get more consistent exporter output.

Fixed #636 by using DOICheck and DOIStrip in export filters

---

src/main/java/net/sf/jabref/gui/EntryMarker.java
src/main/java/net/sf/jabref/gui/groups/WarnAssignmentSideEffects.java
src/main/java/net/sf/jabref/gui/maintable/PersistenceTableColumnListener.java
src/main/java/net/sf/jabref/gui/maintable/SpecialMainTableColumns.java
src/main/java/net/sf/jabref/gui/menus/RightClickMenu.java
src/main/java/net/sf/jabref/gui/preftabs/TableColumnsTab.java
src/main/java/net/sf/jabref/importer/OAI2Handler.java
src/main/java/net/sf/jabref/importer/fetcher/GVKParser.java
src/main/java/net/sf/jabref/importer/fileformat/MedlineImporter.java
src/main/java/net/sf/jabref/importer/fileformat/MedlinePlainImporter.java
src/main/java/net/sf/jabref/logic/groups/ExplicitGroup.java
src/main/java/net/sf/jabref/logic/importer/fetcher/ArXiv.java
src/main/java/net/sf/jabref/logic/mods/MODSEntry.java
src/main/java/net/sf/jabref/logic/openoffice/OOBibStyle.java
src/main/java/net/sf/jabref/logic/util/UpdateField.java
src/main/java/net/sf/jabref/model/entry/BibLatexEntryTypes.java
src/main/java/net/sf/jabref/model/entry/BibtexEntryTypes.java
src/main/java/net/sf/jabref/model/entry/FieldName.java
src/main/java/net/sf/jabref/model/entry/IEEETranEntryTypes.java
src/main/java/net/sf/jabref/model/entry/InternalBibtexFields.java
src/main/java/net/sf/jabref/preferences/JabRefPreferences.java
src/test/java/net/sf/jabref/model/entry/FieldNameTest.java

More field names in `FieldName` and a method `FieldName.orFields(FieldName.YEAR, FieldName.DATE)` to generate `"year/date"`.

More field names and a method

---

src/main/java/net/sf/jabref/JabRefMain.java
src/main/java/net/sf/jabref/cli/ArgumentProcessor.java
src/main/java/net/sf/jabref/gui/BasePanel.java
src/main/java/net/sf/jabref/gui/EntryTypeList.java
src/main/java/net/sf/jabref/gui/FieldSetComponent.java
src/main/java/net/sf/jabref/gui/GenFieldsCustomizer.java
src/main/java/net/sf/jabref/gui/ImportInspectionDialog.java
src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java
src/main/java/net/sf/jabref/gui/labelpattern/SearchFixDuplicateLabels.java
src/main/java/net/sf/jabref/gui/preftabs/LabelPatternPrefTab.java
src/main/java/net/sf/jabref/importer/fileformat/EndnoteImporter.java
src/main/java/net/sf/jabref/importer/fileformat/FreeCiteImporter.java
src/main/java/net/sf/jabref/logic/labelpattern/LabelPatternPreferences.java
src/main/java/net/sf/jabref/logic/labelpattern/LabelPatternUtil.java
src/main/java/net/sf/jabref/pdfimport/PdfImporter.java
src/test/java/net/sf/jabref/logic/labelpattern/LabelPatternUtilTest.java

The `static` initializer is quite ugly, but I do not really know what the best way to change it is. Maybe call `updateDefaultPattern` in `JabRefMain` after setting up the preferences?

Added LabelPatternPreferences

---

src/main/java/net/sf/jabref/gui/journals/ManageJournalsPanel.java

Apparently I missed one place in #1631... Same CHANGELOG though.

Fixed one more NPE which should have been fixed in #1631

---

src/main/resources/l10n/Menu_fr.properties

- Translation of an empty string
- Correction: wrong capitalization for *AUX

French localization: Menu

---

src/main/java/net/sf/jabref/JabRefGUI.java
src/main/java/net/sf/jabref/collab/FileUpdateMonitor.java
src/main/java/net/sf/jabref/gui/FieldSetComponent.java
src/main/java/net/sf/jabref/gui/GUIGlobals.java
src/main/java/net/sf/jabref/gui/ImportInspectionDialog.java
src/main/java/net/sf/jabref/gui/SidePaneManager.java
src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java
src/main/java/net/sf/jabref/gui/maintable/MainTableSelectionListener.java
src/main/java/net/sf/jabref/gui/preftabs/TableColumnsTab.java
src/main/java/net/sf/jabref/importer/fileformat/SilverPlatterImporter.java
src/main/java/net/sf/jabref/logic/layout/format/HTMLChars.java
src/main/java/net/sf/jabref/logic/layout/format/LatexToUnicodeFormatter.java
src/main/java/net/sf/jabref/logic/openoffice/OOPreFormatter.java
src/main/java/net/sf/jabref/model/database/DuplicationChecker.java

And some better variable names.

Replaced Object with appropriate class where possible

---

src/main/java/net/sf/jabref/external/push/PushToApplicationButton.java
src/main/java/net/sf/jabref/gui/JabRefFrame.java
src/main/java/net/sf/jabref/gui/preftabs/ExternalTab.java
src/main/java/net/sf/jabref/gui/push/AbstractPushToApplication.java
src/main/java/net/sf/jabref/gui/push/PushToApplication.java
src/main/java/net/sf/jabref/gui/push/PushToApplicationAction.java
src/main/java/net/sf/jabref/gui/push/PushToApplicationButton.java
src/main/java/net/sf/jabref/gui/push/PushToApplications.java
src/main/java/net/sf/jabref/gui/push/PushToEmacs.java
src/main/java/net/sf/jabref/gui/push/PushToLatexEditor.java
src/main/java/net/sf/jabref/gui/push/PushToLyx.java
src/main/java/net/sf/jabref/gui/push/PushToTeXstudio.java
src/main/java/net/sf/jabref/gui/push/PushToTexmaker.java
src/main/java/net/sf/jabref/gui/push/PushToVim.java
src/main/java/net/sf/jabref/gui/push/PushToWinEdt.java

Moved PushToApplication functionality from external.push to gui.push and cleaned up a bit, like getting rid of the static list.

PushToApplication cleanup and refactoring

---

src/test/java/net/sf/jabref/cli/AuxCommandLineTest.java
src/test/java/net/sf/jabref/logic/groups/GroupsUtilTest.java
src/test/java/net/sf/jabref/logic/xmp/XMPSchemaBibtexTest.java
src/test/java/net/sf/jabref/logic/xmp/XMPUtilTest.java

introduced when updating to the latest ErrorProne version.

Fixed most of the ErrorProne warnings

---

CHANGELOG.md
src/main/java/net/sf/jabref/JabRefGUI.java
src/main/java/net/sf/jabref/gui/JabRefFrame.java
src/main/java/net/sf/jabref/logic/remote/server/RemoteListenerServer.java

Fix #1288 Newly opened bib-file is not focused

---

CHANGELOG.md
src/main/java/net/sf/jabref/gui/openoffice/OpenOfficePanel.java

Doesn't fix the whole issue #1669, but at least the bug in the UI code so that the manual connection dialog can be drawn on Linux.

Fixed OO/LO manual connection dialog on Linux

---

src/main/java/net/sf/jabref/logic/cleanup/DoiCleanup.java
src/main/java/net/sf/jabref/logic/formatter/bibtexfields/NormalizeDateFormatter.java
src/main/java/net/sf/jabref/logic/formatter/bibtexfields/UnitsToLatexFormatter.java
src/main/java/net/sf/jabref/logic/layout/AbstractParamLayoutFormatter.java
src/main/java/net/sf/jabref/logic/layout/format/Authors.java
src/main/java/net/sf/jabref/logic/layout/format/IfPlural.java
src/main/java/net/sf/jabref/logic/layout/format/Replace.java
src/main/java/net/sf/jabref/logic/layout/format/WrapContent.java
src/main/java/net/sf/jabref/logic/layout/format/WrapFileLinks.java

In some places it made no real difference, in other it improved the code a bit. `UnitsToLatexFormatter` is reworked a bit, partly as a consequence.

Replaced some arrays with lists

---

build.gradle

Will merge if the build passes.

Updated wiremock version

---

src/main/resources/l10n/JabRef_fr.properties

French localization: Jabref_fr: empty string translated

---

build.gradle

Will merge if the builds pass.

Updated string similarity version

---

src/main/resources/l10n/Menu_fr.properties

French localization: Menu: Translation of an empty string

---

src/main/resources/l10n/JabRef_fr.properties

French localization: Jabref_fr: empty strings translated

---

src/main/java/net/sf/jabref/gui/FileListEntryEditor.java

Fix for #1609
Manually tested
Is just a simple restoring of the orig feature

Fix  auto open dialog on adding new file manually

---

src/main/java/net/sf/jabref/MetaData.java
src/main/java/net/sf/jabref/logic/importer/fetcher/DiVA.java
src/main/java/net/sf/jabref/logic/importer/fileformat/BibtexParser.java
src/test/java/net/sf/jabref/logic/importer/fetcher/DiVATest.java

Added DiVA fetcher based on the new interface

---

src/main/resources/l10n/JabRef_sv.properties

Updated some Swedish translations

---

src/main/java/net/sf/jabref/external/ExternalFileTypeEntryEditor.java
src/main/java/net/sf/jabref/external/MoveFileAction.java
src/main/java/net/sf/jabref/gui/groups/GroupAddRemoveDialog.java
src/main/java/net/sf/jabref/gui/undo/CountingUndoManager.java
src/main/java/net/sf/jabref/logic/bibtex/FieldContentParser.java
src/main/java/net/sf/jabref/logic/importer/fileformat/MedlineImporter.java
src/main/java/net/sf/jabref/logic/journals/Abbreviation.java
src/test/java/net/sf/jabref/SearchQueryHighlightListenerTest.java
src/test/java/net/sf/jabref/logic/formatter/bibtexfields/OrdinalsToSuperscriptFormatterTest.java
src/test/java/net/sf/jabref/logic/groups/GroupsUtilTest.java
src/test/java/net/sf/jabref/logic/journals/AbbreviationsTest.java
src/test/java/net/sf/jabref/logic/journals/ShippedJournalAbbreviationDuplicateTest.java
src/test/java/net/sf/jabref/logic/layout/format/HTMLCharsTest.java
src/test/java/net/sf/jabref/model/entry/AuthorListParameterTest.java

Fixed a number of Codacy issues.

Fixed some Codacy issues

---

src/test/java/net/sf/jabref/cli/AuxCommandLineTest.java
src/test/java/net/sf/jabref/logic/auxparser/AuxParserTest.java
src/test/java/net/sf/jabref/logic/bibtex/BibEntryWriterTest.java
src/test/java/net/sf/jabref/logic/bibtexkeypattern/BibtexKeyPatternUtilTest.java
src/test/java/net/sf/jabref/logic/openoffice/OOBibStyleTest.java

Removed not needed initializations of `Globals.prefs`.

Got rid of Globals in tests

---

src/main/java/net/sf/jabref/gui/importer/fetcher/DiVAtoBibTeXFetcher.java
src/main/java/net/sf/jabref/logic/importer/fetcher/DiVA.java
src/main/java/net/sf/jabref/logic/importer/fileformat/BibtexParser.java
src/main/java/net/sf/jabref/logic/importer/util/DBLPHelper.java
src/test/java/net/sf/jabref/logic/bibtexkeypattern/BibtexKeyPatternUtilTest.java
src/test/java/net/sf/jabref/logic/importer/ParsedBibEntryTests.java
src/test/java/net/sf/jabref/logic/importer/fileformat/BibtexParserTest.java

Seemed convenient, even though the source does not fully benefit from it.

Added method singleFromStringOptional

---

src/main/java/net/sf/jabref/logic/layout/LayoutEntry.java
src/main/java/net/sf/jabref/logic/layout/format/EntryTypeFormatter.java

Follow-up documentation and fixed comments for #1651

---

src/main/resources/l10n/Menu_fr.properties

French localization: Menu: update

---

CHANGELOG.md
src/main/java/net/sf/jabref/gui/dbproperties/DatabasePropertiesDialog.java
src/main/java/net/sf/jabref/logic/help/HelpFile.java

Added help button in Database Properties dialog

---

src/main/java/net/sf/jabref/gui/DuplicateResolverDialog.java
src/main/java/net/sf/jabref/logic/help/HelpFile.java

Implements #1767: Add Help Button to access new help page

---

src/main/java/net/sf/jabref/gui/BasePanel.java
src/main/java/net/sf/jabref/gui/importer/ImportInspectionDialog.java
src/main/java/net/sf/jabref/gui/importer/ImportMenuItem.java
src/main/java/net/sf/jabref/gui/importer/actions/AppendDatabaseAction.java
src/main/java/net/sf/jabref/gui/plaintextimport/TextInputDialog.java
src/main/java/net/sf/jabref/logic/util/UpdateField.java
src/main/java/net/sf/jabref/logic/util/UpdateFieldPreferences.java
src/main/java/net/sf/jabref/logic/util/date/EasyDateFormat.java
src/main/java/net/sf/jabref/pdfimport/PdfImporter.java
src/main/java/net/sf/jabref/preferences/JabRefPreferences.java

Less dependency on JabRefPreferences in a small part of logic...

Added UpdateFieldPreferences

---

build.gradle

I'll merge if the builds/tests pass.

Updated java-string-similarity to 0.16

---

src/main/java/net/sf/jabref/gui/SidePaneManager.java

The (new?) focus feature lead to an NPE when closing the last tab since there was no table to focus...

Fix NPE when closing the last tab

---

build.gradle

Will merge if the builds and tests pass.

Updated WireMock to 2.1.10

---

src/main/java/net/sf/jabref/logic/exporter/ExportFormat.java
src/main/java/net/sf/jabref/logic/layout/LayoutEntry.java
src/main/java/net/sf/jabref/logic/layout/LayoutFormatterPreferences.java

Some suggestions from by @koppor in #1695 which I didn't fully understand then. Also final Globals call in `logic`removed.

Some improvements to LayoutFormatterPreferences

---

src/main/java/net/sf/jabref/MetaData.java
src/main/java/net/sf/jabref/cli/ArgumentProcessor.java
src/main/java/net/sf/jabref/collab/ChangeScanner.java
src/main/java/net/sf/jabref/gui/dbproperties/DatabasePropertiesDialog.java
src/main/java/net/sf/jabref/gui/exporter/AutoSaveManager.java
src/main/java/net/sf/jabref/gui/exporter/ExportAction.java
src/main/java/net/sf/jabref/gui/exporter/ExportToClipboardAction.java
src/main/java/net/sf/jabref/gui/exporter/SaveDatabaseAction.java
src/main/java/net/sf/jabref/logic/importer/fileformat/BibtexParser.java
src/test/java/net/sf/jabref/BibtexTestData.java
src/test/java/net/sf/jabref/logic/importer/OpenDatabaseTest.java
src/test/java/net/sf/jabref/logic/importer/fileformat/BibtexParserTest.java

Made output of MetaData.getEncoding() Optional

---

src/main/java/net/sf/jabref/cli/CrossrefFetcherEvaluator.java
src/main/java/net/sf/jabref/gui/FieldSetComponent.java
src/main/java/net/sf/jabref/gui/JabRefFrame.java
src/main/java/net/sf/jabref/gui/PreviewPanel.java
src/main/java/net/sf/jabref/gui/desktop/JabRefDesktop.java
src/main/java/net/sf/jabref/gui/importer/actions/AppendDatabaseAction.java
src/main/java/net/sf/jabref/gui/importer/fetcher/DiVAtoBibTeXFetcher.java
src/main/java/net/sf/jabref/gui/importer/fetcher/ISBNtoBibTeXFetcher.java
src/main/java/net/sf/jabref/gui/journals/ManageJournalsPanel.java
src/main/java/net/sf/jabref/gui/maintable/MainTableDataModel.java
src/main/java/net/sf/jabref/gui/push/AbstractPushToApplication.java
src/main/java/net/sf/jabref/logic/exporter/ExportFormat.java
src/main/java/net/sf/jabref/logic/exporter/SavePreferences.java
src/main/java/net/sf/jabref/logic/groups/TreeNode.java
src/main/java/net/sf/jabref/logic/importer/fetcher/ArXiv.java
src/main/java/net/sf/jabref/logic/importer/fetcher/DOItoBibTeX.java
src/main/java/net/sf/jabref/logic/importer/fetcher/DiVA.java
src/main/java/net/sf/jabref/logic/importer/fetcher/GvkFetcher.java
src/main/java/net/sf/jabref/logic/importer/fileformat/BibtexParser.java
src/main/java/net/sf/jabref/logic/importer/util/DBLPHelper.java
src/main/java/net/sf/jabref/logic/net/Cookie.java
src/main/java/net/sf/jabref/logic/util/io/XMLUtil.java
src/main/java/net/sf/jabref/model/database/BibDatabase.java
src/test/java/net/sf/jabref/logic/bibtexkeypattern/BibtexKeyPatternUtilTest.java
src/test/java/net/sf/jabref/logic/importer/ParsedBibEntryTests.java
src/test/java/net/sf/jabref/logic/importer/fileformat/BibtexParserTest.java
src/test/java/net/sf/jabref/logic/net/CookieTest.java

* Renaming variables
* Closing resources
* Checking for null
* Removed deprecated method
* Added annotations
* Removed unused code

Removed some warnings and findbugs issues

---

CHANGELOG.md
src/main/java/net/sf/jabref/gui/EntryMarker.java
src/main/java/net/sf/jabref/gui/PreviewPanel.java
src/main/java/net/sf/jabref/gui/preftabs/GeneralTab.java
src/main/java/net/sf/jabref/preferences/JabRefPreferences.java

Has been disabled since long so might as well remove the code.
Also cleaned up the preferences a bit.

Removed entry preview toolbar

---

src/main/java/net/sf/jabref/external/WriteXMPAction.java
src/main/java/net/sf/jabref/gui/bibtexkeypattern/SearchFixDuplicateLabels.java
src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java
src/main/java/net/sf/jabref/gui/groups/TransferableEntrySelection.java
src/main/java/net/sf/jabref/gui/importer/fetcher/IEEEXploreFetcher.java
src/main/java/net/sf/jabref/gui/openoffice/OpenOfficePanel.java
src/main/java/net/sf/jabref/gui/undo/UndoableChangeType.java
src/main/java/net/sf/jabref/gui/undo/UndoableFieldChange.java
src/main/java/net/sf/jabref/gui/undo/UndoableInsertEntry.java
src/main/java/net/sf/jabref/gui/undo/UndoableRemoveEntry.java
src/main/java/net/sf/jabref/logic/bibtex/BibEntryWriter.java
src/main/java/net/sf/jabref/logic/bibtexkeypattern/BibtexKeyPatternUtil.java
src/main/java/net/sf/jabref/logic/importer/fetcher/CrossRef.java
src/main/java/net/sf/jabref/logic/search/rules/GrammarBasedSearchRule.java
src/main/java/net/sf/jabref/logic/search/rules/RegexBasedSearchRule.java
src/main/java/net/sf/jabref/logic/xmp/XMPUtil.java
src/main/java/net/sf/jabref/model/database/BibDatabase.java
src/main/java/net/sf/jabref/model/database/KeyChangeListener.java
src/test/java/net/sf/jabref/logic/cleanup/CleanupWorkerTest.java
src/test/java/net/sf/jabref/logic/importer/fileformat/BibtexImporterTest.java
src/test/java/net/sf/jabref/logic/importer/fileformat/BibtexParserTest.java
src/test/java/net/sf/jabref/logic/xmp/XMPUtilTest.java

Converted a number of deprecated method calls

---

src/main/java/net/sf/jabref/gui/menus/FileHistoryMenu.java
src/main/java/net/sf/jabref/logic/util/io/FileHistory.java
src/main/java/net/sf/jabref/preferences/JabRefPreferences.java
src/test/java/net/sf/jabref/logic/util/io/FileHistoryTest.java

Removed JabRefPreferences from FileHistory

---

src/main/java/net/sf/jabref/MetaData.java
src/main/java/net/sf/jabref/gui/dbproperties/DatabasePropertiesDialog.java

Fix #1806 Wrong Database properties encoding

---

src/main/java/net/sf/jabref/gui/importer/ImportMenuItem.java
src/main/java/net/sf/jabref/gui/importer/actions/AppendDatabaseAction.java
src/main/java/net/sf/jabref/gui/importer/actions/OpenDatabaseAction.java

Fix #1803 Working directory is set to full path including filename

---

src/main/resources/l10n/Menu_it.properties

Update of Menu_it.properties for 3.6 release.

Update of Menu_it.properties

---

CHANGELOG.md
src/main/java/net/sf/jabref/JabRefGUI.java
src/main/java/net/sf/jabref/cli/ArgumentProcessor.java
src/main/java/net/sf/jabref/gui/JabRefFrame.java
src/main/java/net/sf/jabref/gui/importer/ParserResultWarningDialog.java
src/main/java/net/sf/jabref/logic/bibtexkeypattern/BibtexKeyPatternUtil.java
src/main/java/net/sf/jabref/logic/bst/BibtexNameFormatter.java
src/main/java/net/sf/jabref/logic/groups/GroupsUtil.java
src/main/java/net/sf/jabref/logic/importer/ParserResult.java
src/main/java/net/sf/jabref/logic/layout/format/Authors.java
src/main/java/net/sf/jabref/logic/layout/format/CreateDocBookAuthors.java
src/main/java/net/sf/jabref/logic/layout/format/CurrentDate.java
src/main/java/net/sf/jabref/logic/layout/format/HTMLChars.java
src/main/java/net/sf/jabref/logic/layout/format/LatexToUnicodeFormatter.java
src/main/java/net/sf/jabref/logic/openoffice/OOBibStyle.java
src/main/java/net/sf/jabref/model/entry/Author.java
src/test/java/net/sf/jabref/logic/bibtexkeypattern/BibtexKeyPatternUtilTest.java
src/test/java/net/sf/jabref/model/entry/AuthorListTest.java

* ParserResult.getFile()
* Author.getFirst(), getVon(), getJR(), and getLast()
Some minor clean ups in HTMLChars and LatexToUnicodeFormatter
Also fixed an NPE when the pattern `authFirstFull` is used and the author does not have a von-part.

Some more Optional

---

src/main/java/net/sf/jabref/logic/bibtex/comparator/FieldComparator.java
src/main/java/net/sf/jabref/logic/util/strings/StringUtil.java
src/test/java/net/sf/jabref/logic/util/strings/StringUtilTest.java

Optional result from string to integer conversion

---

src/main/java/net/sf/jabref/collab/ChangeScanner.java
src/main/java/net/sf/jabref/gui/PreambleEditor.java
src/main/java/net/sf/jabref/logic/bst/VM.java
src/main/java/net/sf/jabref/logic/exporter/BibDatabaseWriter.java
src/main/java/net/sf/jabref/model/database/BibDatabase.java
src/test/java/net/sf/jabref/logic/auxparser/AuxParserTest.java
src/test/java/net/sf/jabref/logic/importer/OpenDatabaseTest.java
src/test/java/net/sf/jabref/logic/importer/fileformat/BibtexParserTest.java
src/test/java/net/sf/jabref/model/database/BibDatabaseTest.java

The code was/is a bit confusing since both null and "" preamble are dealt with in the same way (not saved).

Made output of BibDatabase.getPreamble() Optional

---

src/main/java/net/sf/jabref/MetaData.java
src/main/java/net/sf/jabref/collab/ChangeScanner.java
src/main/java/net/sf/jabref/collab/GroupChange.java
src/main/java/net/sf/jabref/gui/groups/GroupAddRemoveDialog.java
src/main/java/net/sf/jabref/gui/groups/GroupSelector.java
src/main/java/net/sf/jabref/gui/importer/ImportInspectionDialog.java
src/main/java/net/sf/jabref/gui/importer/actions/AppendDatabaseAction.java
src/main/java/net/sf/jabref/gui/importer/actions/ConvertLegacyExplicitGroups.java
src/main/java/net/sf/jabref/gui/menus/RightClickMenu.java
src/test/java/net/sf/jabref/MetaDataTest.java
src/test/java/net/sf/jabref/logic/importer/fileformat/BibtexParserTest.java

Made MetaData.getGroups return Optional

---

src/main/java/net/sf/jabref/gui/JabRefFrame.java
src/main/java/net/sf/jabref/gui/bibtexkeypattern/BibtexKeyPatternDialog.java
src/main/java/net/sf/jabref/logic/bibtexkeypattern/BibtexKeyPatternPreferences.java
src/main/java/net/sf/jabref/logic/bibtexkeypattern/BibtexKeyPatternUtil.java
src/main/java/net/sf/jabref/logic/util/io/RegExpFileSearch.java
src/main/java/net/sf/jabref/preferences/JabRefPreferences.java
src/test/java/net/sf/jabref/logic/bibtexkeypattern/MakeLabelWithDatabaseTest.java

Improved tests for BibtexKeyPatternUtil and made some related changes (removed unused preference and move a gui class).

Tests for makeLabel and some cleanups in BibtexKeyPattern prefs

---

src/main/java/net/sf/jabref/logic/bibtexkeypattern/BibtexKeyPatternUtil.java
src/test/java/net/sf/jabref/logic/bibtexkeypattern/BibtexKeyPatternUtilTest.java
src/test/java/net/sf/jabref/logic/bibtexkeypattern/MakeLabelWithDatabaseTest.java

Removed some unused/unnecessary code and added a number of tests.

More tests and some cleanups of BibtexKeyPatternUtil

---

src/test/java/net/sf/jabref/logic/layout/format/WrapFileLinksTest.java

Initial tests for WrapFileLinks

---

config/checkstyle/checkstyle.xml

Let checkstyle test that no (GPL) header is present

---

src/main/java/net/sf/jabref/gui/journals/ManageJournalAbbreviationsView.java

Reenable localization in JournalAbbreviationDialog

---

src/main/java/net/sf/jabref/JabRefMain.java
src/main/java/net/sf/jabref/gui/preftabs/AdvancedTab.java
src/main/java/net/sf/jabref/logic/remote/RemotePreferences.java
src/main/java/net/sf/jabref/preferences/JabRefPreferences.java
src/test/java/net/sf/jabref/logic/remote/RemotePreferencesTest.java

As logic should not reference `JabRefPreferences`.

Refactored RemotePreferences

---

src/main/java/net/sf/jabref/JabRefMain.java
src/main/java/net/sf/jabref/gui/preftabs/NetworkTab.java
src/main/java/net/sf/jabref/logic/net/ProxyPreferences.java
src/main/java/net/sf/jabref/preferences/JabRefPreferences.java

Fewer dependencies to `JabRefPreferences` in `logic`.

Refactored ProxyPreferences

---

.mailmap
AUTHORS

.mailmap edited, AUTHORS generated
- Siedlerchr removed

Double authors removed 2

---

src/test/java/net/sf/jabref/ArchitectureTests.java
src/test/java/net/sf/jabref/logic/cleanup/CleanupWorkerTest.java
src/test/java/net/sf/jabref/logic/importer/fetcher/IsbnFetcherTest.java

Removed last Globals in logic tests and introduced architecture test

---

src/main/resources/l10n/JabRef_ja.properties
src/main/resources/l10n/Menu_ja.properties

@kojiyokota I was so kind and fixed the language files for you. You had some duplicates in there, probably resulted in conflicts from merging
@koppor  We could merge this and then @kojiyokota can update the missing strings again as new pr.
Follow up from #1973

Update japanse trranlsation (removed duplicates)

---

src/integrationTest/java/net/sf/jabref/gui/search/SearchResultsTest.java
src/test/java/net/sf/jabref/gui/search/SearchResultsTest.java
src/test/java/net/sf/jabref/logic/search/DatabaseSearcherTest.java
src/test/java/net/sf/jabref/logic/search/SearchQueryTest.java

This PR updates https://github.com/gabrielmldantas/jabref/pull/1 to the most resent JabRef code.
* tests for search expressions
* UI test for the search
This could help create tests for a solution for #1975

Add search test

---

src/main/java/net/sf/jabref/gui/IconTheme.java
src/main/java/net/sf/jabref/gui/search/GlobalSearchBar.java

Icon does not change when toggling global search

---

CHANGELOG.md
src/main/java/net/sf/jabref/logic/integrity/IntegrityCheck.java
src/main/java/net/sf/jabref/logic/integrity/MonthChecker.java
src/main/resources/l10n/JabRef_da.properties
src/main/resources/l10n/JabRef_de.properties
src/main/resources/l10n/JabRef_en.properties
src/main/resources/l10n/JabRef_es.properties
src/main/resources/l10n/JabRef_fa.properties
src/main/resources/l10n/JabRef_fr.properties
src/main/resources/l10n/JabRef_in.properties
src/main/resources/l10n/JabRef_it.properties
src/main/resources/l10n/JabRef_ja.properties
src/main/resources/l10n/JabRef_nl.properties
src/main/resources/l10n/JabRef_no.properties
src/main/resources/l10n/JabRef_pt_BR.properties
src/main/resources/l10n/JabRef_ru.properties
src/main/resources/l10n/JabRef_sv.properties
src/main/resources/l10n/JabRef_tr.properties
src/main/resources/l10n/JabRef_vi.properties
src/main/resources/l10n/JabRef_zh.properties
src/test/java/net/sf/jabref/logic/integrity/IntegrityCheckTest.java

Implemented Integrity MonthChecker

---

.gitignore
localization.gradle
scripts/.gitignore
scripts/README.md
scripts/logger.py
scripts/syncLang.py
src/main/resources/l10n/JabRef_da.properties
src/main/resources/l10n/JabRef_de.properties
src/main/resources/l10n/JabRef_en.properties
src/main/resources/l10n/JabRef_es.properties
src/main/resources/l10n/JabRef_fa.properties
src/main/resources/l10n/JabRef_fr.properties
src/main/resources/l10n/JabRef_in.properties
src/main/resources/l10n/JabRef_it.properties
src/main/resources/l10n/JabRef_ja.properties
src/main/resources/l10n/JabRef_nl.properties
src/main/resources/l10n/JabRef_no.properties
src/main/resources/l10n/JabRef_pt_BR.properties
src/main/resources/l10n/JabRef_ru.properties
src/main/resources/l10n/JabRef_sv.properties
src/main/resources/l10n/JabRef_tr.properties
src/main/resources/l10n/JabRef_vi.properties
src/main/resources/l10n/JabRef_zh.properties
src/main/resources/l10n/Menu_ja.properties

Relevant Issues: #1939
I rewrote the the localization script:
The Script has following commands available
- `$ python scripts/syncLang.py status [--extended]`
- prints the current status to the terminal
- `[--extended]` if the translations keys which create problems should be printed
- usable with Gradle tasks
- `$ gradle status`
- `$ gradle statusExtended`
- `$ python scripts/syncLang.py markdown`
- Creates a markdown file of the current status and opens it
- usable with Gradle tasks
- `$ gradle statusWithMarkdown`
- `$ python scripts/syncLang.py update [--extended]`
- compares all the localization files against the English one and fixes unambiguous duplicates, removes obsolete keys, adds missing keys, and sorts them
- `[--extended]` if the translations keys which create problems should …

Rewrite localization script

---

src/main/java/net/sf/jabref/model/search/rules/SearchRules.java

Fix logged warning when searching for nothing (i.e. clear search)

---

CHANGELOG.md
src/main/java/net/sf/jabref/JabRefGUI.java
src/main/java/net/sf/jabref/gui/help/NewVersionDialog.java
src/main/java/net/sf/jabref/gui/worker/VersionWorker.java
src/main/java/net/sf/jabref/preferences/JabRefPreferences.java
src/main/java/net/sf/jabref/preferences/VersionPreferences.java

Fixes #2054 
Made a rookie mistake and ignored the already ignored version again.
Reworked the preferences to the new design.

Fix ignore version

---

src/main/resources/l10n/JabRef_it.properties

Add Italian translation for new strings

---

CHANGELOG.md
src/main/java/net/sf/jabref/gui/JabRefFrame.java

Two separator glitch in menu edit

---

src/main/resources/l10n/JabRef_fr.properties
src/main/resources/l10n/Menu_fr.properties

French localization: untranslated strings + a correction

---

src/main/java/net/sf/jabref/gui/bibtexkeypattern/BibtexKeyPatternPanel.java

Fix exception when opening preference dialog

---

src/main/java/net/sf/jabref/gui/search/GlobalSearchBar.java

Implements/fixes https://github.com/koppor/jabref/issues/103

CTRL+f in search field highlights everything

---

src/main/java/net/sf/jabref/gui/maintable/MainTableSelectionListener.java

1. Create new database  (or use an existing one, the important part is that the editor was never opened in this database before)
- create a new entry

Hotfix: NPE in the main table

---

src/main/java/net/sf/jabref/gui/groups/GroupTreeNodeViewModel.java

This fixes #2119 and #2098 
- ~~[ ] Change in CHANGELOG.md described~~ Introduced in dev builds

Fix group drag and drop

---

src/test/java/net/sf/jabref/logic/importer/fetcher/AstrophysicsDataSystemTest.java

Added missing fields 
Fixes #2168

fix failing ADS test

---

src/main/java/net/sf/jabref/logic/importer/fetcher/ArXiv.java
src/main/java/net/sf/jabref/logic/net/URLDownload.java

Fixes #2222 URLDownload now resolves redirects by default

---

CHANGELOG.md
src/main/java/net/sf/jabref/gui/JabRefFrame.java
src/main/java/net/sf/jabref/gui/SidePaneComponent.java
src/main/java/net/sf/jabref/gui/groups/GroupSelector.java
src/main/java/net/sf/jabref/preferences/JabRefPreferences.java

fixes #2224 (Mnemonics for "Toggle Group Pane") and #2201 resp. #1825

Fixes for group pane toggling

---

src/main/resources/l10n/JabRef_zh.properties
src/main/resources/l10n/Menu_zh.properties

Update Chinese translation for version 3.7.

---

src/main/java/net/sf/jabref/logic/cleanup/RenamePdfCleanup.java
src/test/java/net/sf/jabref/logic/cleanup/RenamePdfCleanupTest.java

I found some time to look into the code. It seems, only the last conditional statement was accidentally placed inside the for loop.
I fixed that and now the behavior is as before, as far I can see.

Moved return out of for-loop

---

src/main/java/net/sf/jabref/shared/DBMSSynchronizer.java

Fixes https://github.com/JabRef/jabref/pull/2300#issuecomment-261801274.

Fix initialization of a shared database

---

build.gradle
src/test/java/net/sf/jabref/logic/citationstyle/CitationStyleGeneratorTest.java

see https://github.com/michel-kraemer/citeproc-java/releases

Update citeproc dependency to 1.0.1

---

src/main/java/net/sf/jabref/model/database/BibDatabaseContext.java
src/main/java/net/sf/jabref/model/metadata/FileDirectoryPreferences.java

Suggest current BIB folder when no defaults are set.

Fix #1446 Only add non empty paths

---

src/main/java/net/sf/jabref/gui/fieldeditors/EntryLinkListEditor.java
src/main/java/net/sf/jabref/model/entry/BibtexSingleField.java
src/main/java/net/sf/jabref/model/entry/InternalBibtexFields.java
src/main/resources/l10n/JabRef_da.properties
src/main/resources/l10n/JabRef_de.properties
src/main/resources/l10n/JabRef_en.properties
src/main/resources/l10n/JabRef_es.properties
src/main/resources/l10n/JabRef_fa.properties
src/main/resources/l10n/JabRef_fr.properties
src/main/resources/l10n/JabRef_in.properties
src/main/resources/l10n/JabRef_it.properties
src/main/resources/l10n/JabRef_ja.properties
src/main/resources/l10n/JabRef_nl.properties
src/main/resources/l10n/JabRef_no.properties
src/main/resources/l10n/JabRef_pt_BR.properties
src/main/resources/l10n/JabRef_ru.properties
src/main/resources/l10n/JabRef_sv.properties
src/main/resources/l10n/JabRef_tr.properties
src/main/resources/l10n/JabRef_vi.properties
src/main/resources/l10n/JabRef_zh.properties

See #2243
- Increase heigth of crossref field
- Rename Select to Jump to entry

Crossref improvements

---

config/IntelliJ Code Style.xml

Contains:
- Import style according to wiki.
- Automatic line breaks

Add intellij code style

---

CHANGELOG.md
src/main/java/net/sf/jabref/gui/preftabs/FileTab.java

Fixes https://github.com/JabRef/jabref/issues/2378.

Fix preferences backup option not saved

---

src/main/resources/l10n/JabRef_it.properties

Translate new entries

---

CHANGELOG.md
src/main/java/net/sf/jabref/gui/FXDialogService.java
src/main/java/net/sf/jabref/gui/FileDialog.java
src/main/java/net/sf/jabref/gui/importer/ImportFileFilter.java
src/main/java/net/sf/jabref/gui/importer/ImportFormats.java
src/main/java/net/sf/jabref/gui/journals/ManageJournalAbbreviationsViewModel.java
src/main/java/net/sf/jabref/gui/util/FileDialogConfiguration.java
src/main/java/net/sf/jabref/logic/util/FileExtensions.java
src/test/java/net/sf/jabref/gui/journals/ManageJournalAbbreviationsTest.java

[FX] Use native file dialog

---

src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java
src/main/java/net/sf/jabref/gui/entryeditor/MathSciNetPaneView.java
src/main/java/net/sf/jabref/model/entry/FieldName.java
src/main/java/net/sf/jabref/model/entry/MathSciNetId.java

Review MathSciNet tab

---

src/main/java/net/sf/jabref/cli/XMPUtilMain.java
src/main/java/net/sf/jabref/gui/importer/fetcher/ACMPortalFetcher.java
src/main/java/net/sf/jabref/gui/importer/fetcher/IEEEXploreFetcher.java
src/main/java/net/sf/jabref/gui/importer/fetcher/INSPIREFetcher.java
src/main/java/net/sf/jabref/logic/importer/fetcher/BibsonomyScraper.java
src/main/java/net/sf/jabref/logic/importer/fetcher/DoiFetcher.java
src/main/java/net/sf/jabref/logic/importer/fileformat/BibtexImporter.java
src/main/java/net/sf/jabref/logic/importer/fileformat/BibtexParser.java
src/test/java/net/sf/jabref/cli/AuxCommandLineTest.java
src/test/java/net/sf/jabref/gui/groups/GroupsUtilTest.java
src/test/java/net/sf/jabref/gui/importer/EntryFromFileCreatorManagerTest.java
src/test/java/net/sf/jabref/logic/auxparser/AuxParserTest.java
src/test/java/net/sf/jabref/logic/bibtex/BibEntryWriterTest.java
src/test/java/net/sf/jabref/logic/bibtexkeypattern/BibtexKeyPatternUtilTest.java
src/test/java/net/sf/jabref/logic/bst/TestVM.java
src/test/java/net/sf/jabref/logic/exporter/BibtexDatabaseWriterTest.java
src/test/java/net/sf/jabref/logic/importer/BibDatabaseTestsWithFiles.java
src/test/java/net/sf/jabref/logic/importer/DatabaseFileLookupTest.java
src/test/java/net/sf/jabref/logic/importer/ParsedBibEntryTests.java
src/test/java/net/sf/jabref/logic/importer/fileformat/BibtexParserTest.java
src/test/java/net/sf/jabref/logic/layout/LayoutTest.java
src/test/java/net/sf/jabref/logic/openoffice/OOBibStyleTest.java
src/test/java/net/sf/jabref/logic/xmp/XMPUtilTest.java

Revert "Replace calls of BibtexParser.parse"

---

src/main/resources/l10n/Menu_ru.properties

L10N-ru update

---

src/main/java/net/sf/jabref/JabRefExecutorService.java

incorrect log name of JabRefExecutorService

---

CHANGELOG.md
src/main/java/net/sf/jabref/gui/importer/fetcher/ACMPortalFetcher.java

Remove html code from ACM fetcher
Fixes #2472 

Remove html code from ACM fetcher

---

CHANGELOG.md
src/main/java/net/sf/jabref/gui/groups/GroupDialog.java

Will merge as soon as build passes.

Fix #2481: ClassCastException because of wrong cast

---

build.gradle

@koppor is this the correct way to include the src folder? I'm never sure about these gradle things.
I already merge so that we have a working fx build.

Include fxml files in src folder as resources

---

src/main/java/net/sf/jabref/logic/l10n/Localization.java
src/main/resources/l10n/JabRef_da.properties
src/main/resources/l10n/JabRef_de.properties
src/main/resources/l10n/JabRef_en.properties
src/main/resources/l10n/JabRef_es.properties
src/main/resources/l10n/JabRef_fa.properties
src/main/resources/l10n/JabRef_fr.properties
src/main/resources/l10n/JabRef_in.properties
src/main/resources/l10n/JabRef_it.properties
src/main/resources/l10n/JabRef_ja.properties
src/main/resources/l10n/JabRef_nl.properties
src/main/resources/l10n/JabRef_no.properties
src/main/resources/l10n/JabRef_pt_BR.properties
src/main/resources/l10n/JabRef_ru.properties
src/main/resources/l10n/JabRef_sv.properties
src/main/resources/l10n/JabRef_tr.properties
src/main/resources/l10n/JabRef_vi.properties
src/main/resources/l10n/JabRef_zh.properties
src/main/resources/l10n/Menu_ru.properties
src/test/java/net/sf/jabref/logic/l10n/LocalizationBundleForTEst.java
src/test/java/net/sf/jabref/logic/l10n/LocalizationConsistencyTest.java
src/test/java/net/sf/jabref/logic/l10n/LocalizationEntry.java
src/test/java/net/sf/jabref/logic/l10n/LocalizationParser.java
src/test/java/net/sf/jabref/logic/l10n/LocalizationParserTest.java

Fixes eclipse build and fix also failing localization files

rename LocalizationBundle in Test folder

---

CHANGELOG.md
src/main/java/net/sf/jabref/logic/formatter/bibtexfields/LatexCleanupFormatter.java
src/test/java/net/sf/jabref/logic/formatter/bibtexfields/LatexCleanupFormatterTest.java

Revert "Fix repeated escaping of % sign"

---

src/main/resources/l10n/JabRef_fr.properties

French localization: translation of a string

---

src/main/java/net/sf/jabref/gui/EntryTypeDialog.java
src/main/java/net/sf/jabref/logic/importer/fetcher/DoiFetcher.java

I think making the DOI fetcher default ias reasonable, I always need to select it otherwise as the first alphabetical entry is default for now.

Make DOIFetcher the default fetcher in new entry dialog

---

src/main/java/net/sf/jabref/gui/cleanup/FieldFormatterCleanupsPanel.java
src/main/java/net/sf/jabref/model/entry/InternalBibtexFields.java
src/test/java/net/sf/jabref/logic/integrity/IntegrityCheckTest.java

See https://github.com/koppor/jabref/issues/162

Enhance integrity check tests

---

.travis.yml
buildres/gui-tests.sh
src/test/java/net/sf/jabref/logic/cleanup/BiblatexCleanupTest.java

https://travis-ci.org/JabRef/jabref/builds/201863404

Travis Build

---

jabref.install4j

JabRef causes permanent discrete GPU usage

---

src/main/resources/l10n/Menu_fr.properties

Localization: Menu: French: Update

---

src/main/resources/l10n/JabRef_fr.properties

Localization: General file: French: Update

---

src/test/java/org/jabref/logic/importer/fetcher/MedlineFetcherTest.java

Add missing/changed fields to fix test
As this entry seems to be published now, I don't  expected it to change further...

Fix medline fetcher test

---

src/main/java/org/jabref/gui/entryeditor/EntryEditor.java

and File Annotations
Adjust formatting
~~- [ ] Change in CHANGELOG.md described~~
~~- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org]~~(https://github.com/JabRef/help.jabref.org/issues)?)

Fix NPE on tab switching in EntryEditor between Mr Dlib

---

src/main/resources/l10n/JabRef_fr.properties

Localization: MainFile: French: update

---

src/main/java/org/jabref/logic/pdf/EntryAnnotationImporter.java

FileAnnotationTab now only shows the FileName, not the full path.

---

CHANGELOG.md
src/main/java/org/jabref/logic/msbib/MSBibConverter.java
src/main/java/org/jabref/logic/msbib/MSBibEntry.java
src/main/java/org/jabref/model/entry/BibEntry.java
src/test/resources/org/jabref/logic/exporter/MsBibExportFormatTestDay.bib
src/test/resources/org/jabref/logic/exporter/MsBibExportFormatTestDay.xml

Fix for #2691 
Only works if date is given in ISO8601 
~~- [ ] If you changed the localization: Did you run `gradle localizationUpdate`?

Export day from date field to MS Office xml

---

CHANGELOG.md.orig
src/test/java/org/jabref/logic/importer/fetcher/IsbnViaChimboriFetcherTest.java

Fix URL in isbn test

---

CHANGELOG.md
src/main/java/org/jabref/gui/preftabs/FileTab.java
src/main/java/org/jabref/gui/util/DirectoryDialogConfiguration.java

Change to FXDialogService
~~- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)~~

Open main file directory in correct file dir

---

src/test/java/org/jabref/logic/util/BuildInfoTest.java

Azure test

---

src/main/java/org/jabref/gui/entryeditor/FieldExtraComponents.java

@lynyus Can you check if my code is fine conceptually?

Move DOI fetching to separate thread #2682

---

src/main/resources/l10n/JabRef_zh.properties
src/main/resources/l10n/Menu_zh.properties

Update Chinese translation.

---

src/main/resources/l10n/Menu_fr.properties

Localization: French: Menu: Translation of new entries

---

src/main/java/org/jabref/gui/logging/ApplicationInsightsAppender.java
src/main/resources/ApplicationInsights.xml
src/main/resources/log4j2.xml

Speedup start by improving Application Insights configuration

---

src/main/resources/l10n/JabRef_it.properties

Translate new strings

---

src/main/resources/l10n/Menu_de.properties

Add German menu translations

---

src/main/resources/l10n/JabRef_zh.properties
src/main/resources/l10n/Menu_zh.properties

Fix 'library' vs 'database' Chinese translation.

---

src/main/java/org/jabref/gui/groups/EntryTableTransferHandler.java

Fix for #2760
Internal change only. Was introduced by fa6e0740fdc66afe05f0b54a507f58198f6e2000

Fix Drag and drop of file by first converting to File and then to path

---

src/test/java/org/jabref/logic/util/io/CiteKeyBasedFileFinderTest.java

Fix associated files test

---

src/main/java/org/jabref/gui/fieldeditors/DateEditor.fxml
src/main/java/org/jabref/gui/fieldeditors/DateEditor.java
src/main/java/org/jabref/gui/fieldeditors/DateEditorViewModel.java
src/main/java/org/jabref/gui/fieldeditors/FieldEditors.java
src/main/java/org/jabref/gui/util/BindingsHelper.java
src/main/java/org/jabref/gui/util/component/TemporalAccessorPicker.java
src/main/java/org/jabref/model/entry/Date.java

Should fix https://github.com/JabRef/jabref/issues/2806 and https://github.com/JabRef/jabref/pull/2781#issuecomment-296427732.

Fix #2806: date editor also accepts incomplete dates

---

src/main/resources/l10n/Menu_el.properties

Θέλω βοηθεια για να το μεταφράσω...

Menu Greek Translation

---

.github/ISSUE_TEMPLATE.md

A small improvement, as logs often grow long and nobody likes scrolling.
<details>
<summary>Log File</summary>
```
Paste an excerpt of your log file here
```
</details>

Improve Issue Template Using a Collapsible Log Area

---

LICENSE.md

...hopefully. I took the standard text that is provided by github (there are essentially no changes to the previous text except Anführungsstriche vs double apostrophes)

Update license file so that github recognize it properly

---

src/main/java/org/jabref/logic/l10n/Languages.java
src/main/resources/l10n/JabRef_el.properties
src/main/resources/l10n/Menu_el.properties
src/test/java/org/jabref/logic/l10n/LocalizationConsistencyTest.java

fixes https://github.com/JabRef/jabref/issues/2893.

Update Localization of Greek Translations

---

src/main/java/org/jabref/gui/entryeditor/FieldsEditorTab.java

Internal changes only related to the new Entry Editor:
Steps to reproduce original problem:
Add new empty database
Add entry from DOI 10.1016/j.jfineco.2013.10.005
Add another entry from same DIO
NPE Exception occured

Fix NPE when calling requestFocus on non selected field

---

src/main/java/org/jabref/gui/autocompleter/AppendPersonNamesStrategy.java
src/main/java/org/jabref/gui/autocompleter/AppendWordsStrategy.java
src/main/java/org/jabref/gui/autocompleter/AutoCompletionTextInputBinding.java
src/main/java/org/jabref/gui/autocompleter/BibEntrySuggestionProvider.java
src/main/java/org/jabref/gui/autocompleter/PersonNameSuggestionProvider.java
src/main/java/org/jabref/gui/autocompleter/StringSuggestionProvider.java
src/main/java/org/jabref/gui/autocompleter/SuggestionProvider.java
src/main/java/org/jabref/gui/fieldeditors/JournalEditor.java
src/main/java/org/jabref/gui/fieldeditors/SimpleEditor.java
src/main/java/org/jabref/gui/fieldeditors/SimpleEditorViewModel.java

Fix #2998: improve auto completion

---

src/test/java/org/jabref/logic/importer/fetcher/LibraryOfCongressTest.java

This test is currently failing with a 500 Error. I would suggest to add it to the allowed failures and open an issue.

Mark LibraryOfCongressTest as a fetcher test

---

.travis.yml

Add checkstyle as separate test to speedup feedback.

Add checkstyle as separate TravisCI test

---

circle.yml
jabref.install4j
scripts/prepare-install4j.sh

We need to check if the install4j migration did change something inside the installer.

Closes #3027 and updates install4j to v7

---

src/main/java/org/jabref/gui/FindUnlinkedFilesDialog.java
src/main/java/org/jabref/gui/IconTheme.java
src/main/java/org/jabref/gui/actions/ManageKeywordsAction.java
src/main/java/org/jabref/gui/externalfiles/SynchronizeFileField.java
src/main/java/org/jabref/gui/filelist/FileListEntryEditor.java
src/main/java/org/jabref/logic/citationstyle/CitationStyleCache.java
src/main/java/org/jabref/model/entry/identifier/Eprint.java
src/main/resources/l10n/JabRef_da.properties
src/main/resources/l10n/JabRef_de.properties
src/main/resources/l10n/JabRef_el.properties
src/main/resources/l10n/JabRef_en.properties
src/main/resources/l10n/JabRef_es.properties
src/main/resources/l10n/JabRef_fa.properties
src/main/resources/l10n/JabRef_fr.properties
src/main/resources/l10n/JabRef_in.properties
src/main/resources/l10n/JabRef_it.properties
src/main/resources/l10n/JabRef_ja.properties
src/main/resources/l10n/JabRef_nl.properties
src/main/resources/l10n/JabRef_no.properties
src/main/resources/l10n/JabRef_pt_BR.properties
src/main/resources/l10n/JabRef_ru.properties
src/main/resources/l10n/JabRef_sv.properties
src/main/resources/l10n/JabRef_tr.properties
src/main/resources/l10n/JabRef_vi.properties
src/main/resources/l10n/JabRef_zh.properties

Enable join and replace of keywords

---

src/main/resources/l10n/JabRef_fr.properties

Localization: French: Translation of new entries

---

CHANGELOG.md
src/main/java/org/jabref/gui/ReplaceStringDialog.java

Make Replace Strings work in bibtexkeyfield

---

CHANGELOG.md
src/main/java/org/jabref/gui/desktop/JabRefDesktop.java
src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java
src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditorViewModel.java

Don't call Paths.get on http link to prevent an exception
Fix #3165

Allow removal of online links from entry

---

src/main/resources/l10n/JabRef_ja.properties

Add two translated strings in JabRef_ja.properties

Add missing Japanese translation

---

src/main/resources/l10n/JabRef_ja.properties
src/main/resources/l10n/Menu_ja.properties

Removed spacing error and improved some translations

Improvement in Japanese translation

---

gradle/wrapper/gradle-wrapper.properties
src/test/java/org/jabref/model/database/event/AutosaveEventTest.java
src/test/java/org/jabref/model/entry/EntryLinkListTest.java

I want to  increase testcoverage. This is my first pull request with minor changed to get used to the contribution process.
none, too little changed.
Added tests for AutoEvent and EntryLinkList
2859 done, 139 failed, 6 ignored. Failed tests had nothing to do with my changed.

Testcoverage for AutoEvent and EntryLinkList

---

CHANGELOG.md
src/main/java/org/jabref/gui/help/AboutDialogController.java
src/main/java/org/jabref/gui/help/AboutDialogViewModel.java
src/main/resources/org/jabref/gui/help/AboutDialog.fxml

the textArea is initialized in controller.
I add a textArea to see the versionInfo

adding a textArea to see versionInfo into it.

---

src/main/resources/l10n/JabRef_fr.properties

Localization: French: Translation of a new string

---

src/test/java/org/jabref/logic/importer/fetcher/IsbnViaEbookDeFetcherTest.java

It seems as if the on-line reference changed by adding an author's first name.
Hence field "author" and "url" were updated to match our assertion again.

[minor change] Fix assertion failure due to change of online reference

---

src/test/java/org/jabref/logic/importer/fetcher/DBLPFetcherTest.java

fix dblp fetcher

---

src/main/resources/l10n/JabRef_tr.properties

Translated current remaining enteries to Turkish in JabRef_tr.properties  #3174

Add missing Turkish translation

---

src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java

Couldn't push to master directly for some reason.

Small fix in drag and drop handler of linked files

---

src/main/java/org/jabref/gui/actions/CopyBibTeXKeyAndLinkAction.java
src/main/java/org/jabref/logic/util/io/CiteKeyBasedFileFinder.java

Why do I get the following error when trying to push to master?!
>git checkout origin/master -b codecleanup
git push origin master
To https://github.com/JabRef/jabref.git
! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'https://github.com/JabRef/jabref.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Codecleanup

---

src/main/java/org/jabref/gui/entryeditor/SourceTab.java

Follow-up of #3366. I'll merge it directly since the changes are minimal.

Source tab: hide notification pane when code is correct again

---

CHANGELOG.md
src/main/java/org/jabref/gui/preftabs/AppearancePrefsTab.java

Fixes #3391 
Tested with Xubuntu 16.10

Don't list same look and feels more than once

---

src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java
src/test/java/org/jabref/logic/importer/fetcher/MathSciNetTest.java

Tests were failing since the url changed.

Fix MathSciNet fetcher

---

src/main/java/org/jabref/gui/BasePanel.java

Fixes #3347. No changelog entry since bug was introduced after release of 4.0.

Fix NPE when saving new file

---

build.gradle

Update guava from 23.2 -> 23.3

---

src/test/java/org/jabref/logic/l10n/LocalizationConsistencyTest.java
src/test/java/org/jabref/logic/l10n/LocalizationParser.java
src/test/java/org/jabref/logic/util/BracketedPatternTest.java
src/test/java/org/jabref/logic/xmp/XMPUtilTest.java

Fix some error prone warnings

---

src/test/java/org/jabref/logic/importer/fetcher/IsbnViaChimboriFetcherTest.java

fix isbn result from chimbori

---

build.gradle

Update junit-vintage-engine from 4.12.0 -> 4.12.1

---

CHANGELOG.md
src/main/java/org/jabref/gui/BasePanel.java
src/main/java/org/jabref/gui/importer/fetcher/ACMPortalFetcher.java
src/main/java/org/jabref/logic/net/URLDownload.java

Fix acm fetcher
Fixes #3500 
----

update user agent and change acm to https

---

xjc.gradle

Mark jaxb-xjc as not updateable

---

build.gradle

Can we update to this version @tobiasdiez?
Refs: https://github.com/JabRef/jabref/pull/3317

Update applicationinsights from 1.0.9 -> 2.0.0-BETA

---

scripts/prepare-install4j.sh

Adapt scripts/prepare-install4j.sh to JRE1.8.0_152

---

jabref.install4j
scripts/prepare-install4j.sh

Install4j jres 152

---

CHANGELOG.md
src/main/java/org/jabref/preferences/JabRefPreferences.java

Implements the workaround presented at https://github.com/JabRef/jabref/issues/3522#issuecomment-351046350.

Disable the autocompletion as default

---

.travis.yml

https://docs.travis-ci.com/user/languages/java/#Caching
----

Update travis cache config as recommned by the docs

---

src/test/java/org/jabref/logic/importer/fetcher/IsbnViaEbookDeFetcherTest.java
src/test/java/org/jabref/logic/importer/fetcher/MedlineFetcherTest.java

Merge as soon as build passes, since these are only minor changes.
----

Fix fetcher tests

---

src/main/java/org/jabref/gui/BasePanel.java

Fixes #3584
(No changelod needed as this is a followup from #3574 
----

Initialize previe before MainPanel to prevent NPEs on delete

---

src/main/java/org/jabref/gui/BasePanel.java

Not sure if this is the solution for  #3608
----

Fix NPE when changing entries between databases

---

build.gradle

Explicitly set jacoco version

---

src/main/java/org/jabref/JabRefMain.java
src/main/java/org/jabref/logic/util/JavaVersion.java
src/main/resources/l10n/JabRef_en.properties

Triggered by [discussion in the forum](http://discourse.jabref.org/t/java-error-on-jabref/974).
Build fails because I'm not sure whether I should add the empty translations to the other languages or not. @koppor ?!
----

Add installation directory to Java version error message

---

src/test/java/org/jabref/logic/importer/fetcher/IacrEprintFetcherTest.java

Fix ICAR fetcher test which resulted in build failure

---

build.gradle

I did a quick test with my LIbre Office installation and it works as expected.
----

Replace openoffice jars with libreoffice  jars

---

build.gradle
src/main/java/org/jabref/logic/importer/fetcher/IsbnFetcher.java

Exclude Fetcher Tests from main test 

---

CHANGELOG.md
src/main/java/org/jabref/logic/msbib/MSBibConverter.java

Fixes https://github.com/koppor/jabref/issues/284
Failing tests are already fixed in master (fetcher)
(I did not create a new test as I didn't want to mess up #3665 )
----

Export all fields with their latex free equivalent for MS Office

---

src/test/resources/org/jabref/logic/exporter/MsBibExportFormatTestLatexFree.bib
src/test/resources/org/jabref/logic/exporter/MsBibExportFormatTestLatexFree.xml

add Office xml test for latex free fields

---

src/main/java/org/jabref/Globals.java
src/main/java/org/jabref/gui/BasePanel.java
src/main/java/org/jabref/gui/ClipBoardManager.java
src/main/java/org/jabref/gui/DefaultInjector.java
src/main/java/org/jabref/gui/DragAndDropDataFormats.java
src/main/java/org/jabref/gui/DuplicateSearch.java
src/main/java/org/jabref/gui/actions/CopyBibTeXKeyAndLinkAction.java
src/main/java/org/jabref/gui/collab/EntryAddChangeViewModel.java
src/main/java/org/jabref/gui/externalfiles/DroppedFileHandler.java
src/main/java/org/jabref/gui/importer/EntryFromFileCreatorManager.java
src/main/java/org/jabref/gui/importer/ImportInspectionDialog.java
src/main/java/org/jabref/gui/importer/actions/AppendDatabaseAction.java
src/main/java/org/jabref/gui/maintable/MainTable.java
src/main/java/org/jabref/gui/mergeentries/MergeEntriesDialog.java
src/main/java/org/jabref/gui/undo/UndoableInsertEntry.java
src/main/java/org/jabref/logic/bibtex/BibEntryWriter.java
src/main/java/org/jabref/pdfimport/PdfImporter.java

Reimplement copy and paste of entries

---

CONTRIBUTING.md

I was reading through the file and I noticed a simple typo.

Fixed typo, mayor to major

---

src/main/java/org/jabref/gui/DefaultInjector.java

This should fix the annotation tab in the new maintable.
----

Fix annotation tab

---

src/main/java/org/jabref/gui/EntryTypeDialog.java

This fixes https://github.com/koppor/jabref/issues/283
----

Allow spaces in DOIs

---

CHANGELOG.md
src/main/java/org/jabref/gui/EntryTypeDialog.java
src/main/java/org/jabref/preferences/JabRefPreferences.java

I have added a new preference that stores that last used id fetcher.

Default ID type in the ID-based entry generator

---

src/main/resources/xjc/mods/mods-3-6.xsd
src/main/resources/xjc/mods/mods-3-7.xsd
src/main/resources/xjc/mods/mods-binding.xjb
src/main/resources/xjc/mods/xlink.xsd
src/main/resources/xjc/mods/xml.xsd
xjc.gradle

Fixes #3737 
Not sure if this works and is the way to go.
If we need to update the mods schema we need to alter the paths again.
Also, I don't know if we may inline this here.

Inline loc.org xsds

---

src/main/java/org/jabref/Globals.java

Don't call Telemetry when headless mode
Fixes #3754 
----

Make JabRef cli work in headless mode

---

src/main/resources/l10n/JabRef_de.properties
src/main/resources/l10n/JabRef_fr.properties
src/main/resources/l10n/JabRef_ja.properties

[WIP] New Crowdin translations

---

src/main/java/org/jabref/gui/actions/JabRefAction.java

Adds telemetry tracking to every menu/toolbar action.
----

Add telemetry to track every action

---

src/main/java/org/jabref/logic/l10n/Languages.java

Addtagaloglang

---

src/main/resources/l10n/JabRef_es.properties

Added a couple of missing Spanish localized texts
----

Add Spanish translations

---

docs/adr/0000-use-markdown-architectural-decision-records.md
docs/adr/0001-use-crowdin-for-translations.md
docs/adr/0002-use-slf4j-for-logging.md
docs/adr/index.md
docs/adr/template.md

This updates [MADR](https://adr.github.io/madr/) to its latest version 2.0.3. Also update the made ADRs to MADR 2.0.3. Add a new option to "Use Crowdin".

Update to MADR 2.0.3

---

src/main/java/org/jabref/gui/BasePanel.java
src/main/java/org/jabref/gui/DialogService.java
src/main/java/org/jabref/gui/exporter/ExportToClipboardAction.java
src/main/java/org/jabref/gui/openoffice/DetectOpenOfficeInstallation.java
src/main/java/org/jabref/gui/search/GlobalSearchBar.java
src/test/java/org/jabref/gui/search/ContainsAndRegexBasedSearchRuleDescriberTest.java
src/test/java/org/jabref/gui/search/GrammarBasedSearchRuleDescriberTest.java
src/test/java/org/jabref/gui/search/TextFlowEqualityHelper.java

will merge directly. Push on maintable-beta was not possible for some reason....
----

Bunch of smaller improvements

---

src/main/java/org/jabref/gui/externalfiles/DownloadExternalFile.java
src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java
src/main/java/org/jabref/logic/importer/fetcher/DoiResolution.java
src/main/java/org/jabref/logic/net/URLDownload.java

- Increase timeout as DOI resolution often fails from `5000`to `10000`
- Return DOI page if it directly redirects to a PDF (good guess that it is the fulltext then)

Improve DOI resolution fetcher

---

src/main/java/org/jabref/logic/integrity/FieldCheckers.java
src/main/java/org/jabref/model/entry/BibtexSingleField.java
src/main/java/org/jabref/model/entry/InternalBibtexFields.java

Monthfiled in patent should be treated same as month (IEEETRAN)

---

src/main/java/org/jabref/gui/BasePanel.java
src/main/java/org/jabref/gui/FindUnlinkedFilesDialog.java
src/main/java/org/jabref/gui/JabRefFrame.java
src/main/java/org/jabref/gui/cleanup/FieldFormatterCleanupsPanel.java
src/main/java/org/jabref/gui/collab/ChangeScanner.java
src/main/java/org/jabref/gui/copyfiles/CopyFilesAction.java
src/main/java/org/jabref/gui/entryeditor/EntryEditor.java
src/main/java/org/jabref/gui/externalfiles/SynchronizeFileField.java
src/main/java/org/jabref/gui/externalfiles/TransferableFileLinkSelection.java

Merge identical methods

---

src/main/java/org/jabref/gui/BasePanel.java
src/main/java/org/jabref/gui/FindUnlinkedFilesDialog.java
src/main/java/org/jabref/gui/JabRefFrame.java
src/main/java/org/jabref/gui/cleanup/FieldFormatterCleanupsPanel.java
src/main/java/org/jabref/gui/collab/ChangeScanner.java
src/main/java/org/jabref/gui/copyfiles/CopyFilesAction.java
src/main/java/org/jabref/gui/entryeditor/EntryEditor.java
src/main/java/org/jabref/gui/externalfiles/SynchronizeFileField.java
src/main/java/org/jabref/gui/externalfiles/TransferableFileLinkSelection.java
src/main/java/org/jabref/model/entry/BibtexSingleField.java
src/main/java/org/jabref/model/entry/InternalBibtexFields.java

Debug refactoring

---

build.gradle

merge if green
Junit 5.1.0 -> 5.1.1
mockito 2.17.0 -> 2.18.0
checkstyle 8.8 -> 8.9
----

Update dependencies for junit, mockito and checkstyle

---

src/main/java/org/jabref/gui/importer/fetcher/IEEEXploreFetcher.java
src/main/java/org/jabref/logic/importer/fetcher/IEEE.java
src/test/java/org/jabref/logic/importer/fetcher/IEEETest.java
src/test/resources/testbib/crossref.bib
src/test/resources/testbib/jabref-authors.bib

IEEE tests are broken, but they were before. needs to be fixed.
Fixes #3930

[WIP] Replace all IEEE URLs with https #3930

---

src/main/java/org/jabref/logic/integrity/PersonNamesChecker.java
src/test/java/org/jabref/logic/integrity/PersonNamesCheckerTest.java
src/test/java/org/jabref/model/entry/AuthorListTest.java

Corporate names in brackets are valid corporate authors

---

src/main/java/org/jabref/gui/maintable/CellFactory.java
src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java

This fixes #3860 
URL Column now shows URL or DOI correctly and opens on click.
----

Fixed Url column

---

jabref.install4j
scripts/prepare-install4j.sh

Update Install4j Config to 7.0.4 and JREs to 1.8.0_172

---

src/main/java/org/jabref/model/entry/BibEntry.java

Otherwise typing in the date field results in a bunch of logged warning messages.
----

Change date parsing warning to debug statement

---

src/main/java/org/jabref/gui/SidePaneManager.java

Fix that sometimes an empty side pane is shown

---

build.gradle

Change version to 5.0 dev

---

CONTRIBUTING.md

I discovered https://guides.github.com/introduction/flow/index.html and https://github.com/joelparkerhenderson/git_commit_message. I thought, it would be good to integrate. 😇

Refine links

---

src/main/java/org/jabref/logic/importer/EntryBasedParserFetcher.java
src/main/java/org/jabref/logic/importer/FulltextFetchers.java
src/main/java/org/jabref/logic/importer/IdBasedParserFetcher.java
src/main/java/org/jabref/logic/importer/SearchBasedParserFetcher.java

Improve error message for fetchers

---

src/test/java/org/jabref/gui/journals/ManageJournalAbbreviationsViewModelTest.java

Sorry for the noise, for some reason I no longer can push directly to master...
----

Fix reference to junit pioneer

---

build.gradle

RichTextFX will no longer be maintained
https://github.com/FXMisc/RichTextFX/issues/768
@JabRef/developers  Tagging this with devcall has we need to discuss if we have any bugs left regarding this and if it is compatible with java 9 @florian-beetz 
----

Update to latest release of richtextfx

---

src/test/java/org/jabref/logic/importer/fetcher/IsbnViaChimboriFetcherTest.java

Adapt the url of returned data
just checking if ci server still works
----

Fix isbn chimbori test

---

src/main/java/org/jabref/model/FieldChange.java

This is a comment that describes the purpose of a class.
----

Added a comment for the purpose of the class

---

src/main/java/org/jabref/gui/collab/ChangeScanner.java
src/main/java/org/jabref/gui/collab/DatabaseChangeMonitor.java
src/main/java/org/jabref/gui/exporter/SaveDatabaseAction.java
src/main/java/org/jabref/gui/mergeentries/MergeEntries.java
src/main/java/org/jabref/gui/mergeentries/MergeEntriesDialog.java

Fixes #4233
fix fx thread error
convert file to path
----

fix npe in Merge entries dialog

---

build.gradle

Update junit-pioneer from 0.2.1 -> 0.2.2

---

src/main/java/org/jabref/gui/preferences/AppearancePrefsTab.java

That thrown NPE if theme not set.

fix NPE in AppearancePreferenceTab

---

src/main/java/org/jabref/gui/maintable/MainTable.css

Make rank image narrower

---

src/test/java/org/jabref/logic/exporter/ModsExportFormatTestFiles.java
src/test/resources/org/jabref/logic/exporter/ModsExportFormatTestAllFields.xml

[#4272](https://github.com/JabRef/jabref/issues/4272)
----

Fixes for all mods exporter tests

---

src/main/java/org/jabref/gui/preferences/PreferencesDialog.java
src/main/java/org/jabref/gui/preferences/PreferencesFilterDialog.fxml
src/main/java/org/jabref/gui/preferences/PreferencesFilterDialog.java

Convert "Show preferences" dialog to JavaFX

---

build.gradle

Use 'junit-jupiter' aggregator module

---

src/main/java/org/jabref/preferences/JabRefPreferences.java

Closes https://github.com/JabRef/jabref/issues/4585.
----

Disable rank column by default

---

src/main/java/org/jabref/gui/preferences/FileTab.java

Fix #4703: Newline format couldn't be changed

---

src/main/java/org/jabref/logic/msbib/MsBibAuthor.java
src/test/java/org/jabref/logic/msbib/MsBibAuthorTest.java

Adding "von" part to Author's last name when exporting to MS Office 2007

---

src/main/java/org/jabref/gui/entryeditor/SourceTab.java

Adding support for input methods

---

src/main/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGenerator.java
src/main/java/org/jabref/logic/bibtexkeypattern/BracketedPattern.java
src/test/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGeneratorTest.java
src/test/java/org/jabref/logic/bibtexkeypattern/MakeLabelWithDatabaseTest.java

Reverts JabRef/jabref#4713
Wrong merge

Revert "Fix: bibkey generated does not handle diacritics"

---

src/main/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGenerator.java
src/main/java/org/jabref/logic/bibtexkeypattern/BracketedPattern.java
src/test/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGeneratorTest.java
src/test/java/org/jabref/logic/bibtexkeypattern/MakeLabelWithDatabaseTest.java

Revert "Revert "Fix: bibkey generated does not handle diacritics""

---

src/jmh/java/org/jabref/benchmarks/Benchmarks.java

Code optimized and created a reusable method to get writer output

---

CHANGELOG.md
src/main/java/org/jabref/gui/importer/ImportEntriesDialog.java

Fixes [#4755](https://github.com/JabRef/jabref/issues/4755)
----

Enable import button only if entry selected

---

src/main/java/org/jabref/gui/entryeditor/FieldsEditorTab.java
src/main/java/org/jabref/gui/fieldeditors/BibtexKeyEditor.fxml

Implements UI change suggested in [#4687](https://github.com/JabRef/jabref/issues/4687)
fixes #4687
----

Shortens text fields in Required Fields Tab

---

src/main/java/org/jabref/JabRefException.java
src/main/java/org/jabref/JabRefMain.java

While looking at the code, I observed obsolete documentation patterns which did not confine to the Documentation Guidelines.
I changed the pattern of commenting and also added a comment for the logger.
----

Improved and Added Documentation

---

build.gradle

update to latest gradle plugins

---

README.md

Added table of contents to the Readme

Readme TOC

---

src/main/java/org/jabref/gui/entryeditor/OtherFieldsTab.java

Fix order of other fields

---

src/main/java/org/jabref/gui/customentrytypes/CustomizeEntryAction.java
src/main/java/org/jabref/gui/customentrytypes/EntryTypeCustomizationDialog.java
src/main/java/org/jabref/gui/customentrytypes/FieldSetComponent.java

fix wrong package

---

src/test/resources/org/jabref/logic/exporter/ModsExportFormatTestAllFields.xml
src/test/resources/org/jabref/logic/exporter/ModsExportFormatTestBook.xml
src/test/resources/org/jabref/logic/exporter/ModsExportFormatTestMultipleEntries.xml
src/test/resources/org/jabref/logic/exporter/ModsExportFormatTestOnlyRequiredFields.xml
src/test/resources/org/jabref/logic/exporter/ModsExportFormatTestTotalPages.xml

fix mods tests

---

build.gradle

Add rule to ignore snapshot updates in the dependencyUpdates

---

src/main/java/org/jabref/gui/preferences/GeneralTabViewModel.java

fix: database mode is always saved as Biblatex

---

src/main/java/org/jabref/gui/mergeentries/DiffHighlighting.java
src/main/java/org/jabref/logic/journals/AbbreviationParser.java
src/main/java/org/jabref/logic/journals/JournalAbbreviationLoader.java

Fix diff dialog missing spaces

---

src/main/java/org/jabref/model/entry/field/FieldFactory.java

Add DOI, URL, Eprint  field to general tab layout

---

.dependabot/config.yml

With this change dependabot should propose PRs if one of the git submodules is updated (i.e. the citation styles).
----

Let dependabot update git submodules

---

.gitmodules
eclipse.gradle
src/main/java/org/jabref/JabRefMain.java

Revert "[WIP] Get JabRef running in eclipse"

---

snap/snapcraft.yaml

add desktop gtk 3

---

snap/snapcraft.yaml

remove desktop gtk3

---

snap/snapcraft.yaml

See https://snapcraft.io/docs/snapcraft-yaml-reference
----

Add MIT license field

---

.github/workflows/cleanup_pr.yml

Remove the folder on build server once PR is merged

---

.github/workflows/deployment.yml

Set checkout  fetch depth to 1

---

.github/workflows/deployment.yml
build.gradle

Will merge if build passes.
----

Update paths to jpackage
