.github/workflows/deployment.yml
Remove the "build/distribution" part of the folder structure in the zip file.
----
=> Fix path in zip file

build.gradle
=> Make Windows build runnable from console

CHANGELOG.md
=> Fixed Typo Mistakes and Fixed Grammar Mistakes

build.gradle
=> Upgrade to JavaFX 13

build.gradle
=> Update gradle version plugin

.github/workflows/deployment.yml
Something is not working...
It is not finding the snap file.
This uses a single docker command
----
=> Snapcraft docker

.github/workflows/deployment.yml, .travis.yml, build.gradle
First test of the build using openjdk 12. Works for me locally
=> [WIP] Test JDK12

src/main/java/org/jabref/gui/preferences/PreviewTab.fxml
Fixes bug in #5451 
Should be pretty self-explanatory.
----
=> Fix misplaced Checkbox in Prefs/PreviewTab

src/main/java/org/jabref/logic/citationstyle/CitationStyle.java
waiting for the installer
----
=> Quick fix CSL errors

external-libraries.txt
[#5523](https://github.com/JabRef/jabref/issues/5523)
----
=> Fix typos in external-libraries.txt file

build.gradle
=> Reenable stack trace to debug windows build

.github/workflows/deployment.yml
Let's hope nothing breaks this time
merge if green
----
=> Udpate jpackage to 1-67

.github/workflows/deployment.yml
=> Add gradle caching for github actions

buildres/linux/org.jabref.jabref.json, buildres/windows/jabref.json
=> Rename JabFox to JabRef Browser Extension

build.gradle
=> Fix jpackage build

src/test/java/org/jabref/logic/importer/fetcher/IsbnFetcherTest.java
Somehow, the result by the fetchers changed. This just adapts
=> Fix expected result

build.gradle
Check if it works
Refs https://github.com/java-diff-utils/java-diff-utils/issues/60
----
=> Update java diff utils to 4.5 snapshot

build.gradle
=> revert detailed test output to failed only

buildres/linux/postrm
This should have been changed..
It was edited as an echo command to verify the files it was looking for.
----
=> Change postrm to remove json files

src/main/java/org/jabref/logic/l10n/Language.java, src/main/resources/l10n/JabRef_pt.properties
Portuguese language from europe was added, as it has some differences in relation to portuguese from Brazil.
There were also new translations.
----
=> European Portuguese

.github/workflows/deployment.yml
=> Set dev to false on tag builds

src/main/java/org/jabref/logic/importer/WebFetchers.java, src/test/java/org/jabref/logic/importer/WebFetchersTest.java, src/test/java/org/jabref/logic/importer/fetcher/ACMPortalFetcherTest.java
See https://github.com/JabRef/jabref/issues/5804 for details
=> Disable ACM Fetcher

src/main/java/org/jabref/gui/entryeditor/SourceTab.java
=> Added update method to typePropertyListeners

CHANGELOG.md, build.gradle, src/main/java/org/jabref/logic/importer/Parser.java, src/main/java/org/jabref/logic/util/io/FileNameCleaner.java, src/test/java/org/jabref/logic/util/io/FileNameCleanerTest.java
=> Fix invalid filename with curly braces and fix wrong encoding in parser

src/main/java/org/jabref/gui/util/FieldsUtil.java, src/main/resources/l10n/JabRef_en.properties
Names of special fields were not translated in preferences.
fixes #5701
=> Translation for SpecialField names in preferences

gradle/wrapper/gradle-wrapper.properties, gradlew.bat
Changelog: https://docs.gradle.org/6.2.1/release-notes.html
=> Update gradle from 6.2 to 6.2.1

src/main/java/org/jabref/Globals.java
@tobiasdiez Can you confirm that this is fixed and the code no longer needed?
See https://github.com/Microsoft/ApplicationInsights-Java/issues/662
=> Shutdown should be fixed since v2.1.2

src/main/java/org/jabref/gui/BasePanel.java
When I create a new library, it is created, but an exception is shown:
Fixes an issue introduced at #6056.
=> Fix exception when creating a new library

docs/teaching.md
I offered Open Source courses in which JabRef was one of the "objects." 
Created two items in the teaching.md to add these courses.
=> Added Courses offered at NAU and UTFPR

docs/teaching.md
Add information about the OSS course in Harbin China to the "JabRef as teaching object" site.
=> Add course in China

src/main/java/org/jabref/logic/formatter/bibtexfields/HtmlToUnicodeFormatter.java, src/main/java/org/jabref/logic/layout/format/HTMLChars.java, src/main/java/org/jabref/logic/openoffice/OOPreFormatter.java
Found by IntelliJ: https://www.jetbrains.com/help/phpstorm/regexp-redundant-character-escape.html
<!--
=> Remove redundant RegExp character replace

CHANGELOG.md, src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java, src/main/java/org/jabref/gui/util/comparator/PriorityFieldComparator.java
This PR is a follow up to #6222
=> Fix sort by priority (#6222)

CHANGELOG.md, buildres/mac/Info.plist, buildres/mac/Info.plist.template
=> Try with info.plist.template also

buildres/linux/JabRef.desktop
Changed StartupWMClass entry in /buildres/linux/JabRef.desktop from org-jabref-JabRefMain to org.jabref.JabRefMain.
Fixes #6396
=> Fix StartupWMClass

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefFrame.java
=> Restore some missing keyboard shortcuts

CHANGELOG.md, src/main/java/org/jabref/gui/edit/EditAction.java
Addition to the pull #6438, I'm sorry for making a mistake. I should've add a `break` after the switch statement. Please take a look again.
=> Addition to the early pull #6438

CHANGELOG.md, src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java, src/main/java/org/jabref/gui/util/comparator/NumericFieldComparator.java, src/test/java/org/jabref/gui/util/comparator/NumericFieldComparatorTest.java
@calixtus  I think you forgot to merge the modified branch in master
=> Dimitra 6349

src/main/java/org/jabref/gui/actions/ActionHelper.java
otherwise it will be interpreted as path which obiously fails
Fixes #6507
~~- [ ] Change in CHANGELOG.md described (if applicable)~~ Dev version only
=> Return true in action helper if file is online link

docs/teaching.md, src/main/java/org/jabref/preferences/JabRefPreferences.java
The error was introduced in #6518 and reported in gitter
=> FIx NPE in loading save order when starting jabref

docs/guidelines-for-setting-up-a-local-workspace.md
Guidelines updated for Eclipse otherwise the configuration cannot be run under Linux.
=> Guidelines updated for Eclipse

CHANGELOG.md, src/main/java/org/jabref/gui/libraryproperties/LibraryPropertiesDialogViewModel.java
Fixes #6541 
Followup from #6570
=> Fix library marked as changed when opening library properties

snap/snapcraft.yaml
This should make it visible in the info shown in the software center.
It might be a good idea to also describe the process for connecting browsers,
or redirect to the relevant readme in github
=> add removable-media info in snap description

CHANGELOG.md, src/main/java/org/jabref/gui/customizefields/CustomizeGeneralFieldsDialogViewModel.java
Fixes #6604 by correcting the list of unwanted characters
=> Fixed error when specifying general fields by correcting unwanted characters list

docs/advanced-reading/jpackage.md
I just fixed the styling so CI should succeed.
=> (docs) fix styling

src/main/java/org/jabref/gui/JabRefDialogService.java, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/exporter/ExportCustomizationDialogView.java, src/main/java/org/jabref/gui/importer/ImportCustomizationDialog.java, src/main/java/org/jabref/gui/texparser/ParseLatexDialogView.java
Fixes #6692, renamed listBind to bindContent where it was used
=> fixed issue 6692

.github/workflows/snap.yml
=> change snap action from obsoloete to newer

.github/workflows/refresh-csl-subtrees.yml
=> Update CSL only on master

src/test/java/org/jabref/model/entry/BibEntryTypesManagerTest.java
Fixed small issue about forgotten biblatex test.
=> Fix biblatex software test

src/main/java/org/jabref/logic/TypedBibEntry.java
In another context, I stumbled upon TypedBibEntry. I fixed some typos and simplified the constructor code. (No Optionals as parameters)
=> Change code style in TypedBibEntry

src/main/java/org/jabref/gui/cleanup/CleanupPresetPanel.java, src/main/java/org/jabref/gui/commonfxcontrols/FieldFormatterCleanupsPanel.java
Follow up ref https://github.com/JabRef/jabref/pull/6788#pullrequestreview-475866233
=> Fix cleanup formatters to avoid race conditions

.github/workflows/deployment.yml
=> Downgrade to java 14 for win and linux

.github/workflows/check-links.yaml
Just internal changes - no need to review
=> Simplify check-links.yaml (markdown-link-check)

src/main/java/org/jabref/logic/util/BuildInfo.java
Fixes typo in key. At least IntelliJ minded.
=> Fixed typo in BuildInfo

src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/actions/ActionFactory.java, src/main/java/org/jabref/gui/edit/EditAction.java, src/main/java/org/jabref/gui/maintable/MainTable.java
Fixes #6293
Needs testing unter linux
=> Refactor edit action

.github/workflows/deployment.yml
run notarization only om master branch
=> Separate signing and notarizing

src/main/resources/l10n/JabRef_en.properties
As requested in  https://github.com/JabRef/jabref/pull/6849#issuecomment-685923096_
=> "Find unlinked files": removal on entry in en l10

docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace.md
=> Update run configuration for IDE

src/main/java/org/jabref/logic/importer/util/ShortDOIService.java
This addresses one of the errors in the fetcher tests as run by the CI (see #6369). Here is and [example of a test failure](https://github.com/JabRef/jabref/runs/1035408706?check_suite_focus=true#step:6:253).
=> Fix a fetcher test for the ShortDOIService

config/README.md, docs/README.md, docs/adr.md, docs/adr/0004-use-mariadb-connector.md, docs/adr/0006-only-translated-strings-in-language-file.md, docs/adr/0008-use-public-final-instead-of-getters.md, docs/adr/0011-test-external-links-in-documentation.md, docs/adr/0013-add-native-support-biblatex-software.md, docs/adr/0014-separate-URL-creation-to-enable-proper-logging.md, docs/adr/0015-support-an-abstract-query-syntax-for-query-conversion.md, docs/adr/0016-mutable-preferences-objects.md, docs/adr/0017-allow-model-access-logic.md, docs/adr/template.md, docs/advanced-reading/fetchers.md, docs/getting-into-the-code/code-howtos.md, docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace.md, docs/readings-on-coding/tools.md, docs/teaching.md
This PR fixes several typos and some grammatical errors.
=> Fix grammar and typos

build.gradle
I did not test all dialogs but most of the thing seeemed to work.
Changelog: https://github.com/openjdk/jfx/blob/jfx15/doc-files/release-notes-15.md
Fixes #7017 
Fixes #4947 
Probably also fixes #6086 
Probably also fixes #5866
=> Update to javafx15

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java, src/test/java/org/jabref/gui/groups/GroupTreeViewModelTest.java
=> Add selection of 'All Entries' group on start-up

src/main/java/org/jabref/gui/exporter/SaveDatabaseAction.java, src/main/java/org/jabref/gui/shared/SharedDatabaseUIManager.java
follow up to #6129 
fixes #7053
=> Fixed setting title of saved new library

build.gradle, src/main/java/module-info.java
Reverts JabRef/jabref#7090
afterburner fx needs those
=> Revert deletion of jakarta  annotation 

src/main/java/org/jabref/gui/groups/GroupTreeView.java, src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java
=> Fixes NPE on opening GroupPanel

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/SourceTab.java, src/main/java/org/jabref/gui/keyboard/CodeAreaKeyBindings.java
=> Fix saving in codeArea without leaving the field

build.gradle
=> remove jython dependency

build.gradle
=> Revert "remove jython dependency"

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefFrame.java
=> Changed context menu item order for library tabs

src/main/java/org/jabref/preferences/JabRefPreferences.java
Improvements for integrity and coherence of the entry preview (in the context of #7083; in addition to #7093)
=> Improvements for Entry Preview (in the context of #7083 and in addition to #7093)

src/main/java/org/jabref/model/entry/identifier/DOI.java, src/test/java/org/jabref/model/entry/identifier/DOITest.java
Fixes a checkstyle issue of #7257.
=> Improved detection of long DOI's within text

CHANGELOG.md, src/main/java/org/jabref/logic/msbib/MSBibEntry.java, src/test/resources/org/jabref/logic/exporter/MsBibExportFormatTest1.xml, src/test/resources/org/jabref/logic/exporter/MsBibExportFormatTestDateAcessed.xml, src/test/resources/org/jabref/logic/exporter/MsBibUrlDate.xml
=> Export full month name instead of number in ms office

snap/snapcraft.yaml
=> Update snapcraft source url

.github/workflows/refresh-csl-subtrees.yml, .github/workflows/refresh-journal-lists.yml
Our push actions does not work for protected branches, therefore I decided to use a PR
=> Create PR as push does not work for protected

.github/workflows/refresh-csl-subtrees.yml, .github/workflows/refresh-journal-lists.yml
=> Fixjournalabbrev

src/main/java/org/jabref/gui/EntryTypeView.java
Do not show an error message if there is no error
Fixes #7020
=> Fixed validation before typing in new entry dialog #7020

docs/adr.md
=> Doc: Add recent ADR to ADR's list

CHANGELOG.md, src/main/java/org/jabref/gui/ClipBoardManager.java
#2292  Pasted `arxivId` creates new BibEntry
=> add ability to insert arxivId

CHANGELOG.md, src/main/resources/resource/layout/simplehtml.layout
Report from forum
https://discourse.jabref.org/t/problem-with-exporting-techreport-phdthesis-mastersthesis-to-html/2634
=> Fix school/instituation is printed twice

.github/workflows/automerge.yml, .github/workflows/update-gradle-wrapper.yml
This adds an auto-update for gradle by using https://github.com/gradle-update/update-gradle-wrapper-action.
I quote from the action's manual for the Y:
> Why should I use this action?
>
> Gradle Wrapper is the recommended way to setup Gradle in your project. The Wrapper is a script that downloads and invokes a declared Gradle version. By checking the Wrapper into version control you make the build process more standardised, easy and reliable.
>
> Maintaining dependencies up-to-date is regarded as a good practice, and the build system files should be no exception. Unfortunately, often times developers add the Wrapper to the project repository once and just forget about it.
>
> The Update Gradle Wrapper Action aims to help keeping Gradle projects on GitHub polished to high standards and to …
=> Add "Update Gradle Wrapper Action"

.github/workflows/deployment.yml
=> Revert "Skip Mac OS build if secret not present"

.github/workflows/automerge.yml, .github/workflows/refresh-csl-subtrees.yml
Follow-up to https://github.com/JabRef/jabref/pull/7306. I missed committing the update when `cp` modified a file
=> Fix CSL update

build.gradle, src/test/java/module-info.test
Refs https://github.com/java9-modularity/gradle-modules-plugin/issues/188#issuecomment-831561930
=> Update to java modularity plugin 1.8.3

.github/workflows/deployment.yml, .github/workflows/tests.yml, docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace.md
=> use java 16 as build environment for deployment

src/test/java/org/jabref/logic/formatter/bibtexfields/UnicodeToLatexFormatterTest.java
=> fix checkstyle in unit test

src/test/java/org/jabref/model/pdf/FileAnnotationTest.java
Add unit test to FileAnnotationTest.java to cover previously uncovered method abbreviateAnnotationName().
=> Add unit test for abbreviateAnnotationName() to FileAnnotationTest.java

.github/PULL_REQUEST_TEMPLATE.md
There are contributors who have difficulties with advanced markdown. This PR tries to refine the instructions.
=> Add easier how-to for checklist

build.gradle
=> Revert "Bump org.eclipse.jgit from 5.11.1.202105131744-r to 5.12.0.202106070339-r"

eclipse.gradle
=> change eclipse default output dir

CHANGELOG.md, src/main/java/org/jabref/gui/EntryType.fxml, src/main/java/org/jabref/gui/commonfxcontrols/FieldFormatterCleanupsPanel.fxml, src/main/java/org/jabref/gui/contentselector/ContentSelectorDialog.fxml, src/main/java/org/jabref/gui/customentrytypes/CustomizeEntryTypeDialog.fxml, src/main/java/org/jabref/gui/edit/MassSetFieldsDialog.java, src/main/resources/l10n/JabRef_en.properties
=> add missing l10n

buildres/linux/JabRef.desktop
=> Change WM_CLASS to jabref

.github/workflows/refresh-journal-lists.yml
=> fix workflow

.github/workflows/refresh-journal-lists.yml, buildSrc/src/main/groovy/org/jabref/build/JournalAbbreviationConverter.groovy
=> Fixjournalworkflow

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java
Fixes #7912 and fixes #7930 (duplicate)
=> Fix broken GroupDialog

src/main/java/org/jabref/logic/importer/fileformat/PdfContentImporter.java
Identifiers found in PDFs will be fetched by the PdfMergeMetadataImporter (7947).
This way, we can fetch identifiers found by the other Pdf-Importers as well (Grobid, embedded-bib, XMP...)
=> Remove DOI lookup from PdfContentImporter

CHANGELOG.md, src/main/java/org/jabref/gui/linkedfile/LinkedFilesEditDialogViewModel.java
=> Fix exception when editing URL file

src/main/java/org/jabref/gui/util/DefaultTaskExecutor.java, src/main/java/org/jabref/logic/pdf/search/indexing/IndexingTaskManager.java, src/main/java/org/jabref/logic/pdf/search/indexing/PdfIndexer.java
=> Fix output when closing JabRef while indexing

build.gradle
https://gluonhq.com/javafx-17-is-here/
Seems to work without problems so far
=> Update to javafx 17

.github/workflows/deployment.yml, .github/workflows/tests.yml, build.gradle
=> increase memory for gradle

build.gradle, gradle.properties
In reference to https://github.com/checkstyle/checkstyle/issues/10792, I would like to test this change against jabref's github CI before proceeding with investigation on Checkstyle's side.
Edit: checkstyle gradle build has passed, @Siedlerchr please take a look
=> bump checkstyle version to 9.0

src/main/java/org/jabref/model/groups/SearchGroup.java, src/main/java/org/jabref/model/search/rules/GrammarBasedSearchRule.java, src/test/java/org/jabref/logic/importer/util/GroupsParserTest.java, src/test/java/org/jabref/model/groups/SearchGroupTest.java
Fixes #8087 
Add some more tests
Add toString method
=> Fixes exception in fulltext search on invalid search

build.gradle
Fixes some issues with menus and bidirectional bindings
=> udpate to javafx 17.0.0.1

build.gradle
=> Update javafx to 17.0.1

src/main/java/org/jabref/preferences/SearchPreferences.java
Fixes #8230
Fixes #8234
no changelog required as this is a followup from the search perferences refactoring
=> Fix exception for search flags

CHANGELOG.md, src/main/java/org/jabref/gui/preferences/preview/PreviewTabViewModel.java, src/main/java/org/jabref/gui/preview/PreviewViewer.java
=> Fix exception on preview style edit and selection

build.gradle
=> Update Controlsfx to 11.1.1

CHANGELOG.md, src/main/java/org/jabref/gui/preview/PreviewViewer.java
=> Fix NPE when clicking on preview

CHANGELOG.md, src/main/java/org/jabref/gui/collab/EntryChangeViewModel.java
=> FIX NPE on Merge Dialog

src/main/java/org/jabref/gui/theme/ThemeManager.java
=> Quickfix for edge case in theme system

src/main/java/org/jabref/logic/bibtex/BibEntryWriter.java, src/main/java/org/jabref/logic/exporter/BibDatabaseWriter.java, src/main/java/org/jabref/logic/exporter/BibtexDatabaseWriter.java, src/main/java/org/jabref/logic/importer/fileformat/BibtexImporter.java, src/main/java/org/jabref/logic/importer/fileformat/BibtexParser.java, src/test/java/org/jabref/logic/exporter/BibtexDatabaseWriterTest.java, src/test/java/org/jabref/logic/importer/fileformat/BibtexImporterTest.java
Small code comment improvements. Submitting for review as I will rely on these on multiple PRs.
=> Improve code comments

src/test/java/org/jabref/logic/exporter/BibtexDatabaseWriterTest.java, src/test/resources/org/jabref/logic/importer/fileformat/encoding-windows-1252-with-header.bib
Adds an additional test to https://github.com/JabRef/jabref/pull/8424
=> Add roundtrip test

build.gradle
=> Update to Javafx 17.02

src/main/java/org/jabref/gui/JabRefFrame.java
Fixes https://github.com/JabRef/jabref/issues/7614#issuecomment-1021577802
=> Potential fix for Library tab issue

src/test/java/org/jabref/logic/importer/fetcher/RfcFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/SpringerFetcherTest.java
=> Fixsomefetchers

src/main/java/org/jabref/logic/shared/DBMSSynchronizer.java
Updates by the DBMSProcessor were not handled in a background task and blocked the GUI until all changes were synced. 
Fixes #8485 by wrapping _DBMSSynchronizer.listen(FieldChangedEvent event)_ actions to sync databases into a background task. Events that cause GUI changes to take place were posted within the JavaFX Thread.
=> Handling of field change events as background task

CHANGELOG.md, src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/logic/pdf/search/indexing/IndexingTaskManager.java
=> Revert "Fix for Indexing stopping while having library modification"

build.gradle, src/main/java/module-info.java
Fixes #8566
jpackage build works for me a well
=> Fix medline import due to mising module

src/main/resources/l10n/JabRef_en.properties
=> Missed l10n for fetcher fix

src/main/java/org/jabref/gui/collab/EntryChangeViewModel.java, src/main/java/org/jabref/gui/duplicationFinder/DuplicateResolverDialog.java, src/main/java/org/jabref/gui/externalfiles/ImportHandler.java, src/main/java/org/jabref/gui/mergeentries/MergeEntries.java, src/main/java/org/jabref/gui/mergeentries/MergeEntriesDialog.java, src/main/java/org/jabref/logic/citationkeypattern/CitationKeyGenerator.java
Follow up to https://github.com/JabRef/jabref/pull/8361; fixes #8642 
refs #8406
=> Improve key generation

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.fxml, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditorViewModel.java
=> Allow adding and deleting multiple files in the general tab

src/main/java/org/jabref/logic/importer/IdBasedParserFetcher.java, src/test/java/org/jabref/logic/importer/fetcher/AbstractIsbnFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/IsbnViaEbookDeFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/IsbnViaOttoBibFetcherTest.java
While I was working on creating tests for ebook.de, I improved the code style of the tests.
=> Refine code of ISBN fetcher tests

src/test/java/org/jabref/logic/importer/fetcher/DBLPFetcherTest.java
=> fix dblp fetcher test

src/main/java/module-info.java, src/test/java/org/jabref/logic/importer/fetcher/DoiResolutionTest.java
=> Fix DOI Resultion Test

src/main/java/module-info.java, src/test/java/org/jabref/logic/importer/fetcher/GrobidCitationFetcherTest.java
=> Fix Grobid tests

src/main/java/module-info.java
=> Add uses for tika

src/main/java/org/jabref/gui/maintable/columns/LinkedIdentifierColumn.java
=> Fix single identifier cannot be opened on click

.github/workflows/automerge.yml, CHANGELOG.md, src/main/java/org/jabref/logic/cleanup/DoiCleanup.java, src/main/java/org/jabref/model/entry/identifier/DOI.java, src/test/java/org/jabref/logic/cleanup/DoiCleanupTest.java, src/test/java/org/jabref/logic/cleanup/DoiDecodeCleanupTest.java
=> Fixes #8787 Decode doi contains masked characters

src/main/java/org/jabref/gui/desktop/os/Linux.java
=> Fix linux terminal opening process error

src/test/java/org/jabref/logic/importer/fetcher/CiteSeerTest.java, src/test/java/org/jabref/logic/importer/fetcher/JstorFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/RfcFetcherTest.java
This PR fixes the fetcher tests
=> Fix RfcFetcherTest

src/main/java/org/jabref/gui/JabRefFrame.java
=> Reworded t in prev pr

src/main/java/org/jabref/gui/openoffice/OpenOfficePanel.java
=> try to gather more output from LO exception

docs/decisions/0001-use-crowdin-for-translations.md
=> Fix dead link

src/test/java/org/jabref/logic/importer/fetcher/CiteSeerTest.java
Citeseer should work again, so we reenable the test.
=> Reenable CiteSeerTest

src/main/java/org/jabref/preferences/JabRefPreferences.java
=> Fix issue with empty fallback directory

CHANGELOG.md, src/main/java/org/jabref/gui/preferences/importexport/ImportExportTabViewModel.java
=> Fixed save order config

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fileformat/ModsImporter.java, src/test/resources/org/jabref/logic/importer/fileformat/MODSImporterTestGenreMapping.bib, src/test/resources/org/jabref/logic/importer/fileformat/MODSImporterTestGenreMapping.xml
=> Add mappings on ModsImporter.java

CHANGELOG.md, build.gradle, src/main/java/module-info.java, src/main/java/org/jabref/model/pdf/search/SearchFieldConstants.java
=> Update lucene version to 9.4

build.gradle, src/main/java/module-info.java, src/test/java/org/jabref/architecture/MainArchitectureTests.java
=> Fix archunit

README.md
The previous link was dead (404). I believe this is what it was meant to point to?
=> Update README Decision Records link

CHANGELOG.md, src/main/java/org/jabref/logic/l10n/Language.java
=> Support Arabic language

docs/code-howtos/jpackage.md, docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace.md, snap/local/JabRef-launcher
Fix a few remaining spots that were referring to the old launcher config. Fixes #9264.
=> Fix snap launcher config

.github/workflows/check-links.yaml, CHANGELOG.md, src/main/java/org/jabref/logic/xmp/XmpUtilShared.java
Fixes #9383
Workaround for IllegalArgumentException
=> Do not break on Exception in XMP parser

buildres/linux/jabrefHost.py
This PR adds a check if the browser running is a flatpak, and if so uses the adequate command to escape confinement to call jabref.
I added another error message so the extension can call the proper section in the guide (not yet written).
I will add the necessary information in the changelog and the extension repo before this is merged.
=> Add support for flatpak browsers

.github/workflows/cleanup_pr.yml, .github/workflows/deployment.yml, .github/workflows/snap.yml, .github/workflows/tests.yml
Follow-up to https://github.com/JabRef/jabref/pull/9378
Open: Fix other files, too.
=> Fix secrets presence

src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java, src/main/java/org/jabref/logic/importer/fetcher/ZbMATH.java
=> Fix Math Sci Net and ZB math fetcher test

build.gradle
Fixes https://github.com/JabRef/jabref/issues/9417
=> Switch from JDK18 to JDK17

.github/workflows/deployment-arm64.yml
=> add deployment with arm as well

.github/workflows/deployment.yml
=> try to repack deb file

.github/workflows/upload-release.yml
Follow-up to https://github.com/JabRef/jabref/pull/9530
=> Fix run GitHub Release Upload workflow

.github/workflows/deployment-arm64.yml, .github/workflows/deployment.yml
=> Set to 5.9.6000

snap/snapcraft.yaml
=> Show development information

CONTRIBUTING.md
=> Typographical error removed

src/test/java/org/jabref/logic/importer/fetcher/SemanticScholarTest.java
=> fix semantic scholar test

src/test/java/org/jabref/logic/importer/fetcher/AstrophysicsDataSystemTest.java, src/test/java/org/jabref/logic/importer/fetcher/DOABFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/LibraryOfCongressTest.java
=> Fixed various fetcher tests

CHANGELOG.md, src/main/java/org/jabref/model/entry/field/IEEEField.java, src/main/java/org/jabref/model/entry/field/UnknownField.java
=> Fix storing multiline properties for custom fields in custom entry types

src/main/java/org/jabref/gui/cleanup/CleanupSingleAction.java, src/main/java/org/jabref/gui/entryeditor/EntryEditor.fxml, src/main/java/org/jabref/gui/entryeditor/EntryEditor.java
Add "Cleanup entry" in the entryeditor.
=> Add "Cleanup entry" in the entryeditor

build.gradle, src/main/java/org/jabref/gui/autocompleter/AutoCompletionTextInputBinding.java, src/main/java/org/jabref/logic/exporter/EmbeddedBibFilePdfExporter.java, src/main/java/org/jabref/logic/xmp/XmpUtilWriter.java
While refining issues (eg., https://github.com/koppor/jabref/issues/475), I came across some typos in the code. This PR fixes them.
=> Fixes typos

src/test/java/org/jabref/logic/importer/fetcher/DOAJFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/LibraryOfCongressTest.java
=> Fix Doaj Fetcher

src/main/java/org/jabref/gui/groups/GroupTreeView.java
Fixes #9708
Follow up fix from #9686
```[tasklist]
```
=> Fix updating of group numbers

src/main/java/org/jabref/gui/customentrytypes/EntryTypeViewModel.java, src/main/java/org/jabref/gui/entryeditor/OtherFieldsTab.java, src/main/java/org/jabref/logic/bibtex/BibEntryWriter.java, src/main/java/org/jabref/logic/database/DuplicateCheck.java, src/main/java/org/jabref/logic/integrity/NoBibtexFieldChecker.java, src/main/java/org/jabref/model/entry/BibEntryType.java, src/main/java/org/jabref/model/entry/BibEntryTypeBuilder.java, src/main/java/org/jabref/model/entry/BibEntryTypesManager.java, src/main/java/org/jabref/model/entry/field/BibField.java, src/main/java/org/jabref/model/entry/types/BibtexEntryTypeDefinitions.java, src/main/java/org/jabref/model/entry/types/StandardEntryType.java, src/test/java/org/jabref/model/entry/BibEntryTest.java
While I was looking at the code, I applied IntelliJ suggestion to convert `BibField` from class to record (first commit).
I also added some links (second commit).
```[tasklist]
```
=> BibTeX code refinements

src/main/java/org/jabref/logic/bibtex/comparator/BibStringDiff.java, src/test/java/org/jabref/logic/bibtex/comparator/BibStringDiffTest.java
add missing test cases for BibStringDiff
```[tasklist]
```
=> add missing BibStringDiff test cases

src/main/java/org/jabref/logic/shared/DBMSProcessor.java, src/main/java/org/jabref/logic/shared/DBMSSynchronizer.java, src/main/java/org/jabref/logic/shared/OracleProcessor.java, src/main/java/org/jabref/logic/shared/PostgreSQLProcessor.java
Some very little code changes (while working on https://github.com/JabRef/jabref/pull/9220)
```[tasklist]
```
=> Minor refinements at DBMS code (mostly logger, JavaDoc)

src/main/java/org/jabref/logic/shared/DBMSType.java
Fixes https://github.com/koppor/jabref/issues/409
```[tasklist]
```
=> Ensure that Postgres is the default database to create

src/main/java/org/jabref/logic/msbib/MSBibMapping.java
=> fix issue after merging

.devcontainer/devcontainer.json, .vscode/settings.json, docs/getting-into-the-code/high-level-documentation.md, docs/getting-into-the-code/vscode.md
This fixes the dev container config. At least it tries to. @tobiasdiez Can you check?
Because of https://github.com/microsoft/vscode-remote-release/issues/8280#issuecomment-1518046345, it depends on https://github.com/JabRef/jabref/pull/9781.
```[tasklist]
```
=> Fix VS Code Dev Container

src/main/java/org/jabref/logic/importer/fetcher/SemanticScholar.java
=> Fix for non-found link at SemanticScholar

src/main/java/org/jabref/preferences/JabRefPreferences.java
=> Store all types in prefs to inlcude modififed

build.gradle
The latest version now supports java 20 
```[tasklist]
```
=> update  jacoco version config

rewrite.yml, src/main/java/org/jabref/logic/msbib/MSBibConverter.java
Enable OpenRewrite rule ChainStringBuilderAppendCalls
```[tasklist]
```
=> Enable ChainStringBuilderAppendCalls

src/main/java/org/jabref/logic/exporter/ModsExporter.java
Hotfix to get OpenRewrite check running (next PR)
```[tasklist]
```
=> Fix OpenRewrite

rewrite.yml, src/main/java/org/jabref/gui/desktop/JabRefDesktop.java, src/main/java/org/jabref/gui/documentviewer/DocumentPageViewModel.java, src/main/java/org/jabref/gui/groups/MoveGroupChange.java, src/main/java/org/jabref/logic/importer/fetcher/BibsonomyScraper.java, src/main/java/org/jabref/logic/importer/fileformat/BibtexParser.java, src/main/java/org/jabref/logic/importer/fileformat/RepecNepImporter.java, src/main/java/org/jabref/logic/layout/format/DocBookAuthorFormatter.java, src/main/java/org/jabref/logic/msbib/MSBibDatabase.java, src/main/java/org/jabref/logic/msbib/MSBibEntry.java, src/main/java/org/jabref/logic/openoffice/backend/GetContext.java, src/main/java/org/jabref/logic/openoffice/frontend/OOFrontend.java, src/main/java/org/jabref/logic/openoffice/frontend/UpdateCitationMarkers.java, src/main/java/org/jabref/logic/openoffice/style/OOProcessAuthorYearMarkers.java, src/main/java/org/jabref/logic/openoffice/style/OOProcessNumericMarkers.java, src/main/java/org/jabref/logic/protectedterms/ProtectedTermsParser.java, src/main/java/org/jabref/logic/shared/DBMSSynchronizer.java, src/main/java/org/jabref/model/database/BibDatabase.java, src/main/java/org/jabref/model/entry/BibtexString.java, src/main/java/org/jabref/model/strings/StringUtil.java
Manual updates: DocBookAuthorFormatter, DocumentPageViewModel, MSBibEntry, OOProcessNumericMarkers, DBMSSynchronizer, BibDatabase, BibtexString, StringUtil
Refs https://github.com/openrewrite/rewrite-static-analysis/issues/98
```[tasklist]
```
=> Enables RemoveEmptyJavaDocParameters

src/test/resources/junit-platform.properties
Result of DevCall discussion
```[tasklist]
```
=> Add comment on default execution mode for JUnit

src/main/java/org/jabref/cli/ArgumentProcessor.java, src/main/java/org/jabref/gui/exporter/SaveDatabaseAction.java, src/main/java/org/jabref/logic/autosaveandbackup/BackupManager.java, src/main/java/org/jabref/logic/crawler/StudyRepository.java, src/main/java/org/jabref/logic/exporter/BibDatabaseWriter.java, src/test/java/org/jabref/logic/citationkeypattern/CitationKeyGeneratorTest.java
Fixes https://github.com/JabRef/jabref/issues/9869
=> Fix save order

rewrite.yml, src/main/java/org/jabref/logic/shared/DatabaseLocation.java, src/main/java/org/jabref/model/search/rules/SearchRules.java
This enables https://docs.openrewrite.org/recipes/java/cleanup/removeextrasemicolons
```[tasklist]
```
=> Enable RemoveExtraSemicolons

src/main/java/org/jabref/logic/exporter/MetaDataSerializer.java, src/main/java/org/jabref/logic/importer/util/MetaDataParser.java, src/main/java/org/jabref/model/metadata/MetaData.java
Better code readability IMHO.
```[tasklist]
```
=> Add constant FILE_DIRECTORY_LATEX

src/main/java/org/jabref/gui/desktop/JabRefDesktop.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java
This adds some code comments. (Needed them to craft https://github.com/JabRef/jabref-issue-melting-pot/issues/177).
```[tasklist]
```
=> Add some code comments

.github/workflows/tests-fetchers.yml, src/test/java/org/jabref/logic/crawler/CrawlerTest.java
=> Fix NPE when executing CrawlerTest

CHANGELOG.md, src/main/java/org/jabref/gui/desktop/os/Linux.java, src/main/resources/l10n/JabRef_en.properties
=> Fix linux default open folder and terminal

src/main/java/org/jabref/gui/preferences/customexporter/CustomExporterTabViewModel.java, src/main/java/org/jabref/gui/preferences/customimporter/CustomImporterTabViewModel.java, src/main/java/org/jabref/logic/exporter/ExporterFactory.java, src/main/java/org/jabref/logic/importer/ImportFormatReader.java, src/main/java/org/jabref/logic/importer/ImporterPreferences.java, src/main/java/org/jabref/preferences/ExportPreferences.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/main/java/org/jabref/preferences/PreferencesService.java, src/test/java/org/jabref/cli/ArgumentProcessorTest.java, src/test/java/org/jabref/gui/exporter/ExportToClipboardActionTest.java, src/test/java/org/jabref/logic/exporter/ExporterTest.java, src/test/java/org/jabref/logic/importer/ImportFormatReaderIntegrationTest.java, src/test/java/org/jabref/logic/importer/ImportFormatReaderParameterlessTest.java
Follow-up to #9808 
Follow-up to #9998
=> Observable Preferences W (CustomExportFormats)

src/main/java/org/jabref/model/entry/field/FieldFactory.java, src/main/java/org/jabref/model/entry/field/StandardField.java, src/main/java/org/jabref/model/entry/field/UserSpecificCommentField.java
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/197, follow-up to https://github.com/JabRef/jabref/pull/9727
=> A user comment is now multi line

build.gradle
Triggered by https://github.com/JabRef/jabref/pull/10019#issuecomment-1597420269, which was solved with a manual update. After checking with depdendabot, it turns out, that dependabot needs a certain format.
Applies the suggestion by https://github.com/dependabot/dependabot-core/issues/1104#issuecomment-1605305246.
=> Enable auto update of OpenRewrite plugin

.github/workflows/cleanup_pr.yml
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/232
=> Cancel builds when PR is closed

.github/workflows/cleanup_pr.yml
Follow-up to https://github.com/JabRef/jabref/pull/10077
=> Cancel build publishing if PR is closed/merged

src/test/search/resources/test-library-A.bib, src/test/search/resources/test-library-D.bib
Adds test-library-D.bib to `src/test/search/resources` for manual testing in the future.
=> Test folder search

src/test/java/org/jabref/logic/journals/JournalAbbreviationRepositoryTest.java
=> Fixed abbreviation in JournalAbbreviationRepositoryTest

buildres/csl/csl-styles/apa-eu.csl
=> Use latest master style for csl apa eu

src/test/java/org/jabref/logic/importer/fetcher/BiodiversityLibraryTest.java
Replace entry for a unique one in testPerformSearch. Fixes #https://github.com/JabRef/jabref-issue-melting-pot/issues/206.
=> Replace entry for testPerformSearch 

src/test/java/org/jabref/logic/importer/fetcher/isbntobibtex/EbookDeIsbnFetcherTest.java
Follow-up PR for https://github.com/JabRef/jabref-issue-melting-pot/issues/252 disabling fetcher test.
=> Disable test class

src/main/java/org/jabref/gui/search/GlobalSearchBar.java, src/test/java/org/jabref/gui/edit/ReplaceStringViewModelTest.java
Small code fixes while I had the IDE open
=> Fix minor code issues

CHANGELOG.md, src/main/java/org/jabref/logic/l10n/Language.java
https://foojay.social/@laurentduval@mastodon.social/110900686194093781
=> Add Finnish (request on Mastodon)

src/main/java/org/jabref/gui/openoffice/OOBibBase.java, src/main/java/org/jabref/logic/formatter/casechanger/UpperCaseFormatter.java, src/main/resources/l10n/JabRef_en.properties
Refs https://github.com/JabRef/jabref/issues/10109#issuecomment-1681308664
=> correct  en l10n strings

.github/workflows/deployment-arm64.yml
Fixes #https://github.com/JabRef/jabref-issue-melting-pot/issues/262
=> rename files with arm64 suffix

src/main/java/org/jabref/gui/fieldeditors/journalinfo/JournalInfoViewModel.java, src/main/java/org/jabref/logic/importer/fetcher/JournalInformationFetcher.java, src/test/java/org/jabref/logic/journals/JournalInformationFetcherTest.java
=> move journal fetcher

rewrite.yml, src/main/java/org/jabref/gui/groups/GroupTreeView.java, src/main/java/org/jabref/gui/maintable/columns/FileColumn.java, src/main/java/org/jabref/logic/cleanup/ConvertToBibtexCleanup.java, src/main/java/org/jabref/logic/importer/fileformat/MedlineImporter.java, src/main/java/org/jabref/logic/importer/fileformat/PdfMergeMetadataImporter.java, src/main/java/org/jabref/logic/pdf/search/indexing/DocumentReader.java, src/main/java/org/jabref/logic/xmp/XmpUtilWriter.java, src/main/java/org/jabref/migrations/PreferencesMigrations.java, src/test/java/org/jabref/logic/importer/fetcher/BvbFetcherTest.java
Enable https://docs.openrewrite.org/recipes/staticanalysis/isemptycalloncollections
=> Enable IsEmptyCallOnCollections

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupDialogView.java
Fixed that checked case sensitive and regular expression were not displayed checked
Fixes #10108
Fixes #9049
before:
after:
=> Fixed that checked case sensitive and regular expression were not displayed checked

src/main/java/org/jabref/gui/help/VersionWorker.java
Unlocalize LOGGER output (and change log level)
=> Unlocalize logger at UpdateCheck

CHANGELOG.md, src/main/java/org/jabref/logic/formatter/Formatters.java, src/main/java/org/jabref/logic/importer/WebFetchers.java, src/test/java/org/jabref/gui/slr/ManageStudyDefinitionViewModelTest.java, src/test/java/org/jabref/logic/importer/WebFetchersTest.java
=> Remove CCS as it is no longer available

.gitignore
Small "productivity" improvement
=> Add CHANGELOG.html to .gitignore

.github/workflows/deployment-arm64.yml, .github/workflows/deployment.yml
Follow-up to  https://github.com/JabRef/jabref/pull/10275
=> Disable upload to builds.jabref.org if build at merge queue

build.gradle
=> Update jmh plugin

.github/workflows/deployment-arm64.yml, .github/workflows/deployment.yml
Follow-up to https://github.com/JabRef/jabref/pull/10280
=> More guards for upload

snap/snapcraft.yaml
=> Update base 22 for snapcraft

snap/snapcraft.yaml
=> gnome-42-2204

snap/snapcraft.yaml
=> Allow building on arm

build.gradle, src/main/java/org/jabref/gui/journals/AbbreviateAction.java
Small code improvement
(Small PR to have the next PR more focussed)
=> Apply exit early pattern

rewrite.yml, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java, src/main/java/org/jabref/gui/openoffice/Bootstrap.java, src/main/java/org/jabref/gui/openoffice/OOBibBaseConnect.java, src/main/java/org/jabref/gui/search/GlobalSearchBar.java, src/main/java/org/jabref/logic/importer/fetcher/ArXivFetcher.java, src/main/java/org/jabref/logic/layout/StringInt.java, src/test/java/org/jabref/gui/autocompleter/SuggestionProvidersTest.java, src/test/java/org/jabref/logic/exporter/DocBook5ExporterTest.java, src/test/java/org/jabref/logic/importer/fileformat/MarcXmlParserTest.java
Applies https://docs.openrewrite.org/recipes/java/shortenfullyqualifiedtypereferences
=> Apply ShortenFullyQualifiedTypeReferences

rewrite.yml, src/main/java/org/jabref/gui/entryeditor/fileannotationtab/FulltextSearchResultsTab.java, src/main/java/org/jabref/logic/citationkeypattern/BracketedPattern.java, src/main/java/org/jabref/logic/importer/AuthorListParser.java, src/main/java/org/jabref/logic/importer/fetcher/MrDLibFetcher.java, src/main/java/org/jabref/logic/importer/fileformat/MedlinePlainImporter.java, src/main/java/org/jabref/logic/layout/format/AuthorAndToSemicolonReplacer.java, src/main/java/org/jabref/migrations/PreferencesMigrations.java, src/main/java/org/jabref/model/entry/identifier/ArXivIdentifier.java, src/test/java/org/jabref/logic/bibtex/BibEntryWriterTest.java
Applies https://docs.openrewrite.org/recipes/staticanalysis/usestringreplace
=> Use OpenRewrite UseStringReplace

CHANGELOG.md, src/main/java/module-info.java
Fixes https://github.com/JabRef/jabref/issues/10274
Refs https://github.com/JabRef/jabref/issues/10274#issuecomment-1707404929
=> Add requires on org.freedesktop.dbus

docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-89-run-with-intellij.md
I manged to get IntellIJ to buld JabRef - without gradle. I creatd a how to. Please double check.
More details at https://stackoverflow.com/a/77040569/873282.
=> Add howto for "Build and run using IntelliJ IDEA"

build.gradle
Follow up from https://github.com/JabRef/jabref/pull/10326
=> fix afterburner and javafx errors on startup

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java
=> Fix groups validator

src/main/java/org/jabref/logic/importer/fetcher/INSPIREFetcher.java
=> FIX NPE in inspire fetcher

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fetcher/GvkFetcher.java, src/main/java/org/jabref/logic/importer/fetcher/isbntobibtex/IsbnFetcher.java, src/main/java/org/jabref/logic/importer/fileformat/PicaXmlParser.java, src/test/java/org/jabref/logic/importer/fetcher/isbntobibtex/GVKIsbnFetcherTest.java
Fixes #10348
Chek for E-resources and isbn
use arrayList instead of linkedlist
=> Fix isbn fetcher returning misc

docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/eclipse.md, docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-89-run-with-intellij.md
Follow-up to https://github.com/JabRef/jabref/pull/10323
Includes https://stackoverflow.com/a/69892626/873282
=> Refine IntelliJ howto

src/test/java/org/jabref/logic/bibtex/comparator/EntryComparatorTest.java, src/test/java/org/jabref/logic/bibtex/comparator/FieldComparatorTest.java
Add testPresentFieldsWithKeyField & testPresentFieldsWithoutKeyField for code coverage as well as reducing code.
=> Add tests for EntryComperatorTest

build.gradle
https://github.com/openjdk/jfx20u/blob/master/doc-files/release-notes-20.0.2.md
=> update javafx to 20.0.2

src/main/java/org/jabref/gui/actions/StandardActions.java, src/main/java/org/jabref/gui/preferences/external/ExternalTab.fxml, src/main/java/org/jabref/gui/preferences/external/ExternalTab.java, src/main/java/org/jabref/logic/help/HelpFile.java, src/main/resources/l10n/JabRef_en.properties
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/279.
Button: ![grafik](https://github.com/JabRef/jabref/assets/127773292/37377d41-a629-461c-b416-64aa0cfa40d1)
Outcome: ![grafik](https://github.com/JabRef/jabref/assets/127773292/76841126-de16-4727-9f83-111747964ef9)
=> Link to online documentation 

src/main/java/org/jabref/gui/fieldeditors/contextmenu/EditorMenus.java, src/main/java/org/jabref/gui/fieldeditors/identifier/IdentifierEditor.java, src/main/java/org/jabref/model/entry/identifier/DOI.java, src/test/java/org/jabref/model/entry/identifier/DOITest.java
Reported by @ThiloteE 
Original stack trace:
```
caused by: java.lang.StringIndexOutOfBoundsException: Range [1, 0) out of bounds for length 1
at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4608)
at …
```
=> Fix DOI parsing error

src/main/java/org/jabref/gui/cleanup/CleanupAction.java
=> Show exception in cleanup error

CHANGELOG.md, src/main/java/org/jabref/gui/push/PushToApplications.java, src/main/java/org/jabref/gui/push/PushToTexShop.java, src/main/resources/l10n/JabRef_en.properties
Fixes https://discourse.jabref.org/t/push-to-texshop-mac/2699
TODO: Ask for logo license
=> Add TeXShop (macOS only)

src/main/java/org/jabref/logic/importer/fetcher/CrossRef.java, src/test/java/org/jabref/logic/importer/fetcher/ACMPortalFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/CrossRefTest.java
=> Add fields to CrossRef 

src/main/java/org/jabref/logic/importer/fetcher/CrossRef.java, src/test/java/org/jabref/logic/importer/fetcher/CrossRefTest.java
=> follow up to crossref issue and number

src/test/java/org/jabref/logic/importer/util/GrobidServiceTest.java
=> Adapt tests to new GROBID service

CHANGELOG.md, src/main/java/org/jabref/logic/citationstyle/CitationStyle.java, src/main/java/org/jabref/logic/shared/DBMSProcessor.java, src/main/java/org/jabref/logic/shared/PostgreSQLProcessor.java
=> Fix parsing of version DB struct in database

src/main/java/org/jabref/gui/integrity/IntegrityCheckAction.java, src/main/java/org/jabref/gui/integrity/IntegrityCheckDialog.java, src/main/java/org/jabref/logic/integrity/IntegrityCheck.java
=> Add tooltip for integrity check dialog

external-libraries.md
=> update external libraries

.github/heylogs.java, .github/workflows/tests.yml
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/315
=> Update CHANGELOG.md linter

src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/entryeditor/RelatedArticlesTab.java, src/main/java/org/jabref/gui/externalfiles/ImportHandler.java, src/main/java/org/jabref/gui/mergeentries/FetchAndMergeEntry.java, src/main/java/org/jabref/logic/importer/ImportCleanup.java, src/main/java/org/jabref/logic/importer/ImportCleanupBiblatex.java, src/main/java/org/jabref/logic/importer/ImportCleanupBibtex.java, src/test/java/org/jabref/gui/externalfiles/ImportHandlerTest.java, src/test/java/org/jabref/logic/importer/fetcher/ArXivFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/CompositeSearchBasedFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/SearchBasedFetcherCapabilityTest.java
Follow-up to https://github.com/JabRef/jabref/pull/10513
I especially fixed proper inheritance https://github.com/JabRef/jabref/pull/10562/files#diff-21fc4582e5cd15b52ff18fd210f00d78845396e2a8a6979bfd6ab7327f925243
=> Minor code improvements to ImportHandler

src/main/java/org/jabref/logic/importer/ImporterPreferences.java, src/main/java/org/jabref/logic/importer/WebFetchers.java, src/main/java/org/jabref/logic/importer/fetcher/AstrophysicsDataSystem.java, src/main/java/org/jabref/logic/importer/fetcher/BiodiversityLibrary.java, src/main/java/org/jabref/logic/importer/fetcher/IEEE.java, src/main/java/org/jabref/logic/importer/fetcher/ScienceDirect.java, src/main/java/org/jabref/logic/importer/fetcher/SemanticScholar.java, src/main/java/org/jabref/logic/importer/fetcher/SpringerFetcher.java, src/main/java/org/jabref/logic/importer/fetcher/SpringerLink.java, src/main/java/org/jabref/logic/importer/fetcher/ZbMATH.java, src/test/java/org/jabref/logic/importer/fetcher/SemanticScholarTest.java
Refactor api key getting
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/320
=> Add api key for semantic scholar if available

.github/workflows/tests.yml
Update codecov following newest developments. See https://github.com/codecov/codecov-action and 
https://about.codecov.io/blog/setting-up-codecov-with-java-and-gradle/
Freshly updated metrics at https://app.codecov.io/gh/JabRef/jabref
=> change codecov

build.gradle
update controlsfx
Fixes https://github.com/JabRef/jabref/issues/8523
Fixes https://github.com/JabRef/jabref/issues/5941
Now requires GTK3 for linux and. macOS 11 minimum 
https://github.com/openjdk/jfx/blob/jfx21/doc-files/release-notes-21.md
=> Update to JavaFX 21.01

src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java
Fixes #10499
Searching by MrNumber works now as well.
I could not test the other query interface as it returns a 401 but from the website it seems to have the correct params npw
=> Fix mathscinet fetcher by id

src/main/java/org/jabref/logic/importer/fetcher/DoiFetcher.java, src/main/java/org/jabref/logic/importer/fetcher/TitleFetcher.java, src/test/java/org/jabref/logic/importer/fetcher/ArXivFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/AstrophysicsDataSystemTest.java, src/test/java/org/jabref/logic/importer/fetcher/DoiFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/LOBIDFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/MedraTest.java, src/test/java/org/jabref/logic/importer/fetcher/PagedSearchFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/TitleFetcherTest.java
Many fetcher tests fail (see https://github.com/JabRef/jabref/pull/10709). This PR fixes some of them.
=> Fix (some) fetcher tests

build.gradle, external-libraries.md
=> Externallibs

CHANGELOG.md, src/main/java/org/jabref/gui/EntryTypeView.java, src/main/java/org/jabref/gui/EntryTypeViewModel.java
Fix https://github.com/JabRef/jabref/issues/10508
=> Fix cancelling ignored when generating an entry from id

CHANGELOG.md, src/main/java/org/jabref/gui/actions/StandardActions.java, src/main/java/org/jabref/gui/icon/InternalMaterialDesignIcon.java, src/main/java/org/jabref/gui/maintable/MainTable.css, src/main/java/org/jabref/gui/sidepane/SidePaneType.java, src/main/java/org/jabref/gui/specialfields/SpecialFieldViewModel.java
Old:
New:
Fixes https://github.com/JabRef/jabref/issues/10431
Follow-up to https://github.com/JabRef/jabref/pull/10620
=> Fix color for hovered special fields

docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-89-run-with-intellij.md
Native IntelliJ copy is too slow. Use OS copy routines.
@Siedlerchr Is this description understandable for MacOS as well?
=> Refine howto for copying

build.gradle
Refs https://github.com/JabRef/jabref/issues/10729
=> downgrade javafx to check if it works

build.gradle
Follow-up to https://github.com/JabRef/jabref/pull/10762
=> Remove remainging "testLogging"

src/main/java/org/jabref/gui/theme/ThemeManager.java
=> Add wokraround for theme detector issue

src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/gui/autosaveandbackup/BackupManager.java, src/main/java/org/jabref/gui/maintable/MainTable.java
Some small updates at the loading code comments / variable names. Also deletes dead code.
I think, I found a dead code fragment due to recent refactorings by @calixtus.
=> Refine loading code

rewrite.yml
- https://github.com/JabRef/jabref/pull/10788
- https://github.com/JabRef/jabref/pull/10787
- https://github.com/JabRef/jabref/pull/10786
=> Adapt rewrite.yml to match merged PRs

build.gradle
Fixes #5867
Probably also #10731
Release notes https://gluonhq.com/products/javafx/openjfx-21-release-notes/#21.0.2
=> Update to javafx 21.0.2

.github/workflows/deployment-arm64.yml, .github/workflows/deployment.yml, .github/workflows/refresh-journal-lists.yml, .github/workflows/tests-fetchers.yml, .github/workflows/tests.yml, .github/workflows/update-gradle-wrapper.yml
=> Update to jdk 21.0.2

.github/workflows/deployment-arm64.yml
=> Switch to arm runner macos14

.github/workflows/deployment-arm64.yml
=> Fix secrents presence chcek

.github/workflows/deployment-arm64.yml, .github/workflows/deployment.yml, .github/workflows/refresh-journal-lists.yml, .github/workflows/tests-fetchers.yml, .github/workflows/tests.yml
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/350
=> Bump gradle-build-action to actions/setup-gradle

docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-13-code-style.md
Fixes https://github.com/JabRef/jabref/pull/10944
=> Refine text for disablement

src/main/java/org/jabref/logic/texparser/DefaultLatexParser.java
=> Use java.nio in org.jabref.logic.texparser.DefaultLatexParser

.github/workflows/deployment-jdk-ea.yml
Refs https://github.com/awalsh128/cache-apt-pkgs-action/issues/128#issuecomment-1975385668
=> Try latest master of awalsh128/cache-apt-pkgs-action

src/test/java/org/jabref/gui/entryeditor/citationrelationtab/BibEntryRelationsRepositoryTest.java
Test for the update at https://github.com/JabRef/jabref/pull/10980.
=> Add BibEntryRelationsRepositoryTest

.github/workflows/tests.yml
Just some magic. Uses https://github.com/awalsh128/cache-apt-pkgs-action?tab=readme-ov-file#cache-apt-pkgs-action.
=> Speed up failure reporting

src/main/java/org/jabref/logic/importer/fileformat/BibtexParser.java
=> Follow up fix with bibdesk groups

build.gradle
Details:
https://github.com/openjdk/jfx/blob/master/doc-files/release-notes-22.md
=> Update javafx to 22

src/main/java/org/jabref/gui/FrameDndHandler.java, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/Telemetry.java
=> Some cleanups and refactorings in JabRefFrame

build.gradle
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/391
=> Fix pdfbox

build.gradle
=> Update citeproc to released version

build.gradle, src/main/java/module-info.java
HOTFIX
Fixes https://github.com/JabRef/jabref/issues/10676#issuecomment-2018874315
Similar to https://github.com/JabRef/jabref/pull/10689
=> Fix missing module error for CSL

docs/code-howtos/custom-svg-icons.md
=> add json file

src/main/java/org/jabref/gui/cleanup/CleanupPresetPanel.fxml, src/main/java/org/jabref/gui/desktop/os/NativeDesktop.java, src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/maintable/ExtractReferencesAction.java, src/main/java/org/jabref/logic/importer/fileformat/PdfContentImporter.java, src/main/resources/l10n/JabRef_en.properties
More strings to translate ...
Some more grouping in `JabRef_en.properties`
And some other, unrelated minor code improvements.
=> Fix headings in cleanup dialog

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/KeywordsEditor.java, src/main/java/org/jabref/gui/fieldeditors/KeywordsEditorViewModel.java, src/main/java/org/jabref/gui/fieldeditors/LinkedEntriesEditor.java, src/main/java/org/jabref/model/entry/EntryLinkList.java
Closes #11178.
https://github.com/JabRef/jabref/assets/52158423/4793de09-ffc7-45b3-baea-ffc418273fce
=> Commit new keyword when typing the keywords separator

src/test/java/org/jabref/logic/database/DuplicateCheckTest.java
=> Fix comment

build.gradle
Fixes https://github.com/JabRef/jabref/issues/11225
=> Add addtional java options with export and opens

.github/workflows/add-greeting-to-issue.yml
=> Make newcomer message even more welcoming

CHANGELOG.md, src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/gui/StateManager.java, src/main/java/org/jabref/gui/externalfiles/ImportHandler.java, src/main/java/org/jabref/gui/groups/GroupNodeViewModel.java, src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java, src/main/java/org/jabref/model/database/BibDatabaseContext.java, src/test/java/org/jabref/gui/groups/GroupTreeViewModelTest.java
Fixes #11085 
Fixes #11269
Fixes #8933
Equals/hashcode changes too much
1. Create a new empty library
2. add a subgroup
3. Paste two or more entries in the subgroup
4.
=> Fix import selected groups

.github/workflows/deployment-arm64.yml, .github/workflows/deployment-jdk-ea.yml, .github/workflows/deployment.yml
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/411
v
=> Update codesign action due to Node 16 deprecation

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/EntryEditorPreferences.java, src/main/java/org/jabref/gui/entryeditor/FieldsEditorTab.java, src/main/java/org/jabref/preferences/JabRefPreferences.java
Fixes https://github.com/JabRef/jabref/issues/11281
=> Store preview divider pos in entry editor

src/main/java/org/jabref/logic/bst/BstFunctions.java, src/test/java/org/jabref/logic/bst/BstFunctionsTest.java
Small follow-up to https://github.com/JabRef/jabref/pull/11304.
Should not change any functionality, but cleaner code.
=> Sanitize input for substring$

src/test/java/org/jabref/logic/importer/fetcher/DOABFetcherTest.java
=> Fix DOABFetcherTest

CHANGELOG.md, src/main/java/org/jabref/logic/importer/AuthorListParser.java, src/test/java/org/jabref/logic/importer/AuthorListParserTest.java
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/438
=> Fix parsing of single Uppercase author last name

CHANGELOG.md, src/main/java/org/jabref/gui/theme/ThemeManager.java
fixes https://github.com/JabRef/jabref/issues/11344
=> Apply font size override after setting theme

src/main/java/org/jabref/gui/preferences/PreferencesSearchHandler.java
=> Change branches of `scanLabeledControls`

src/main/java/org/jabref/gui/entryeditor/EntryEditor.java
Hotfix for https://github.com/JabRef/jabref/pull/11379
=> Fix missing dependency injection

.github/workflows/tests.yml
Old version was no longer maintained
new version has last release 3 days ago
=> Update reviewdog checkstyle

.github/workflows/tests.yml
=> use default latest checkstyle

src/main/java/org/jabref/gui/preferences/PreferencesDialog.fxml, src/main/java/org/jabref/gui/preferences/PreferencesDialogView.java
=> Revert "Increase height of preferences dialog"

snap/snapcraft.yaml
=> Update snapcraft.yaml to new version

.github/workflows/deployment.yml
=> Change runner image for mac

.github/workflows/deployment.yml, CHANGELOG.md
add changelog
Fixes https://github.com/JabRef/jabref/issues/11468
Fixes #11475
=> fix macos image name

CHANGELOG.md
=> Add missing issue numbers

build.gradle
Just the maven coordinates have changed, the package name stays the same
=> change to jabref easybding

src/main/java/org/jabref/gui/externalfiles/UnlinkedFilesDialogView.java, src/main/java/org/jabref/preferences/JabRefPreferences.java
Save configuration on dialog exit
Fixes https://github.com/JabRef/jabref/issues/11540
Follow up to https://github.com/JabRef/jabref/pull/11493
Changelog is not necessary
=> Fix find unlinked files

.github/workflows/cleanup-pr.yml, .github/workflows/deployment-arm64.yml, .github/workflows/deployment.yml, .github/workflows/gource.yml, .github/workflows/tests.yml
This ports the nice output from https://github.com/JabRef/jabref/blob/7be96c676409a9938873f20b0d08a55d8afbd72a/.github/workflows/deployment-jdk-ea.yml#L61 to the other workflows
=> Nicer secret precense output for all workflows

src/main/java/org/jabref/logic/importer/fetcher/GrobidCitationFetcher.java, src/main/java/org/jabref/logic/importer/util/GrobidService.java
Add debug possibility to Grobid
Additionally: Minor variable renaming
=> Add logging to Grobid

src/main/java/org/jabref/gui/importer/GrobidOptInDialogHelper.java, src/main/java/org/jabref/logic/importer/fetcher/GrobidPreferences.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/test/resources/testbib/pdfs/.gitignore
Related: https://github.com/JabRef/jabref/pull/11563
=> Minor code style improvements

src/main/java/org/jabref/gui/actions/StandardActions.java, src/main/resources/l10n/JabRef_en.properties
Just the correction of a typo (double dots)
=> Update StandardActions.java : typo corrected

.github/workflows/add-greeting-to-issue.yml, docs/code-howtos/faq.md, docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-11-code-into-ide.md, docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-12-build.md, docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-13-code-style.md
Refs https://github.com/JabRef/jabref/pull/11507 which had to be closed due to https://github.com/JabRef/jabref/pull/11507#issuecomment-2268025339. This PR adds the remaining non-conflicting changes:
- Add link to developer FAQs in first time contribution greeting.
- Grammar fix in `faq.md`.
- Add some pointers about reaching IntlliJ Settings in M2 Macs while setting up the development environment.
=> Improve developer documentation

src/main/java/org/jabref/gui/preferences/general/GeneralTabViewModel.java
=> fix checkstyle

PRIVACY.md
Add Mistral AI, Hugging Face and DJL privacy policies.
=> Add more organizations related to AI features to PRIVACY.md

docs/teaching.md
Small stylistic improvement. Just letting the CI check run.
=> Rework "Praises"

CHANGELOG.md, src/main/java/org/jabref/gui/integrity/IntegrityCheckDialog.fxml, src/main/java/org/jabref/gui/integrity/IntegrityCheckDialog.java, src/main/java/org/jabref/logic/integrity/IntegrityMessage.java
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/473
improve some code
=> Improve ingerity check dialog scolling

src/main/java/org/jabref/gui/preferences/ai/AiTab.fxml, src/main/java/org/jabref/logic/ai/GenerateEmbeddingsTask.java, src/main/resources/l10n/JabRef_en.properties
=> Correction of 2 typos

src/main/java/org/jabref/gui/preferences/ai/AiTab.fxml, src/main/java/org/jabref/gui/preferences/ai/AiTab.java, src/main/java/org/jabref/gui/preferences/ai/AiTabViewModel.java, src/main/resources/l10n/JabRef_en.properties
Closes https://github.com/InAnYan/jabref/issues/152.
=> Make embedding models combobox searchable

build.gradle, src/main/java/org/jabref/gui/ai/components/aichat/AiChatComponent.java, src/main/java/org/jabref/gui/entryeditor/SciteTabViewModel.java, src/main/java/org/jabref/gui/maintable/MainTable.java, src/main/java/org/jabref/gui/maintable/PersistenceVisualStateTable.java, src/main/java/org/jabref/logic/ai/models/JabRefEmbeddingModel.java, src/main/java/org/jabref/logic/citationstyle/JabRefLocaleProvider.java, src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java
Follow-up to https://github.com/JabRef/jabref/pull/11608
=> Bump OpenRewrite gradle plugin and BOM

src/main/java/org/jabref/gui/preferences/entryeditor/EntryEditorTabViewModel.java
Closes https://github.com/JabRef/jabref/issues/11663
=> Save "Show AI summary tab" in entry editor preferences

src/main/java/org/jabref/gui/openoffice/OOBibBase.java
Closes https://github.com/subhramit/jabref/issues/26
Follow-up to: #11577
=> Auto-update CSL Bibliography feature

docs/decisions/0031-use-current-tab-for-deciding-style-type-for-oo.md
Nitpick: The old title looked a little too long.
Refs. https://github.com/JabRef/jabref/pull/11477
=> Change ADR title

src/main/java/org/jabref/gui/preferences/ai/AiTab.fxml, src/main/java/org/jabref/gui/preferences/ai/AiTab.java, src/main/java/org/jabref/gui/preferences/ai/AiTabViewModel.java, src/main/java/org/jabref/logic/util/LocalizedNumbers.java, src/main/resources/l10n/JabRef_en.properties
=> Fix for settings saving in AI tab

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fetcher/ArXivFetcher.java, src/test/java/org/jabref/logic/importer/fetcher/ArXivFetcherTest.java, src/test/java/org/jabref/logic/integrity/BracesCorrectorTest.java
=> use braces corrector for abstract in arxiv

src/main/java/org/jabref/gui/maintable/MainTable.java, src/main/java/org/jabref/gui/theme/StyleSheetFile.java, src/main/java/org/jabref/logic/xmp/XmpUtilReader.java, src/main/java/org/jabref/model/search/Analyzer/LatexToUnicodeFoldingFilter.java, src/main/resources/tinylog.properties
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/522
=> Reduce log noise, even in debug mode

src/main/java/org/jabref/gui/openoffice/OpenOfficePanel.java, src/main/java/org/jabref/gui/sidepane/SidePaneContentFactory.java
Just a more AI dependency. But it's not that much, because it's still needed for groups..
=> Remove AI service from OpenOfficePanel

src/main/java/org/jabref/logic/formatter/bibtexfields/HtmlToLatexFormatter.java
- rewrite a for-loop to a regex and replaceAll
=> finish todo in HtmlToLatexFormatter

build.gradle
Discussed during a call with @InAnYan and @ThiloteE
=> Update djl api dependency

src/main/java/org/jabref/gui/importer/actions/OpenDatabaseAction.java
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/559
=> Fix exception on opening same file twice

src/main/java/org/jabref/logic/ai/chatting/chathistory/storages/MVStoreChatHistoryStorage.java, src/main/java/org/jabref/logic/ai/util/MVStoreBase.java
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/575
=> Handle AI service exceptions when starting second instance

src/main/java/org/jabref/gui/search/GlobalSearchBar.java
Follow-up to: #11854
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/583
=> Focus search bar after toggling search flags

src/main/java/module-info.java
We should keep grouping of requires.
=> Fix sort of requires

src/main/java/org/jabref/gui/shared/SharedDatabaseLoginDialogView.java, src/main/java/org/jabref/gui/shared/SharedDatabaseLoginDialogViewModel.java
That was because of one of my AI PRs
=> Fix broken shared database

docs/code-howtos/localization.md
=> Add link to Java code.

docs/code-howtos/http-server.md
=> Refine howto for HTTP Server

src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java, src/main/java/org/jabref/logic/importer/ImportFormatReader.java, src/main/java/org/jabref/logic/importer/fileformat/PdfContentImporter.java, src/main/java/org/jabref/logic/importer/fileformat/PdfEmbeddedBibFileImporter.java, src/main/java/org/jabref/logic/importer/fileformat/PdfGrobidImporter.java, src/main/java/org/jabref/logic/importer/fileformat/PdfImporter.java, src/main/java/org/jabref/logic/importer/fileformat/PdfMergeMetadataImporter.java, src/main/java/org/jabref/logic/importer/fileformat/PdfVerbatimBibtexImporter.java, src/main/java/org/jabref/logic/importer/fileformat/PdfXmpImporter.java, src/test/java/org/jabref/logic/importer/fileformat/PdfVerbatimBibtexImporterTest.java
Add `PdfImporter` abstract class to group importers
=> Refine PDF importers

.github/workflows/on-labeled.yml
... and fix version of github-action-move-issues.
=> Rename on-labeled workflow 

src/main/java/org/jabref/gui/undo/CountingUndoManager.java
Fixes https://github.com/JabRef/jabref/issues/11966
=> fix not on fx thread on cleanup with undo redo binding

CONTRIBUTING.md
Triggered by https://github.com/koppor/jabref/issues/551#issuecomment-2415906274, I think, our contributing guide needs to be refined.
I'll merge to have it available intermediatly.
=> Add links to our setup guideline.

.github/workflows/assign-issue.yml
Does not work - see https://github.com/takanome-dev/assign-issue-action/pull/245#issuecomment-2416827818
=> Revert "Test WIP version of action (#11989)"

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fileformat/PdfMergeMetadataImporter.java
=> Switch priorities: XMP over Grobid

src/main/java/org/jabref/gui/externalfiles/DownloadFullTextAction.java, src/main/resources/l10n/JabRef_en.properties
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/465
=> Streamline text of DownloadFullTextAction

CONTRIBUTING.md
Some contributors want to re-create a pull request (e.g., https://github.com/JabRef/jabref/pull/12009#discussion_r1804670003). 
Therefore, I added some text to `CONTRIBUTING.md`.
=> Add "After submission of a pull request"

build.gradle
https://github.com/openjdk/jfx23u/commit/54a682d31d3880a813015dfbb6a12414e0154caa
=> Update to javafx 23.0.1

.github/workflows/assign-issue.yml
I missed to update the placeholdes at https://github.com/JabRef/jabref/pull/12027.
=> Fix placeholders

src/main/java/org/jabref/gui/mergeentries/FetchAndMergeEntry.java, src/main/java/org/jabref/logic/importer/CompositeIdFetcher.java
Caused by a review of https://github.com/JabRef/jabref/pull/12025
=> Add some links into the code

src/main/java/org/jabref/model/entry/field/FieldFactory.java
Triggered by https://github.com/JabRef/jabref/issues/11939#issuecomment-2423901006
=> Exhanges a TODO to a comment

src/main/java/org/jabref/gui/frame/MainToolBar.java, src/main/resources/l10n/JabRef_en.properties
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/644
=> Change casing and improve naming of Background tasks

src/test/java/org/jabref/logic/l10n/LocalizationTest.java
Context: https://github.com/JabRef/jabref/pull/12017#issuecomment-2433100699
=> Add test that %0 is kept

.github/workflows/on-labeled-issue.yml
=> Add project move after manually putting "📍 Assigned" label

src/main/java/org/jabref/logic/openoffice/style/JStyle.java
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/670
=> Fix NPE in case of last selected jstyle file is not a resource

src/main/java/org/jabref/gui/preferences/ai/AiTabViewModel.java, src/main/java/org/jabref/logic/ai/AiPreferences.java
Previously chat model in AI tab was not properly working.
Now it should be all right.
=> Fix AI settings

.devcontainer/devcontainer.json, .github/workflows/deployment-arm64.yml, .github/workflows/deployment-jdk-ea.yml, .github/workflows/deployment.yml, .github/workflows/tests-fetchers.yml, .github/workflows/tests.yml, .github/workflows/update-gradle-wrapper.yml, .gitpod.Dockerfile, build.gradle, docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-12-build.md
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/669
All issues seen at https://github.com/JabRef/jabref/pull/12134 should be fixed.
=> Update JDK from 21 to 23

CHANGELOG.md, gradle/wrapper/gradle-wrapper.properties, src/main/java/org/jabref/gui/actions/ActionHelper.java, src/main/java/org/jabref/gui/frame/JabRefFrame.java, src/main/java/org/jabref/gui/frame/OpenConsoleAction.java
Fixes https://github.com/JabRef/jabref/issues/11920
Supersedes https://github.com/JabRef/jabref/pull/12162
=> Disable menu items for unsaved library

src/main/java/org/jabref/gui/linkedfile/LinkedFileEditDialogViewModel.java
Fixes https://github.com/JabRef/jabref/issues/12236
Follow up to https://github.com/JabRef/jabref/pull/12219
Link the issue that will be closed, e.g., "Closes #333". If your PR closes a koppor issue, link it using its URL, e.g., "Closes https://github.com/koppor/jabref/issues/47".
=> Fix file adding

CHANGELOG.md
Follow-up to: https://github.com/JabRef/jabref/pull/12157
=> Add changelog entry for "Find title from second page"

rewrite.yml
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/715
=> Disable non-working Openrewrite recipe

src/main/java/org/jabref/logic/openoffice/style/JStyle.java
=> Fix OO default jstyle loading from resources

src/main/java/org/jabref/gui/maintable/MainTableColumnModel.java
refs https://github.com/JabRef/jabref/issues/12326#issuecomment-2558635752
=> add toString methods to MainTableColumnModel

src/main/java/org/jabref/gui/linkedfile/DeleteFileAction.java
Follow-up to https://github.com/JabRef/jabref/pull/12324
Some more code comments - in case someone touches the source again.
=> Refine comments

.github/workflows/deployment.yml
=> Downgrade runner image (replace condtions)

src/main/java/org/jabref/gui/errorconsole/LogEventViewModel.java, src/main/java/org/jabref/gui/fieldeditors/FieldNameLabel.java, src/main/java/org/jabref/gui/groups/GroupNodeViewModel.java, src/main/java/org/jabref/gui/groups/UndoableAddOrRemoveGroup.java, src/main/java/org/jabref/gui/mergeentries/newmergedialog/fieldsmerger/FieldMergerFactory.java, src/main/java/org/jabref/gui/util/ControlHelper.java, src/main/java/org/jabref/gui/util/FieldsUtil.java, src/main/java/org/jabref/logic/exporter/GroupSerializer.java, src/main/java/org/jabref/logic/importer/fileformat/RisImporter.java, src/main/java/org/jabref/model/entry/BibEntry.java, src/main/java/org/jabref/model/entry/Month.java
- Utilized pattern matching where applicable to simplify code.  
- Replaced `if` statements with `switch` where appropriate for better clarity and performance.  
- Applied `switch` expressions where possible to improve conciseness and maintainability.
=> Refactor switch statements

src/main/java/org/jabref/gui/entryeditor/citationrelationtab/BibEntryView.java, src/main/java/org/jabref/gui/frame/JabRefFrameViewModel.java, src/main/java/org/jabref/gui/util/ControlHelper.java, src/main/java/org/jabref/logic/bibtex/comparator/EntryComparator.java, src/main/java/org/jabref/logic/database/DuplicateCheck.java, src/main/java/org/jabref/logic/exporter/GroupSerializer.java, src/main/java/org/jabref/logic/formatter/casechanger/Word.java, src/main/java/org/jabref/logic/importer/fileformat/BibtexImporter.java, src/main/java/org/jabref/logic/importer/fileformat/IsiImporter.java, src/main/java/org/jabref/logic/integrity/BracesCorrector.java, src/main/java/org/jabref/logic/openoffice/backend/Backend52.java, src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckResultTxtWriter.java, src/main/java/org/jabref/model/entry/event/FieldChangedEvent.java, src/main/java/org/jabref/model/entry/field/OrFields.java, src/main/java/org/jabref/model/openoffice/style/OODataModel.java, src/main/java/org/jabref/model/openoffice/style/PageInfo.java, src/main/java/org/jabref/model/study/Study.java
- Extracted lists into static constants where applicable.  
- Introduced explicit casts to ensure lists are accessed using the correct generic type.  
- Replaced manual string length checks with `String.isEmpty()` where possible.  
- Removed unnecessary boxing to improve performance.  
- Used `StringBuilder` instead of string concatenation in loops for better efficiency.  
- Optimized code by using bulk operations where applicable.  
- Eliminated improper `==` comparisons.  
- Fixed an issue with infinite recursion (closes #12397).
=> Fixed Probable Bugs and Improved Code Efficiency

src/main/java/org/jabref/model/entry/LinkedFile.java
For https://github.com/JabRef/jabref-issue-melting-pot/issues/766.
The formulation might not be the best.
=> Add comment to field `fileType` of `LinkedFile`

src/main/java/org/jabref/logic/importer/fileformat/BibtexParser.java
Extracted from https://github.com/JabRef/jabref/pull/12145
=> Improve condition

src/test/resources/testbib/issue-12274/README.md, src/test/resources/testbib/issue-12274/issue-12274.bib
This adds test case for #12274
=> Add test data for 12274

build.gradle
See https://gluonhq.com/products/javafx/openjfx-23-release-notes/
=> Update JavaFX from 23.0.1 to 23.0.2

CHANGELOG.md, src/main/java/org/jabref/gui/frame/FileHistoryMenu.java
=> Keep removed files in filehistory

.github/workflows/assign-issue.yml
Switches to https://github.com/m7kvqbe1/github-action-move-issues/pull/32
Follow-up to https://github.com/JabRef/jabref/pull/11945
=> Use development version of move-action

CHANGELOG.md, build.gradle
=> add mac and linux arm deps for postgres

docs/decisions/0041-use-one-form-for-singular-and-plural.md
https://phrase.com/blog/posts/pluralization/ is a good blog. Should be linked.
=> Add link to Blog

.github/workflows/tests.yml
Workaround for download issues
Based on https://github.com/koppor/plantuml/blob/5463976275448b97da1934c3f8a28ba2c31ce62b/.github/workflows/build-and-publish.yml#L32
=> Cache clparse

.github/workflows/product-map.yml
Some research on advanced actions. Let's see how useful this is.
=> Readd product map action

CONTRIBUTING.md
=> Add note on reviewing time

.github/PULL_REQUEST_TEMPLATE.md
The old template had too much text for a too little thing: Description is much text; just modifying a link and deleting text is too little.
With this, I try to make it easer.
=> Refine PULL_REQUEST_TEMPLATE.md

.github/workflows/assign-issue.yml, .github/workflows/on-issue-labeled.yml, .github/workflows/on-issue-unlabeled.yml
Ports https://github.com/m7kvqbe1/github-action-move-issues/pull/37 to here.
=> Use fixed version of action

.github/workflows/check-links.yml, .github/workflows/gource.yml, .github/workflows/on-issue-comment.yml, .github/workflows/unassign-issues.yml, .github/workflows/update-gradle-wrapper.yml
Some actions should not run at jabref-koppor.
=> Refine workflow triggers

.github/ghprcomment.yml
Follow-up to https://github.com/JabRef/jabref/pull/12513.
Refined the message on force push detection.
=> Refine force push PR comment

src/main/java/org/jabref/gui/consistency/ConsistencyCheckDialog.java
Closes #12696 
This PR make sure not to show columns with same values.
=> Leave out same columns in the check consistency results table

CHANGELOG.md, src/main/java/org/jabref/gui/journals/AbbreviateAction.java
Fixes https://github.com/JabRef/jabref/issues/12634
=> Fix threading issue in abbreviate action

.github/ghprcomment.yml
Triggered by https://github.com/JabRef/jabref/pull/12678#issuecomment-2724222903
Maybe we should just link documentation?
=> Refine mesasge for merge-conflicts

src/test/java/org/jabref/logic/importer/fetcher/ACMPortalFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/CrossRefTest.java
=> Disable ACM, because not working on CI

.github/workflows/deployment-jdk-ea.yml, build.gradle
https://gluonhq.com/products/javafx/openjfx-24-release-notes/#24
=> Update to javafx 24

CHANGELOG.md, src/main/java/org/jabref/logic/journals/JournalAbbreviationLoader.java
Fixes https://github.com/JabRef/jabref/issues/12776
=> Catch invalid Path exception in journal loading

README.md
Using latest badge.
Refs https://github.com/APIdia-net/apidia.net/issues/2#issuecomment-2741292851
=> Update APIdia badge

.github/ghprcomment.yml
[Optional]
Trigger: https://github.com/JabRef/jabref/pull/12815#issuecomment-2750902040
Contributor had marked the mandatory checks, but one was not in the correct format. Specifically, `[ ]` was marked as `[]`.
=> Refine comment on mandatory checks format

.github/ghprcomment.yml, .github/workflows/tests.yml
[As per internal discussion]
Contributors often overwrite/remove the mandatory checks from the PR description.
=> Validate existence of Mandatory Checks section

build.gradle
=> Jacoco 0.8.13 is now released

.github/workflows/on-issue-comment.yml
Add @InAnYan's username to the "maintainers" list for the assign me action.
- [/] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to …
=> Assignment action rights: add Ruslan

src/main/java/org/jabref/gui/frame/MainMenu.java, src/main/java/org/jabref/gui/help/HelpAction.java, src/main/java/org/jabref/gui/util/URLs.java
Closes _____
Describe the changes you have made here: what, where, why, ...
If your work is not yet complete, please open a draft pull request. In that case, outline your intended next steps. Do you need feedback? Will you continue in parallel? ... …
=> fix donations url

src/main/java/org/jabref/gui/maintable/MainTable.java
=> Fix writing of example entry

.github/ghprcomment.yml, .github/workflows/on-pr-opened-updated.yml
Closes _____
Describe the changes you have made here: what, where, why, ...
If your work is not yet complete, please open a draft pull request. In that case, outline your intended next steps. Do you need feedback? Will you continue in parallel? ...
- [.] [Checked documentation](https://docs.jabref.org/): Is …
=> Reenable commenting on missing issue number

src/main/java/org/jabref/model/database/BibDatabase.java, src/main/java/org/jabref/model/database/KeyChangeListener.java
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/868
Follow up to #12926
=> Fix NPE when no citekey available

.github/ghprcomment.yml
Triggered by https://github.com/JabRef/jabref/pull/12975#issuecomment-2822755602
Proposal for more soft tone...
- [.] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even …
=> Refine no-force-push

jablib/src/main/java/org/jabref/model/database/BibDatabaseContext.java
=> Add `@return` to `getFileDirectories`

.github/workflows/deployment.yml
Ported from https://github.com/JabRef/jabref/pull/13036
- [.] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation …
=> Fix environment variable JAVA_HOME

.github/workflows/deployment.yml
=> Fix path for artifacts

jabgui/build.gradle.kts, jabgui/buildres/mac/JabRef-dmg-setup.scpt
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/901
- [.] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the …
=> readd dmg position script

README.md
This will help new developers that are not familiar with the build system in getting a working version quickly.  The link was previously "hidden" under the "Installation" title, which does not really fit that purpose.
Please also see the accompanying documentation PR at https://github.com/JabRef/user-documentation/pull/563.
=> Add link to instructions for building from sources in `README.md`

docs/architecture-and-components.md, docs/code-howtos/index.md, docs/index.md
For all labels starting with `component:`, a small explanation and link to documentation is added.
Moreover, the general architecture is moved to a seperate .md file …
=> Create "Architecture and Components"

jabgui/src/main/java/org/jabref/gui/maintable/MainTable.java, jablib/src/main/java/org/jabref/logic/bibtex/BibEntryWriter.java
While commenting on a PR, I found some small things to improve in the code.
- [.] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to …
=> minor-code-updates

jabgui/src/main/java/org/jabref/gui/preferences/PreferenceTabViewModel.java, jabgui/src/main/java/org/jabref/gui/preferences/entryeditor/EntryEditorTabViewModel.java
Some micro code updates (highlighting of TODO text in IntelliJ) …
=> Micro code updates

jabgui/src/main/java/org/jabref/gui/fieldeditors/FieldNameLabel.java, jabgui/src/main/java/org/jabref/gui/preferences/PreferenceTabViewModel.java, jabgui/src/main/java/org/jabref/gui/preferences/PreferencesTab.java, jablib/src/main/resources/l10n/JabRef_en.properties, jablib/src/main/resources/resource/layout/din1505/README.txt
Fixes spacing - e.g. consistently without space …
=> Change e. g. to e.g.

README.md
Follow-up to https://github.com/JabRef/jabref/pull/13123 and https://github.com/JabRef/jabref/pull/13114
=> Add JabKit to README.md

flatpak/org.jabref.jabref.desktop, jabgui/build.gradle.kts, snap/snapcraft.yaml
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/926
- [.] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the …
=> Refine descriptions for linux store entries

docs/decisions/0045-use-input-flag-always-for-inpüut-files.md
Follow-up to https://github.com/JabRef/jabref/pull/13158#discussion_r2106253157
- [/] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request …
=> Create ADR 0045 for --input

.github/workflows/on-pr-opened-updated.yml, .github/workflows/unassign-issues.yml
This improves conditions of our workflows so that they work better on forks.
- [/] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to …
=> Refine conditions of workflows

.github/ghprcomment.yml
Triggered by https://github.com/JabRef/jabref/pull/13174#issuecomment-2914024977
I think, the ucrrent text is too long. And we need to say "correctly", because some students use the wrong syntax.
- [.] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I …
=> Refine text for referencing

rewrite.yml
Refs https://github.com/JabRef/jabref-issue-melting-pot/issues/937
Files upstream issue https://github.com/openrewrite/rewrite-static-analysis/issues/580 …
=> Disable non-working rule

.github/PULL_REQUEST_TEMPLATE.md
On some PRs, I see what is changed, but I need much knowledge of the issue to know how to test.
I think, the contributors should know how to test - then, they can also describe the steps.
- [.] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created …
=> Add testing instructions to PR template

.github/dependabot.yml
=> try to speficy the dirs separate

.github/workflows/unassign-issues.yml
We wanted to include the [JabRef DeepWiki page](https://deepwiki.com/JabRef/jabref). This PR does this.
- [/] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I …
=> Refine assignment reminder

docs/code-howtos/faq.md
Closes #_____
In about one to three sentences, describe the changes you have made: what, where, why, ...
Describe how reviewers can test this fix/feature. Ideally, think of how you would guide a beginner user of Jabef to try out your change.
You can add screenshots or videos (using [Loom](https://www.loom.com/) or by just adding .mp4 files).
- [.] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I …
=> Add alls submodule path for fixing

.github/workflows/binaries.yml
=> fix deletion again

.github/workflows/on-pr-closed.yml
Follow-up to https://github.com/JabRef/jabref/pull/13316
Triggered from https://github.com/JabRef/jabref/issues/13109#issuecomment-2981210514
=> Try to fix wrong issue "fixed" linking

jablib/build.gradle.kts
Fixes https://github.com/jabref/jabref/issues/13423
Follow-up to https://github.com/JabRef/jabref/pull/13401
- [/] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even …
=> Explicitely pin dependencies

jablib/src/main/java/org/jabref/model/entry/BibEntry.java, jablib/src/test/java/org/jabref/model/entry/BibEntryTest.java
Closes #13426 
- Switched to StringBuilder for improved performance and readability.
- Ensured authors are formatted correctly using AuthorList.fixAuthorLastNameOnlyCommas.
- Applied LatexToUnicodeAdapter.format for proper LaTeX-to-Unicode conversion in titles.
=> update getAuthorTitleYear method

.github/workflows/tests.yml, build-logic/src/main/kotlin/org.jabref.gradle.base.dependency-rules.gradle.kts
Implements https://github.com/gradlex-org/extra-java-module-info/issues/188#issuecomment-3034660271
- [/] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I …
=> Try option 1 of fix

.jbang/JabSrvLauncher.java
In https://github.com/JabRef/jabref/pull/13447 changes to JabSrvLauncher were missing and making the jbang build test fail. This should fix this. …
=> fixes jbang jabsrvlauncher build failing 

jabgui/src/main/java/org/jabref/gui/walkthrough/declarative/NavigationPredicate.java
Closes N/A
Apply additional fixes according @koppor (https://github.com/JabRef/jabref/pull/13182)
N/A
=> Additional fixes to walkthrough infrastructure

.jbang/JabSrvLauncher.java
In https://github.com/JabRef/jabref/pull/13457 changes to JabSrvLauncher were missing and making the jbang build test fail. This should fix this. …
=> fix jbang run failing

jablib/src/test/java/org/jabref/logic/citationstyle/CitationStyleGeneratorTest.java, jablib/src/test/java/org/jabref/logic/openoffice/oocsltext/CSLFormatUtilsTest.java
Closes https://github.com/JabRef/jabref/issues/13420
1. Run `CSLFormatUtilsTest` in IntelliJ or with `./gradlew jablib:test`.
2. Confirm that all tests pass without assertion errors related to month name mismatches.
> **Note:**  
> To meet the current issue requirements, the modified test code **does not pass yet**.  
> The test expectations have been aligned with the actual output, but there are still discrepancies that need to be resolved.
=> test: adapt CSLFormatUtilsTest expectations to use full month name 'July'

CHANGELOG.md
=> Remove duplicate CHANGED heading

docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/eclipse.md, docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-89-run-with-intellij.md, docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/vscode.md
=> Refine warnings

.jbang/README.md, .vscode/ltex.dictionary.en-US.txt, README.md
Reinfes main `README.md` more - and also `.jbang/README.md`
- [/Tests created for changes (if applicable) …
=> Refine README.md for running JabKit

jabgui/src/main/java/org/jabref/gui/externalfiles/AutoSetFileLinksUtil.java, jabgui/src/main/java/org/jabref/gui/externalfiles/UnlinkedFilesCrawler.java
- [/[Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.
=> Minor JavaDoc updates

.devcontainer/devcontainer.json, .sdkmanrc
=> update java vendor in devcontainer and sdkmanrc

docs/decisions/0047-use-references-heading-in-citations-tab.md
Refs https://github.com/JabRef/jabref/pull/13620 …
=> Add ADR-0047

build-support/src/main/java/CitationStyleCatalogGenerator.java, jablib/src/main/java/module-info.java, jablib/src/main/java/org/jabref/logic/citationstyle/CSLStyleLoader.java, jablib/src/main/java/org/jabref/logic/citationstyle/CitationStyle.java
Follow-up to https://github.com/JabRef/jabref/pull/13728#issuecomment-3214688985
Alternative to https://github.com/JabRef/jabref/pull/13733
./gradlew :jabguil:run
- [/] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull …
=> Add backwards compatibililty for citation style cache

.github/workflows/tests-pr.yml
Triggered from https://github.com/JabRef/jabref/pull/13771
=> Adapt PR checklist test

jablib/build.gradle.kts
Quickfix
- [.] I added JUnit tests for changes (if applicable)
- [.] I added screenshots in the PR description (if change is visible to the user)
- [.] I described the change in `CHANGELOG.md` in a way that is understandable for the average user (if change is visible to the user)
- [.] I checked the [user documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request updating file(s) in <https://github.com/JabRef/user-documentation/tree/main/en>.
=> Fix warnings about native access in jablib

jabgui/src/main/java/org/jabref/gui/consistency/ConsistencyCheckDialogViewModel.java, jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java, jablib/src/test/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckTest.java
Follow-up to https://github.com/JabRef/jabref/pull/13584.
Fixes consistency check to handle unknown entry types again.
(Also to https://github.com/JabRef/jabref/pull/12433)
Minor code refactorings.
Run consistency check
- [/] I checked the [user documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull …
=> Improve ConsistencyCheck code (and one minor other code place)

jablib/src/main/java/org/jabref/logic/importer/fileformat/BibtexParser.java
Just some small spelling fixes
=> Spell "BibDesk" with capital "D"

jablib/src/main/java/org/jabref/logic/ai/ingestion/MVStoreEmbeddingStore.java, jablib/src/main/java/org/jabref/logic/ai/util/MVStoreBase.java
NA, internal refactor
Fixes jbang tests
=> Use jspecify annotations

config/IntelliJ Code Style.xml
Pre-condition for https://github.com/JabRef/jabref/pull/13872
Risen by https://github.com/JabRef/jabref/pull/13872#issuecomment-3288627249
- [/] I checked the [user documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request updating file(s) in …
=> Fix record wrapping

jabgui/src/main/java/org/jabref/migrations/PreferencesMigrations.java
Fixes https://github.com/JabRef/jabref/issues/13898
Follow-up to #13699
1. Switch to other language
2. Start JabRef
=> Put config for general tab if missing

jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java
I had dozens of exceptions while running LSP:
```
caused by: java.lang.AssertionError
at org.jabref.jablib/org.jabref.logic.quality.consistency.BibliographyConsistencyCheck.check(BibliographyConsistencyCheck.java:149)
at org.jabref.jabls/org.jabref.languageserver.util.LspConsistencyCheck.check(LspConsistencyCheck.java:27)
at org.jabref.jabls/org.jabref.languageserver.util.LspDiagnosticHandler.computeDiagnostics(LspDiagnosticHandler.java:93)
at org.jabref.jabls/org.jabref.languageserver.util.LspDiagnosticHandler.computeAndPublishDiagnostics(LspDiagnosticHandler.java:54)
at org.jabref.jabls/org.jabref.languageserver.BibtexTextDocumentService.didOpen(BibtexTextDocumentService.java:36)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at …
```
=> Remove wrong `assert` statement

.gitignore
Follow-up to https://github.com/JabRef/jabref/pull/13913
see ´git gui`  not showing any strange files in `.idea/` any more.
- [.] I manually tested my changes in running JabRef (always required)
- [.] I added JUnit tests for changes (if applicable)
- [.] I added screenshots in the PR description (if change is visible to the user)
- [.] I described the change in `CHANGELOG.md` in a way that is understandable for the average user (if change is visible to the user)
- [.] I checked the [user documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request updating file(s) in <https://github.com/JabRef/user-documentation/tree/main/en>.
=> Refine .gitginore
