JabRef/jabref

CHANGELOG.md, src/main/java/org/jabref/logic/cleanup/Cleanups.java, src/main/java/org/jabref/logic/cleanup/FieldFormatterCleanups.java, src/main/java/org/jabref/logic/importer/fileformat/BibtexParser.java, src/test/java/org/jabref/logic/cleanup/CleanupsTest.java, src/test/java/org/jabref/logic/exporter/FieldFormatterCleanupsTest.java, src/test/java/org/jabref/logic/importer/fileformat/BibtexParserTest.java
During crafting tests for the syntax, we noticed that save actions were not correctly parsed in some cases.
=> Fix parsing of save actions

CHANGELOG.md, src/main/java/org/jabref/logic/crawler/StudyYamlParser.java, src/main/java/org/jabref/model/study/Study.java, src/test/java/org/jabref/logic/crawler/StudyYamlParserTest.java, src/test/resources/org/jabref/logic/crawler/study-jabref-5.7.yml
Follow-up to https://github.com/JabRef/jabref/pull/9116
=> Fix parsing of JabRef v5.7 study.yml files

src/main/java/org/jabref/gui/slr/StartNewStudyAction.java, src/main/java/org/jabref/logic/crawler/StudyRepository.java, src/main/java/org/jabref/logic/git/SlrGitHandler.java, src/test/java/org/jabref/logic/crawler/CrawlerTest.java, src/test/java/org/jabref/logic/crawler/StudyDatabaseToFetcherConverterTest.java, src/test/java/org/jabref/logic/crawler/StudyRepositoryTest.java, src/test/java/org/jabref/logic/crawler/StudyYamlParserTest.java
Follow-up on https://github.com/JabRef/jabref/pull/9116 
`study.yml` is not modified any more during a call.
=> "study.yml" is static now

src/main/java/org/jabref/gui/mergeentries/newmergedialog/PersonsNameFieldRowView.java
=> Don't show the info button when the authors field content is identical

src/main/java/org/jabref/gui/JabRefFrame.java
I think, the binding was called twice for databases opened at startup.
=> Remove double stateManager.activeDatabaseProperty()

CHANGELOG.md, src/main/java/org/jabref/logic/importer/util/FileFieldParser.java, src/main/java/org/jabref/logic/util/io/FileNameCleaner.java, src/main/java/org/jabref/logic/util/io/FileUtil.java, src/main/java/org/jabref/model/entry/LinkedFile.java, src/main/java/org/jabref/model/util/FileHelper.java, src/test/java/org/jabref/architecture/MainArchitectureTests.java, src/test/java/org/jabref/logic/importer/util/FileFieldParserTest.java, src/test/java/org/jabref/model/util/FileHelperTest.java
Fixes https://github.com/JabRef/jabref/issues/8991#issuecomment-1214131042
Follow-up to https://github.com/JabRef/jabref/issues/8786
=> Linked files with an absolute path can be opened again

src/main/java/org/jabref/gui/collab/ExternalChangesResolverDialog.fxml
Using 'Cancel' is more accurate since closing the dialog will cancel any resolved changes.
=> Rename 'Close' to 'Cancel' in the External Changes Resolver dialog

src/main/java/org/jabref/gui/LibraryTab.java
Commit d8b48dd1ea8034df583b23dadb69a022566131f1 introduced a bug that
prohibited the fulltext-indexer to start.
It now uses the OpenDatabaseAction that does not trigger the indexing
listener. This suggests that openinga new library never triggered an
index-creation as that always used that action.
=> Fix index-creation

src/main/java/org/jabref/gui/shared/SharedDatabaseUIManager.java
Currently, the dialog has no title.
=> Set 'Update refused' dialog title

CHANGELOG.md, src/main/java/org/jabref/logic/formatter/casechanger/TitleCaseFormatter.java, src/main/java/org/jabref/logic/formatter/casechanger/Word.java, src/test/java/org/jabref/logic/formatter/casechanger/SentenceCaseFormatterTest.java, src/test/java/org/jabref/logic/formatter/casechanger/TitleCaseFormatterTest.java
Fixes https://github.com/JabRef/jabref/issues/9102
Fixes https://github.com/JabRef/jabref/issues/9112
What: I implemented a change to the Word.java file so that the code that capitalize any part of a title that follows one of the characters from the en-dash list, like "-", "~" or "〰" on the Title Case method is limited only to the Title Case and not other Scenarios ( like Sentence Case). The changes made as part of [#9102](https://github.com/JabRef/jabref/issues/9102) made changes to the common method used by all types of Cases but the issue fix primarly aimed at the Title case and not other cases. Created a seperated method to handle only Title Case . 
For example, the title "wetting-and-drying cycle and others effects becomes "Wetting-And-Drying Cycle and Others Effects" instead of the …
=> Anomaly with Title case and Sentence case #9112

build.gradle, src/main/java/org/jabref/gui/StateManager.java, src/main/java/org/jabref/gui/actions/ActionHelper.java, src/main/java/org/jabref/gui/groups/GroupTreeView.java, src/main/java/org/jabref/gui/maintable/BibEntryTableViewModel.java, src/main/java/org/jabref/gui/util/OptionalObjectProperty.java, src/main/java/org/jabref/model/entry/BibEntry.java
=> Update to jfx 19

.devcontainer/devcontainer.json
Similar to the config for gitpod, we add a config for Github's codespaces. Compilation works. Moreover, one can run the compiled version (in the browser) buy following the steps at https://github.com/devcontainers/features/blob/main/src/desktop-lite/NOTES.md#connecting-to-the-desktop and then opening a terminal, and running jabref via `gradle run`.
=> Add config for codespaces

CHANGELOG.md, src/main/java/org/jabref/logic/cleanup/FieldFormatterCleanup.java, src/main/java/org/jabref/logic/cleanup/FieldFormatterCleanups.java, src/main/java/org/jabref/model/metadata/ContentSelector.java, src/main/java/org/jabref/model/metadata/MetaData.java
Fixes #9159
Generate new equals, hashcode for FieldFormatterCleanup and toString methods
=> Fix saving triggers metadata changed

CHANGELOG.md, src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/logic/pdf/search/indexing/DocumentReader.java
PdfIndexing is improved in two ways:
- fix a bug that caused re-indexing on each start of JabRef
- add an empty entry to the index for files JabRef was not able to read (happens a lot due to missing fonts). This way JabRef knows the file was already read and will not try again on the next start (assuming the read would fail again).
Fixes #8420
=> Improve startup-behavior of pdf indexer

build.gradle
This removes [Java Flight Recorder](https://docs.oracle.com/javacomponents/jmc-5-4/jfr-runtime-guide/about.htm#JFRUH170)
> Java Flight Recorder requires a commercial license for use in production.
> [...]
> Java Flight Recorder (JFR) is a tool for collecting diagnostic and profiling data about a running Java application.
I think, we never used it on a user's side, so would remove it for our distribution.
On a case-per-case-basis, we (or some researchers) could include `jdk.jfr` back locally.
=> Remove Java Flight Recorder

CHANGELOG.md, src/main/java/org/jabref/logic/formatter/casechanger/CapitalizeFormatter.java, src/main/java/org/jabref/logic/formatter/casechanger/Word.java, src/test/java/org/jabref/logic/formatter/casechanger/CapitalizeFormatterTest.java
Fixes #9157
Added to a new method to Word (toUpperFirstIgnoreHyphen) that is called in CapitalizeFormatter to capitalize first letter of every word, including words after hyphen characters.
=> "Capitalize" capitalizes words after hyphens

CHANGELOG.md, src/main/java/org/jabref/gui/customentrytypes/CustomizeEntryTypeDialogView.java
Fix missing title for "Customize Entry Types" dialogue
Fixes #9198
=> Fix missing title for "customize entry types" dialogue

.devcontainer/devcontainer.json
For some reason java 18 is no longer available through the "tem" distro. Thus using "sem" now and using the latest improvements to the java-feature to directly install java 18: https://github.com/devcontainers/features/pull/172
=> Improve installation of java 18 in devcontainer

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/contextmenu/DefaultMenu.java
Converting fields that were empty led to a Nullpointer Exception. This PR checks for null strings and replaces the return value with a blank String.
Fixes #9200
=> disable conversions for empty fields

CHANGELOG.md, src/main/java/org/jabref/gui/importer/ImportEntriesViewModel.java, src/main/java/org/jabref/gui/util/BackgroundTask.java, src/main/resources/l10n/JabRef_en.properties
Fixes [#9195](https://github.com/JabRef/jabref/issues/9195)
Updated message when fetcher returns an empty list of entries.
=> Searching for an entry on the web shouldn't take forever

.devcontainer/devcontainer.json, .vscode/settings.json, config/VSCode Code Style.xml
- Add gradle extension
- Add basic vscode config for checkstyle and formatting
=> Improve VSCode config

docs/decisions/0026-use-swings-file-chooser-to-determine-default-directory.md, src/main/java/org/jabref/gui/desktop/JabRefDesktop.java, src/main/java/org/jabref/model/database/BibDatabaseContext.java
=> Add ADR-0026 on using Swing's FileChooser

src/main/java/org/jabref/logic/l10n/Language.java
Enable [Ukrainian](https://en.wikipedia.org/wiki/Ukrainian_language) as language.
=> Add Ukrainian as language

src/main/java/org/jabref/model/entry/BibEntry.java, src/test/java/org/jabref/logic/exporter/BibtexDatabaseWriterTest.java, src/test/java/org/jabref/logic/importer/fileformat/BibtexParserTest.java, src/test/java/org/jabref/migrations/SpecialFieldsToSeparateFieldsTest.java, src/test/java/org/jabref/model/database/BibDatabaseTest.java
Refs and I will hopefully find a way to fixes #9187 
After a while debugging and adding tests everywhere I finally found the culprit. The keyword special field migration calls 
removeKeywords on an entry and that internally calls getKeywords which returns only a Set and readds those
=> As this is now a Set: Poof our duplicate keywords are gone and the library has changed 
Questions to decide: Remove duplicate keywords on save? Probably easiest solution
Refactor migration to keep duplicates?
=>  Opening a file removes duplicate keywords and triggers lib changed

docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace.md
This causes split package issues because its coming from Gradle and from the jdk folder  gradle already pulls it in
=> Remove explicit javafx jmod stuff mentioning from the docs

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fetcher/DOABFetcher.java, src/test/java/org/jabref/logic/importer/fetcher/DOABFetcherTest.java
Fixes #8708.
Previously, the DOAB Fetcher could not obtain the ISBN of a DOAB entry. This PR modifies the URL for DOAB query to include `BITSTREAM` data (where ISBN information can be found). 
Below is an example of the previous and updated URL's for DOAB queries (note the ",bitstreams" suffix)
`PREVIOUS`: https://directory.doabooks.org/rest/search?query=handle:%2220.500.12854/26303%22&expand=metadata
`UPDATED`: https://directory.doabooks.org/rest/search?query=handle:%2220.500.12854/26303%22&expand=metadata,bitstreams
The fetcher can then obtain the ISBN and add the field to the entry accordingly. I am creating this Draft PR to discuss with maintainers that it seems like **_many_** DOAB entries do not have ISBN metadata or `BITSTREAM` objects and so the ISBN may perhaps be unobtainable in …
=> DOAB Fetcher now fetches ISBN and imprint fields where possible

CHANGELOG.md, src/main/java/org/jabref/gui/cleanup/CleanupDialog.java
Fixes #9223 
The content of the dialog for the cleanup entries becomes partially visible when resizing the 
dialog (decreasing the size) vertically or horizontally.
I added a *ScrollPane* and put the content of the *presetPanel* inside this ScrollPane in order to
be able to scroll and view the rest of the content when needed (when the dialog is resized).
**Note:** I put the name of the ScrollPane Object as `scrollPane` but I believe the name can be more significant and coherent 
with the project structure.
I also changed the preferred height to 650, so when the dialog opens, it displays all the initial information without the need 
to display the scroll bar.
While fixing this issue, i noticed that the *CleanupDialog* can be resized with no limits. In other words the size of the dialog …
=> Fix for resizing cleanup entries dialog

src/main/java/org/jabref/gui/shared/SharedDatabaseLoginDialogViewModel.java
Follow-up of  #9000. The problem was that if the folder was set, the autosave tick did not make any difference. Now the tick is "active", i.e. synchronizing to a local database is deactivated even if the folder is set.
=> Make autosave tick in shared database opening dialog active

.github/workflows/refresh-csl-subtrees.yml, src/main/java/org/jabref/logic/citationstyle/CSLAdapter.java, src/main/resources/csl-styles/apa.csl, src/test/java/org/jabref/logic/citationstyle/CitationStyleGeneratorTest.java
Follow up to  #8607
This follow up was necessary because of https://github.com/citation-style-language/styles/pull/6255
- adds apa.csl for test
- fixes tests
- adds mapping as javadoc comment
=> Adjust and make tests for BibTex/Biblatex/CSL mapping more accurate by adding Apa 7th edition

src/main/java/org/jabref/gui/libraryproperties/LibraryPropertiesViewModel.java, src/main/java/org/jabref/gui/libraryproperties/general/GeneralPropertiesView.java
Mainly changing an observable list to an ordinary readonly list, which is sufficient and slightly more performant.
=> Minor code improvements in library properties dialog

.github/workflows/greetings.yml
Introduces a GitHub action that automatically comments and gives advice to first time contributors of the JabRef repository. Only triggers upon assignment of users to an issue.
Relevant documentation:
- https://github.com/actions/first-interaction
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issues
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onevent_nametypes
=> [WIP] Add GitHub action: Greetings.yml - Automates advice to JabRefs first time code contributors

CHANGELOG.md, src/main/java/org/jabref/gui/preferences/PreferencesDialogView.java
Fixes #8888 
The Preferences dialog was not closing when the CLOSE DIALOG key binding was pressed. This was because when the user changed the tab, they needed to click the Preference Tab List. This ListView was not respecting the event handlers that were present on the dialog. To resolve this, an 'onKeyReleased' event was added to the ListView. The Preferences tab now closes when the CLOSE DIALOG key binding is pressed.
=> Preferences dialog now closes on CLOSE DIALOG key binding

src/main/java/org/jabref/cli/Launcher.java, src/main/java/org/jabref/gui/MainApplication.java
=> Test launcher mac menu

src/main/java/org/jabref/gui/groups/GroupTreeView.java, src/main/resources/l10n/JabRef_en.properties
Fixes Issue: #9304 
Added A-Z to the translation key in the GroupTreeView.java and JabRef_en.properties files
=> Fix for issue 9304

.github/workflows/deployment.yml
We want to have the GitHub actions green for external contributors.
=> Add skips for MacOS X build

CHANGELOG.md, src/main/java/org/jabref/logic/util/io/CitationKeyBasedFileFinder.java, src/test/java/org/jabref/logic/util/io/CitationKeyBasedFileFinderTest.java
Fixes #9267 
This aims to fix the issue where it is impossible to find the related file when the citation key involves some characters (e.g. `:`) that cannot be contained in the file name. 
We fix this issue by searching the related file with the citation key where its unsafe characters are replaced with underscores `_`. (See [#9267](https://github.com/JabRef/jabref/issues/9267))
- Input a citation key with an unsafe character (colon ":")   
- Before  
- After  
**Note: The user should reopen the library to see the attachment**
=> Fix issue: Auto-linking files with safe character replacements #9267

CHANGELOG.md, src/main/java/org/jabref/gui/maintable/BibEntryTableViewModel.java
Once applied, entries in the maintable sorted by a special field value are getting updated immediately after their value has changed.
The workaround is necessary because specialFieldValues and entry.fields get updated separately (entry.fields before speicalFieldValues). This lead to the behaviour that when sorting for a special field in the maintaible (like ranking or read status), the sorting does not get updated properly on change.
Closes #9334. (See also the issue for a more detailed description of the underlying problem)
=> Update sorting of entries in maintable by special fields immediately

src/main/java/module-info.java
When compiling JabRef in IntelliJ, I got following error message:
```
...src\main\java\org\jabref\gui\desktop\os\Windows.java:84:9
java: cannot access com.sun.jna.LastErrorException
class file for com.sun.jna.LastErrorException not found
```
We had the libraries in the classpath since the usage of AppDirs:
```
\--- net.harawata:appdirs:1.2.1
\--- net.java.dev.jna:jna-platform:5.6.0
\--- net.java.dev.jna:jna:5.6.0
```
Direct JNA usage was introduced at https://github.com/JabRef/jabref/pull/9222.
Seems, simply, a `requires` statement was missing:
```java
requires com.sun.jna;
```
This PR adds this statement.
=> Adds missing "requires" statement

.github/workflows/cleanup_pr.yml, .github/workflows/deployment.yml, .github/workflows/gource.yml, .github/workflows/snap.yml, .github/workflows/tests.yml
Implements https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Also fixes casing "macos-latest" so that the Mac OS binary should not be build any more for "external" PRs.
=> Switch from set-output to environment files

src/main/java/org/jabref/gui/groups/GroupTreeView.java, src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java
Fixes #9368
Fixes #9360
Briefly, the solution is to add four methods to the various types of groups: **AllowDragInto**, **CanBeDragged**, **isEditable** and **AllowActionOnSelectedEntry**.
**AllowDragInto**, **CanBeDragged**  should solve the problem of authorizaztion to Drag and Drop: during drag and drop, the GroupTreeView queries these methods to know what is allowed to do.
If the drag and drop is successful, in **shared database**, update grouping in the MetaData table.
Adding **isEditable** and **AllowActionOnSelectedEntry**, we can establish which menu items to display for each type of group.
**Note**: I have not tested the TexGroup group.
=> Add Check if groups drag and drop allowed

docs/contributing.md
Fix old link and a add new link in section "good commit messages"
=> Fix link in contributing.md

src/main/java/org/jabref/gui/maintable/MainTable.java, src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java, src/main/java/org/jabref/gui/maintable/MainTableHeaderContextMenu.java
Fixes #6601 **[WIP]**
**The user is able to right-click on the header of a maintable, to toggle the each column(field) visibility. This is also updated in the Entry Table in preferences. This is intended to improve the efficiency of using the program/UI as it will give users one less step from toggling the visibility of fields, instead of clicking through the preferences menus.**
Inspired from #7729, #8762
**Demonstration (Screenshots):**
1. When the user right clicks on the Main Table header, a context menu appears with the most commonly used fields based on the default preferences), and the other currently used fields. A tick next to the item shows whether the column is visible in the table. The seperator in the table distinguishes between commonly and currently used fields. 
2. When an …
=> Fix for issue: right click menu 6601

CHANGELOG.md, src/main/java/org/jabref/model/util/FileHelper.java
Fixes https://github.com/JabRef/jabref/issues/9386
The user created a new library, but did not save the library. Thus, we had no path to resolve the (absolute) filename.
=> Return absolute path in case an absolute one is given

src/main/java/org/jabref/gui/LibraryTab.java
Fixes #9440
Works so far. Just needs some code style polish I think
Changelog not necessary as this was working fine in the lats release
=> Update database context in state manager after loading

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/gui/collab/DatabaseChange.java, src/main/java/org/jabref/gui/collab/DatabaseChangesResolverDialog.java, src/main/java/org/jabref/gui/dialogs/BackupUIManager.java, src/main/java/org/jabref/gui/importer/actions/OpenDatabaseAction.java
Fixes https://github.com/koppor/jabref/issues/637 and refines some other code.
=> Fix GroupTree wrongly displayed

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/logic/autosaveandbackup/BackupManager.java, src/main/java/org/jabref/logic/util/BuildInfo.java, src/main/java/org/jabref/logic/util/io/BackupFileUtil.java, src/test/java/org/jabref/logic/autosaveandbackup/BackupManagerTestDiscarded.java, src/test/java/org/jabref/logic/util/BuildInfoTest.java
Fixes https://github.com/JabRef/jabref/issues/9361
=> Add "discarded" flag to backups

CHANGELOG.md, src/main/java/org/jabref/gui/preferences/PreferencesDialogView.java
Fixed #9017 
Closes #9242 
Just a little bit more space to breathe (10 px)
before:
after:
=> Fixed controls outgrow preferences dialog

CHANGELOG.md, src/main/java/org/jabref/logic/importer/WebFetchers.java, src/test/java/org/jabref/logic/importer/fetcher/CiteSeerTest.java, src/test/java/org/jabref/logic/importer/fetcher/MedlineFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/SemanticScholarTest.java
=> Fix fetcher tests

CHANGELOG.md, src/main/java/org/jabref/logic/importer/CompositeIdFetcher.java, src/main/java/org/jabref/logic/importer/WebFetchers.java, src/main/java/org/jabref/logic/importer/fileformat/PdfMergeMetadataImporter.java, src/test/java/org/jabref/logic/importer/fetcher/SemanticScholarTest.java, src/test/java/org/jabref/logic/importer/fetcher/isbntobibtex/DoiToBibtexConverterComIsbnFetcherTest.java
The DoiToBibtexConverterComIsbnFetcher fetcher bases on https://doi-to-bibtex-converter.herokuapp.com/. That page is sort of 404:
=> Disable DoiToBibtexConverterComIsbnFetcher

src/main/java/org/jabref/gui/citationkeypattern/GenerateCitationKeyAction.java, src/main/java/org/jabref/gui/commonfxcontrols/CitationKeyPatternPanel.java, src/main/java/org/jabref/gui/commonfxcontrols/CitationKeyPatternPanelViewModel.java, src/main/java/org/jabref/gui/libraryproperties/keypattern/KeyPatternPropertiesView.java, src/main/java/org/jabref/gui/preferences/PreferencesDialogViewModel.java, src/main/java/org/jabref/gui/preferences/citationkeypattern/CitationKeyPatternTab.java, src/main/java/org/jabref/gui/preferences/citationkeypattern/CitationKeyPatternTabViewModel.java, src/main/java/org/jabref/gui/shared/SharedDatabaseUIManager.java, src/main/java/org/jabref/logic/bibtex/comparator/MetaDataDiff.java, src/main/java/org/jabref/logic/citationkeypattern/CitationKeyGenerator.java, src/main/java/org/jabref/logic/citationkeypattern/CitationKeyPatternPreferences.java, src/main/java/org/jabref/migrations/PreferencesMigrations.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/main/java/org/jabref/preferences/PreferencesService.java, src/test/java/org/jabref/logic/citationkeypattern/CitationKeyGeneratorTest.java, src/test/java/org/jabref/logic/citationkeypattern/MakeLabelWithDatabaseTest.java, src/test/java/org/jabref/logic/citationkeypattern/MakeLabelWithoutDatabaseTest.java, src/test/java/org/jabref/logic/crawler/CrawlerTest.java, src/test/java/org/jabref/logic/crawler/StudyRepositoryTest.java, src/test/java/org/jabref/logic/integrity/IntegrityCheckTest.java
=> Observable Preferences R (CitationKeyPatternPreferences)

CHANGELOG.md, src/main/java/org/jabref/preferences/JabRefPreferences.java
=> Fix remember last open valid library with empty new one

buildres/mac/jabrefHost.py
Fixes #9474
The previous MacOS hardcoded path fails if JabRef is installed to a users local applications directory rather than the system one (e.g. if the user doesn't have admin permissions). On my version of MacOS (12.6.1) and python (3.9.6) this change works correctly for local installs as well as global. The Mac app bundle is structured differently so an alternate path is still required.
If the difference in `which` behaviour is still a problem (maybe on older versions/different python versions?) the original hardcoded fallback could also be included as a final option. If that is still necessary the explanatory comment should be updated too, as should the docs to detail when the hardcoded fallback is needed and therefore when users may need to manually update it.
As mentioned on the …
=> Update MacOS jabrefHost.py to find local installs

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupTreeView.java
Regression that was introduced in #9286  
https://discourse.jabref.org/t/how-sort-groups-a-z-not-subgroups/3682
=> Fix no context menu with sorting on all entries group

CHANGELOG.md, src/main/java/org/jabref/gui/preferences/preview/PreviewTab.java
=> Add double click on preview style to add/remove from the selected list

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/DateEditorViewModel.java, src/main/java/org/jabref/model/entry/Date.java, src/test/java/org/jabref/model/entry/DateTest.java
Fixes #9492 
Basically moved the uuuu/M up, so the year does not get parsed as month
=> Fix date parser for year/month

.github/workflows/refresh-journal-lists.yml, CHANGELOG.md
Fixes https://github.com/JabRef/abbrv.jabref.org/issues/91
Note that the (current) version of https://github.com/JabRef/jabref/pull/9504 works fine (because all strings of that IEEE list are simply overwritten). However, there may be updates.
=> Remove journal_abbreviations_ieee_strings.csv from journal lists

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java, src/main/java/org/jabref/logic/net/URLDownload.java
Fixes #9518
Improved error logging
=> Fix downloading in case of circular redirect

CHANGELOG.md, build.gradle, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditorViewModel.java
=> Fix not on fx thread error when downloading file

CHANGELOG.md, src/main/java/org/jabref/preferences/JabRefPreferences.java
=> Set default button state for fulltext search to false

.github/workflows/deployment-arm64.yml, .github/workflows/deployment.yml, GitVersion.yml
We set the new major version to 6 directly after the last release (https://github.com/JabRef/jabref/commit/e586da37ffec97d44d1a2209988fb5ced0b6f0c4). However, we decided to release version 5.9 inbetween. Thus, we need to rool back.
Possibilities:
- Open a separate branch, cherry-pick all commits but leave out the semver commit. -- I tried with `git rebase -i v5.8`, but that was not good
- Manually set the version
This PR implements the second approach. Note that this will NOT re-open https://github.com/JabRef/jabref/issues/5399 and https://github.com/JabRef/jabref/issues/5657 (linked from 
https://github.com/JabRef/jabref/pull/5682), because the patch number is increased by using the number of commits since the last (hard-coded) release v5.8.
Resulting about dialog:
=> Release v5.9 preparation - set "GitVersion" explicitely

.github/workflows/deployment-arm64.yml, .github/workflows/deployment.yml
The release deployment flow for mac (ARM64) should not intervere with the "normal" deployment flow.
=> Refine notarization for Mac OS build

.github/workflows/deployment-arm64.yml, .github/workflows/deployment.yml
=> Reenable GitVersion

buildres/windows/JabRefHost.ps1
=> chore: improve debug output in powershell starter script

src/main/java/org/jabref/logic/bibtex/comparator/BibDatabaseDiff.java, src/test/java/org/jabref/logic/bibtex/comparator/BibDatabaseDiffTest.java
**Context**
When an external change in the database occurs, JabRef loads the new version of the database and parses it. Then it compares the list of entries on JabRef and the list of entries loaded from the new version. In the comparison logic, JabRef tries to predict what entries were added, deleted, or modified. The logic is straightforward:
- If an entry exists in JabRef's memory but not in the external database then it's **deleted** from outside
- If an entry exists in the external database but not in JabRef's memory then it's **added** from outside
- If an entry exists in both places then it is **modified** from outside
**So how does JabRef know when an entry is modified?**
JabRef doesn't know for sure when an entry is modified but it can make some decent predictions. To decide if …
=> Detect more cases of an entry modified in the external changes resolver dialog

CHANGELOG.md, src/main/java/org/jabref/logic/util/io/FileUtil.java, src/test/java/org/jabref/logic/util/io/FileUtilTest.java
Fixes #9567
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/70
=> Sort unique library suffix by length

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fetcher/DOABFetcher.java
Fixes https://github.com/JabRef/jabref/issues/9571
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/75
=> Fix doab fetcher

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupTreeView.java
Fixes #9281
problem- there was a filter to consume the mouse right click mouse event which disallowed right click to select row but it allowed the context menu row creation for the row
solution- remove the filter as it is made more sense that we will be able to select row with right click also (I checked and windows explorer behaves the same way)
=> remove filter that consumes mouse rightclick

CHANGELOG.md, buildres/linux/jabrefHost.py
Remove overquoting in jabrefHost.py, fixing #9588. On Linux (not MacOS), the script wraps the BibTeX passed to JabRef via CLI parameter in an extra set of ' quotes. Since the data is never evaluated by a shell script, the quotes are passed to JabRef and are stored in the database. This may be the cause for the garbage charactes observed in #9582; however, this fix does not address that issue.
Fixes #9588
=> Remove overquoting in jabrefHost on Linux

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefGUI.java
=> Adding a min width and a min height for the main window

CHANGELOG.md, src/main/java/org/jabref/cli/ArgumentProcessor.java, src/test/java/org/jabref/cli/ArgumentProcessorTest.java, src/test/resources/org/jabref/cli/ArgumentProcessorTestExportMatches.bib
This fixes #9581 by creating an export bib file when the `bib` export format is specified, or when there is no specified export format.
=> Fix command line export for --exportMatches

CHANGELOG.md, src/main/java/org/jabref/gui/preferences/linkedfiles/LinkedFilesTabViewModel.java, src/main/resources/l10n/JabRef_en.properties
Closes #8010 
~~Question: The error is still showing when saving preferences even after choosing to store files relative to the library location. Is this the correct behavior?~~
=> Refine main directory not found error message

src/main/java/org/jabref/logic/importer/fetcher/INSPIREFetcher.java, src/test/java/org/jabref/logic/importer/fetcher/INSPIREFetcherTest.java
Improve [#9602](https://github.com/JabRef/jabref/pull/9602)
Normally, one can fetch information of new arXiv paper in the INSPIRE database, but this entry doesn't have doi in the INSPIRE database because it is preprint and hasn't been published in journal.
After some time, the paper gets published, if one wants to update the entry through "Update with bibliographic information from the web", then doi is unavailable.
So I added a fetcher with arXiv ID.
In addition, I added the post cleanup to keep the consistency between SearchBasedParserFetcher and EntryBasedFetcher.
=> Improve the INSPIREFetcher in "Update with bibliographic information from the web"

src/main/java/org/jabref/gui/journals/AbbreviateAction.java, src/main/java/org/jabref/gui/preferences/journals/JournalAbbreviationsTab.java, src/main/java/org/jabref/gui/preferences/journals/JournalAbbreviationsTabViewModel.java, src/main/java/org/jabref/logic/journals/JournalAbbreviationLoader.java, src/main/java/org/jabref/logic/journals/JournalAbbreviationPreferences.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/main/java/org/jabref/preferences/PreferencesService.java, src/test/java/org/jabref/gui/preferences/journals/JournalAbbreviationsViewModelTabTest.java
=> Observable Preferences S

CHANGELOG.md, src/main/java/org/jabref/logic/importer/WebFetchers.java, src/main/java/org/jabref/logic/importer/fetcher/IacrEprintFetcher.java, src/test/java/org/jabref/logic/importer/fetcher/IacrEprintFetcherTest.java
Adds fulltext fetching for IACR eprint PDFs.
My Java skills are a bit rusty, and while the code works, I'm happy to make additional changes if there are more elegant ways to do things.
I am unsure about whether to add anything to the developer docs on fetchers, as they seem to only cover a subset of all fetchers anyway (so far, the IACR fetcher isn't mentioned at all).
- (not applicable)
- There does not seem to be fetcher-specific documentation for users (regarding fulltext fetching)
=> Fulltext fetcher for IACR eprints

CHANGELOG.md, src/main/java/org/jabref/logic/autosaveandbackup/BackupManager.java
Backups were made without any change (see https://github.com/JabRef/jabref/issues/9488#issuecomment-1445149783). This fixes it.
=> JabRef writes a new backup file only if there is a change.

CHANGELOG.md, src/main/java/org/jabref/cli/Launcher.java, src/main/java/org/jabref/gui/backup/BackupResolverDialog.java, src/main/java/org/jabref/gui/dialogs/BackupUIManager.java, src/main/java/org/jabref/logic/autosaveandbackup/BackupManager.java, src/main/java/org/jabref/logic/util/OS.java, src/main/java/org/jabref/logic/util/io/BackupFileUtil.java, src/main/java/org/jabref/preferences/JabRefPreferences.java
While discussing the backup path with @ThiloteE, I found, we are inconsistent.
Before:
```
├───100.0.0
│   └───backups
├───Logs
│   ├───100.0.0
│   ├───5.7--2022-08-05--73c111c
│   ├───5.8--2022-11-21--f7ea169
│   ├───5.8--2022-12-18--b7fae4b
│   ├───5.9--2023-01-04--bc3b9892f
│   ├───6.0--2023-01-01--b06ec3f
│   ├───6.0--2023-01-04--06771c8
│   └───unknown
├───lucene94
│   ├───-1446191503
│   ├───-1525049150
│   ├───-1981152844
│   ├───-2018577075
│   ├───-271657575
│   ├───-404722334
│   ├───-911001257
│   ├───1750725641
│   ├───1907816293
│   ├───647714185
│   ├───762261717
│   └───unsaved
└───ssl
```
After:
```
├───backups
├───logs
│   └───100.0.0
├───lucene94
│   ├───-1446191503
│   ├───-1981152844
│   ├───-2018577075
│   └───-404722334
└───ssl
```
Note that `logs` is spelled with …
=> Streamline AppDirs paths

src/main/java/org/jabref/gui/mergeentries/newmergedialog/cell/ThreeWayMergeCell.java, src/main/java/org/jabref/logic/layout/format/AuthorLF_FF.java, src/main/java/org/jabref/logic/layout/format/AuthorLF_FFAbbr.java
Fixes https://github.com/koppor/jabref/issues/475
Deleted three empty javadoc comments.
```[tasklist]
- / Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- / Tests created for changes (if applicable)
- / Manually tested changed features in running JabRef (always required)
- / Screenshots added in PR description (for UI changes)
- / [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- / [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation …
```
=> remove empty javadoc comments

CHANGELOG.md, src/main/java/org/jabref/gui/preview/PreviewViewer.java, src/main/java/org/jabref/gui/search/GlobalSearchResultDialog.java
Fixes https://github.com/JabRef/jabref/issues/9362
When nothing has been selected in the Global Search dialog, the preview screen will remain black on dark mode instead of being white.
Moreover when there is an entry in the table, the first entry will also be shown in the preview instead of only being selected on the table.
```[tasklist]
```
=> Global Search UI preview is dark in dark theme when no entry is shown

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java, src/main/java/org/jabref/gui/linkedfile/DeleteFileAction.java, src/main/resources/l10n/JabRef_en.properties
Fixes #9473
Created `DeleteFileAction` class that extends `SimpleCommand`. This class handles both the creation of the dialog that either shows a file name or the amount of files, depending on the selection in the `LinkedFileViewModel`, as well as the unlinking/deletion itself. Also changed the call in `LinkedFilesEditor` when <kbd>Delete</kbd> is pressed to use this new `DeleteFileAction` class.
```[tasklist]
```
---
Deletion of a single file:
Deletion of multiple files:
=> Improved dialog for deletion of multiple files

CHANGELOG.md, build.gradle, src/main/java/module-info.java, src/main/java/org/jabref/logic/layout/format/MarkdownFormatter.java, src/test/java/org/jabref/logic/layout/format/MarkdownFormatterTest.java
To reduce the number of dependencies (due to [JDK-8240567](https://bugs.openjdk.org/browse/JDK-8240567); refs https://github.com/JabRef/jabref/issues/5226), I removed two dependencies IMHO used very seldom.
In the current JabRef, if you select the build-in preview, you get a markdown rendering. This changes now a bit.
Before:
After:
```[tasklist]
```
=> Remove support for Markdown syntax for strikethrough and task lists

.github/workflows/automerge.yml
Checking https://github.com/JabRef/jabref/pull/9643, I see that the automerge action was skipped_
I asked ChatGPT, so let's see if this works:
```[tasklist]
```
=> Try to get auto merge running

src/test/java/org/jabref/logic/citationkeypattern/AbstractCitationKeyPatternTest.java, src/test/java/org/jabref/model/entry/KeywordListTest.java
Decided not to do fix https://github.com/koppor/jabref/issues/163 so we will not replace StringTokenizer.
Related test cases are in this PR
```[tasklist]
```
=> Write test cases for StringTokenizer

CHANGELOG.md, src/main/java/org/jabref/gui/errorconsole/ErrorConsole.css
Fix text color in the event log console when applying dark mode by setting text color to `-fx-text-base-color`. Also, fix the font size of icons before warning logs.
Fixes #9732
```[tasklist]
```
Fixed event log console:
Dark mode:
Light Mode:
=> Fix text color in the event log console when applying dark mode

src/main/java/org/jabref/gui/DefaultInjector.java, src/main/java/org/jabref/gui/JabRefGUI.java, src/main/java/org/jabref/gui/MainApplication.java, src/main/java/org/jabref/gui/SendAsEMailAction.java, src/main/java/org/jabref/logic/importer/fileformat/PdfMergeMetadataImporter.java, src/main/java/org/jabref/model/database/BibDatabaseContext.java
Small cleanups
- Log call
- Wrong class reference for logger
```[tasklist]
```
=> Minor code fixes regarding DefaultInjector

CHANGELOG.md, src/main/java/org/jabref/gui/externalfiles/UnlinkedPDFFileFilter.java, src/main/java/org/jabref/logic/util/io/DatabaseFileLookup.java, src/test/java/org/jabref/gui/externalfiles/UnlinkedFilesCrawlerTest.java
Fixes #9735 
```[tasklist]
```
=> Current library's bib file is removed from the unlinked file search results

CHANGELOG.md, build.gradle, src/main/java/module-info.java
Fixes #9761 
This version seems to work now, the rowset was missing in the module info.
```[tasklist]
```
=> Fix mariadb error

build.gradle
Switch to Java 19 for gradle build
It seems that the toolset around VS Code does not support Java 20. See https://github.com/redhat-developer/vscode-java/issues/3043#issuecomment-1517991699.
I think, we do not use [new features of JDK 20](https://www.infoworld.com/article/3676699/jdk-20-the-new-features-in-java-20.html) yet, thus I propose the downgrade.
JabRef can still be compiled with JDK 20.
```[tasklist]
```
=> Down to JDK19

src/main/java/org/jabref/logic/util/StandardFileType.java
Follow-up to https://github.com/JabRef/jabref/pull/9583. 
Thank @morgantec for the hint - https://github.com/JabRef/jabref/issues/9372#issuecomment-1518549405
```[tasklist]
```
=> Remove BibTeXML from StandardFileType

src/test/java/org/jabref/logic/importer/fetcher/JstorFetcherTest.java
Tests executed locally around midnight in Europe - and they failed. This PR fixes it.
```[tasklist]
```
=> Refine JsorFetcherTest#searchById to ignore urlDate

docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/pre-02-software.md
Fixed link's relative path in "Required Software" documentation
```[tasklist]
```
=> Fix path in devs documentation

CHANGELOG.md, src/main/java/org/jabref/gui/util/FileFilterConverter.java, src/main/resources/l10n/JabRef_en.properties
Fixes #9372 
Change default File Chooser to show supported files extensions
```[tasklist]
```
=> Change default File Chooser to show supported files extensions

src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/logic/exporter/BibtexDatabaseWriter.java, src/main/java/org/jabref/model/entry/event/FieldChangedEvent.java
Sometimes, we use `==` instead of `equals`.
I think, all cases are fine. Nevertheless, the places deserve code comments.
Triggered by applying https://docs.openrewrite.org/recipes/java/cleanup/referentialequalitytoobjectequals
```[tasklist]
```
=> Add comments to == usage instead of equals

build.gradle, rewrite.yml, src/main/java/org/jabref/gui/autocompleter/SuggestionProviders.java, src/main/java/org/jabref/gui/desktop/JabRefDesktop.java, src/main/java/org/jabref/gui/entryeditor/fileannotationtab/FileAnnotationViewModel.java, src/main/java/org/jabref/gui/fieldeditors/FieldEditors.java, src/main/java/org/jabref/gui/fieldeditors/identifier/EprintIdentifierEditorViewModel.java, src/main/java/org/jabref/gui/fieldeditors/identifier/IdentifierEditor.java, src/main/java/org/jabref/gui/journals/UndoableAbbreviator.java, src/main/java/org/jabref/gui/journals/UndoableUnabbreviator.java, src/main/java/org/jabref/gui/search/GlobalSearchBar.java, src/main/java/org/jabref/logic/bibtex/BibEntryWriter.java, src/main/java/org/jabref/logic/bibtex/comparator/FieldComparator.java, src/main/java/org/jabref/logic/citationstyle/JabRefItemDataProvider.java, src/main/java/org/jabref/logic/cleanup/FieldFormatterCleanup.java, src/main/java/org/jabref/logic/database/DuplicateCheck.java, src/main/java/org/jabref/logic/exporter/ModsExporter.java, src/main/java/org/jabref/logic/importer/fileformat/BibtexParser.java, src/main/java/org/jabref/logic/importer/fileformat/PdfMergeMetadataImporter.java, src/main/java/org/jabref/logic/importer/util/IdentifierParser.java, src/main/java/org/jabref/logic/integrity/TypeChecker.java, src/main/java/org/jabref/logic/openoffice/style/OOBibStyleGetCitationMarker.java, src/main/java/org/jabref/logic/xmp/DocumentInformationExtractor.java, src/main/java/org/jabref/logic/xmp/DublinCoreExtractor.java, src/main/java/org/jabref/logic/xmp/XmpUtilWriter.java, src/main/java/org/jabref/model/entry/BibEntry.java, src/main/java/org/jabref/model/groups/WordKeywordGroup.java
Updates openrewrite to most recent version (refs https://github.com/openrewrite/rewrite-gradle-plugin/issues/199)
Enables [CompareEnumsWithEqualityOperator](https://docs.openrewrite.org/recipes/java/cleanup/compareenumswithequalityoperator)
Code looks uncommon, because `==` is used instead of `equals`. Is that OK for us?
```[tasklist]
```
=> Enable CompareEnumsWithEqualityOperator

CHANGELOG.md, src/main/java/org/jabref/logic/importer/CompositeIdFetcher.java, src/main/java/org/jabref/model/entry/identifier/DOI.java, src/test/java/org/jabref/logic/importer/fetcher/CompositeIdFetcherTest.java, src/test/java/org/jabref/model/entry/identifier/DOITest.java
Fixes #9821
Modify org/jabref/logic/importer/CompositeIdFetcher.java to detect and remove ?doi= tag before passing to DOI.parse
Add unit tests to org/jabref/model/entry/identifier/DOITest.java
Update CHANGELOG.md
```[tasklist]
```
=> Detect and remove ?doi= tag before passing to DOI.parse

src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/JabRefGUI.java, src/main/java/org/jabref/gui/documentviewer/DocumentViewerView.java, src/main/java/org/jabref/gui/externalfiles/GitIgnoreFileFilter.java, src/main/java/org/jabref/gui/fieldeditors/identifier/IdentifierEditor.java, src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java, src/main/java/org/jabref/gui/maintable/MainTable.java, src/main/java/org/jabref/gui/mergeentries/MultiMergeEntriesView.java, src/main/java/org/jabref/gui/preferences/keybindings/KeyBindingsTab.java, src/main/java/org/jabref/gui/preferences/preview/PreviewTabViewModel.java, src/main/java/org/jabref/gui/search/GlobalSearchResultDialog.java, src/main/java/org/jabref/gui/search/SearchResultsTable.java, src/main/java/org/jabref/logic/citationstyle/JabRefItemDataProvider.java, src/main/java/org/jabref/logic/l10n/Localization.java, src/main/java/org/jabref/logic/pdf/search/indexing/IndexingTaskManager.java, src/main/java/org/jabref/logic/protectedterms/ProtectedTermsParser.java, src/main/java/org/jabref/logic/util/StandardFileType.java, src/main/java/org/jabref/logic/xmp/DublinCoreExtractor.java, src/main/java/org/jabref/model/ChainNode.java, src/main/java/org/jabref/model/entry/EntryLinkList.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/test/java/org/jabref/gui/search/GlobalSearchBarTest.java, src/test/java/org/jabref/logic/database/DatabaseMergerTest.java, src/test/java/org/jabref/logic/formatter/FormatterTest.java, src/test/java/org/jabref/logic/layout/LayoutHelperTest.java, src/test/java/org/jabref/logic/net/URLDownloadTest.java, src/test/java/org/jabref/logic/shared/DBMSConnectionTest.java, src/test/java/org/jabref/model/TreeNodeTest.java
Manually applies the rule https://docs.openrewrite.org/recipes/java/cleanup/replacelambdawithmethodreference.
Not automatic possible, because of
- https://github.com/openrewrite/rewrite-static-analysis/issues/94
- https://github.com/openrewrite/rewrite-static-analysis/issues/95
- https://github.com/openrewrite/rewrite-static-analysis/issues/86#issuecomment-1537855430
```[tasklist]
```
=> OpenRewrite ReplaceLambdaWithMethodReference

docs/contributing.md
hopefully fixed link to workspace settup guide in dev-docs contibuting.md page
There was a broken link at https://devdocs.jabref.org/contributing.html , I've changed the link in contributing.md which I think should fix it.
Link seemed to work within github but I'm not sure how I'd go about testing it for the actual website. Any help would be appreciated.
```[tasklist]
```
=> Update dev contributing.md

src/main/java/org/jabref/gui/commonfxcontrols/SaveOrderConfigPanel.fxml, src/main/resources/l10n/JabRef_en.properties
"Keep original order" in save preferences is not that clear for the user. Here a proposal with more clarity:
```[tasklist]
```
=> Make consequences of "Keep original order" more clear

src/test/resources/testbib/jabref-authors.bib
`jabref-authors.bib` contained the old special field format. We migrated special fields away from keywords. JabRef silently changes the format without any warning and thus triggers "file changed on disk" errors. This PR fixes that for the concrete file.
```[tasklist]
```
=> Migrate jabref-authors.bib to new format

build.gradle
Enables https://docs.openrewrite.org/recipes/java/logging/slf4j/loggersnamedforenclosingclass
Seems not to work here, see  https://github.com/openrewrite/rewrite-logging-frameworks/issues/105
I would nevertheless merge it.
```[tasklist]
```
=> Enable LoggersNamedForEnclosingClass

CHANGELOG.md, src/main/java/org/jabref/cli/Launcher.java, src/main/java/org/jabref/gui/OpenConsoleAction.java, src/main/java/org/jabref/gui/desktop/JabRefDesktop.java, src/main/java/org/jabref/gui/desktop/os/NativeDesktop.java, src/main/java/org/jabref/gui/desktop/os/Windows.java, src/main/java/org/jabref/gui/fieldeditors/identifier/BaseIdentifierEditorViewModel.java, src/main/java/org/jabref/gui/mergeentries/FetchAndMergeEntry.java, src/main/java/org/jabref/gui/openoffice/DetectOpenOfficeInstallation.java, src/main/java/org/jabref/gui/preferences/externalfiletypes/EditExternalFileTypeEntryDialog.java, src/main/java/org/jabref/logic/importer/fetcher/INSPIREFetcher.java, src/main/java/org/jabref/logic/util/OS.java, src/main/java/org/jabref/logic/util/io/BackupFileUtil.java, src/main/java/org/jabref/model/database/BibDatabaseContext.java, src/main/java/org/jabref/model/pdf/search/SearchFieldConstants.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/main/resources/l10n/JabRef_en.properties, src/test/java/org/jabref/logic/autosaveandbackup/BackupManagerTest.java, src/test/java/org/jabref/logic/util/io/BackupFileUtilTest.java, src/test/java/org/jabref/model/database/BibDatabaseContextTest.java
Follow-up to https://github.com/JabRef/jabref/pull/9584. Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/93.
Lucene-Index is now stored in `lucence/<version>`.
```text
├───backups
├───logs
│   ├───100.0.0
│   ├───5.10--2023-04-06--0111d59
│   └───5.9--2023-01-04--bc3b9892f
├───lucene
│   └───95
│       ├───-369469544
│       └───40622060
└───ssl
```
Thus, `%APPDATA%\..\Local\org.jabref` looks more clean to the user
Discussion was done at https://github.com/JabRef/jabref/pull/9676.
Upgrade from lucene94 to 95 was done after release of JabRef v5.9 and thus this change does not affect users basing on the release version. They will encounter a re-index in all cases.
```[tasklist]
```
=> Change lucene index path to have sub directories

rewrite.yml, src/main/java/org/jabref/gui/JabRefDialogService.java, src/main/java/org/jabref/gui/StateManager.java, src/main/java/org/jabref/gui/duplicationFinder/DuplicateResolverDialog.java, src/main/java/org/jabref/gui/edit/automaticfiededitor/AutomaticFieldEditorDialog.java, src/main/java/org/jabref/gui/importer/ImportAction.java, src/main/java/org/jabref/gui/preferences/customentrytypes/CustomEntryTypesTabViewModel.java, src/main/java/org/jabref/gui/preferences/preview/PreviewTabViewModel.java, src/main/java/org/jabref/logic/importer/fileformat/CustomImporter.java, src/main/java/org/jabref/logic/shared/DBMSProcessor.java, src/main/java/org/jabref/logic/shared/OracleProcessor.java, src/test/java/org/jabref/logic/bibtex/FileFieldWriterTest.java, src/test/java/org/jabref/logic/importer/fetcher/isbntobibtex/EbookDeIsbnFetcherTest.java, src/test/java/org/jabref/logic/openoffice/style/OOBibStyleTest.java
This enables https://docs.openrewrite.org/recipes/java/cleanup/methodparampad.
- Good: ` -> ` always there
- Bad: `new Array[]` is also treated as function, thus no space between `[]` and `{`
```[tasklist]
```
=> Enable MethodParamPad

CHANGELOG.md, src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/logic/util/UpdateField.java, src/test/java/org/jabref/logic/util/UpdateFieldTest.java
I removed some Booleans from the code. I think, the "overWriteOwner" preference is now working. Before, it was always overwritten.
```[tasklist]
```
=> Fix respecting overWriteOwner preferences

src/main/java/org/jabref/logic/exporter/BibWriter.java, src/main/java/org/jabref/logic/exporter/MetaDataSerializer.java, src/main/java/org/jabref/logic/importer/fileformat/BibtexParser.java, src/main/java/org/jabref/logic/importer/util/MetaDataParser.java, src/main/java/org/jabref/model/metadata/MetaData.java, src/test/java/org/jabref/logic/importer/fileformat/BibtexParserTest.java, src/test/java/org/jabref/logic/importer/util/MetaDataParserTest.java, src/test/java/org/jabref/logic/integrity/IntegrityCheckTest.java
My JabRef showed `C:git-repositoriesjabrefsrctestresourcespdfs` as path. Don't know why. I checked the source and modified the parsing logic that JabRef also accepts paths with single \ in the field.
@Comment{jabref-meta: fileDirectory:C:\git-repositories\jabref\src\test\resources\pdfs;}
When JabRef writes, there will be double backslashes.
This PR also modifes the meta data writing code in a way that the trailing ; of each entry could be removed. I think, this should be done for JabRef 6.0. -- Maybe, also a complete rewrite of the metadata serialization could be done (refs https://github.com/koppor/jabref/issues/232)
Minor fixes include
- Rename variable to lower case start
- Use `.withField` in test
```[tasklist]
```
=> Enable single backslashes at fileDirectory

CHANGELOG.md, src/main/java/org/jabref/gui/Globals.java, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/logic/bibtex/comparator/BibDatabaseDiff.java, src/main/java/org/jabref/logic/exporter/BibDatabaseWriter.java, src/main/java/org/jabref/model/database/BibDatabase.java, src/main/java/org/jabref/model/database/BibDatabaseContext.java, src/main/java/org/jabref/model/entry/BibEntry.java, src/main/java/org/jabref/model/entry/field/StandardField.java, src/main/resources/l10n/JabRef_en.properties, src/test/java/org/jabref/logic/exporter/BibtexDatabaseWriterTest.java, src/test/java/org/jabref/model/database/BibDatabaseTest.java, src/test/java/org/jabref/model/entry/BibEntryTest.java
Fixes https://github.com/JabRef/jabref/issues/8645.
Empty entries IMHO do not contain any information.
Exmaple for empty entries:
```bibtex
@misc{}
@article{}
```
With a citation key or any other field, they are not empty:
```bibtex
@misc{test}
@article{test2}
```
This PR adds a functionality so that these entries are automatically removed while writing.
In case they are removed, JabRef will (**udate** NOT) issue a warning "changed on disk". I think, this warning is OK, isn't it?
```[tasklist]
```
=> Remove empty entries automatically

src/main/java/org/jabref/gui/desktop/os/DefaultDesktop.java, src/main/java/org/jabref/gui/desktop/os/Linux.java, src/main/java/org/jabref/gui/desktop/os/OSX.java, src/main/java/org/jabref/gui/desktop/os/Windows.java
=> Make logger instances vars in linux

CHANGELOG.md, src/main/java/org/jabref/logic/importer/util/FileFieldParser.java, src/test/java/org/jabref/logic/importer/util/FileFieldParserTest.java
Fixes https://discourse.jabref.org/t/mendeley-bib-import-with-linked-files/3470. Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/178.
```[tasklist]
```
=> Support for $\backslash$ in file paths

src/main/java/org/jabref/gui/help/ErrorConsoleAction.java, src/main/java/org/jabref/gui/icon/JabRefMaterialDesignIcon.java, src/main/java/org/jabref/gui/util/RecursiveTreeItem.java, src/main/java/org/jabref/gui/util/ViewModelTreeCellFactory.java, src/main/java/org/jabref/logic/citationstyle/CSLAdapter.java, src/main/java/org/jabref/logic/importer/EntryBasedFetcher.java, src/main/java/org/jabref/logic/importer/fetcher/ArXivFetcher.java, src/main/java/org/jabref/logic/importer/fetcher/BiodiversityLibrary.java, src/main/java/org/jabref/logic/importer/fetcher/DOAJFetcher.java, src/main/java/org/jabref/logic/importer/fetcher/DoiResolution.java, src/main/java/org/jabref/logic/importer/fetcher/IEEE.java, src/main/java/org/jabref/logic/importer/fetcher/OpenAccessDoi.java, src/main/java/org/jabref/logic/importer/fetcher/SpringerFetcher.java
This PR fixes half of the javadoc errors.
Refs https://github.com/koppor/jabref/issues/475
Maybe, the other errors are fixed by some contributors or by us later.
```[tasklist]
```
=> Fixes some JavaDoc errors

src/main/java/org/jabref/logic/importer/fileformat/BibtexParser.java, src/test/java/org/jabref/logic/importer/fileformat/BibtexImporterTest.java, src/test/java/org/jabref/logic/importer/fileformat/BibtexParserTest.java
This streamlines tests in BibtexParserTest.
I did not touch all, but I think, even this is an improvement.
```[tasklist]
```
=> Modernize tests at BibtexParserTest

CHANGELOG.md, src/main/java/org/jabref/gui/preferences/table/TableTabViewModel.java
Fixes #9913 
In the `Entry Table` - tab in **Preferences**, you can add custom columns by specifying a name in the combobox below the grid. If you type in something into the textfield and delete it, you can still add a custom column entry into the list, despite the textfield being empty.
We add one more check for the actual textual content to avoid this bug.
```[tasklist]
```
=> Fix empty fields being added to the entry table preferences

CHANGELOG.md, src/main/java/org/jabref/gui/preferences/externalfiletypes/EditExternalFileTypeViewModel.java
Fixes #9895
In **Preferences**, in the **External file types** tab, if an application is set for an entry and you try to edit said entry, the application path doesn't fill in into the selected-application field of the dialog window. This change fixes that by setting that value from the 'external file types' viewmodel.
```[tasklist]
```
=> Add fill in of selectedApplicationProperty when opening the editDialog of external application preference

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fileformat/BibtexImporter.java, src/test/java/org/jabref/logic/importer/fileformat/BibtexImporterTest.java
line.starts with fails on utf bom chars, because the % sign is actually at position 1 and not on pos 0 in the string.
java reads the bom chars as well.
Fixes #9926
```[tasklist]
```
=> Fix UTF bom parsing

.github/PULL_REQUEST_TEMPLATE.md
Task lists are not yet fully supported in PRS:
https://github.com/orgs/community/discussions/39106#discussioncomment-5994408
```[tasklist]
```
=> Revert tasklist for PRs

CHANGELOG.md, src/main/java/org/jabref/logic/citationstyle/JabRefItemDataProvider.java, src/main/java/org/jabref/model/entry/BibEntry.java
Add hint in javadoc
Fixes #9947
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/183
```[tasklist]
```
=> Fix unmodifable Set Exception in generating preview

CHANGELOG.md, src/main/java/org/jabref/gui/desktop/os/Linux.java
Fixes #9953 
The "working directory" arguments to "gnome-terminal" and "konsole" were incorrect due to slight mis-use of ProcessBuilder, which meant they were badly formed and the terminal loaded in a default directory (most likely the user's home dir).
There are currently no tests at all for any of this functionality at a low-level (i.e., what operating system commands are called and with what args), nor any OS-specific test filtering, etc... probably because it is significant and complex to assert a running terminal's directory, especially from a unit test. Therefore, I have intentionally not attempted to add a test because doing so would require considerable refactoring of existing tests (OpenConsoleActionTest), with not much benefit -- and it still might not be possible to truly prove …
=> Fixing "working directory" argument of two of the three Linux "open terminal" commands

src/main/java/org/jabref/model/strings/UnicodeToReadableCharMap.java, src/test/java/org/jabref/logic/citationkeypattern/CitationKeyGeneratorTest.java
Add three test cases for method testCheckLegalKey in org.jabref.logic.citationkeypattern.CitationKeyGeneratorTest.java
Related to the edge cases in #9799 disscussion
Two of the tests fail because they are edge cases. 
To solve this, we need to put more characters in UnicodeToReadableCharMap 
```[tasklist]
```
=> Add test cases in testCheckLegalKey 

build.gradle, rewrite.yml, src/main/java/org/jabref/gui/groups/UndoableMoveGroup.java
This enables [RemoveJavaDocAuthorTag](https://docs.openrewrite.org/recipes/java/cleanup/removejavadocauthortag)
Also updates `org.openrewrite.rewrite` gradle plugin to 5.40.6. Update to 6.0.0 is not possible. I filed an issue at https://github.com/openrewrite/rewrite-gradle-plugin/issues/203.
I also removed all logging recipes, because they were not triggered at all - and 6.0.0 showed some exceptions when they were loaded.
=> OpenRewrite: Enable RemoveJavaDocAuthorTag

src/main/java/org/jabref/gui/ClipBoardManager.java, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/edit/EditAction.java, src/main/java/org/jabref/gui/maintable/MainTable.java
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/187.
No CHANGELOG.md entry, because it worked in 5.9
In the first commit, I did some code improvements:
- JabRefFrame: Use unusaed variable
- EditAction: Keep order of actions consistent
- MainTable: Prevent unnecessary object construction
=> Fix paste of BibTeX data

CHANGELOG.md, src/main/java/org/jabref/gui/slr/ManageStudyDefinition.fxml, src/main/java/org/jabref/gui/slr/ManageStudyDefinitionView.java, src/main/java/org/jabref/gui/slr/ManageStudyDefinitionViewModel.java, src/main/java/org/jabref/gui/slr/StudyCatalogItem.java, src/main/java/org/jabref/logic/crawler/Crawler.java, src/main/java/org/jabref/logic/crawler/StudyCatalogToFetcherConverter.java, src/main/java/org/jabref/logic/crawler/StudyFetcher.java, src/main/java/org/jabref/logic/crawler/StudyRepository.java, src/main/java/org/jabref/model/study/StudyDatabase.java, src/main/resources/build.properties, src/main/resources/l10n/JabRef_ar.properties, src/main/resources/l10n/JabRef_da.properties, src/main/resources/l10n/JabRef_de.properties, src/main/resources/l10n/JabRef_en.properties, src/main/resources/l10n/JabRef_es.properties, src/main/resources/l10n/JabRef_fr.properties, src/main/resources/l10n/JabRef_it.properties, src/main/resources/l10n/JabRef_ja.properties, src/main/resources/l10n/JabRef_ko.properties, src/main/resources/l10n/JabRef_no.properties, src/main/resources/l10n/JabRef_pl.properties, src/main/resources/l10n/JabRef_pt_BR.properties, src/main/resources/l10n/JabRef_ru.properties, src/main/resources/l10n/JabRef_tr.properties, src/main/resources/l10n/JabRef_zh_CN.properties, src/main/resources/l10n/JabRef_zh_TW.properties, src/test/java/org/jabref/gui/slr/ManageStudyDefinitionViewModelTest.java, src/test/java/org/jabref/logic/crawler/StudyCatalogToFetcherConverterTest.java
In Issue #9951, it was instructed to replace the term "database" with "catalog" in the code files `org.jabref.gui.slr` and `org.jabref.logic.crawler`.
Fixes https://github.com/koppor/jabref/issues/615
=> Changed database to catalog in org.jabref.gui.slr and org.jabref.logic.crawler

src/main/java/org/jabref/gui/libraryproperties/contentselectors/ContentSelectorViewModel.java, src/main/resources/l10n/JabRef_en.properties, src/test/java/org/jabref/gui/libraryproperties/contentselectors/ContentSelectorViewModelTest.java
Triggered by https://github.com/JabRef/jabref/pull/9989/files#diff-f1bccc4fe4e0595584a0e84d950cb03c36f9246fa7f5799a526b1d34d1c434be
=> Remove "Field name:" from localization - we already have "Field name"

CHANGELOG.md, src/main/java/org/jabref/logic/cleanup/URLCleanup.java, src/main/java/org/jabref/model/entry/Date.java, src/test/java/org/jabref/logic/cleanup/URLCleanupTest.java
Follow-up to #9970
Fixes [#koppor216](https://github.com/koppor/jabref/issues/216)
Following up to the recently added cleanup operation for the `Url` field, the current proposal serves as a cleanup operation for the `Urldate` field of a BibTex entry.  Essentially, when a date referring to the access date of a URL address is identified in the `Note` field then we move it to the `Urldate` field. Including the aforementioned operation, we achieve more **precise** and **effective** handling of user's mistaken entries' recording.
1. User stores a URL and a corresponding URL-DATE in the `Note` field
2. User clicks on `Quality` section
a. Selects `Cleanup entries` option
b. Enables `Move URL in note field to url field` action
c. Clicks on `OK`
3. Afterwards, the cleanup operation will have been …
=> Add cleanup operation in reference to the Urldate field

src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/entryeditor/EntryEditorPreferences.java, src/main/java/org/jabref/gui/entryeditor/OtherFieldsTab.java, src/main/java/org/jabref/gui/preferences/entryeditor/EntryEditorTabViewModel.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/main/java/org/jabref/preferences/PreferencesService.java
=> Observable Preferences X (EntryEditorPreferences revisited)

src/main/java/org/jabref/logic/importer/util/MetaDataParser.java
I am looking into the diff of https://github.com/JabRef/jabref/pull/10009 and am thinking, where we did "wrong". While submitting a feature request to open rewrite (https://github.com/openrewrite/rewrite-static-analysis/issues/123), I think we can also work on the position of variables.
Creating new Objects takes time in Java. Therefore, constants are put as class variables. I did this for `SINGLE_BACKSLASH`. OK? Or should we keep the constant local, because a) we think, keeping constants as class members is not always appropriate, b) the variables is used only there and c) we don't really care about that micro optimization.
=> Make SINGLE-BACKSLASH private static final

CHANGELOG.md, src/main/java/org/jabref/gui/libraryproperties/saving/SavingPropertiesViewModel.java, src/main/java/org/jabref/gui/preferences/customentrytypes/CustomEntryTypesTabViewModel.java, src/main/java/org/jabref/gui/preferences/export/ExportTabViewModel.java, src/main/java/org/jabref/model/entry/field/FieldFactory.java
Fixes https://github.com/JabRef/jabref/issues/10010
=> Show  more fields for save sort order and export sort order

.github/workflows/deployment.yml
Follow-up to https://github.com/JabRef/jabref/pull/10004
It used to work, but suddenly gradle starts to complain:
Cannot locate tasks that match '.gradle.java.installations.paths=D:\a\_temp\jdk\jdk-21' as project '.gradle.java.installations.paths=D' not found in root project 'JabRef'.
Example: https://github.com/JabRef/jabref/actions/runs/5416997856/jobs/9847443571
This PR tries to fix that.
=> Fix Windows build

src/main/java/org/jabref/gui/help/AboutDialog.css, src/main/java/org/jabref/gui/help/AboutDialog.fxml
Should fix this:
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/210
=> Minor fixes to about dialog

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/actions/StandardActions.java, src/main/resources/l10n/JabRef_en.properties
fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/213
After:
=> GUI: Replace "Close" by "Close library"

CHANGELOG.md, build.gradle, docs/code-howtos/javafx.md, eclipse.gradle, external-libraries.md, src/main/java/module-info.java, src/main/java/org/jabref/gui/Base.css, src/main/java/org/jabref/gui/documentviewer/PdfDocumentPageViewModel.java, src/main/java/org/jabref/gui/fieldeditors/LinkedEntriesEditor.fxml, src/main/java/org/jabref/gui/fieldeditors/LinkedEntriesEditor.java, src/main/java/org/jabref/gui/icon/IconTheme.java, src/test/java/org/jabref/testutils/interactive/styletester/StyleTester.fxml
Sadly JFoenix is not developed anymore. Using JFoenix with JPMS was very clumsy.
- Replaced call to SwingFxUtils with some native code
- Removed JFoenix Colorpicker with vanilla
- Replaced JFoenix Chipview with GemsFX TagView
Turn autocompletion on and restart JabRef to test this.
=> Replaced abandoned JFoenix controls

.github/workflows/deployment.yml
We often write messages like: "The builds should be available in 30mins at builds.jabref.org". With this PR, there will be an automatic message as soon as the binaries got uploaded. In case of another push, there will be a new comment be created (and the old one deleted). This way, the logical order of commits and comments is kept.
=> Add link to build binary

.github/workflows/cleanup_pr.yml
Our directory on the build server grows. See https://builds.jabref.org/pull/.
We had a script for deletion. We, however, changed the directory scheme - without adapting this action.
This PR should fix it.
However, I can only try when a branch is deleted.
Thus, I merge ^^.
=> Try to fix branch deletion

.github/workflows/deployment-arm64.yml, .github/workflows/deployment.yml
This removes upload to GitHub artifact store (to speed up build)
Also:
- Rename (internal) "Deploy" to "Upload"
- Minor fix in deployment-arm64 (follow-up to https://github.com/JabRef/jabref/pull/10041)
This keeps https://github.com/JabRef/jabref/pull/10049 functional.
Old measures:
(From https://github.com/JabRef/jabref/actions/runs/5432766102 / https://github.com/JabRef/jabref/pull/10049)
=> Speedup "deployment" (to builds.jabref.org)

.github/workflows/cleanup_pr.yml
We also have an action adding a link to the build at the PR (https://github.com/JabRef/jabref/blob/9e14b0ec5c544c62d41b1c8af7cecdacdf23df7e/.github/workflows/deployment.yml#L371). We have an action removing the branch on builds.jabref.org (https://github.com/JabRef/jabref/blob/main/.github/workflows/cleanup_pr.yml). Then, the link is 404. Thus, the comment should be deleted. This PR tries that.
=> Update download comment at PR if PR closed

.github/workflows/gource.yml
Hopefully, the csl files should be gone now.
Refs https://github.com/NBprojekt/gource-action/issues/16#issuecomment-1617426933
=> Update gource action

CHANGELOG.md, src/main/java/org/jabref/gui/importer/fetcher/WebSearchPaneViewModel.java, src/main/java/org/jabref/logic/importer/CompositeIdFetcher.java, src/test/java/org/jabref/gui/importer/fetcher/WebSearchPaneViewModelTest.java
This fixes #7575 by adding a pre-processing step to the web search, using `org.jabref.logic.importer.CompositeIdFetcher`.
This is a followup to PR #9969, and extends the logic to cover ISBN and ArXiv ID cases as well.
=> Add ability to use ISBN & ArXiv ID in websearch

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java
This fixes #10017 by removing the sort that was being carried out after group addition and edit
=> Group order reset after adding a new group

.github/workflows/deployment.yml
The notarization was executed for PRs. I think, a brace was missing. I reordered the condition so that it is more consistent to the previous one - and I added the missing brace.
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/231
Example: https://github.com/JabRef/jabref/pull/10066
https://github.com/JabRef/jabref/actions/runs/5459748285/jobs/9936231235?pr=10066
Workflow file:
https://github.com/JabRef/jabref/blob/ffedea2d79f66eff0cabe2a18e3d747a4bed90a3/.github/workflows/deployment.yml#L286
- `steps.checksecrets.outputs.secretspresent == 'YES'` is `false`
- `(startsWith(github.ref, 'refs/tags/') || (${{ inputs.notarization }})) && (steps.checksecrets.outputs.secretspresent == 'YES')` is `true`
=> Fix condition for notarization

.github/workflows/refresh-journal-lists.yml, buildSrc/build.gradle, buildSrc/src/copied/java/org/jabref/logic/journals/JournalAbbreviationLoader.java, buildSrc/src/copied/java/org/jabref/logic/journals/JournalAbbreviationPreferences.java
Working on fixing following:
```
f$ ./gradlew run
> Configure project :
Project : => 'org.jabref' Java module
> Task :run
2023-07-11 20:37:35 [main] org.jabref.cli.Launcher.main()
ERROR: Unexpected exception: org.h2.mvstore.MVStoreException: The read format 2 is smaller than the supported format 3 [2.2.220/5]
at com.h2database.mvstore@2.2.220/org.h2.mvstore.datautils.newmvstoreexception(datautils.java:996)
```
There are also build errors when the update workflow is triggered manually:
https://github.com/JabRef/jabref/actions/runs/5527607325/jobs/10083532466
```
Starting a Gradle Daemon (subsequent builds will be faster)
/home/runner/work/jabref/jabref/buildSrc/src/copied/java/org/jabref/logic/journals/JournalAbbreviationPreferences.java:5: error: package javafx.beans.property does not …
```
=> Try to fix .mv

CHANGELOG.md, src/main/java/org/jabref/gui/libraryproperties/constants/ConstantsPropertiesView.java, src/main/java/org/jabref/gui/libraryproperties/constants/ConstantsPropertiesViewModel.java, src/test/java/org/jabref/gui/libraryproperties/constants/ConstantsPropertiesViewModelTest.java
The string defined in a BibTeX file were shown in random order in the respective GUI editor. While the code already sorts them, by storing the items into a set, it destroys the order again. Fix this behaviour by storing them as a list, which retains the order.
=> Fix order of string in editor

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefGUI.java, src/main/java/org/jabref/preferences/GuiPreferences.java, src/main/java/org/jabref/preferences/JabRefPreferences.java
Fixes https://github.com/JabRef/jabref/issues/4939
=> Fix window pos not remembered

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupTreeView.java, src/main/java/org/jabref/gui/util/ViewModelTreeTableRowFactory.java
Fixing bug introduced in https://github.com/JabRef/jabref/pull/9728 which undid/broke this improvement: https://github.com/JabRef/jabref/pull/8785, which prevented the group node from being selected when the user is just attempting to expand or shrink the tree node. Now, once again, the mouse click is handled and consumed at the capture stage if the expansion pane is clicked, therefore preventing the node from being selected.
=> Fixing unwanted tree group node expansion selection bug

.github/workflows/tests.yml
This adds https://github.com/marketplace/actions/merge-conflict-finder.
We sometimes have git merge conflict markers when merging CSL updates. This action ensures that we notice it early.
=> Add git merge conflict finder

.github/workflows/refresh-journal-lists.yml
Our .mv file gets updated too often. I don't see, why.
Thus adapting the workflow not to commit and push, but always to create a PR.
=> Hotfix: Always create a PR for updating journal lists

src/main/java/org/jabref/cli/ArgumentProcessor.java, src/main/java/org/jabref/cli/Launcher.java
Just pass `--debug` to the command line.
=> Allow enabling debug logs

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java, src/main/java/org/jabref/logic/l10n/Localization.java, src/test/java/org/jabref/logic/importer/fileformat/ACMPortalParserTest.java
Fix cli debug log option
Fixes #10107
Follow up from #10137
=> Fix author parsing of ACM

src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/JabRefGUI.java
=> Store window sizes in prefs at JabRef frame quit

src/main/java/org/jabref/gui/autocompleter/PersonNameSuggestionProvider.java, src/main/java/org/jabref/model/entry/AuthorList.java
Fix https://github.com/JabRef/jabref/issues/9952
Fix https://github.com/JabRef/jabref/issues/6967 
~~Probably because of a deadlock while accessing AthorList#AUTHOR_CACHE but can't confirm...~~
Actually, this can't be a deadlock because there were no use of locks. It's a well known problem that cause non thread-safe Map implementations to get into an infinite loop if accessed concurrently.
https://dzone.com/articles/java-7-hashmap-vs
=> Fix high CPU usage because of author name autocomplete

CHANGELOG.md, src/main/java/org/jabref/gui/preferences/autocompletion/AutoCompletionTab.fxml
=> Fixed togglegroups

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fetcher/GvkFetcher.java, src/main/java/org/jabref/logic/importer/fileformat/PicaXmlParser.java, src/test/java/org/jabref/logic/importer/fetcher/BvbFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/GvkFetcherTest.java
Fixes Part of #10160
compare code attributes in xml with ignore case
Fix BVB fetcher tests as well
=> Fix GVK Fetcher url

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/externalfiles/ExternalFilesEntryLinker.java, src/main/java/org/jabref/gui/externalfiles/ImportHandler.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditorViewModel.java, src/main/java/org/jabref/gui/maintable/MainTable.java, src/main/java/org/jabref/gui/preview/PreviewPanel.java, src/main/resources/l10n/JabRef_en.properties, src/test/java/org/jabref/logic/util/FileNameCleanerTest.java
Fixes #10182
Also supported for drag and drop
(The FilenameCleanerTest can be converted to parameterized test, bu this can be an easy student task)
Display a dialog with auto-renaming option
=> Fix adding files with illegal characters

src/main/java/org/jabref/gui/EntryTypeViewModel.java, src/main/java/org/jabref/logic/importer/WebFetchers.java, src/main/java/org/jabref/logic/importer/fetcher/GvkFetcher.java, src/main/java/org/jabref/logic/importer/fetcher/isbntobibtex/IsbnFetcher.java, src/test/java/org/jabref/logic/importer/WebFetchersTest.java, src/test/java/org/jabref/logic/importer/fetcher/CompositeIdFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/CompositeSearchBasedFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/DiVATest.java, src/test/java/org/jabref/logic/importer/fetcher/GvkFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/isbntobibtex/GVKIsbnFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/isbntobibtex/IsbnFetcherTest.java, src/test/java/org/jabref/logic/importer/fileformat/ACMPortalParserTest.java, src/test/java/org/jabref/logic/importer/util/GrobidServiceTest.java
Fixes #10123
Fixes #9979
Refs #10125
Tested with the ISBNs
Only the first ISBN seems odd,  alternative isbn is working now
https://opac.k10plus.de/DB=2.299/SET=2/PRS=HOL/SHW?FRST=1&ACT=SRCHA
=> Enable ISBN search with GVK

build.gradle, src/main/java/module-info.java, src/main/java/org/jabref/logic/exporter/BibDatabaseWriter.java, src/main/java/org/jabref/logic/exporter/TemplateExporter.java
Follow-up to https://github.com/JabRef/jabref/pull/10227
Remove [JSpecify](https://jspecify.dev/).
Although JSpecify is cool and annotations can be made, the concrete usage should be more "useful". A follow-up PR can add a real example, code howto, and an ADR.
Link to the stackoverflow question for null annotations: https://stackoverflow.com/q/4963300/873282
=> Remove JSpecify salt

build.gradle
We do not use `@version` and `@author`. Thus, it should not be shown in any JavaDoc.
=> No version and author in JavaDoc

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java
Fixed that checked-out radio buttons under specified keywords were not displayed as checked after closing and reopening the edit group window
Fixes #10248 
before: 
after:
=> Fixed saving radio button choice under specified keywords

build.gradle
Java Keyring released a new version, which integrated our fix https://github.com/javakeyring/java-keyring/pull/90.
Follow-up to https://github.com/JabRef/jabref/pull/10224, refs https://github.com/JabRef/jabref/issues/8055.
=> Update Java Keyring dependency

.github/workflows/deployment-arm64.yml, .github/workflows/deployment.yml
Fixes "timeout" in merge queue.
Follow-up to https://github.com/JabRef/jabref/pull/10282
=> Fix mixup with YAML tags

src/jmh/java/org/jabref/benchmarks/Benchmarks.java, src/main/java/org/jabref/cli/ArgumentProcessor.java, src/main/java/org/jabref/gui/autosaveandbackup/BackupManager.java, src/main/java/org/jabref/gui/exporter/CreateModifyExporterDialogViewModel.java, src/main/java/org/jabref/gui/exporter/SaveDatabaseAction.java, src/main/java/org/jabref/logic/crawler/StudyRepository.java, src/main/java/org/jabref/logic/exporter/BibDatabaseWriter.java, src/main/java/org/jabref/logic/exporter/BibtexDatabaseWriter.java, src/main/java/org/jabref/logic/exporter/ExporterFactory.java, src/main/java/org/jabref/logic/exporter/SaveConfiguration.java, src/main/java/org/jabref/logic/exporter/SelfContainedSaveConfiguration.java, src/main/java/org/jabref/model/metadata/SelfContainedSaveOrder.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/main/java/org/jabref/preferences/PreferencesService.java, src/test/java/org/jabref/gui/autosaveandbackup/BackupManagerDiscardedTest.java, src/test/java/org/jabref/gui/exporter/ExportToClipboardActionTest.java, src/test/java/org/jabref/logic/exporter/BibtexDatabaseWriterTest.java
I "forgot" to properly handly self-containedness at the exporters. This caused
```
Caused by: java.lang.IllegalArgumentException: TABLE requires external lookup.
at org.jabref@100.0.0/org.jabref.model.metadata.selfcontainedsaveorder.<init>(selfcontainedsaveorder.java:12)
at org.jabref@100.0.0/org.jabref.model.metadata.selfcontainedsaveorder.of(selfcontainedsaveorder.java:25)
at org.jabref@100.0.0/org.jabref.preferences.jabrefpreferences.getexportconfiguration(jabrefpreferences.java:2275)
at org.jabref@100.0.0/org.jabref.preferences.jabrefpreferences.getcustomexportformats(jabrefpreferences.java:2281)
```
The underlying issue is that concrete exporters are generated in the preferences. In future work, this should be solved. This PR "only" fixes that setting the preferences works again. …
=> Fix exception when opening preferences

rewrite.yml
Applies https://docs.openrewrite.org/recipes/staticanalysis/replacestringbuilderwithstring
No change in the code, thus, this will be a check for contributors only.
=> Add ReplaceStringBuilderWithString

.github/workflows/refresh-csl-subtrees.yml
This makes the action more consistent with the refresh journal list action (https://github.com/JabRef/jabref/blob/main/.github/workflows/refresh-journal-lists.yml)
I tried out the update at - and it worked in general. No PR created, but I assume that this will work.
=> Modernize GitHub workflow for refresh CSL

.github/workflows/deployment-arm64.yml, .github/workflows/deployment.yml, .github/workflows/tests-fetchers.yml, .github/workflows/upload-release.yml
Each of our workflows should be in a separate concurrency group. This was not quite the case before. This PR fixes that.
Hotfix.
=> Fix concurrency groups

.github/workflows/deployment.yml, .github/workflows/tests.yml
We had the issue that the deployment workflow as not triggered for some PRs. See https://github.com/JabRef/jabref/pull/9769#issuecomment-1705542648.
The reason was a wrong trigger. We had the idea that binaries should only be created if there actually was changed something leading to changes in the binaries. Only changing tests does not lead to a change in the binary. For instance, test-only PRs do not change the binary. -- GitHub's branch protection rules demand that the workflows run. Regardless if the trigger ignores the changes. Thus, either make the workflows success optional - or trigger the workflow always.
Since test-only PRs are very seldom and we do want to have the deplyoment required, I remove the "filter" at the trigger.
Kind of hotfix.
=> Fix triggers for deployment

.github/workflows/deployment.yml
Failing run at merge queue: https://github.com/JabRef/jabref/actions/runs/6076277004/job/16484394051
I do not know why some others went through...
=> Add missing do-not-notarize guard when in merge queue

.devcontainer/devcontainer.json, build.gradle, settings.gradle
The pre-builds of our devcontainers failed. (They are configured at https://github.com/JabRef/jabref/settings/codespaces). 
This PR fixes it with two ways:
1. Introduces [Foojay Toolchains Plugin](https://github.com/gradle/foojay-toolchains#foojay-toolchains-plugin) to allow gradle download the JDK by itself (already it - see https://github.com/JabRef/jabref/actions/runs/6094889864)
2. Install JDK20 in the container
Other improvements:
- Always take latest debian release
- Gradle should have a nicer output
Side note: I udpated the pre-build configuration to build once a week only. Should be enough (as currently no one seems to use that feature - we should nevertheless keep it as maintaining is less effort then re-introducing).
=> Fix devcontainer prebuilds

settings.gradle
Reverts JabRef/jabref#10322
breaks mac build
=> Revert "Add workaround for IDEA-317606"

src/test/java/org/jabref/logic/database/DuplicateCheckTest.java
Reworking DuplicateCheckerTests to follow the one-assertion-per-test rule
Follow-up to https://github.com/JabRef/jabref/pull/9769
(Can't continue on duplicate checker the next days; submitting the current work to enable others working on it)
=> Rework duplicate checker tests

build.gradle, rewrite.yml, src/main/java/org/jabref/logic/formatter/bibtexfields/EscapeAmpersandsFormatter.java, src/test/java/org/jabref/gui/theme/ThemeManagerTest.java, src/test/java/org/jabref/logic/bst/BstVMVisitorTest.java, src/test/java/org/jabref/logic/net/URLDownloadTest.java, src/test/java/org/jabref/logic/shared/DBMSProcessorTest.java
I went through the changelogs of OpenRewrite and added following rewrites:
- https://docs.openrewrite.org/recipes/java/testing/junit5/removetrycatchfailblocks
- https://docs.openrewrite.org/recipes/java/testing/junit5/asserttrueinstanceoftoassertinstanceof 
- https://docs.openrewrite.org/recipes/staticanalysis/equalstocontentequals
No efffects:
- https://docs.openrewrite.org/recipes/java/recipes/usejavaparserbuilderinjavatemplate
- https://docs.openrewrite.org/recipes/staticanalysis/replaceweekyearwithyear
- https://docs.openrewrite.org/recipes/staticanalysis/sortedsetstreamtolinkedhashset
- https://docs.openrewrite.org/recipes/java/migrate/io/replacefileinoroutputstreamfinalizewithclose
- https://docs.openrewrite.org/recipes/staticanalysis/removetostringcallsfromarrayinstances
- …
=> Add new openrewrite rules

build.gradle, src/main/java/org/jabref/cli/JournalListMvGenerator.java
I got annoyed by the duplicate warnings. Not that important so that we should see it at every test. Thus, I muted that.
The clean "fix" is proposed at https://github.com/JabRef/abbrv.jabref.org/issues/149.
=> Add "--verbose" to MV generator

CHANGELOG.md
I run the CHANGELOG.md linter [heylogs](https://github.com/nbbrd/heylogs) on our CHANGELOG.md. The errors were as follows:
```
8:47   error  Expecting HTTPS protocol                      https
249:164  error  Expecting GitHub issue ref 8484, found 8448   github-issue-ref
249:439  error  Expecting GitHub issue ref 6000, found 6002   github-issue-ref
270:72   error  Expecting GitHub issue ref 9147, found 9175   github-issue-ref
396:118  error  Expecting GitHub issue ref 8510, found 8150   github-issue-ref
423:318  error  Expecting GitHub issue ref 7012, found 7102   github-issue-ref
432:148  error  Expecting GitHub issue ref 7012, found 7102   github-issue-ref
503:100  error  Expecting GitHub issue ref 7882, found 7892   github-issue-ref
550:70   error  Expecting GitHub issue ref 72, found …
```
=> Fix CHANGELOG.md linting issues

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupDialogView.java, src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java
Fixes #10350
Init viewModel in initializing method, not in ctor as injected are not yet present in ctor
=> Fix NPE when adding new aux group

docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/pre-03-code.md
Closes https://github.com/JabRef/jabref/pull/10345 (that one is much more effort)
=> Add workaround for IDEA-317606

src/main/java/org/jabref/gui/exporter/WriteMetadataToLinkedPdfsAction.java, src/main/resources/l10n/JabRef_en.properties
Change key from {} to %0 in WriteMetadataToPdfsAction. Fix L10. This PR fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/275.
=> Replacement localization

.github/workflows/deployment-arm64.yml, .github/workflows/deployment.yml, CHANGELOG.md, buildres/mac/jabrefHost.py, buildres/mac/native-messaging-host/chromium/org.jabref.jabref.json, buildres/mac/native-messaging-host/firefox/org.jabref.jabref.json, buildres/mac/postinstall
Fixes https://github.com/JabRef/jabref/issues/10308
I found out about "add-content", however that only copies to the root dir, so I adjusted the scripts:
Need testing if the python path still works
=> Copy browser extension files for mac

.github/heylogs.java, .github/workflows/tests.yml, CHANGELOG.md, config/checkstyle/checkstyle_reviewdog.xml
[heylogs](https://github.com/nbbrd/heylogs) is IMHO a great linter for CHANGELOG.md files. This PR adds check for it.
Example:
Faililng check:
After fixing the CHANGELOG.md file (refs https://github.com/JabRef/jabref/pull/10351)
=> Add good linting of CHANGELOG.md

.github/workflows/deployment-arm64.yml, .github/workflows/deployment.yml
Lightweight alternative to https://github.com/JabRef/jabref/pull/10345. "Just" fixing the names in our build script (display only)
Moreover, have "JabRef e.V." as vendor and `JabRef` as mac-package-identifier (instead of Jabref)
=> Fix casing "macOS" and "JabRef", vendor: JabRef e.V.

src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/gui/actions/ActionHelper.java
Refs #10373 
Use changed list from the listener
=> Try to fix ioob for selected entries

.github/workflows/deployment.yml
Follow-up to https://github.com/JabRef/jabref/pull/10402
I checked the build log for a PR coming from a fork (https://github.com/JabRef/jabref/actions/runs/6258474828/job/16992551711?pr=10391). I saw that we don't build anything for macOS.
This PR:
- `prepareModulesDir` also for forks (seems that target does not need the signing keys).
- Renaming and re-compressing files only for "real" builds (because I assume a contributor does not work on our build internals and thus there is no need for a check)
Does not execute jPackage in the case of no-secretes-present. I think `prepareModulesDir` is enough for a fork to check.
We could also think about executing `jPackage` for PRs from us only - and stick to `prepareModulesDir` for forks on all OSs.
=> Build more on macOS at PRs from forks

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupTreeView.java, src/main/java/org/jabref/gui/util/ViewModelTreeTableRowFactory.java
~~Fixes 10403~~ Fixes #10404 
Fixes #10317
Fixes #10374
=> Fix adding and removing selected entries to group context menu

src/main/java/org/jabref/gui/EntryTypeView.java, src/main/java/org/jabref/gui/EntryTypeViewModel.java
Import by ID in new entry was running on the FX thread (wtf?)  
Came up in the forum https://discourse.jabref.org/t/jabref-5-10-not-allowing-citations-to-be-added-into-sub-groups-with-right-click/3990/11?u=siedlerchr
=> Fix fetcher worker execution on background thread

CHANGELOG.md, src/main/java/org/jabref/logic/integrity/AmpersandChecker.java, src/main/java/org/jabref/logic/integrity/HTMLCharacterChecker.java, src/test/java/org/jabref/logic/integrity/AmpersandCheckerTest.java, src/test/java/org/jabref/logic/integrity/HTMLCharacterCheckerTest.java
Fixes https://github.com/koppor/jabref/issues/585#issuecomment-1735461242
Refs https://github.com/JabRef/jabref/issues/8712#issuecomment-1731114692
=> Exclude check for ampersand (&) at verbatim fields

.github/workflows/refresh-csl-subtrees.yml, .github/workflows/refresh-journal-lists.yml
On https://github.com/JabRef/jabref/pull/10432, there was no triggering of actions.
Reading https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs, it cannot work with the GITHUB_TOKEN.
Let's try with our token for updating the gradle wrapper.
=> Fix triggering workflows

CHANGELOG.md, src/main/java/org/jabref/logic/cleanup/URLCleanup.java, src/test/java/org/jabref/logic/cleanup/URLCleanupTest.java
"Move URL in note field to url field" was causing NPEs
Refs https://discourse.jabref.org/t/cleanup-entries-cant-get-it-to-work/3999/6?u=siedlerchr
=> Fix NPEs in UrlCleanup

src/test/java/org/jabref/gui/fieldeditors/LinkedFileViewModelTest.java
=> Mark download PDF test as fetcher test

src/main/java/org/jabref/gui/auximport/AuxParserResultViewModel.java, src/main/java/org/jabref/gui/auximport/FromAuxDialog.fxml
This adds some code comments and makes the button wieder:
=> Polish AUX file import dialog

src/main/java/org/jabref/gui/importer/GenerateEntryFromIdAction.java
Sometimes on MacOSX, the pop over **sometimes** closes without pressing enter. This is a work around to avoid "duplicate entry" dialog in case of adding a DOI.
Now, when JabRef notifies about the search, the pop over is closed.
Before, the popup was closed after the search (independent of if there was an error or not)
=> Close pop over early

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fileformat/IsiImporter.java, src/test/java/org/jabref/logic/importer/fileformat/IsiImporterTest.java
The ISI importer used the .REVIEW field which we migrate away on load.
Refs https://github.com/JabRef/jabref/issues/10370
=> Use .COMMENT instead of outdated .REVIEW

CHANGELOG.md, src/main/java/org/jabref/gui/desktop/JabRefDesktop.java
Refs https://github.com/JabRef/jabref-issue-melting-pot/issues/152#issuecomment-1740419521
=> Open file in browser if is url

src/main/java/org/jabref/logic/importer/fileformat/MedlineImporter.java, src/test/java/org/jabref/logic/importer/fileformat/MedlineImporterTest.java
=> Remove Guava dependency in MedlineImporter

.github/workflows/add-greeting-to-issue.yml, .github/workflows/automerge.yml
This adds a missing `--squash` argument o `gh merge`.
It also renames the camel-cased workflow YAML file to [caterpillar-case](https://stackoverflow.com/a/21956960/873282) (AKA kebap-base)
=> Fix gh pr merge argument

CHANGELOG.md, src/main/java/org/jabref/gui/importer/fetcher/WebSearchPaneView.java
One can select a PDF text and paste it by middle button on the JabRef search bar
Fixes  https://github.com/JabRef/jabref/issues/7905
=> Middle-button paste in X fix

src/main/java/org/jabref/model/entry/Date.java, src/test/java/org/jabref/model/entry/DateTest.java
Fixes #2753 
This pull request contributes to #2753.
- Parse the TODO list of date formats in Date.java class. 
- Tests added.
=> Issue 2573 support biblatex date formats

CHANGELOG.md, src/main/java/org/jabref/gui/actions/StandardActions.java, src/main/java/org/jabref/gui/groups/GroupTreeView.java, src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java, src/main/resources/l10n/JabRef_en.properties
I have added an option to further sort subgroups on Z-A order, and also by ascending and descending number of subgroups. Currently only the option to sort from A-Z exists. 
Fixes #10249
=> Add New Group Sorting Options

src/main/java/org/jabref/gui/preferences/network/NetworkTab.fxml, src/main/resources/l10n/JabRef_en.properties, src/test/java/org/jabref/logic/l10n/LocalizationConsistencyTest.java
=> Adjust issue bug text

.github/workflows/tests.yml, .vscode/ltex.dictionary.en-US.txt, docs/code-howtos/code-quality.md
It is hard for newcomers to know about that we have more than checkstyle in place. See https://github.com/JabRef/jabref/pull/10496#issuecomment-1773730958.
We (currently) don't have it in the documentation. This is future work.
I think, it is more helpful, if we automatically comment on the PR to support tailored guidance. This PR tries to do it.
=> Split Java code style checks

src/main/resources/META-INF/services/org.tinylog.writers.Writer, src/main/resources/tinylog.properties, src/test/java/module-info.test
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/313
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/312
>LOGGER ERROR: Service implementation 'org.jabref.gui.logging.ApplicationInsightsWriter' not found
=> Remove application insights writer from meta inf

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupTreeView.java
Fixes https://github.com/JabRef/jabref/issues/9972#issuecomment-1773888349
=> Readd empty group hits display

.github/workflows/tests.yml, CHANGELOG.md
This uses [clparse](https://github.com/marcaddeo/clparse) to detect updates to sections of `CHANGELOG.md` of released versions. This happens if PRs are longer-lasting than releases.
It implements the suggestion of https://github.com/NiclasvanEyk/keepac/issues/20#issuecomment-1712944920
This PR cannot use [heylogs](https://github.com/nbbrd/heylogs), because https://github.com/nbbrd/heylogs/pull/146 is not merged (and thus the functionality is not available).
=> Add check for frozen CHANGELOG.md sections

CONTRIBUTING.md, docs/contributing.md, docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-13-code-style.md
Two contributors worked on `main`. I think, it is because this "no-no" is too far away from the setup guide. I bring it closer by providing a deep link to https://devdocs.jabref.org/contributing#contribute-code.
=> Add deep links to code contribution howto

src/main/java/org/jabref/gui/externalfiles/DuplicateDecisionResult.java, src/main/java/org/jabref/gui/externalfiles/ImportHandler.java, src/main/java/org/jabref/logic/cleanup/MoveFilesCleanup.java, src/test/java/org/jabref/gui/externalfiles/ImportHandlerTest.java
Write testing for issue #10372
I divided importEntryWithDuplicateCheck into several parts to facilitate testing, and added DuplicateDecisionResult.java to facilitate storage of duplicate files.
=> ImportHandlerTest-handleDuplicatesTest

.gitpod.Dockerfile
The current gitpod config runs Java 18 which causes build errors since the project is set to target Java 21. This PR fixes that by upgrading the java version in `.gitpod.Dockerfile`.
=> Update Java version to 21 in gitpod config

build.gradle, src/main/java/org/jabref/logic/importer/fetcher/ArXivFetcher.java
Triggered by the diff at `zbMath` at https://github.com/JabRef/jabref/pull/10561, I was recommended at https://github.com/openrewrite/rewrite-static-analysis/issues/168#issuecomment-1776020058 to update to [the latest snapshot](https://docs.openrewrite.org/reference/snapshot-instructions).
This PR updates OpenRewrite to the latest snapshots, which are a bit better than the current version.
=> Update to latest recipes

CHANGELOG.md, src/main/java/org/jabref/gui/mergeentries/newmergedialog/fieldsmerger/FileMerger.java, src/test/java/org/jabref/gui/mergeentries/newmergedialog/fieldsmerger/FileMergerTest.java
Add test
Fixes https://github.com/JabRef/jabref/issues/10572
=> Fix file field merging

.github/workflows/deployment.yml
Forks currently don't get any binary. This should fix it.
If build runs through, I'll merge (to be able to work on https://github.com/koppor/jabref/pull/660)
=> Enable collecting GitHub build artifacts for forks

.github/PULL_REQUEST_TEMPLATE.md, src/main/java/org/jabref/gui/JabRefFrame.java
Multiple contributors did not use "fixes", but other words (not recognized by GitHub https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
The explanation seems to be that "fixes" is interpreted as fixing a bug only. Thus, they changed the wording. See https://github.com/koppor/jabref/issues/540#issuecomment-1778610956 for that explanation.
"Resolves" has more weight to me than "Closes". However, GitHub has "Close" at issues, therefore, I propose to use "Closes" as text.
=> Replace "fixes" by "closes"

src/test/java/org/jabref/logic/importer/fetcher/AstrophysicsDataSystemTest.java, src/test/java/org/jabref/logic/importer/fetcher/CollectionOfComputerScienceBibliographiesFetcherTest.java, src/test/java/org/jabref/logic/net/URLDownloadTest.java
=> Fix failing fetcher tests

CHANGELOG.md, src/main/java/org/jabref/logic/formatter/bibtexfields/ShortenDOIFormatter.java, src/test/java/org/jabref/logic/formatter/bibtexfields/ShortenDOIFormatterTest.java
=> Check if value is already a Short DOI

CHANGELOG.md
Follow up to https://github.com/JabRef/jabref/pull/10627
- add gtk 3.8
- add glibc_2.34
- add MacOS 11
=> Add minimum requirements to CHANGELOG.md

.github/workflows/tests.yml
Due to https://github.com/nbbrd/heylogs/issues/163#issuecomment-1803403620, I updated heylogs. The update works. Thus, we get one issue less.
If tests are green, I just merge. Otherwise, all PRs will report an issue because of CHANGELOG errors.
=> Adapt tests to new heylogs

src/main/java/org/jabref/gui/fieldeditors/identifier/IdentifierEditor.java
Fixes #10629
No changelog needed as this was an unintended side effect of #10178
=> Fix NPE in lookup identifer

CHANGELOG.md, src/main/resources/resource/layout/hayagrivayaml.layout, src/test/java/org/jabref/logic/exporter/HayagrivaYamlExporterTest.java
Closes #10596 
The parent field is added to the Hayagriva YAML exporter, which was introduced in #10451 
Previously, the exporter neglected some fields, addressing two specific cases:
1. **Case 1 (entry type: article):**
- The journal field is now included under the parent field in addition to volume, issue, and publisher (if present).
2. **Case 2 (entry type: book):**
- The series field is now included under the parent field.
- The issue and publisher are also added for books
I confirmed that the exported .yaml file works with the typst system by using `hayagriva literature.yaml reference` as stated in their [documentation](https://github.com/typst/hayagriva/tree/main).
Also, I compared the exports of the typst system with the exports from jabref and they contained the same fields.
=> Added parent field to Hayagriva YAML export

.github/heylogs.java, .github/workflows/tests.yml
This implements https://github.com/NiclasvanEyk/keepac/issues/20#issuecomment-1712944920. Since https://github.com/marcaddeo/clparse/issues/22 was solved, this should be possible.
Also updated heylogs to the latest release.
Follow-up to https://github.com/JabRef/jabref/pull/10631.
Screenshot for failing check:
=> Use clparse (instead of heylogs)

.github/workflows/tests.yml
I thought it would be nice to have some messages at PRs when sth goes wrong.
However, only persons with access rights to this repo get these texts - others not.
Thus, I remove them.
@reviewdog can. Follow-up is to convert the output in case of errors to a format consumable to reviewdog.
=> Remove comments - don't work on forks

rewrite.yml, src/test/java/org/jabref/gui/externalfiles/FileFilterUtilsTest.java, src/test/java/org/jabref/gui/maintable/MainTableColumnModelTest.java, src/test/java/org/jabref/gui/sidepane/SidePaneViewModelTest.java, src/test/java/org/jabref/gui/theme/ThemeManagerTest.java, src/test/java/org/jabref/logic/bibtex/comparator/BibStringDiffTest.java, src/test/java/org/jabref/logic/database/DatabaseMergerTest.java, src/test/java/org/jabref/logic/importer/fetcher/IacrEprintFetcherTest.java, src/test/java/org/jabref/logic/journals/AbbreviationTest.java, src/test/java/org/jabref/logic/layout/format/ReplaceTest.java, src/test/java/org/jabref/logic/msbib/MsBibAuthorTest.java, src/test/java/org/jabref/logic/net/ProxyTest.java, src/test/java/org/jabref/model/FieldChangeTest.java, src/test/java/org/jabref/model/entry/BibEntryTest.java, src/test/java/org/jabref/model/openoffice/CitationEntryTest.java, src/test/java/org/jabref/model/strings/StringUtilTest.java
This enables rewrite of tests using OpenRewrite's JUni5 "cleanup assertions" recipe: https://docs.openrewrite.org/recipes/java/testing/junit5/cleanupassertions
=> Clean up test code

.github/workflows/check-links.yml, .github/workflows/deployment-arm64.yml, .github/workflows/deployment.yml, .github/workflows/tests-fetchers.yml, .github/workflows/tests.yml
This PR enables parallel builds in the merge queue. Now, merges are build in parallel, but with the previous entries in the merge queue inside. In case a predecessor fails, it is exluded and the all subsquent builds are run again. See https://github.com/orgs/community/discussions/63136#discussioncomment-7738973 for a graphics.
I tried out the "fix" at https://github.com/winery/test-concurrency-at-merge-queues - and it looked good! 😅
More background: After thinking more of https://github.com/orgs/community/discussions/63136 and why GitHub did not answer it, I thought, it must be a user error.
=> Fixes concurrency group to speed up merge queues

build.gradle, src/main/java/org/jabref/gui/preview/PreviewViewer.java
Fixes #10676  
Supersedes #10682 
Test with gradlew jpackage on my machine
=> Fix missing module error  for CSL

src/main/java/org/jabref/gui/MainApplication.java, src/main/java/org/jabref/logic/journals/predatory/PredatoryJournalListLoader.java, src/main/java/org/jabref/logic/journals/predatory/PredatoryJournalRepository.java, src/test/java/org/jabref/logic/integrity/IntegrityCheckTest.java, src/test/java/org/jabref/logic/integrity/PredatoryJournalCheckerTest.java
Fixes https://discourse.jabref.org/t/jabref-always-displaying-full-screen-on-ubuntu-not-in-gnome-windown/4090/3
Seems like there is a problem with the path in the jlink module stuff package when opening a File resource instead of a stream 
Copy code from JournalAbbrev
=> Fix predatory journal loading resoures

docs/code-howtos/tools.md
I saw a "broken" link in the docs. Removed some more "geeky" part in the docs to fix that.
=> Remove autohotkey part

src/main/java/org/jabref/logic/importer/fetcher/SemanticScholar.java, src/test/java/org/jabref/logic/importer/fetcher/SemanticScholarTest.java
We can get the citaiton pdf url in the meta tag. And we need to request html, otherwise we get json which does not containt this fiel
=> Fix fulltext of semantic scholar

CHANGELOG.md, src/main/java/org/jabref/gui/actions/StandardActions.java, src/main/java/org/jabref/gui/edit/CopyMoreAction.java, src/main/java/org/jabref/gui/keyboard/KeyBinding.java, src/main/java/org/jabref/gui/preferences/external/ExternalTabViewModel.java, src/main/java/org/jabref/gui/push/AbstractPushToApplication.java, src/main/java/org/jabref/logic/push/CitationCommandString.java, src/main/java/org/jabref/preferences/ExternalApplicationsPreferences.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/main/resources/l10n/JabRef_en.properties, src/test/java/org/jabref/gui/edit/CopyMoreActionTest.java, src/test/java/org/jabref/gui/push/PushToEmacsTest.java, src/test/java/org/jabref/preferences/CitationCommandStringTest.java
Fixes #10615
Supersedes https://github.com/JabRef/jabref/pull/10690
=> Fix Copy cite command should respect preferences

src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java, src/main/resources/l10n/JabRef_en.properties
Newlines have to be inside the localization strings, not outside.
=> Merge split localization string

build.gradle
=> Downgrade jfx 21.0.1 to jfx 21

CHANGELOG.md, src/main/java/org/jabref/gui/preview/PreviewPanel.java
Fix https://github.com/JabRef/jabref/issues/9172
In `PreviewViewer`, both `setEntry` and `setLayout` will assign the entry and layout fields respectively and call the `update` method to reflect the new UI state. The thing is that `update` would start a background task to update the UI. The `setLayout` method would run the update UI background task on the previous entry because the entry field assignment happens in `setEntry`. While `setEntry` would run the task with the new entry. The bug happens when the task started by the `setLayout` method finishes last which will result in the overriding of the display of the new entry preview made by `setEntry`.
=> Fix the preview panel showing the wrong entry (an entry that is not selected in the entry table)

src/test/java/org/jabref/logic/importer/ParserResultTest.java
Tests were added as requested from the conversation in the merged pull request #10700. The three tests added aim to verify the correct output from the getErrorMessage function. Specifically when the ParserResult is empty, not empty, or has duplicate messages added, 
- [ x ] Tests created for changes (if applicable)
- [ x ] Manually tested changed features in running JabRef (always required)
=> Added tests to verify proper output from getErrorMessage()

.github/workflows/check-links.yml
Our link checker reports an error at [http 429](https://de.wikipedia.org/wiki/HTTP-Statuscode#code429). 
We should ignore it.
Sources:
- https://github.com/lycheeverse/lychee/issues/367 -- no other work around available
- Idea to add 403 to ignore list: https://github.com/lycheeverse/lychee-action/issues/39
=> Ignore 429 at link check

CHANGELOG.md, src/main/java/org/jabref/logic/database/DuplicateCheck.java, src/test/java/org/jabref/logic/database/DuplicateCheckTest.java, src/test/java/org/jabref/logic/integrity/ASCIICharacterCheckerTest.java
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/249
=> Fix duplicate checker does not respect umlauts / latex free fields 

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fetcher/DoiResolution.java, src/main/java/org/jabref/logic/layout/LayoutEntry.java, src/main/java/org/jabref/logic/layout/LayoutFormatterPreferences.java, src/main/java/org/jabref/logic/layout/format/DOICheck.java, src/main/java/org/jabref/model/entry/identifier/DOI.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/test/java/org/jabref/logic/layout/format/DOICheckTest.java
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/341
Fixes https://discourse.jabref.org/t/export-html-disregards-custom-doi-base-uri/4084
=> Use custom doi now in Template exporter

.github/workflows/refresh-csl-subtrees.yml, .github/workflows/refresh-journal-lists.yml, .gitmodules
Via https://stackoverflow.com/a/12527608/873282, I found a solution for our "dirty" sub modules.
The GitHub workflow update is a "wild guess". I would say: Merge and fix the workflows if they don't work.
=> Ignore submodule changes (for normal devs)

build.gradle
Our fetcher tests output the test results twice:
```
> Task :fetcherTest
org.jabref.logic.importer.fetcher.ACSTest
Test findByDOI() FAILED
org.opentest4j.AssertionFailedError: expected: <Optional[https://pubs.acs.org/doi/pdf/10.1021/bk-2006-STYG.ch014]> but was: <Optional.empty>
ACSTest > findByDOI() FAILED
org.opentest4j.AssertionFailedError: expected: <Optional[https://pubs.acs.org/doi/pdf/10.1021/bk-2006-STYG.ch014]> but was: <Optional.empty>
at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
```
This was unreadable. 
---
We have the plugin [gradle-test-logger-plugin](https://github.com/radarsh/gradle-test-logger-plugin) enabled for that. Today, I found the solution (refs https://github.com/radarsh/gradle-test-logger-plugin/issues/252#issuecomm …
=> Streamline test output

src/test/java/org/jabref/architecture/MainArchitectureTest.java, src/test/java/org/jabref/logic/search/DatabaseSearcherWithBibFilesTest.java
Follow-up to https://github.com/JabRef/jabref/pull/10193.
The usage of the annotation `@AllowedToUseSwing` was a quick hack. Now, the "exception" is inside `MainArchitectureTest`.
=> Fix annotation

src/main/java/org/jabref/logic/citationstyle/CitationStyle.java, src/main/java/org/jabref/logic/citationstyle/JabRefLocaleProvider.java
I had some CSL issues.
They can be fixed 
- cd src/main/resources/csl-locales
- git reset --hard
- cd ../csl-styles
- git reset --hard
I did not know that, so I improved our error code a bit..
=> Change default CSL style to ieee-with-url

.github/workflows/add-greeting-to-issue.yml
This should fix labeling using our label.
We need to use `pull_request_target`, so that the action is triggered with **our** code and **our** secrets. See https://stackoverflow.com/a/74959635/873282 for a longer explanation. Source: https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
=> Fix labeling of PRs for newcomers

src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/logic/bibtex/BibEntryWriter.java, src/main/java/org/jabref/logic/bibtex/TypedBibEntry.java, src/main/java/org/jabref/logic/xmp/DublinCoreExtractor.java, src/test/java/org/jabref/logic/TypedBibEntryTest.java
Since `TypedBibEntry` is more a wrapper in comparison to core BibEntry java class, we put it in a separate package. However, I don't like it to be floating around in the general package `org.jabref.logic`. I moved it into `org.jabref.logic.bibtex`. Users will note that it needs `BibEntry` to work.
=> Change package of TypedBibEntry

CHANGELOG.md, src/main/java/org/jabref/gui/auximport/FromAuxDialog.java
When generating a sub library based on an aux file, it should also be possible if some keys are missing.
Now the Generate button is enabled even if there are one or more missing BibEntries.
=> Fix enablement of Aux dialog's "Generate" button

src/main/java/org/jabref/gui/util/comparator/NumericFieldComparator.java, src/main/java/org/jabref/logic/bibtex/comparator/FieldComparator.java
While stumbling on an OpenRewrite issue (https://github.com/openrewrite/rewrite/issues/3913), I found WTF code inside JabRef. We use that code for performance reasons. 
Thus, I thought, let's really use it to gain performance. Here is my (first) change. In a follow-up PR, I will rewrite all `Integer.parseInt` to `StringUtil.valueOf`. This takes a bit time, since I don't know how to use [refaster in OpenRewrite](https://docs.openrewrite.org/authoring-recipes/types-of-recipes#refaster-templates) or how we can use [error prone's refaster templates](https://errorprone.info/docs/refaster) here.
=> Use StringUtil.intValueOf instead of StringUtil.intValueOfOptional or custom code

src/main/java/org/jabref/gui/shared/SharedDatabaseUIManager.java, src/main/java/org/jabref/logic/git/SlrGitHandler.java, src/main/java/org/jabref/logic/importer/FulltextFetchers.java, src/main/java/org/jabref/logic/importer/fetcher/ComplexSearchQuery.java, src/main/java/org/jabref/logic/importer/fetcher/transformers/IEEEQueryTransformer.java, src/main/java/org/jabref/logic/shared/DBMSConnectionProperties.java, src/main/java/org/jabref/model/database/BibDatabaseContext.java, src/main/java/org/jabref/preferences/JabRefPreferences.java
Applies https://docs.openrewrite.org/recipes/java/removeobjectsisnull
> Replace calls to Objects.isNull(..) and Objects.nonNull(..) with a simple null check. **Using these methods outside of stream predicates is not idiomatic.**
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.java.RemoveObjectsIsNull?organizationId=SmFiUmVm
=> refactor: Transform calls to `Objects.isNull(..)` and `Objects.nonNull(..)`

src/main/java/org/jabref/cli/Launcher.java, src/main/java/org/jabref/gui/DefaultInjector.java, src/main/java/org/jabref/gui/Globals.java, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/JabRefGUI.java, src/main/java/org/jabref/gui/openoffice/OpenOfficePanel.java
=> Refactored quitting process

CHANGELOG.md, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.fxml, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java
Closes #10425
> fixed an issue where the fulltext search button in entry editor used to disappear on click till the search is completed.
> Now shows progress animation as it should when search is in progress as it should.
=> Fixed fulltext fetcher button invisible

CHANGELOG.md, src/main/java/org/jabref/gui/push/PushToTexShop.java
Fixes https://discourse.jabref.org/t/push-to-texshop-mac/2699/17?u=siedlerchr
This alllows `~\cite{key1,key2}`
=> Fix escaping of slashes for TexShop

src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/gui/util/BackgroundTask.java
When a large library is loaded and the tab is close during load, there is an exception:
```
java.lang.NullPointerException: Cannot invoke "javafx.scene.control.TabPane.getSelectionModel()" because the return value of "org.jabref.gui.LibraryTab.getTabPane()" is null
at org.jabref@100.0.0/org.jabref.gui.LibraryTab.setDatabaseContext(LibraryTab.java:264)
at org.jabref@100.0.0/org.jabref.gui.LibraryTab.onDatabaseLoadingSucceed(LibraryTab.java:243)
```
This PR fixes that - and also adds some NPE checks at close (to enable the tab being closed despite NPEs)
=> Fix NPE when tab is close during load

CHANGELOG.md, src/main/java/org/jabref/logic/openoffice/frontend/UpdateCitationMarkers.java, src/main/java/org/jabref/logic/openoffice/style/OOBibStyle.java, src/test/resources/org/jabref/logic/openoffice/style/test.jstyle, src/test/resources/org/jabref/logic/openoffice/style/testWithDefaultAtFirstLIne.jstyle
By default, zero width space is added in front of each citation in the text in Openoffice/Libreoffice. This causes ugly line breaks if new line starts with a citation:
To allow changing if a zero width space is added to each citation, a new boolean in the style file can be used:
SpaceBefore="true" -> Default behaviour with the zero width space
SpaceBefore="false" -> No space is added:
Pull request to documentation added.
=> Space before citations in Openoffice/Libreoffice integration

CHANGELOG.md, src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/gui/autocompleter/SuggestionProviders.java
Closes #8145 
Fixed the initial issue when autocompletion was disabled, the crossref field was not populating the suggestions.
Now the CrossRef field is populating the suggestions even if AutoCompletion(File > Preferences > Autocompletion) is disabled
=> Fix Suggestion Provider for Crossref during autocompletion disable

src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/logic/pdf/search/PdfIndexer.java, src/main/java/org/jabref/logic/pdf/search/PdfSearcher.java, src/main/java/org/jabref/model/database/BibDatabaseContext.java
I started JabRef. Twice. Then, the **same** index is used for Lucene by the second instance. Does not work:
```
Could not initialize the IndexWriter
org.apache.lucene.store.LockObtainFailedException: Lock held by another program: /home/koppor/.local/share/jabref/lucene/99/06bf8206--y.bib/write.lock
...
Uncaught exception occurred in Thread[#60,JavaFX Application Thread,5,main]
java.lang.NullPointerException: Cannot invoke "org.apache.lucene.index.IndexWriter.getReader(boolean, boolean)" because "writer" is null
```
This PR adds a workaround by using `null` and Optionals.
This also adds a workaround for https://github.com/JabRef/jabref/issues/10781 by checking for `null`. The workaround is the first code... OK, we could also check why the `null` appears here. Sounded like bigger work for …
=> Fix closing of JabRef in case of issues with index writer

CHANGELOG.md, src/main/java/org/jabref/logic/msbib/MSBibConverter.java, src/test/resources/org/jabref/logic/exporter/MSBibXmlTest.bib, src/test/resources/org/jabref/logic/exporter/MSBibXmlTest.xml
Fixes #10807 
" if ("Art".equals(msBibType) || "Misc".equals(msBibType)) {
result.publicationTitle = entry.getFieldLatexFree(StandardField.TITLE).orElse(null);
}"
=> BibTeX 'Title' to MS Office 'Publicationtitle' field

docs/code-howtos/openoffice/ooresult-ooerror/index.md, docs/code-howtos/openoffice/ooresult-ooerror/ooresult-alternatives.md
**Issue**: The sections "[OOError](https://devdocs.jabref.org/code-howtos/openoffice/ooresult-ooerror/)", and ["Alternatives to using OOResult](https://devdocs.jabref.org/code-howtos/openoffice/ooresult-ooerror/ooresult-alternatives)" are not visible in the navigation bar or the [Table of Contents of the LibreOffice](https://devdocs.jabref.org/code-howtos/openoffice/).
Does this match the expected hierarchy?
=> docs: About OOError, Alternatives section not visible

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/LatexCitationsTab.java, src/main/java/org/jabref/gui/entryeditor/LatexCitationsTabViewModel.java, src/main/resources/l10n/JabRef_en.properties
Fixes  #10584.
- As for developer's documentation I don't think anything should change.
- As for the user's documentation I think the screenshots and GIFs [here](https://docs.jabref.org/advanced/entryeditor/latex-citations) should be replaced to include the new button. Should I make an issue in the [user-documentation](https://github.com/JabRef/user-documentation/issues) repository after the pull is merged?
=> Add refresh button for LaTeX citations.

docs/code-howtos/IntelliJ.md, docs/code-howtos/javafx.md, docs/code-howtos/openoffice/ooresult-ooerror/index.md, docs/code-howtos/openoffice/order-of-appearance.md, docs/code-howtos/openoffice/problems.md, docs/code-howtos/testing.md, docs/code-howtos/ui-recommendations.md, docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/eclipse.md
Removed all backslashes that were causing errors in URLs in the documentation.
=> docs: Fixed all URLs and corrected typos

docs/teaching.md
Fixed 2 broken links the teaching docs.
=> Fix Broken Links

src/main/java/org/jabref/gui/DialogService.java, src/main/java/org/jabref/gui/JabRefDialogService.java, src/main/java/org/jabref/gui/libraryproperties/contentselectors/ContentSelectorViewModel.java, src/main/java/org/jabref/gui/preferences/customentrytypes/CustomEntryTypesTab.java, src/test/java/org/jabref/gui/libraryproperties/contentselectors/ContentSelectorViewModelTest.java
Implemented task 3 from #10560. 
Disabled the add field button if the entry type is not selected to prevent exceptions.
=>  Change the popup to enter types to the combo box for custom entry types

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/CommentsTab.java
Fixes #10870
This issue occurs when the `defaultOwner` contains capital letters. 
For example, if `defaultOwner = Test`, the `userSpecificCommentField.name` will be `comment-Test`, after saving it to the .bib file, it will be written as `comment-test`. As a result, every time the `commentsTab` is opened, it will contain both `comment-Test` and `comment-test` fields.
=> Fix issue in comments Tab

CHANGELOG.md, src/main/java/org/jabref/preferences/FilePreferences.java, src/main/java/org/jabref/preferences/InternalPreferences.java, src/main/java/org/jabref/preferences/JabRefPreferences.java
Fixes https://github.com/JabRef/jabref/issues/10924
At https://github.com/JabRef/jabref/pull/9910 I did not properly use our subscription system.
=> Fix "Changing owner name crashes the application"

src/main/java/org/jabref/migrations/PreferencesMigrations.java, src/main/java/org/jabref/model/entry/field/StandardField.java, src/main/java/org/jabref/preferences/JabRefPreferences.java
After PR #10896, the abstract field now supports markdown. 
If I try to reset the default preview style from the preferences, the abstract loses the markdown formatter.
=> Fix: abstract field loses markdown formatter after resetting default preview style

CHANGELOG.md, src/main/java/org/jabref/gui/documentviewer/DocumentViewerView.java
Use setAsDialogPane in ViewLoader to correctly display the PDF when Document Viewer window is resized.
Closes #10934
=> Fix "Document Viewer: PDF shows only in half of the window size" #10934

rewrite.yml, src/main/java/org/jabref/gui/fieldeditors/MapBasedEditorViewModel.java, src/main/java/org/jabref/gui/util/DefaultTaskExecutor.java, src/main/java/org/jabref/gui/util/ViewModelTreeTableCellFactory.java, src/test/java/org/jabref/model/paging/PageTest.java
Enables https://docs.openrewrite.org/recipes/staticanalysis/usediamondoperator.
Did not work a few months ago, but seems to work now.
=> OpenRewrite: Enable UseDiamondOperator

CHANGELOG.md, src/main/java/org/jabref/gui/documentviewer/DocumentViewerControl.java
I have added the ability to change the zoom level using Ctrl + Scroll in the PDF Document Viewer.
Additionally, I have limited the zoom-out to ~1 page by setting a minWidth, as an unlimited zoom-out led to following problems:
- Occasional display errors (e.g. no text displayed for certain pages)
- No content can be seen if zoomed out too far, might be unclear to the user what happened and that zooming in will fix problem
The Document Viewer is still not very user friendly in my opinion and I am not sure how much further development time should be invested in its current state.
It might be a better option to get rid of it alltogether and always use the "Open file (F4)" option when a user wants to open a PDF.
=> Added ability to change zoom using Ctrl + Scroll in Document Viewer

src/main/java/org/jabref/preferences/JabRefPreferences.java
Fixes #10966
was introduced in bec55f8c42430221838fbd18a91fe652e2408dda
=> Fix menu bar gone on macOS

src/main/java/org/jabref/gui/entryeditor/citationrelationtab/BibEntryRelationsRepository.java, src/main/java/org/jabref/gui/entryeditor/citationrelationtab/semanticscholar/SemanticScholarFetcher.java
We should avoid `throw new RuntimeExcption()`. I replaced **all** calls. Maybe, I replaced too much. IDK.
=> Replace throw new RuntimeException by LOGGER / other throws

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/citationrelationtab/BibEntryRelationsCache.java
Citations and References under the "Citation Relations" Tab are now saved in an LRUMap instead of a regular HashMap.
Their size is now limited to a (somewhat arbitrarily chosen) 100 entries.
I chose to initialize them at max size to avoid resizing, although I am not sure whether this works as intended. Each Map stores Lists which themselves grow and potentially lead to reallocation of memory.
=> Store Citation Relations in LRU Cache

CHANGELOG.md, src/main/java/org/jabref/gui/cleanup/CleanupPresetPanel.fxml, src/main/java/org/jabref/gui/cleanup/CleanupPresetPanel.java, src/main/java/org/jabref/logic/cleanup/CleanupWorker.java, src/main/java/org/jabref/logic/cleanup/RemoveLinksToNotExistentFiles.java, src/main/java/org/jabref/preferences/CleanupPreferences.java, src/test/java/org/jabref/logic/cleanup/RemoveLinksToNotExistentFilesTest.java
We added a functionality to remove non-existent files and added it as an option in the cleanup entries. We also grouped the checkboxes in cleanup entries according to the suggestion made by koppor.
Closes #10929 
1. Non-existent file is linked to article
2. Cleanup Entries
3. Remove non-existent entries added, and the checkboxes are grouped
4. After cleanup the non-existent file is no longer linked to the article
=> Adds feature CleanupJob for removing non-existent files

src/main/java/org/jabref/model/entry/identifier/DOI.java, src/test/java/org/jabref/model/entry/identifier/DOITest.java
Fixes #10985 
Some of the DOI links are not working because it has some special characters in it. 
For example ```10.1007/978-3-030-02671-4\_7``` it has an extra backslash '\\'.
I tried to fix the general problem instead of just the backslashes so I tried to eliminate all [unsafe character](https://www.ietf.org/rfc/rfc1738.txt#:~:text=These%20characters%20are%20%22%7B%22%2C,be%20encoded%20within%20a%20URL.)
In the code I added them to the CHARS_TO_REMOVE regex variable. 
as for '^' I handled it alone because the [formatter](https://github.com/JabRef/jabref/blob/f5efb349da7932c4149b2f9992533ccb1340d8e6/src/main/java/org/jabref/model/entry/identifier/DOI.java#L170) is replacing any ```^ + number``` with the superscript of the the number 
for example: 10^34 -> 10<sup>3</sup>4
=> Enhance DOI parser to deal with special characters

src/main/java/org/jabref/gui/autocompleter/AutoCompletePreferences.java, src/main/java/org/jabref/gui/preferences/autocompletion/AutoCompletionTab.fxml, src/main/java/org/jabref/gui/preferences/autocompletion/AutoCompletionTab.java, src/main/java/org/jabref/gui/preferences/autocompletion/AutoCompletionTabViewModel.java, src/main/java/org/jabref/model/entry/field/FieldFactory.java
Closes #10952 
Use tags editor for auto-completion preferences with suggestions for all standard BibTeX and BibLaTeX fields.
- Should users be able to add a field that is not a standard Bib(La)TeX field, i.e., a field not suggested?
- Why is it important to always add `crossref`, `related`, and `entryset` fields?  https://github.com/JabRef/jabref/blob/79ba1f0d461268fbafa4196e6a4b5fec0a114b95/src/main/java/org/jabref/migrations/PreferencesMigrations.java#L297-L304
=> Use tags editor for auto completion preferences

src/main/java/org/jabref/gui/entryeditor/RequiredFieldsTab.java, src/main/java/org/jabref/migrations/CustomEntryTypePreferenceMigration.java, src/main/java/org/jabref/model/entry/BibEntryType.java, src/main/java/org/jabref/model/entry/BibEntryTypeBuilder.java, src/main/java/org/jabref/model/entry/EntryConverter.java, src/main/java/org/jabref/model/entry/field/FieldFactory.java, src/main/java/org/jabref/model/entry/field/OrFields.java, src/main/java/org/jabref/model/entry/types/BibtexEntryTypeDefinitions.java
The ordering of required and optional fields is important (e.g., for serialization, ...).
The API should respect the order. Thus, I introduced an explicit `SequencedSet` here.
Longer story: Experiments with new editor layout: https://github.com/koppor/jabref/issues/679 (and idea of https://github.com/JabRef/jabref/issues/6191).
=> Use SequencedSet for required and optional fields

src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/gui/autocompleter/ContentSelectorSuggestionProvider.java, src/main/java/org/jabref/gui/autocompleter/SuggestionProvider.java, src/main/java/org/jabref/gui/autocompleter/SuggestionProviders.java, src/main/java/org/jabref/gui/fieldeditors/FieldEditors.java, src/main/java/org/jabref/gui/fieldeditors/LinkedEntriesEditor.java, src/main/java/org/jabref/gui/fieldeditors/LinkedEntriesEditorViewModel.java
Context: https://github.com/JabRef/jabref/pull/10910#issuecomment-1974107026, https://github.com/JabRef/jabref/pull/10910#issuecomment-1974642081
Related issue: #8145
=> fix suggestion provider for crossref field

CHANGELOG.md, build.gradle, src/main/java/org/jabref/gui/JabRefFrame.java, src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/gui/StateManager.java, src/main/java/org/jabref/gui/fieldeditors/FieldEditors.java, src/main/java/org/jabref/gui/fieldeditors/LinkedEntriesEditor.java, src/main/java/org/jabref/gui/fieldeditors/LinkedEntriesEditorViewModel.java, src/main/resources/l10n/JabRef_en.properties
Fixes #5484
Fixes https://github.com/JabRef/jabref/issues/9369
Closes https://github.com/JabRef/jabref/pull/8456
Not beautiful, but works.
=> Fixed jump to entry from crossref

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/OtherFieldsTab.java
Before: Field shown twice:
After:
"Other fields" not shown.
=> Fix "Other fields" tab respecting custom tabs

src/main/java/org/jabref/migrations/PreferencesMigrations.java, src/main/java/org/jabref/preferences/JabRefPreferences.java
The default preferences contain configuration for a tab "Comments":
This became obsolete with the PR adding user-specific comment fields (https://github.com/JabRef/jabref/pull/9727)
After this PR:
Added a migration
=> Remove obsolete "Comments" tab configuration

src/test/java/org/jabref/model/entry/BibEntryTypesManagerTest.java
Follow-up to https://github.com/JabRef/jabref/pull/10823
openRewrite does not treat method names `testsXyzAbc`. These get `sXyzAbc` instead of `xyzAbc`.
JabRef had three of them. Fixed.
=> Fix test names

CHANGELOG.md, src/main/java/org/jabref/Launcher.java, src/main/resources/l10n/JabRef_en.properties
JabRef deleted old log files upon start. (Reported by @Doublonmousse at https://github.com/JabRef/jabref/issues/10853#issuecomment-1994162901 - thank you for the report!)
This PR fixes that.
=> Change to rolling logs

src/main/java/org/jabref/Launcher.java
Follow-up to https://github.com/JabRef/jabref/pull/11023, because of https://github.com/JabRef/jabref/pull/11023#issuecomment-1997570271
=> Fix log file path on Windows

rewrite.yml
Fixes openrewrite output
recipe validation error in org.jabref.config.rewrite.cleanup.recipeList[4] (in file:/C:/git-repositories/JabRef/rewrite.yml): recipe 'org.openrewrite.java.recipes.UseJavaParserBuilderInJavaTemplate' does not exist.
=> Remove non-existing recipe

src/test/java/org/jabref/logic/formatter/bibtexfields/RemoveBracesFormatterTest.java
=> Convert RemoveBracesFormatterTest to @ParameterizedTest

CHANGELOG.md, src/main/java/org/jabref/logic/importer/util/FileFieldParser.java, src/test/java/org/jabref/logic/importer/fileformat/BibtexParserTest.java, src/test/java/org/jabref/logic/importer/util/FileFieldParserTest.java
=> Fixes Zotero file handling for absolute paths

CHANGELOG.md, buildres/windows/JabRefHost.ps1
This implements the solution suggested by https://github.com/JabRef/JabRef-Browser-Extension/issues/493#issuecomment-1428073766
Closes https://github.com/JabRef/JabRef-Browser-Extension/issues/493
I found the issue to be the `Remove-Item` call, because the temporary file is being accessed by the running JabRef instance, so it results in the error message:
```
Cannot remove item ...\AppData\Local\Temp\1\tmp7642.tmp: The process cannot access the file '...\AppData\Local\Temp\1\tmp7642.tmp' because it is being used by another process.
```
By redirecting the output of that to $null, that error is not sent to the plugin and so the issue is patched.
I will create a separate issue in this repository to track the remaining problem of the temporary files not being deleted when the script is run.
=> Fix error on browser extension import

.github/workflows/deployment-jdk-ea.yml, build.gradle
This is the "uncritical" part of https://github.com/JabRef/jabref/pull/11057.
It removes released JDK and JavaFX versions from the EA build.
=> Remove 22 from EA builds

.github/workflows/deployment-jdk-ea.yml
The tests at https://github.com/JabRef/jabref/pull/10995 were failing for the EA build. I think, I just missed some secrets precense checks.
=> Add more secrete presence checks

CHANGELOG.md, src/main/java/org/jabref/gui/linkedfile/DownloadLinkedFileAction.java, src/test/java/org/jabref/gui/linkedfile/DownloadLinkedFileActionTest.java
I just noticed that using the "Redownload file" funcionality from linked files copied the current path to the sourceURL, which made it so that the actual source URL was lost upon the second download of a file. To reproduce:
1. Create an entry
2. Download a file to the entry with the Download button on the right of the Files section in the General tab
3. Right-click on the file, choose Edit, and observe that the "Link" points to the local file's path, and sourceURL points to the url used for the download
4. Delete the downloaded file from the download directory
5. Right-click again on the file and choose "Redownload file"
6. When the download is finished, right-click the linked file, choose Edit, and notice that both Link and sourceURL point to the local path
Through git blame, the changes …
=> Fix regression from adding tests.

src/main/java/org/jabref/logic/formatter/bibtexfields/UnicodeToLatexFormatter.java, src/main/java/org/jabref/logic/util/strings/HTMLUnicodeConversionMaps.java, src/test/java/org/jabref/logic/formatter/bibtexfields/UnicodeToLatexFormatterTest.java, src/test/java/org/jabref/logic/layout/format/LatexToUnicodeFormatterTest.java
I added the test case mentioned in [#5547](https://github.com/JabRef/jabref/issues/5547#issuecomment-554067764) and other test cases to ensure reliability. 
The problem with the test case was that ```ı̄``` is not one character it's a combination of ```ı  +   ̄``` unlike ```ā```. What was happennig is that ```ı``` was being converted to ```\i``` and then ```  ̄ ``` was being converted to ```{\={}}``` so the result would be ```{\i{\={}}}```.
I made it that we deal with such characters that cause conflict after combining accents. They are stored in a new variable called ```UNICODE_LATEX_CONVERSION_MAP_AFTER_COMBINING_ACCENTS``` I think this will be the base to deal with such cases.
I also added some of the underdot characters as the previous implementation didn't handle them.
=> Add test cases for "UnicodeToLatex" and "LatexToUnicode"

LICENSE, buildres/LICENSE_with_Privacy.md
Our installer listed an older year.
=> Fix year in installer

build.gradle, src/main/java/module-info.java, src/main/java/org/jabref/gui/theme/ThemeManager.java
Refs #8729 
Follow-up to #10593
=> Replace jthemedetector with new platform prefs

src/main/java/org/jabref/gui/linkedfile/DownloadLinkedFileAction.java, src/main/resources/l10n/JabRef_en.properties
This addresses #11075 .
The old error dialog:
Has been updated to:
Edit: On review, it has been further changed to:
The relevant localization string has also been added to ```JabRef_en.properties```.
=> Change error dialog string

CHANGELOG.md, src/main/java/org/jabref/logic/xmp/XmpUtilWriter.java, src/test/java/org/jabref/logic/exporter/XmpPdfExporterTest.java
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/271
=> Do no export file field in XMP

CHANGELOG.md, src/main/java/org/jabref/model/entry/identifier/DOI.java, src/test/java/org/jabref/model/entry/identifier/DOITest.java
This pull request closes #10648 
On attempting to use JabRef's "Import by ID" feature as described in the linked issue, while importing using DOI URLs or DOI numbers containing some special characters, such as [https://doi.org/10.1175/1520-0493(2002)130%3C1913:EDAWPO%3E2.0.CO;2](https://doi.org/10.1175/1520-0493(2002)130%3C1913:EDAWPO%3E2.0.CO;2), the following error was thrown:
as if, the DOI link itself was an invalid one. However, the link was perfectly fine.
The bug was extremely subtle and tough to trace. On careful inspection it was detected that when the ```performSearchById(identifier)``` was being called somewhere along the flow, line 23 was causing the variable ```doi``` to be assigned to ```https://doi.org/10.1175/1520-0493(2002)130%3C1913:EDAWPO%3E2.0.CO```. That is, somehow …
=> Fix DOI Url parsing

gradle/wrapper/gradle-wrapper.properties
Update Gradle Wrapper from 8.7-rc-3 to 8.7.
Read the release notes: https://docs.gradle.org/8.7/release-notes.html
---
- Gradle release: `8.7`
- Distribution (-bin) zip checksum: `544c35d6bd849ae8a5ed0bcea39ba677dc40f49df7d1835561582da2009b961d`
- Wrapper JAR Checksum: `cb0da6751c2b753a16ac168bb354870ebb1e162e9083f116729cec9c781156b8`
---
<details>
<br /> …
=> Update Gradle Wrapper from 8.7-rc-3 to 8.7

CHANGELOG.md, src/main/java/org/jabref/logic/formatter/bibtexfields/HtmlToLatexFormatter.java, src/main/java/org/jabref/logic/importer/fetcher/DoiFetcher.java, src/test/java/org/jabref/logic/formatter/bibtexfields/HtmlToLatexFormatterTest.java
- Fixes https://github.com/koppor/jabref/issues/286
- Closes https://github.com/JabRef/jabref/pull/11078
While commenting on PR https://github.com/JabRef/jabref/pull/11078, I learned that we could simply using our `HtmlToLatexFormatter`. I needed to teach it to understand `\` in front, but it worked well.
Thanks to @InAnYan who found out where to put the cleanup. Thus, I added him to `Co-authored-by`.
=> Fix html content handling when fetching IEEE papers

CHANGELOG.md, src/main/java/org/jabref/logic/citationkeypattern/BracketedPattern.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/test/java/org/jabref/logic/citationkeypattern/BracketedPatternTest.java, src/test/java/org/jabref/logic/citationkeypattern/CitationKeyGeneratorTest.java, src/test/java/org/jabref/logic/citationkeypattern/MakeLabelWithDatabaseTest.java
=> Fix the handling of an "overflow" of authors at `[authIniN]`

CHANGELOG.md, build.gradle, external-libraries.md, src/main/java/org/jabref/gui/entryeditor/citationrelationtab/CitationRelationsTab.css, src/main/java/org/jabref/gui/importer/ImportEntriesDialog.css, src/main/java/org/jabref/gui/importer/ImportEntriesDialog.java
- Fixes #10931.
- Fixes #11081. This was a bug in controlsfx, which was fixed in https://github.com/controlsfx/controlsfx/pull/1541. Just updated to version 11.2.1.
=> Add text wrapping to the import dialog

CHANGELOG.md, src/main/java/org/jabref/gui/importer/ImportEntriesViewModel.java, src/main/java/org/jabref/gui/linkedfile/DownloadLinkedFileAction.java, src/main/resources/l10n/JabRef_en.properties
Closes #11075.
This is an attempt to make JabRef's handling of imports with an unsaved library more newcomer-friendly.
Earlier, if there was an attempt to import entries via web search, with the source being Springer, Arxiv, etc. (any source that allows associated pdfs to be downloaded), we would get the following dialog if the library was not saved:
The problem was that: 
**(1)** This dialog was not good UX (as pointed out by @koppor).
**(2)** This dialog would pop up multiple times - for example, if the user had selected 25 entries and clicked on import (without having saved the library), the dialog would come up and needed to be closed 25 times before returning to functionality. This was very inconvenient, especially for people who are new to JabRef. …
=> Remove warnings shown when importing search entries in unsaved libraries

docs/code-howtos/custom-svg-icons.md
I think, the sentence can be removed, because the text above (and below) provide enough context.
=> Remove obsolete sentence

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fileformat/BibtexParser.java, src/main/java/org/jabref/logic/util/io/FileUtil.java, src/test/java/org/jabref/logic/importer/fileformat/BibtexParserTest.java
Closes #11117
Improve error handling for bibdesk linked files parsing
=> improve error handling for bibdesk files

CHANGELOG.md, src/main/java/org/jabref/logic/importer/util/MetaDataParser.java, src/main/java/org/jabref/model/entry/BibEntryTypeBuilder.java, src/test/java/org/jabref/model/entry/BibEntryTypeBuilderTest.java
Fixes https://github.com/JabRef/jabref/issues/11127
This is a fix for the exception introduced in https://github.com/JabRef/jabref/pull/11013#pullrequestreview-1935076690 
The main culprit is that we did not do a migration to remove duplicate fields
=> Fix importing of custom entry types with duplicate fields

docs/contributing.md
The link to the GitHub flow was expired in devdocs . This commit updates the link to the new URL:
https://docs.github.com/en/get-started/using-github/github-flow
=> docs: fix expired link in devdocs.jabref.org/contributing.html

.gitmodules
=> Set git submodules ignore to dirty

src/main/java/org/jabref/gui/help/AboutDialogViewModel.java
Closes #11135 
This is a small fix to the link to JabRef's MIT license file, as pointed out in the issue. The license file is LICENSE and not LICENSE.md
- ~[ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)~
- ~[ ] Tests created for changes (if applicable)~
- ~[ ] Screenshots added in PR description (for UI changes)~
=> Fix LICENSE link

CHANGELOG.md, src/main/java/org/jabref/gui/actions/StandardActions.java, src/main/java/org/jabref/gui/keyboard/KeyBinding.java
This PR adds the keyboard shortcut <kbd>Ctrl</kbd> + <kbd>,</kbd> to open the preferences.
=> Add keyboard shortcut Ctrl + , to open preferences

CHANGELOG.md, src/main/java/org/jabref/gui/actions/StandardActions.java, src/main/java/org/jabref/gui/preferences/keybindings/KeyBindingsTab.fxml, src/main/java/org/jabref/gui/preferences/keybindings/KeyBindingsTab.java, src/main/java/org/jabref/gui/preferences/keybindings/KeyBindingsTabViewModel.java, src/main/resources/l10n/JabRef_en.properties
This PR updates the Preferences tab for **Key bindings**, renaming it to **Keyboard shortcuts**. It updates the tab title, the page title and the messages when changing keyboard shortcuts. This follows a request from @koppor on the Gitter channel.
This PR updates the file in `resources/l10n/JabRef_en.properties` to replace all occurrences of `key\ bindings` with `keyboard\ shortcuts`.
=> Change "Key bindings" to "Keyboard shortcuts"

.gitmodules
This reverts commit dd2268d72e30ca64ade1548413cf127f8887b97f introduced at https://github.com/JabRef/jabref/pull/11148.
I have many diffs here in submodules when switching branches.
According to https://stackoverflow.com/questions/3240881/git-can-i-suppress-listing-of-modified-content-dirty-submodule-entries-in-sta/12527608#12527608 - `all` is better than `dirty`.
=> Revert "Set git submodules ignore to dirty (#11148)"

src/main/java/org/jabref/gui/search/GlobalSearchBar.java
Fixes #11171
https://github.com/JabRef/jabref/assets/52158423/48a35fc1-a010-40c3-bb2e-2e123447d893
=> Set the initial global search query to the current normal search query

.github/workflows/deployment-arm64.yml
JavaFX homepage (https://jdk.java.net/javafx23/) shows
macOS / AArch64 	
I was very confused. I consulted Wikipedia. They say:
Thus, I use ARM64. And I prefix it with "macOS" to ensure that it is clear that it is NOT for arm32bit linux or something.
=> Update runner name

.github/workflows/deployment.yml, .github/workflows/update-gradle-wrapper.yml
Just very small fixes.
Applies suggestion of https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#remove-unused-files-from-gradle-user-home-before-saving-to-the-cache
=> Minor updates at CI

.github/workflows/deployment-arm64.yml, .github/workflows/deployment-jdk-ea.yml, .github/workflows/deployment.yml, .github/workflows/tests-fetchers.yml, .github/workflows/tests.yml, .github/workflows/update-gradle-wrapper.yml
This PR switches the runtime JDK for gradle to [Eclipse Temurin](https://adoptium.net/de/temurin/releases/) (and away from [Liberica JDK](https://bell-sw.com/libericajdk/)). The main reason is that Temurin is the standard JDK and we do not need derivations here. We have used Liberica in the past, because they included our JDK fix earlier than the others. Now, this is obsolete.
This DOES NOT change the JDK used for compilation. This is done by the [vendor statement](https://docs.gradle.org/current/userguide/toolchains.html#sec:vendors) inside the `toolchain` configuration in `build.gradle`. 
> If no vendor is specified, distributions are iterated in the order they are provided by the [DiscoAPI](https://github.com/foojayio/discoapi), …
=> Switch from liberica to temurin

.github/workflows/deployment-arm64.yml, .github/workflows/deployment-jdk-ea.yml, .github/workflows/tests-fetchers.yml, .github/workflows/tests.yml
Tries to apply https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#remove-unused-files-from-gradle-user-home-before-saving-to-the-cache
I was thinking to use read-only caches, but I was not sure which test should be read only... The tests seem to fetch different dependencies and AFAIK gradle is a lazy loader...
=> More "gradle-home-cache-cleanup: true"

CHANGELOG.md, src/main/java/org/jabref/gui/Base.css, src/main/java/org/jabref/gui/actions/StandardActions.java, src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/groups/GroupTreeView.java, src/main/java/org/jabref/gui/importer/fetcher/WebSearchPaneView.java, src/main/java/org/jabref/gui/keyboard/KeyBinding.java, src/main/java/org/jabref/gui/keyboard/KeyBindingRepository.java, src/main/java/org/jabref/gui/keyboard/TextInputKeyBindings.java, src/main/java/org/jabref/gui/search/GlobalSearchBar.java, src/main/java/org/jabref/gui/search/SearchTextField.java, src/main/resources/l10n/JabRef_en.properties, src/test/java/org/jabref/gui/search/GlobalSearchBarTest.java
Fixes https://github.com/JabRef/jabref/issues/10764
~~I somehow hang. Seems that the `CLEAR_SEARCH` is not found - even if configured.~~
~~Did not reset preferences again... Is it because `Esc` != `Escape`?~~
```
WARN: event: KeyEvent [source = CustomTextField[id=searchField, styleClass=text-input text-field custom-text-field clearable-field search-field], target = CustomTextField[id=searchField, styleClass=text-input text-field custom-text-field clearable-field search-field], eventType = KEY_PRESSED, consumed = false, character =  , text = , code = ESCAPE]
2024-04-13 14:54:09 [JavaFX Application Thread] org.jabref.gui.search.SearchTextField.lambda$create$2()
WARN: bindings: [CLOSE]
```
Just removing the case statement for the text field would be enough to fix the issue. 
Background:
- …
=> Fix pressing ESC in text fields

build.gradle
Follow-up to https://github.com/JabRef/jabref/pull/11195
When running JabRef using gradle, one gets following outputs:
```
WARNING: Unknown module: org.jabref.merged.module specified to --add-exports
WARNING: Unknown module: org.jabref.merged.module specified to --add-exports
WARNING: Unknown module: org.jabref.merged.module specified to --add-opens
WARNING: Unknown module: org.jabref.merged.module specified to --add-opens
WARNING: Unknown module: org.jabref.merged.module specified to --add-opens
```
They are caused by our new `applicationDefaultJvmArgs` entry. That entry is needed for our `jpackage` task. 
However, for `run`, they are not needed. Thus, this PR adds a "hot patch" to the `run` task to avoid that output.
=> Remove WARNING outputs at "run"

CHANGELOG.md, src/main/java/org/jabref/gui/collab/DatabaseChangeDetailsViewFactory.java, src/main/java/org/jabref/gui/collab/metedatachange/MetadataChangeDetailsView.java, src/main/java/org/jabref/gui/libraryproperties/contentselectors/ContentSelectorViewModel.java, src/main/java/org/jabref/logic/bibtex/comparator/MetaDataDiff.java, src/main/java/org/jabref/model/metadata/ContentSelectors.java, src/test/java/org/jabref/logic/bibtex/comparator/MetaDataDiffTest.java
Fixes https://github.com/JabRef/jabref/issues/9064
=> Fix changed on disk for ContentSelectors and groups

build.gradle, src/main/java/org/jabref/logic/exporter/AtomicFileOutputStream.java
fix atomic outputstream closed channels exceptions
Release notes:
https://github.com/openjdk/jfx22u/commit/bbad35849e5d855fc84a3693c9c41e96cd555dd0
=> Fix atomic outputstream closed channels exceptions (and update JavaFX)

src/main/java/org/jabref/logic/database/DuplicateCheck.java, src/test/java/org/jabref/logic/database/DuplicateCheckTest.java
Closes #8885 
- I placed the modified ISBN check below this statement
https://github.com/JabRef/jabref/blob/6789460795b5f3eaabe960027d851ed08493ad95/src/main/java/org/jabref/logic/database/DuplicateCheck.java#L334
to ensure that the types are the same first.
- Added 2 tests.
=> Bring back a modified ISBN check and add more tests

build.gradle
When trying to download JavaFX sources or documentation using IntelliJ, Gradle fails this error:
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':ijDownloadSourcesec754862-2f9'.
> Could not resolve all files for configuration ':downloadSources_a230d098-20fe-44c1-a391-cf97fe123b54'.
> Could not resolve org.openjfx:javafx-controls:22.0.1.
Required by:
project :
> Cannot choose between the following variants of org.openjfx:javafx-controls:22.0.1:
- linux-aarch64Runtime
- linuxRuntime
- mac-aarch64Runtime
- macRuntime
- runtime
- winRuntime
All of them match the consumer attributes:
- Variant 'linux-aarch64Runtime' capability org.openjfx:javafx-controls:22.0.1:
- Unmatched attributes:
- Provides org.gradle.category 'library' but the consumer didn't …
```
=> Fix issue when downloading JavaFX Sources with IntelliJ

.github/workflows/tests.yml
We see PRs coming from "main". It seems not all contributors follow our guidelines. We do have at the first page of https://devdocs.jabref.org/contributing#contribute-code a bold hint not to use main. Could be made even better (refs https://github.com/JabRef/jabref-issue-melting-pot/issues/416)
This PR adds a check if the PR originates from `main`. I do post from `koppor/main` to check for the effects.
=> Add check for PRs from "main"

.github/workflows/deployment-jdk-ea.yml
See https://github.com/koppor/jabref/actions/runs/8795100403/job/24135640567. The EA version is build, but no artifacts uploaded. This should also be possible for forks. (The action runs in all cases at forks, too. Should produce some results though)
=> Fix artifact creation for forks

src/test/java/org/jabref/logic/importer/fetcher/BiodiversityLibraryTest.java, src/test/java/org/jabref/logic/importer/fetcher/CiteSeerTest.java, src/test/java/org/jabref/logic/importer/fetcher/CrossRefTest.java, src/test/java/org/jabref/logic/importer/fetcher/IEEETest.java, src/test/java/org/jabref/logic/importer/fetcher/ISIDOREFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/ScholarArchiveFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/SemanticScholarTest.java, src/test/java/org/jabref/logic/importer/fileformat/PdfGrobidImporterTest.java
Seeing that more and more people are confused because of failing fetcher tests (e.g., https://github.com/JabRef/jabref/pull/11253), I did a "brute force" fix.
Note that I also needed to disable "GROBID", because it did not return anything.
=> Fix Biodiversity fetcher test results

src/main/java/org/jabref/gui/search/GlobalSearchBar.java
=> Update search results when active database changes

src/main/java/org/jabref/cli/JabRefCLI.java, src/main/resources/l10n/JabRef_en.properties, src/test/java/org/jabref/cli/JabRefCLITest.java
=> Remove obsolete methods

.github/workflows/deployment-arm64.yml, .github/workflows/deployment.yml
fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/428
Does this issue also occur under windows/linux`
=> Fix missing add opens for javafx on mac

build.gradle, docs/code-howtos/testing.md
We used a deprecated gradle setting (`$buidDir`). Morevoer, [JaCoCo](https://www.eclemma.org/jacoco/) did not cover the "normal" test cases. Both is fixed with this PR.
After executing `./gradlew jacocoTestReport`, `build/reports/jacoco/test/html/index.html` is generated:
This PR also includes jacoco in `testing.md` (and restructures it a bit).
=> Fix jacoco plugin

src/main/java/org/jabref/logic/pdf/search/PdfIndexer.java
Addressed an issue where outdated pdf files were not being removed from the Lucene index.
The duplicate checker checks for the modification time of the pdf but doesn't remove it from the index if it is outdated.
This causes a lot of duplication in the index every time a library opens, the pdf will be added to the index again.
This also led to incorrect search results when using old keywords.
=> Remove outdated pdf indexed files from Lucene index

src/main/java/org/jabref/model/entry/BibEntry.java
While discussing Ids vs. CitationKey, we found out that the comments of BibEntry could be improved.
This somehow refs https://github.com/JabRef/jabref/blob/main/docs/code-howtos/remote-storage-jabdrive.md.
=> Fix comment

src/main/java/org/jabref/gui/entryeditor/LatexCitationsTabViewModel.java
An exception is thrown when switching from the "search result" tab to the "latex citations" tab
=> Update latex citations status in JavaFx thread

docs/code-howtos/index.md
Small fix in our code documentation
=> Remove wrong "Database" word

docs/code-howtos/index.md, src/main/java/org/jabref/gui/externalfiles/ExternalFilesEntryLinker.java, src/main/java/org/jabref/gui/externalfiletype/CustomExternalFileType.java, src/main/java/org/jabref/gui/linkedfile/LinkedFilesEditDialogViewModel.java, src/main/java/org/jabref/logic/cleanup/RelativePathsCleanup.java, src/main/java/org/jabref/logic/externalfiles/LinkedFileHandler.java, src/main/java/org/jabref/logic/util/io/FileUtil.java
While reviewing https://github.com/JabRef/jabref/pull/11327, I missed a method in `FileUtil` - and also noticed outdated documentation. This PR fixes that.
=> New method FileUtil#relativize

src/main/java/org/jabref/gui/util/BackgroundTask.java, src/main/java/org/jabref/gui/util/DefaultTaskExecutor.java, src/main/java/org/jabref/logic/pdf/search/IndexingTaskManager.java
Small improvement of our JavaDoc while discussiong things.
=> Add documentation for BackgroundTask (and improve code)

docs/code-howtos/localization.md, src/test/java/org/jabref/logic/l10n/LocalizationConsistencyTest.java
=> Improve devdocs for localization

docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-12-build.md
Typo in line no. 45: select a JDK 21
Correction: select JDK 21
Typo in line no. 69: you re-open
Correction: you reopen
Typo in line no. 76: omited
Correction: omitted
Typo in line no. 87 : always the
Correction: always be the
Typo in line no. 96 : parts JabRef
Correction: parts of JabRef
Typo in line no. 105: JabRef is opened
Correction: JabRef is open
Typo in line no. 132 : In the menubar
Correction: In the menu bar
Typo in line no. 146: Enter 'bibenrytest'
Correction: Enter 'bibentrytest'
Typo in line no. 180 : enables to start the debugger
Correction: enables the debugger to start.
=> Update intellij-12-build.md to Fix Minor Typos

src/main/java/org/jabref/gui/mergeentries/DiffHighlighting.java, src/test/java/org/jabref/gui/mergeentries/DiffHighlightingTest.java
Our diffs now work differently. No one complained while using the new MergeEntriesDialog. @HoussemNasri @Siedlerchr
=> Remove unused generateSymmetricHighlighting

src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/entryeditor/EntryEditorTab.java, src/main/java/org/jabref/gui/entryeditor/FieldsEditorTab.java, src/main/java/org/jabref/gui/entryeditor/OffersPreview.java, src/main/java/org/jabref/gui/entryeditor/PreviewTab.java, src/main/java/org/jabref/gui/entryeditor/RelatedArticlesTab.java, src/main/java/org/jabref/gui/entryeditor/citationrelationtab/CitationRelationsTab.java, src/main/java/org/jabref/gui/shared/SharedDatabaseUIManager.java
In the context of another PR, I needed to work with the EntryEditor. I moved the refactorings out to a separate PR.
- Introduce interface OffersPreview
- Merge two lists of tabs
- Introduce method
- Rename variables
=> Streamline code in EntryEditor

src/main/java/org/jabref/gui/collab/DatabaseChange.java, src/main/java/org/jabref/gui/collab/DatabaseChangeList.java, src/main/java/org/jabref/gui/collab/DatabaseChangeMonitor.java, src/main/java/org/jabref/logic/bibtex/comparator/BibDatabaseDiff.java, src/main/java/org/jabref/logic/bibtex/comparator/BibEntryDiff.java, src/main/java/org/jabref/logic/bibtex/comparator/MetaDataDiff.java, src/main/java/org/jabref/logic/bibtex/comparator/PreambleDiff.java, src/main/java/org/jabref/model/entry/BibEntry.java, src/main/resources/tinylog.properties, src/test/java/org/jabref/logic/bibtex/comparator/BibDatabaseDiffTest.java
Made during thinking of https://github.com/JabRef/jabref/issues/4877 (but did not work)
=> Improve code of BibDataBaseDiff

src/main/java/org/jabref/preferences/JabRefPreferences.java
Exception was always thrown even when no passwords were there to remove.
This is just fixing a log message. Do we need a changelog here too for that?
Processing business logic with exceptions is bad, but there is no other way with the current implementation of KeyRing.
=> Fix error log on storing preferences

src/main/java/org/jabref/model/database/BibDatabaseContext.java
Follow-up to https://github.com/JabRef/jabref/pull/11271
Side comment: I wonder why that PR fixed https://github.com/JabRef/jabref/issues/8933. The `hashCode` was introduced at #10776, which was implemented after the issue appeared.
=> Add some more JavaDoc

src/main/java/org/jabref/gui/StateManager.java, src/main/java/org/jabref/model/database/BibDatabaseContext.java
Follow-up to #11400
Replace mapping of the BibDatabaseContext to use UIDs, fixing the issue of search results being 0 after updating an entry.
=> Search result mapping use UIDs instead of hashcodes of BibDatabaseContext

CHANGELOG.md, src/main/java/org/jabref/gui/collab/DatabaseChangeDetailsView.java, src/main/java/org/jabref/gui/collab/DatabaseChangeDetailsViewFactory.java, src/main/java/org/jabref/gui/collab/entrychange/EntryChangeDetailsView.java, src/main/java/org/jabref/gui/collab/groupchange/GroupChangeDetailsView.java, src/main/java/org/jabref/gui/collab/metedatachange/MetadataChangeDetailsView.java, src/main/java/org/jabref/gui/collab/preamblechange/PreambleChangeDetailsView.java, src/main/java/org/jabref/gui/collab/stringadd/BibTexStringAddDetailsView.java, src/main/java/org/jabref/gui/collab/stringchange/BibTexStringChangeDetailsView.java, src/main/java/org/jabref/gui/collab/stringdelete/BibTexStringDeleteDetailsView.java, src/main/java/org/jabref/gui/collab/stringrename/BibTexStringRenameDetailsView.java
Closes [issue 1120](https://github.com/JabRef/jabref/issues/11220)
See screenshots bellow.
And refactor some code from the **org.jabref.gui.collab** package:
- Make the anchor pane offset configuration common for all subclasses of  **org.jabref.gui.collab.DatabaseChangeDetailsView**
- Replace the pattern mathing for if statement by a pattern matching for switch statement in **org.jabref.gui.collab.DatabaseChangeDetailsViewFactory** and remove the related TODO
Please read commits one by one to make PR easier to understand.
=> Fix missing external changes resolver dialog scrollbar 

src/main/java/org/jabref/gui/LibraryTab.java
The code executed when closing a SQL shared library should be in the code closing the library, not at the part where a close is requested.
=> Fix close in the context of shared databases

build.gradle
Fixes https://github.com/JabRef/jabref/issues/11426
on mac it was already in the pipeline
=> add missing add opens call

.github/workflows/tests.yml
Fixes following warning
Warning: This job uses deprecated functionality from the 'gradle/wrapper-validation-action' action. Consult the logs for more details.
DEPRECATION: The action `gradle/wrapper-validation-action` has been replaced by `gradle/actions/wrapper-validation`. See https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#the-action-gradlewrapper-validation-action-has-been-replaced-by-gradleactionswrapper-validation
=> Update gradle wrapper validation action

CHANGELOG.md, src/main/java/org/jabref/gui/documentviewer/DocumentViewModel.java, src/main/java/org/jabref/gui/documentviewer/DocumentViewer.fxml, src/main/java/org/jabref/gui/documentviewer/DocumentViewerView.java, src/main/java/org/jabref/gui/documentviewer/DocumentViewerViewModel.java, src/main/java/org/jabref/gui/documentviewer/ShowDocumentViewerAction.java, src/main/java/org/jabref/gui/entryeditor/fileannotationtab/FulltextSearchResultsTab.java
Some improvements to the document viewer and search results tab
- Clicking on the page number to open the document viewer, it was displaying the first linked file of the selected entry instead of the correct file. Also without custom CSS.
- "Open file" was open all linked files to the entry.
- Added validation to the next and previous page buttons in the document viewer to disable them on the first and last pages.
- Close the document viewer when the selected entry does not have any linked files.
- Avoid opening multiple document viewers.
- Selecting multiple entries will add all linked files of the selected entries to the list of files.
=> Improve document viewer

src/main/java/org/jabref/gui/preferences/PreferencesDialog.fxml, src/main/java/org/jabref/gui/preferences/PreferencesDialogView.java
Normal screen resolutions are FullHD (1920x1080) or higher. Therefore, I took the liberty to increase the preferered hight of our preference dialog.
Before:
After:
=> Increase height of preferences dialog

build.gradle, settings.gradle
We get error `206` on Windows if we add more dependencies. See https://github.com/InAnYan/jabref/issues/5 for details.
There is a fix (https://github.com/java9-modularity/gradle-modules-plugin/pull/282). This PR ports this fix to the `main` branch to enable new branches on Windows.
=> Enable `./gradlew run` on Windows if more dependencies are used

CHANGELOG.md, src/main/java/org/jabref/gui/cleanup/CleanupAction.java, src/main/resources/l10n/JabRef_en.properties
=> REmove message when opening cleanup entries

CHANGELOG.md, snap/local/JabRef-launcher
Fixes https://github.com/JabRef/jabref/issues/11465
Reason: In #11195, we introduced `applicationDefaultJvmArgs`, which are required to be passed to `java` launcher.
The existing script (introduced in 2020, https://github.com/JabRef/jabref/pull/6439), did pass a wrong parameter `-p`. It was not noticed, because the path was not found (one `../` was missing). Now, we need this config "somehow", because of this #11195.
=> Fix launcher

CHANGELOG.md, src/main/java/org/jabref/gui/openoffice/DetectOpenOfficeInstallation.java, src/main/java/org/jabref/gui/openoffice/OpenOfficePanel.java, src/main/java/org/jabref/logic/openoffice/OpenOfficeFileSearch.java, src/main/java/org/jabref/logic/openoffice/OpenOfficePreferences.java
JabRef could not detect `soffice.exe` on my machine. I fixed it.
=> Fix detection of soffice.exe

scripts/vms/.gitignore, scripts/vms/README.md, scripts/vms/fedora/Vagrantfile, scripts/vms/ubuntu/Vagrantfile
To have "the same" virtual machines ready to try out things, here is a proposal based on [Vagrant](https://developer.hashicorp.com/vagrant/install?product_intent=vagrant).
- Refs https://github.com/JabRef/jabref/issues/11465 (provides an Ubuntu where `snap` can be executed.)
- Refs https://github.com/JabRef/jabref/issues/11464 (provides a Fedora39 with a Java JDK available)
---
Follow up:
- Install JabRef Firefox plugin automatically - https://askubuntu.com/questions/73474/how-to-install-firefox-addon-from-command-line-in-scripts
---
=> Initial Vagrant config

docs/decisions/0004-use-mariadb-connector.md, src/main/resources/tinylog.properties
Fix link for mysql connector
Follow up from #10250
=> Fix tinylog

CHANGELOG.md, src/main/java/org/jabref/gui/preferences/websearch/WebSearchTab.java
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/467
=> Fix preferences selection error

CHANGELOG.md, src/main/java/org/jabref/logic/layout/LayoutHelper.java, src/test/java/org/jabref/logic/layout/LayoutTest.java
Adds support in the layout parser for special characters `+:` used in biblatex data annotations.
Fixes #11505
=> Add minimal support for biblatex data annotations

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/EntryEditor.java
Follow-up to #11379.
An exception was thrown after changing "show preview as a tab" in the preferences.
<details>
<summary>Exception</summary>
```
ERROR: Uncaught exception occurred in Thread[#54,JavaFX Application Thread,5,main]: java.lang.NullPointerException: Cannot invoke "org.jabref.model.entry.BibEntry.getType()" because "entry" is null
at org.jabref@100.0.0/org.jabref.gui.entryeditor.RequiredFieldsTab.determineFieldsToShow(RequiredFieldsTab.java:59)
at org.jabref@100.0.0/org.jabref.gui.entryeditor.FieldsEditorTab.shouldShow(FieldsEditorTab.java:213)
at org.jabref@100.0.0/org.jabref.gui.entryeditor.RequiredFieldsTab.shouldShow(RequiredFieldsTab.java:31)
at org.jabref@100.0.0/org.jabref.gui.entryeditor.EntryEditor.lambda$adaptVisibleTabs$5(EntryEditor.java:352)
at …
```
=> Fix NPE when saving preferences

build.gradle
JitPack has issues. https://status.jitpack.io/
```
A problem occurred configuring root project 'JabRef'.
> Could not resolve all artifacts for configuration ':classpath'.
> Could not resolve com.github.koppor.gradle-modules-plugin:gradle-modules-plugin:jitpack-SNAPSHOT.
Required by:
project : > com.github.koppor:gradle-modules-plugin:jitpack-SNAPSHOT:d68df40569-1
> Could not resolve com.github.koppor.gradle-modules-plugin:gradle-modules-plugin:jitpack-SNAPSHOT.
> Could not get resource 'https://jitpack.io/com/github/koppor/gradle-modules-plugin/gradle-modules-plugin/jitpack-SNAPSHOT/gradle-modules-plugin-jitpack-d68df40569-1.pom'.
> Could not HEAD 'https://jitpack.io/com/github/koppor/gradle-modules-plugin/gradle-modules-plugin/jitpack-SNAPSHOT/gradle-modules-plugin-jitpack-d68df40569-1.po …
```
=> Try to use koppor/gradle-modules-plugin "release" (made in fork)

CHANGELOG.md, src/main/java/org/jabref/gui/LibraryTab.java
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/468
=> Always show star for local unsaved library

src/main/java/org/jabref/logic/citationstyle/CitationStyle.java
Addresses https://github.com/JabRef/jabref/pull/11521#issuecomment-2251824512
If, in a development setup, `csl-styles` submodules are missing, `NullPointerException` is thrown when trying to access the default (ieee) style.
- The try-catch block in context:
https://github.com/JabRef/jabref/blob/771c4cd58957c7a56586bea5efc02df2384727d9/src/main/java/org/jabref/logic/citationstyle/CitationStyle.java#L120-L128
is using try-with-resources, which automatically closes the `InputStream`. However, if `getResourceAsStream` returns null, no exception is thrown at this point. The null `InputStream` is passed to `createCitationStyleFromSource`. This has been modified to add a null check.
- A null pointer exception has also been additionally caught and handled at the callee function …
=> Patch: NullPointerException when accessing (absent) default CSL style file

src/test/java/org/jabref/logic/l10n/LocalizationParser.java
Triggered by https://github.com/JabRef/jabref/pull/11539, where `%` were removed.
=> Add comments to FXML localization parsing

docs/code-howtos/localization.md
Triggered by https://github.com/JabRef/jabref/pull/11539, where % were removed.
Follow up to https://github.com/JabRef/jabref/pull/11558.
=> Add more explanation for localization in Java code and FXML

.github/workflows/tests.yml, docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-13-code-style.md
Newcomers sometimes do not know, where to click in GitHub's UI. This PR should add some helpful text for them.
This is a follow-up to https://github.com/JabRef/jabref/pull/10649. The "only" fix required was to use `pull_request_target` as trigger - and not just `pull_request`.
=> Have GitHub commenting on pull requests in case of failed linting checks

CHANGELOG.md
Small markdown fix in CHANGELOG.md
=> Fix Markdown

src/main/java/org/jabref/gui/JabRefGUI.java
I think, the instance of ClipboardManager is only required at `org.jabref.gui.maintable.MainTable#copy`. All other use the `static` helper methods such as `org.jabref.gui.ClipBoardManager#getContents`.
Maybe, we should either rewrite all methods not to be `static` any more - or convert `setContent` to a `static` method, too.
=> Fix setting of ClipboardManager at injector

src/main/resources/tinylog.properties
Refs https://github.com/JabRef/jabref/pull/11441
These logs are no longer needed, so disabling them:
=> Disable GUI debug log

src/main/java/org/jabref/logic/importer/fileformat/CitaviXmlImporter.java, src/test/java/org/jabref/logic/importer/fileformat/ImporterTestEngine.java
While "reviewing" https://github.com/JabRef/jabref/pull/11552, I made some fixes to the CitaviCode.
We had luck, that this ever worked. The input file was deleted before it is processed 🤣
I also use a library for the BOM removal instead of some hand-crafted stuff.
=> Citavi: Fix closing of input file

src/main/java/module-info.java
Gradle `dependencies` shows following for the `runtimeClassPath`:
```
+--- com.github.tomtung:latex2unicode_2.13:0.3.2
|    \--- org.scala-lang:scala-library:2.13.8
```
I wonder, why it worked before, but I added it now.
From the "other" group, I moved up the JavaFX library and http client library.
I also added some ["region:" / "endregion" grouping](https://stackoverflow.com/a/12623285/873282).
=> Add "requires scala.library"

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefDialogService.java, src/main/java/org/jabref/gui/StateManager.java, src/main/java/org/jabref/gui/frame/MainToolBar.java, src/main/java/org/jabref/gui/util/UiTaskExecutor.java
JabRef collected all run tasks. This was confusing. This PR fixes this.
=> No more shown finished background tasks

CHANGELOG.md, src/main/java/org/jabref/cli/ArgumentProcessor.java, src/main/java/org/jabref/cli/JabRefCLI.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java, src/main/resources/l10n/JabRef_en.properties
The CLI options were strange. I never had a clue, what was wrong. But the IntelliJ spell checker guided me.
Should be a bit better understandable now
=> fix-casing-in-cli-options

src/main/java/org/jabref/gui/Base.css, src/main/java/org/jabref/gui/maintable/MainTable.css, src/test/resources/testbib/simple-search-library.bib
Follow-up to: #11510. Closes https://github.com/LoayGhreeb/jabref/issues/8.
Before:
After:
=> Update main table colors

src/main/java/org/jabref/gui/Base.css, src/main/java/org/jabref/gui/Dark.css, src/main/java/org/jabref/gui/maintable/MainTable.css
Follow-up to https://github.com/JabRef/jabref/pull/11579
Dark mode was not working. I tried to use very dark colors now:
More changes:
- When hovering on a focused line, the text color changes (to indicate the hover activity - otherwise, there is no hovering feedback)
- Cleanup Base.css and MainTable.css
- introduce -jr-hover-text
=> Fix dark mode for table

scripts/vms/README.md, scripts/vms/fedora/README.md, scripts/vms/ubuntu/README.md, scripts/vms/windows/README.md, scripts/vms/windows/Vagrantfile
This adds a new Vagrant VM to get a clean Windows environment with git, a JDK, Firefox and LibreOffice installed. Then one can test JabRef's functionalities more easily.
Also reworked the `README.md` file(s).
=> Add Windows Vagrant file

scripts/vms/README.md, scripts/vms/linux-mint-cinnamon/README.md, scripts/vms/linux-mint-cinnamon/Vagrantfile, scripts/vms/ubuntu/Vagrantfile
Wish by @Siedlerchr 
This adds a Linux Mint VM.
This is Linux Mint 21.
Linux Mint 22 was released recently. There currently is no downloadable Vagrant image available. Only some [packer scripts](https://github.com/rmoesbergen/packer-linuxmint). I decided not to maintain a Vagrant image, but to wait that someone publishes a Linux Mint 22 image.
=> Add Vagrant Linux Mint Cinnamon VM

scripts/vms/README.md, scripts/vms/windows/Vagrantfile
Adds C++ redistributable required by AI feature
Removes firefox and libreoffice to reduce installation time.
=> Vagrant Windows image: Add C++ redistributable

CHANGELOG.md, src/main/java/org/jabref/gui/preferences/general/GeneralTabViewModel.java
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/496
=> Open theme browse in last css dir

src/main/java/org/jabref/gui/entryeditor/LatexCitationsTab.java, src/main/java/org/jabref/gui/preferences/entryeditor/EntryEditorTab.fxml, src/main/java/org/jabref/gui/util/FileNodeViewModel.java, src/main/resources/l10n/JabRef_en.properties
Before:
After:
Moreover:
- replace "file" and "files" by file(s)
- fix casing at tab "LaTeX citations"
- "Show '...' tab" --> "Show tab '...'"
=> Fix localization

CHANGELOG.md, src/main/java/org/jabref/logic/citationstyle/CitationStyle.java
[**Subsidiary PR for the GSoC '24 CSL4LibreOffice Project**]
Upgrade parser of CSL style titles from DOM to StAX
=> Upgrade to StAX parsing for CSL style titles

src/test/java/org/jabref/model/entry/identifier/DOITest.java
**Follow-up to:** https://github.com/JabRef/jabref/pull/11084
Integrates test for the DOI URL parsing (for the case of special characters) into existing parameterized test.
Refs https://github.com/JabRef/jabref/pull/11084#discussion_r1536927292
=> Integrate DOI parsing special character test in existing parameterized test

.github/workflows/tests.yml
partially revert
https://github.com/JabRef/jabref/pull/11556
=> Remove comment on PR again

src/main/java/org/jabref/gui/search/GlobalSearchBar.java
Follow-up to #11510.
Invalid regex search query throws an exception: https://github.com/JabRef/jabref-issue-melting-pot/issues/414#issuecomment-2272756300.
```
java.lang.RuntimeException: Label.text : A bound value cannot be set.
at javafx.base@22.0.2/javafx.beans.property.StringPropertyBase.set(Unknown Source)
at javafx.base@22.0.2/javafx.beans.property.StringPropertyBase.set(Unknown Source)
at javafx.base@22.0.2/javafx.beans.property.StringProperty.setValue(Unknown Source)
```
=> Fix invalid regex query throws an exception

CHANGELOG.md, src/main/java/org/jabref/gui/Base.css
Attempts to fix https://github.com/InAnYan/jabref/issues/153.
In this PR I changed the color of prompt text in `TextField`s to be lighter.
Previously, basic text and prompt text had similar colors, so it may appear like user has already entered some text. Especially it was a problem in entering chat model for Hugging Face.
Was:
Became:
This change may affect other JabRef style, so I made a separate PR. We can discuss the change there.
If it's not a good change, then I'll revert it and will only change the style of chat model prompt text (will not touch other JabRef style).
=> Change text prompt color

src/main/java/org/jabref/gui/ai/components/aichat/AiChatComponent.java, src/main/java/org/jabref/logic/ai/chathistory/AiChatHistory.java, src/main/java/org/jabref/logic/ai/chathistory/BibDatabaseChatHistoryManager.java, src/main/java/org/jabref/logic/ai/chathistory/InMemoryAiChatHistory.java
When deletion of chat messages was introduced, the handling of chat history is wrong.
1) We wrongly create keys for MVStore.
2) We wrongly access messages from MVStore (it was IntRange, but it shouldn't be, because there could be gaps from deleted messages).
3) Deletion of messages was not by index, but by contents (this is just wrong, for example if you had exact same error message, when you delete it, everything became messed up).
c- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)~
=> Fix handling of chat history and deletion of messages

docs/code-howtos/custom-svg-icons.md
As a result of #11577, the default icons pack at https://devdocs.jabref.org/code-howtos/custom-svg-icons.html needs to be updated.
=> Update JabRef material icon pack

docs/code-howtos/faq.md
Currently, the FAQ uses bullet points for structuring
The larger the FAQ grows, the more usable will be headings. I restructured the FAQ to have a heading for each question. Since each text after the heading will be a fix, I also removed the `Fix`  word.
---
I also added a hint for ANTLR issues
=> Use headings in FAQ

src/main/java/org/jabref/gui/preferences/PreferencesDialogViewModel.java
There was a "load" of the preferences into all viewModels executed - if a preference was changed.
(It was refactored at #10659, but was there even earlier)
I think, this is not necessary.
=> setValues is not necessary at storing of preferences

src/main/java/org/jabref/logic/importer/fetcher/GrobidCitationFetcher.java, src/test/java/org/jabref/logic/importer/fetcher/BvbFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/GrobidCitationFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/GvkFetcherTest.java, src/test/java/org/jabref/logic/importer/fetcher/OpenAccessDoiTest.java, src/test/java/org/jabref/logic/importer/fetcher/SpringerFetcherTest.java
I went through the fetcher test results at https://github.com/JabRef/jabref/pull/11643 - they all should come from other strings returned. This PR fixes it.
=> Fix FetcherTests

docs/code-howtos/code-quality.md
Some devdocs info addition.
Source: https://app.moderne.io/organizations/JabRef/jabref?branch=main&origin=github.com
=> Add link to the moderne platform

CHANGELOG.md, src/main/java/org/jabref/gui/Base.css, src/main/java/org/jabref/gui/search/GlobalSearchBar.java
Closes https://github.com/LoayGhreeb/jabref/issues/11.
=> Highlight search bar on wrong syntax

README.md
A contributor changed the JDK minimum requirement. This is not necessary, therefore, I updated the text.
Refs https://github.com/JabRef/jabref-issue-melting-pot/issues/416
=> Rework TL;DR contibuting

src/main/java/org/jabref/gui/preferences/ai/AiTabViewModel.java
Closes https://github.com/JabRef/jabref-issue-melting-pot/issues/511.
When you accept privacy policy for AI, AI features are enabled, but API key is empty.
If in this state you go to preferences, change some other preferences that you need (for example switching language), then preferences window won't allow this to do, because there is an empty API key.
What this PR does: even if API key is empty, we allow to save it empty. All logic will work okay after that, because empty API key is handled [there](https://github.com/JabRef/jabref/blob/8a0edc251fa3158bd478810105cfeeda4854e6f7/src/main/java/org/jabref/gui/entryeditor/AiChatTab.java#L100), and as a last resort [there](https://github.com/JabRef/jabref/blob/8a0edc251fa3158bd478810105cfeeda4854e6f7/src/main/java/org/jabref/logic/ai/models/Ja …
=> Fix saving preferences while AI API key is empty

scripts/vms/README.md, scripts/vms/debian-12/README.md, scripts/vms/debian-12/Vagrantfile, scripts/vms/fedora/Vagrantfile, scripts/vms/linux-mint-cinnamon/README.md, scripts/vms/linux-mint-cinnamon/Vagrantfile, scripts/vms/ubuntu/Vagrantfile, scripts/vms/windows/Vagrantfile
Refs https://github.com/JabRef/jabref/issues/10731#issuecomment-2302010761
=> Add Debian VM (and improve other Vagrant files)

src/main/java/org/jabref/logic/ai/GenerateEmbeddingsTask.java, src/main/java/org/jabref/logic/ai/models/UpdateEmbeddingModelTask.java, src/main/java/org/jabref/logic/ai/summarization/GenerateSummaryTask.java, src/main/java/org/jabref/logic/util/ProgressCounter.java
Changes made:
1. The algorithm calculates ETA in a different way: previously it somehow recorded time of one work (actually, it was a strange algorithm). Now it very simple: just measure how long the task was working, then using some simple math (`ONE_WORK_TIME = WORKING_TIME / WORK_DONE`) calculate final `ETA = ONE_WORK_TIME * (WORK_MAX - WORK_DONE)` (some of the variables might be zero, so I also added checks for that).
2. `ProgressCounter` will also periodically updated itself, in case one work takes too much time (previously, update happened only when amount of work is changes).
~- [ ] Screenshots added in PR description (for …
=> Refine ProgressCounter

src/main/java/org/jabref/gui/preferences/ai/AiTab.fxml, src/main/java/org/jabref/gui/preferences/ai/AiTab.java, src/main/java/org/jabref/logic/help/HelpFile.java
Changes made:
- Put "Enable AI functionality" help button in right place.
- Add "Temperature" help.
- Reorganize expert settings in a table (some of the parameters).
- Also changed instruction `TextArea` to `ResizableTextArea` (we already use package that provides a lot of JavaFX components, so why not to use a better one).
Before:
After:
=> Improve AI preferences UI and add temperature help

CHANGELOG.md, src/main/java/org/jabref/gui/openoffice/OOBibBase.java, src/main/java/org/jabref/gui/openoffice/OpenOfficePanel.java
Closes https://github.com/JabRef/jabref/issues/11684
Cause of issue: See removed comment in (old) line 71 of `OOBibBase.java` in changed files. `boolean refreshBibliographyDuringSyncWhenCiting` was always set to false, which rendered the feature non-functional.
- This is now set properly at the time of citing with JStyles, and the overwrite to `false` has been removed.
- Some miscellaneous refactoring
=> Fix: Auto-sync bibliography for JStyle

src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java, src/main/java/org/jabref/logic/openoffice/oocsltext/CSLFormatUtils.java
Nitpick: Refactored hardcoded magic string into a format utility constant for uniformity.
=> Minor refactor (Bibliography body paragraph format)

CHANGELOG.md, src/main/java/org/jabref/gui/exporter/CreateModifyExporterDialog.fxml, src/main/java/org/jabref/gui/exporter/CreateModifyExporterDialogViewModel.java
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/519
Also some visual adjustments
before
after
=> Custom export format: Browse opens selected template folder

src/main/java/org/jabref/logic/openoffice/ReferenceMark.java
Follow-up to: https://github.com/JabRef/jabref/pull/11712
- Use more strict regex to exactly match the format, disallow multiple whitespaces, disallow absence of unique ID, etc.
- A lot of code I wrote for https://github.com/JabRef/jabref/pull/11712 may seem like black-magic, as the fix was needed as soon as possible. I will slowly be documenting the code to aid this. Some JavaDoc is added in this PR as well.
=> Refine parsing format of CSL reference marks

src/main/java/module-info.java, src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/model/search/Analyzer/LatexAwareNGramAnalyzer.java, src/main/java/org/jabref/model/search/SearchFieldConstants.java
Follow-up to: #11542
Update the Lucene version. If any changes to the index require reindexing (e.g., new/removed/renamed fields, analyzer changes), this version number should be updated.
Changing the version will change the index path:
https://github.com/JabRef/jabref/blob/6af91b963dce2a4c9d0320ed8d0e1423b80f8a54/src/main/java/org/jabref/gui/desktop/os/NativeDesktop.java#L100-L105
The old index will be removed https://github.com/JabRef/jabref/blob/8a0edc251fa3158bd478810105cfeeda4854e6f7/src/main/java/org/jabref/Launcher.java#L208-L229
=> Update lucene version

src/main/java/org/jabref/logic/openoffice/oocsltext/CSLReferenceMarkManager.java
Fixes the following edge-case bugs:
1. Inserting a new reference just before the reference numbered "1" without any space or line break or text in between (coalescing case 1)
https://github.com/user-attachments/assets/9996ea14-404e-45ed-a33d-b01b6627ec69
2. Inserting a new reference before the reference numbered "1" with a paragraph break [shift+enter] (not a line break [enter]) (coalescing case 2)
https://github.com/user-attachments/assets/a9bb72ef-a237-411e-9ea1-16bd7799a8bd
Both cases used to throw an exception and did not update the old "1" after the new reference to "2".
=> CSL - Fix bug when inserting reference coalescing  before first entry

build.gradle, src/main/java/module-info.java, src/main/java/org/jabref/logic/importer/fetcher/ACS.java, src/test/java/org/jabref/logic/importer/fetcher/ACSTest.java
Did not suceed with JCEF (see https://github.com/koppor/jabref/pull/695), but these are small code quality improvements.
=> Refine ACS test code

src/test/java/org/jabref/logic/importer/fileformat/BibtexParserTest.java
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/446
=> Add parser test

src/main/java/org/jabref/Launcher.java, src/main/java/org/jabref/gui/JabRefGUI.java, src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/gui/entryeditor/EntryEditor.java, src/main/java/org/jabref/gui/preferences/ai/AiTab.java, src/main/java/org/jabref/gui/preferences/ai/AiTabViewModel.java, src/main/java/org/jabref/logic/ai/AiService.java, src/main/java/org/jabref/logic/ai/chatting/model/JabRefChatLanguageModel.java, src/main/java/org/jabref/logic/ai/chatting/model/JvmOpenAiChatLanguageModel.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/main/java/org/jabref/preferences/PreferencesService.java, src/main/java/org/jabref/preferences/ai/AiApiKeyProvider.java, src/main/java/org/jabref/preferences/ai/AiPreferences.java
Removed unnecessary `AiService` (it turns out there is no that much code, I used InelliJ analysis tools). Also removed `AiApiKeyProvider`, the code for API keys is now in the `AiPreferences`.
=> Remove unnecessary AI dependencies

src/main/java/org/jabref/cli/ArgumentProcessor.java, src/main/java/org/jabref/gui/externalfiles/AutoLinkFilesAction.java, src/main/java/org/jabref/gui/externalfiles/AutoSetFileLinksUtil.java, src/main/java/org/jabref/gui/frame/JabRefFrameViewModel.java, src/main/java/org/jabref/gui/maintable/BibEntryTableViewModel.java, src/main/java/org/jabref/logic/UiCommand.java, src/main/java/org/jabref/logic/search/DatabaseSearcher.java
Fixes an architectural flaw
Refs https://github.com/JabRef/jabref/issues/110
=> Fix ArgumentProcessor

CHANGELOG.md, src/main/java/org/jabref/gui/linkedfile/DownloadLinkedFileAction.java, src/main/java/org/jabref/gui/preferences/websearch/WebSearchTab.fxml, src/main/java/org/jabref/gui/preferences/websearch/WebSearchTab.java, src/main/java/org/jabref/gui/preferences/websearch/WebSearchTabViewModel.java, src/main/java/org/jabref/preferences/FilePreferences.java, src/main/java/org/jabref/preferences/JabRefPreferences.java, src/main/resources/l10n/JabRef_en.properties, src/test/java/org/jabref/gui/linkedfile/DownloadLinkedFileActionTest.java
Refs https://discourse.jabref.org/t/import-adds-pdf-link-and-url-to-file-entry/4484/2
Follow up from https://github.com/JabRef/jabref/issues/10848
=> Add pref switch to not store url

src/main/java/org/jabref/logic/bst/util/BstTextPrefixer.java, src/test/java/org/jabref/logic/bst/util/BstTextPrefixerTest.java
1. add more unit test about nested brace cases
2. refactor the `textPrefix` method to make it clear
- I used a private class with public variable fields to handle multiple return value. If we prefer only use class with private fields I can refactor it later.
=> refactor BstTextPrefixer.textPrefix

src/main/java/org/jabref/logic/cleanup/FieldFormatterCleanups.java, src/main/java/org/jabref/logic/exporter/MetaDataSerializer.java, src/main/java/org/jabref/logic/importer/util/MetaDataParser.java
1. move `parse` into `MetaDataParser`
2. move `getAsStringList` into `MetaDataSerializer`
3. some minor fix
=> finish ToDo in FieldFormatterCleanups

src/main/java/org/jabref/logic/citationkeypattern/BracketedPattern.java, src/test/java/org/jabref/logic/citationkeypattern/BracketedPatternTest.java
- prepare to refactor this method
=> add unit test to generateInstitutionKey

CHANGELOG.md, src/main/java/org/jabref/gui/undo/CountingUndoManager.java, src/main/java/org/jabref/gui/undo/RedoAction.java, src/main/java/org/jabref/gui/undo/UndoAction.java
Closes #8807
- **Redo button is disabled**
- **Undo button is disabled**
=> Enable/Disable the undo and redo toolbar/menu buttons correctly

build.gradle, src/main/java/module-info.java
Reported by @Siedlerchr 
```
e java.lang.Exception: java.util.ServiceConfigurationError: ai.djl.repository.zoo.ZooProvider: module org.jabref.merged.module does not declare `uses`
at org.jabref@5.16.30482/org.jabref.gui.util.uitaskexecutor.converttoexception(uitaskexecutor.java:215)
...
Caused by: java.util.ServiceConfigurationError: ai.djl.repository.zoo.ZooProvider: module org.jabref.merged.module does not declare `uses`
at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
```
=> Add uses directive

src/main/java/org/jabref/gui/externalfiles/ImportHandler.java
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/535 
Follow up issue from https://github.com/JabRef/jabref/pull/11758
=> Fix undo not on fx thread exception

scripts/vms/README.md, scripts/vms/windows10/README.md, scripts/vms/windows10/Vagrantfile, scripts/vms/windows11/README.md, scripts/vms/windows11/Vagrantfile
Add new Vagrant config for Windows 11 VMs. (Maybe helps to reproduce https://github.com/JabRef/jabref/issues/11755).
=> Add Windows 11 VM

src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java, src/main/java/org/jabref/gui/importer/actions/SearchGroupsMigrationAction.java, src/main/resources/l10n/JabRef_en.properties
If the automatic migration fails, display a dialog allowing users to manually migrate the group or keep the existing query.
Closes #11752
=> Add manual migration for search syntax when automatic migration fails

docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/trouble-shooting.md
Follow up to #11766. Previous PR: https://github.com/JabRef/jabref/pull/11778.
=> Add more OS-dependent context to panel freeze dev documentation.

src/main/java/org/jabref/gui/JabRefDialogService.java
1. replace multiple if-else to switch case
2. remove unused generics `<V>`
3. replace `.collect(Collectors.toList())` to `.toList()`
4. remove unnecessary braces
- I'm no sure do we really need this kind of small refactor, please review and let me know if this change aligns with our goals.
=> minor refactor to JabRefDialogService

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fileformat/PdfContentImporter.java, src/test/java/org/jabref/logic/importer/fileformat/PdfContentImporterTest.java
I noticed that the extracted DOI was in the wrong format when I used PDF importer for one of the papers in the chocolate bib 
doi.org/10.1017/S0007114507795296
=> Improve pdf content parser for DOIs

src/main/java/org/jabref/gui/ai/components/aichat/AiChatComponent.java
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/549
=> Fix ai chat not on fx thread

CHANGELOG.md, src/main/java/org/jabref/gui/Base.css, src/main/java/org/jabref/gui/fieldeditors/KeywordsEditor.java, src/main/java/org/jabref/gui/fieldeditors/LinkedEntriesEditor.java, src/main/java/org/jabref/gui/preferences/autocompletion/AutoCompletionTab.java
Closes #11177
- Clicking anywhere in the tags field will now correctly request focus.
- The border color of the field changes when it is focused.
=> Fix tags field focus

src/main/java/org/jabref/gui/JabRefGUI.java, src/main/java/org/jabref/logic/ai/AiService.java, src/main/java/org/jabref/logic/ai/ingestion/GenerateEmbeddingsForSeveralTask.java
Closes https://github.com/JabRef/jabref-issue-melting-pot/issues/544.
Group chat history wasn't saved. Fixed.
And there was also a problem with embeddings generation for group. One statement should be in JavaFX thread. Fixed.
=> Fix group chat history and group embeddings generation

src/test/java/org/jabref/logic/l10n/LocalizationConsistencyTest.java
Fixes https://github.com/JabRef/jabref/issues/11784
Closes https://github.com/JabRef/jabref/pull/11793
=> Refine TODO

CHANGELOG.md, src/main/java/org/jabref/gui/JabRefDialogService.java, src/main/java/org/jabref/gui/StateManager.java, src/main/java/org/jabref/gui/frame/MainToolBar.java, src/main/java/org/jabref/gui/util/UiTaskExecutor.java
This implements the quick fix for https://github.com/JabRef/jabref/issues/11701.
=> Revert 2c8fc01

CHANGELOG.md, src/main/java/org/jabref/gui/frame/FileHistoryMenu.java
Fixes #9042
"Recent files" menu was not updated in runtime. Now it should be.
=> Fix "Recent files" menu behaviour

src/main/java/org/jabref/gui/util/UiTaskExecutor.java, src/main/java/org/jabref/logic/search/LuceneManager.java, src/main/java/org/jabref/logic/search/indexing/BibFieldsIndexer.java, src/main/java/org/jabref/logic/search/indexing/DefaultLinkedFilesIndexer.java, src/main/java/org/jabref/logic/util/BackgroundTask.java
Closes #11701.
The issue will be resolved if the PR for hiding completed background tasks (#11821) is merged. 
However, this PR fixes the issue even if hiding completed tasks isn't implemented. Progress was shown with an empty title and no progress because sometimes background indexing tasks start but have no files to add to the index. 
There was no control to show the task to the user after it started executing. This PR added this option. 
Calling `task.showToUser(true)` after `executeWith` will show the task if it's still running.
=> Fix indexing task progress

src/main/java/org/jabref/gui/entryeditor/SourceTab.java, src/main/java/org/jabref/logic/importer/fileformat/MrDLibImporter.java, src/main/java/org/jabref/logic/openoffice/action/EditMerge.java, src/main/java/org/jabref/model/openoffice/rangesort/RangeSortVisual.java
- refs:#11829
- finish:Inner classes like `ComparableMark` can be converted to record classes.
- most of them can't change it since there are a method in it or changed the record value, which against the purpose of record.
=> convert Inner classes to record classes

CHANGELOG.md, src/main/java/org/jabref/gui/externalfiles/ImportHandler.java, src/main/java/org/jabref/logic/database/DuplicateCheck.java
Run duplicate check on background thread
In 90% cases better performance, except if you have plenty of duplicates (UI dialog is shown then)
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/574
Side effect, UI might freeze if you copy a large number of entries because of respawning the duplicate entry dialog. Not happy about it,
=> Improve performance with duplicate check on paste

rewrite.yml, src/main/java/org/jabref/gui/entryeditor/DeprecatedFieldsTab.java, src/main/java/org/jabref/gui/entryeditor/citationrelationtab/semanticscholar/SemanticScholarFetcher.java, src/main/java/org/jabref/logic/auxparser/DefaultAuxParser.java, src/main/java/org/jabref/logic/bibtex/comparator/BibDatabaseDiff.java, src/main/java/org/jabref/logic/cleanup/ConvertToBiblatexCleanup.java, src/main/java/org/jabref/logic/cleanup/ConvertToBibtexCleanup.java, src/main/java/org/jabref/logic/cleanup/FileLinksCleanup.java, src/main/java/org/jabref/logic/cleanup/ISSNCleanup.java, src/main/java/org/jabref/logic/importer/fetcher/ACS.java, src/main/java/org/jabref/logic/importer/fetcher/ApsFetcher.java, src/main/java/org/jabref/logic/importer/fetcher/MrDLibFetcher.java, src/main/java/org/jabref/logic/importer/fetcher/OpenAccessDoi.java, src/main/java/org/jabref/logic/integrity/DateChecker.java, src/main/java/org/jabref/logic/integrity/FileChecker.java, src/main/java/org/jabref/logic/msbib/MSBibConverter.java, src/main/java/org/jabref/logic/shared/DBMSSynchronizer.java, src/main/java/org/jabref/migrations/ConvertLegacyExplicitGroups.java, src/main/java/org/jabref/migrations/ConvertMarkingToGroups.java, src/main/java/org/jabref/model/util/OptionalUtil.java
Adds 
- https://docs.openrewrite.org/recipes/java/migrate/util/optionalnotemptytoispresent
- https://docs.openrewrite.org/recipes/java/migrate/util/optionalnotpresenttoisempty
And updates a (non-related) JavaDoc
=> Code refinements

CHANGELOG.md, src/main/java/org/jabref/gui/linkedfile/DownloadLinkedFileAction.java, src/main/java/org/jabref/gui/preferences/websearch/WebSearchTabViewModel.java, src/main/java/org/jabref/logic/importer/FetcherException.java, src/main/java/org/jabref/logic/importer/fetcher/BvbFetcher.java, src/main/java/org/jabref/logic/importer/fetcher/IEEE.java, src/main/java/org/jabref/logic/importer/fetcher/ResearchGate.java, src/main/java/org/jabref/logic/importer/fileformat/MarcXmlParser.java, src/main/java/org/jabref/logic/net/URLDownload.java, src/main/java/org/jabref/logic/net/ssl/TrustStoreManager.java, src/test/java/org/jabref/logic/importer/fetcher/BvbFetcherTest.java
This updates the user agent to the latest one by FireFox (source: https://www.whatismybrowser.com/guides/the-latest-user-agent/firefox)
This also logs the URL used for an error HTTP response.
Example:
```
INFO: https://www.researchgate.net/search.Search.html?type=publication&query=Paranoid%3A%20a%20global%20secure%20file%20access%20control%20system: SimpleHttpResponse{statusCode=403, response
```
=> Update user agent and log URL

CHANGELOG.md, src/main/java/org/jabref/gui/search/GlobalSearchBar.java, src/main/resources/l10n/JabRef_en.properties
fixes https://github.com/JabRef/jabref/issues/9491#issuecomment-1369188282
=> Ask for enable indexing when clicking fulltext search

CHANGELOG.md, src/main/java/org/jabref/gui/importer/fetcher/LookupIdentifierAction.java
=> Fix not on FX thread exception for DOI(arxiv lookup

CHANGELOG.md, src/main/java/org/jabref/gui/preferences/websearch/WebSearchTab.fxml, src/main/java/org/jabref/logic/importer/WebFetchers.java, src/main/java/org/jabref/logic/importer/fetcher/CompositeSearchBasedFetcher.java, src/main/resources/l10n/JabRef_en.properties
Closes #11866 
Instances of 'Search Selected' has been changed to 'Search Pre-configured' in the following files:
- CompositeSearchBasedFetcher.java in line 21
- JabRef_en.properties in line 128
- WebFetchers.java in line 241
- WebSearchTab.fxml in line 30
=> Change instances of 'Search Selected' to 'Search Pre-configured'

docs/code-howtos/faq.md, docs/code-howtos/fetchers.md, docs/code-howtos/testing.md
Information pertaining to (automatic) fetcher tests are added to fetchers.md. Information pertaining to how fetcher tests could be done locally are also added to testing.md.
=> Add fetcher test info to developer documentation

CHANGELOG.md
Refs. https://github.com/JabRef/jabref/pull/11839
Removes one of the changelog entries that correspond to https://github.com/JabRef/jabref/issues/11809, as it was caused in an unreleased version.
=> Remove changelog entry

CHANGELOG.md, src/main/java/org/jabref/gui/frame/MainMenu.java, src/main/java/org/jabref/gui/frame/MainToolBar.java
This PR improves the user interface by disabling certain menu items and toolbar buttons when no library is open.
"Save All" menu item in MainMenu.java is now disabled (greyed out) when there are no open libraries.
"New entry from plain text" menu item in MainMenu.java is now disabled when there are no open libraries.
"Global Search" bar in the main toolbar (MainToolBar.java) is now disabled when there are no open libraries.
"New entry from plain text" button in the main toolbar (MainToolBar.java) is now disabled when there are no open libraries.
https://github.com/user-attachments/assets/9fb688e5-5dbb-4e20-9f16-b0bf33f691d3
Closes #11923
https://github.com/JabRef/jabref/issues/11923
=> Fix disable some actions when no libraries are open

src/main/java/org/jabref/gui/exporter/SaveAllAction.java, src/main/java/org/jabref/gui/frame/MainMenu.java, src/main/java/org/jabref/gui/frame/MainToolBar.java, src/main/java/org/jabref/gui/plaincitationparser/PlainCitationParserAction.java, src/main/java/org/jabref/gui/search/GlobalSearchBar.java
Revert #11936, and bind the action directly to the executable, rather than disabling the menu item.
=> Disable actions when no libraries are open

.vscode/extensions.json
LTeX is not maintained anymore. [LTeX+](https://github.com/ltex-plus/vscode-ltex-plus) is the maintained fork.
=> Replace LTeX by LTeX+

docs/code-howtos/bibtex.md
While commenting on https://github.com/JabRef/jabref/issues/11136#issuecomment-2408466396, I thought, it would be a good idea to have some text.
=> Add small text on BibTeX handling

src/main/java/org/jabref/model/database/BibDatabase.java, src/main/java/org/jabref/model/entry/BibEntry.java
`maybenull` is non-standard Java, isn't it?
=> Replace "maybenull" by annotation

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/citationrelationtab/CitationRelationsTab.java
closes https://github.com/JabRef/jabref-issue-melting-pot/issues/609
=> Added double click to jump to entry in CitationRelationsTab

.github/workflows/react-on-issue-labels.yml
After we assign a `FirstTimeContribution` label, change the state in the project.
This relates to https://github.com/JabRef/jabref/pull/11945.
=> Add change of state on assignment

.github/workflows/assign-issue.yml, .github/workflows/react-on-issue-labels.yml, CONTRIBUTING.md
We constantly get contributors wanting to have an issue assigned. To reduce the load, I propose the [assign-issue-action](https://github.com/takanome-dev/assign-issue-action). Contributors can then issue `/assign-me` and then they get assigned. Nice feature: After 30 days of inactivity, they get unassigned. (We can configure this time frame)
I also included text of our [newcomer text](https://github.com/JabRef/jabref/blob/main/.github/workflows/add-greeting-to-issue.yml).
Drawback: Our project boards are not updated accordingly. Filed as feature-wish to the action -> https://github.com/takanome-dev/assign-issue-action/issues/239
Alternative [`.take`](https://github.com/bdougie/take-action). Seems to have the same capabilities as the chosen action. Found via …
=> Add assign-me-action

docs/code-howtos/fetchers.md, src/main/java/org/jabref/Launcher.java, src/main/java/org/jabref/gui/entryeditor/citationrelationtab/semanticscholar/SemanticScholarFetcher.java, src/main/java/org/jabref/logic/importer/ImporterPreferences.java, src/main/java/org/jabref/logic/importer/fetcher/AstrophysicsDataSystem.java, src/main/java/org/jabref/logic/importer/fetcher/BiodiversityLibrary.java, src/main/java/org/jabref/logic/importer/fetcher/IEEE.java, src/main/java/org/jabref/logic/importer/fetcher/ScienceDirect.java, src/main/java/org/jabref/logic/importer/fetcher/SpringerFetcher.java, src/main/java/org/jabref/logic/importer/fetcher/SpringerLink.java, src/main/java/org/jabref/logic/preferences/JabRefCliPreferences.java, src/main/java/org/jabref/logic/util/BuildInfo.java, src/main/java/org/jabref/logic/util/Directories.java, src/test/java/org/jabref/logic/importer/fetcher/BiodiversityLibraryTest.java, src/test/java/org/jabref/logic/util/BuildInfoTest.java
closes https://github.com/JabRef/jabref-issue-melting-pot/issues/604
also removes some telemetry artifacts
=> Replace new instantiation of BuildInfo with calls to Injector

src/main/java/org/jabref/cli/JabRefCli.java
Current main:
```
> Task :run
WARNING: Using incubator modules: jdk.incubator.vector
Messages are not initialized before accessing key: Display help on command line options
Exception in thread "main" java.lang.UnsupportedOperationException: Configuration cannot be changed after applying to tinylog
at org.tinylog.api@2.7.0/org.tinylog.configuration.Configuration.set(Configuration.java:288)
at java.base/java.util.Map.forEach(Map.java:733)
at org.jabref@100.0.0/org.jabref.cli.JabRefCli.initLogging(JabRefCli.java:164)
at org.jabref@100.0.0/org.jabref.Launcher.main(Launcher.java:26)
```
This is because of the use of injector (introduced in https://github.com/JabRef/jabref/pull/11954 - and merged into https://github.com/JabRef/jabref/pull/11921).
This PR fixes it.
---
Hotfix, therefore I will …
=> Do not use Injector while initializing logging

.github/workflows/on-labeled.yml
When browsing the workflow, GitHub displays only some first characters. Leading to an unreadable output:
This PR fixes it.
=> Improve step names

.github/workflows/on-labeled-issue.yml, .github/workflows/on-labeled-pr.yml, .github/workflows/on-unlabeled-issue.yml
We have support for automerge (see https://github.com/JabRef/jabref/blob/main/.github/workflows/automerge.yml for details). It ensures a) updates come in quickly and b) are checked by the CI.
Sometimes, we need things to go in quickly without a review (e.g., hot fixes). They should go in after a successful CI check.
Idea: Use "automerge" label. If that label is present, the CI will try to merge this PR after a successful check.
This PR also renames the workflows and fixes triggers.
=> Enable "automerge" label handling on a PR.

.github/workflows/on-labeled-issue.yml
Until https://github.com/takanome-dev/assign-issue-action/issues/244 is implemented, we should make the unassignment procedure transparent.
I just copied over the text from the reaction on `/assign-me`.
=> Add information on unassignment

src/main/java/org/jabref/Launcher.java, src/main/java/org/jabref/cli/JabKit.java
On [JabCon2024](https://blog.jabref.org/2024/09/18/JabCon24/), we discussed about naming. Current state:
- `JabKit` for the command-line-only version
- `JabLib` for a library published by [Maven Central](https://central.sonatype.com/)
This PR implements this naming.
=> Rename JabRefCli to JabKit

.github/workflows/assign-issue.yml
Switches to the development version at https://github.com/takanome-dev/assign-issue-action/pull/245
=> Test WIP version of action

.github/workflows/deployment-arm64.yml, .github/workflows/deployment-jdk-ea.yml, .github/workflows/deployment.yml
We sometimes have "no space left on device" during uploading:
We can ignore this error, because it is not cruicial for the build itself.
We need to use `|| true`, because there is no native support to ignore failures - https://github.com/actions/runner/issues/2347
=> Ignore rsync errors on uploading

.github/workflows/assign-issue.yml, .github/workflows/on-labeled-issue.yml, .github/workflows/on-unlabeled-issue.yml
Now, on assignment via the action, the project is also updated. No more action with the "Assigned" label.
Refs https://github.com/takanome-dev/assign-issue-action/issues/247
Can be merged if https://github.com/takanome-dev/assign-issue-action/pull/245 is merged.
I hope that https://github.com/m7kvqbe1/github-action-move-issues/issues/4 will also be implemented soon 😅
=> Update takanome-dev/assign-issue-action to beta

.github/workflows/cleanup-pr.yml, .github/workflows/deployment.yml
Refs https://github.com/thollander/actions-comment-pull-request/issues/397
=> Fix removing comments

.github/PULL_REQUEST_TEMPLATE.md
Studients do not delete the HTML comment markers (e.g., https://github.com/JabRef/jabref/pull/12009), thus, the link does not work. I shortened the howto to a two-liner.
They always link the issue in the title - thus I removed that recommendation; as long as they link in the text, we are fine.
I removed the explanation text for "Closes". They can google background information.
=> Try other template format

.github/workflows/on-review-submitted.yml
We have the labels [status: changes required](https://github.com/JabRef/jabref/labels/status%3A%20changes%20required) and [status: ready-for-review](https://github.com/JabRef/jabref/labels/status%3A%20ready-for-review). They can be automatically assigned/removed
- If PR is reviewed: Add `status: changes required` and Remove `status: ready for review`
=> Add label addition and removal of status: *

.github/workflows/assign-issue.yml
Now that https://github.com/takanome-dev/assign-issue-action/pull/245 is merged, we need to use that version
=> Use the beta version of takanome-dev/assign-issue-action@beta

.github/workflows/automerge.yml, .github/workflows/on-review-submitted.yml
On https://github.com/JabRef/jabref/actions/runs/11416917936/job/31768654513, I got
```
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
env:
GH_TOKEN: ${{ github.token }}
```
Not sure why it works for the auto merge. This PR makes all environment variable names consistent.
=> Fix environement variable name for gh cli

.github/workflows/on-review-submitted.yml
Tries to fix
```
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
env:
GH_TOKEN: ${{ github.token }}
```
and also that step triggered even on approval
=> Try to fix token and condition

CHANGELOG.md, src/main/java/org/jabref/gui/externalfiles/ImportHandler.java, src/main/java/org/jabref/logic/importer/CompositeIdFetcher.java, src/main/java/org/jabref/model/entry/identifier/SSRN.java, src/test/java/org/jabref/model/entry/identifier/SSRNTest.java
Allows importing (e.g. via pasting) of both short and long SSRN URLs via their associated DOI.
This also removes some dead code that was not cleaned up in #12009.
Closes #11687
=> Add SSRN urls to CompositeIdFetcher

src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java, src/main/java/org/jabref/logic/bibtex/InvalidFieldValueException.java, src/main/java/org/jabref/logic/preferences/JabRefCliPreferences.java
Some `@deprecated` annotations were confusing. I replaced them with text.
Refs https://github.com/JabRef/jabref/issues/11674
=> Replace `@deprecated` by explaining text

src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java, src/main/java/org/jabref/logic/bibtex/InvalidFieldValueException.java, src/main/java/org/jabref/logic/preferences/JabRefCliPreferences.java
Follow-up to https://github.com/JabRef/jabref/pull/12055.
Closes https://github.com/JabRef/jabref/issues/11674
=> Readd `@deprecated` annotation

.github/workflows/tests.yml
Fix link to CONTRIBUTING.md 
Follow-up to https://github.com/JabRef/jabref/pull/11945
=> Fix link to contribution guide

.github/workflows/pages.yml, docs/Gemfile, docs/decisions/adr-template.md
Jekyll build fails. This should fix it
Udpates just-the-docs from 0.5.0 to 0.10.0 - see https://github.com/just-the-docs/just-the-docs/blob/main/MIGRATION.md#migrating-and-upgrading for a guide (not thoroughly followed)
=> Disable meta data elements in adr-template

CHANGELOG.md, src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java
Added CitationKey as a default column to the entry table by adding it to the default preferences. This closes #10510.
=> Add CitationKey as a default column (#10510)

.github/PULL_REQUEST_TEMPLATE.md
Some students do not add a CHANGELOG.md entry, even if they should (e.g., https://github.com/JabRef/jabref/pull/12081)
This PR tries to refine the text for the check.
=> Refine PULL_REQUEST_TEMPLATE.md

.github/workflows/assign-issue.yml, .github/workflows/check-links.yml, .github/workflows/cleanup-pr.yml, .github/workflows/deployment-arm64.yml, .github/workflows/deployment-jdk-ea.yml, .github/workflows/gource.yml, .github/workflows/on-labeled-issue.yml, .github/workflows/on-labeled-pr.yml, .github/workflows/on-unlabeled-issue.yml, .github/workflows/pr-comment.yml, .github/workflows/update-gradle-wrapper.yml
Some checks (e.g., external links) and updates (gradle wrapper) should only be done in our main repo.
Needs to be "tested" in "production"
=> Limit some workflows to main repository

src/main/java/org/jabref/gui/externalfiles/ImportHandler.java
New entries were not correctly bound to the entry editor and main table because they were cloned before being added to the database.
Follow-up to #11724.
Closes https://github.com/JabRef/jabref-issue-melting-pot/issues/656
=> Fix inserting new entry

src/test/java/org/jabref/logic/l10n/LocalizationConsistencyTest.java
People tend to blindly add localization keys into `JabRef_en.properties`. 
With the proposed text, they maybe think more?
=> Refine hint on pasting keys.

src/main/java/org/jabref/gui/maintable/MainTable.java, src/main/java/org/jabref/gui/maintable/MainTableDataModel.java, src/main/java/org/jabref/model/database/BibDatabase.java
Instead of the sequential scan to find the entry view model, retrieve the index of the entry from the database. This is faster because it uses a binary search based on the entry id.
Closes https://github.com/JabRef/jabref-issue-melting-pot/issues/660
=> Improve `MainTable#findEntry`

src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/gui/entryeditor/citationrelationtab/CitationRelationsTab.java
In some code patghways, the entry editor was shown, but the main table selection was not updated.
IMHO if the entry editor is shown - there should be a single (!) entry in the main table focused: The entry currently edited.
(This PR contains some code cleanup from https://github.com/JabRef/jabref/pull/12124/ - the important change is the removal of explicit `clearAndSelect` calls and include them into `showAndEdit`)
=> Always select entry in main table when showing entry editor

src/main/java/org/jabref/gui/LibraryTab.java
Implement "early exit" pattern for org.jabref.gui.LibraryTab#doCopyEntry
=> Implement early exit

src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/gui/cleanup/CleanupAction.java, src/main/java/org/jabref/gui/specialfields/SpecialFieldAction.java
The method `updateEntryEditorIfShowing` seems to be a left-over of old times.
It was called very rarely.
Since the argument for `showAndEdit` was the currently entry, the only action the thing did was to focus the entry editor. The callers were "Cleanup" and "SpecialFieldAction". I don't think, they need an entry editor focus.
=> Remove updateEntryEditorIfShowing

.devcontainer/devcontainer.json, .github/workflows/deployment-arm64.yml, .github/workflows/deployment-jdk-ea.yml, .github/workflows/deployment.yml, .github/workflows/tests-fetchers.yml, .github/workflows/tests.yml, .github/workflows/update-gradle-wrapper.yml, .gitpod.Dockerfile, .vscode/ltex.dictionary.en-US.txt, build.gradle, docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-12-build.md
Refs https://github.com/JabRef/jabref-issue-melting-pot/issues/669
=> Preare Update Java JDK from 21 to 22

docs/code-howtos/localization.md, docs/decisions/0040-use-one-form-for-singular-and-plural.md, src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/gui/externalfiles/DownloadFullTextAction.java, src/main/resources/l10n/JabRef_en.properties
Add ADR on pluralization. 
Risen by https://github.com/JabRef/jabref/pull/12124#discussion_r1821600951.
This also replaces "entry(ies)" by "entry(s)", which read better IMHO.
Seeign Ukrainian listed at first example at https://cldr.unicode.org/index/cldr-spec/plural-rules, I ask @InAnYan about his oppinion here.
=> Add ADR for "entry(s)"

CHANGELOG.md
Follow-up to https://github.com/JabRef/jabref/pull/12085.
This adds the CHANGELOG.md entry
=> Add entry to CHANGELOG.md

src/main/java/org/jabref/logic/ai/AiDefaultPreferences.java
Hot fix! Summarization doesn't work in JabRef currently, because I messed up
=> Fix summarization templates

CHANGELOG.md, src/main/java/org/jabref/logic/citationkeypattern/CitationKeyGenerator.java, src/test/java/org/jabref/logic/citationkeypattern/CitationKeyGeneratorTest.java, src/test/java/org/jabref/logic/citationkeypattern/MakeLabelWithDatabaseTest.java, src/test/java/org/jabref/logic/formatter/bibtexfields/RegexFormatterTest.java
Doesn't fully work, needs some more polishing.
Follow-up to https://github.com/JabRef/jabref/pull/9703
=> Allow - in citaton keys

docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-11-code-into-ide.md
Refs https://github.com/JabRef/jabref-issue-melting-pot/issues/504
I finally found a "solution" for the git submodule issue (posted at https://stackoverflow.com/questions/66773544/git-submodule-not-ignored-even-with-ignore-all/79176853#79176853). -- Background: I was about to file a bug against `lazygit`, but then I found out that `git add -A` ignores the `ignore = all` setting. After some googling, I found the solution to use `git update-index --assume-unchanged {sub-module-path}`.
This PR adds this to the documetation.
=> Add howto for git modules

src/main/java/org/jabref/gui/Base.css
Follow-up to https://github.com/JabRef/jabref/pull/11881
Hovering and selection should work now.
Kind of hot-fix (and also trial and erorr).
I merge - we can include more fixes later.
=> Fix hovering and selection highlighting

CHANGELOG.md, src/main/java/org/jabref/cli/ArgumentProcessor.java, src/main/java/org/jabref/gui/frame/JabRefFrameViewModel.java
Fixes https://github.com/koppor/jabref/issues/377.
=> Open "near-by" .bib file

.github/workflows/assign-issue.yml
We should give students (and us) more time for finishing an issue.
=> Increase time-out for work from 30 to 90 days

src/main/java/org/jabref/gui/entryeditor/FieldsEditorTab.java
=> REduce log level noise

src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java, src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditorViewModel.java, src/main/java/org/jabref/gui/linkedfile/LinkedFileEditDialogViewModel.java, src/main/java/org/jabref/logic/util/io/FileUtil.java, src/test/java/org/jabref/gui/linkedfile/LinkedFileEditDialogViewModelTest.java
Fixes #12212
some cleanup
Follow up to https://github.com/JabRef/jabref/pull/11539
=> move check for invalid characters to linked files editor

src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java, src/main/java/org/jabref/logic/openoffice/oocsltext/CSLFormatUtils.java, src/main/java/org/jabref/logic/openoffice/oocsltext/CSLUpdateBibliography.java, src/test/java/org/jabref/logic/openoffice/oocsltext/CSLFormatUtilsTest.java
Closes https://github.com/JabRef/jabref-issue-melting-pot/issues/697
- Reduces the number of UNO API calls - 
a) The `OOTextIntoOO#write()` method by default shifts the cursor to the end of the text after operations are done, so calling `cursor.collapseToEnd()` everywhere is needless.  
b) Explicit deletion of extra newlines/paragraph breaks using `cursor.setString()` is no longer needed in case of numeric styles as RegEx in `transformHTML` is now adapted to handle it, which is way faster.
- Changes newlines in bibliography to paragraph breaks, improving performance of documents with a large number of bibliographic entries drastically, as per information from https://bugs.documentfoundation.org/show_bug.cgi?id=163984
Old:
New: 
- Fixes extra newlines before each numeric bibliographic …
=> [OO] Major performance improvements & fixes

CHANGELOG.md, src/main/java/org/jabref/gui/libraryproperties/general/GeneralPropertiesViewModel.java, src/main/java/org/jabref/model/database/BibDatabaseContext.java, src/main/resources/l10n/JabRef_en.properties
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/694
=> Open specified folder in library properties

CHANGELOG.md, src/main/java/org/jabref/logic/exporter/ExporterFactory.java, src/main/resources/l10n/JabRef_en.properties, src/main/resources/resource/layout/title-markdown/title-md.article.layout, src/main/resources/resource/layout/title-markdown/title-md.book.layout, src/main/resources/resource/layout/title-markdown/title-md.incollection.layout, src/main/resources/resource/layout/title-markdown/title-md.inproceedings.layout, src/main/resources/resource/layout/title-markdown/title-md.layout, src/test/java/org/jabref/logic/exporter/MarkdownTitleExporterTest.java
I quickly implemented an export format in a specific (admittedly, opinionated) format to Markdown... I find the format useful to put on websites that uses Markdown as input format [website](https://linusdietz.com/publications).
For anybody who's interested, the command I use to generate the list of the website is: 
```
jabref -n -i literature.bib --exportMatches '(author="dietz"  and (entrytype=="article" or entrytype="inProceedings" or entrytype="inCollection"))',test.md,title-md
```
- / Screenshots added in PR description (for UI changes)
=> Markdown Export Formatter

.moderne/moderne.yml, build.gradle
Moderne does not support auto detection of the JDK. Thus, we need an explicit config.
Source: https://rewriteoss.slack.com/archives/C01A843MWG5/p1732576166436149?thread_ts=1732565625.698539&cid=C01A843MWG5
=> Add config for moderne

src/main/java/org/jabref/gui/JabRefGUI.java
I reset my prefs, jabref was opening in maximized mode, I resized Jabref but the stage still reported maximized
Refs https://github.com/JabRef/jabref/issues/11530
=> always set maximized  to false on exit for mac

README.md
I discussed with SE researchers about using JabRef. But we found no information in README.md. This is bad for small talk. Therefore, I added some text.
Will trigger auto merge to enable more discussions today.
=> Add hints on research (and BibTeX) to README.md

.github/ghprcomment.yml
I got feedback that the import order was messy, even though the IDE was setup correctly. As concequence, I refined the hint. Maybe, it helps.
=> Refine code comment of checkstyle

docs/decisions/0036-use-textarea-for-chat-content.md, docs/decisions/0042-use-webview-for-summarization-content.md
- Added a link to JavaFX Markdown UI component, that is the only one existing (for current moment).
- Wrote `ADR-0042`.
- Fixed some wording and style.
I don't know, but can I replace whole sections in one ADR by linking to whole sections in other ADR?
=> Add ADR-0042 and fix ADR-0036

.github/workflows/assign-issue.yml
This switches the assign-issue-action to a WIP version to test - https://github.com/takanome-dev/assign-issue-action/pull/261
=> Switch to pr-261 of assign-issue-action

src/main/java/org/jabref/gui/Base.css, src/main/java/org/jabref/gui/Dark.css
Closes #11898 . 
This PR allows each entry's background color to change by making some minor adjustments to Base.css and Dark.css files.
https://github.com/user-attachments/assets/f74d13b3-ac7a-49eb-9ff2-cee956d9b98d
=> Entry color now changes when dragging

CHANGELOG.md, src/main/java/org/jabref/gui/ai/components/summary/SummaryShowingComponent.fxml, src/main/java/org/jabref/gui/ai/components/summary/SummaryShowingComponent.java
Closes #12233 
As it was pre-requested, I've implemented an option when user is able, using checkbox, to change the formation of the `AI Summary`. If user checks it, `WebView` with formatted into `html` markdown appears, otherwise text stays raw. It is pretty useful new feature that makes `AI Summary` user-friendly for those, who loves to see formatted text, instead of raw `markdown` that besides the text contains "weird", in user's opinion characters.   
1. In the issue discussion, I asked questions, and maintainers came up with an idea that we need a simple toggle, so I decided to add into `org/jabref/gui/ai/components/summary/SummaryShowingComponent.fxml` a `CheckBox` that appears one the left below the `AI Summary`
2. This toggle handled in …
=> Use Markdown in AI Summary tab implemented

CHANGELOG.md, src/main/java/org/jabref/gui/preferences/externalfiletypes/ExternalFileTypesTabViewModel.java
Fixes https://github.com/JabRef/jabref/issues/12311
File extension uniqueness checks does not make sense oneedit when ext didn't change
=> Fix application not saved in external file type

src/main/java/org/jabref/gui/preferences/externalfiletypes/ExternalFileTypesTabViewModel.java
Follow-up to #10496.
The method name was not consistent to other Java code.
=> Fix method name

CHANGELOG.md, src/main/java/org/jabref/gui/linkedfile/DeleteFileAction.java
Fixes https://github.com/JabRef/jabref/issues/9731
=> Just Delete link from entry if the file is no longer accesible on disk

src/main/java/org/jabref/gui/externalfiles/ImportHandler.java, src/main/java/org/jabref/gui/externalfiles/UnlinkedFilesDialogViewModel.java, src/main/java/org/jabref/logic/importer/fileformat/PdfContentImporter.java, src/main/java/org/jabref/logic/importer/fileformat/PdfMergeMetadataImporter.java, src/test/java/org/jabref/logic/importer/fileformat/PdfContentImporterTest.java
Some bugs:
- Several steps of PDF import didn't work because of relativization. I removed it, but IDK if it's okay to do this. After that, all steps worked.
- When searching for unlinked files, PDF import didn't work at all.
- There was some bug when importing specific PDF files, when algorithm can't find title of the book. I replaced `String` to `Optional<String>` and import worked correctly.
- NEW: replaced `files` to `List.of(file)` in `ImportHandler`.
- [?] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
=> Fix some bugs with PDF imports

CHANGELOG.md, src/main/java/org/jabref/logic/importer/Importer.java
Fixes https://discourse.jabref.org/t/jabref-5-15-opens-bib-files-with-shift-jis-encoding-instead-of-utf-8/5369/
=>  Improve utf8 detection 

.github/workflows/deployment-arm64.yml, .github/workflows/deployment.yml
Link the issue that will be closed, e.g., "Closes #333". If your PR closes a koppor issue, link it using its URL, e.g., "Closes https://github.com/koppor/jabref/issues/47".
=> use v4 instead of master

src/main/java/org/jabref/logic/search/query/SearchToSqlVisitor.java, src/test/java/org/jabref/logic/search/query/SearchQuerySQLConversionTest.java
Follow-up to #11803.
Reverse searching with empty fields: Searching with `file = ""` will now return entries where the file field is empty, while searching with `file != ""` will return entries that contain files.
Closes https://github.com/JabRef/jabref-issue-melting-pot/issues/667
=> Searching for entries with empty field

src/main/java/org/jabref/logic/search/indexing/BibFieldsIndexer.java
Attempt to fix #12167.
I cannot reproduce the issue on my machine, but I guess it may be related to background threads and quickly updating the entry.
One possible scenario is that the user is updating the field quickly, and updating the field is a critical section that should be completed as an atomic operation without interruptions.
```
updateEntry(BibEntry entry, Field field) {
removeField(entry, field);
insertField(entry, field);
}
```
The issue might occur if the first thread removes the field, but before it inserts the field again, another thread updates the same entry and also removes the field. This could result in both threads attempting to insert the same field into the table twice, violating the primary key constraint (`entryId`, `fieldName`), which must be unique.
=> Fix postgres unique constraint exception

CHANGELOG.md, src/main/java/org/jabref/gui/Base.css, src/main/java/org/jabref/gui/Dark.css
Fixes #12413
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/755
=> Fix number column hits by adding css selectors

.gitattributes
There is a binary file comparison, which fails if .bak is CRLF instead of LF.
=> Fix tests for BackupManager

src/main/java/org/jabref/logic/importer/Importer.java
Refs https://github.com/JabRef/jabref-issue-melting-pot/issues/764.
Just a small comment explaining how to properly import files that are binary. Also explains a bit why `PdfImport#importDatabase(BufferedReader)` throws an exception.
=> Add comment for binary-based importers

CHANGELOG.md, src/main/java/org/jabref/gui/maintable/RightClickMenu.java
The fix ensures that if the database is untitled, the "Copy to" option in the right-click context menu displays "untitled" instead of a blank space.
=> Fix the displayed name of an untitled database

CHANGELOG.md, src/main/java/org/jabref/gui/autosaveandbackup/BackupManager.java
Fixes https://github.com/JabRef/jabref/issues/12462
=> Fix BibTexStrings not included in backup file

src/main/java/org/jabref/gui/maintable/RightClickMenu.java
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/768
Follow up to https://github.com/JabRef/jabref/pull/12374
=> Fix no such element exception in copy to

src/main/java/org/jabref/gui/Base.css, src/main/java/org/jabref/gui/WorkspacePreferences.java, src/main/java/org/jabref/gui/frame/JabRefFrame.java, src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java
Follow up to #12395 
Simplified and some quick code cleanups
@priyanshu16095 please check
=> Simplify hide tabbar

CHANGELOG.md, src/main/java/org/jabref/logic/citationkeypattern/BracketedPattern.java, src/main/java/org/jabref/logic/openoffice/oocsltext/CSLFormatUtils.java, src/test/java/org/jabref/logic/citationkeypattern/BracketedPatternTest.java, src/test/java/org/jabref/logic/citationkeypattern/CitationKeyGeneratorTest.java
Closes https://github.com/JabRef/jabref/issues/12312
=> Bring back `authorsAlpha` citation key pattern

src/main/java/org/jabref/gui/edit/CopyTo.java, src/main/resources/l10n/JabRef_en.properties
fixes #12486 
Add confirmation message after using "Copy to" option, also show whether the cross-reference entry was copied or not.
Copy to with cross-reference included
Copy to with cross-reference excluded
=> Add confirmation for 'Copy to' with cross-reference status

src/main/java/org/jabref/gui/edit/CopyTo.java
This fix ensures that the "Copy to" option follows the chosen preference correctly.
https://github.com/user-attachments/assets/93a6dde8-776a-4b80-94df-4f779d10843c
=> Fix: Usage of "Copy to" option preference

.github/workflows/product-map.yml
product map generation is does not work - blocked by https://github.com/product-map/product-map-action/issues/7
=> Disable product-map.yml

docs/decisions/0023-localized-preferences.md
=> Add ADR for "Localized Preferences"revisited

.github/workflows/product-map.yml, src/main/java/org/jabref/gui/consistency/ConsistencyCheckDialog.java
This PR ensures that columns for JabRef specific fields like ranking, read status, and more are not included in the table. Additionally, it removes redundant columns where the entire column represents there is an optional or required field is present
Removed
=> Fix remove redundant columns from consistency check table

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fileformat/MedlineImporter.java, src/test/resources/org/jabref/logic/importer/fileformat/MedlineImporterTestNbib.bib, src/test/resources/org/jabref/logic/importer/fileformat/MedlineImporterTestNbib.xml
During the import process, the labels indicating individual paragraphs within an abstract returned by PubMed/Medline XML are preserved. Closes #12527. Also complexity of some methodes is reduced.
=> Include PubMed labels in abstract at import (closes #12527)

src/test/resources/pdfs/PdfContentImporter/pdfContentImporterTest-pdfs.bib
We could not open `pdfContentImporterTest-pdfs.bib`. This PR fixes it.
Follow-up to https://github.com/JabRef/jabref/pull/12018
=> Fix syntax issues (and reformat using JabRef)

.github/workflows/assign-issue.yml
After reading https://github.com/m7kvqbe1/github-action-move-issues/pull/28/files, I think, the configuration with `default-column` works fine.
- If label "Assigned" is put: The issue is put to column "Assigned"
- If label "Assigned" is removed (AKA not existing): The issue is put to column "Free to take"
We still have to use a WIP version, because we do not want to track all issues in these boards, but only the issues we manually put there. (https://github.com/m7kvqbe1/github-action-move-issues/pull/28/)
=> Enable move back to column "Free to take"

.github/workflows/assign-issue.yml
After reading through https://github.com/JabRef/jabref/issues?q=sort%3Aupdated-desc%20is%3Aissue%20is%3Aopen%20label%3A%22%F0%9F%93%8D%20Assigned%22, I think, there are issues without any activity. Since we run out of "good first issues", we should enable others to take part.
We can still add "[📌 Pinned](https://github.com/JabRef/jabref/labels/%F0%9F%93%8C%20Pinned)" if a contributor needs longer to work on things.
I am aware that the metrics are still not that good - currently, all activity on an issue counts - not only the one of a contributor (https://github.com/takanome-dev/assign-issue-action/issues/268) or pull request activity (https://github.com/takanome-dev/assign-issue-action/issues/267).
=> Unassign after 45 days of inactivity

src/main/java/org/jabref/gui/commonfxcontrols/CitationKeyPatternSuggestionCell.java
Issue: The added dropdown has an issue, it shifts upwards when it reaches the bottom of the screen due to the default behavior of Context Menu in JavaFX.
This PR ensures that the dropdown is properly positioned and dynamically adjusts its height based on the available space. 
Additionally, the "All patterns" submenu is always shown when displaying the suggestions list is not possible, ensuring that the  UX is not compromised.
=> Fix Citationkey pattern dropdown UI issue

CHANGELOG.md, src/main/java/org/jabref/gui/actions/StandardActions.java, src/main/java/org/jabref/gui/groups/GroupNodeViewModel.java, src/main/java/org/jabref/gui/groups/GroupTreeView.java, src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java, src/main/java/org/jabref/gui/keyboard/KeyBinding.java, src/main/resources/l10n/JabRef_en.properties
This PR adds the functionality to rename a subgroup using the F2 keybinding. 
It converts the text into a text field, allowing the user to change the name, providing a better user experience.
=> Add rename subgroup option

.github/workflows/tests-fetchers.yml
Follow-up to #8258 -> `org.jabref.logic.importer.fileformat.pdf.PdfMergeMetadataImporterTest` is marked as fetcher test. Thus, fetcher tests should run if a change in this file occurs.
Whole thing triggered by https://github.com/JabRef/jabref/pull/12088 rendering a test not working, but did not show up, because no fetcher tests ran.
=> Fix trigger of fetcher tests

.gitmodules, CONTRIBUTING.md, src/main/java/org/jabref/gui/groups/GroupNodeViewModel.java, src/main/java/org/jabref/gui/groups/GroupTreeView.java, src/main/resources/l10n/JabRef_pt_BR.properties
Before
After
"Closes https://github.com/JabRef/jabref/issues/12540".
=> Enable drag-and-drop of PDFs into groups Fixes #12540

CHANGELOG.md, src/main/java/org/jabref/gui/LibraryTab.java
=> Fix incorrect deletion notification when canceling entry deletion

src/test/java/org/jabref/logic/importer/fetcher/SpringerFetcherTest.java
Added  default api key support for springer fetcher tests. Fixes #12610
=> Fixed tests for springer fetcher

.github/workflows/product-map.yml
Since https://github.com/product-map/product-map-action/issues/7 is fixed, we can try out product map.
Follow-up to https://github.com/JabRef/jabref/pull/12644
=> Enable product-map for contributions

.github/workflows/assign-issue.yml
We are working close with the developer of the `assign-issue-action`. We are using now the `edge` version for testing and providing quick feedback.
Refs: https://github.com/takanome-dev/assign-issue-action/pull/285#issuecomment-2708503286
=> Use edge version for assign-issue-action

.github/workflows/check-links.yml
Fixes lychee to run when CHANGELOG.md is changed --> there (typically) are no external links - and we have [heylogs](https://github.com/nbbrd/heylogs) checking the CHANGELOG.md intself
=> ignore CHANGELOG.md when checking on pushes

.github/ghprcomment.yml, .github/workflows/on-pr-closed.yml, .github/workflows/on-pr-opened.yml, .github/workflows/pr-comment.yml
- When a contributor opens a PR, we needed to manually update the state in the project.
- When we closed a PR without merging, we needed to manually update the state in the project (and also manually unassign the user)
With this PR, we get this in an automated fassion.
Following PRs need to be monitored and these files updated as soon as the PRs are merged:
- https://github.com/neofinancial/ticket-check-action/pull/58
- https://github.com/m7kvqbe1/github-action-move-issues/pull/38
=> Move issues on PR activity

CHANGELOG.md, src/main/java/org/jabref/gui/integrity/IntegrityCheckAction.java, src/main/resources/l10n/JabRef_en.properties
Closes https://github.com/JabRef/jabref/issues/12694
This PR changes the text "Checking integrity..." to "Waiting for the check to finish..." in integrity check progress dialog.
=> Change the message in the Integrity check progress dialog

.github/workflows/on-issue-comment.yml, .github/workflows/unassign-issues.yml
This is the final step to really automate the project state moval.
Before: If issues were automatically unassigned, they were still in the "Assigned" Column.
Now: If issues were automatically unassigned, they are moved accordingly.
I cannot really test it, we need to wait until an unassignment happens.
=> Split assign-workflow in issue-comment and schedule

.github/workflows/deployment-arm64.yml, .github/workflows/deployment-jdk-ea.yml, .github/workflows/deployment.yml, .github/workflows/tests-fetchers.yml, .github/workflows/tests.yml
Remove deprecated paramter.
See https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#the-gradle-home-cache-cleanup-input-parameter-has-been-replaced-by-cache-cleanup
Fixes
=> Remove deprecated parameter

.github/workflows/unassign-issues.yml, CHANGELOG.md, src/main/java/org/jabref/gui/actions/StandardActions.java, src/main/java/org/jabref/gui/cleanup/CleanupAction.java, src/main/java/org/jabref/gui/cleanup/CleanupDialog.java, src/main/java/org/jabref/gui/entryeditor/DeprecatedFieldsTab.java, src/main/java/org/jabref/gui/keyboard/KeyBinding.java, src/main/resources/l10n/JabRef_en.properties
Closes https://github.com/JabRef/jabref/issues/12703
This is an simple replace text in few files for changing "Cleanup entries" to "Clean up entries"
=> replacing "Cleanup entries" to "Clean up entries"

.github/workflows/tests-fetchers.yml
I get errors for fetcher tests in the jabref-koppor repo. Contributors probably also see this
Therefore disabling the scheduled tests on forks.
=> Refine condition for testing fetchers

.github/workflows/on-issue-unassigned.yml, .github/workflows/on-pr-closed.yml
At https://github.com/JabRef/jabref/issues/12351, I saw
And no workflow was started... still "Assigned". This PR should fix this. ` .github/workflows/on-issue-unassigned.yml` 
Also at unlabled: remove assignees
Also remove "FirstTimeContribution" label.
=> Add unassignment workflow (and removal of assignees)

CHANGELOG.md
Triggered by https://github.com/JabRef/jabref/pull/12718/files
This enables https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md012---multiple-consecutive-blank-lines
=> Disallow multiple consecutive blank lines in CHANGELOG.md

CHANGELOG.md, src/main/java/org/jabref/gui/preferences/PreferencesSearchHandler.java, src/main/java/org/jabref/gui/preferences/keybindings/KeyBindingsTab.fxml, src/main/java/org/jabref/gui/preferences/keybindings/KeyBindingsTab.java, src/main/java/org/jabref/gui/preferences/keybindings/KeyBindingsTabViewModel.java
I've improved the search functionality in the preferences view to include values from comboboxes and text fields, not just labeled controls. Previously, searching for "VScode" returned no results, requiring users to search for "push" instead. Now, comboboxes or textfields containing the searched term can be found directly.
In addition, when searching keybindings, matching categories now expand automatically, which wasn't the case before. I've also added "Expand all" and "Collapse all" buttons at the bottom of the tree table for easier navigation.
It's also now possible to search directly for specific key combinations (e.g., "ctrl+w") to quickly locate the associated actions.
Closes #12647
=> changed preferences and keybind search (issue #12647)

.gitattributes
Triggered by https://github.com/JabRef/jabref/pull/12678 and https://github.com/JabRef/jabref/pull/12732.
Merge conflicts in `JabRef_en.properties` are mostly because two different new translation strings are added by different branches. When merging using the command line, both are taken - if `merge=union` is active.
This PR enables this.
(Note: It is not supported by GitHub - see https://github.com/isaacs/github/issues/487 for details)
=> merge=union for JabRef_en.properties

src/main/java/org/jabref/gui/consistency/ConsistencyCheckDialog.java, src/main/java/org/jabref/gui/consistency/ConsistencyCheckDialogViewModel.java
Closes https://github.com/JabRef/jabref/issues/12697
This PR remove the second "Citation key" column from the Consistency check results table.
=> Remove second "Citation key" column from the Consistency check results table.

README.md
Follow-up to my commit https://github.com/JabRef/jabref/commit/2edf46ef60c778b2c987b7e348c89c6b9040b675.
Majorly - rearranged "contribution" pointers in readme in the order of their importance - taking into consideration that programmers are the most frequent contributors to JabRef.
Changes (or the assumptions on which the changes are based):
1. JabRef is not just used by scientists.
2. The first reference to direct people to should be `CONTRIBUTING.md` - as it is the bible.
3. Second most important pointer is the local development setup (rearranged).
4. Non-programmers can improve user-docs as well - added text.
5. Bug fixes are generally what people start with, not feature additions. Programmers can also improve documentation.
6. Added link to an example on running test locally.
7. …
=> Improve readme for newcomers

.github/ghprcomment.yml, .github/workflows/on-pr-opened.yml
Triggered by https://github.com/JabRef/jabref/pull/12544
=> Add automatic message on submodule modifications

.github/workflows/on-pr-opened.yml
Triggered by  https://github.com/JabRef/jabref/pull/12745 -> https://github.com/JabRef/jabref/pull/12747
Currently, issues are unassigned when a PR is closed. If a contributor submits a new PR, the issue is marked as "in-progress", but the assignee is not updated.
With this PR the assignees of an issue are "enrichted" by the PR submitter.
I am aware that an issue have then multiple persons assigned. I think, this helps rather then it hurts.
=> Add PR creator as issue assignee when a PR is opened

.github/workflows/on-issue-comment.yml, .github/workflows/on-pr-closed.yml, .github/workflows/on-pr-opened.yml, .github/workflows/unassign-issues.yml
Triggered by https://github.com/JabRef/jabref/issues/12434#issuecomment-2727112445
The action itself suggests 7 days as default for unassignment (https://github.com/takanome-dev/assign-issue-action?tab=readme-ov-file#inputs). This was too short for us, we opted for `45` days. Often, nothing happens and the issue ist just unassigned.
We are interested that a PR is there which is worked on.
IMHO, two weeks should be enough to open a draft PR - or discuss on the issue itself something to get a draft PR ready.
Therefore: If PR is opened, `📌 Pinned` label is added. With this, label, the issue is not unassigned after 14 days. In case the PR is closed without merging, the `📌 Pinned` label is removed.
- [/] Change in `CHANGELOG.md` described in a way that is understandable for the average user …
=> Add "📌 Pinned" for WIP workflows

.github/workflows/unassign-issues.yml
We block re-assignments.
Thus, the default text does not make sense.
I removed the yellow text.
=> Refine unassign-issues.yml

.github/PULL_REQUEST_TEMPLATE.md, .github/ghprcomment.yml, .github/workflows/on-pr-opened.yml
Risen by https://github.com/JabRef/jabref/pull/12761
Our RegEx matched the wrong issue number:
Therefore, the contributor could not be assigned to the issue:
Separated check into "Ensure that contributor is assigned (fails if not commented on issue)" to really make explicit when assignment does not work -- will not raise any comment
Also fixed a typo
=> Add explicit error on missing number

.github/workflows/on-pr-closed.yml
Triggered by https://github.com/JabRef/jabref/pull/12756
When closing a PR, we unassign the contributor and free the issue. However, if someone opens a second PR for the same issue (in the example: https://github.com/JabRef/jabref/issues/12702), the action should not do this work. this PR.
This update of the action fixes it.
The change in `taget-column` should have no effect. With the upstream fix https://github.com/m7kvqbe1/github-action-move-issues/pull/37, the current data of the issue is used (and not stale one)
=> Move to other column only if no assignee left

.github/workflows/on-pr-closed.yml, .github/workflows/on-pr-opened.yml
Note: My PR comment at https://github.com/JabRef/jabref/pull/12775 triggered https://github.com/JabRef/jabref/blob/928b7e55984109ad2ff597777c380be74120893b/.github/workflows/on-pr-opened.yml (https://github.com/JabRef/jabref/actions/runs/13941592810?pr=12775)
Then, it assigned me and pinned numer 12702.
Since also someone else could craft "bad" PR descriptions, I changed the action to just add the current PR worker to the list of assignees instead of replacing it.
(I also fixed a hard-coded issue number)
=> Keep existing assignees on a PR

CONTRIBUTING.md, README.md, docs/code-howtos/code-quality.md, docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/pre-03-code.md
Before:
After:
I know, I liked these badges some years ago. With our target group, I think, they are not useful at all - APIdia is :)
=> Switch Badges

.github/ghprcomment.yml, .github/workflows/tests.yml
Added a workflow that detects if no changes were made to CHANGELOG.md and notifies the user to document any changes there.
=> workflow added for detecting changelog modification

.github/ghprcomment.yml, .github/workflows/tests.yml
Reverts JabRef/jabref#12783
This check raised discussion among the maintainers (smilar discussions I had before)
I was convinced that this workflow is too much  - and would also require (`/no-changelog-entry-needed` bot reaction).
A possible follow-up is to add a check for the "checklist" part in the PR description.
@palukku sorry for the effort spend!
=> Revert "workflow added for detecting changelog modification"

.github/workflows/tests.yml
"No checkbox present' is a subset condition of "not equal to 7 checkboxes present", so can be collapsed.
=> Optimize mandatory checks test

.github/workflows/on-issue-unlabeled.yml
I changed the label from "good first issue" to "good second issue" at https://github.com/JabRef/jabref/issues/12556 - and then the Assignee was removed -> https://github.com/JabRef/jabref/actions/runs/14022902800/job/39257172728
Should not happen - only removal if label "Assigned" or "FirstTimeCodeContribution" is removed.
- [.] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in …
=> Fix removal of all assignees

.github/ghprcomment.yml, .github/workflows/tests.yml
Follow-up to https://github.com/JabRef/jabref/pull/12786 / https://github.com/JabRef/jabref/pull/12783
Triggered by https://github.com/JabRef/jabref/pull/12796#issuecomment-2745266922
Check sonly for `[x]` and then for CHANGELOG.md modificatoins - does not check for `[/]` and then if CHANGELOG.md is notg modified
- [/] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull …
=> workflow added for detecting changelog modification (#12783)

build.gradle
Triggered by https://github.com/JabRef/jabref-issue-melting-pot/issues/836
I don't like "(Unknown Source)".
This should bring back line numbers. …
=> Remove --strip-debug

src/main/java/org/jabref/gui/cleanup/CleanupAction.java
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/836
- Uses copy of list to prevent concurrent modification exception
Additionally:
- Fixed cound of modified entries
=> Fix concurrent modification exception

.github/ghprcomment.yml
For comments on PRs on failing tests, I reordered the comments. Note that the bot sends the first matching comment only, even if multiple test fails:
- PR text
- Compilation, tests, and code style
- CHANGELOG.md and *.md
- Submodules and branche
---
I also modified the text for `main` branch to say: In future, they should do differently. Otherwise, the contributor might get confused.
- [.] [Checked developer's documentation](https://devdocs.jabref.org/): Is the …
=> Reorder priorities

.github/ghprcomment.yml
Context: https://github.com/JabRef/jabref/pull/12817
Students want to geht their code out and seem not to care about the checks of code. Thus, waiting for a PR checklist being fixed before any code comments appear leads to NOOP on their side.
With this update of `ghprcomments.yml`, students get:
- Comments on failing code - first hit only
- Always comments on wrong PR format (both issue link and checklist)
This is a HOT FIX, therefore merging immediatly.
- [.] …
=> Make PR text comments always appearing

CHANGELOG.md, src/main/java/org/jabref/logic/util/io/FileUtil.java, src/test/java/org/jabref/logic/util/io/FileUtilTest.java
Closes #12188
This fixes an issue where LaTeX commands (e.g., \mkbibquote{...}) were retained in generated filenames using the [fulltitle] pattern.
- When the filename pattern is set to `[bibtexkey] - [fulltitle]`, and linked files are renamed automatically (e.g., during PDF import or when using "Rename file to pattern"), the class `LinkedFileHandler` calls `FileUtil.createFileNameFromPattern()` to generate the new filename.
- Previously, this method only applied `FileNameCleaner.cleanFileName(targetName)`, which removes illegal characters, but does not strip LaTeX commands such as `\mkbibquote{}`. This led to filenames like: `BrayBuildingCommunity - Building _mkbibquote_Community_.pdf`
- To fix this, I added a call to `RemoveLatexCommandsFormatter.format()` before cleaning the filename. …
=> Fix for issue: Sanitization of generated filenames (remove LaTeX commands) #12188

CHANGELOG.md, src/main/java/org/jabref/gui/groups/GroupTreeView.java
Closes https://github.com/JabRef/jabref/issues/11487
Problem:
Previously, when a group was removed, it would still appear on hover, and users could interact with it via the right-click context menu. Additionally, for groups without a description, the description of the previously removed group could incorrectly appear due to this bug. This was caused by the UI not refreshing immediately after the group was deleted. (before_changes.mp4)
https://github.com/user-attachments/assets/68c2cea4-7cab-4989-a43d-4a6508599238
Solution:
Added groupTree.refresh(); after group removal to ensure the interface updates correctly, preventing ghost groups from lingering in the UI and avoiding incorrect description display for newly created groups. (after_changes.mp4) …
=> Fix: Refresh groupTree after removing group (fixes #11487)

CHANGELOG.md, src/main/java/org/jabref/logic/importer/fetcher/DoiFetcher.java, src/test/java/org/jabref/logic/importer/fetcher/DoiFetcherTest.java
Closes #12434
This fixes an issue where valid DOI couldn't be imported if they had some special characters like _<_ or _>_.
These characters have to be URL encoded which was usually done with DOI#getURIAsASCIIString but this returns the whole URL and DoiFetcher#getAgency used a different domain, so it created the URL manually with DOI#asString which is not URL encoded. I added the URL encoding in DoiFetcher#getAgency.
The image below shows that the DOI mentioned in the issue was imported successfully after the fix.
- [/] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I …
=> Fix import of DOI with < and > characters

src/main/java/org/jabref/gui/openoffice/OOBibBase.java, src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java
Some quick architectural cleanups triggered by discussion at https://github.com/JabRef/jabref/pull/12784#discussion_r2014742700.
- Free `CSLCitationOOAdapter` completely of preferences.
- Some related comments explaining usage of the initial style of generic style type to detect changes in styles in the adapter
- Only one instance of `CSLUpdateBibliography` needed - some more breathing space for the garbage collector.
=> Tiny CSL architectural cleanup

.github/ghprcomment.yml
Consistent wording for the comments: 
- Always guide users to the test box in a PR - not the tab in the PR.
- Have the action to do as last paragraph of the comment …
=> Consistent wording

CHANGELOG.md, src/main/java/org/jabref/gui/maintable/columns/FileColumn.java
Ensures that when hovering over the "Linked Files" tab, the tooltip displays all linked files instead of just the first one. This fix resolves the issue where only the first linked file was shown.
The logic in createFileTooltip was updated to generate a single string containing the paths of all linked files.
An early return was added at the beginning to handle cases where no files are linked, improving efficiency. The text for the "Open file" action was also adjusted: it now displays "Open file" when there is only one linked file and "Open files..." when there are multiple. The phrase "Open files..." was chosen because it was the only plural form available in the translation files, as neither "Open files" nor "Open files %0" were present. This ensures consistency across different …
=> Fix tooltip display for multiple linked files

src/main/java/org/jabref/logic/util/BuildInfo.java
Our `BuildInfo` class contained non-used properties from a very long time ago. I removed that.
- [.] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted …
=> Remove java9 property from BuildInfo

.github/workflows/on-pr-opened.yml, .github/workflows/on-pr-synchronize.yml, .github/workflows/pr-comment.yml
Triggered by https://github.com/JabRef/jabref/pull/12747#issuecomment-2760401736
With `synchronize`, a comment should be triggered as soon as there is a modification of `main` …
=> Post conflict message as soon as conflict occurrs

CHANGELOG.md, src/main/java/org/jabref/gui/openoffice/OOBibBase.java
Follow-up to https://github.com/JabRef/jabref/pull/12472 (and prior)
- Use controller locking to prevent document refresh during citing/re-insertion/bibliography generation/re-generation.
Drastically improves the performance of write operations in the document, making them appear almost instantaneous.
https://github.com/user-attachments/assets/0419a9fa-a854-43bf-9ec9-c8109deb3ed7
=> [OO/CSL] Instantaneous citation insertion and refresh

.github/workflows/on-issue-comment.yml, .github/workflows/unassign-issues.yml
Ports https://github.com/takanome-dev/assign-issue-action/pull/320 to here.
- Changed "final" unassignment deadline to 21 days
- Sends a reminder after 11 days
Options: turn back to 14 days (and reminder after 7 days); but I think, this could be too pushy for student groups. 10 /11days is a good meassure IMHO
- [.] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull …
=> Add "reminder_comment"

src/main/java/org/jabref/gui/edit/CopyToPreferences.java, src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java
Closes #12843 
This pull request addresses an issue where the dialog prompting users about including cross-references reappears even after the user has selected the "Do not ask again" option. Additionally, it resolves the problem of the updated state of preferences not being saved correctly, ensuring that the last saved state persists across sessions.
* Use EasyBind.listen() in `getCopyToPreferences` to observe any change in these properties to save the preferences.
* Implemented property binding in  `CopyToPreferences` class.
_Screen Recordings:_ 
https://github.com/user-attachments/assets/79ee2755-3576-42ad-8284-516a07f7c04e
https://github.com/user-attachments/assets/88e5359e-c797-462d-926d-7722d642b9d4
- [/] Screenshots added in PR …
=> Fix "Copy to" preferences

CHANGELOG.md, src/main/java/org/jabref/gui/entryeditor/SciteTab.java, src/main/java/org/jabref/gui/preferences/ai/AiTab.fxml, src/main/java/org/jabref/gui/preferences/preview/PreviewTab.fxml, src/main/resources/l10n/JabRef_en.properties
After translating Chinese (Simplified), I found that some texts could not be translated:
- "User message for chatting", "Completion text for summarization of a chunk", "Completion text for summarization of several chunks" are in the localization dictionary but missing the prefix `%` in `AiTab.fxml`.
- "Show preview in entry table tooltip" in the `PreviewTab.fxml` also needs a prefix `%` to get translated.
- The tab title of "Citation Information" could not be translated and the content of the tab could not be translated as well.
To solve this, I made some fixes as follows:
- I directly added the prefix `%` for the first two spots, and added the localization strings in `JabRef_en.properties` according to [Localization | Developer Documentation](https://devdocs.jabref.org/code-howtos/localiz …
=> Fix for missing localization strings in SciteTab and Preferences dialog

CHANGELOG.md, src/main/java/org/jabref/gui/LibraryTab.java, src/main/java/org/jabref/gui/frame/JabRefFrame.java
Fix pasting on mac works again in the maintable
Request focus on the maintable when adding a new library
=> Remove key handling mac paste workaround and focus on maintable

.github/workflows/on-pr-closed.yml
Detected at https://github.com/JabRef/jabref/issues/7516#issuecomment-2801983511
Dependabot creates comments with the format `#{number}`. This number is treated as JabRef issue number, but it is not:
This is an issue of the RegEx of the used action [ticket-check-action](https://github.com/neofinancial/ticket-check-action). 
I updated the configuration to "listen" to GitHubs keywords `closes` etc.
- [.] [Checked developer's …
=> Add workaround for comment posting / issue move

build.gradle, settings.gradle
Update gradle syntax which is deprecated and scheduled to be removed in Gradle 9.0 and 10.0.
As per report `problems-report.html` generated by the `projectReport` task.
=> Upgrade Gradle syntax

docs/requirements/entry-editor.md, src/main/java/org/jabref/gui/entryeditor/EntryEditor.java
Follow-up to #12210
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/861
=> EntryEditor now also shows on empty entries

docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-89-run-with-intellij.md
At https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-89-run-with-intellij.html the numbering is odd
This PR tries to fix it. …
=> Try to fix numbering

src/main/java/org/jabref/gui/Base.css, src/main/java/org/jabref/gui/ai/components/aichat/AiChatComponent.java
Tiny PR fixing newline related comments (extra/missing) in https://github.com/JabRef/jabref/pull/12747.
=> Fix newline comments

build.gradle, src/main/java/org/jabref/logic/citationstyle/CitationStyleCatalogGenerator.java
Some cleanups/optimizations in build process of JabRef:
- Do not export the generated CSL catalog into `src/main/resources/` and then copy it to `build/resources/main`. 
Instead, export it directly to `build/resources/main` and let both JabRef application as well as tests use it from there. The catalog is an artifact generated during build process, not an "src" resource like the actual csl style files. (Trigger: https://github.com/JabRef/jabref/pull/12960#discussion_r2051556121)
- Remove `exclude module: "jsr305"` from guava dependency as https://github.com/google/guava/issues/2960 is fixed.
- [/] Screenshots added …
=> Clean build process

CHANGELOG.md, src/main/java/org/jabref/logic/openoffice/ReferenceMark.java, src/test/java/org/jabref/logic/openoffice/ReferenceMarkTest.java
Follow-up to https://github.com/JabRef/jabref/pull/12474
To accommodate the following auto-generated default citation key from the bibtex entry mentioned in https://github.com/JabRef/jabref/issues/12930#issue-2991246751:
```
@Online{,
author = {{The PGF/TikZ Team}},
date   = {2023-01-16},
title  = {pgf – Create PostScript and PDF graphics in TeX},
url    = {https://ctan.org/pkg/pgf},
}
```
[contains forward slashes("`/`")]
Earlier behavior: The key would not be parsed properly as it was not flexible enough to allow slashes. After citation, on trying to generate bibliography, following dialog was observed:
And then the exception:
=> [OO] Allow slashes in citation keys for reference marks

src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java, src/main/java/org/jabref/logic/citationstyle/CSLStyleUtils.java, src/main/java/org/jabref/logic/citationstyle/CitationStyle.java, src/main/java/org/jabref/logic/preferences/JabRefCliPreferences.java, src/test/java/org/jabref/logic/citationstyle/CSLStyleUtilsTest.java
Follow-up to https://github.com/JabRef/jabref/pull/12951
- `isCitationStyleFile(...)` is a static file-based utility used across many classes, and does not depend on a Citation Style model instance. A model instance should already _assume_ that it's a valid Citation Style file. Moved it to `CSLStyleUtils`.
- Rearranged methods in `CSLStyleUtils` for better readability.
- Added tests for `isCitationStyleFile(...)`
=> Rearrange some CSL methods, add more tests

src/main/java/org/jabref/gui/openoffice/StyleSelectDialogViewModel.java
Follow-up to https://github.com/JabRef/jabref/pull/12951.
Use `BibEntryTypesManager` from constructor instead of redundantly using injector in `StyleSelectDialogViewModel`.
=> Remove usage of Injector in `StyleSelectDialogViewModel`

.github/workflows/automerge.yml, .github/workflows/crowdin.yml, .github/workflows/on-pr-closed.yml, .github/workflows/on-pr-opened-updated.yml, .github/workflows/tests.yml, crowdin.yml
Follow-up to #12990.
- Fixes paths in `/crowdin.yml` 
- Swtiches from crowdin-config to [crowdin action](https://github.com/crowdin/github-action)
Refs https://github.com/crowdin/github-action/issues/274
- [.] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If …
=> Add Crowdin action

jablib/src/main/java/org/jabref/logic/bibtex/BibEntryWriter.java
Tries to avoid boxing and unboxing in BibEntryWriter …
=> Use basic type

jablib/src/main/java/org/jabref/logic/citationstyle/CSLAdapter.java, jablib/src/main/java/org/jabref/logic/citationstyle/CitationStyleGenerator.java
Support for Citation Styles in JabRef was introduced in 2016 in https://github.com/JabRef/jabref/pull/1928, which had included a warning comment regarding citation generation time due to citeproc-java using JavaScript. Also refs. https://github.com/JabRef/jabref/pull/3533 where this comment put as an implNote.
As of [release 3.0.0](https://github.com/michel-kraemer/citeproc-java/releases/tag/3.0.0) of citeproc-java (March 2024), the library is implemented in pure Java, so the comments needed some refinement.
Suggestions welcome, as I was hesitant to remove the "takes time" part from the comments.
- [/] Manually …
=> Update JavaDoc for CSL citation generation

docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-11-code-into-ide.md, docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/pre-02-software.md
Minor fixes in docs.
Ported from https://github.com/JabRef/jabref/pull/13036
- [.] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to …
=> Fix path - and fix typo

.github/workflows/update-gradle-wrapper.yml
According to https://github.com/gradle-update/update-gradle-wrapper-action/tree/v2/, there is no JDK setup needed - thus I am removing the installation there. …
=> Updating the gradle wrapper does not need any JDK

CHANGELOG.md, jabgui/src/main/java/org/jabref/gui/openoffice/OpenOfficePanel.java
=> Fix OO sync button not enabeld for jstyle

.github/workflows/deployment-ea.yml, .github/workflows/deployment.yml
Ports changes of https://github.com/JabRef/jabref/pull/13032 to -ea - and some minor updates of ea build to normal build.
- [.] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> …
=> Port changes of normal build to ea build

CHANGELOG.md, jabgui/src/main/resources/org/jabref/gui/openoffice/StyleSelectDialog.fxml
Fix: Increase preview area in style selection dialog to show full citation preview (#13051)
Closes #13051
This PR fixes a UI issue where the preview of citation styles (both Jstyle and CSL) in the OpenOffice style selection dialog was too small, especially on macOS. The preview box height has been increased to ensure full visibility of citation content without requiring vertical scrolling or cutting off lines.
Changes made:
- Increased the height (`prefHeight`) of the `VBox` containing the preview (`cslPreviewBox` and `jStylePreviewBox`) in `StyleSelectDialog.fxml`.
- Verified visually that the updated layout does not impact the overall dialog size or distort other elements.
Before (macOS):  
After (macOS):  
- [/] Tests created for changes (not applicable - UI layout only)
@lydia-yan …
=> Fix: Increase preview area in style selection dialog to show full citation preview (#13051)

jablib/src/main/java/org/jabref/logic/openoffice/style/JStyle.java
Closes https://github.com/JabRef/jabref/issues/13073
This is an internal PR to observe any side-effects.
The issue occurs only when running via gradle, and not on installing via dmg/msi.
Description of fix based on [artifact](https://claude.ai/public/artifacts/f6f424c6-034c-4c70-b4f4-511f70f481d6). …
=> Try to fix `FileNotFoundException` on selecting default JStyles

jabgui/src/main/java/org/jabref/gui/preferences/general/GeneralTabViewModel.java, jablib/src/main/resources/l10n/JabRef_en.properties
=> Fix inclusion of output string in translation

jabgui/src/main/java/org/jabref/gui/preferences/ai/AiTabViewModel.java
IntelliJ showed some hints to replace an unused variable by `_`.
- [/] [Checked developer's documentation](htps://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request. …
=> Replace unused variables by_

jabgui/build.gradle.kts, jabgui/src/main/java/org/jabref/gui/JabRefGUI.java, jabgui/src/main/java/org/jabref/gui/LibraryTab.java, jabgui/src/main/java/org/jabref/gui/importer/actions/OpenDatabaseAction.java
Follow-up to #13012
`fileUpdateMonitor` was not initalized properly.
Additionally, this PR enables `assert` statements to be evaluted. …
=> Fix startup in case of files

CHANGELOG.md, jabgui/src/main/java/org/jabref/gui/newentry/NewEntryView.java, jabgui/src/main/java/org/jabref/gui/newentry/NewEntryViewModel.java, jablib/src/main/java/org/jabref/logic/importer/CompositeIdFetcher.java
Select correct tab for creation of new entry (#13087)
Closes #13087
This PR improves the user experience when creating new entries. If the clipboard contains a valid identifier (like a DOI), the 'Enter Identifier' tab will now be automatically selected, and the identifier will be pre-filled.  
Changes made:
- Automatically select "Enter identifier" tab when clipboard contains valid identifier 
- Automatically populate the input field with clipboard content 
- If no valid identifier is found, the dialog falls back to the previously used approach from preferences.
Before:  
After:  
- [/] Tests created for changes (not applicable)
[@lydia-yan](https://github.com/lydia-yan) [@yoasaaa](https://github.com/yoasaaa) [@brandon-lau0](https://github.com/brandon-lau0) …
=> feat: select correct tab for creation of new entry (#13087)

.github/ISSUE_TEMPLATE/bug_report.yml
Bug reports should have the type "bug"
Found via https://github.com/community/maintainers/discussions/529
- [.] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, …
=> Add type "Bug"

jablib/src/main/java/org/jabref/logic/ai/chatting/AiChatLogic.java
=> Fix `OpenAITokenizer` constructor deprecation

jabkit/src/main/java/org/jabref/cli/CheckConsistency.java
We use "library" for .bib file and "database" for SQL-database. …
=> Use "library" for .bib file

Dockerfile.jabkit, Dockerfile.jabsrv
At https://github.com/orgs/JabRef/packages/container/package/jabsrv, I see
---
This PR does that.
I accept that the names are not consistent:
I would no open yet another repository for this, because that is more confusing (and the build is more complicated)
- [.] [Checked …
=> Link to JabRefs repo

.github/workflows/binaries.yml, .jbang/JabKitLauncher.java, config/checkstyle/suppressions.xml, gradle.properties, jablib/build.gradle.kts
Follow-up to https://github.com/JabRef/jabref/pull/13123
Triggered by https://github.com/APIdia-net/apidia.net/issues/2#issuecomment-2888414260
The chosen approach follows https://wiki.debian.org/Subkeys
---
Alternatives:
- import GnuPG key using https://github.com/crazy-max/ghaction-import-gpg
- [.] …
=> Add publishing of JabLib snapshot to maven central

.github/workflows/on-issue-unassigned.yml, .github/workflows/on-pr-closed.yml
Triggered by https://github.com/JabRef/jabref/issues/13013 - the action removed the assigned and pinned label; even though I was assigned.
This PR fixes this
Also removes some more labels on PR closing
- [.] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If …
=> Fix label removal on unassigment

jablib/src/main/java/org/jabref/logic/bibtex/comparator/BibEntryByCitationKeyComparator.java, jablib/src/main/java/org/jabref/logic/bibtex/comparator/BibEntryByFieldsComparator.java, jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java, jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckResultTxtWriter.java, jablib/src/main/resources/l10n/JabRef_en.properties, jablib/src/test/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckResultTxtWriterTest.java
Fixes https://github.com/JabRef/jabref/issues/13013
No CHANGELOG, because feature is not yet released …
=> Fix citation key table

.jbang/JabSrvLauncher.java, docs/code-howtos/http-server.md, jabsrv-cli/src/main/java/org/jabref/http/server/cli/ServerCli.java, jabsrv/src/main/java/org/jabref/http/server/LibrariesResource.java, jabsrv/src/main/java/org/jabref/http/server/LibraryResource.java, jabsrv/src/test/java/org/jabref/http/server/LibrariesResourceTest.java, jabsrv/src/test/rest-api.http
- Add "demo" library for http: for test setups, it is useful to have some path working on all instances. <http://localhost:6050/libraries/demo> is now available on all platforms
- On Windows checkout, the "real" Chocolate.bib is now served (it is the same content as served at `/demo`)
- Enable `jbang https://github.com/JabRef/jabref/blob/main/.jbang/JabSrvLauncher.java`
- Restructured `rest-api.http` …
=> Refine HTTP Server

.jbang/CloneJabRef.java
Required for https://github.com/JabRef/user-documentation/pull/569
- [.] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the …
=> Add JabRef cloning command

crowdin.yml
=> fix location of properties files for crowdin

.github/workflows/binaries-ea.yml, .github/workflows/binaries.yml, jabgui/build.gradle.kts, jabkit/build.gradle.kts, jabsrv-cli/build.gradle.kts
This enables [JEP 450: Compact Object Headers (Experimental)](https://openjdk.org/jeps/450).
They are considered stable: [JEP 519: Compact Object Headers](https://openjdk.org/jeps/519)
> In one setting, the SPECjbb2015 benchmark uses [22% less heap space and 8% less CPU time](https://github.com/rkennke/talks/blob/master/Lilliput-FOSDEM-2025.pdf).
>
> In another setting, the number of garbage collections done by SPECjbb2015 is [reduced by 15%](https://bugs.openjdk.org/browse/JDK-8350457?focusedId=14766358&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14766358), with both the G1 and Parallel collectors.
- [/] Tests created for …
=> Enable JEP-450 and ZGC

jabkit/src/main/java/org/jabref/cli/Search.java, jablib/src/main/java/org/jabref/logic/search/DatabaseSearcher.java, jablib/src/test/java/org/jabref/logic/search/DatabaseSearcherTest.java, jablib/src/test/java/org/jabref/logic/search/DatabaseSearcherWithBibFilesTest.java
Refactor the DatabaseSearcher so it is no longer needed to create a new DatabaseSearcher everytime you want to perform a search and instead use the existing one (and therefore also the existing Indexmanager). …
=> Refactor Databasesearcher

.jbang/CheckoutPR.java
Wished at https://github.com/JabRef/blog.jabref.org/pull/115#discussion_r2116110119
Works:
=> CheckoutPR: Add support for updating main

CHANGELOG.md, jabgui/src/main/java/org/jabref/Launcher.java, jabgui/src/main/java/org/jabref/gui/frame/JabRefFrame.java, jabgui/src/main/java/org/jabref/gui/remote/CLIMessageHandler.java, jablib/src/main/java/org/jabref/logic/UiCommand.java, jablib/src/main/java/org/jabref/logic/remote/RemoteMessage.java, jablib/src/main/java/org/jabref/logic/remote/client/RemoteClient.java, jablib/src/main/java/org/jabref/logic/remote/server/RemoteListenerServer.java, jablib/src/main/java/org/jabref/logic/remote/server/RemoteMessageHandler.java
Closes #13129 
This issue consisted on focusing a running instance of Jabref when the user tried to open another instance of the program. To do so, the first step was to modify the handleMultipleAppInstances function, to return an option from an enum containing CONTINUE, SHUTDOWN, FOCUS to determine what to do next. If there is no instance, CONTINUE is selected and one boots up, if an instance is running, FOCUS is returned. Focus is a function created inside UiCommands. In the launcher if FOCUS is returned it triggers RemoteClient's sendFocus function, which sends the message FOCUS and its outlined inside RemoteMessage. Then the RemoteListenerServer picks up this FOCUS message inside of a case within a switch, which calls a function from the RemoteMessageHandler called handlerFocus() and …
=> feat(focus): Add functionality to focus on running instance

.github/workflows/tests.yml, renovate.json
We have four JBang scripts: https://github.com/JabRef/jabref/tree/main/.jbang - they specify dependencies inside the files and do not re-use the depdencies in `build.gradle.kts`.
I think, with [Forking Renovate GitHub App](https://github.com/apps/forking-renovate) and rough JBang tests, we could have automatic updates, similar to `dependabot`.
Alternative: Write a script updating the version numbers in the JBang scripts `//DEP` statements based on the information in `build.gradle.kts` files. Would be another JBang script :p. Maybe 50 lines, but IDK if its worth.
- [/] Manually tested changed features in running …
=> Add JBang tests and renovate support

.github/workflows/on-issue-comment.yml, .github/workflows/unassign-issues.yml
Since our gitter chat is not that frequently used, but students seem to be stuck, we add links to the JabRef Guru: https://gurubase.io/g/jabref on issue assignment and reminders.
- [/] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue …
=> Add link to JabRef guru

.github/workflows/tests.yml, .jbang/CheckoutPR.java, justfile
Refines `CheckoutPR.java` to show more information
I wanted to show the current HEAD commit SHA, but this was not easily possible. Thus, I left "as is". …
=> Use setup-jbang action (instead of custom call of .sh script)

.github/workflows/tests.yml
Follow-up to https://github.com/JabRef/jabref/pull/12869 (and somehow https://github.com/JabRef/jabref/pull/9992)
Run Windows tests on `main` - and manual trigger only; because they take too long - and we have seldomly changes working not on Windows.
- [./ Manually tested changed features in running JabRef (always required)
- [/] [Checked documentation](https://docs.jabref.org/): …
=> Run Windows tests only on main (and on demand)

jabgui/src/main/java/org/jabref/gui/exporter/WriteMetadataToLinkedPdfsAction.java, jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java, jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBaseConnect.java, jabgui/src/main/java/org/jabref/gui/slr/ManageStudyDefinitionViewModel.java, jabgui/src/main/java/org/jabref/gui/util/FilteredListProxy.java, jabkit/src/main/java/module-info.java, jabkit/src/main/java/org/jabref/cli/Convert.java, jabkit/src/main/java/org/jabref/cli/PdfUpdate.java, jabkit/src/main/java/org/jabref/cli/Search.java, jablib/src/main/java/org/jabref/generators/CitationStyleCatalogGenerator.java, jablib/src/main/java/org/jabref/generators/LtwaListMvGenerator.java, jablib/src/main/java/org/jabref/logic/ai/chatting/model/Gpt4AllModel.java, jablib/src/main/java/org/jabref/logic/ai/ingestion/FileToDocument.java, jablib/src/main/java/org/jabref/logic/bst/BstPreviewLayout.java, jablib/src/main/java/org/jabref/logic/citationstyle/CSLStyleLoader.java, jablib/src/main/java/org/jabref/logic/exporter/AtomicFileOutputStream.java, jablib/src/main/java/org/jabref/logic/exporter/OOCalcDatabase.java, jablib/src/main/java/org/jabref/logic/exporter/OpenDocumentRepresentation.java, jablib/src/main/java/org/jabref/logic/exporter/OpenDocumentSpreadsheetCreator.java, jablib/src/main/java/org/jabref/logic/exporter/OpenOfficeDocumentCreator.java, jablib/src/main/java/org/jabref/logic/importer/fileformat/BibtexParser.java, jablib/src/main/java/org/jabref/logic/importer/fileformat/MrDLibImporter.java, jablib/src/main/java/org/jabref/logic/importer/fileformat/MsBibImporter.java, jablib/src/main/java/org/jabref/logic/importer/fileformat/PdfMergeMetadataImporter.java, jablib/src/main/java/org/jabref/logic/importer/util/MathMLParser.java, jablib/src/main/java/org/jabref/logic/preferences/JabRefCliPreferences.java, jablib/src/main/java/org/jabref/logic/util/io/RegExpBasedFileFinder.java, jablib/src/main/java/org/jabref/logic/xmp/XmpUtilShared.java, jablib/src/main/java/org/jabref/model/schema/DublinCoreSchemaCustom.java, rewrite.yml
Follow-up to https://github.com/JabRef/jabref/pull/13178
- Addresses https://github.com/JabRef/jabref/pull/13178#discussion_r2111120936 and https://github.com/JabRef/jabref/pull/13178#discussion_r2111170183
- Remove generic exceptions from codebase wherever possible
- Remove unused observable change parameters in `JabRefCliPreferences`
- Use `toList()` in the classes touched above where applicable …
=> Miscellaneous refactoring - II

.github/workflows/on-pr-opened-updated.yml
Hotfix for https://github.com/JabRef/jabref/pull/13206
Contributors were assigned wrong issue numbers.
- [.] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I …
=> Fix wrong detection of issue numbers

jablib/src/main/java/org/jabref/logic/util/StandardFileType.java
YAML files also take `yml` as extension
=> Add yml as YAML extension

build-logic/build.gradle.kts, build-logic/src/main/kotlin/buildlogic.java-common-conventions.gradle.kts
Follow-up to https://github.com/JabRef/jabref/pull/13112
Applies fix of Jendrik https://github.com/JabRef/jabref/pull/13112#issuecomment-2933459438 …
=> Fix macOS-14 gradlew :jabgui:run

docs/code-howtos/faq.md
https://github.com/JabRef/jabref/blob/main/.github/workflows/merge-upstream.yml merges our main branch to contributors main branch regularly. This fails if workflow files are touched and might confuse contributors.
Maybe, a FAQ helps.
- [.] [Checked documentation](https://docs.jabref.org/): Is the …
=> Add FAQ on upstream sync

.github/workflows/update-gradle-wrapper.yml
Closes #_____
In about one to three sentences, describe the changes you have made: what, where, why, ...
Describe how reviewers can test this fix/feature. Ideally, think of how you would guide a beginner user of Jabef to try out your change.
You can add screenshots or videos (using [Loom](https://www.loom.com/) or by just adding .mp4 files).
- [.] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I …
=> add java install to gradle wrapper action

jabgui/build.gradle.kts
When executing in the IDE, I get
```
WARNING: Unknown module: org.jabref.merged.module specified to --add-exports
WARNING: Unknown module: org.jabref.merged.module specified to --add-exports
WARNING: Unknown module: org.jabref.merged.module specified to --add-opens
WARNING: Unknown module: org.jabref.merged.module specified to --add-opens
WARNING: Unknown module: org.jabref.merged.module specified to --add-opens
WARNING: Unknown module: org.jabref.merged.module specified to --add-opens
WARNING: Unknown module: org.jabref.merged.module specified to --enable-native-access
```
This is correct as the merged module is created by the jlink plugin, not before.
I fixed by moving these arguments to jlink.
I am not sure if `--enable-native-access` can be called multiple times. Therefore, a separate …
=> Move module tweaking of merged module to launcher

.github/workflows/on-pr-opened.yml
Since @trag-bot sometimes is wrong, we need to inform newcomers.
Based on https://github.com/plbstl/first-contribution
- [/] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, …
=> Add welcome message to first time contributors

jablib/src/main/antlr/org/jabref/logic/journals/ltwa/Ltwa.g4
This PR enhances the part of the Ltwa.g4 grammar file which causes parsing issues on some Windows systems, making it compatible with Windows and ensuring proper interpretation of characters.
- Fetch the latest changes.
- Restart the JabRef, it will work.
=> Update LETTER fragment to resolve Windows parsing issue

CHANGELOG.md, jabkit/src/main/java/org/jabref/JabKit.java, jabkit/src/main/java/org/jabref/cli/CheckConsistency.java, jabkit/src/test/java/org/jabref/cli/ArgumentProcessorTest.java
Closes #13328
A rough sketch of my idea how the consistency checker could yield a return code in cases where it did not find some inconsistencies.  This can be especially useful, when the checker is used in scripts or CI, where it could mark the stage as failing due to the non-zero return code.
@Siedlerchr @koppor This is a probably very hacky way of doing it, to sketch the idea.  I'd like to know your feedback about it, though.
Run the jabkit CLI with argument `check-consistency --input /path/to/erronueous.bib`
- [/] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull …
=> Let consistency checker yield a return code

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/on-pr-opened-updated.yml
Trying to use backticks as markers for replacement. I think, ``, `{{...}}`, `«...»` will cause more confusion.
- [/] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even …
=> Refine PR Template

docs/code-howtos/faq.md
abbrv instad of abbrev
Closes _____
=> Fix submodule repo name

.github/workflows/binaries-ea.yml, .github/workflows/binaries.yml, .github/workflows/delete-old-runs-automatically.yml, .github/workflows/dockerimages.yml, .github/workflows/latex.yml, .github/workflows/pages.yml, .github/workflows/tests.yml
Tries to disable workflows for forks (to save money for them)
Quick adressing of https://github.com/JabRef/jabref-issue-melting-pot/issues/964, but needs more work as follow-up. …
=> Reduce workflow runs for forks

docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/pre-03-code.md
Refs https://github.com/JabRef/jabref-issue-melting-pot/issues/964
=> Add "Disable GitHub actions"

jabgui/src/main/java/org/jabref/gui/entryeditor/fileannotationtab/FileAnnotationTab.java, jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java, jabgui/src/main/java/org/jabref/gui/preferences/entryeditor/EntryEditorTab.java, jabgui/src/main/java/org/jabref/gui/preferences/entryeditor/EntryEditorTabViewModel.java, jabgui/src/main/resources/org/jabref/gui/preferences/entryeditor/EntryEditorTab.fxml, jablib/src/main/java/org/jabref/logic/preferences/JabRefCliPreferences.java
Closes N/A;
Refactor "enableFileAnnotationsTab" to "smartFileAnnotationsTab" and rewrote shouldShow() in FileAnnotationTab as requested in #13279
=> Reword enableFileAnnotationsTab and refactor FileAnnotationsTab::shouldShow

.github/workflows/binaries.yml
=> Only prevent failure in publishing from stopping the workflow

jablib/src/test/java/org/jabref/logic/importer/fetcher/CrossRefTest.java, jablib/src/test/java/org/jabref/logic/importer/fetcher/MedlineFetcherTest.java, jablib/src/test/java/org/jabref/logic/importer/fetcher/SpringerFetcherTest.java
As discussed on devcall.
This **does not** solve 403s, 404s, too many requests, returned `Optional.empty`s, `[]`s and server-side exceptions.
=> Adapt some fetcher tests

.github/workflows/binaries-ea.yml
We cannot use JDK-25-ea due to https://github.com/gradle/gradle/issues/33310. We therefore disabled the whole EA thing in the workflows. We forgot to update the sepate steps for macOS. 
Fixed by this PR.
- [/] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If …
=> Fix usage of non-EA JDK

build-logic/src/main/kotlin/org.jabref.gradle.base.repositories.gradle.kts
With Gradle 9.0. RC 1 I get
```
> Failed to apply plugin 'org.jabref.gradle.base.repositories'.
> Cannot convert URI 'file:C:\git-repositories\JabRef/jablib/lib' to a file.
```
This PR fixes this.
Follow-up to https://github.com/JabRef/jabref/pull/13319
- [/] [Checked …
=> Fix maven url

jablib/src/main/java/org/jabref/logic/importer/fileformat/CitaviXmlImporter.java
Javadoc of CitaviXmlImporter.getPages contains invalid html, rendering it invalid javadoc. That is because some example code contains unescaped non-html `<...>` tags. Rather than escaping the problematic characters by `&lt;`, `&gt;`, which would have been the ugly and cheap solution, I took a moment to wrap the examples into proper snippet tags. Minor further improvements like inserting `<p>` tags instead of `----` which would not have resulted in the desired effect.
=> Fix Javadoc in CitaviXmlImporter.java/getPages

jablib/build.gradle.kts
We generate *.mv and `citation-style-catalog.json`.
Gradle runs these tasks even if the input directory does not change.
The input directory do not change that often; ignoring these speeds up the build significantly.
Assumptions:
- GitHub CI starts on blank build directory
- Developers seldomly work on parts of jabref requiring fresh abbreviation lists and new/other citation styles
- If developers work in the area of mv files, they will refresh these files on their own.
- [/] Screenshots added in PR description (if change is visible to the …
=> Speed up build by making assumptions

CHANGELOG.md, jablib/src/main/java/org/jabref/logic/importer/WebFetchers.java, jablib/src/main/java/org/jabref/logic/importer/fetcher/EuropePmcFetcher.java, jablib/src/test/java/org/jabref/logic/importer/fetcher/EuropePmcFetcherTest.java
Refs https://github.com/JabRef/jabref-issue-melting-pot/issues/955
Implemented ID based fetcher for EuropePMC
Follow up tasks (new issue):
- Full text fetcher (search results include links if fulltex is available)
- Search based parser fetcher
- Supporting of other types e.g. books 
(That's why I think it's not worth adding it in changelog right now)
Test written
- [/] [Checked documentation](https://docs.jabref.org/): Is the …
=> First part for implementaion of a Europe PMC fetcher

CHANGELOG.md, jabgui/src/main/java/org/jabref/gui/desktop/os/NativeDesktop.java, jabgui/src/main/java/org/jabref/gui/externalfiletype/ExternalFileType.java
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/968
In the case of a NON-online link (AKA a file) and a NON existing file, following code was executed
// No file matched the name, try to open it directly using the given app
openExternalFilePlatformIndependent(type, link, externalApplicationsPreferences);
IDK why. Is in since more than one year. Strange.
I removed it.
1. Rename an attached file
2. Try to open with JabRef
3. See error dialog
- [/] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue …
=> Click on non-existing PDF should raises dialog box

jablib/build.gradle.kts
Should fix following issue - hopefully
```
Plugin [id: 'com.github.koppor.jbang-gradle-plugin', version: 'fix-7-SNAPSHOT', artifact: 'com.github.koppor:jbang-gradle-plugin:fix-7-SNAPSHOT'] was not found in any of the following sources:
- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Included Builds (None of the included builds contain this plugin)
- Plugin Repositories (could not resolve plugin artifact 'com.github.koppor:jbang-gradle-plugin:fix-7-SNAPSHOT')
Searched in the following repositories:
Gradle Central Plugin Repository
maven(https://jitpack.io)
```
=> Change coordinates of plugin fix to get it working (again)

jablib/build.gradle.kts
We don't need the hack anymore. (Hint by jjohannes) …
=> Remove validation error suppression

jabsrv/src/main/java/module-info.java, jabsrv/src/main/java/org/jabref/http/dto/cayw/SimpleJson.java, jabsrv/src/main/java/org/jabref/http/server/LibraryResource.java, jabsrv/src/main/java/org/jabref/http/server/Server.java, jabsrv/src/main/java/org/jabref/http/server/cayw/CAYWQueryParams.java, jabsrv/src/main/java/org/jabref/http/server/cayw/CAYWResource.java, jabsrv/src/main/java/org/jabref/http/server/cayw/format/BibLatexFormatter.java, jabsrv/src/main/java/org/jabref/http/server/cayw/format/CAYWFormatter.java, jabsrv/src/main/java/org/jabref/http/server/cayw/format/FormatterService.java, jabsrv/src/main/java/org/jabref/http/server/cayw/format/SimpleJsonFormatter.java, jabsrv/src/main/java/org/jabref/http/server/cayw/gui/CAYWEntry.java, jabsrv/src/main/java/org/jabref/http/server/cayw/gui/SearchDialog.java, jabsrv/src/main/java/org/jabref/http/server/cayw/gui/SearchField.java, jabsrv/src/main/java/org/jabref/http/server/cayw/gui/SearchResultContainer.java, jabsrv/src/main/java/org/jabref/http/server/cayw/gui/SelectedItemsContainer.java, jabsrv/src/test/cayw.http
Follow up https://github.com/JabRef/jabref/pull/13185 and https://github.com/JabRef/jabref/issues/13187#issuecomment-3025649349
Closes https://github.com/palukku/jabref/issues/5
You can test the simple-json format by using this command:
`curl http://localhost:23119/better-bibtex/cayw?format=simple-json`
for biblatex (which is the default format) you can use this and change the command (defaults to autocite)
`curl http://localhost:23119/better-bibtex/cayw?format=biblatex&command=notautocite`
- [/] [Checked developer's …
=> Refine CAYW Endpoint

.jbang/README.md
I think, it would be good to have a README.md for our JBang scripts.
Here an initial proposal.
`jbang jabsrv@jabref` fails here, but I think, this is just a hickup, because https://github.com/JabRef/jbang-catalog/blob/main/jbang-catalog.json contains `jabsrv`.
- [/] [Checked …
=> Add .jbang/README.md

jabgui/src/test/java/org/jabref/gui/mergeentries/FieldRowViewModelTest.java
Closes 
Renamed the test method for non-mergeable fields in FieldRowViewModelTest to improve clarity and better reflect the tested behavior. No functional changes, only a test name update for maintainability.
No user-facing changes.  
To test, simply run the test suite (e.g., `./gradlew test`) and confirm all tests pass.
- [/] [Checked …
=> test: rename and clarify mergeFields exception test for non mergeable fields

jabsrv/src/main/java/org/jabref/http/manager/HttpServerManager.java, jabsrv/src/main/java/org/jabref/http/manager/HttpServerThread.java
When another server was started, JabRef could not shut down.
There migth be other issues - e.g., when working with preferences and another port (https://github.com/JabRef/jabref/pull/13479), but that can be handled then ^^ …
=> Hotfix for non-shutdown of http server

build-logic/src/main/kotlin/org.jabref.gradle.base.dependency-rules.gradle.kts, jabgui/src/main/java/module-info.java, jablib/src/main/java/module-info.java, jabsrv-cli/src/main/java/module-info.java, jabsrv/src/main/java/module-info.java
Closes #13509
This pull request reverts several module names in `module-info.java` and related Gradle configurations back to their previous values to ensure compatibility and maintain consistency with the existing codebase and dependencies.
1. Build the project using `./gradlew clean build` and verify there are no module-related errors.
2. Run the application and confirm that the modules load correctly without runtime issues.
=> fix: revert Java module names to restore Status Log compatibility in JabRef 5.15

.github/workflows/run-openrewrite.yml, jabgui/src/test/java/org/jabref/gui/libraryproperties/contentselectors/ContentSelectorViewModelTest.java
Triggered by https://github.com/JabRef/jabref/pull/13523
We should have a quick way to run OpenRewrite
Execute the workflow
- [/] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> …
=> Add run openrewrite

jabkit/src/main/java/org/jabref/JabKit.java
```bash
koppor@DESKTOP-KAK953S MINGW64 /c/git-repositories/jabref (refine-consistency-output)
$ jbang .jbang/JabKitLauncher.java
2025-07-05 11:41:15 [main] org.jabref.logic.journals.JournalAbbreviationLoader.loadRepository()
INFO: Loaded journal abbreviations from C:\Users\koppor\AppData\Local\Temp\jabref-journal14768976930855100370\journal-list.mv
&&&    &&&&&    &&&&&&&&   &&&&&&&&   &&&&&&&&& &&&&&&&&&
&&&    &&&&&    &&&   &&&  &&&   &&&  &&&       &&&
&&&   &&& &&&   &&&   &&&  &&&   &&&  &&&       &&&
&&&   &&   &&   &&&&&&&    &&&&&&&&   &&&&&&&&  &&&&&&&
&&&  &&&&&&&&&  &&&   &&&  &&&   &&&  &&&       &&&
&&&  &&&   &&&  &&&   &&&  &&&   &&&  &&&       &&&
&&&&&   &&&   &&&  &&&&&&&&   &&&   &&&  &&&&&&&&& &&&
Version: 100.0.0
Staying on top of your literature since 2003 - …
```
=> --porcelain does not output any info or warn errors on the console

test-support/src/main/java/org/jabref/support/CommonArchitectureTest.java
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/983
=> Added archtest, fixed whitespaces

CHANGELOG.md, jabgui/src/main/java/org/jabref/gui/theme/ThemeManager.java
- Add try/catch around themeWindowManager.install() to handle RuntimeException
- Prevents crash when native libraries are incompatible with ARM64 architecture
- Fixes #13536
Closes https://github.com/JabRef/jabref/issues/13536
- Added try/catch block around `themeWindowManager.install(scene)` in ThemeManager
- Prevents RuntimeException crash when native libraries are incompatible with ARM64 architecture
=> Fix Intel crash in ThemeManager on macOS

.github/workflows/publish.yml, .jbang/JabKitLauncher.java, .jbang/JabSrvLauncher.java
JBang and maven central did not work well together - I think, it is because I mixed up `-SNAPSHOT` with our AssemblyVersion magic.
Now, we have 6.0-SNAPSHOT as library versions - independent of 6.0-alpha.2 relases etc.
We could to more intelligent, but we need something working now :)
- [/] [Checked …
=> Fix version for SNAPSHOT

.github/ghprcomment.yml, CHANGELOG.md
Closes https://github.com/JabRef/jabref/issues/13576
replaces string "Tests" in two cases to "Source Code Tests" in file ghprcomment.yml
=>  Fix: Replace string "Tests" with "Source Code Tests" in PR Comment

jabgui/src/main/java/org/jabref/gui/LibraryTab.java
Discussion with @koppor 
Old artifact in LibraryTab
=> Remove double listener of LibraryTab

jablib/src/test/java/org/jabref/logic/citationstyle/CSLStyleUtilsTest.java, jablib/src/test/java/org/jabref/logic/citationstyle/CitationStyleGeneratorTest.java, jablib/src/test/java/org/jabref/logic/openoffice/oocsltext/CSLFormatUtilsTest.java
Refs #13465 
Closes https://github.com/JabRef/jabref/pull/13564
This reverts commit 7efa8d2802bd4115d4c18d6720598b258a11bea7. …
=> Update CSL Styles

CHANGELOG.md, jablib/src/main/java/org/jabref/logic/openoffice/ReferenceMark.java, jablib/src/test/java/org/jabref/logic/openoffice/ReferenceMarkTest.java
Uses `Pattern.UNICODE_CHARACTER_CLASS` so that `\w` also matches non-ASCII characters (e.g. Cyrillic, Chinese) in citation keys.  
Adds unit tests with Cyrillic keys.
Closes [#<13301>](https://github.com/JabRef/jabref/issues/13301)
* **ReferenceMark.java**  
Compiles both regex patterns with `Pattern.UNICODE_CHARACTER_CLASS`, allowing Unicode citation keys.
* **ReferenceMarkTest.java**  
Adds two test cases (`Ты2025`, `Я2025`) to verify parsing of Cyrillic keys.
* Manual verification in LibreOffice Writer confirms bibliography generation now works with non-Latin keys.
1. Build & launch JabRef from this branch
2. In JabRef, create a new library containing:
```bibtex
@Article{Ты2025,
author = {Ты},
title  = {You},
year   = {2025},
}
@Article{Я2025},
author = {Я},
title  = {I},
year   = …
```
=> #13301 Fix/unicode reference marks

CONTRIBUTING.md
Closes #13586
In the pull request process for CONTRIBUTING.md, the steps previously linked to high-level documentation. Needed to be updated to architecture and components and its corresponding link.
To test this feature, check if the link to leads to the the architecture and components devdocs page when reviewing the 'Pull Request Process' section on CONTRIBUTING.md. Note: While I did see the mention for the .md link, I used .html since CONTRIBUTING.md is primarily viewed on Github. Users clicking on .md link would receive a 404 error. This link format matches other documentation links in the same file. If any changes are needed, or if there any issues due to this I am welcome to change it accordingly. 
Users should see the above screenshot when clicking the corresponding link. 
- [/] …
=> Updated architecture and components link in CONTRIBUTING.md

CHANGELOG.md, jabgui/src/main/java/org/jabref/gui/JabRefGUI.java
Follow-up to #10044
Fixes https://github.com/JabRef/jabref/issues/12412
1. Be in a network requiring a proxy without (!) a password
2. Confgiure JabRef
3. Use citation relations …
=> Fix setting of proxy without password

CHANGELOG.md, jabgui/src/main/java/org/jabref/gui/entryeditor/citationrelationtab/CitationRelationsTab.java, jabgui/src/main/resources/org/jabref/gui/Dark.css
Closes #13599
Fix dark mode in {} of Citation Relations tab of the entry editor.
1. Switch to dark mode.
2. Open sample entry and go to Citation Relations tab.
3. Click on {} BibTeX source button.
4. Dialog shows content of the BibTeX source in the dark mode.
5. Switch back to the Light theme.
=> Fix dark mode in {} of Citation Relations tab of the entry editor

CHANGELOG.md, jablib/src/main/java/org/jabref/logic/importer/util/ShortDOIService.java
=> Use https for shortDOI

.github/workflows/tests-code.yml, jablib/src/main/java/org/jabref/logic/git/GitHandler.java, jablib/src/test/java/org/jabref/logic/git/SlrGitHandlerTest.java, jablib/src/test/java/org/jabref/logic/git/status/GitStatusCheckerTest.java
Should fix failing `aheadStatusWhenLocalHasNewCommit`
```
> Task :jablib:test
org.jabref.logic.git.status.GitStatusCheckerTest
Test aheadStatusWhenLocalHasNewCommit() FAILED
org.junit.platform.commons.JUnitException: Failed to close extension context
Caused by: java.io.IOException: Failed to delete temp directory C:UsersRUNNER~1AppDataLocalTempjunit-3955357767749560680. The following paths could not be deleted (see suppressed exceptions for details): <root>, remote.git, remote.gitobjects, remote.gitobjectspack, remote.gitobjectspackpack-ecbf2dd4bbf508163d7476aaef9cafd6984af163.pack
```
- [/] Manually tested changed …
=> One more Git close

jablib/src/main/java/org/jabref/logic/bibtex/comparator/BibDatabaseDiff.java, jablib/src/main/java/org/jabref/logic/database/DuplicateCheck.java, jablib/src/main/java/org/jabref/model/strings/StringUtil.java, jablib/src/test/java/org/jabref/logic/database/DuplicateCheckTest.java, jablib/src/test/java/org/jabref/model/strings/StringUtilTest.java
`compareEntriesStrictly` did not take all "properties" of a BibEntry into account
=> Include entry type and comment comparison in compareEntriesStrictly

.github/ghprcomment.yml
I just encountered that I cannot use `gh co`. I think, this should be also put as argument to the contributors.
```bash
koppor@DESKTOP-KAK953S MINGW64 /c/git-repositories/jabref (update-gradle)
$ gh co 13553
remote: Enumerating objects: 374, done.
remote: Counting objects: 100% (170/170), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 374 (delta 162), reused 151 (delta 151), pack-reused 204 (from 3)
Receiving objects: 100% (374/374), 74.55 KiB | 641.00 KiB/s, done.
Resolving deltas: 100% (185/185), completed with 45 local objects.
From github.com:JabRef/jabref
! [rejected]              refs/pull/13553/head -> fix-for-issue-12995  (non-fast-forward)
failed to run git: exit status 1
```
- [/] Change in `CHANGELOG.md` described in a way that is understandable for the …
=> Refine description for force-push

.github/workflows/binaries.yml, .github/workflows/publish.yml, .github/workflows/run-openrewrite.yml, .github/workflows/tests-code-fetchers.yml, .github/workflows/tests-code.yml
Risen by https://github.com/JabRef/jabref/pull/13584#issuecomment-3220212832
While we experimented with different VMs (refs https://github.com/adoptium/adoptium-support/issues/1271#issuecomment-3155899373), we switched to zulu - and then to correto.
This PR sould make it consistent.
- [.] I manually tested my changes in running JabRef (always required)
- [.] I added JUnit tests for changes (if applicable)
- [.] I added screenshots in the PR description (if change is visible to the user)
- [.] I described the change in `CHANGELOG.md` in a way that is understandable for the average user (if change is visible to the user)
- [.] I checked the [user documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at …
=> Switch from zulu to corretto

jabgui/src/main/java/org/jabref/gui/walkthrough/WalkthroughAction.java, jabgui/src/main/java/org/jabref/gui/walkthrough/WalkthroughOverlay.java, jabgui/src/main/java/org/jabref/gui/walkthrough/WalkthroughRenderer.java, jabgui/src/main/java/org/jabref/gui/walkthrough/WindowOverlay.java, jabgui/src/main/java/org/jabref/gui/walkthrough/declarative/NodeResolver.java, jabgui/src/main/java/org/jabref/gui/walkthrough/effects/Spotlight.java, jabgui/src/main/java/org/jabref/gui/walkthrough/utils/WalkthroughResolver.java, jabgui/src/main/java/org/jabref/gui/walkthrough/utils/WalkthroughReverter.java, jabgui/src/main/java/org/jabref/gui/welcome/WelcomeTab.java, jabgui/src/main/java/org/jabref/gui/welcome/components/QuickSettings.java, jabgui/src/main/java/org/jabref/gui/welcome/components/Walkthroughs.java, jabgui/src/main/resources/org/jabref/gui/Base.css, jabgui/src/main/resources/org/jabref/gui/Dark.css, jablib/src/main/resources/l10n/JabRef_en.properties
Closes https://github.com/Yubo-Cao/jabref/issues/6
This PR fixes the following error:
1. IllegalStateException in search walkthrough
2. IndexOutOfBounds and cannot close database during DialogService.showAndWait in the add group walkthrough
1. The Search walkthrough should work properly even if multiple library tab is open
2. The Add Group walkthrough should be more robust to unwanted user interaction. Specifically, you may launch the add group walkthrough and:
a. Click on other group in the entry tab during the walkthrough without leading to error
b. Close the add group dialog in the middle without leading to error
- [/] I described the change in …
=> Walkthrough additions

.github/workflows/tests-code.yml, .jbang/JabLsLauncher.java, docs/decisions/0048-jbang-script-modification-for-testing-in-ci.md
JBang checks should run on PRs, too.
1. Base a PR on this one and see if it works.
=> Refine JBang check

.github/workflows/publish.yml, .github/workflows/tests-code.yml
- Follow-up to https://github.com/JabRef/jabref/pull/13765: Refine tests
- Follow-up to https://github.com/JabRef/jabref/pull/13584 - to trigger SNAPSHOT update if interface changes
Merge into main and update something in jablib in a PR and then merge. See that SNAPSHOT will get updated :)
AKA code-and-fix
- [/] I checked the [user documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at …
=> Publish SNAPSHOT on jablib change

CHANGELOG.md, jabgui/src/main/java/org/jabref/gui/slr/StartNewStudyAction.java, jablib/src/main/java/org/jabref/logic/git/GitHandler.java
Closes #13773 
This PR fixes a regression where the `GitHandler.pullOnCurrentBranch()` method was modified to support remote repositories. However, the same method is also used in the SLR module for local-only study repositories, which have no remote set up by default.
To fix this, we reverted to the original behavior where the method attempts to pull from a remote (if configured), but silently ignores errors when no remote is present. This preserves compatibility with local-only workflows (like the SLR module).
- [/] I …
=> Restore local-only Git behavior for SLR to fix repository initialization error

.github/workflows/on-pr-changes-requested.yml, .github/workflows/on-pr-opened-updated.yml
We more and more make use of the label [status: changes-required](https://github.com/JabRef/jabref/issues?q=sort%3Aupdated-desc%20is%3Apr%20is%3Aopen%20label%3A%22status%3A%20changes-required%22)
For each PR with the label, we need to check now and then if the label is still valid.
With the label removed, we "only" need to check if the changes were really adressed.
GitHub itself does not handle the whole status properly: https://github.com/orgs/community/discussions/17875
Work with PRs :)
- [/] I described the change in `CHANGELOG.md` in a way that is understandable for the average …
=> Auto add and remove of "status: changes-required" label

CHANGELOG.md, jabgui/src/main/java/org/jabref/gui/importer/ImportEntriesViewModel.java
Closes #13015 
Reformats the BibTeX shown in the Import dialog’s “Show BibTeX source” preview to JabRef’s canonical style. The incoming string is parsed into a `BibEntry` and rendered via `BibEntryWriter` with `reformat=true`; if parsing fails, the raw string is shown unchanged. This makes the preview readable and consistent with JabRef’s formatting guidelines.
1.Open JabRef
2.Create new library
3.Open Firefox
4.Ensure that JabRef plugin is installed
5.Navigate to https://learning.oreilly.com/library/view/infrastructure-as-code/9781098150341/
6.Click on "Import references..."
7.See Popup
8.Select "Show BibTeX source"
9.See the formatting
Before : 
After : 
=> Reformat BibTex in Show BibTex Source

.github/workflows/tests-code.yml
Follow-up to https://github.com/JabRef/jabref/pull/13765 to exclude non-source Java files
Risen by https://github.com/JabRef/jabref/pull/13490
Merge into a PR modify `jablib` and there some `module-info` file
- [/] I checked the [user documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request …
=> [JBang] Fix files matched

CHANGELOG.md, jabgui/src/main/java/org/jabref/gui/edit/automaticfiededitor/AbstractAutomaticFieldEditorTabView.java, jabgui/src/main/java/org/jabref/gui/edit/automaticfiededitor/AutomaticFieldEditorDialog.java, jabgui/src/main/java/org/jabref/gui/edit/automaticfiededitor/AutomaticFieldEditorViewModel.java, jabgui/src/main/resources/org/jabref/gui/Base.css, jabgui/src/main/resources/org/jabref/gui/edit/automaticfiededitor/AutomaticFieldEditorDialog.fxml, jabgui/src/main/resources/org/jabref/gui/edit/automaticfiededitor/copyormovecontent/CopyOrMoveFieldContentTab.fxml, jabgui/src/main/resources/org/jabref/gui/edit/automaticfiededitor/editfieldcontent/EditFieldContentTab.fxml, jabgui/src/main/resources/org/jabref/gui/edit/automaticfiededitor/renamefield/RenameFieldTab.fxml
- **fix: Update the UI for the automatic field editor**
- **docs: Update CHANGELOG.md**
Closes https://github.com/JabRef/jabref-issue-melting-pot/issues/780
1. Open Example Library
2. Select some entries
3. Select Edit > Automatic Field Editor
=> Remove unnecessary spacing and margin in the AutomaticFieldEditor

jablib/src/test/java/org/jabref/logic/cleanup/RenamePdfCleanupTest.java
Closes N/A
Fix the rename PDF test. Run the test to test.
=> fix: Fix the rename test [windows]

CHANGELOG.md, jabgui/src/main/java/org/jabref/gui/LibraryTab.java, jabgui/src/main/java/org/jabref/gui/frame/JabRefFrame.java
Closes #11428
This PR ensures that the search bar's auto-completion is correctly initialized as soon as a database is opened, without requiring the user to switch tabs. The auto-completer is now updated immediately after the real database context is loaded, improving the user experience and resolving the issue where auto-completion was unavailable until a tab switch.
1. **Launch JabRef.**
2. Go to **File → Open library…** and open `jablib/src/main/resources/Chocolate.bib`.
3. Wait until the Chocolate tab finishes loading (spinner disappears).
4. Click the **Global Search** bar (top toolbar) and type `s` or `sm`.
**Before**
No suggestions appear at this step.
**After**
Auto-completion popup appears immediately.
---
=> Initialize search bar auto-completion with real database context (no tab switch needed)

jabgui/src/main/resources/org/jabref/gui/Base.css
Closes N/A
Open JabRef and tweak font size. Now the icon in toolbar works properly under all sort of font size.
default:
13pt:
10pt:
Would greatly appreciate testing from other platforms. The screenshot above is obtained from a Windows 25H2 machine.
=> fix: Improper icon sizing with respect to font size

CHANGELOG.md, jabgui/src/main/java/org/jabref/gui/search/GlobalSearchResultDialog.java
Closes https://github.com/JabRef/jabref/issues/13840
I could not get the "Just move the window to the back" thing working. Either the whole application was moved to background or nothing happened. Tried various things
Have library with entries
Open global search dialog
click on pin to keep on top
double click on entry 
=> window stays open
- [x I checked the [user documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request updating file(s) in <https://github.com/JabRef/user-documentation/tree/main/en>.
=> Keep global search bar open when  keep on top pin is selected

jablib/src/main/java/org/jabref/logic/importer/ParserResult.java, jablib/src/main/java/org/jabref/logic/importer/fileformat/BibtexParser.java, jablib/src/main/java/org/jabref/logic/integrity/IntegrityCheckResultErrorFormatWriter.java, jablib/src/main/java/org/jabref/model/entry/field/Field.java, jabls/build.gradle.kts, jabls/src/main/java/module-info.java, jabls/src/main/java/org/jabref/languageserver/util/LspConsistencyCheck.java, jabls/src/main/java/org/jabref/languageserver/util/LspDiagnosticBuilder.java, jabls/src/main/java/org/jabref/languageserver/util/LspDiagnosticHandler.java, jabls/src/main/java/org/jabref/languageserver/util/LspIntegrityCheck.java
Closes https://github.com/palukku/jabref/issues/42 & Closes https://github.com/palukku/jabref/issues/45 & Closes https://github.com/palukku/jabref/issues/50
In #13746 the ranges of the fields and entries it self got added now the lsp utilizes these ranges instead of simple string matching.
Also aliases are now handled so if there the error occurs on an alias field the alias is also correctly detected.
- [/] I checked the [user documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I …
=> LSP Refactor to use ranges instead of string matching

CHANGELOG.md, jabgui/src/main/java/org/jabref/gui/JabRefGuiStateManager.java, jabgui/src/main/java/org/jabref/gui/LibraryTab.java, jabgui/src/main/java/org/jabref/gui/NavigationHistory.java, jabgui/src/main/java/org/jabref/gui/StateManager.java, jabgui/src/main/java/org/jabref/gui/actions/StandardActions.java, jabgui/src/main/java/org/jabref/gui/frame/JabRefFrame.java, jabgui/src/main/java/org/jabref/gui/frame/MainToolBar.java, jabgui/src/main/java/org/jabref/gui/keyboard/KeyBinding.java, jablib/src/main/resources/l10n/JabRef_en.properties
Closes https://github.com/JabRef/jabref/issues/6352
**This brings back an "improved" (per-tab) version of chronological navigation across entries that existed in JabRef 4.x.**
1. Start JabRef
2. Open Chocolate.bib
3. Click (or double-click to open the entry editor) on an entry
4. Click on another entry (the "Back" navigation button should now be available)
5. Repeat step 4 a couple of times
6. Press the "Back" navigation button any number of times till valid (the "Forward" navigation button should now be available)
7. Press the "Forward" navigation button any number of times as valid
8. Play with permutations of step 6 and 7 and check if a) the order is correct b) the entry editor correctly reflects the entry that is navigated to.
9. Open another non-empty library and check steps 3-8, …
=> Chronological navigation in libraries

config/IntelliJ Code Style.xml
Follow-up to [`c48262f` (#13874)](https://github.com/JabRef/jabref/pull/13874/commits/c48262f789f7d59329a67fd611890186efc2b407)
Reason: https://github.com/JabRef/jabref/pull/13885#pullrequestreview-3221145441
- Revert Elvis operator reformatting
- Ignore JBang files
- [/] I checked the [user documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at …
=> Improve IntelliJ settings

jabgui/src/main/java/org/jabref/gui/edit/automaticfiededitor/MoveFieldValueAction.java, jabgui/src/main/java/org/jabref/gui/mergeentries/threewaymerge/FieldRowViewModel.java, jabgui/src/main/java/org/jabref/gui/mergeentries/threewaymerge/cell/HeaderCell.java, jabgui/src/main/java/org/jabref/gui/mergeentries/threewaymerge/cell/sidebuttons/ToggleMergeUnmergeButton.java, jabgui/src/main/java/org/jabref/gui/mergeentries/threewaymerge/fieldsmerger/CommentMerger.java, jabgui/src/main/java/org/jabref/gui/mergeentries/threewaymerge/fieldsmerger/FieldMerger.java, jabgui/src/main/java/org/jabref/gui/mergeentries/threewaymerge/fieldsmerger/FileMerger.java, jabgui/src/main/java/org/jabref/gui/mergeentries/threewaymerge/fieldsmerger/GroupMerger.java, jabgui/src/main/java/org/jabref/gui/mergeentries/threewaymerge/fieldsmerger/KeywordMerger.java, jablib/src/main/java/org/jabref/logic/layout/format/HTMLChars.java, jablib/src/main/java/org/jabref/model/entry/identifier/ArXivIdentifier.java, jablib/src/main/java/org/jabref/model/entry/identifier/EprintIdentifier.java, jablib/src/main/java/org/jabref/model/strings/StringUtil.java, jablib/src/test/java/org/jabref/logic/importer/fetcher/CiteSeerTest.java
Preparation for https://github.com/JabRef/jabref/pull/13885
=> Fix JavaDoc

.github/workflows/binaries.yml
Triggered by https://github.com/JabRef/jabref/pull/13901
Binaries take a while for creating - users should try out on their system. 
Assumption: In most of the cases, there is no intervention of the developer needed before the issue raiser should try out.
Therefore, the idea is to add a message to the issue if there is a binary.
1. Merge :)
2. Create  PR referencing an issue
3. Add: 'dev: binaries`
4. wait
5. See the co,ment on the issue
- [/] I …
=> Add comment on issue on binary

jabgui/src/main/resources/tinylog.properties
On CachyOS, Gnome, I get > 10 messages on start
```
2025-09-14 17:42:22 [JavaFX Application Thread] org.freedesktop.dbus.connections.transports.TransportBuilder.build()
INFO: Using transport dbus-java-transport-native-unixsocket to connect to unix:path=/run/user/1000/bus
```
With this PR, they are gone.
Maybe they are a hint that we open the key manager too often? (Wrong lifecycle?)
Start JabRef on Gnome ^^
- [/] I checked the [user …
=> Do not show transport info messages

.github/workflows/on-pr-opened-updated.yml
Idea from https://github.com/JabRef/jabref/pull/13935#issuecomment-3309410981
NA
=> Restrict remove-label changes required action to internal PRs

.github/workflows/on-pr-opened-updated.yml, .github/workflows/pr-changelog.yml, .github/workflows/pr-comment.yml, .github/workflows/pr-format.yml, .github/workflows/pr-modifications.yml, .github/workflows/tests-code.yml
Follow-up to https://github.com/JabRef/jabref/pull/13850
- Rename workflow file for better grouping
- Factors out CHANGELOG.md modification check, because needs to be checked on both PR comment edit and PR content change
- Fix forgotten upload of PR number
- Add check for not uploading PR number if no PR
- Fix "pr-commentyml" to raise no error on main branch
- [/] I checked the [user documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a …
=> Refine workflows

CHANGELOG.md, jabgui/src/main/java/org/jabref/gui/externalfiles/GitIgnoreFileFilter.java, jabgui/src/test/java/org/jabref/gui/externalfiles/GitIgnoreFileFilterTest.java, jabgui/src/test/java/org/jabref/gui/externalfiles/UnlinkedFilesCrawlerTest.java
Fixes https://discourse.jabref.org/t/set-list-of-ignored-folders-paths/5425/6?u=siedlerchr
=> Fix gitignore not working for subdir patterns

.idea/vcs.xml, CHANGELOG.md, jablib/src/main/java/org/jabref/logic/externalfiles/LinkedFileHandler.java, jablib/src/main/java/org/jabref/logic/util/io/FileUtil.java, jablib/src/test/java/org/jabref/logic/citationkeypattern/BracketedPatternTest.java, jablib/src/test/java/org/jabref/logic/externalfiles/LinkedFileHandlerTest.java, jablib/src/test/java/org/jabref/logic/util/io/FileUtilTest.java
Closes #13735
- Refractored`FileUtil.createFileNameFromPattern` to return an `Optional<String>`, ensuring that empty pattern resolutions correctly result in an empty Optional instead of a "-" string. 
- The `LinkedFileHandler.getSuggestedFileName` method has been updated to handle this new return type.
- The corresponding JUnit tests are also being adapted to reflect these changes.
=> Fix refine check for getSuggestedFileName

.github/workflows/on-pr-opened-updated.yml
Follow-up to https://github.com/JabRef/jabref/pull/13936
The PR runs on `pull_request_target`, thus using the version of the workflow of this repository and also the token of this repository.
The really required fix was the passing of GH_TOKEN
- [/] I checked the [user documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even …
=> Keep label removal

jablib/src/main/java/org/jabref/logic/search/indexing/BibFieldsIndexer.java, jablib/src/test/java/org/jabref/logic/search/indexing/BibFieldsIndexerTest.java
Closes https://github.com/JabRef/jabref/issues/13978#issuecomment-3339978514
- [.] I manually tested my changes in running JabRef (always required)
- [.] I added JUnit tests for changes (if applicable)
- [.] I added screenshots in the PR description (if change is visible to the user)
- [.] I described the change in `CHANGELOG.md` in a way that is understandable for the average user (if change is visible to the user)
- [.] I checked the [user documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request updating file(s) in <https://github.com/JabRef/user-documentation/tree/main/en>.
=> Fix duplicate key error on insertion

CHANGELOG.md, jabgui/src/main/java/org/jabref/gui/preferences/PreferencesSearchHandler.java, jabgui/src/main/java/org/jabref/gui/preferences/PreferencesTab.java, jabgui/src/main/java/org/jabref/gui/preferences/websearch/WebSearchTab.java, jablib/src/main/resources/l10n/JabRef_en.properties
Closes #13929
This PR adds the ability to search for the "Configure API key" option in the Web Search preferences tab
- Updated `WebSearchTab.java` to add search keywords such as "Configure API key", "Custom API key", "api", "api key", "apikey"
- Updated `PreferencesTab.java` to include a default `getSearchKeywords()` method
- Modified `PreferencesSearchHandler.java` to consider keywords when filtering tabs
With this change, users can quickly find the "Configure API key" option by typing relevant search terms in the preferences search bar
1. Open JabRef
2. Go to **Preferences → Web Search** tab
3. In the search bar at the top of Preferences, type any of the following:
- "Configure API key"
- "Custom API key"
- "api"
- "api key"
4. Verify that the Web Search tab is highlighted as a search …
=> Make Web Search 'Configure API key' searchable in preferences #13929

.github/workflows/tests-code.yml
Follow-up to https://github.com/JabRef/jabref/pull/13933
Sometimes, JBang does not work locally - this adds some kind of test
Check workflow output
- [/] I checked the [user documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request updating file(s) in …
=> Add more JBang tests

CHANGELOG.md, jablib/src/main/java/org/jabref/logic/bibtex/FieldWriter.java, jablib/src/test/java/org/jabref/logic/bibtex/FieldWriterTest.java
Closes #12605 
Updated the `org.jabref.logic.bibtex.FieldWriter#checkBraces` method with more information written in error message and added a method that checks whether a character is escaped.
1. Open JabRef
2. Create empty library
3. Click "Add entry"
4. Enter D\{"u}sseldorf in the author field
5. The unmatched bracket is shown between `*`.
=> Improved BibTeX brace check with more information in error message

jabkit/src/test/java/org/jabref/cli/ArgumentProcessorTest.java
Closes #13709
Fixed the test `org.jabref.cli.ArgumentProcessorTest#checkConsistency` by replacing "\r\n" with "\n" in the test output and added fail message.
Run the test `org.jabref.cli.ArgumentProcessorTest#checkConsistency`, which should pass.
=> Fixed consistency check test

gradle/wrapper/gradle-wrapper.properties, gradlew, gradlew.bat
Update Gradle Wrapper from 9.3.0-jabref-1 to 9.1.0.
Read the release notes: https://docs.gradle.org/9.1.0/release-notes.html
---
- Gradle release: `9.1.0`
- Distribution (-bin) zip checksum: `a17ddd85a26b6a7f5ddb71ff8b05fc5104c0202c6e64782429790c933686c806`
- Wrapper JAR Checksum: `76805e32c009c0cf0dd5d206bddc9fb22ea42e84db904b764f3047de095493f3`
---
<details>
<br /> …
=> Update Gradle Wrapper from 9.3.0-jabref-1 to 9.1.0
